### ISSUE TITLE
Remote filter: emails not visible when set to be left on server

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#1]
**Originally by _AlexC_ on 2010-03-03 08:41:45 +0100**

___
I use a remote filter which sets matching emails to "Don't download" and with 2.6 what happens is that they are not shown in the download pre-selection window so they stay on the server unnoticed.

**Comment by tboeckel** [comment]
**Originally on 2010-03-03 08:56:18 +0100**

___
This has been fixed already in the 2.7 nightly builds. Please check again with that version if you like.

**Comment by jens-maus** [comment]
**Originally on 2010-08-26 11:39:50 +0200**

___
reopened due to upcoming merge on 2.6p1 branch.

**Comment by tboeckel** [comment]
**Originally on 2010-08-26 14:45:39 +0200**

___
In (8710eb6):
 * YAM_TR.c: the "avoid duplicates" option cleared too many flags which caused
  mails not to be displayed in the preselection list. This closes #1.
