### ISSUE TITLE
When printing e-mails a list of attachments is also printed

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#100]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2010-03-04 22:00:25 +0100**

___
It would be great and helpfull to have the list of attachments to an e-mail also printed when printing an e-mail. This way one knows on a later moment what the e-mail had for an attachment.

**Comment by tboeckel** [comment]
**Originally on 2013-07-15 08:17:36 +0200**

___
In (a9f6ef7):
 * YAM_MA.c, YAM_RE.c: printing a mail will now include a list of attachments. Additionally the printout will no longer contain a plain copy of all header lines, but a stripped down version of subject sender, receiver and date. This closes #100.

**Comment by tboeckel** [comment]
**Originally on 2013-07-15 08:18:15 +0200**

___
**Release Note:**
Printing a mail will now include a list of attachments. Additionally the printout will no longer contain a plain copy of all header lines, but a stripped down version of subject sender, receiver and date.
