### ISSUE TITLE
Support numpad delete

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#101]
**Originally by _mario@cattaneo.de_ on 2010-03-04 22:24:21 +0100**

___
As this probabably is an enhancement and not really a bug I file it here.

My PC keyboard has no "entf"-key besides the one on the numpad. So it would be nice, if together with the DELTE-key that one would be supported too throughout YAM. Thanks.

**Comment by tboeckel** [comment]
**Originally on 2010-03-04 22:24:56 +0100**

___
Perhaps you could use a tool like MMKeyboard to map "numericpad ," to "delete"? Or better file a support request for keyboards like yours to handle the numeric pad Delete key like a normal Delete key. That would automatically fix *all* applications and not just YAM.

**Comment by jens-maus** [comment]
**Originally by _padrino_ on 2010-03-04 22:25:42 +0100**

___
Well, there are no other apps but YAM to cause this problem, at least now that I know of. So for me, YAM is the exception to the rule.

**Comment by tboeckel** [comment]
**Originally on 2010-03-04 22:26:08 +0100**

___
Try SimpleMail. It uses exactly the same mechanism to delete mails like YAM does. The only difference is the hotkey. YAM uses "-capslock del" and SimpleMail uses "delete", hence the only difference it that YAM ignores the capslock key.

**Comment by tboeckel** [comment]
**Originally on 2010-09-30 11:54:04 +0200**

___
After lots of thinking I will close this ticket. It is not YAM's task to support certain missing keyboard features by workarounds. Such stuff should be handled at system level to let all applications benefit, not just YAM alone.
