### ISSUE TITLE
"Un-spam" mail when d&d'ed out of spam-folder

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#103]
**Originally by _mario@cattaneo.de_ on 2010-03-04 22:29:49 +0100**

___
As a mail is marked as SPAM when dropped into the SPAM-folder it would make sense to set it to "no SPAM" when it is dragged out of the SPAM-folder, IMHO.

BTW, the same holds for "moving" a mail, using the contextmenu, I think.

**Comment by jens-maus** [comment]
**Originally on 2013-01-14 23:47:57 +0100**

___
care should be taken not to unspam a mail when dragged into a trash folder.

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 07:47:20 +0200**

___
In (6873c83):
 * YAM_MA.c: mails dragged out of the spam folder will now be marked as non-spam in case the "mark on move" option is enabled. This closes #103.

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 11:44:40 +0200**

___
**Release Note:**
Mails dragged out of the spam folder will now be marked as non-spam in case the "mark on move" option is enabled.
