### ISSUE TITLE
Add filter action to recognize as SPAM

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#105]
**Originally by _alexandre@balaban.fr_ on 2010-03-04 22:33:06 +0100**

___
It would be neat to be able to create filter which action would be 'recognize as SPAM'. This action would then be similar in effect than manualy clicking on 'SPAM' button in the toolbar, it would just be automatic. Why ? Because the SPAM filter integrate in YAM seems to be based only on keywords in the subject and contains but not on other header fields, for example Sender or reply-to. I have many SPAMs that I can know they are SPAM only by looking at that headers but the current SPAM filter fails to recognize them as such because message contents is different from time to time, having that option I would be able to setup it to automatically recognize new SPAM from several known sources...

**Comment by tboeckel** [comment]
**Originally on 2010-03-04 22:33:48 +0100**

___
If you have set up a custom filter which recognizes a mail as spam by just checking some headers, then why don't you let that filter move the mail to the spam folder? As far as I understand this request this is what you want. The moved mail will be added to the spam recognition database automatically, unless you configured YAM not to do that automatically.

**Comment by jens-maus** [comment]
**Originally by _abalabanb_ on 2010-03-04 22:34:30 +0100**

___
Yes you are right, if "moving to SPAM folder" also adds the mail to the spam recognition database then it would do the trick and fulfill my request. Anyway in the end it would be great if the spam filter would also analyze headers such as the from, reply-to etc. not only mail object and contents.

**Comment by jens-maus** [comment]
**Originally by _amigaphil@users.sourceforge.net_ on 2010-03-04 22:35:53 +0100**

___
Below is a quote from SpamFryer.yam.readme. Is this what you are looking for ? (A new version of SpamFryer for YAM might appear soon ;-) )

If you want SpamFryer.yam to automatically check all new mails, then start YAM (this example assumes version 2.5), open the Settings/Configuration menu (or press the Right Amiga key and the asterisk in the top right corner of the numeric pad at the same time), click on 'Scripts' in the left column and select the line marked 'After getting mail' in the 'Action (Name)' column that appears under the heading 'Scripts settings'. Name will then be ghosted; ensure that the cycle gadget alongside says 'ARexx' not 'AmigaDOS' and enter:

```
YAM:Rexx/SpamFryer.yam Incoming QUIET
```

on the following line, by the caption 'Script'. Make sure that the two checkboxes below are both ticked:

```
[v] Open console window
[v] Wait for termination
```

**Comment by jens-maus** [comment]
**Originally on 2010-03-08 14:22:24 +0100**

___
Yes, moving the mail to the SPAM folder should add it to the spam database as well. So this request should already be fullfilled AFAICS. Therefore I flag that report as "invalid"
