### ISSUE TITLE
ARexx - MAILUPDATE

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#109]
**Originally by _AmigaPhil@scarlet.be_ on 2010-03-04 22:52:05 +0100**

___
After issuing a MAILUPDATE command to refresh a folder index, the N (New) status mails might have is gone.

Shouldn't it be worth to make MAILUPDATE to preserve that N status ? Or add a new 'KEEPNEW' switch for that ?

**Comment by tboeckel** [comment]
**Originally on 2010-03-04 22:53:37 +0100**

___
This might interfere with the "Mark new mail as unread" startup option. I will see what I can do about that. Perhaps the function should distinguish between startup and later use.

**Comment by jens-maus** [comment]
**Originally by _amigaphil_ on 2010-03-04 22:54:22 +0100**

___
I've uploaded a script for testing in the support tracker list.

#2912954 - "Import" Arexx scripts - testing request https://sourceforge.net/tracker/?func=detail&aid=2912954&group_id=13560&atid=213560

**Comment by jens-maus** [comment]
**Originally by _amigaphil_ on 2010-03-04 22:54:59 +0100**

___
This would be no more needed if the following 2 feature requests are
accepted:

#2860257 (Allows MAILIMPORT to return FILENAMEs)
#2928409 (Allows MAILSTATUS to accept FILENAME as input)

**Comment by jens-maus** [comment]
**Originally on 2013-06-30 20:52:16 +0200**

___
After having tested the issue again with YAM 2.8 it seems that ticket is not valid anymore since many mail status related things have been changed in 2.8 including this matter. So please retest with YAM 2.8+ and reopen if the issue is still not fixed properly.
