### ISSUE TITLE
Recent changes to attachment/part-name handling produces unusable names

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#119]
**Originally by _mario@cattaneo.de_ on 2010-03-05 15:55:48 +0100**

___
With recent YAM, when I view parts of a mail I only get
- RAW format
- Part.1
- Part.2
- ...

In the past the "Parts" where meaningfull and contained e.g. name.html if there was an HTML-page in the mail...

**Comment by tboeckel** [comment]
**Originally on 2010-03-06 14:25:09 +0100**

___
In (ca9816b):
 * AttachmentRequestWindow.c: added an additional column to display a mail
  part's description. This fixes #119.
