### ISSUE TITLE
Multiple user identity support (similar to Thunderbird)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#121]
**Originally on 2010-03-06 00:18:44 +0100**

___
A multiple user identity functionality should be added to YAM that allows for a single user to specify different source email addresses which are connected to settings like the SMTP, POP3, signatures, etc. of each defined email address. Then, in the write window those identities should be selectable on the front view of the window via a cycle gadget.

All in all that user identity mangement should be largely borrowed from the functionality Thunderbird supports.

**Comment by jens-maus** [comment]
**Originally on 2010-03-06 07:07:51 +0100**

___
(In #27) This will be addressed as soon as the multiple user identity support is implemented.

**Comment by tboeckel** [comment]
**Originally on 2010-12-06 16:02:57 +0100**

___
Removing #27 from the blocking list as there is no limit for the number of mail servers anymore.

**Comment by jens-maus** [comment]
**Originally on 2012-05-09 21:53:50 +0200**

___
feature has been finally implemented in changeset [5894]
