### ISSUE TITLE
Enhance the SPAM filter engine to recognize external SPAM checker

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#128]
**Originally on 2010-03-06 00:38:46 +0100**

___
In Thunderbird, a user can very easily select that the SPAM checker engine should recognize the SPAM status of incoming mails based on commonly known header insertion lines like "X-Spam-Status:" for "SpamAssassin".

YAM should adopt that behaviour in a future version and automatically flag a mail as SPAM or HAM according to that external "trusted" checkers. However, the users should be able to manually select which of the external SPAM engines to trust...

**Comment by tboeckel** [comment]
**Originally on 2012-07-10 11:41:57 +0200**

___
In (0a1c39a):
 * YAM_COg.c, YAM_FI.c: implemented a filter import from Thunderbird's .sfd files. This import will try to replicate the given filters as close as possible using YAM's filtering facilities. Please note that not all features of Thunderbird's filters can be replicated by YAM due to fundamental differences in operation. This closes #128.

**Comment by jens-maus** [comment]
**Originally on 2012-07-10 12:32:59 +0200**

___
Sorry, but IMHO this ticket is not fully fulfilled. We need to have the Spamassassin&SpamCop rules from Thunderbird hardcoded in YAM rather than relying on having the user to import them manually. Thus, I will reopen this ticket as still unresolved. Neverthelesse, the possibility to import a filter form thunderbird is a very good point now.

**Comment by tboeckel** [comment]
**Originally on 2012-07-11 09:40:08 +0200**

___
In (6a4f0b3):
 * YAM_CO.c, YAM_COg.c, YAM_COs.c, YAM_FI.c: implemented the "trust header lines of external filter" feature as known from Thunderbird. This lets the user choose an external filter from an number of installed .sfd files in the resources directory. These files usually define two filters for specific header lines to tell spam and non-spam mails apart. The filters will *not* occur in YAM's own list of filters. This finally closes #128 again.
