### ISSUE TITLE
Random crash while doing search

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#13]
**Originally by _anonymous_ on 2010-03-03 15:47:21 +0100**

___
Hello.

I was doing a search in the main window search gadget. When YAM just crashed. It was doing a layout and crashed in newlib. Sorry but that is all the info I can currently give. GrimReaper needs an editor to customise crashlogs, I have heaps!

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2010-03-03 15:47:58 +0100**

___
**Attachment added:** [`Crashlog_YAM_2009-10-16_00-29-26.txt`](https://yam.ch/attachments/13/Crashlog_YAM_2009-10-16_00-29-26.txt) (38.0 KiB)

**Comment by tboeckel** [comment]
**Originally on 2010-03-03 15:48:47 +0100**

___
Looking at the crashlog it seems you were changing folders while the search
was still in progress. Is that possible?

You set the "group" of this report to "2.5", hence I suppose you are using
YAM2.5. Would you dare to try the nightly build of 2.6 and check if the
problem happens then again?

**Comment by jens-maus** [comment]
**Originally on 2010-03-07 14:31:38 +0100**

___
Does that still happen with YAM 2.6?

**Comment by jens-maus** [comment]
**Originally by _trac-robot_ on 2010-03-22 03:11:57 +0100**

___
This ticket was closed automatically by the system.  It was previously set to a Pending status and hasn't been updated within 14 days.
