### ISSUE TITLE
Typo in german MSG_HELP_MA_BT_FILTER

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#140]
**Originally by _opionline@yahoo.de_ on 2010-03-09 01:02:58 +0100**

___
>> I just checkout the SVN repository and check the latest changes.
>> I saw an old error which i forget to post long time ago.
>> It's in yam/locale/german.ct at MSG_HELP_MA_BT_FILTER:
>> 'sind, nur diese gefilter werden.' should be
>> 'sind, nur diese gefiltert werden.'
>
> Please submit a bug report for that, as usual :)
>
> regards,
> jens

Done!

**Comment by tboeckel** [comment]
**Originally on 2010-03-09 09:20:17 +0100**

___
In (447a25e):
 * locale/german.ct: fixed a typo. This really fixes #140.

**Comment by jens-maus** [comment]
**Originally on 2010-08-26 11:37:11 +0200**

___
reopened due to upcoming merge on 2.6p1 branch.

**Comment by tboeckel** [comment]
**Originally on 2010-08-26 14:07:56 +0200**

___
In (782c010):
 * locale/german.ct: fixed a typo. This really fixes #140.
