### ISSUE TITLE
Double clicks on attachments (gadget in read win) don't if attachmet is highlighted already

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#141]
**Originally by _mario@cattaneo.de_ on 2010-03-09 03:09:27 +0100**

___
If an attachment is selected a double click will not perform the normal "open action", like you expect it from icons on WB. Eg. in an AttachmentRequestWindow this does work (of course)

**Comment by tboeckel** [comment]
**Originally on 2010-03-09 09:29:44 +0100**

___
In (ba2bb7a):
 * AttachmentImage.c: a double click on an already selected attachment icon
  will now correctly invoke the associated command. This fixes #141.
