### ISSUE TITLE
yam 2.6 (MorphOS) freeze when using find on folder with encrypted mails

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#146]
**Originally by _yam.asc@schwarzes.net_ on 2010-03-16 07:53:19 +0100**

___
YAM 2.6 (MorphOS) freezes when using find (message body) on folder 
with include encrypted mails. The freeze occurs shortly after yam is asking
for the passphrase. But it is not a pgp issue, without find, it is possible to 
decrypt and show an encrypted mail. This bug will also not occour with YAM 2.5.

**Comment by tboeckel** [comment]
**Originally on 2012-05-02 08:55:39 +0200**

___
Please create an ALL+@ALL log using the debug version of YAM. If possible please use YAM 2.7 or YAM 2.8-dev. Since I am not using PGP for mail encryption I am not able to reproduce this issue easily, thus I need your help.

**Comment by tboeckel** [comment]
**Originally on 2012-07-12 08:41:26 +0200**

___
No help from your side => no fix from our side. Sorry.
