### ISSUE TITLE
yam 2.6 installation fails

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#147]
**Originally by _lf2@tim.it_ on 2010-03-19 07:40:49 +0100**

___
Hi,
yam 2.6 installation (YAM26-AmigaOS3.lha) fails due to absence of ".taglines" and ".addressbook" files.
Regards

Luciano

**Comment by jens-maus** [comment]
**Originally on 2010-03-19 07:46:15 +0100**

___
This has already been fixed for the next release (2.7). Until that version is released you can find the two files here for download including a fixed version of the installation script:

http://trac.yam.ch/browser/trunk/doc

**Comment by jens-maus** [comment]
**Originally on 2010-08-26 11:22:06 +0200**

___
As we are about to release 2.6p1 as a patch release, I reopen this problem it to be merged onto the bugfix-2.6 branch. Please close as soon as it is fixed in bugfix-2.6 branch.

**Comment by tboeckel** [comment]
**Originally on 2010-08-26 12:37:47 +0200**

___
In (bec3e95):
 * tools/mkrelease.sh: copied over the mkrelease.sh script from the 2.7 branch.
  This fixes #147.
