### ISSUE TITLE
It's not possible to turn off the Spam filter

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#149]
**Originally by _opionline@yahoo.de_ on 2010-03-25 11:54:12 +0100**

___
Running the latest nightly build
YAM 2.7-dev [OS3/m68k] (25.03.2010)

Step by step to reproduce
(sorry german strings taken from the GUI):

1. run YAM.
2. go to 'Konfig'.
3. go to 'Spam'.
4. uncheck the checkbox 'Spam-Filter aktiv'.
5. click 'Speichern'.
6. you get a requester 'Der Spam-Filter wurde soeben deaktiviert...'
with 3 checkboxes enabled.
7. click 'Benutzen'.

Afterwards the spam filter should be disabled but it's
still enabled and nothing has changed in the .config file
(except the BirthdayCheckTime but thats another issue)

**Comment by tboeckel** [comment]
**Originally on 2010-07-18 21:01:35 +0200**

___
In (44fba20):
 * YAM_COs.c: disabling the spam filter resulted in an inactive filter on the
  first sight, but internally all config items regarding to the spam filter
  were set back to their default values, which in fact means "spam filter
  active". Now the spam filter is correctly disabled. This closes #149.
