### ISSUE TITLE
YAM crashing when dragging mail to another folder...

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#15]
**Originally by _mario@cattaneo.de_ on 2010-03-03 15:51:49 +0100**

___
Sound so familar, somehow... I get crashes (3 in one week) when moving a mail from incomming to another folder by drag and drop. Find GrimReaper Log attached.

**Comment by jens-maus** [comment]
**Originally by _padrino_ on 2010-03-03 15:52:57 +0100**

___
**Attachment added:** [`Crashlog_YAM_2009-12-14_19-55-06.txt`](https://yam.ch/attachments/15/Crashlog_YAM_2009-12-14_19-55-06.txt) (8.2 KiB)
crash on drag and drop - Moved from SF. Original author: padrino

**Comment by tboeckel** [comment]
**Originally on 2010-03-03 15:53:34 +0100**

___
Can you give some more information about the crashes, please? Do you have a separate read window opened or are you using the embedded read pane? Even if it should make no difference at all, does the crash happen for other folders as well or just for the Incoming folder?

**Comment by jens-maus** [comment]
**Originally by _padrino_ on 2010-03-03 15:54:06 +0100**

___
I am using external read windows. As my habbit is only to drag from inbox to a special box I cannot tell about others. And as said, this is random, but repetitive... Could be, that it happens, when the d&d'ed mail is open at that time. Not sure though. Sorry.

**Comment by jens-maus** [comment]
**Originally by _padrino_ on 2010-03-03 15:54:45 +0100**

___
Ok,

today it happened again. External readwin displaying message, moving it to another folder. As usual the same folder, my favourite operation ;) I will attach the log, though it is probably useless. BTW, it's no crash, but a GR YAM does recover from. Are there any debug things I can use and still be able to use YAM nicely? As you can see, this really happens very rarely.

Using YAM 2.6-dev [OS4/PPC] (28.12.2009) Copyright (C) 2000-2009 YAM Open Source Team at the moment...

**Comment by jens-maus** [comment]
**Originally by _padrino_ on 2010-03-03 15:55:18 +0100**

___
**Attachment added:** [`Crashlog_YAM_2010-01-08_12-08-01.txt`](https://yam.ch/attachments/15/Crashlog_YAM_2010-01-08_12-08-01.txt) (32.3 KiB)
another reaper - Moved from SF. Original author: padrino

**Comment by tboeckel** [comment]
**Originally on 2010-03-03 15:55:53 +0100**

___
Can you please provide such a crashing example mail? Maybe it is not a general bug in YAM but very specific to certain mails.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-03-03 22:30:29 +0100**

___
If/when it happens again I will provide the message.

**Comment by jens-maus** [comment]
**Originally on 2010-03-07 14:59:16 +0100**

___
changing status to pending to see if the issue comes up again or not.

**Comment by tboeckel** [comment]
**Originally on 2010-03-09 14:34:23 +0100**

___
Could you please provide an example mail which caused a crash for you? The more I think about it the more I come to the conclusion that this is not a general bug in YAM's way to handle the data but depends on certain mails and their structure.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-03-09 15:31:15 +0100**

___
Where is my comment that it did not happen recently anymore?!

So I have no mail here, to show.

If it happens again, I can provide that mail.

I could provide some mails where I think it happend, but I am not perfectly sure.

**Comment by tboeckel** [comment]
**Originally on 2010-03-09 15:42:09 +0100**

___
Just try yourself with the mails in suspect if you can make YAM crash. If the crash happens then please attach one or two of these mails to this report. Otherwise we'll have to wait until it happens again. Maybe my assumption is simply wrong and the bug is fixed already by pure luck.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-03-09 16:18:49 +0100**

___
Thanks for the info/idea. ;)
I am amazed how easily I could produce the grim reaper.
I'll attach the mail right away.

May theory is this it might be a YAM updating index while moving a mail timing thing, though I don't know if it this possible...

As the GR happends after dragging less then 10 mails (one after another, quite fast), I am confident, that I could reproduce it quite easily.

So if you want me to check it with debug YAM and special debug-settings, just tell and I will give it a try.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-03-09 16:19:19 +0100**

___
**Attachment added:** [`dont_move_me.msg`](https://yam.ch/attachments/15/dont_move_me.msg) (6.8 KiB)
GR on the move

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-03-09 16:20:50 +0100**

___
**Attachment added:** [`Crashlog_YAM_2010-03-09_16-08-51.txt`](https://yam.ch/attachments/15/Crashlog_YAM_2010-03-09_16-08-51.txt) (32.3 KiB)
latest reaper

**Comment by tboeckel** [comment]
**Originally on 2010-03-09 17:05:43 +0100**

___
So far I couldn't make YAM/OS3 crash with this mail, no matter how often I move it from one folder to another one with the read window being open. It seems only OS4 is affected right now.

Did you receive the mail exactly like this or did you modify it before you added it here? I am wondering, because "m@c.d" is definitely no valid email address.

Just to be sure, please create a MIME+MAIL log with either the current or the next nightly build.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-03-09 17:41:46 +0100**

___
Yes, I altered the adresses for privacy reasons.

**Comment by tboeckel** [comment]
**Originally on 2010-03-11 09:17:36 +0100**

___
I don't know if I am too dumb or if the issue simply doesn't happen for me. No matter how often I drag the mail from one folder to another I cannot make YAM crash, neither on OS3 nor on OS4. I tried to reproduce the issue as follows:

1. import the attached mail into an arbitrary folder 
2. open the mail into a separate read window 
3. drag the mail from the main window's mail list to a different folder, the read window will be closed by this 
4. start again at point 2.

Anything different from your way to make YAM crash?

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-03-12 16:50:17 +0100**

___
I can't make it crash atm either. I tried in normal use and also in heavy use with debug. Though a few days/versions ago it seemed easy, at least once. ;)

Your actions seem correct though.

I'll see if this will happen here, in every day use duing the next days/week. If not, maybe it's really gone by accident. Let's see :)

**Comment by jens-maus** [comment]
**Originally on 2010-03-12 17:05:01 +0100**

___
Ok thanks Mario for the information. I will flag that ticket as 'pending' so that after 14 days the tracker will automatically close it. Just reopen it if the problem reappears. Just check your "My Reports" link at the top right corner of this website.

**Comment by jens-maus** [comment]
**Originally by _trac-robot_ on 2010-03-27 03:12:21 +0100**

___
This ticket was closed automatically by the system.  It was previously set to a Pending status and hasn't been updated within 14 days.
