### ISSUE TITLE
Docky: Make Docky icon text changable

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#150]
**Originally by @raziel- on 2010-03-30 23:39:15 +0200**

___
The docky icon text should be able to display the same information as does the APP icon. This way a docky icon could provide all information one needs when having YAM iconified and not wanting another icon lying around on the Workbench

**Comment by tboeckel** [comment]
**Originally on 2010-09-30 09:37:02 +0200**

___
There is no way to provide a custom text to be displayed below the Docky icon. Sorry.
