### ISSUE TITLE
Notification: Add an icon to the Notification requester

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#151]
**Originally by @raziel- on 2010-03-30 23:39:23 +0200**

___
Trivial and shouldn't be high on your list, but it would be nice if some icon (mybe a small version of the check icon) could be attached to the Notification requester after new mail has been fetched.

**Comment by tboeckel** [comment]
**Originally on 2010-09-30 21:21:14 +0200**

___
In (d0a49d4):
 * YAM_TR.c: if the file "Themes/default/notify" exists it will be displayed in
  YAM's AmigaOS4 new mail notification. This closes #151.
