### ISSUE TITLE
grim reaper when trying to download mails

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#155]
**Originally by _Michael.Merkel@gmx.net_ on 2010-04-11 11:37:32 +0200**

___
hi.

using the very latest nightly i get a grim reaper when trying to retrieve mails. grim is attached.

using amigaos4.1upd1.

regards
michael

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-04-11 11:37:51 +0200**

___
**Attachment added:** [`Crashlog_YAM_BETA_2010-04-11_11-34-02.txt`](https://yam.ch/attachments/155/Crashlog_YAM_BETA_2010-04-11_11-34-02.txt) (32.2 KiB)
grim reaper crash log

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-04-11 11:38:44 +0200**

___
i forgot... i can ignore the grim and go on.
but no files are downloaded - opening another ticket for this.

regards
michael

**Comment by tboeckel** [comment]
**Originally on 2010-04-11 12:59:20 +0200**

___
See ticket #156 for the explanation.
