### ISSUE TITLE
currently nightly does not download any mails?

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#156]
**Originally by _Michael.Merkel@gmx.net_ on 2010-04-11 11:42:00 +0200**

___
hi.

unfortunately the last "working" nightly timed out today and i was forced to use the current nightly which has a big "warning" notice in the changelog.

when trying to download messages it just does not work. nothing is downloaded.

(sorry if this is known)

regards[[BR]]michael

**Comment by tboeckel** [comment]
**Originally on 2010-04-11 12:59:39 +0200**

___
You read the big warning, but did you understand it? It says that the current nightly builds are unstable and may not work at all. This is exactly what you noticed right now. And this is a known and even documented fact. So where is the bug?

Sorry for being harsh, but if we already tell about known bugs and crashes there is no reason to tell us again.

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-04-11 20:10:27 +0200**

___
hi thore.

just to answer your question:

 1. the fact that no mails can be downloaded is written in the changelog? so i'm sorry. i have not read that. i read:[[BR]][[BR]]
> 2010-03-16 Thore Böckelmann <tboeckel@gmx.de>
> * Transfer.c, ReceiveMails.c, mui/TransferWindow.c: partly reenabled POP mail downloads. At least the transfer window is opened **and the mails are downloaded**, but the statistics are not yet updated and the received mails are not yet filtered.

[[BR]]my fault that i thought it may be a bug that something mentioned as working does not work. again - sorry :-([[BR]]
 1. the grim reaper is mentioned in the changelog? again i'm sorry. i have  not read that and i thought a reproducible reaper may help.

and why do i fool use that version which is told to be broken:

> 2010-03-15 Jens Langner <Jens.Langner@light-speed.de>
>   WARNING: This is one of several fundamental changes to the internals of YAM. The changes are *not* complete yet and the current state of the changes break existing functionality. For example, with these changes the preselection window will stop working until we have everything finalized. In addition, the SMTP mail sending is also currently not working as well as many other functionality. **So if you need a fully working/stable YAM version stay away from these versions and either downgrade to the official 2.6 version or keep your existing 2.7-dev as long as our work isn't finalized.** You have been warned.

well, guess what, i wanted to do the latter. i did. until today when the latest one stopped working.if you suggest using the last working nightly build it would have been sort of nice to remove the timeout in that one. just my 2ct.

again - sorry that i wanted to report a bug.

regards[[BR]]michael

**Comment by jens-maus** [comment]
**Originally on 2010-04-11 21:07:50 +0200**

___
No we are suggesting to revert to the latest official build instead (2.6) which anyway isn't that different from the current nightly builds. So sorry, but we have to do some large internal changes and thus currently the nightly builds are broken.

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-04-11 21:16:45 +0200**

___
hi damato.

thanks for the answer. i will "downgrade" now as there is no other opinion.

but just to make my point clear: you suggest to either revert to 2.6. OR to keep the latest stable nightly ;-) (the latter is not possible) - so ok. let's go back then (just downloading).

i just was a bit upset that a bug report of a reaper (which by the way is in since several nightly builds) is answered in such an impolite way. "thats not a bug it's a known issue"

regards[[BR]]michael

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-04-11 22:52:12 +0200**

___
Don't worry Michael. I get into the same troubble some time ago.
See also #148.

I hope the mentioned bugs are removed ASAP so testers can use
the nightly builds again.

BTW: i never saw an open source project so much time unusable!

I think for such things svn have the possibility to open branches
and after finalize the big changes merging the branch into the main.

**Comment by jens-maus** [comment]
**Originally on 2010-04-11 23:29:57 +0200**

___
Come on guys, don't be unfair.

We are always trying hard to keep the nightly builds usable. But unstable builds are as the name implies "unstable" per se. These are no beta versions nor versions that are ment to be used daily. And of course we could open SVN branches and work there but this would even take more time from us and hey, we are only 3 people working on YAM. So please calmn down and don't compare YAM with public open source projects like e.g. Thunderbird where you got hundreds of developers. The stable build works perfectly right now and isn't that far away from what we changed in 2.7 already. So please don't make our live even more complicated by forcing us to not work on the trunk. As soon as we have the time we will finalize our changes to the transfer stuff and then people are free to use the nightly builds again.

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-04-12 21:51:38 +0200**

___
hi damato.

> Come on guys, don't be unfair.

sorry. i was not unfair. at least it was not my intention to be so. if you feel like that - i only can say sorry.

> We are always trying hard to keep the nightly builds usable.
> But unstable builds are as the name implies "unstable" per se.

sure. unstable means for me that the build may unexpectedly crash. that's fine. but it crashed actully redproducible on my side so i thought a bugreport would be - at least - welcome. but it wasn't.
instead i got a snippy answer in the sense of "read before you think/write".
actually i did. actually that was the reason i did NOT install the newer ightly builds but kept the old one (like suggested in the very same text i was not able to understand). only when the old nightly timed out (which *imo* should not happen reading the "warning text", i used the never one.

again - sorry if someone felt upset! at least i did.

regards
michael

**Comment by jens-maus** [comment]
**Originally on 2010-04-17 20:54:22 +0200**

___
Ok guys, FYI. I just moved all the highly experimental stuff (new transfer/preselection window) to a separate SVN branch "newtransfer-2.7". So the next upcoming nightly build should hopefully be usable again.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-04-18 21:14:24 +0200**

___
Many thanks for moving the new stuff into a new branch.
I'll check if the nightly builds are working again ASAP.
