### ISSUE TITLE
app.lib complains about V1-issues...

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#158]
**Originally by _mario@cattaneo.de_ on 2010-04-18 16:51:58 +0200**

___
YAM 2.7-dev [OS4/PPC] (18.04.2010) Copyright (C) 2000-2010 YAM Open Source Team

Though the changelog states:

"* YAM.c, DockyIcon.c: fixed the mixed up usage of V2 tags with a V1 interface
    of application.library. The old V1 interface used completely broken tag
    definitions which collided with standard tags like TAG_IGNORE or TAG_MORE.
    This is worked around by trying to obtain the V2 interface first and fall
    back to the V1 interface upon failure. The function calls then must be
    adapted to use the correct tag definitions for the two possible interface
    versions.
"

There still seem to be problems.
If I misundetood the changelog - sorry.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-04-18 16:53:37 +0200**

___
Forgot: Requester poping, saying "App has opened version 2 of interface application, but tried to pass version 1 tag definitions to app.lib"

**Comment by tboeckel** [comment]
**Originally on 2010-04-19 07:53:35 +0200**

___
In (2065c82):
 * DockyIcon.c: registering YAM at application.lib didn't respect the fact that
  even with a new V2 interface the build system's SDK could be slightly out-
  dated and still use the old V1-only tag definitions. This closes #158.
