### ISSUE TITLE
Grim Reaper searching mail bodies

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#160]
**Originally by _mario@cattaneo.de_ on 2010-04-20 16:20:56 +0200**

___
YAM 2.7-dev [OS4/PPC] (20.04.2010) Copyright (C) 2000-2010 YAM Open Source Team

when I search my inbox for a keyword in mailbodies YAM shows me the reaper (find log attached).
Is there a way to log which mail YAM is processing at that very moment, so I could upload that one, too, if needed.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-04-20 16:21:33 +0200**

___
**Attachment added:** [`Crashlog_YAM_alpha_2010-04-20_11-46-21.txt`](https://yam.ch/attachments/160/Crashlog_YAM_alpha_2010-04-20_11-46-21.txt) (30.3 KiB)
GR log when searching mailbodies

**Comment by tboeckel** [comment]
**Originally on 2010-04-20 16:34:57 +0200**

___
A FILTER debug log will include the mail's subject.

**Comment by tboeckel** [comment]
**Originally on 2010-04-21 07:51:12 +0200**

___
In (b21a50f):
 * YAM_RE.c: added missing NULL pointer check for output file. Having no output
  file is a valid situation. This closes #160.
