### ISSUE TITLE
Download status in mail transfer window is broken

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#163]
**Originally by _Mike Steed <72207.463@compuserve.com>_ on 2010-04-26 09:26:35 +0200**

___
The download status display in the mail transfer window broke
in v. 2.6. It worked fine in v. 2.5.

When downloading mail via a 56K dialup connection, the number
of bytes downloaded is a very large negative number, which
increments towards zero during the download. The number of
bytes to be downloaded looks correct. The transfer rate is
impossibly large, in the hundreds of megabytes per second,
though it does decrease some during the download. The running
time looks correct, but the time left is always zero.

Here's a snapshot of the display during one recent mail
retrieval:

-118056627 B of 33.1 KB @ 442.60 MB/s
   00'09" running - 00'00" left

I'm running YAM 2.6 on an A3000 with a 50 MHz 68060, under
OS 3.9.2. As mentioned I'm using a dialup connection, so the
download is relatively slow, leaving plenty of time to see
the bug.

**Comment by jens-maus** [comment]
**Originally by _Mike Steed <72207.463@compuserve.com>_ on 2010-04-30 08:09:43 +0200**

___
More info on this one: I've noticed that the download status display seems to work correctly if I've told YAM to download and then delete the first item in the list of emails. If I've told YAM to just delete it without downloading it (usually the case, due to spam), then the bug appears.

**Comment by tboeckel** [comment]
**Originally on 2010-09-29 08:10:05 +0200**

___
Please check again with the recently released YAM 2.6p1 if this issue is still valid.

**Comment by tboeckel** [comment]
**Originally on 2010-10-07 15:07:31 +0200**

___
@mike steed:

Since you replied to me in private already and confirmed that the issue is still valid with YAM 2.6p1, would you perhaps try YAM 2.7-dev? I have a quite slow Internet connection at home, too, and for me the transfer display is absolutely correct with 2.7.

**Comment by tboeckel** [comment]
**Originally on 2010-10-12 15:34:38 +0200**

___
In (115066b):
 * tcp/pop3.c: don't update the transfer control group while loading the mail
  details for the preselection list. This will output a malformed time since
  the transfer has not been started yet. This closes #163.

**Comment by jens-maus** [comment]
**Originally by _72207.463@compuserve.com_ on 2010-10-13 07:59:33 +0200**

___
I'm not sure if that's the bug or not, since the problem persists even while the mail transfer is in progress, and never appears if the first file in the list is downloaded rather than simply deleted on the server. But whatever it is, it seems to have been fixed in the v. 2.7 development release (as of 9-Oct-10).

**Comment by jens-maus** [comment]
**Originally by _72207.463@compuserve.com_ on 2010-10-13 07:59:35 +0200**

___
-- Sorry, accidentally posted comment 5 twice. --
