### ISSUE TITLE
Localization problems after restart

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#167]
**Originally by _Immo Müller de Vries <immomdv@gmx.de>_ on 2010-06-04 08:09:04 +0200**

___
I am using the german catalogue. Start YAM then restart YAM (Projekt/Neu starten english: Poject/Restart). Click on "Neu" (New). Now the text for "Nachricht" (Message) and "Optionen" (Options) is wrong and also the text in the tab "Optionen" is not correct. If you quit YAM and start it again everything is fine again.
This error occurs also with YAM 2.6

**Comment by jens-maus** [comment]
**Originally on 2010-06-05 14:16:31 +0200**

___
Sorry, I am not able to reproduce this issue here. No matter how often I "restart" YAM with the german catalog the translated text in the write window is always correct. So please check your german catalog and state which OS/machine you use as well as the catalog version you use. And please make sure you are able to reproduce this issue several times. In addition, please check your Locale:Catalogs directory as well as the YAM:Catalogs directory for different catalog versions you might have around.

**Comment by jens-maus** [comment]
**Originally by _Immo Müller de Vries <immomdv@gmx.de>_ on 2010-06-05 23:24:54 +0200**

___
I am using MorphosOS so perhaps the issue is not reproducable with Amiga OS. Maybe someone can test the behaviour of YAM with MorphOS.

I have redone the test with a real clean system (booting directly from the MorphOS CD and using YAM from a freshly extracted YAM archive.

Here is what I did:
I extracted YAM26-MorphOS.lha onto an USB stick and renamed the directory 'german' in YAM 2.6/Catalogs/ to 'deutsch'. Then I moved all files from the directories 'YAM 2.6/Install/Libs/' and 'YAM 2.6/Install/MUI/' to the main directory 'YAM 2.6/' so that YAM can find the necessary libraties and MUI classes.

After that I disabled all partitions to be sure that only the files from the stick are beeing used. I booted from the brandnew MorphOS 2.5 CD and chose 'Preferred Language: Deutsch' and 'Keymap: German Keyboard with 105 keys'.
After the start of Ambient I chose from the menu 'Einstellungen/System' --> 'Locale' and changed 'Land und Sprachen' to 'Deutschland' and klicked on 'Benutzen'.

Now I inserted the stick and started YAM. In the dialogue I chose 'Dauerhaft ignorieren'. Then I clicked on 'Neu' for a new message. In the configuration dialogue I entered 'a', 'b', 'c' and 'd' for name, e-mail address and so on. I clicked on 'Speichern' to save the preferences. Then I clicked again on 'Neu'. The editor opens and everything is fine (the three tabs read 'Nachricht', 'Anhänge' and 'Optionen'. I closed the editor and chose 'Projekt/Neu starten' from the menu to restart YAM. If I now click on 'Neu' to open the editor the text in the tabs is wrong (sometimes there is simply a wrong text and sometimes strange signs appear). Also interesting: If you restart YAM without having opened the editor before, the text in the tabs is correct...

**Comment by tboeckel** [comment]
**Originally on 2010-06-09 15:25:16 +0200**

___
Perhaps you should contact one of the MorphOS developers about this issue. Since neither of us is able to reproduce this issue on any non-MorphOS system and YAM is really doing nothing bad or illegal with its catalogs. The respective code is unchanged since lots of month (or even years). If there would be really something bad then I am sure this would have been noticed much earlier.

**Comment by tboeckel** [comment]
**Originally on 2010-06-09 16:10:56 +0200**

___
Argh! Forgot what I wrote. YAM *IS* doing something illegal. For the write window some static variables are used to keep the tabs' titles and these are initialized only once. This means that after a restart the pointers to the old catalog are used which are no longer valid and hence result in the unreadable strings.

**Comment by tboeckel** [comment]
**Originally on 2010-06-09 16:30:16 +0200**

___
In (46604be):
 * mui/WriteWindow.c: the tabs' title texts and several other static texts were
  initialized on the very first use only. Restarting YAM by choosing "Restart"
  from the project menu closed YAM's catalog and reopened it later. This could
  result in invalid pointers the next time the write window was opened again.
  Now the pointers are initialized every time. We really must get rid of these
  static variables!! This closed #167.

**Comment by jens-maus** [comment]
**Originally on 2010-08-26 11:33:36 +0200**

___
reopened due to upcoming merge on 2.6p1 branch.

**Comment by tboeckel** [comment]
**Originally on 2010-08-26 14:15:35 +0200**

___
In (18c09ad):
 * mui/WriteWindow.c: the tabs' title texts and several other static texts were
  initialized on the very first use only. Restarting YAM by choosing "Restart"
  from the project menu closed YAM's catalog and reopened it later. This could
  result in invalid pointers the next time the write window was opened again.
  Now the pointers are initialized every time. We really must get rid of these
  static variables!! This closes #167.
