### ISSUE TITLE
notification window on os4.1 has no text

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#171]
**Originally by _Michael.Merkel@gmx.net_ on 2010-07-10 13:31:16 +0200**

___
hi.[[BR]]the email notification window of yam (using os4.1's notification system) is simply empty since several builds. don't know if this is a general problem or just on my side.[[BR]]all other programs i use show the notification very well, though.[[BR]][[BR]]using the current nightly build on os4.1upd2[[BR]][[BR]]regards...[[BR]]michael

**Comment by tboeckel** [comment]
**Originally on 2010-07-15 09:21:25 +0200**

___
I just tried the latest nightly build and for me the message "Received 1 new mails!" is displayed correctly by Ringhio.

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-07-15 20:55:33 +0200**

___
**Attachment added:** `Notification_YAM_NOK.jpg` (11.7 KiB)
![Notification_YAM_NOK.jpg](https://yam.ch/attachments/171/Notification_YAM_NOK.jpg)
YAM notification

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-07-15 20:55:52 +0200**

___
**Attachment added:** `NotificationRexx_OK.jpg` (17.3 KiB)
![NotificationRexx_OK.jpg](https://yam.ch/attachments/171/NotificationRexx_OK.jpg)
REXX notification - working fine

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-07-15 20:56:12 +0200**

___
that's weird. is there any setting which can configure the text color or smth? per application?

i attached tweo screenshots. one of my yam notification window and one of the example rexx script provided with the notification system. i have no idea what to do?!



thanks and regards
michael

**Comment by tboeckel** [comment]
**Originally on 2010-07-15 22:54:48 +0200**

___
I just added some debug output to the relevant part of the code. Please try again with the next nightly build and provide a GUI debug log (see http://faq.yam.ch/content/12/54/en/basics-about-yam_s-debugging-facilities.html for more details).

Please provide your version of application.library and RinghioServer. Maybe there was a bug somewhere inbetween which has been fixed in the meantime.

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-07-17 18:04:17 +0200**

___
Replying to thboeckel:
> I just added some debug output to the relevant part of the code. Please try again with the next nightly build and provide a GUI debug log (see http://faq.yam.ch/content/12/54/en/basics-about-yam_s-debugging-facilities.html for more details).
> 
> Please provide your version of application.library and RinghioServer. Maybe there was a bug somewhere inbetween which has been fixed in the meantime.

application.library: application.library 53.10 (13.11.2009)
ringhioserver: Ringhio 53.16 (28.02.2010)

and attached is the log.

thanks and
regards...

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-07-17 18:04:56 +0200**

___
**Attachment added:** [`YAM.debug`](https://yam.ch/attachments/171/YAM.debug) (25.8 KiB)
yam.debug - yam debug version + gui

**Comment by tboeckel** [comment]
**Originally on 2010-07-18 14:14:31 +0200**

___
Fixed in the next nightly build. I was under the wrong assumption that the beta V2 interface was using proper tag values only. But the Notify() function did that for the V1 interface already from V53.7 on, which is required at least anyway.
