### ISSUE TITLE
Rebuild Folder Index issue

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#173]
**Originally by _enzobarba@libero.it_ on 2010-07-17 17:56:48 +0200**

___
Hi,
from some YAM 2.7 nightly build the 'rebuild index' doesn't work.
In YAM 2.6 it works.

to reproduce the issue:
1. select a mail-folder with some mail
2. rightclick -> rebuild index
3. the index will be resetted, but the mails are still there.
(I open yam2.6 stable rel. and I make the same steps to
rebuild index correctly)

I'm on PEG2 G4, MOS 1.4.5 latest ambient beta

**Comment by jens-maus** [comment]
**Originally on 2010-07-17 17:57:59 +0200**

___
what exactly do you mean by "the mails are still there"? What should happen instead? and can you please check if the OS3 version running under MOS works different?

**Comment by tboeckel** [comment]
**Originally on 2010-07-17 18:06:44 +0200**

___
Please provide a FOLDER+MAIL debug log created by the debug version of the next nightly build. See http://faq.yam.ch/content/12/54/en/basics-about-yam_s-debugging-facilities.html for details about YAM's debugging facilities.

Jens, did you change anything concerning the MorphOS builds? We didn't change anything regarding index building or directory scanning. Yet this is the second report about this problem on MorphOS.

**Comment by jens-maus** [comment]
**Originally on 2010-07-17 18:46:04 +0200**

___
Replying to thboeckel:
 
> Jens, did you change anything concerning the MorphOS builds? We didn't change anything regarding index building or directory scanning. Yet this is the second report about this problem on MorphOS.

I only changed the MOS SDK to the very latest version available when it was released for MOS 2.5. Perhaps this might be the reason why things are working different now. As the author is runing MOS 1.4.5 I am curious if Christoph might run also 1.4.5. So this would then point out an incompatibility of the MOS 2.5 SDK to older MOS versions.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2010-07-17 19:17:28 +0200**

___
Replying to thboeckel:
> Please provide a FOLDER+MAIL debug log created by the debug version of the next nightly build. See http://faq.yam.ch/content/12/54/en/basics-about-yam_s-debugging-facilities.html for details about YAM's debugging facilities.

I'll try to do that debuglogs;
at present I made some tests:
1. the OS3 version freeze during startup on my Peg2/MOS1.4.5
2. i'm trying the latest yam2.7-nightly DEBUG version.. and it works

so:
--YAM2.7mos latest nightly build -> "rebuild index" get 0 (even on folders with many mails in)
--YAM2.7mos latest nightly build DEBUG ver. -> "rebuild index" return the exact number of mails in the folder

**Comment by tboeckel** [comment]
**Originally on 2010-07-18 13:47:47 +0200**

___
Replying to damato:

> I only changed the MOS SDK to the very latest version available when it was
> released for MOS 2.5. Perhaps this might be the reason why things are 
> working different now. As the author is runing MOS 1.4.5 I am curious if
> Christoph might run also 1.4.5. So this would then point out an
> incompatibility of the MOS 2.5 SDK to older MOS versions.

According to one of his last private mails Christoph is using MOS 2.4 and 2.5.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2010-07-19 09:16:14 +0200**

___
Replying to [#173 enzobarba@…]:
> Hi,
> from some YAM 2.7 nightly build the 'rebuild index' doesn't work.
> In YAM 2.6 it works.
> 
> to reproduce the issue:
> 1. select a mail-folder with some mail
> 2. rightclick -> rebuild index
> 3. the index will be resetted, but the mails are still there.
> (I open yam2.6 stable rel. and I make the same steps to
> rebuild index correctly)
> 
> I'm on PEG2 G4, MOS 1.4.5 latest ambient beta

Hi,

it seems that I have excately the same problem using YAM with MorphOS!

I use MorphOS 2.5 though.

**Comment by tboeckel** [comment]
**Originally on 2010-07-19 11:00:19 +0200**

___
I think I found the bug, but I really wonder why it did not occur with OS3 which also uses the reimplemented function. Please try again with the next nightly build. If the problem still persists, then please reopen this bug.

**Comment by tboeckel** [comment]
**Originally on 2010-07-19 11:00:50 +0200**

___
In (8a1e9ed):
 * extrasrc/ExamineDir.c: the ExamineDir() reimplementation directly returned
  the type value from the ExAll() call instead of converting it to the
  ExamineDir() style. This confused the calling function to ignore files
  which certainly should have been found. This closes #173.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2010-07-21 08:27:19 +0200**

___
Replying to thboeckel:
> In (8a1e9ed):
 * extrasrc/ExamineDir.c: the ExamineDir() reimplementation directly returned
>   the type value from the ExAll() call instead of converting it to the
>   ExamineDir() style. This confused the calling function to ignore files
>   which certainly should have been found. This closes #173.

Hi, I tested the new version from yesterday with this fix but here under MorphOS 2.5 it still doesn't seems to work! Same behavour as before, after an Update index there are always 0 Mails shown in the drawer. It still works correctly with the debug version though, which is: after an Update index the correct number of Mails in a directory are displayed.

**Comment by jens-maus** [comment]
**Originally by _enzobarba@libero.it_ on 2010-07-21 11:46:47 +0200**

___
Replying to rmsyam:
> Hi, I tested the new version from yesterday with this fix but here under MorphOS 2.5 it still doesn't > seems to work! Same behavour as before, after an Update index there are always 0 Mails shown > in the drawer. It still works correctly with the debug version though, which is: after an Update index > the correct number of Mails in a directory are displayed.

same here on my mos1.4.5 and yam latest nightly build

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2010-07-26 07:37:09 +0200**

___
Replying to enzobarba@…:
> Replying to rmsyam:
> > Hi, I tested the new version from yesterday with this fix but here under MorphOS 2.5 it still doesn't > seems to work! Same behavour as before, after an Update index there are always 0 Mails shown > in the drawer. It still works correctly with the debug version though, which is: after an Update index > the correct number of Mails in a directory are displayed.
> 
> same here on my mos1.4.5 and yam latest nightly build

Hi, any news yet to solve this problem/bug?

**Comment by tboeckel** [comment]
**Originally on 2010-07-26 12:49:25 +0200**

___
Maybe yes, maybe no. I just modified some stuff concerning error handling and possible wrong interpretations in certain error situations.

Please try again with the next nightly build. A FOLDER+MAIL+@TAGS log might be interesting in case the scanning operation still fails.

**Comment by jens-maus** [comment]
**Originally by _enzobarba@libero.it_ on 2010-07-27 08:15:57 +0200**

___
the bug is still here, with nightly b. 27072010
on my mos1.4.5
(the debug version works good; production version no. as before)

**Comment by jens-maus** [comment]
**Originally by _enzobarba@libero.it_ on 2010-07-27 08:16:12 +0200**

___
Replying to thboeckel:
> Please try again with the next nightly build. A FOLDER+MAIL+@TAGS log might be interesting in case the scanning operation still fails.

the bug is still here, with nightly b. 27072010
on my mos1.4.5
(the debug version works good; production version no. as before)

**Comment by tboeckel** [comment]
**Originally on 2010-07-27 08:17:33 +0200**

___
Replying to enzobarba@…:
> Replying to thboeckel:
> > Please try again with the next nightly build. A FOLDER+MAIL+@TAGS log might be interesting in case the scanning operation still fails.
> 
> the bug is still here, with nightly b. 27072010
> on my mos1.4.5
> (the debug version works good; production version no. as before)

Then please provide the requested log (FOLDER, MAIL and @TAGS).

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2010-07-27 09:13:18 +0200**

___
**Attachment added:** [`yam.log.zip`](https://yam.ch/attachments/173/yam.log.zip) (14.6 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2010-07-27 09:13:39 +0200**

___
Replying to thboeckel:
> Replying to enzobarba@…:
> > Replying to thboeckel:
> > > Please try again with the next nightly build. A FOLDER+MAIL+@TAGS log might be interesting in case the scanning operation still fails.
> > 
> > the bug is still here, with nightly b. 27072010
> > on my mos1.4.5
> > (the debug version works good; production version no. as before)
>
> Then please provide the requested log (FOLDER, MAIL and @TAGS).

Hi, it still doesn't work neither on MorphOS 2.5 with the normal version but it works with the debug version! I generated a log as you asked above with the debug version.

**Comment by jens-maus** [comment]
**Originally on 2010-07-27 19:54:14 +0200**

___
In (e46c1f5):
 * extrasrc.h, extrasrc/ExamineDir.c, extrasrc/AllocSysObject.c: replaced
  incorrectly used "PPC" defines with the correct "__PPC__" ones. This was
  indeed the reason why the MorphOS compile showed a strange behaviour when
  running the index rescanning after having switched to MOS 2.5 SDK. This
  should finally fix #173.

**Comment by jens-maus** [comment]
**Originally by _enzobarba@libero.it_ on 2010-07-28 07:42:37 +0200**

___
Replying to damato:
> In (e46c1f5):
 * extrasrc.h, extrasrc/ExamineDir.c, extrasrc/AllocSysObject.c: replaced
>   incorrectly used "PPC" defines with the correct "__PPC__" ones. This was
>   indeed the reason why the MorphOS compile showed a strange behaviour when
>   running the index rescanning after having switched to MOS 2.5 SDK. This
>   should finally fix #173.
> 

Yes!
now here it's working.

thanks!
