### ISSUE TITLE
Can't send any mails anymore

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#174]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2010-07-29 15:41:55 +0200**

___
Hi, as of todays nightly build I get the following error:

Couldn't open bsdsocket.library interface required for TCP/IP connections.
Please make sure that you have a compatible and correctly configured
TCP/IP stack installed, and that your network interface is up and running.

Yesterdays and before builds do send the mails without problems!

Please let me know if you need log files and if so which tags...

**Comment by tboeckel** [comment]
**Originally on 2010-07-29 15:46:17 +0200**

___
A NET log would be great.

**Comment by tboeckel** [comment]
**Originally on 2010-07-29 16:21:10 +0200**

___
No need for a log. Should be fixed in the next nightly build.
