### ISSUE TITLE
keyboard navigation no longer working

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#175]
**Originally by _Michael.Merkel@gmx.net_ on 2010-08-02 20:26:46 +0200**

___
hi.

with the current nightly build the keyboard navigation is broken:
the left/right cursor keys jump to the folder tree or to the mail area like before - that seems fine. but then the cursor up/down are not working like expected. they only move the mail text on the right and no longer the tree entry.

in the changelog is written:

> 2010-07-30 Thore Böckelmann <tboeckel@gmx.de>
> ...
> * YAM_MA.c, mui/MainMailListGroup.c: use the NListview objects to set up the left/right key focus feature instead of the NList objects for consistency reasons. In any case the NListview object must become the active object instead of the embedded NList object.

so i'm not sure if there is some new nlist classes missing to make it work again?! or if there is a problem now.

thanks and
regards....
Michael

**Comment by tboeckel** [comment]
**Originally on 2010-08-03 08:27:20 +0200**

___
I don't know if I get your description right. I just installed NList 0.105 again and tried it together with the latest nightly build of YAM. Although the two lists will be highlighted by MUI's additional active frame the keyboard navigation works as expected for me. With left/right I can jump between the folder and the mail list. With up/down I can scroll within these lists. No matter if I use the embedded read pane or a separate read window up/down will scroll the list of mails and not the mail text in the embedded read pane. To scroll the mail text one has to click on the mail text itself or press TAB twice to make the read pane the active object.

Do you expect a different behaviour? If yes, in which respect?

**Comment by tboeckel** [comment]
**Originally on 2010-08-03 08:34:20 +0200**

___
I forgot to say, the "active border" will vanish with the next NList release. The current version does several things wrong in this respect. Furthermore there may be other obstacles you currently cannot verify like I can, because I did some changes to NList which are not yet released.

The problem is that a "list" consists of two objects: the list itself (which just manages all the entries, i.e. the mails) and a surrounding listview which provides the scrollbars and the complete environment. From MUI's POV the listview should be the active object and not the embedded lists, as the listview knows how to handle keyboard input and to which object this input should be forwarded. Unfortunately the current NList's "KeyXXXFocus" feature sets the embedded list as active object. This caused bug #14, which I fixed recently. But this fix is not limited to YAM, but required changes to NList itself, as explained above.

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-08-03 20:36:25 +0200**

___
ok. this is a similar problem.

in general the keyboards work fine it seems.

it only does not work if you click once in the message list with the mouse! in my case the list on the left is then still "selected" (marked blue) but the cursors move the grey selection on the right.

and cursor-left/right does also no longer work.

so it seems nlist update is needed for this? correct?

thanks and regards...
michael

**Comment by tboeckel** [comment]
**Originally on 2010-08-04 08:44:19 +0200**

___
Replying to MichaelMerkel:
> it only does not work if you click once in the message list with the mouse! in my case the list on the left is then still "selected" (marked blue) but the cursors move the grey selection on the right.
> 
> and cursor-left/right does also no longer work.

Hm, even that works for me without problem. I just verified this with the latest 0.105 release and the latest nightly build of YAM. I even verified this to work with and without the embedded read pane. No matter how often I click into the folder tree or mail list I am still able to move the focus with the left/right cursor keys and the then visibly active list will correctly scroll up and down.

Which mode are you using? Separate read window or read pane?
 
> so it seems nlist update is needed for this? correct?

From my point of view a new release of NList will only fix the graphical issues, i.e. the active border although the list itself will show the active state by using different cursor colors already.

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-08-04 21:01:05 +0200**

___
ok - i tried the latest nightly and the problem seems gone!
you changed something?

regards...
Michael

**Comment by tboeckel** [comment]
**Originally on 2010-08-06 12:24:33 +0200**

___
Replying to MichaelMerkel:
> ok - i tried the latest nightly and the problem seems gone!
> you changed something?

Yes, although this was only a very tiny change. The mail header lists still had the "default object on click" **and** the "active object on click" feature enabled. This might have caused some trouble for the embedded read pane. Although it cannot have any impact for a separate read window.

Anyway, if everything is now working as expected I will close this bug.
