### ISSUE TITLE
the about window can only be closed with the escape key

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#176]
**Originally by _Michael.Merkel@gmx.net_ on 2010-08-08 17:18:42 +0200**

___
hi - no big brainer this time.

the current about window can not be closed by pressing the close button but only by pressing escape ;-)

thanks and regards...

michael

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2010-08-09 08:15:26 +0200**

___
Yes confirmed, it cannot be closed anymore, shortcut doesn't work too :-/

samo79

**Comment by tboeckel** [comment]
**Originally on 2010-08-09 08:16:01 +0200**

___
In (6c679b3):
 * mui/Aboutwindow.c: fixed wrong usage of MUIV_Notify_Self. This closes #176.
