### ISSUE TITLE
YAM tries to close file twice -> recoverable alert on exit

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#178]
**Originally by _mario@cattaneo.de_ on 2010-08-14 17:11:17 +0200**

___
YAM 2.7-dev [OS4/PPC] (14.08.2010)

First of all, this does not happen with the debug version, so I cannot provide you with a debug log.
Second there is nothing on the grim reaper side.

I only know, when I quit YAM I get a dos requester complaining that a file that was already closed was closed a second time, then there is a yellow guru.

If there is anything I can do to give you some more info, please tell me.

**Comment by tboeckel** [comment]
**Originally on 2010-08-14 18:36:27 +0200**

___
I just tried that nightly build. Ran YAM and quitted it again => no problem.

If there is something else to do to let the issue happen then this tiny bit of information is missing in your report.

**Comment by jens-maus** [comment]
**Originally on 2010-08-14 18:50:40 +0200**

___
Ok. I tried to reproduce the issue as well. So I compiled myself a non-debug version and simply started it and quit YAM immediately. And here it also seems to happen. The requester that comes up seems to be comming from dos.library directly reminding the user that an already closed file was tried to be closed a second time. So there indeed seems to be some internal problem which might need some further investigation. Let's see if SnoopDOS&Co can help in finding out why the debug version works while the non-debug version shows the problem on quit.

**Comment by jens-maus** [comment]
**Originally on 2010-08-14 20:13:28 +0200**

___
In (6aca62b):
 * extrasrc/NewReadArgs.c,h: unified the "public" and "private" NewRDArgs
  data structure as we are utilizing it anyway completely. In addition, the
  data alignment enforcement has been removed. All together this fixes #178
  where a Close() has been executed on an invalid file handle due to the
  wrong structure alignment of NewRDArgs.
