### ISSUE TITLE
Thought about placing filter-gadgets below the nlist?

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#18]
**Originally by _mario@cattaneo.de_ on 2010-03-03 16:42:04 +0100**

___
Have you tried to put the new two gadgets below the list. I think this would look much better. And it removes the danger of clicking the wrong gadget (e.g. want pop but do change filter-cycler). Please give it a try. I think the relation to the list is still there, even if it is under it. You want to copy thunderbird (I don't know it), and TB is the mailer of firefox, and FF e.g. has the search-string gadget below the HTML-area, too. Cool argument, huh? ;)

**Comment by jens-maus** [comment]
**Originally by _treteimer_ on 2010-03-03 16:42:54 +0100**

___
Even better would it be to place it inside the status bar. There is a lot of unused space in it which could be filled with that perfectly. That would also let both lists - folders and mails - have the same height again for aesthetical reasons. Furthermore the popup gadget to switch between different parts of the mail to be searched in should be replaced by a cycle gadget as for "View", too. Would look better and give the user information on what is search criteria atm. Both selections should be saved on exit automatically. Even if no search criteria is used the info "139 of 139 shown" shopuld be displayed.

**Comment by jens-maus** [comment]
**Originally on 2013-01-19 21:08:54 +0100**

___
After having thought about this enhancement I feel that it should be quite easy to support it by adding an option to the Look&Feel configuration in YAM. However, I object the arguments from 'treteimer' and it should not be moved to the status bar.

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 09:07:27 +0200**

___
In (1ae6d82):
 * YAM_CO.c, mui/MainWindow.c: the position of the quick search bar is now configurable and allows the user to place the bar below the main mail list. This closes #18.

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 11:43:11 +0200**

___
**Release Note:**
The position of the quick search bar is now configurable and allows the user to place the bar below the main mail list.
