### ISSUE TITLE
YAM crashes when deleting mails from trashcan by hand

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#181]
**Originally by _mario@cattaneo.de_ on 2010-08-17 16:37:59 +0200**

___
YAM 2.7-dev [OS4/PPC] (17.08.2010) Copyright (C) 2000-2010 YAM Open Source Team

I am not deleting Mails at once, but let YAM put them to trashcan instead.
When I then open the trashcan folder, mark all the mails (say 15-20 in total) and press the delete button from the toolbar YAM crashes.

Find attached a GR log of the non debug version an a sashimi log of the debug version (set @all all) of the same built

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-08-17 16:38:29 +0200**

___
**Attachment added:** [`Crashlog_YAM_2010-08-17_14-34-57.txt`](https://yam.ch/attachments/181/Crashlog_YAM_2010-08-17_14-34-57.txt) (29.8 KiB)
GR log

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-08-17 16:38:48 +0200**

___
**Attachment added:** [`sashimi.out`](https://yam.ch/attachments/181/sashimi.out) (5.5 KiB)
debug log

**Comment by jens-maus** [comment]
**Originally on 2010-08-17 16:51:48 +0200**

___
Sorry, but I cannot reproduce the problem here. Here I perfectly deleted about 2000 mails from the trashcan by hand without a single crash. Is the problem reproducable for you or did it only happen once?

**Comment by tboeckel** [comment]
**Originally on 2010-08-17 16:57:40 +0200**

___
Do you have a debug kernel running on OS4? I just ask because the register r9 contains the very suspective value 0xccccccc. This usually points to some double Remove() calls.

**Comment by tboeckel** [comment]
**Originally on 2010-08-17 17:12:38 +0200**

___
One additional question. How is NListviews.mcp configured on your system? Please tell me your settings for the horizontal and vertical scrollbar. Are these set to "automatic"?

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-08-17 17:15:51 +0200**

___
Yes, I am using a debug kernel (to get the most infos into logs?).
And NLV is both set to "FullAuto".

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-08-17 18:04:28 +0200**

___
It's me again.
I assume it's related to the "FullAuto"-Setting. Cause when I set it to "Auto" no crash occures.
Well, now it also crashed when when I just switch "special" folders (find a log for that attached, though probably not usefull).

It seems related to the phenomenon that one folder here does always turn on/off the sliders when active. Seems like YAM/NLV cannot decide whether sliders are needed or not an therefor switches arround all the time. Now when I switch from that folder to another YAM crashes. Which it did not in the past.
Think I will reintall older NLV to see if the crash is gone then (again), the "jumping" will of course remain.

I think I talked about this to you some time ago. Still I was not able to have a perct config (best default) to give to you.
Maybe I should try another approach, so you can reproduce it.

**Comment by tboeckel** [comment]
**Originally on 2012-04-26 17:10:05 +0200**

___
Closing this ticket as this is no bug in YAM but in NList. If you are able to reproduce the crash easily then please open a new bug in [NList's bugtracker](http://sourceforge.net/tracker/?atid=662281&group_id=112474&func=browse).
