### ISSUE TITLE
Icons are drawn with pink border on OS3.9

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#182]
**Originally by _amix@pc-dome.com_ on 2010-08-21 01:20:43 +0200**

___
After installing YAM 2.6 over 2.4 all icons have problems with transparency and are displayed with a pink border. I know that this issue has already been addressed but as I understand it was only for AROS (Changeset 4534)?

I use OS3.9 with WB-replacement DOPus 5 II Maggellan on Winuae.
Screen Picasso Winuae 1024x768 16Bit

I would like to included a screenshot of the Toolbar and the prefs application of akPNG datatypes.

**Comment by jens-maus** [comment]
**Originally by _amix@pc-dome.com_ on 2010-08-21 00:58:14 +0200**

___
**Attachment added:** `yam.jpg` (63.1 KiB)
![yam.jpg](https://yam.ch/attachments/182/yam.jpg)
pink icons in yam 2.6 under OS3.9 with DOpus 5 Maggellan II as WB replacement

**Comment by tboeckel** [comment]
**Originally on 2010-08-22 20:34:27 +0200**

___
You might want to try AfAOS. Its picture.datatype is able to correctly return the alpha channel data (=transparency) to the application.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2010-08-23 18:42:16 +0200**

___
Replying to [#182 amix@…]:
> After installing YAM 2.6 over 2.4 all icons have problems with transparency and are displayed with a pink border. I know that this issue has already been addressed but as I understand it was only for AROS (Changeset 4534)?
> 
> I use OS3.9 with WB-replacement DOPus 5 II Maggellan on Winuae.

Same here (Classic, OS3.5, DOpus Mag. II, AKpng 45.11).

On 68k Amigas, loading the Yam interface is very slow because of the (datatype decoded) images.
In this case, I recommend to install and use the empty (imageless) theme (empty_theme.lha from Aminet), and one of the status image set from LtStatusImg.lha

But as you are using UAE, the slowdown is probably not that important...

I had the same issue (transparent as pink background) with one Hollywood application.  The solution was to install the pngalpha.library (pngalpha_lib.lha). But this does not work (not used) with Yam.
So in the meantime, the workaround is to enjoy the pink images :-) , or no images (empty theme).

**Comment by tboeckel** [comment]
**Originally on 2010-09-29 08:12:59 +0200**

___
Closing this bug as "won't fix". Sorry, but there is no way to workaround the limitations of the old and buggy picture.datatypes. Working replacements are available. So either use these or live with the pink borders.

**Comment by jens-maus** [comment]
**Originally on 2010-09-29 08:35:02 +0200**

___
Just a comment: Perhaps we should create a new entry in our online FAQ about that and give hints which picture.datatype are known to behave correctly and where to get it from?!?
