### ISSUE TITLE
YAM crash without e.g. NList.mcc

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#186]
**Originally by _opionline@yahoo.de_ on 2010-08-24 22:40:59 +0200**

___
If i start YAM without e.g. NList.mcc or a wrong version
of a mcc then YAM crash.

Step by step to reproduce:
1. rename NList.mcc in your Libs: path
2. start YAM
3. click 'Beenden'
4. YAM crash at this point

used version:
YAM 2.7-dev [OS3/m68k] date 24.08.2010 (build 20100824)
used system:  AO3.9 - BB2 on a A2000 - 060

I attach the MuOutput.txt with the MuToolsHit and a DebugLog.txt
with the Debug output (@all all) for such crash.

unfortunately my GG installation is not working so i can't
have a look and provide a patch for this issue.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-24 22:41:18 +0200**

___
**Attachment added:** [`DebugLog.txt`](https://yam.ch/attachments/186/DebugLog.txt) (8.0 KiB)

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-24 22:41:35 +0200**

___
**Attachment added:** [`MuOutput.txt`](https://yam.ch/attachments/186/MuOutput.txt) (4.3 KiB)

**Comment by tboeckel** [comment]
**Originally on 2010-08-25 13:17:03 +0200**

___
In (e088f9d):
 * BayesFilter.c, MethodStack.c: the spam filter's and the method stack's
  aribtration semaphores are now accessed only after their proper
  initialization. This closes #186.
