### ISSUE TITLE
Active/Inactive status of mail and folder list breaks keyboard usage (e.g. Del key)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#188]
**Originally on 2010-08-26 11:12:33 +0200**

___
Since the changes in the course of the NList 0.106+ release, which fixes an important bug in the active/inactive display status of NList/NListview objects, the keyboard management of YAM 2.6 seems to got broken somehow. Under certain circumstances the Del key or the cursor up/down keys stop working even if the mail list is displayed as being the "active" object of the main window.

The following procedure should demonstrate the problem when NList 0.106+ is used together with YAM 2.6:

1. make sure the embedded read pane is enabled
2. select a mail in the mail list
3. select some text in the header list so that it gets the 'active' status
4. press 3xshift+tab to switch to the mail list so that it gets the 'active' status
5. use the 'del' or cursor up/down keys to try to scroll the mail list
6. you should see that the mail list doesn't scroll or delete the mail
7. use the mouse to select another mail in the mail list
8. now the cursor up/down key starts working again, but the 'del' key still doesn't work
9. use cursor left/right to switch to the folder list and back to the mail list
10. now everything works again (del & cursor up/down).

With YAM 2.7-dev or NList 0.105 everythings seems to work again. So the problem is the combination of YAM 2.6+NList 0.106+

**Comment by tboeckel** [comment]
**Originally on 2010-08-26 15:03:19 +0200**

___
The fixed tickets #1 and #14 plus some additional fixes finally close this one.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2010-08-26 15:41:39 +0200**

___
The fix (http://trac.yam.ch/changeset/5004) should go
into the main branch too. IMHO.

**Comment by tboeckel** [comment]
**Originally on 2010-08-26 15:42:25 +0200**

___
All changes I did to the bugfix-2.6 branch were in fact taken from the main trunk.

**Comment by jens-maus** [comment]
**Originally on 2010-08-26 15:43:58 +0200**

___
Replying to anonymous:

> The fix (http://trac.yam.ch/changeset/5004) should go
> into the main branch too. IMHO.

This is non-sense. The main trunk is already fixed. Of course!

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-27 02:25:04 +0200**

___
Sorry it was me who wrote comment 3 but i was not looged in.

I wrote that because yesterday i saw that the cursor keys in
the lists doesn't work on my system and today i read this
bugreport and the fix for that. So my assumption was the patch
was not yet into the main branch. sorry for that.

I use the latest MCC_NList-0.107 archive and YAM 2.7-dev
[OS3/m68k] (24.08.2010) so the coursor keys in YAM should work.

I'm sure in a previous version of YAM and/or NList it was
possible to scroll in the lists with the up/down keys and
change the lists (folder/mails) with the right/left keys.

I just load the build from today (27.08.2010) and it still
doesn't work so i reopen this bug.


Resetting the prefs to the default values doensn't help.
CTRL + up/down does work like expected, with marking.

BTW: i don't use the embedded read pane but if i do so
(for this test) then i must press  *4* x shift+tab to make
the mail list 'active' again. (see point 4 above)

**Comment by jens-maus** [comment]
**Originally on 2010-08-27 08:15:50 +0200**

___
That's very strange as we thought that everything is fine with the latest nightly build and NList 0.107. So can you please elaborate further and tell us more about your system? I guess you are using OS3/m68k, right? Which MUI version? MUI 3.8? And can you please give us a step-by-step explaination like the one I wrote above how to reproduce it, or do you use the same procedure to show the problem? And have you tried resetting the NList settings to their defaults? We should really get that nailed down because otherweise we cannot release 2.6p1.

**Comment by tboeckel** [comment]
**Originally on 2010-08-27 13:48:22 +0200**

___
**Attachment added:** [`NListtree.mcc`](https://yam.ch/attachments/188/NListtree.mcc) (71.5 KiB)
test version of NListtree.mcc

**Comment by tboeckel** [comment]
**Originally on 2010-08-27 13:48:53 +0200**

___
**Attachment added:** [`NListview.mcc`](https://yam.ch/attachments/188/NListview.mcc) (7.8 KiB)
test version of NListview.mcc

**Comment by tboeckel** [comment]
**Originally on 2010-08-27 13:50:47 +0200**

___
I suppose you are still using MUI3.8. This one has some severe bugs when it come to keyboard handling. Under certain conditions the classes are not triggered for every key press.

I added some workarounds for this issue in NListtree.mcc and NListview.mcc. Please try the attached versions. If they fix the issue for you then we must release a fixed version of NList along with YAM 2.6p1.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-27 14:45:30 +0200**

___
Yes of course i rum MUI 3.8 on a A2000 (68k060) AOS3.9 BB2.
Do you know a more recent version for 68k? ;-)


Here is my step by step:
1. Start Yam.
2. Select a mail or a folder in the lists:
3. Use the cursor keys - none of them is working.

The attached NListtree.mcc.18.33.new NListview.mcc.19.81.new
are working ok. :-)

But i can't mark the mails using the ctrl key - seems the
key handling has changed.

Using ctrl + up/down keys scroll to the begin or end of the list.
Shift + up/down jump to first/last entry of the visible mails.

Alt + ctrl mark all mails from the current active up to the
first/last of all mails.
Shift + ctrl Same as Alt + ctrl except only the visible mails
get selected.

Maybe i must reset my settings?
Or how is it possible to select some mails like before?



BTW: Yesterday i saw that in the MUI prefs program the
follow mcc's don't have a icon in the left list:
NList (+ Nlisttree), Texteditor and MCC_BetterString.

See  also attached pic Mui-Prefs.png.
Should i file a bugreport(s) for this?

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-27 14:46:39 +0200**

___
**Attachment added:** `Mui-Prefs.png` (2.4 KiB)
![Mui-Prefs.png](https://yam.ch/attachments/188/Mui-Prefs.png)

**Comment by tboeckel** [comment]
**Originally on 2010-08-28 08:45:19 +0200**

___
Replying to opiopi:
> The attached NListtree.mcc.18.33.new NListview.mcc.19.81.new
> are working ok. :-)
> 
> But i can't mark the mails using the ctrl key - seems the
> key handling has changed.
> 
> Using ctrl + up/down keys scroll to the begin or end of the list.
> Shift + up/down jump to first/last entry of the visible mails.

This is due how you configured the standard MUI keys. These definitely clash with NList's default settings. MUI uses ctrl+up/down to go the first/last entry of a list. NList will handle these special keys first, before it handles its own key definitions. This is why ctrl+up/down does not mark any entry.
Check your MUI configuration and change it accordingly.

I tried this on several systems now (OS3 and OS4), using different versions of MUI (3.8 and 3.9), and all behave in the same way now. Although none of them can mark entries with ctrl+up/down this is no bug, but just a "buggy" configuration.

To make it short, I will close this bug because from my point of view there is nothing to fix, neither in YAM, nor in NList (except the workaround for MUI3.8).

The only thing I can offer is to change NList's default key bindings. Do you have any suggestion which does not collide with some other key setting?

> BTW: Yesterday i saw that in the MUI prefs program the
> follow mcc's don't have a icon in the left list:
> NList (+ Nlisttree), Texteditor and MCC_BetterString.

Do you have the latest NBitmap.mcc installed? This one is used to display truecolor images. If it is missing or too old (15.8+ is needed) you will see the old color mapped image.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-28 10:17:17 +0200**

___
Hmm if i read the 'Keybindings' page in MUI config i see this entries:

control up = Select up
control down = Select down

so either your desription or the description on this page is wrong.

Additional i think it was possible with earlier version to hold the
ctrl key and click on some list entries and then only these entries
gets selected. This also doesn't work with the current version.

But all that should go to the correct place e.g. the Nlist bugtracker.


Yes i have NBitmap.mcc 15.11 [OS3/m68k] (18.08.2010) installed
but the icon are not here. Seems i must check my datatypes.

**Comment by jens-maus** [comment]
**Originally on 2010-08-28 10:54:21 +0200**

___
Hi, I have to support the observations from Thore here. In fact, I downgraded my system to YAM 2.6 and the NList version that it distributed. And here the same happens. Control+up/down just changes the view and does NOT select anything in NList. In addition, also Shift+up/down does only scroll down/up side-wise.

After having checked the keybinding configuration of NListviews and MUI it really seems that the default settings for selection of entries with the keyboard clashes with the default keyboard settings in the MUI keybinding. I was also able to get rid of the problem by either clearing the "Up/Down" and "Page Up/Down" settings in keybinding in MUI and afterwards NList was able to use Control+Up/Down and Shift+Up/Down. Another possibility is also to change the keybinding in NListviews to use the following mapping:

shift alt up = Page up selection
shift alt down = Page down selection
alt up = upwards selection
alt down = downwards selection

So instead of using the "Control" key in NList it would be IMHO better to use the "Alt" key for keyboard selection as this won't clash with the internal defaults of the MUI keybindings.

However, why Frank seems to recall that this was working before isn't clear. Either he mixes something up or some recent changes finally fixed some problems in regard with MUI 3.8 which might now show the correct behaviour. So Frank, can you please downgrade to YAM 2.6 and install the NList versions it comes with. And then please check how this versions behave.

Regarding the with Ctrl+Mousekey. This also does not work here. However, the correct combination to select several entries separately seems to be Shift+Mousekey here.

So please let us clear this thing up so that we can release a new NList version quickly before we are going to finish up 2.6p1.

**Comment by jens-maus** [comment]
**Originally on 2010-08-28 10:56:56 +0200**

___
BTW: I also checked the behaviour on MOS and there Ctrl+Up/Down also scrolls instead of providing an entry collection.

So perhaps this missunderstanding shows that we need a new FAQ entry in faq.yam.ch? In addition, I think we should change the default keybindings in NListviews to use ALT rather than CONTROL.

**Comment by tboeckel** [comment]
**Originally on 2010-08-28 13:08:24 +0200**

___
Replying to damato:
> Regarding the with Ctrl+Mousekey. This also does not work here. However, the correct combination to select several entries separately seems to be Shift+Mousekey here.

To be consistent with the global AmigaOS style it was always the Shift key to trigger multi selection.

Of course one could change this to his preferred likings and thus a specific combination might have worked at some point in time.

**Comment by jens-maus** [comment]
**Originally on 2010-08-29 00:12:47 +0200**

___
Replying to thboeckel:

> Of course one could change this to his preferred likings and thus a specific combination might have worked at some point in time.

Please note that I just changed the default NList keybindings in the recent sources to use the ALT key rather than CONTROL to select entries via the keyboard. This should hopefully fix the clashing keybinding settings between MUI and NList.

**Comment by jens-maus** [comment]
**Originally on 2010-08-29 10:54:17 +0200**

___
I just added an entry to our online-FAQ. So please check the following URL for information on how to configure NList until 0.108 has been released:

http://faq.yam.ch/content/1/62/en/why-is-keyboard-selection-of-multiple-mails-not-working.html

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-30 00:15:36 +0200**

___
I'm sure i select last week mails using the CTRL + up/down key.
But today i can't reproduce the selection. Maybe last week i
really play to much with the configurations.

The problem should be fixed with damatos changes.
So i don't want to play again with different versions and configurations
because it makes no sense anymore.

For multi select with the mouse i'm not sure if it was
CTRL or Shift and i don't test it last week.
Today i test that too and it's the shift key and it works ok.
