### ISSUE TITLE
Mailbox/Check single account no longer working

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#190]
**Originally by _mario@cattaneo.de_ on 2010-08-27 14:45:02 +0200**

___
YAM 2.7-dev [OS4/PPC] (27.08.2010) Copyright (C) 2000-2010 YAM Open Source Team

Postfach/Einzelnes Konto überprüfen, does open a transpher window here, but nothing happens. Selecting regular POP-gadget does work (just to make sure there are really mails on the server :-))

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-27 16:01:04 +0200**

___
If i use any menu then YAM try to get always the mails from first entry in the POP server list (see config).

**Comment by tboeckel** [comment]
**Originally on 2010-08-28 13:17:11 +0200**

___
In (b76bddc):
 * YAM_MA.c: setting up the POP3 menu items must increase the index. This
  fixes #190.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-31 03:00:44 +0200**

___
Sorry i must reopen this bug.
I just try to get mails form my 10th account and it was not possible
via the menu. Instead of getting mail YAM run the 1st configured script.
The 11th menu entry run the 2nd script.

IIRC here was a limit for 16 accounts until YAM 2.6.
But now it seems YAM has a limit at 10 accounts.
I think we want to go forward. ;-)

IMHO the goal was that YAM have a unlimited number of accounts.
This should be of course also valid for the Menu entries for the
accounts until the limit by the OS.

Maybe the limit was set because of the hotkeys it should be removed
and let the user define the own hotkey if he really want a hotkey
for the accounts.

I still know that those functions are in development.

**Comment by tboeckel** [comment]
**Originally on 2010-08-31 08:39:33 +0200**

___
In (cfedeeb):
 * YAM_MA.c: adding the POP3 servers to the menu will bail out now after the
  maximum number of ten (10) entries. This closes #190 again.

**Comment by tboeckel** [comment]
**Originally on 2010-08-31 08:40:45 +0200**

___
One final question: who needs 10 or more POP3 accounts? :)

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-08-31 12:39:39 +0200**

___
You are forgeting, that YAM supports multiuser. Take a family, parents and 3 kids. Each wit 2 accounts, voila 10 accounts easily. :-)

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-31 14:10:04 +0200**

___
Padrino say it already. Additional 2 accounts are the minimum IMHO.
I know only one people who has only one account, all other have at
least 3 accounts.
I myself have 7 active accounts and some inactive are still into
the config but disabled.
Maybe it's possible to add a config entry to set the maximum
entries in the menu? That should suit all users.

**Comment by jens-maus** [comment]
**Originally on 2010-08-31 18:02:07 +0200**

___
In (ffd4a84):
 * YAM_MA.c: moved the Notify creation out of the MA_New() function into
  the CreateDynamicMenus() function and enabled it to dynamically create
  and kill notifies. In addition, the limit for POP3 menus has been raised
  to 30. This should really be enough for people as not all POP3 accounts
  are really required to be a menuitem and users can freely move POP3
  accounts around to get the first 30 items displayed accordingly. This
  refs #190.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-08-31 23:46:14 +0200**

___
Thanks a lot for the final fix.



BTW: The notification E-Mail about the fix
send from: "trac@yam.ch" <trac@yam.ch>
Date: Tue, 31 Aug 2010 16:02:07 -0000

contain a footer with the follow text:
Ticket URL: </ticket/190#comment:9>
YAM - Yet Another Mailer <http://trac.yam.ch/>
The Open-Source Amiga E-mail suite
--

I would be nice if the Ticket URL is a real URL with
the protocol and a Fully Qualified Domain Name.
e.g. <http://trac.yam.ch/ticket/190#comment:9>

**Comment by jens-maus** [comment]
**Originally on 2010-08-31 23:59:09 +0200**

___
Replying to opiopi:
> BTW: The notification E-Mail about the fix
> send from: "trac@yam.ch" <trac@yam.ch>
> Date: Tue, 31 Aug 2010 16:02:07 -0000
> 
> contain a footer with the follow text:
> Ticket URL: </ticket/190#comment:9>
> 
> I would be nice if the Ticket URL is a real URL with
> the protocol and a Fully Qualified Domain Name.
> e.g. <http://trac.yam.ch/ticket/190#comment:9>

Sorry, but I cannot fix the whole world ;) This is a minor bug of the trac system we are using and thus you have to live with it... However, feel free to report it here: 

http://trac.edgewall.org/wiki/NewTicket

:-)

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-09-01 00:27:43 +0200**

___
Done -> http://trac.edgewall.org/ticket/9593
