### ISSUE TITLE
YAM crashes (re)building my index of small ;) incoming - with 8000 files

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#193]
**Originally by _mario@cattaneo.de_ on 2010-08-27 18:54:24 +0200**

___
YAM 2.7-dev [OS4/PPC] (27.08.2010) Copyright (C) 2000-2010 YAM Open Source Team

Got a crash (#181 related) from YAM, so I had to reboot and YAM now wants to rebuild index and crahes every time (arround entry 5255-5265, btw).
Find attched a GR of the "regular" built and a log from the debug version.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-08-27 18:54:57 +0200**

___
**Attachment added:** [`Crashlog_YAM_2010-08-27_18-11-50.txt`](https://yam.ch/attachments/193/Crashlog_YAM_2010-08-27_18-11-50.txt) (28.3 KiB)
GR log of nondebug version

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-08-27 18:59:14 +0200**

___
**Attachment added:** [`sashimi.out`](https://yam.ch/attachments/193/sashimi.out) (77.2 KiB)
stripped debug log, if you need more, just tell me, I have 500KB :-)

**Comment by tboeckel** [comment]
**Originally on 2010-08-28 19:29:44 +0200**

___
My last change should fix this issue. If not, the please reopen this ticket.
