### ISSUE TITLE
Mail preview locks up

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#195]
**Originally by _mario@cattaneo.de_ on 2010-08-29 15:15:50 +0200**

___
YAM 2.7-dev [OS4/PPC] (29.08.2010) Copyright (C) 2000-2010 YAM Open Source Team

Set the preview window to "always".
Pop mail.

1. The window cannot be resized while the list is updating.
2. (Even) when the list is complete, clicking "cancel" has no effect.
3. Downloading, ie. pressing "start" (and choosing the different dl-options) does work though. And window does autoclose.

**Comment by tboeckel** [comment]
**Originally on 2010-08-30 12:16:55 +0200**

___
In (fb08db6):
 * tcp/pop3.c: the current mail server node is now remembered during a POP3
  session. This saves some GetMailServer() calls and also makes it possible
  to abort the session with an opened and already finished preselection list.
  Furthermore allowed the application to perform its event handling while the
  preselection list is filled with data. This closes #195.
