### ISSUE TITLE
Enablung status display in docky does not work while YAM is running

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#197]
**Originally by _mario@cattaneo.de_ on 2010-08-29 17:23:14 +0200**

___
YAM 2.7-dev [OS4/PPC] (29.08.2010) Copyright (C) 2000-2010 YAM Open Source Team

To see the "display MB-status in docky"-setting be enabled one has to save the prefs, leave YAM and restart it. Otherwise there will be no dockicon added.
On the opposite disabling does work. So, after disabling and pressing "use" the icon is removed from the docky (as it should).

**Comment by tboeckel** [comment]
**Originally on 2010-09-30 21:45:41 +0200**

___
In (b50e118):
 * AppIcon.c, DockyIcon.c: slightly reworked the Docky icon logic to always
  display the correct Docky icon. This closes #197.
