### ISSUE TITLE
error message when doubleclick on URL

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#199]
**Originally by _opionline@yahoo.de_ on 2010-08-31 16:52:06 +0200**

___
I don't use this feature for long time but today i get a
error message when doubleclick on URL even if i use the
original script 'GotoURL.yam' from the rexx drawer:
The error message is:

Ausführung des ARexx-Kommandos 'YAM:Rexx/GotoURL.yam http://trac.yam.ch/ticket/190#comment:6' fehlgeschlagen (Fehler 0).
Bitte stellen Sie sicher, dass die Datei existiert und ein korrektes ARexx-Skript ist.

(BTW: I'm sure it exists and is a valid ARexx-Skript!)

I configured YAM like this:
Beim Doppelklick auf einen URL:
Skript: YAM:Rexx/GotoURL.yam %p  -> ARexx
'Öffne Konsolenfenster' and 'Warte auf Beendigung' both are unchecked.

It was working this way in the past with without such error message.

If i enable 'Warte auf Beendigung' or run it as 'AmigaDOS' (with Script Bit set)
or as 'rx YAM:Rexx/GotoURL.yam %p' then i get no error message.

So a possible solution would be to not check the return value if
'ARexx' is set *and* 'Warte auf Beendigung' isn't set.

Or at least a hint in the guide and/or bubblehelp?
So maybe this ticket is not a bug but a enhancement request.

**Comment by tboeckel** [comment]
**Originally on 2010-09-01 14:24:50 +0200**

___
In (877f5fa):
 * Rexx.c: in case YAM receives an asynchronous reply to a former
  SendRexxCommand() call an error message will only be displayed if the
  result is not equal to zero. This is now the same reaction as for a
  synchronous ARexx script. This closes #199.
