### ISSUE TITLE
EOL char deleted when re-editing message

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#2]
**Originally by _stevebow@users.sourceforge.net_ on 2010-03-03 14:33:58 +0100**

___
When you edit a message in the Outgoing folder, the very last EOL char is deleted.

For example, start a new message, then after the sig press <Enter> several times, then Hold the message.

Edit that message (now in Outgoing) and the very last EOL is gone. Hold and Edit again, and once more the last EOL is gone. This continues until the last EOL char is gone, but any ASCII (such as the sig itself) is not affected.

I have tried this with SimpleMail but the problem is not present, so it appears to be an issue with YAM and not TextEditor.

Using YAM 24/3/06 and TextEditor.mcc 15.17, OS4/A1XE.

**Comment by jens-maus** [comment]
**Originally by _stevebow_ on 2010-03-03 14:36:24 +0100**

___
Rather than opening a new bug, I'll reopen this one as the fix to this bug
has created another.

The problem is now the opposite. When you re-edit a held message, an EOL
char is now added.

**Comment by jens-maus** [comment]
**Originally on 2010-03-03 14:37:36 +0100**

___
Ok, the issue should now hopefully be fixed once and for
all. So please grab the next nightly build and verify that
the problem is gone.

**Comment by jens-maus** [comment]
**Originally by _stevebow_ on 2010-03-03 14:38:23 +0100**

___
Almost there.

If a held message has no attachment, the bug can be considred fixed. But
if there is already an attachment an EOL is still being added to the
message body in the write window.

Using the 27/4/06 build.

**Comment by jens-maus** [comment]
**Originally on 2010-03-03 14:38:59 +0100**

___
Is the issue still persistent with the latest YAM nightly?
Please retry again.

**Comment by jens-maus** [comment]
**Originally by _stevebow_ on 2010-03-03 14:39:30 +0100**

___
Yes it is. Using the 9/06/2006 nightly build and TextEditor 15.17.

**Comment by jens-maus** [comment]
**Originally on 2010-03-03 14:40:15 +0100**

___
Ok. now I think I should have addressed really all kind of
incarnations of this bug. So please check the next upcoming
nightly build and try to reproduce each single observation
you had once again please. Let me know if everything seems
to work now as expected. I really hope that issue is now
resolved for forever...

**Comment by jens-maus** [comment]
**Originally by _stevebow_ on 2010-03-03 14:40:47 +0100**

___
Do you want the good news or the bad news? ;^)

The good news is that you've fixed the problem of EOLs being added when
rediting messages (and attached text files getting EOLs too).

The bad news is, you've introduced a new problem.

Do this:

1. Start a new message, enter name/subject.
2. Do not add any text to the message body (important), just leave the
sig.
3. Attach a text file eg. S:startup-sequence.
4. Hold this message.
5. In the Outgoing folder, hilite and edit/read this message.

Here, I get the following error message:

Unexpected EOF while decoding multipart message. The message seems to be
truncated.

The sig is not displayed nor is the attachment.

Additionally, one e-mail I have received with a video/mpeg attachment also
displays this error. The attachment icon claims it is a 0 byte plain text
attachment. I can send you this entire message privately if you wish.

As this is related, I'll not close this bug.

**Comment by jens-maus** [comment]
**Originally on 2010-03-03 14:41:14 +0100**

___
Oh damn, I really shouldn't code that quickly after
midnight. Thanks for finding the issue so quickly. I already
fixed it so please wait until the next nightly to appear and
then please trey to reproduce all of the issues in that LONG
bugreport after another and verify please that all things
are working fine now so that I can close that damn ticket :)

thanks again for all your help and great bug reports!

**Comment by jens-maus** [comment]
**Originally by _stevebow_ on 2010-03-03 14:41:36 +0100**

___
Yes, you appear to have squashed that bug for real this time :^).
I have tried the various combinations of this bug and things now work as
expected. Thanks.

**Comment by jens-maus** [comment]
**Originally by _stevebow_ on 2010-03-03 14:42:03 +0100**

___
I've re-opened this as the problem has re-appeared (1/12/2008 build).
Trailing EOL chars are deleted when a held message is re-edited.

I suspect this has something to do with the recent bugfix #2349683.

**Comment by jens-maus** [comment]
**Originally on 2010-03-07 10:33:09 +0100**

___
Would you please state if this problem really still exists with either the latest release 2.6 version or even the latest 2.7 nightly build? Thanks.

**Comment by tboeckel** [comment]
**Originally on 2010-03-09 15:33:56 +0100**

___
In (41dceda):
 * YAM_RE.c: reading a message part will now correctly add the LF character
  which was stripped by the GetLine() function. This fixes #2.
