### ISSUE TITLE
Add section "file name pit falls" in YAM.guide

### ISSUE THREAD

**Issue by tboeckel** [jens-maus/yam#20]
**Originally on 2010-03-03 16:46:23 +0100**

___
YAM.guide should contain a section explaining common pit falls concerning file names, especially when these file names are passed to YAM's ARexx handling function.

This section should cover handling of file names containing spaces and other special characters which might cause problems with dos/ReadArgs() (see bug #635893) and hence either need to be escaped or surrounded by quotes.

**Comment by jens-maus** [comment]
**Originally on 2013-02-02 19:55:00 +0100**

___
accepting ticket for 2.9 release. Please note that such a documentation enhancement should be performed now in the HTML-based documentation instead.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-06 21:29:10 +0200**

___
Is this ticket still valid ?

I mean, after reading it, I quickly check my own Incoming folder, and saw no unsafe filenames.

Quoted from the Yam 2.8p1 guide:
```
Each message is saved as a separate file of which the filename 
is constructed by encoding certain information about the mail 
(date, status, etc) using the Base64 standard encoding.
The resulting name is compatible to any filesystem.
```

Indeed, characters resulting of a Base64 encoding are safe for filenames.  There is also no risk that spaces can be embedded in it.
For the extra part of the filename construction, the equal sign, plus, minus, dot, comma, are also valid characters for filenames.
So, as far as with the current stable version of Yam (2.8p1), there is no risk that Yam can make the DOS to go mad.


If the reporter of this ticket is looking for a way to deal with possibly unsafe filenames from ARexx scripting, here is attached an ARexx function that I'm using for escaping wildcard characters.
Usage: SafeFilename = escwc(UnSafeFilename)

As for possible spaces in filenames, the internal space() function should help to remove or replace them by, eg, a "+" or a "_".


Maybe I misunderstood the ticket ?
Is there a need of documenting how to parse the messages' filenames ?
Are there cases where Yam can produce no so secured filenames ?

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-06 21:30:10 +0200**

___
**Attachment added:** [`escwc`](https://yam.ch/attachments/20/escwc) (1.0 KiB)
ARexx function to escape wildcard characters in filenames

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-07 22:05:45 +0200**

___
> Is there a need of documenting how to parse the messages' filenames ?

This made myself curious, so I've updated a node in the English guide with some info I *guessed*.

(Do not append it on the guide before proof-reading/completing the info.)

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-07 22:57:01 +0200**

___
**Attachment added:** [`reference`](https://yam.ch/attachments/20/reference) (1.3 KiB)
Guide node: Reference - Message storage

**Comment by jens-maus** [comment]
**Originally on 2013-09-08 17:26:05 +0200**

___
Sorry, but we abadoned the Amigaguide documentation with YAM 2.8 in favour of documenting everything here in the wiki of the yam homepage. So we won't release any further amigaguide documentation but will try to improve the online docs.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-20 22:02:26 +0200**

___
Would you like help with the online documentation ?
I can convert the guide nodes into wiki formatted documents.

**Comment by tboeckel** [comment]
**Originally on 2013-09-21 21:40:46 +0200**

___
Replying to AmigaPhil:
> Would you like help with the online documentation ?
> I can convert the guide nodes into wiki formatted documents.

Help is definitely always welcome. I am absolutely no wiki expert and unfortunately Jens is currently on vacation for the next 3 weeks. But if you can prepare something in the meantime then feel free to go ahead.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-26 19:54:05 +0200**

___
Replying to thboeckel:
> Help is definitely always welcome. I am absolutely no wiki expert and unfortunately Jens is currently on vacation for the next 3 weeks. But if you can prepare something in the meantime then feel free to go ahead.

The [[wiki:Documentation/ARexx API|ARexx API]] documentation is now online (see also #434). 
I've tried to include changes since the latest update of the guide, so please review [[wiki:Documentation/rx_requestfile|REQUESTFILE]], [[wiki:Documentation/rx_writeidentity|WRITEIDENTITY]], [[wiki:Documentation/rx_findmail|FINDMAIL]], and [[wiki:Documentation/rx_setmail|SETMAIL]].  There are probably other changes to be made that I am not aware of...

For the other parts of the documentation, there are many things I can't decide by myself; so I prefer to let you, or Jens, to update them.  If it can help, I'm attaching here the guide nodes converted to wiki files.
Please note that you cannot just copy and paste them.  The titles are to be re-build (prepending the lines with 2 or more equal signs), ensure that all lines of a paragraph are idented the same way to keep it consistent, add line feed (double backslash) where needed, and escape some characters to avoid wiki interpretation.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-26 19:55:09 +0200**

___
**Attachment added:** [`wikidoc.lha`](https://yam.ch/attachments/20/wikidoc.lha) (151.6 KiB)
Amiga guide to Wiki docs

**Comment by tboeckel** [comment]
**Originally on 2013-11-27 09:06:08 +0100**

___
I just added a section to the global ARexx documentation to add quotes to any kind of file name and to check scripts with a file located in the Amiga RAM disk, i.e. "RAM Disk:foo/bar".

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 22:17:10 +0100**

___
**Release Note:**
improved online documentation (http://doc.yam.ch/) regarding the use of quotes when specifying file/directory paths.
