### ISSUE TITLE
Problems to navigate with cursor  keys on the configuration window YAM2.7dev-20100901

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#200]
**Originally by _tomsmart1@gmx.de_ on 2010-09-01 14:26:19 +0200**

___
I used YAM2.7dev-20100901 68K with MUI 3.8 and up to date MCCs including and with the updated NList classes form the Ticket #188 on a A2000 with Blizzard 2060 and Spectrum 28/24 with CGX and AmigaOS 3.9 BB2.
I only discovert it with this new Nlist classes because with older versions navigation with the cursor key wasn't possible.

First problem on stroke of the cursor key up and down are interpreted as two:
Here the step by step:
1. start YAM
2. open configuration window
3. press cursor down and up key so you see that the cursor in the list jump from entry to next entry or the one before
4. activate this list with a press of the TAB key
5. press then cursor down and up key 
 
Here you can see that the cursor in the list jump 2 entry width in the list so to the over next.

Second problem is that one cursor up and down key stroke are interpreted (have en effect) on two lists.
Here step by step:  

1. start YAM
2. open Configuration window
3. select Filter in the main config list with the cursor keys
3. select and active the list with the filters with the TAB key
4. try to select the second filter in filter list with the cursor down key

And here you will see on slow machines that the second filter is select in the filter list and directly after that the cursor in the main config list jump to Spam and so the Spamfilter settings are displayed.

For both problems if i active the listers with the Mouse the cursor key function normaly in the list.

**Comment by tboeckel** [comment]
**Originally on 2010-09-01 15:34:02 +0200**

___
There was still a tiny bug in NListview.mcc which caused a keyboard event to be handled twice. This will be fixed with the next NList release.
