### ISSUE TITLE
Add a comma and space when using doubleclick on address popuplist

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#203]
**Originally by _opionline@yahoo.de_ on 2010-09-02 17:28:22 +0200**

___
This is a enhancement request:

Here is a step by step to see the goal:

1. Write a new mail
2. Type some letters into the 'to' string gadget.
3. If you see a alias or address which you want press the return key
4. The 'to:' field contain the Alias and the E-Mail address followed by a comma and space.
(that's OK like that)
5. Now empty the 'to:' field.
6. Type the same keys as in 2.
7. Select the same (or another) entry from the popuplist (double click)
8. The result in the 'to:' field is the Alias and the E-Mail address but without the comma and space.

Now my little request: please add a comma and space if a user select a entry from the list.
and remove it later if no address follow, just like if you press return. So a user can tpye the next address without to add the letters itself.

Same goes for the 'CC' and 'BCC' addresses in the Option tab.

**Comment by tboeckel** [comment]
**Originally on 2010-09-29 09:01:03 +0200**

___
In (862e359):
 * mui/Addrmatchlist.c: double clicking an entry in the match list will now
  append a comma and a space just like pressing Return does. This closes #203.
