### ISSUE TITLE
Buttons in addressbook

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#204]
**Originally by _s.hawamdeh@teletu.it_ on 2010-09-05 20:00:05 +0200**

___
Is it possible to make translable the buttons in addressbook ?

I ask this because having them in english create some problems with the shortcuts already translated in my language.

The buttons are:

_To: 
_CC:
_BCC:

Thanks :-)

**Comment by tboeckel** [comment]
**Originally on 2010-09-06 09:01:00 +0200**

___
These three buttons were not translated by intention. Technically speaking mails use these three text strings internally in their header. So we kept the names as they are. Or do you want to keep the english/technical strings, but just change the shortcuts? There are not many options for "CC" and "BCC"...

Anyway, if we should ever make these string translatable this will not happen for YAM 2.6p1. Thus I will set the milestone to 2.7.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2010-09-06 18:21:43 +0200**

___
Ok i choose the easy way changing the shortcut, this fix temporarily #204
Modification availible from revision 5154

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2010-09-07 14:46:10 +0200**

___
Ok i choose the easy way changing the shortcut, this fix temporarily #204
Modification availible from revision 5154
