### ISSUE TITLE
Check for update silent again

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#206]
**Originally by _s.hawamdeh@teletu.it_ on 2010-09-08 14:28:11 +0200**

___
It was fixed in bug @80 but maybe it comes again.
Since latest nighly (2010-09-07) the "check for update" option seems silent again, there is no warning anymore if updates are not availible.

**Comment by tboeckel** [comment]
**Originally on 2010-09-08 14:50:31 +0200**

___
In (c72f77d):
 * tcp/Connection.c: a connection's error code is now correctly set after each
  receive operation. This closes #206.
