### ISSUE TITLE
YAM overwrite not allocated memory.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#208]
**Originally by _opionline@yahoo.de_ on 2010-09-13 19:20:00 +0200**

___
As the Summary say: YAM overwrite not allocated memory.
I get a lot of Hits using MuGuardianAngel and YAM. I attach one of them.
The part '-> ...' are added from a script using gccfindhit.

Here is an easy Step by Step to reproduce:

1. Run YAM.debug (YAM 2.7-dev [OS3/m68k] (11.09.2010))
2. Click on 'Config'
3. Click 'Save'

At this point i get the hits.
I think the nondebug version i not affected but i'm not sure.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-09-13 19:20:14 +0200**

___
**Attachment added:** [`MuGuardianAngelHit.txt`](https://yam.ch/attachments/208/MuGuardianAngelHit.txt) (4.5 KiB)

**Comment by tboeckel** [comment]
**Originally on 2010-09-14 09:08:56 +0200**

___
In (3d98bc7):
 * extrasrc/AllocSysObject.c: fixed the memory munging for the debug build to
  correctly decrement the counter and avoid writing one byte too much and
  hence causing MungWall hits. This closes #208.
