### ISSUE TITLE
Warning with signatures

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#209]
**Originally by @mattrust on 2010-09-14 08:59:16 +0200**

___
On AROS-i386 I get a warning when I try to enter the signature settings. See attached file.

**Comment by jens-maus** [comment]
**Originally by @mattrust on 2010-09-14 08:59:40 +0200**

___
**Attachment added:** `yam-warning.png` (3.1 KiB)
![yam-warning.png](https://yam.ch/attachments/209/yam-warning.png)
Screenshot warning

**Comment by tboeckel** [comment]
**Originally on 2010-09-14 09:21:25 +0200**

___
Which version of TextEditor.mcc do you have installed?

**Comment by jens-maus** [comment]
**Originally by @mattrust on 2010-09-14 09:46:15 +0200**

___
It's 15.35. But it's built with the AROS build-system and not downloaded from somewhere.

**Comment by tboeckel** [comment]
**Originally on 2010-09-14 10:23:21 +0200**

___
Ok, I finally managed to reproduce this issue and fixed it.

I was using a signature already and the issue only happens if one then switches to the alternative (but still empty) signatures. This was a bug in TextEditor.mcc.

Closing this as "fixed".
