### ISSUE TITLE
Search function is broken

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#211]
**Originally by _opionline@yahoo.de_ on 2010-09-15 04:04:59 +0200**

___
It seems that YAMs search function is broken because it
find no string which are in the header of a mail.

Step by step to reproduce:

1. Import the attached mail 'mail.eml'. (This is a mail i get from Thore but i edit the mail and delete the private data and change the text in the mail body. But the same happen with real received mails too.)
2. If the mail is in your inbox click the button 'find'.
3. Select in 'Search in' 'Message headers' or 'Whole message'.
4. Be sure '=' is selected from the drop down menu.
5. Into the textfield type for example '127'
6. Click 'Start search'

IMHO YAM should find the string in the mail but YAM doesn't
return any match. The same happen if try different search
strings which are in the header e.g 'xxx' 'Tester' etc.
I try also ADos search patterns e.g. '#?127#?' or '#?Tester#?'
without success.

Do i anything wrong or is the search function is really broken?

Used version YAM 2.6p1 [OS3/m68k] (14.09.2010)

BTW: The same happen with the new search function in YAM 2.7.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-09-15 04:05:15 +0200**

___
**Attachment added:** [`mail.eml`](https://yam.ch/attachments/211/mail.eml) (2.6 KiB)
Testmail

**Comment by tboeckel** [comment]
**Originally on 2010-09-15 09:13:15 +0200**

___
In (e3bbd85):
 * YAM_FI.c: a search in the mail headers now bails out as soon as a matching
  string has been found instead of continuing the search which will forget
  about the found string. This closes #211.

**Comment by tboeckel** [comment]
**Originally on 2010-09-16 10:14:10 +0200**

___
In (ffb905d):
 * YAM_FI.c: applied the necessary change to close #211 in the bugfix branch.
