### ISSUE TITLE
Some folder creation issues.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#215]
**Originally by _opionline@yahoo.de_ on 2010-09-18 18:50:05 +0200**

___
This report decribe some issues for the folder creation.
I don't want to create a extra ticket for all of them.
(It would really to much work for me. I spend a lot time of testing...)

Here is a step by step for creation of a new folder.

1. run YAM (here Version: YAM 2.7-dev [OS3/m68k] (18.09.2010))
2. Do a right click on the folder list.
3. Click 'Like current' in the requester.
4. Type as 'Name' any name. (here i use 'Test1')
5. Type as 'Path' any name. (here i use 'Test1folder')
6. click 'Ok'
7. (*) Here YAM do nothing. Running Snoopdos show me that YAM does a 'Lock PathToProgdir/Test1folder  Read  Fail'. IMHO YAM should create a folder if a Read  Fails. Otherwise maybe ask the user if want to use really this existing folder or maybe silent use this folder?
8. Because 5. dosn't work click on the Drawer requester button. The requester open.
9. (*) The title is 'Datei auswählen' but should 'Schublade auswählen' or anything like that.
10. Select 'new drawer' from the requester menu and create a drawer called 'Test1folder'. Select the new created folder in the requester and click 'Ok'.
11. Click 'Ok' in the 'Folder settings'.
12. Click 'Yes' in the 'Confirmation Request'.
13. (*) YAM do again a 'Lock PathToProgdir/Test1folder  Read'. This time with a result= OK. And... do nothing else.

So i can't create a new folder with this YAM Version.
The (*) marked points should be fixed IMHO.

IIRC here was some other folder creation issues with older YAM versions but i can't test is with the current version:
14. If the creation was successful and you delete the folder then you can't use the same name in the same YAM session again.
E.g. create a Folder 'Test1', delete the folder in YAM (using the context menu in the folder list) and now try to create a new folder with the name 'Test1'. YAM seems to remember the name and doesn't accept the name even if YAM itself was deleting the folder.
15. At point 8. YAM create a icon for the folder but doesn't delete the icon at point 14.

Another folder creation issue:
If you right click on a folder group, select 'New folder...' from the context menu and select 'Like current' then YAM is trying to create a 'New folder group' but the user want a 'New folder...'!
Maybe i this case the 'Like current' should removed from the requester?

I know it's very much for one report but all related to folder creation. :-)

**Comment by tboeckel** [comment]
**Originally on 2010-09-19 13:35:38 +0200**

___
In (be32267):
 * YAM_FO.c: creating a new folder now correctly sets up the full path to the
  folder's directory. This closes #215.
