### ISSUE TITLE
Mailto issue (OWB-->YAM)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#216]
**Originally by _s.hawamdeh@teletu.it_ on 2010-09-21 01:56:04 +0200**

___
I have a problem passing a complete mailto from OWB to YAM, the first part of the address is taked but the subject not, for example:

If I click with OWB this mail link on a webpage:

mailto:info@yahoo.com?subject=Hello Friend

It take only the address part but then, it doesn't catch the string "Hello Friend" into the Subject field of YAM

So here is what I have into YAM destination field:

info@yahoo.com?subject

If needed i can give real examples ...

**Comment by tboeckel** [comment]
**Originally on 2010-09-21 07:52:13 +0200**

___
Sorry, but exactly this does work with IBrowse and OpenURL. It must be an OWB issue. I don't know how OWB handles/parses such links, but it's not YAM doing anything wrong here. YAM can only react on the stuff it gets passed in and if OWB is omitting the subject then YAM is out of the game.

Just take this tiny HTML document:

```
<html>
<head><title>mailto: test</title></head>
<body>
<a href="mailto:johndoe@foobar.com?subject=Hello Friend">Write a mail</a>
</body>
</html>
```

Configure IBrowse to use YAM's WEBmail.rexx script for mailto: links with parameters "%h %s" and YAM will open a write window with the correct address and subject if you click on the link of that example page.
