### ISSUE TITLE
Morphos Bug in archive

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#217]
**Originally by _beworld@sfr.fr_ on 2010-09-21 12:56:44 +0200**

___
In the archive file : YAM27dev-MorphOS.lha, there are two empty directories in "locale" and "themes".
This causes a problem of extraction from the archive to the YAM installation directory.

**Comment by tboeckel** [comment]
**Originally on 2010-09-21 13:03:24 +0200**

___
I just downloaded the last three nightly build for MorphOS (18.9.2010 to 21.09.2010) and there is not a single empty directory in any archive.
