### ISSUE TITLE
new threaded send not working?

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#218]
**Originally by _Michael.Merkel@gmx.net_ on 2010-09-22 20:52:52 +0200**

___
hi.

pressing the send button just does - nothing on my side :-( no window no reaction.

i know this is a new feature but smth seems to be broken.

using 2.7 fromÂ¿22.09.2010

regards...
michael

**Comment by tboeckel** [comment]
**Originally on 2010-09-22 21:11:06 +0200**

___
Well, I suppose you have some mail waiting to be sent :)

I tested this on AmigaOS3 and AmigaOS4 and it is working without problems for me.

Please provide a THREAD+NET log.

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-09-23 20:31:23 +0200**

___
Replying to thboeckel:

> Well, I suppose you have some mail waiting to be sent :)

:-) sure

> I tested this on AmigaOS3 and AmigaOS4 and it is working without problems for me.
> Please provide a THREAD+NET log.

attaching the log right now. i did the following:
- start YAM
- press "send" (one mail already in the outgoing folder) -> nothing happens
- press amiga+q to quit
- yam asking me to send the remaining mails - i say "yes"
- now yam complains about a still open task and wether to wait or not. i say "quit".

hope this helps?

thanks and regards
michael

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-09-23 20:31:59 +0200**

___
**Attachment added:** [`yam_debug.txt`](https://yam.ch/attachments/218/yam_debug.txt) (18.3 KiB)
yam debug thread + net

**Comment by tboeckel** [comment]
**Originally on 2010-09-24 08:27:38 +0200**

___
Ok, I can see that the thread found one mail to be sent, but then exits with failure. Right after that a second send thread is started, which then hangs. Did you try to send twice?

Anyway, please create a THREAD+NET+GUI log with the next nightly build. I have added some debug output to possibly locate the point of failure.

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-09-24 20:47:37 +0200**

___
**Attachment added:** [`yam_debug_02.txt`](https://yam.ch/attachments/218/yam_debug_02.txt) (28.1 KiB)
updated with new nightly and new strange problem?

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-09-24 20:50:19 +0200**

___
Replying to thboeckel:
> Ok, I can see that the thread found one mail to be sent, but then exits with failure. Right after that a second send thread is started, which then hangs. Did you try to send twice?
> 
> Anyway, please create a THREAD+NET+GUI log with the next nightly build. I have added some debug output to possibly locate the point of failure.

here it comes. just uploaded.
and now smth new strange is happening:
i start yam, it comes up, i have some unread mails in my inbox. yam navigates to the first mail in the listview. and, tataaa, a "write new mail" window pops up! just like if i pressed the "new mail" button. but i have not!!
what is wrong now?
i typed in a receiver and subject and pressed send. like before nothing happened. the mail still sits n the outgoing folder :-(

p.s. the write new mail window only opens with the debug version of yam. and not with the regular one.

thanks and regards
michael

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-09-25 14:34:46 +0200**

___
attaching new log with yestersays nightly debug version.
now the auto-opening-write-window is gone... strange.

regards
michael

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-09-25 14:35:33 +0200**

___
**Attachment added:** [`yam_debug_03.txt`](https://yam.ch/attachments/218/yam_debug_03.txt) (25.1 KiB)
again - from today

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-09-27 16:17:10 +0200**

___
YAM 2.7-dev [OS4/PPC] (25.09.2010) Copyright (C) 2000-2010 YAM Open Source Team

Same here, sent, just does nothing...

**Comment by tboeckel** [comment]
**Originally on 2010-09-27 21:54:59 +0200**

___
This morning I changed some stuff concerning the method stack handling. Now I am able to send mails with an OS4 build done on Jens' build machine. I hope the fix also applies for the next nightly build. Please try and report.

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-09-28 18:57:45 +0200**

___
hi thore.

yes. now sending is fine again!
the send window is a little bit "out of shape", though. but this is currently just cosmetic.

many thanks and regards
michael

**Comment by tboeckel** [comment]
**Originally on 2010-09-29 08:07:54 +0200**

___
Replying to MichaelMerkel:

> yes. now sending is fine again!

Ok, closing this bug as fixed then.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-09-29 17:03:45 +0200**

___
@Michael

The send window is just "out of shape" when you perform a manual send, right?
When sending a mail instandly the window is as small as it needs to be.
But when you have mail sitting in outgoing folder and then send them all, then you get a window with an empty area at the bottom, which about double sizes the window.
Can you confirm that?

**Comment by tboeckel** [comment]
**Originally on 2010-09-29 17:14:39 +0200**

___
There is still a small glitch with the transfer group in the transfer window. Currently MUI seems to need at least one additional, although invisible, object to correctly resize the window. Without that (as it is now) the window can be resized, but its contents will not follow. I will have to investigate what is causing this.
