### ISSUE TITLE
Move or delete a selection defined after a "find"

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#219]
**Originally by _JDuch@fulladsl.be_ on 2010-09-27 18:13:08 +0200**

___
The possibility to move or delete a selction made after doing a "find" and then in the "find" window hutting "select matched" does not work since version 2.6.
The selection is made OK, but the appropriate "delete" or "move" buttons are ghosted.
I reported this before, (some months ago) in the support section and Thore promised this would be fixed in the nightly build
This fix seemingly did not made it to  2.6p1.

**Comment by jens-maus** [comment]
**Originally on 2010-09-27 18:14:16 +0200**

___
Does the problem still exist in the nightly builds or have it been fixed already?

**Comment by tboeckel** [comment]
**Originally on 2010-11-12 19:20:27 +0100**

___
Closing this ticket as "works for me" as you did not respond. I just tried to reproduce this issue with the latest nightly build and for me the buttons are correctly enabled.
