### ISSUE TITLE
Move folder directories in own "folders" subdirectory, rename spam folder to "Junk"

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#222]
**Originally on 2010-09-29 09:40:32 +0200**

___
Here are some thoughts about our current folder management and how we can make it more compatible and logical:

 1. despite cluttering the main YAM directory (YAM:) with all mail folder directories, it would be better to have a global YAM:folders directory in which new and existing folders are moved/created in.
 2. The default folders (outgoing/incoming/sent/spam, etc.) should be renamed (the directories) to be compatible to what other mail clients (e.g. Thunderbird) name them. This would make it more easy to integrate IMAP support in future. This would me to rename "outgoing" to "Outgoing" or "sent" to "Sent". And also rename "Spam" to "Junk".

This would of course also require to implement an automatic folder move operation once 2.7 is started and found old default folders lying in the YAM: directory instead of having them in the YAM:folders subdirectory as well as automatically renaming e.g. "Spam" to "Junk" and so on.

After all, this change would really make the folder management ore consistent for future changes. Currently, the YAM: directory is really cluttered with many mail folder directories which is not nice IMHO.

**Comment by tboeckel** [comment]
**Originally on 2013-08-13 09:12:45 +0200**

___
The next commit will implement part 1 of this task and also close it. If renaming of certain folder is really necessary and desired this should be covered by a new ticket/task.

**Comment by tboeckel** [comment]
**Originally on 2013-08-13 09:13:58 +0200**

___
In (8263266):
 * YAM_FO.c, misc: all folder directories will be moved to a new subdirectory named "Folders" in the user's mail directory (which defaults to YAM's program directory if not changed via ToolTypes or the user configuration) to clean up the default directory. Possibly duplicate directory names will be get a unique number appended. In the future it will not be possible anymore to select an arbitrary path for the folders, but only the directory name within the "Folders" directory. The folder's path will default to the name as shown in the folder listtree, unless it contains invalid characters for a path (i.e. a slash or a colon). This closes #222.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 22:33:13 +0100**

___
**Release Note:**
To cleanup the main program directory of YAM all folder directories will be automatically moved to a new subdirectory named "Folders" in the user's mail directory (which defaults to YAM's program directory if not changed via ToolTypes or the user configuration). Possibly duplicate directory names get a unique number appended. To ease folder setup it is not possible anymore to select any arbitrary path for a folder, but only the directory name within the "Folders" directory.
