### ISSUE TITLE
Last entry in mail selection/preview window only shows size

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#223]
**Originally by _mario@cattaneo.de_ on 2010-09-29 17:08:43 +0200**

___
YAM 2.7-dev [OS4/PPC] (28.09.2010) Copyright (C) 2000-2010 YAM Open Source Team

Set preview to always and POP.
Last entry in the list will show filesize, the others colums are empty though.

**Comment by tboeckel** [comment]
**Originally on 2010-09-29 17:22:28 +0200**

___
Well, for me it is exactly the other way round. All lines get filled with details, but only the last line is left clean. Please try again with the next nightly build and reopen this ticket if required.

**Comment by tboeckel** [comment]
**Originally on 2010-09-29 17:22:40 +0200**

___
In (fabe56a):
 * YAM_TR.c: the POP3 detail download stopped one mail too early and left the
  last line in the preselection window empty. Now YAM correctly advances until
  the last mail. This closes #223.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-09-30 03:51:51 +0200**

___
That's what I wrote, last entry, ie. last row (Reihe) has only the size column (Spalte). The rest (/other columns) is (/are) empty. :D
Anyway, I can confirm the fix with recent nightly built...

**Comment by tboeckel** [comment]
**Originally on 2010-09-30 07:39:45 +0200**

___
Ooops. Must have misread that...
