### ISSUE TITLE
Updatecheck crashes when new update is available

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#224]
**Originally by _mario@cattaneo.de_ on 2010-10-02 03:31:12 +0200**

___
YAM 2.7-dev [OS4/PPC] (01.10.2010) Copyright (C) 2000-2010 YAM Open Source Team

Find crashlog attached.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-10-02 03:31:39 +0200**

___
**Attachment added:** [`Crashlog_YAM_2010-10-02_03-27-40.txt`](https://yam.ch/attachments/224/Crashlog_YAM_2010-10-02_03-27-40.txt) (34.0 KiB)
Crash of update check

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-10-02 19:50:04 +0200**

___
same here. i also attached the crashlog. also a screenshot of the update window after pressing "ignore error". see the first line in the text area on top.

regards...
michael

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-10-02 19:50:33 +0200**

___
**Attachment added:** [`Crashlog_YAM_2010-10-02_19-43-55.txt`](https://yam.ch/attachments/224/Crashlog_YAM_2010-10-02_19-43-55.txt) (32.4 KiB)
mycrashlog

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-10-02 19:50:57 +0200**

___
**Attachment added:** `GR_000.png` (85.0 KiB)
![GR_000.png](https://yam.ch/attachments/224/GR_000.png)
screenshot of update window

**Comment by tboeckel** [comment]
**Originally on 2010-10-03 11:03:53 +0200**

___
In (a6f97da):
 * mui/UpdateNotifyWindow.c, mui/UpdateComponentList.c: correctly implemented
  the component list class. This closes #224.
