### ISSUE TITLE
Crashes on exit

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#226]
**Originally by _mario@cattaneo.de_ on 2010-10-15 16:52:59 +0200**

___
YAM 2.7-dev [OS4/PPC] (15.10.2010) Copyright (C) 2000-2010 YAM Open Source Team

I just have to start and end current nightly built and YAM will crash, Main window is closed, just the small "YAM closing" is still open

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-10-15 16:53:21 +0200**

___
**Attachment added:** [`Crashlog_YAM_2010-10-15_16-55-14.txt`](https://yam.ch/attachments/226/Crashlog_YAM_2010-10-15_16-55-14.txt) (26.2 KiB)
crash on close

**Comment by tboeckel** [comment]
**Originally on 2010-10-17 12:39:15 +0200**

___
In (a3be7a1):
 * mui/MainFolderListtree.c: the dynamically allocated display hook must be
  freed after the object itself has been disposed. It seems NListtree.mcc is
  using the hook while being disposed. This closes #226.
