### ISSUE TITLE
YAM crashes when on collection of new messages from mail server

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#227]
**Originally by _daniel.hutchinson@talktalk.net_ on 2010-10-22 20:55:33 +0200**

___
When YAM checks for e-mail if messages are found on the POP3 server and downloaded a crash occurs immediately after downloading, see GrimReaper crash log below. I am running YAM 2.6p1 on AmigaOS4.1 (update 2).

**Comment by jens-maus** [comment]
**Originally by _daniel.hutchinson@talktalk.net_ on 2010-10-22 15:06:18 +0200**

___
**Attachment added:** [`Crashlog_YAM_2010-10-22_11-07-08.txt`](https://yam.ch/attachments/227/Crashlog_YAM_2010-10-22_11-07-08.txt) (28.8 KiB)
GrimReaper log

**Comment by tboeckel** [comment]
**Originally on 2010-11-08 09:07:43 +0100**

___
In (bbc4d88):
 * YAM_AB.c, misc: made the birthday to string conversion thread safe. I hope
  this also closes #227, altough I was not able to reproduce this issue.

**Comment by tboeckel** [comment]
**Originally on 2010-11-08 09:11:08 +0100**

___
As a temporary solution for YAM 2.6p1 you can try to disable the display of the sender infos (config window -> page "Read" -> set "Sender info" to "none").
