### ISSUE TITLE
multithreaded mail receiving - preselection popup?

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#228]
**Originally by _Michael.Merkel@gmx.net_ on 2010-10-22 21:13:24 +0200**

___
hi thore.

cool stuff! looks like it is faaaast - thanks!
but i have one problem here.
i have 4 mail accounts. preselection window is off.
when receiving my mails i get the preselection popup for the third one?! looks strange to me.
the other accounts are just received without that window.

thanks and regards
michael

**Comment by tboeckel** [comment]
**Originally on 2010-10-23 10:17:25 +0200**

___
I suppose you don't have any size limit >0kB set, do you?

Please provide a NET debug log created with the next nightly build.

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2010-10-23 20:08:28 +0200**

___
Replying to thboeckel:
> I suppose you don't have any size limit >0kB set, do you?

hmmm. yes - i have set it to 100kb.
but the preselection is set to "never". in that case it should be irelevant what is entered there, shouldn't it?!

i now removed the 100kb. and now it works fine. no preselection window any more. that's strange.

> Please provide a NET debug log created with the next nightly build.

still necessary?

thanks and regards
michael

**Comment by tboeckel** [comment]
**Originally on 2010-10-24 11:07:51 +0200**

___
Fixed in the next nightly build:

- tcp/pop3.c: deriving the transfer flags from mail's attributes now correctly
  respects the mail's size and the configured preselection mode. This closes
  #228.
