### ISSUE TITLE
changing the exchange Mail to get&send Mail

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#23]
**Originally by _opionline@yahoo.de_ on 2010-03-03 16:51:04 +0100**

___
Hi

changing the Menue->Folder->Exchange mail to anything more meaningful (e.g. "get and send Mail") or anything like that.

IMHO Exchange is replace anything (original) with another thing and after that you don't have the original which i not the case in YAM. ;-)

**Comment by jens-maus** [comment]
**Originally by _tactica_ on 2010-03-03 16:51:49 +0100**

___
Then please suggest something better than "Exchange" which doesn't involve something as ugly as "Get & send" :)

**Comment by jens-maus** [comment]
**Originally by _opiopi_ on 2010-03-03 16:52:17 +0100**

___
My suggestion is: "Send and Receive E-Mails".

**Comment by tboeckel** [comment]
**Originally on 2010-10-31 10:48:08 +0100**

___
In (e88c554):
 * YAM_MA.c, locale/YAM.cd: renamed the "exchange mail" menu item to "send
  queued and get new mail". This closes #23.
