### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#231]
**Originally by @raziel- on 2010-11-08 14:24:12 +0100**

___
An eMail which keeps the order information of a recently bought product is truncated prematurely cutting off important information.

Error message:

Unexpected EOF while decoding multipart
message in file
'Multimedia:Storage/Mail/Incoming/Pcue+gAM
K9Y=.001,RF'.

The message seems to be truncated.

(08.11.2010 14:07:18)

Thore: Ein schneller Blick auf die Mail hat auf jeden Fall schon gereicht. Die Mail
besteht aus zwei alternativen Teilen (reiner Text und HTML), die durch die
Zeichenkette "------" getrennt sind. Dummerweise wird genau diese Zeichenkette
aber auch im normalen Text verwendet, was dann die Fehlermeldung von YAM
verursacht.

(A quick glance at the mail was in any way sufficient. It consists of two alternative parts (pure text and HTML) which are seperated through the line "------". Unfortunately exactly this line is also used in the normal text which triggers the error message from YAM)

I hope i didn't overdo the translation? ;-)

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2010-11-08 14:30:06 +0100**

___
**Attachment added:** [`Order_Receipt_from_fixyourownprinter.com.msg`](https://yam.ch/attachments/231/Order_Receipt_from_fixyourownprinter.com.msg) (6.6 KiB)
the message

**Comment by tboeckel** [comment]
**Originally on 2010-11-08 14:35:58 +0100**

___
Duplicate of #232.
