### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#232]
**Originally by @raziel- on 2010-11-08 14:24:14 +0100**

___
An eMail which keeps the order information of a recently bought product is truncated prematurely cutting off important information.

Error message:

Unexpected EOF while decoding multipart
message in file
'Multimedia:Storage/Mail/Incoming/Pcue+gAM
K9Y=.001,RF'.

The message seems to be truncated.

(08.11.2010 14:07:18)

Thore: Ein schneller Blick auf die Mail hat auf jeden Fall schon gereicht. Die Mail
besteht aus zwei alternativen Teilen (reiner Text und HTML), die durch die
Zeichenkette "------" getrennt sind. Dummerweise wird genau diese Zeichenkette
aber auch im normalen Text verwendet, was dann die Fehlermeldung von YAM
verursacht.

(A quick glance at the mail was in any way sufficient. It consists of two alternative parts (pure text and HTML) which are seperated through the line "------". Unfortunately exactly this line is also used in the normal text which triggers the error message from YAM)

I hope i didn't overdo the translation? ;-)

**Comment by tboeckel** [comment]
**Originally on 2010-11-08 14:29:46 +0100**

___
**Attachment added:** [`Order_Receipt_from_fixyourownprinter.com.msg`](https://yam.ch/attachments/232/Order_Receipt_from_fixyourownprinter.com.msg) (6.6 KiB)
The mail that YAM complains about

**Comment by tboeckel** [comment]
**Originally on 2010-11-08 14:30:37 +0100**

___
Added the file for raziel_nosgoth. Don't you have an account here?

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2010-11-08 14:35:02 +0100**

___
Replying to thboeckel:
> Added the file for raziel_nosgoth. Don't you have an account here?

Nope, normally YAM just runs perfect :-)

**Comment by jens-maus** [comment]
**Originally on 2011-11-26 10:12:48 +0100**

___
In (65c9296):
 * YAM_RE.c: modified the MIME boundary checks to make sure that the boundary
  is placed on a single line with a final '\0' and only white spaces between
  the boundary and the final NUL char. This should fix problems with slightly
  broken mails where the boundary was not chosen unique enough and where in
  the text it might partly show up. Previously YAM was just comparing the
  beginning of a line with the defined boundary string. However RFC 2046
  defines that the boundary should be on a single line with only white
  spaces and the final CRLF. Thus, this fix should close #232.
