### ISSUE TITLE
Hits when getting mails with preselection.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#233]
**Originally by _opionline@yahoo.de_ on 2010-11-09 11:48:37 +0100**

___
I set YAM in YAM Konfig->Neue Post->Grössenlimit a size of
200 KB. In my inbox was a mail with an size of 564.445 Bytes
so the preselection window appear. At this point i get a 
MuGuardianAngel hit. Attached as YAM-Hit-1.txt.

I attach also a File YAM.Debug-Output.txt which show the
YAM.Debug-Output mixed with the MuGuardianAngel output.

After getting this mail i get another hit. Attached as
YAM-Hit-2.txt. For this hit i have no debug output but
hope it can be fixed without such output.

Used Version: YAM 2.7-dev [OS3/m68k] (06.11.2010)
on a A2000 OS 3.9 BB2

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-11-09 11:48:57 +0100**

___
**Attachment added:** [`YAM-Hit-1.txt`](https://yam.ch/attachments/233/YAM-Hit-1.txt) (4.3 KiB)

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-11-09 11:49:12 +0100**

___
**Attachment added:** [`YAM-Hit-2.txt`](https://yam.ch/attachments/233/YAM-Hit-2.txt) (5.1 KiB)

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-11-09 11:49:24 +0100**

___
**Attachment added:** [`YAM.Debug-Output.txt`](https://yam.ch/attachments/233/YAM.Debug-Output.txt) (5.3 KiB)

**Comment by tboeckel** [comment]
**Originally on 2010-11-11 08:18:09 +0100**

___
I am sorry, but I am unable to reproduce this issue, neither with OS3/MUI3.8 nor with OS4/MUI3.9.

Does it happen for you upon every download with preselection or just sometimes? Did you snapshot the preselection list's columns since it finally became possible since October 27th or are they still resized on demand each time?

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-11-11 13:51:58 +0100**

___
I not yet snapshot the columns.

Today i try it again. I set the size to 2kB.
This time i don't get a hit but i'll try it some times again.
Maybe it's depending on the size of the mails.

Another issue i discover today is:
I get some non ASCII output in the debug console like:
YAM_UT.c:4115:saved layout weight factors: [NonASCII]

A short look into the source show me the in the function
SaveLayout() 'buf' is free'ed but accessed later in the
debug output. Should be changed IMHO.

But that can't the cause for the hits mentioned in the first
post because i got the hits with a non debug version.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-11-11 16:08:12 +0100**

___
After some tests i get again such hit.
I attach the output as 'Output-11.11.2010-1.txt+lines.txt'.

The '-> ...' after the offsets in the stack trace is the
output from GccFindHit added by a script.

I had a short look at the source and assume the calculation
of the memory size in DecodeData() Line 123 is wrong.

I can't verify that because my GCC is still not working. :-(

HTH

BTW: I get also a hit every time i close a read window.
But thats maybe another bug.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-11-11 16:09:04 +0100**

___
**Attachment added:** [`Output-11.11.2010-1.txt+lines.txt`](https://yam.ch/attachments/233/Output-11.11.2010-1.txt+lines.txt) (5.1 KiB)

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-11-11 16:09:05 +0100**

___
Attachment (Output-11.11.2010-1.txt+lines.txt) added by ticket reporter.

**Comment by tboeckel** [comment]
**Originally on 2010-11-11 16:23:45 +0100**

___
Replying to opiopi:

> A short look into the source show me the in the function
> SaveLayout() 'buf' is free'ed but accessed later in the
> debug output. Should be changed IMHO.

Just fixed that.

**Comment by tboeckel** [comment]
**Originally on 2010-11-11 16:26:14 +0100**

___
Replying to opiopi:
> I had a short look at the source and assume the calculation
> of the memory size in DecodeData() Line 123 is wrong.

Ouch, that might have been it. The determined len value is the final size information and has nothing to do with the encoded string length. Please try again with the next nightly build.

> BTW: I get also a hit every time i close a read window.
> But thats maybe another bug.

No, that is absolutely unrelated, because the read windows don't need to save the column layout of some NList objects. Please open a separate ticket for that issue.

**Comment by tboeckel** [comment]
**Originally on 2010-11-11 16:29:00 +0100**

___
In (5e00265):
 * mui/Base64Dataspace.c: fixed a too small memory allocation which very
  probably caused the buffer overrun described in ticket #233.
  This closes #233.

**Comment by tboeckel** [comment]
**Originally on 2010-11-11 16:29:41 +0100**

___
Please try again with the next nightly build and reopen this ticket if the issue is not yet fixed.
