### ISSUE TITLE
Move mail window not keyboard navigatable anymore

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#235]
**Originally by _Deniil_ on 2010-11-23 22:09:18 +0100**

___
Since updating to YAM 2.6p1 I cannot use the keyboard to move an e-mail to another folder anymore. The list of folders is not active, cannot become active by the keyboard and have no drawer marked when opened.

If I use the mouse it works fine. The next time I open the Move window the last folder is selected but it cannot be changed with the arrow keys as in previous versions.

I use this funktion from keyboard often when the battery runs out in my wire-less, optical mouse (never get yourself such a combo).

**Comment by tboeckel** [comment]
**Originally on 2010-11-23 22:25:44 +0100**

___
Press TAB once to make the folder list the active object. Then the cursor keys can be used again as usual.

**Comment by tboeckel** [comment]
**Originally on 2010-11-23 22:36:34 +0100**

___
In (167a576):
 * mui/FolderRequestWindow.c: make the listview object instead of the embedded
  list object the window's default object. This closes #235.
