### ISSUE TITLE
YAM 2.6p1 "Mailto"

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#236]
**Originally by _JDuch@fulladsl.be_ on 2010-11-27 12:41:19 +0100**

___
When clicking on Mailto link on a web page, and Yam is not open, it launches YAM & opens  a write message. When YAM is allready open and i click on such a link YAM is made active and comes to front, no "write message window" is opened.
I have the same with Netsurf

**Comment by tboeckel** [comment]
**Originally on 2010-11-27 16:20:53 +0100**

___
No problem here using IBrowse and a mailto: link. I just had to adapt the used ib2yam.rexx script a bit as it was using an invalid abosolute path for the WaitForPort command to wait for YAM to launch. This made the script continue immediately and since YAM was not running properly yet the rest of the script failed silently and of course did not open a new write window.
After the change everything worked perfectly again.

Which browerser are you using (except NetSurf) and how is YAM started when a mailto: link is clicked?

**Comment by tboeckel** [comment]
**Originally on 2010-11-29 17:41:26 +0100**

___
Any news on this?

**Comment by tboeckel** [comment]
**Originally on 2010-12-17 23:55:12 +0100**

___
Ok, no answer => no interest to get this fixed. Closing this one...

**Comment by jens-maus** [comment]
**Originally by _Hubert Maier <raziel_nosgoth@web.de>_ on 2010-12-19 10:58:51 +0100**

___
Replying to thboeckel:
> Ok, no answer => no interest to get this fixed. Closing this one...

Arrgh, i only now saw this :-(

I get the exact same behaviour

Yam is closed:
Clicking on a mailto link starts up YAM, fetches mail and then opens up the write window with the TO: address in place

Yam is running:
Clicking on the link brings YAM to the front and does nothing else unfortunately

Using OWB3.30 and the URL preferences with YAM as MAILTO: reference
settings in URL: Active|YAM|APPDIR:yam|"MAILTO=%s"

AmigaOS4.1 plus latest updates

**Comment by tboeckel** [comment]
**Originally on 2010-12-19 11:39:26 +0100**

___
Replying to <raziel_nosgoth@?>:
> Yam is closed:
> Clicking on a mailto link starts up YAM, fetches mail and then opens up the write window with the TO: address in place
> 
> Yam is running:
> Clicking on the link brings YAM to the front and does nothing else unfortunately
> 
> Using OWB3.30 and the URL preferences with YAM as MAILTO: reference
> settings in URL: Active|YAM|APPDIR:yam|"MAILTO=%s"

Ok, now I understand the problem.

The point is the following: if YAM is not yet running and started with suitable options to immediately write a new mail this will be done as requested. Starting YAM a second time while another instance is already running and possibly hidden or iconified this will just cause the first instance to appear and the second instance will quit at once without triggering any new mail stuff.

I will see how we can change YAM to make a second start transfer possible MAILTO options to the first instance. But this will affect YAM 2.7+ only as we don't plan another update to YAM 2.6.

As a workaround I suggest to use a script like the ib2yam.rexx script I mentioned in comment #1. For reference I will attach this one to this ticket.

**Comment by tboeckel** [comment]
**Originally on 2010-12-19 11:40:57 +0100**

___
**Attachment added:** [`ib2yam.rexx`](https://yam.ch/attachments/236/ib2yam.rexx) (1.2 KiB)
Script to launch YAM with parameters taken from a mailto: link

**Comment by tboeckel** [comment]
**Originally on 2010-12-19 11:43:26 +0100**

___
The attached ib2yam.rexx script is in no way limited to be used with IBrowse only. I should be possible to use it with any browser.

Just call is like this: ib2yam.rexx "address"|"subject"|"body"

**Comment by tboeckel** [comment]
**Originally on 2010-12-23 11:37:43 +0100**

___
In (3dafa6f):
 * YAM.c, Rexx.c: starting YAM a second time with startup options to compose a
  new mail will now pass these options via ARexx to the already running
  instance. Before the first instance would just have popped up and the new
  mail options were completely ignored. This closes #236.
