### ISSUE TITLE
YAM crashes

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#237]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2010-12-02 08:30:38 +0100**

___
The nightly build for MorphOS from yesterday and today suddenly crashes, e. g. when closing a window after having written a new mail, or closing a window, or edited the Prefs, etc. I attached 2 logs generated by MorphOS.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2010-12-02 08:31:16 +0100**

___
**Attachment added:** [`MorphOS_02-Dec-10_07_39_37.log`](https://yam.ch/attachments/237/MorphOS_02-Dec-10_07_39_37.log) (1.9 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2010-12-02 08:31:43 +0100**

___
**Attachment added:** [`morphos-00000418.log`](https://yam.ch/attachments/237/morphos-00000418.log) (256.0 KiB)

**Comment by tboeckel** [comment]
**Originally on 2010-12-02 15:41:19 +0100**

___
In (9b8c702):
 * mui/YAMApplication.c: fixed a wrong sizeof() statement when adding a new
  entry to the EMail cache. This closes #237. At least I hope. Please reopen
  the ticket if the bug is still present.
