### ISSUE TITLE
Wrong mailsize in mainwindow

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#238]
**Originally by _opionline@yahoo.de_ on 2010-12-05 00:27:29 +0100**

___
The mainwindow display a wrong size if the mailsize is
between 1000 and 1023 bytes.

Step by step to reproduce:
1. Create a mail with a total size of e.g. 1023 bytes.
2. Click on hold to see the mainwindow.
3. Go to the outgoing folder.
4. Look in the mainwindow in the size column.
Here it shows 0.1023 but should show 1023.

Used System : A2000 AOS 3.9 BB2
Used Version: YAM 2.7-dev [OS3/m68k] (04.12.2010)

**Comment by tboeckel** [comment]
**Originally on 2010-12-05 11:49:57 +0100**

___
In (1861cf2):
 * YAM_UT.c: converting a mail size to a string now uses the correct power of
  10 for the conversion. This closes #238.

**Comment by jens-maus** [comment]
**Originally on 2010-12-05 12:19:05 +0100**

___
Let me add that the problem was only present when the 'old' bytes-only display was used in the configuration. When one of the newer size-display settings was used (e.g. mixed-sizes) the problem was not visible.
