### ISSUE TITLE
No action on "Delete only", fetching new mails (w preselect)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#239]
**Originally by _enzobarba@libero.it_ on 2010-12-07 19:08:13 +0100**

___
1. active preselect mails on server pop3
2. Get new mails (i.e. from toolbar)
3. select all
4. "Delete Only"
5. "Fetch" (get)
issue: nothing happens; the mails are still there.

this happens with "delete only" AND "select ALL" mails on the server;
(in others word if the "Delete only" is the only action to do, during the session.

i.e. if I have five mails on server, and I set for 3->"Delete Only" and for 2->"fetch and delete" works Ok.

I'm on PEG2 G4 MOS1.4.5 latest ambient build and latest MUI NList_xx classes.

This happens from 6-7 builds till now.

**Comment by tboeckel** [comment]
**Originally on 2010-12-08 08:42:09 +0100**

___
In (edcf47a):
 * tcp/pop3.c, MailTransferList.c: the POP3 thread now checks for mails to
  either be transferred or deleted to actually start the download. Before only
  mails to be transferred were respected which made it impossible to just
  delete mails from a server without downloading any. This closes #239.
