### ISSUE TITLE
Title of save attachment is wrong: says "save message"

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#24]
**Originally by _mario@cattaneo.de_ on 2010-03-03 16:53:57 +0100**

___
When saving an attachment, the resulting save-requester has "save message" in the tile. Shouldn't it be "Save attachment" or "Save file"? Don't know how it look internally, if the requester is the same to save mail-parts.

**Comment by jens-maus** [comment]
**Originally on 2010-03-07 15:00:17 +0100**

___
verified.

**Comment by tboeckel** [comment]
**Originally on 2010-07-29 13:49:44 +0200**

___
In (bde0536):
 * YAM_RE.c, locale/YAM.cd, locale/german.ct: the title of the save attachment
  requester will now be set in respect of the content type of the file to be
  saved. This closes #24.
