### ISSUE TITLE
Problem with displaying some quoted printable encoding mails

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#240]
**Originally by _anonymous_ on 2010-12-16 09:06:40 +0100**

___
For some while since upgrading to yam 2.6 I've been seeing some emails that don't get displayed correctly when the content is encoded in 'quoted printable'

Here is  fragment from the display of a mail  from a mail from my mailing list

-----

Just a little mail to let you know that Claude is playing on Thursday 16th=
 of December 2010 at the R.M.A. Tavern (The Gun Room), 58 Cromwell Road,=
 Portsmouth.
Ticket =C2=A35 at the doors.

Concert at 9pm.

----

As you can see the text has been displayed undecoded. These mails always used to work with Yam 2.5 and earlier, and as far as I am aware display correctly in other mail clients

I've been short of time else I would havwe reported this earlier! I'l attach a copy of the message above

**Comment by jens-maus** [comment]
**Originally by _andy@broad.ology.org.uk_ on 2010-12-16 03:02:57 +0100**

___
**Attachment added:** [`Claude_Bourbon_s__Christmas_concert_at_the_R.M.A._Tavern__Gun_Room_,_Portsmouth.msg`](https://yam.ch/attachments/240/Claude_Bourbon_s__Christmas_concert_at_the_R.M.A._Tavern__Gun_Room_,_Portsmouth.msg) (4.6 KiB)
Email in quoted printable format

**Comment by tboeckel** [comment]
**Originally on 2010-12-17 18:20:37 +0100**

___
I took a deeper look at the mail and found out that it violates the rules defined by RFC 2049. Although it has the necessary "Content-Type" and "Content-Transfer-Encoding" lines, it is missing the "MIME-Version" header line. Without this YAM will treat the mail as non-MIME conforming and hence display it as 7bit ASCII instead of the given encoding.

Maybe YAM 2.5 was a bit less restrictive in this case, but from YAM 2.6 on the rules are obeyed.

Maybe there is a chance to convince the administrator of that site to send out MIME conformant mails. Direct him to http://www.ietf.org/rfc/rfc2049.txt for the details. The most important stuff is stated just below the line "A mail user agent that is MIME-conformant MUST:". Note the word "MUST"!

And yes, you are right, ThunderBird displays this mail correctly. But what are rules for if everybody disobeys them or bends them to his own requirements?

A possible solution would be not to enforce 7bit ASCII for such mails, but to take them as they are and output a warning.

Jens, what do you think?

**Comment by jens-maus** [comment]
**Originally on 2010-12-17 23:40:59 +0100**

___
Replying to thboeckel:
 
> Jens, what do you think?

I have the same opinion. One of YAMs' features is, that it tries to be as RFC compliant as possible. So if a mail is missing the MIME-Version: header it should be treated as being NON Mime compliant in my understanding.
For the possible solution I am still unsure. Warnings are often simply ignored and it might be that people will think that the Warning is a bug since the message will be displayed correctly.

**Comment by tboeckel** [comment]
**Originally on 2010-12-18 23:37:58 +0100**

___
Well, then I opt for leaving everything as it is. If a mailer produces non-MIME compliant mails then this is not a bug of YAM is such mail cannot be displayed properly. Although other clients silently ignore such errors I must second Jens' opinion. Issuing a warning but (incorrectly) displaying a mail text as it "might" be correct will just hide possible future problems. Better solve the problem at its roots: convince you mailing list admin to produce RFC 2049 conforming mails. That's what rules are made for.

**Comment by jens-maus** [comment]
**Originally by _andy@broad.ology.org.uk_ on 2010-12-21 23:17:20 +0100**

___
Thanks for looking into this. Whilst it was at the back of my mind that the mails themselves might be "buggy" the fact that it worked in 2.5, firebird and others made me think otherwise. I'm effectively the mailing list admin :-) so I'd best study my perl scripts ... and that RFC. Suprised that perl MAIL::SMTP doesn't take care of that automatically but then that's not your problem!

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2012-07-12 11:29:04 +0200**

___
When you are not responsible of the emails you receive there is nothing you can do. So you are stuck with the annoying requester :-( This is even stupid, from my POV, as Yam still displays the content when the requester is acknowledged!
This is so annoying that I a french user switched to Simplemail. I'm thinking the same now :-(

**Comment by jens-maus** [comment]
**Originally on 2012-07-12 11:37:29 +0200**

___
What exactly is your problem? That YAM outputs a warning requester? If so, please attach the mail in question and we will investigate whos fault that is.

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2012-07-12 12:39:57 +0200**

___
**Attachment added:** [`no-mime.msg`](https://yam.ch/attachments/240/no-mime.msg) (3.2 KiB)

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2012-07-12 12:40:42 +0200**

___
Yes the requester is annoying. Attached an example...

**Comment by tboeckel** [comment]
**Originally on 2012-07-12 15:59:02 +0200**

___
In (e4950f6):
 * YAM_ER.c, YAM_RE.c: implemented new function ER_NewWarning(). This servers exactly the same purpose as ER_NewError() but will not open the error window. It will be used in cases a mail does not contain the usual MIME-Version header line, for example, to record such error, but to not annoy the user too many error messages. This finally closes #240.

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2012-07-13 08:35:20 +0200**

___
Replying to thboeckel:
Thanks Thore.
