### ISSUE TITLE
SPAM filter report a error if mail decoding fails

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#241]
**Originally by _antibike@web.de_ on 2010-12-16 18:02:12 +0100**

___
The SPAM filter report a error if mail decoding fails.
This error message should not popup.
If the SPAM filter can read the mail partial and identify it as spam than he can set it to spam.
If he can't read the mail than it's always no spam and the user must find a way to decode.

**Comment by tboeckel** [comment]
**Originally on 2010-12-17 08:16:30 +0100**

___
This one is fixed by [5542] {changeset}.
