### ISSUE TITLE
DSI crash closing YAM when connection is disabled

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#242]
**Originally by _s.hawamdeh@teletu.it_ on 2010-12-23 08:43:33 +0100**

___
I found a strange bug in latest nightly build (20-12-2010), YAM will crash in certain situation when internet connection is turned off

How to reproduce it:

- Disable internet as you like
- Open YAM
- Start the search for updates option (obviously YAM tell you that this operation it's not usefull without an internet connection)
- Close YAM normally

After you close it, YAM generate a DSI crash, here my GR log:

Crash log for task "YAM"
Generated by GrimReaper 53.2
Crash occured in module YAM at address 0x6F640A5C
Type of crash: DSI (Data Storage Interrupt) exception

Register dump:
GPR (General Purpose Registers):
   0: 00000000 51D49390 00000001 00000000 00000000 00000000 6F6190EC 518C5807 
   8: 518CD2C3 53914DC0 0000006D 00000002 518CD2C0 53A6C2FC 53A67F2C 5FFFA800 
  16: 8042B96B 53A60000 80420000 00000000 51E50000 51D49578 561A6AE4 51D498D8 
  24: 0000F4DC 51D49578 5498F024 00000000 00000000 0000012C 000000E0 53914CE0 

FPR (Floating Point Registers, NaN = Not a Number):
   0:              nan              495              301               36 
   4:                0             53.8            127.8      2.14748e+09 
   8:              128               18          1.52344              nan 
  12:                1              496                0    -5.05923e-321 
  16:     1.32625e-315     1.39067e-309                0                0 
  20:                0                0                0     1.61895e-319 
  24:     4.94066e-324                0     1.08752e-311     -4.07294e-35 
  28:                0     1.35808e-312      8.8275e-311      1.04173e+21 

FPSCR (Floating Point Status and Control Register): 0x82004000

SPRs (Special Purpose Registers):
           Machine State (msr) : 0x0002F030
                Condition (cr) : 0x22422048
      Instruction Pointer (ip) : 0x6F640A5C
       Xtended Exception (xer) : 0x00000007
                   Count (ctr) : 0x01811144
                     Link (lr) : 0x6F6190EC
            DSI Status (dsisr) : 0x00800000
            Data Address (dar) : 0x00000022

680x0 emulated registers:
DATA: 51110770 00000003 00000000 00000000 00000000 00000000 00000000 00000000 
ADDR: 5864FAD4 53CB78A8 00000000 00000000 00000000 00000000 00000000 51D48B90 
FPU0:                0                0                0                0 
FPU4:                0                0                0                0 

Symbol info:
Instruction pointer 0x6F640A5C belongs to module "YAM" (PowerPC) 
Symbol: RestartTimer + 0x70 in section 1 offset 0x000A3A3C

Stack trace:
    RestartTimer()+0x70 (section 1 @ 0xa3a3c)
    CloseTempFile()+0x11C (section 1 @ 0x7c0cc)
    m_UpdateNotifyWindow_OM_DISPOSE()+0x34 (section 1 @ 0xe9b0c)
    UpdateNotifyWindowDispatcher()+0x128 (section 1 @ 0xa62bc)
    muimaster.library:CustomClassDispatcher()+0xA0 (section 1 @ 0x20f8)
    native kernel module intuition.library.kmod+0x0001807c
    native kernel module intuition.library.kmod+0x000182a0
    native kernel module intuition.library.kmod+0x00008328
    muimaster.library:MUI_DisposeObject()+0x44 (section 1 @ 0x1fe0)
    muimaster.library:m_Application_DISPOSE()+0x174 (section 1 @ 0xf420)
    muimaster.library:ApplicationDispatcher()+0x3F4 (section 1 @ 0x15790)
    native kernel module intuition.library.kmod+0x0001807c
    native kernel module intuition.library.kmod+0x000182a0
    native kernel module intuition.library.kmod+0x000081e0
    m_YAMApplication_OM_DISPOSE()+0xA8 (section 1 @ 0xfae24)
    YAMApplicationDispatcher()+0x264 (section 1 @ 0xa5af0)
    muimaster.library:CustomClassDispatcher()+0xA0 (section 1 @ 0x20f8)
    native kernel module intuition.library.kmod+0x0001807c
    native kernel module intuition.library.kmod+0x000182a0
    native kernel module intuition.library.kmod+0x00008328
    muimaster.library:MUI_DisposeObject()+0x44 (section 1 @ 0x1fe0)
    muimaster.library:libstub_MUI_DisposeObject()+0x14 (section 1 @ 0xb34)
    Terminate()+0x828 (section 1 @ 0x2970)
    yam_exitfunc()+0x34 (section 1 @ 0x30dc)
    native kernel module newlib.library.kmod+0x00040184
    native kernel module newlib.library.kmod+0x00016e14
    AB_GotoEntry()+0x0 (section 1 @ 0x5e5c)
    native kernel module newlib.library.kmod+0x00001f4c
    native kernel module newlib.library.kmod+0x00002be0
    native kernel module newlib.library.kmod+0x00002d5c
    _start()+0x170 (section 1 @ 0x170)
    native kernel module dos.library.kmod+0x0001b524
    native kernel module kernel+0x00036290
    native kernel module kernel+0x00036310
    

PPC disassembly:
 6f640a54: 57a4843e   rlwinm            r4,r29,16,16,31
 6f640a58: 54a3843e   rlwinm            r3,r5,16,16,31
*6f640a5c: b3bb0022   sth               r29,34(r27)
 6f640a60: b09b0020   sth               r4,32(r27)
 6f640a64: 38000009   li                r0,9

System information:

CPU 
 Model: AMCC PPC440EP V1.3 
 CPU speed: 799 MHz 
 FSB speed: 133 MHz 
 Extensions:  

Machine 
 Machine name: Sam440EP 
 Memory: 1048576 KB 
 Extensions: bus.pci

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2010-12-23 08:44:16 +0100**

___
**Attachment added:** [`Crashlog_YAM_2010-12-23_00-11-27.txt`](https://yam.ch/attachments/242/Crashlog_YAM_2010-12-23_00-11-27.txt) (32.7 KiB)
This is the complete log

**Comment by tboeckel** [comment]
**Originally on 2010-12-23 23:28:44 +0100**

___
In (79ade1d):
 * YAM_UT.c: when closing a temp file which was never opened before YAM did
  nevertheless try to delete this file which of course must fail. As a
  consequence this file was treated as a zombie file furtheron. When all this
  happened while YAM was shutting down adding the file to the zombie file list
  caused a crash, because the timer which then got restarted had been deleted
  already. Now only existing files will be treated as zombie files. This
  closes #242.

**Comment by tboeckel** [comment]
**Originally on 2010-12-23 23:32:07 +0100**

___
In (1a1184f):
 * YAM_UT.c: when closing a temp file which was never opened before YAM did
  nevertheless try to delete this file which of course must fail. As a
  consequence this file was treated as a zombie file furtheron. When all this
  happened while YAM was shutting down adding the file to the zombie file list
  caused a crash, because the timer which then got restarted had been deleted
  already. Now only existing files will be treated as zombie files. This
  closes #242.

**Comment by tboeckel** [comment]
**Originally on 2010-12-23 23:36:31 +0100**

___
Please add crash logs as attachments only instead of as a part of the description.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2010-12-24 01:09:26 +0100**

___
How professional, Thore thanks a lot for the quick fix !

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2010-12-24 01:11:21 +0100**

___
Yes, sorry i forgot this and when i remember it bug was already submitted :-)))
