### ISSUE TITLE
Crash after deletion

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#243]
**Originally by @raziel- on 2010-12-23 14:21:06 +0100**

___
YAM2.6p1 - AmigaOS4.1 (all updates)

I got two times a crash after deleting a mail.
I was able to reproduce it, the problem was copying a mail to a password protected folder *before* which worked very well, but deleting any mail afterwards leads to crash

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2010-12-23 14:21:44 +0100**

___
**Attachment added:** [`Crashlog_YAM_2010-12-23_14-07-29.txt`](https://yam.ch/attachments/243/Crashlog_YAM_2010-12-23_14-07-29.txt) (36.6 KiB)
Grim Reaper

**Comment by tboeckel** [comment]
**Originally on 2010-12-23 14:43:15 +0100**

___
This might be related to the recently fixed ticket #234.

If possible please try to reproduce this issue with the current YAM 2.7-dev.

**Comment by tboeckel** [comment]
**Originally on 2010-12-23 23:44:14 +0100**

___
I tried to reproduce this issue with the current YAM 2.7-dev but I was not able to force a crash at all. I did the following:

1. set up a password for a folder
2. copy some mails to this folder
3. restarted YAM to let it forget about the formerly entered password
4. copy another mail to that folder, entering the password was necessary for this
5. go to the folder and open a mail in a separate read window
6. delete this mail

At least this is how I understand your description. If I did anything wrong please tell me.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2010-12-24 10:45:18 +0100**

___
Not entirely

steps 1 through 4 were correct

step 5 would be to not enter the directory (at least thats not what i did but in general it shouldn't matter) but delete whatever mail in whatever other drawer.

i.e. i copy a mail from "incoming" to "personal" (password) and then delete a mail from "outdated"

**Comment by tboeckel** [comment]
**Originally on 2011-01-04 19:44:16 +0100**

___
I am sorry, but I cannot reproduce this issue, neither with YAM 2.7-dev nor with YAM 2.6p1. Does it happen every time, or does the crash occur more or less randomly?

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2011-01-04 20:55:55 +0100**

___
I can't reproduce it either anymore :-/

It could maybe have been a crash from the xpk module that does the crypting?
I am using xpkIDEA which is still 68k and might be the reason why YAM came up with the crash.

This is only brainstorming of course

**Comment by tboeckel** [comment]
**Originally on 2011-01-10 11:11:49 +0100**

___
@raziel-
> I am using xpkIDEA which is still 68k and might be the reason why YAM came up with the crash.

This is definitely a new fact you did not mention before. I just tried plain password protection for the folder, no XPK compression/encryption. Of course a buggy XPK sublibrary may cause any kind of funny effects, both directly and indirectly. YAM can only rely on the assumption that the XPK package is working properly.

I'll close this ticket for the moment as "works for me". If the crash happens again for you then feel free to reopen it.
