### ISSUE TITLE
Config -> TCP/IP -> POP3 automatic Port setting failure

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#244]
**Originally by _anonymous_ on 2011-01-10 19:16:26 +0100**

___
## Summary
Config -> TCP/IP -> POP3 automatic Port setting failure
switch away from SSL and you get port 995

## Steps to reproduce
 1. goto Config -> TCP/IP -> POP3
 2. use secure connection: click on "no" you get port 110
 3. now click on "TLS" you get port 110
 4. click on "SSL" you get port 110
 5. click again on "no" or "TLS" you get port 995

## Expected results
if you click on SSL you have to set port 995 (default for ssl connection)
if you click on TLS you have to set port 110 (default for tls connection)
if you click on no you have to set port 110 (default for non secure connection)

## Actual results
see "Steps to reproduce"

**Comment by tboeckel** [comment]
**Originally on 2011-01-13 08:11:10 +0100**

___
In (4fd8472):
 * YAM_CO.c: changing the security flags of a POP3 server used the former
  settings to generate the new port number which resulted in a wrong port
  number most of the time. This closes #244.
