### ISSUE TITLE
Warn about incompatible filetype when importing mails

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#247]
**Originally by _mario@cattaneo.de_ on 2011-01-22 19:47:12 +0100**

___
Try to import eg. S:Startup-Sequence (I know, you have to change the filter to do so, but this is just an example ;)).
YAM will silently ignore that file, ie. do nothing. Would be nice, if there was a requester informing the user that something went wrong (incompatiible/corrupted...) with the selected file.

**Comment by tboeckel** [comment]
**Originally on 2011-01-23 16:17:31 +0100**

___
In (37f0a9a):
 * MailImport.c, locale/YAM.cd: trying to import mails from an unknown file now
  outputs an appropriate error message. This closes #247.
