### ISSUE TITLE
Preselection window closes immediately

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#248]
**Originally by _mario@cattaneo.de_ on 2011-01-23 01:06:11 +0100**

___
YAM 2.7-dev [OS4/PPC] (22.01.2011) Copyright (C) 2000-2011 YAM Open Source Team

I have some accounts set to "always", but recently the preselection window does open and close immediatley without performing any action - instead of waiting for user input.

**Comment by tboeckel** [comment]
**Originally on 2011-01-23 14:04:30 +0100**

___
But there are some new mails which could be preselected, not just old mails. Correct?

In any case, could you please provide a NET debug log?

**Comment by tboeckel** [comment]
**Originally on 2011-01-24 10:37:53 +0100**

___
Replying to thboeckel:

> In any case, could you please provide a NET debug log?

Please provide a NET+THREAD debug log. NET alone is not enough.

**Comment by tboeckel** [comment]
**Originally on 2011-01-24 12:11:15 +0100**

___
In (5ef45af):
 * tcp/Connection.c: the new timeout mechanism for gethostbyname() could have
  left the abort signal pending which in turn caused the preselection window
  to be closed immediately. Now the signal is properly cleared.
  This closes #248.

**Comment by tboeckel** [comment]
**Originally on 2011-01-24 12:13:16 +0100**

___
No need for a log anymore. I figured this out myself in the meantime. Please check again with the next nightly build and reopen this ticket if the issue persists.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2011-01-24 12:22:34 +0100**

___
**Attachment added:** [`sashimi.out`](https://yam.ch/attachments/248/sashimi.out) (9.9 KiB)

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2011-01-24 12:23:14 +0100**

___
Yes, there are new mails.

Find log attached.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2011-01-24 12:24:00 +0100**

___
argh. :)
