### ISSUE TITLE
Global "preselection"-setting has no effect

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#249]
**Originally by _mario@cattaneo.de_ on 2011-01-23 01:10:54 +0100**

___
YAM 2.7-dev [OS4/PPC] (22.01.2011) Copyright (C) 2000-2011 YAM Open Source Team

Seems YAM only takes the setting for each account into account.
The global Setting is of no use (anymore).

So maybe remove it, or could/shoud the account-setting have a "default"-setting, which means, when set, the globals setting is used.

**Comment by tboeckel** [comment]
**Originally on 2011-01-23 14:07:03 +0100**

___
Erm, which "global" setting are you talking about? There is no global setting anymore, just per account only.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2011-01-24 12:07:02 +0100**

___
Sorry, mixed it up with the transfersettings.
