### ISSUE TITLE
Anon remailer not working, time to update the thing again

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#25]
**Originally by _tactica@users.sourceforge.net_ on 2010-03-03 16:55:19 +0100**

___
Just for "fun" I tried the xganon remailer currently suggested by YAM sending an email to myself, hours ago, and am still waiting to get anything back. The xganon homepage itself is a wonderful example of saying nothing with a lot of words.

I'd suggest to drop the feature completely as it's blatantly open to abuse and hardly useful for any legit purposes but I have already taken for granted that the remailer will just be updated, so go ahead.

**Comment by jens-maus** [comment]
**Originally by _tactica_ on 2010-03-03 16:56:13 +0100**

___
Just for the record, I just got this:

```
The following message to <remailer@remailer.xganon.com> was undeliverable.
The reason for the problem:
5.4.7 - Delivery expired (message too old) 'timeout'
```

I still think we'd better drop the feature altogether.

**Comment by jens-maus** [comment]
**Originally on 2010-03-03 16:56:40 +0100**

___
Ok, I will discuss that with Thore ASAP and see if we really should drop the feature or have a look for a new default remailer to be configured.

**Comment by jens-maus** [comment]
**Originally on 2010-03-07 17:22:23 +0100**

___
I would opt to completely remove the remailer stuff from YAM as well as there are probably really no users using that feature anymore (have there been any at all)? So I will flag this ticket to get this addressed in the cycle of YAM 2.7

**Comment by tboeckel** [comment]
**Originally on 2010-11-17 13:58:00 +0100**

___
In (cd41f76):
 * misc: completely removed the support for anonymous remailers as suggested
  in ticket #25. YAM should not be used to produce even more junk mails.
  This closes #25.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-11-17 23:11:30 +0100**

___
The new line 774 in trunk/src/YAM_EA.c should be
static const char *SecurityCycleEntries[5]; instead of
static const char *SecurityCycleEntries[4];
beacuse the array has 5 entries.

**Comment by tboeckel** [comment]
**Originally on 2010-11-18 07:58:46 +0100**

___
Very well spotted! Many thanks! It's a real PITA that the compiler does not warn about such fundamental error.
