### ISSUE TITLE
New message - "insert file" at current cursor position

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#250]
**Originally by _mlunk@web.de_ on 2011-01-24 07:50:09 +0100**

___
## Summary
Insert the chosen textfile at the current cursor position.
## Steps to reproduce
Create a new message. Place the text cursor at your wanted position. Click button "insert file" ("Datei einfügen" in German version). YAM will ignore this cursor position and insert text at the beginning of the mail instead.

## Expected results
The contents of the selected file should be inserted at the current cursor position selected by the user beforehand and not at the first character of your message.

**Comment by tboeckel** [comment]
**Originally on 2011-01-24 08:10:32 +0100**

___
This is working for me as expected and exactly as you describe it as expected results with both YAM 2.6p1 and YAM 2.7-dev.

**Comment by jens-maus** [comment]
**Originally by _mlunk@web.de_ on 2011-01-25 07:58:07 +0100**

___
This bug appears in both 2.6p1 and 2.7-dev MOS versions. I counterchecked with OS3 version on MOS 2.7 and with that the bug does not appear. OS3 version inserts the file at the correct position into the mailtext. So handling the insertion of text in MOS version works different from OS3 version.

**Comment by jens-maus** [comment]
**Originally by _mlunk@web.de_ on 2011-01-25 07:58:57 +0100**

___
This bug appears in both 2.6p1 and 2.7-dev MOS versions. I counterchecked with OS3 version on MOS 2.7 and with that the bug does not appear. OS3 version inserts the file at the correct position into the mailtext. So handling the insertion of text in MOS version works different from OS3 version.

**Comment by jens-maus** [comment]
**Originally by _mlunk@web.de_ on 2011-01-25 08:04:42 +0100**

___
This bug appears in both 2.6p1 and 2.7-dev MOS versions. I counterchecked with OS3 version on MOS 2.7 and with that the bug does not appear. OS3 version inserts the file at the correct position into the mailtext. So handling the insertion of text in MOS version works different from OS3 version.

**Comment by jens-maus** [comment]
**Originally by _mlunk@web.de_ on 2011-01-25 08:04:54 +0100**

___
This bug appears in both 2.6p1 and 2.7-dev MOS versions. I counterchecked with OS3 version on MOS 2.7 and with that the bug does not appear. OS3 version inserts the file at the correct position into the mailtext. So handling the insertion of text in MOS version works different from OS3 version.

**Comment by jens-maus** [comment]
**Originally by _mlunk@web.de_ on 2011-01-25 08:05:58 +0100**

___
This bug appears in both 2.6p1 and 2.7-dev MOS versions. I counterchecked with OS3 version on MOS 2.7 and with that the bug does not appear. OS3 version inserts the file at the correct position into the mailtext. So handling the insertion of text in MOS version works different from OS3 version.

**Comment by jens-maus** [comment]
**Originally by _mlunk@web.de_ on 2011-01-25 08:21:22 +0100**

___
This bug appears in both 2.6p1 and 2.7-dev MOS versions. I counterchecked with OS3 version on MOS 2.7 and with that the bug does not appear. OS3 version inserts the file at the correct position into the mailtext. So handling the insertion of text in MOS version works different from OS3 version.

**Comment by jens-maus** [comment]
**Originally by _mlunk@web.de_ on 2011-01-25 08:21:24 +0100**

___
This bug appears in both 2.6p1 and 2.7-dev MOS versions. I counterchecked with OS3 version on MOS 2.7 and with that the bug does not appear. OS3 version inserts the file at the correct position into the mailtext. So handling the insertion of text in MOS version works different from OS3 version.

**Comment by jens-maus** [comment]
**Originally by _mlunk@web.de_ on 2011-01-25 08:21:26 +0100**

___
This bug appears in both 2.6p1 and 2.7-dev MOS versions. I counterchecked with OS3 version on MOS 2.7 and with that the bug does not appear. OS3 version inserts the file at the correct position into the mailtext. So handling the insertion of text in MOS version works different from OS3 version.

**Comment by tboeckel** [comment]
**Originally on 2011-01-25 08:22:25 +0100**

___
In (44b8122):
 * mui/WriteWindow.c, YAM_COg.c: fixed several places where invoking the method
  the MUIM_TextEditor_InsertText was missing the last parameter to specify the
  position where to insert the text. This caused random effects to happen,
  like inserting the text at the beginning. This closes #250.

**Comment by jens-maus** [comment]
**Originally by _mlunk@web.de_ on 2011-12-16 13:30:27 +0100**

___
Verified to work with nightly build of Dec, 16, 2011.
