### ISSUE TITLE
message sent while editing - yam 2.5

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#252]
**Originally by _lf2@tim.it_ on 2011-01-31 00:21:31 +0100**

___
Hi, I encountered a "strage" behavior, a message was sent while editing.
The steps were:
1. write a message, with external editor
2. save the message, into "outgoing"
3. edit the previously saved message, this opens the external editor, then make changes to the message
4. "accidentally" click the "send messages" icon, you will se the "previously saved" message to be sent, while there is an active window editing that message
I think this shouldn't happen. If I am editing a message, probably the previous "incomplete" version should not be sent, unless I save the new version.

**Comment by tboeckel** [comment]
**Originally on 2011-02-01 10:38:55 +0100**

___
In (e718ccc):
 * YAM_MA.c: hitting the "Send" button will no longer send out mails which are
  currently being edited. This closes #252.
