### ISSUE TITLE
indexing bug: subfolder "topmost" overflow

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#253]
**Originally by _arcstrait@gmail.com_ on 2011-01-31 00:22:52 +0100**

___
## Summary
The folder menu appears munged if using a grand number of folders and folder groups. Specifically, folders from folder groups are listed out-of-group at top above INBOX for no apparent reason.
## Steps to reproduce
 1. Generate a folder group.
 2. Generate 2 folder groups in the folder group.
 3. Generate 1 folder apiece in the secondary folder groups.
 4. Generate 11 folders in the first folder group.

That gives one folder group with two folder groups inside bearing one folder apiece, and an additional eleven folders archived inside of the first folder group. 

## Expected results

The list of eleven folders should overflow at count of six folders as folders above the INBOX.

## Actual results
n/a
## Regression
no comprehende
## Notes
Perhaps the maximum number of folders of a subgroup has been defined, perhaps at five?

Severity: Scary!

**Comment by tboeckel** [comment]
**Originally on 2012-04-26 17:06:16 +0200**

___
YAM's folder management has been enhanced in YAM 2.7. Currently I am not able to reproduce this issue myself. Everything is working as expected for me. If you are able to reproduce this issue using YAM 2.7 then please reopen this ticket.
