### ISSUE TITLE
DSI crash trying to check for updates

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#255]
**Originally by _anonymous_ on 2011-03-03 13:23:03 +0100**

___
I get a DSI crash trying to check for updates (from YAM menu)

I'm using the latest YAM 2.7-Dev (3-Mar-2011) on AmigaOS 4.1 Update 2

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2011-03-03 13:18:40 +0100**

___
**Attachment added:** [`Crashlog_YAM_2011-03-03_10-26-02.txt`](https://yam.ch/attachments/255/Crashlog_YAM_2011-03-03_10-26-02.txt) (31.3 KiB)

**Comment by tboeckel** [comment]
**Originally on 2011-03-07 11:53:28 +0100**

___
I tried to reproduce this issue several times by now, but could not make YAM crash. For me this works rock solid on both AmigaOS4 and AmigaOS3.

Are you sure the crash was not caused by some other application gone crazy and trashing YAM's memory?

**Comment by tboeckel** [comment]
**Originally on 2011-03-13 11:17:09 +0100**

___
I am still not able to reproduce this issue, nor with the currently nightly build, nor with my own build.

Please provide a NET debug log for more details.

**Comment by tboeckel** [comment]
**Originally on 2011-03-14 21:53:30 +0100**

___
Please check again with the next nightly build. Perhaps the OM_SET -> MUIM_Set change fixes this issue.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2011-03-15 15:26:33 +0100**

___
Tried latest build and now it works perfectly so you can consider this bug as fixed, thanks ! :-)

**Comment by tboeckel** [comment]
**Originally on 2011-03-15 15:36:33 +0100**

___
Fixed in [5670].
