### ISSUE TITLE
Crash after downloading mail

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#256]
**Originally by _hypexed@yahoo.com.au_ on 2011-03-11 17:12:49 +0100**

___
Hello.

While YAM was loaded I started it downloading my emails while I switched to Workbench. I then got a Grim Reaper! I went back to the YAM screen and the window had came up telling me it had downloaded. So it looks like it crashed after downloading the mail and finishing the operation. This bug may be rare as I haven't seen it before and may be hard to reproduce.

Attached is crash log from my AmigaOS4.1.2 system.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2011-03-11 15:22:20 +0100**

___
**Attachment added:** [`Crashlog_YAM_2011-03-12_00-41-30.txt`](https://yam.ch/attachments/256/Crashlog_YAM_2011-03-12_00-41-30.txt) (29.1 KiB)
Crash

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2011-03-11 15:23:34 +0100**

___
**Attachment added:** [`Crashlog_YAM_2011-03-12_00-41-30.2.txt`](https://yam.ch/attachments/256/Crashlog_YAM_2011-03-12_00-41-30.2.txt) (29.1 KiB)
IP was messed up here

**Comment by jens-maus** [comment]
**Originally by _Damien Stewart <hypexed@yahoo.com.au>_ on 2011-03-12 15:46:17 +0100**

___
**Attachment added:** [`Crashlog_YAM_2011-03-12_00-42-06.txt`](https://yam.ch/attachments/256/Crashlog_YAM_2011-03-12_00-42-06.txt) (28.9 KiB)

**Comment by jens-maus** [comment]
**Originally by _Damien Stewart <hypexed@yahoo.com.au>_ on 2011-03-14 10:39:43 +0100**

___
Sorry added log twice. The new one has the log where the instruction pointer goes haywire. :-)

But I know by the time that happens such a log is  practically??useless.

**Comment by tboeckel** [comment]
**Originally on 2011-03-14 10:56:53 +0100**

___
This kind of crash is indeed quite hard to catch. I suppose YAM's "keep the connection alive" feature is causing this, since the crashlog points to that code location. You might want to try to set the variable "KeepAliveInterval" in YAM's advanced section to zero using a text editor. The "keep alive" facility is used for preselection only, so if you don't use that there should be no negative impact for you.

Another possible solution would be to try the current nightly builds of YAM 2.7-dev. Since there have been substantial modifications to the POP3 stuff it is very likely that the bug has been fixed there already.

**Comment by jens-maus** [comment]
**Originally by _Damien Stewart <hypexed@yahoo.com.au>_ on 2011-03-14 15:39:38 +0100**

___
Okay thanks for the info. I'll check that one out.

 I am usually a user of the nightly builds but once I have a stable version I like to stick with it.  And the builds usually time out, mostly at the worse time. Forcing me to update it again. :-)

**Comment by tboeckel** [comment]
**Originally on 2011-05-16 14:24:34 +0200**

___
Any news on this issue?

**Comment by tboeckel** [comment]
**Originally on 2012-04-26 17:12:05 +0200**

___
Please try to reproduce this issue with YAM 2.7. If it still happens then please reopen this ticket.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2012-05-14 18:14:11 +0200**

___
Hi I just tested with YAM 2.7. It looks fine. Howeever I did send myself an email and attempt to download it while quickly switchng to my Workbench. :-)

Not exactly the same. Will try again when I know I have mail just in case.
