### ISSUE TITLE
Crash when checking for nightly update

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#257]
**Originally by _mario@cattaneo.de_ on 2011-03-12 13:56:47 +0100**

___
YAM 2.7-dev [OS4/PPC] (07.03.2011) Copyright (C) 2000-2011 YAM Open Source Team

Crashes when checks for updates.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2011-03-12 13:57:11 +0100**

___
**Attachment added:** [`Crashlog_YAM_2011-03-12_13-51-33.txt`](https://yam.ch/attachments/257/Crashlog_YAM_2011-03-12_13-51-33.txt) (26.9 KiB)

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2011-03-12 17:56:31 +0100**

___
Duplicate to [http://trac.yam.ch/ticket/255]

Wonder if people check open bug reports before submitting new...

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2011-03-12 18:05:42 +0100**

___
People do.
But a search for "crash" reveiled nothing.
So, guess what?

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2011-03-12 20:51:35 +0100**

___
...

[http://trac.yam.ch/search?q=crash]

quod erat demonstrandum

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2011-03-12 20:58:50 +0100**

___
You can write what you want. At the time there was no hit on "crash" wether due to database- or browser-problem,  whatever (not my eye-vision though)). Peroid.

**Comment by jens-maus** [comment]
**Originally on 2011-03-12 22:18:07 +0100**

___
Guys, please note that this is no forum here but a bug tracker. So please don't argue but keep attached to the facts. Thus, this is a duplicate of #255 and it doesn't matter why the reporter did not find the original ticket in first place.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2011-03-13 11:10:44 +0100**

___
...

[http://trac.yam.ch/search?q=crash]

quod erat demonstrandum

**Comment by tboeckel** [comment]
**Originally on 2011-03-13 11:17:34 +0100**

___
Everybody please switch over to #255.
