### ISSUE TITLE
Can't add a photo in address book/Alias

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#259]
**Originally by _s.hawamdeh@teletu.it_ on 2011-05-13 19:02:41 +0200**

___
If i try to select an image for a new contact in address book i always get a DSI crash.
I try with a simple jpg file

I use YAM 2.7 night build (2.5-dev-2011-04-22)

DSI crash in attachment

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2011-05-13 19:03:00 +0200**

___
**Attachment added:** [`Crashlog_YAM_2011-05-13_18-51-01.txt`](https://yam.ch/attachments/259/Crashlog_YAM_2011-05-13_18-51-01.txt) (30.9 KiB)

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2011-05-13 19:07:22 +0200**

___
Ops me wrong can't edit ticket, i meant version 2.7 of course not 2.5 !

2.7-dev-2011-04-22

**Comment by tboeckel** [comment]
**Originally on 2011-05-14 20:39:28 +0200**

___
In (c8c4467):
 * mui/UserPortraitGroup.c: added missing parameter to method call. This closes #259.
