### ISSUE TITLE
Ghost/disable "get mail" when there is no active account

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#261]
**Originally by _mario@cattaneo.de_ on 2011-05-29 15:18:30 +0200**

___
Think it would make sense to ghost/disable "get mail" (both toolbar and menu) when there is no "active" pop-accopunt.
A rare case, I know... :)

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 07:48:57 +0200**

___
In (48c0435):
 * YAM_CO.c, mui/MainWindowToolbar.c: the Get and Send toolbar buttons will now be disabled in case there is no active POP3 or SMTP server available. This closes #261.

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 11:44:55 +0200**

___
**Release Note:**
The Get and Send toolbar buttons will now be disabled in case there is no active POP3 or SMTP server available.
