### ISSUE TITLE
Prefs/Read --> Selecting colors cause freeze

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#262]
**Originally by _s.hawamdeh@teletu.it_ on 2011-05-30 18:50:48 +0200**

___
If i try to change the color of quotes/URL color in YAM (Prefs/Read) i have an instant freeze.

I'm using the latest YAM night build (2011-05-15) and latest MUI 3.9 on AmigaOS 4.1 Update 2 (Sam Flex 800)

**Comment by tboeckel** [comment]
**Originally on 2011-06-06 14:30:38 +0200**

___
Is there anything on the serial line? I never encountered such a freeze when trying to modify a pen. YAM uses the global MUI standard approach here, nothing fancy or special.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2011-06-07 12:15:30 +0200**

___
Yes it happen only clicking on "Old quotes" (Prefs/Read) but i can't be able to catch any output after resetting (almost using the dumpdebugbuffer command) as i need to turn off my Amiga because keyboard doesn't work :-(

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2011-06-27 07:31:42 +0200**

___
Yes it happen only clicking on "Old quotes" (Prefs/Read) but i can't be able to catch any output after resetting (almost using the dumpdebugbuffer command) as i need to turn off my Amiga because keyboard doesn't work :-(

**Comment by tboeckel** [comment]
**Originally on 2011-06-29 09:42:47 +0200**

___
What color spec is set for the URL color? I have set it to red and the line in the configuration looks like this:

ColorURL         = rBEBEBEBE,00000000,00000000 

Just load YAM's configuration file with your favorite text editor and look up that line in the [Read] section.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2011-06-29 18:01:18 +0200**

___
Ok here is all what i have in config:

[Read]
ShowHeader       = 1
ShortHeaders     = (From|To|Cc|BCC|Date|Subject)
ShowSenderInfo   = 2
WrapHeader       = N
SigSepLine       = 2
ColorSignature   = m4
ColoredText      = m5
Color1stLevel    = r456b456b,a516a516,ffffffff
Color2ndLevel    = m6
Color3rdLevel    = m3
Color4thLevel    = m1
ColorURL         = p6
DisplayAllTexts  = Y
FixedFontEdit    = Y
UseTextStyles    = Y
TextColorsRead   = Y
DisplayAllAltPart= N
MDNEnabled       = Y
MDN_NoRecipient  = 3
MDN_NoDomain     = 3
MDN_OnDelete     = 3
MDN_Other        = 3
MultipleWindows  = Y
StatusChangeDelay= 1000
ConvertHTML      = Y
LocalCharset     = ISO-8859-15
DetectCyrillic   = Y
MapForeignChars  = Y
GlobalMailThreads= N

I download latest nighly and it freeze on the same place ("Old quotes" color in Config -->Prefs/Read)

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2011-10-01 13:30:43 +0200**

___
Seems fixed on AmigaOS 4.1 Update 3 and latest MUI 3.9 release :-)
