### ISSUE TITLE
"Preview" of sound played for new mail not working in prefs

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#263]
**Originally by _mario@cattaneo.de_ on 2011-06-06 02:21:50 +0200**

___
Pressing "play" in prefs/new mail/notification/sound

only produces an error message:

"Beim Abspielen der Tondatei '0' ist ein Fehler aufgetreten."

Seems it always wants to play file "0", no matter what is set to.

Actual sound playing, when new mail is received works, just not the "preview"

**Comment by tboeckel** [comment]
**Originally on 2011-06-06 08:40:01 +0200**

___
In (7dcf479):
 * YAM_COg.c: added missing parameter for MUIM_CallHook and an empty string
  check to avoid trying to play non-existent sound files. This closes #263.
