### ISSUE TITLE
Email not Base64 decoding

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#264]
**Originally by @chris-y on 2011-06-21 07:49:46 +0200**

___
The attached message displays in YAM 2.6p1 as a Base64 encoded block, rather than a correctly decoded message.  I've checked it with the latest nightly build (2011-06-07) and the problem still exists in that version.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2011-06-21 00:14:19 +0200**

___
**Attachment added:** [`msg.lha`](https://yam.ch/attachments/264/msg.lha) (2.7 KiB)
problem message file

**Comment by tboeckel** [comment]
**Originally on 2011-06-21 08:36:44 +0200**

___
YAM will not decode the mail because the header is missing the MIME-Version line. The MIME standard requires this line to detect MIME conformant mails.

Please refer to this document: http://www.ietf.org/rfc/rfc2049.txt

I will modify YAM to output a warning and decode the mail nevertheless. But please keep in mind that the bug is located on the sending side to build a non-MIME-conformant mail. YAM is just following the official rules.

**Comment by tboeckel** [comment]
**Originally on 2011-06-21 08:38:10 +0200**

___
In (ca0a46a):
 * YAM_RE.c: non-MIME-conformant mails without a MIME-Version header line are
  no longer displayed as raw 7bit ASCII text but will be decoded as usual.
  However, a warning about the missing header line will be presented to give
  the user a hint about that fact. Non-MIME-conformant mail clients (like that
  Android thingy) are becoming more and more common these days and it is
  better to have a possibly malformed mail text than a raw base64 dump. This
  closes #264.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2011-06-27 07:31:29 +0200**

___
That works great, thanks.  However a message with none of the MIME-Version, Content-Type or Content-Transfer-Encoding headers is also causing YAM to show the warning - I think it should be treating this as a plain non-MIME message as none of the MIME headers are present.

**Comment by tboeckel** [comment]
**Originally on 2011-06-27 07:37:22 +0200**

___
I just stripped a mail from all that lines and I get no error with the latest nightly build (26.6.2011). If this is happening for you nevertheless then please provide an example mail.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2011-06-27 21:38:19 +0200**

___
It's fine now, thanks.
