### ISSUE TITLE
"Mark as read" filter action

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#265]
**Originally by @chris-y on 2011-06-27 21:37:48 +0200**

___
This is a request to add a "mark as read" function to the mail filtering actions.

Ideally it should be able to change status to any of read, unread, new, marked, spam etc.

**Comment by tboeckel** [comment]
**Originally on 2011-06-29 11:16:25 +0200**

___
In (3e24b46):
 * YAM_FI.c, YAM_CO.c: implemented new filter actions to mark a filtered mail
  as (un)marked, (un)read or as spam/not spam. This closes #265.
