### ISSUE TITLE
"IN" filters do not work in YAM nightly build

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#266]
**Originally by @chris-y on 2011-06-27 21:38:08 +0200**

___
A filter set to search a file does not work in the latest nightly build 26-06-2011.  This function did work in YAM 2.6p1.

To reproduce:
Set up a new filter with the following details:

Comparison:
Search in From
IN .test-addresses
Click on the arrow next to .test-addresses and type an email address to apply the filter to.  Save and close the new file.

Action:
Move to Folder

Clicking Filter will not filter the expected email(s).  Setting a From filter with an address, rather than creating a file with a list of addresses does work as expected however.

Snoopy reports the file is getting opened, so that isn't the cause of the problem:
00036 : YAM             : o.k. # Open(".test-addresses",OLD)[0x15DF1EC0] [222uS]

**Comment by tboeckel** [comment]
**Originally on 2011-06-28 10:31:50 +0200**

___
Ok, this was an easy one. First of all, searching using a pattern file was really abandoned when fast Boyer-Moore string search was introduced. Second, searching using a pattern file definitely requires AmigaDOS patterns to be used.

**Comment by tboeckel** [comment]
**Originally on 2011-06-28 10:32:21 +0200**

___
In (08d291f):
 * YAM_FI.c, mui/SearchControlGroup.c: doing a search with a pattern file is now
  working again, but it must be done using AmigaDOS patterns. Hence these are
  activated automatically now. This closes #266.
