### ISSUE TITLE
Reload arrangement crash

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#269]
**Originally by _s.hawamdeh@teletu.it_ on 2011-07-24 14:12:55 +0200**

___
I get a crash trying to reload the arrangement (column at the left) with the RMB functionality

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2011-07-24 14:13:19 +0200**

___
**Attachment added:** [`Crashlog_YAM_2011-07-08_14-02-35.txt`](https://yam.ch/attachments/269/Crashlog_YAM_2011-07-08_14-02-35.txt) (38.2 KiB)

**Comment by tboeckel** [comment]
**Originally on 2011-07-25 10:49:03 +0200**

___
In (1781e81):
 * mui/MainFolderListtree.c: added some NULL pointer checks to the ChangeFolder
  method. This closes #269.
