### ISSUE TITLE
"New" Gadget in TCP/IP settings

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#27]
**Originally by _opionline@yahoo.de_ on 2010-03-03 17:00:40 +0100**

___
Hi Developers

IMHO the "New" Gadget in TCP/IP settings (below the account list) should be ghosed if a user reach the limit of 16 E-Mail accounts.

Currently YAM does a display beep if a user click on new and has already 16 entries in he list.

BTW: Why we have such limit at all? A much better solution for the issue is to remove the limit. :-)

**Comment by tboeckel** [comment]
**Originally on 1970-01-01 01:21:32 +0100**

___
(In #121) Removing #27 from the blocking list as there is no limit for the number of mail servers anymore.

**Comment by tboeckel** [comment]
**Originally on 2010-03-03 17:01:09 +0100**

___
Fixed in the next nightly build.

Changed this one into a change request so that it doesn't get lost. I think there is no obvious reason why the fixed array should not be converted to a linked list.

**Comment by jens-maus** [comment]
**Originally on 2010-03-06 07:07:51 +0100**

___
This will be addressed as soon as the multiple user identity support is implemented.

**Comment by tboeckel** [comment]
**Originally on 2010-12-06 16:03:07 +0100**

___
I think we can close this ticket since there is no limit for the mail servers anymore. Although the multiple user identity support is not yet implemented this ticket is fulfilled from my point of view.
