### ISSUE TITLE
Birthday feature broken

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#271]
**Originally by _mario@cattaneo.de_ on 2011-08-07 23:33:55 +0200**

___
YAM 2.7-dev [OS4/PPC] (05.08.2011) Copyright (C) 2000-2011 YAM Open Source Team

YAM no longer opens the write-window when you select "yes" when notified about a birthday

**Comment by tboeckel** [comment]
**Originally on 2011-08-15 08:01:16 +0200**

___
In (08442de):
 * mui/BirthdayRequestWindow.c: bumped the notification's parameter counter to the correct value. This closes #271.
