### ISSUE TITLE
Beim Postfach anlegen überschreibt  YAM das Hauptprogramm YAM

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#272]
**Originally by _b.pitthan@t-online.de_ on 2011-09-12 16:58:27 +0200**

___
Ich habe über Werkseinstellung ein neues Postfach angelegt ohne vorher dafür eine Schublade angelegt zuhaben. 
Beim Postfachanlegen habe ich das Postfach einen Namen gegeben. Daraufhin kommt ein Fenster mit der Info das dieses schon existiert (obwohl da keine Schublade mit dem Namen ist) und die Frage
ob es überschrieben werden soll. Wenn ich überschreibe ist YAM weg.

PS: Sorry, meine Englichkentnisse sind misserabel und deswegen in Deutsch.

Und auf diesen Weg auch ein dickes Dankeschön für die tolle Arbeit!

**Comment by tboeckel** [comment]
**Originally on 2011-09-13 13:02:37 +0200**

___
So richtig hilfreich ist auch deine deutsche Beschreibung nicht. Es fehlen einfach zu viele Details.

Ich hab genau das gleiche gerade ausprobiert und das Anlegen des Folders hat problemlos geklappt.

Hast du den Folder vielleicht ganz rein zufällig "YAM" genannt? Dann ist natürlich klar, daß die Datei mit gleichem Namen nach einer expliziten Rückfrage gelöscht wurde.

**Comment by jens-maus** [comment]
**Originally by _b.pitthan@t-online.de_ on 2011-09-14 22:34:37 +0200**

___
> Hallo trac@yam.ch,
>
> Nein, natürlich habe ich das Postfach nicht YAM genannt!
>
> Beschreibung:
> Ich klicke mit der rechten Maustaste in den Bereich der Postfächer.
> Wähle im erscheinenden Auzwahlfenster "Neues Postfach" aus.
> Im darauf folgenden Fenster  wähle ich Werkseinstellung aus.
> Im erscheinenden Fenster für die Postfacheinstellung schreibe ich
> im Feld "Name" das gewünschte Postfach (z.B. EBay) und unter Pfad
> wähle ich nur den angebotenen Pfad aus (bei mir Software:Internet/YAM) dann
> OK.
> Wenn ich dann die Postfacheinstellung mit OK verlasse kommt ein Fenster mit
> folgender Meldung:
>
> Eine Datei oder ein Verzeichnis mit dem angegebenen Pfad
> existiert bereits.
>
> Möchten Sie wirklich fortfahren?
> Ja                                         Nein
>
> Da noch keine Datei Ebay besteht klicke ich auf Ja. Bums ist YAM weg!
>
> Ich nehme mal an das die Pfadangabe YAM überschreibt.  Hier sollte eine
> Kontrolle im Programm vorhanden sein
> sodas nicht zugelassen wird das YAM rein zufällig wie oben beschrieben oder
> bewust überschrieben werden kann.
>
> Ich habe YAM auch schreibgeschützt, wird trotzdem von sich selber
> überschrieben.
>
> Mit Hochachtung für eure Arbeit
> Berny Pitthan

**Comment by tboeckel** [comment]
**Originally on 2011-09-21 22:22:53 +0200**

___
Es reicht nicht aus einfach nur einen Pfad auszuwählen, man muß dort auch ein neues Unterverzeichnis anlegen. Akzeptiert man einfach den vorgegebenen Pfad, dann versucht YAM dieses Verzeichnis als neues Verzeichnis für einen Mailfolder zu verwenden und löscht alle dort vorgefundenen Dateien. Ich gebe zu, daß die Nachfrage diese Vorgehen in keiner Weise erwähnt und ein Klick auf "Ja" dann unvorhersehbare Aktionen durchführt.

Also einfach nur entweder im ASL-Requester noch ein zusätzliches Verzeichnis angeben, oder anschließend einen Verzeichnisnamen hinzufügen (zB Software:Internet/YAM/EBay). Der Name "EBay" hat nichts mit dem Verzeichnisnamen an sich zu tun, sondern ist nur der Name, den YAM als Foldernamen anzeigt. Der Verzeichnisname kann vollkommen unabhängig davon gewählt werden.

Das Problem an der Sache ist halt, daß man auch von Hand ein Verzeichnis anlegen kann und YAM dann dieses Verzeichnis benutzen lassen kann. Deswegen können wir nicht einfach den Foldernamen an den ausgewählten Pfad anhängen. Aber vielleicht sollte man sich dieses Verhalten noch mal genauer überlegen. Zumindest würde ja nichts kaputt gemacht werden, so wie zur Zeit.

**Comment by tboeckel** [comment]
**Originally on 2012-04-27 13:41:46 +0200**

___
YAM 2.8-dev zeigt seit r5844 bei der Nachfrage bei einem existierenden Verzeichnis noch einmal den ausgewählten Pfad an, zusammen mit dem Hinweis, daß dieses Verzeichnis gelöscht wird. Für YAM 2.6(p1) und YAM 2.7 hilft das natürlich nicht direkt weiter. Da muß man halt leider wissen, was dieser Hinweis wirklich bedeutet und welche Folgen die Antwort "Ja" hat.
