### ISSUE TITLE
Yam 2.7

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#273]
**Originally by _rudi.timmer@gmail.com_ on 2011-09-14 16:47:55 +0200**

___
Hi,

I use Yam on my Amiga A1200 with os 3.1 every day.

I have found that when a user select show message on date first recieve that Yam this not save to the settings, when you exit Yam and start again then i have to show the date recieve again.

Als when a user disable the Regards signature this dont work also when you reply on a email again it show regards. even when disbled.

Thanks.

Greetings,

Rudi

**Comment by jens-maus** [comment]
**Originally on 2011-09-14 16:54:48 +0200**

___
Thanks for the report, first of all.

However, please in future obey to the rules when submitting a bug report. That means, please don't report two different things in one report and also use the bug report template the trac system is presenting to you when reporting a bug. Thus, please report in a step-by-step explaination style your problem.

Regarding your first item (message date sorting), please read the following FAQ item to understand how you can get YAM to save your sorting preference permanently:

http://faq.yam.ch/content/1/22/en/why-are-some-columns-of-the-mail-listview-always-resizing-automatically.html

Regarding the "Regards signature" please explain in more detail the problem.

**Comment by tboeckel** [comment]
**Originally on 2011-09-26 15:19:08 +0200**

___
What Jens wanted to point out is the fact that you must snapshot YAM's main window to save the list sort mode permanently. Otherwise any modification will be forgotten as soon as YAM is terminated.
