### ISSUE TITLE
yam nightly (29.09.2011) crashes when opening a mail

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#274]
**Originally by _Michael.Merkel@gmx.net_ on 2011-09-29 20:25:44 +0200**

___
## Summary
yam crashes (grim reaper) when opening a mail.
## Steps to reproduce
 1. start YAM
 2. open a folder
 3. open a mail
## Expected results
mail window open - can read mail
## Actual results
mail window open, empty.
grim reaper
## Notes
crashlog appended

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2011-09-29 20:33:56 +0200**

___
**Attachment added:** [`Crashlog_YAM_2011-09-29_20-15-57.txt`](https://yam.ch/attachments/274/Crashlog_YAM_2011-09-29_20-15-57.txt) (34.1 KiB)

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2011-10-01 15:42:11 +0200**

___
seems to be fixed with the current nightly!

regards...
michael

**Comment by tboeckel** [comment]
**Originally on 2011-10-01 16:06:56 +0200**

___
Yes, I know. It was a bad pointer access implemented by myself.
