### ISSUE TITLE
Date of birth always is wrong

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#280]
**Originally by _ejim@ono.com_ on 2011-12-08 12:24:04 +0100**

___
## Summary
I cannot introduce the birthdate in addresbook, because it always gets me an error message "type of date should be %e-%m-%Y"; Is not should be %d-%m-%Y ?
My language is spanish if it's related with type of date
## Steps to reproduce
 1.
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _ejim@ono.com_ on 2011-12-08 12:24:46 +0100**

___
**Attachment added:** [`image`](https://yam.ch/attachments/280/image) (155.1 KiB)
an image is better than 1000 words

**Comment by tboeckel** [comment]
**Originally on 2011-12-08 12:58:07 +0100**

___
Replying to [#280 natman]:

> I cannot introduce the birthdate in addresbook, because it always gets me an error message "type of date should be %e-%m-%Y"; Is not should be %d-%m-%Y ?
> My language is spanish if it's related with type of date

According to the Autodocs there are 3 possibilities:
  %d  - day number with leading zeros (01-31)
  %-d - day number without leading zeros (1-31)
  %e  - day number with leading spaces ( 1-31)

Currently YAM knows about %d only and will reject all dates which do not match the necessary specs.

**Comment by tboeckel** [comment]
**Originally on 2011-12-08 13:20:33 +0100**

___
Should be fixed in the next nightly build.
