### ISSUE TITLE
Copy to clipboard caused crash if nothing selected

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#281]
**Originally by _s.hawamdeh@teletu.it_ on 2011-12-15 07:41:15 +0100**

___
Right Mouse Button click into the addressbook window and then selecting one of the unit caused a DSI crash if nothing are selected (my addressbook is empty for this test)

Unit 0
Unit 1
Unit 2
Unit 3

All of them caused the same crash, luckly crash are skippable so it's not a huge issue and you can continue to use YAM

I use YAM 2.7-dev (9-december-2011) under AmigaOS 4.1 Update 3

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2011-12-15 07:41:43 +0100**

___
**Attachment added:** [`Crashlog_YAM_2011-12-15_07-30-02.txt`](https://yam.ch/attachments/281/Crashlog_YAM_2011-12-15_07-30-02.txt) (30.4 KiB)

**Comment by tboeckel** [comment]
**Originally on 2011-12-15 08:54:28 +0100**

___
Actually this is a bug in NListtree.mcc. I will try to implement a workaround until a fixed version is released.

**Comment by tboeckel** [comment]
**Originally on 2011-12-15 09:02:21 +0100**

___
In (b33d4cc):
 * mui/AddrBookListtree.c, MainFolderListtree.c: added a workaround for a bug in NListtree.mcc to avoid a NULL pointer access. This closes #281.
