### ISSUE TITLE
YAM overwrites/removes liked .index files

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#283]
**Originally by _mario@cattaneo.de_ on 2011-12-16 13:41:07 +0100**

___
YAM 2.7-dev [OS4/PPC] (22.11.2011) Copyright (C) 2000-2011 YAM Open Source Team

Tried to speed up things here a bit and so I am experimenting a little atm. ;)

So I tried to put my .index of incoming in RAM: and linked from incomming (on HDD) to it.
This seemed to have worked one time, but now everytime YAM updates .index, ie. looks for it and writes to it, the link is ereased and a .index is created on HDD.
Tried e.g. the same with Notepad, that is saving to a softlink and the result is that the new content is showing up at the target.
So I assume, this should be possible with YAM, too?
Thought links would be transparent, but somehow YAM here seems to be a special case?

**Comment by jens-maus** [comment]
**Originally on 2011-12-16 13:50:09 +0100**

___
Relinking certain files to some other directories/volumes is NOT supported by YAM. And I hardly believe that we would be able to catch all situations in YAM to get that supported (E.g. rebuilding an index will definitly erase your link). So better keep the .index files where they belong -> in the folder directory and don't mess with them.

So if you really want to speed up YAM even more, go out and buy yourself a SSD drive. :)

And please don't get me wrong. We simply can't support everything especially if links are not fully supported by all filesystems and operating system versions YAM is supposed to be run on.

**Comment by tboeckel** [comment]
**Originally on 2011-12-16 14:00:12 +0100**

___
Let me also add to this.

First of all, it is the task of dos.library to resolve such issues, not of YAM or any other application. If link support is broken (and this is a well known fact), then no application can do anything against that.

Second, recreating an index files means that YAM first deletes the old .index file (the link in your case) before it creates the new one (a real file again, located on your hard disk).
