### ISSUE TITLE
Sorting options/GUI layout not saved on exit

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#284]
**Originally by _s.hawamdeh@teletu.it_ on 2011-12-19 03:28:21 +0100**

___
YAM should be able to remember the mail disposition chosed manually by the user ("Message date" for example) at exit

Right now when a new mail arrive YAM dispose it automatically at the end of the list of the received messages, this is a bit unfriendly as any time you start YAM to read the latest message received you have to scroll the entire list of messages to find it!

In a ideal world users may choose their disposition clicking on the proper labels (messages list) then at exit all disposition can be saved somewhere automatically

But only about this kind of problem also an simple option in GUI would be ok, for example a new option in "Config --> New Mail" such as:

"Show new mail received on top of the list"

**Comment by jens-maus** [comment]
**Originally on 2011-12-19 09:20:58 +0100**

___
In fact, manually saving the column sorting is already possible. However, the user has to use the 'MUI snapshot' feature for that. That means, after you have changed the sorting for the main listview in YAM you need to manually go to the top right border of the window and use the internal "Snapshot" functionality of MUI. When that is performed YAM will also save the whole layout of the listview including the sorting.

Nevertheless, after rethinking the facts I also think that this should be done automatically when YAM is exited. Therefore I'll keep that ticket open and also assign it to 2.7 as that might be an interesting feature for the next release.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2011-12-19 19:08:48 +0100**

___
Thanks ! :-)

**Comment by jens-maus** [comment]
**Originally on 2011-12-23 21:28:09 +0100**

___
Sorry Samir, but as time is running out for the YAM 2.7 release and your requested change is too complex to quickly implement it we need to push it to the YAM 2.8 milestone. However, I'll set a high priority on it so that it gets addressed quickly for the next release.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2011-12-24 16:24:57 +0100**

___
Ah ok, honestly I had to bring this issue before and not only a week ago :-/
But i didn't know that 2.7 was planned for XMas, aniway there is no problem :-)

Thanks to look at and marry XMAS Jens :-)

**Comment by tboeckel** [comment]
**Originally on 2013-08-29 19:33:26 +0200**

___
The "View" cycle gadget's state should be remembered, too, as suggested by #410.

**Comment by tboeckel** [comment]
**Originally on 2013-11-05 19:09:22 +0100**

___
In (b241add):
 * mui/QuickSearchBar.c: added a unique ObjectID to the view options cycle object. This makes it possible to permanently save the current settings by snapshotting the main window. This refs #284.

**Comment by jens-maus** [comment]
**Originally on 2013-11-18 23:34:58 +0100**

___
In (5c2a061):
 * YAM.c, YAM_MA.c, YAM_UT.c, mui/MainFolderListtree.c, mui/MainWindow.c:
  the folder listtree sorting will now also be automatically saved when
  the new SaveLayoutOnQuit option is turned on (which is the default). In
  addition, the folder listtree order/sorting will now also be saved when
  using the MUI snapshot feature. This change also renders the manual
  menu and context menu entries/functionality for saving and reloading
  the order obsolete. Thus they have been removed. This closes #284.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 22:23:01 +0100**

___
**Release Note:**
The main window layout (size+position) and list sorting options will now be automatically saved upon exiting YAM rather than forcing a user to explicitly 'snapshot' that information via the corresponding MUI functionality. An additional option in the configuration of YAM allow to disable this, thought.
