### ISSUE TITLE
YAM 2.7 (MorphOS) vertical lines in folder list are missing

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#285]
**Originally by _yam.asc@schwarzes.net_ on 2012-01-02 09:17:29 +0100**

___
## Summary
With YAM 2.7 (under MorphOS) the vertical seperation lines in the folder 
list window are missing. Will not occur with YAM 2.6p1.

## Steps to reproduce
 1. Start Yam (MorphOS version)
 2. Have a look at the folder list

## Expected results
Ther should be lines.

## Actual results
No lines.

**Comment by jens-maus** [comment]
**Originally by _yam.asc@schwarzes.net_ on 2012-01-02 03:19:17 +0100**

___
**Attachment added:** `yam2.7-folder.png` (16.7 KiB)
![yam2.7-folder.png](https://yam.ch/attachments/285/yam2.7-folder.png)
snapshot to show the problem

**Comment by jens-maus** [comment]
**Originally on 2012-01-02 09:22:58 +0100**

___
First of all, the bars had been remove on purpose. So this is more or less a feature and not a bug as the vertical bars are not really required, especially if you just have two columns in the listtree. However, I do agree that if you have more than one column enabled the listview looks a bit obfuscated, thus vertical lines can become handy. Therefore, I will set this ticket to accepted and we will think about solutions how to reimplement that in a way that with two column no bars are shown and that with 2+ columns they are visible.

**Comment by tboeckel** [comment]
**Originally on 2012-01-02 09:53:24 +0100**

___
In (f9b7429):
 * mui/MainFolderListtree.c: replaced the NOBAR title format by TBAR to enable separator bars in the title bar at least for easier column resizing. This closes #285.
