### ISSUE TITLE
please add a "reply" possibility for the sent items

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#288]
**Originally by _Michael.Merkel@gmx.net_ on 2012-02-06 21:53:12 +0100**

___
## Problem
you sent a mail and expect an answer. but you don't receive one. so you maybe want to "resent" the mail in form of a reply to all receipients.

## Analysis
the reply button is greyed out for the sent items

## Enhancement recommendation
please activate the possibility to "reply" to already sent mails and then to all receipients.

thanks and regards
michael

**Comment by tboeckel** [comment]
**Originally on 2012-02-07 11:00:34 +0100**

___
I just checked other mail clients (i.e. Thunderbird) and they allow to reply to mails in the "Sent" folder. Should be quite easy to do.

**Comment by tboeckel** [comment]
**Originally on 2012-02-07 16:03:24 +0100**

___
In (5106a7c):
 * mui/ReadMailGroup.c, mui/ReadWindow.c: enabled all "Reply" controls for the sent mail folder. This was already the case within the main window and is completely consistent now. This closes #288.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-03-23 16:29:50 +0100**

___
Don't know if this change is such a good/usefull idea.
Taking the To: to reply to seems kind of hacky to me.

In my opinion valid ways to resend something are:
1. D&D from "sent" to "outgoing"
2. Move/Copy from "sent" to "outgoing" (via menu)
3. Bounce (shift+forward) the mail in "sent"
4. Add an "resend" button/menu entry in YAM ;)

But the way via reply...

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2012-03-23 22:07:28 +0100**

___
hi padrino.

sorry - but all you're suggestions don't fulfill my expectations when "replying" to a sent email.
i *really* want to reply. just like it works in other mail clients, like thore already wrote.

"resent" or "forward" is completely different.
the way thore implemented it is very fine and common.

regards...
michael
