### ISSUE TITLE
Editing an email in sent folder will replace "FROM:" with user's address

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#289]
**Originally by _mario@cattaneo.de_ on 2012-03-20 15:27:11 +0100**

___
YAM 2.8-dev [OS4/PPC]

When you press the "edit"-button with an email in the sent folder, the "From"-field will we overwritten and is not kept as it is done when you press "edit" in the outgoing-folder.
Think the set "value" should be kept there, too.

**Comment by tboeckel** [comment]
**Originally on 2012-03-20 15:48:05 +0100**

___
In (c76fb76):
 * YAM_FI.c: opening the search window from the toolbar or the global menu will now use the current folder as default folder to be searched in. Having no folder to be searched in is quite unintuitive and leads to confusion if the user is sure that some mails must be found but don't get found as YAM does not search anywhere. This closes #289.

**Comment by tboeckel** [comment]
**Originally on 2012-03-20 16:06:05 +0100**

___
Sorry, closed the wrong bug by accident.

**Comment by tboeckel** [comment]
**Originally on 2012-03-20 16:08:11 +0100**

___
Just to get this right, before sending the mail for the first time you modified the "From" field on the Options page of the write window, correct? But how is it possible to sent off such a mail without getting an error from your SMTP server?

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-03-20 16:16:17 +0100**

___
My SMTP Server (Arcor/Vodafone) accepts any (valid?) email-address as from.
E.g. I use my own domain like bla@lastname.de and not at @arcor.de all the time.
And when I write to a company I use special (unique) "bla"-parts (hopping to track back spam ;)), all valid, though.

So I would be p... if the server would reject them all. 8)

**Comment by tboeckel** [comment]
**Originally on 2012-03-20 16:42:51 +0100**

___
Replying to padrino:
> My SMTP Server (Arcor/Vodafone) accepts any (valid?) email-address as from.
> E.g. I use my own domain like bla@lastname.de and not at @arcor.de all the time.
> And when I write to a company I use special (unique) "bla"-parts (hopping to track back spam ;)), all valid, though.

I would consider this a severe security issue. Anybody is able to impersonate as you and can send mails under your name/address.

At least GMX's and web.de's SMTP servers don't accept mails which don't belong to the user who has logged in right before sending the mail.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-03-23 16:36:11 +0100**

___
Though this might possibly be dangerous/abused, but I don't think YAM needs to take care of this.
This can be very usefull (e.g. my wife and I share the same account, as she is not "into computers" an additional one is not needed. And when she writes something she just edits the part before the "@" as the rest is the same.)
Same for me when I use the "anti company spam trick".

YAM has always been flexibal (and powerful?) in that matter and it would just be consitent if it was for this case/folder, too.

**Comment by tboeckel** [comment]
**Originally on 2012-04-27 14:09:38 +0200**

___
In (d60861c):
 * YAM_WR.c: editing a mail in the outgoing folder as new will now leave the From: and ReplyTo: field as they are. This closes #289.
