### ISSUE TITLE
Select "incoming" folder when search is opened for the first time

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#290]
**Originally by _mario@cattaneo.de_ on 2012-03-20 15:31:04 +0100**

___
YAM 2.8-dev [OS4/PPC]

Would be nice, if "search" is opened for the first time, that as default the "incoming"-folder is selected (instead of nothing).
I think this has been the case before, especially as I find myself trying to perform a search when no folder is selected - again and again. 8)

**Comment by tboeckel** [comment]
**Originally on 2012-03-20 16:09:59 +0100**

___
Fixed in the next nightly build.
