### ISSUE TITLE
A folder added after "search" was open will never be displayed

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#291]
**Originally by _mario@cattaneo.de_ on 2012-03-20 15:35:17 +0100**

___
YAM 2.8-dev [OS4/PPC]

Start YAM and open the "search"-gui, leave it open.
Now go to YAM's main window and add a new folder.
This will (of course?) not instantly be shown in the "search-list".
But even when you now close the search-gui and reopen it, the folder still won't show up. Seems the GUI only checks the list of available folders once?

**Comment by tboeckel** [comment]
**Originally on 2012-03-20 16:04:48 +0100**

___
YAM just closes the window but does not dispose it. That means that one gets the result of the previous search presented again when starting a new search. Completely disposing the search window and rebuilding it from scratch would break this behaviour.

I think we'll have to implement some kind of notification mechanism for the search window to rebuild the folder list whenever it was modified.

**Comment by jens-maus** [comment]
**Originally on 2013-07-01 20:53:34 +0200**

___
This seems definitly to be a bug rather than an enhancement request as the folder list should never be out of sync to the real folder list.

**Comment by tboeckel** [comment]
**Originally on 2013-07-15 08:19:03 +0200**

___
In (d099634):
 * YAM_FO.c, mui/MainFolderListttree.c: adding, removing or moving a folder within the main folder tree will now automatically update the folder tree in the search window. This closes #291.

**Comment by tboeckel** [comment]
**Originally on 2013-07-15 08:19:23 +0200**

___
**Release Note:**
Adding, removing or moving a folder within the main folder tree will now automatically update the folder tree in the search window.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 23:00:32 +0100**

___
**Release Note:**
fixed a problem with not seeing a folder added to the folder list immediately.
