### ISSUE TITLE
How about changing the two buttons below the "search in"-list

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#292]
**Originally by _mario@cattaneo.de_ on 2012-03-20 15:39:57 +0100**

___
YAM 2.8-dev [OS4/PPC]

How about changing the buttons from

[All] [None]

to

[All/None] [Toggle]

**Comment by tboeckel** [comment]
**Originally on 2012-03-22 09:12:43 +0100**

___
Having thought about this I must say that such a change doesn't make much sense from my point of view.

Toggling the current selection makes sense if the complement selection is needed very often. But usually one performs a search in certain folders, but the next search is not done in all the other folders. So why do I need a toggle button?

Other mail clients (i.e. Thunderbird) offer to search either in one folder only or in folder group or in all available folders. Comparing to this YAM lets you define your search more precisely as you can choose folders individually without having to respect the folder hierarchy.

The current All and None buttons just serve as a shortcut. But I don't really see the point for a Toggle button. Furthermore combining All and None into one button would in fact be exactly the same as the Toggle button next to it and hence would be even more superflous.

**Comment by jens-maus** [comment]
**Originally on 2013-01-15 00:00:02 +0100**

___
I agree. I don't see a reason for that as well.
