### ISSUE TITLE
Double clicking an URL does highlight/mark parts of the string

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#294]
**Originally by _mario@cattaneo.de_ on 2012-03-20 16:28:23 +0100**

___
YAM 2.8-dev [OS4/PPC] (02.03.2012)

Think this changed "recently".
Double clicking a highlighted URL (to open it) should not highlight/mark parts of the string I think.

**Comment by tboeckel** [comment]
**Originally on 2012-03-20 16:39:49 +0100**

___
Can you give some good reasons why YAM should not do that than just "it should not"?

YAM has always marked the double clicked URL. What is wrong about that?

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-03-20 16:44:22 +0100**

___
I doubt that it always did that as it would likely have bothered me bevore then. ;)
I believe this "change" happend with MUI progress...

I think, the reason is, that is seems logical to me, that double clicking should highlight something OR perform the "link-opening" action. And not both. Cause the user expects the one or the other, not both. If you would want to mark then URLopning is not desired and vice versa.

**Comment by tboeckel** [comment]
**Originally on 2012-03-21 07:32:30 +0100**

___
Replying to padrino:
> I doubt that it always did that as it would likely have bothered me bevore then. ;)
> I believe this "change" happend with MUI progress...

Absolutely not. Even with MUI 3.8 on AmigaOS3 the URL will be selected on double clicking it. This is because TextEditor.mcc does this selection, not MUI itself. And TextEditor.mcc has not been changed in this respect since more than 2 years now.

**Comment by tboeckel** [comment]
**Originally on 2012-05-04 09:07:17 +0200**

___
In (f7de701):
 * mui/ReadMailGroup.c: fixed the double click handling on URLs to let TE.mcc no longer mark parts of the URL. If YAM did handle a double click on a valid item TE.mcc will do no own double click handling. This closes #294.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-05-05 14:47:59 +0200**

___
Thanks for fixing this one though it assumably has always been that way!

There's still another/similar problem I encountered giving OS4's URLOpen a try (instead of openurl).

When you have actived multiple choises of Browsers, so that URLOpen will ask you which browser to use, after selecting the browser-button the textfield will mark the complete string starting from the double click-postion to the current position, namely the requester button of the browser you have chosen (of course for this to happen the opening requester must be placed so that the second position is quite some space away from the first).

Should I open a new ticket for that on?

**Comment by tboeckel** [comment]
**Originally on 2012-05-06 21:44:39 +0200**

___
Please wait for TE.mcc 15.38. The current release 15.37 has a bad bug which interprets a return value from YAM (or any other application) in an inverted fashion and handles the double click again although YAM already has handled it. TE.mcc's default reaction on a double click is to mark the clicked word. Furthermore YAM is launching an external command (here C:URLOpen) synchronously. This mean that control returns to YAM and eventually TE.mcc only if the command terminates. Lots of things could have happened in the meantime, as you already described.

To make it short: wait for TE.mcc 15.38 and open a new ticket if the current behaviour persists.
