### ISSUE TITLE
Update notify without text

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#297]
**Originally by _s.hawamdeh@teletu.it_ on 2012-04-27 14:33:15 +0200**

___
I've found a very curious misbehaviour about the update notify window of YAM (the window that will be open when you want to download a new nightly build) :-)

If you start a search and an update for YAM will be found you will have a popup window with all the proper info of the new update availible, the date, the changelog etc ..

Now if you try to iconify this update window (not the main YAM window) and the reopen it you will get a blank window instead, so no text at all !

See grab for an example:

http://imageshack.us/photo/my-images/715/yam.png/

**Comment by tboeckel** [comment]
**Originally on 2012-04-30 23:32:23 +0200**

___
In (16a155a):
 * mui/UpdateNotifyWindow.c, YAM.c: uniconifying YAM while the update notification is still open will reparse the update file and populate the formerly cleared list of available updates. This closes #297.
