### ISSUE TITLE
Make addressbook entries sort by clicking column titles

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#298]
**Originally by _mario@cattaneo.de_ on 2012-05-05 15:08:10 +0200**

___
Don't know it the addressbook list is the only list in YAM where it does not work, but it would be nice if it worked there, too ;)
(and not just via menu).
Think "title sorting" is a fast and easy way for the user.

**Comment by tboeckel** [comment]
**Originally on 2013-07-17 08:46:24 +0200**

___
In (2d181de):
 * YAM_AB.c, mui/AddrBookListtree.c, misc: made the address book listtree title bar clickable to sort the addresses by any column. This closes #298.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2013-07-20 20:05:37 +0200**

___
Click on address book list tree titile bar freeze the YAM on MorphOS 3.2.

**Comment by tboeckel** [comment]
**Originally on 2013-07-21 19:41:53 +0200**

___
Replying to anonymous:
> Click on address book list tree titile bar freeze the YAM on MorphOS 3.2.

Can you provide any more useful information than just "it freezes"? How many entries does your address book consist of? Any deeply nested groups? Stack size of YAM? Any further crash information?

**Comment by jens-maus** [comment]
**Originally on 2013-07-21 19:46:07 +0200**

___
The problem has already been tracked down by me and fixed in NListtree itself. It seems there were a severe problem in the way NListtree tried to sort lists which had sub-folders. see here: http://sourceforge.net/p/nlist-classes/code/703/

Please note that with the next NListtree release (18.43+) this problem will be fixed.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 22:25:15 +0100**

___
**Release Note:**
address book entries can now be sorted by clicking on the list titles similar to the mail list of the main window.

**Comment by jens-maus** [comment]
**Originally by _A Hoffman_ on 2014-01-27 07:44:31 +0100**

___
Replying to damato:

> The problem has already been tracked down by me and fixed in NListtree itself. It seems there were a severe problem in the way NListtree tried to sort lists which had sub-folders. see here: http://sourceforge.net/p/nlist-classes/code/703/
> 
> Please note that with the next NListtree release (18.43+) this problem will be fixed.

I've had the same address book sort freezing problems with YAM 2.9 in OS3.9.  YAM 2.8p1 was OK, the problem appears to be introduced in the 2.9 full release.  Just tested with the newly released NList (26/1/2014) and the same problem remains.  I have no sub-folders in my address book, but there are 324 entries and some long descriptions.  Any sorting by alias, name, description causes the computer to freeze.  This includes sort by clicking column header or by selecting sort from the menu bar.

Can supply the address book for testing if required, Email: ahoffman[at]clear.net.nz

Can also open a new ticket for this if required??

**Comment by tboeckel** [comment]
**Originally on 2014-01-27 07:46:35 +0100**

___
Replying to Hoffman:

> Can also open a new ticket for this if required??

Please do that. Additionally it would help a lot if you get a login here to make communication easier for all of us. Comments of unregistered persons need to be moderated before they become visible for everybody.

**Comment by tboeckel** [comment]
**Originally on 2014-01-27 16:06:28 +0100**

___
Replying to Hoffman:

> Can also open a new ticket for this if required??

No need for a separate ticket anymore. I found and fixed the reason for this crash. If you like you can check this with the next nightly build of YAM 2.10-dev.

However, please open a new ticket immediately next time. This makes it easier for us to tell old and new bugs apart.

**Comment by tboeckel** [comment]
**Originally on 2014-01-27 16:07:08 +0100**

___
In (41a6de6):
 * mui/AddressBookListtree.c: get the true root treenode pointer during the first iteration when rebuilding the address book after a sort operation. This refs #298.
