### ISSUE TITLE
Don't accept () as email delimiters

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#3]
**Originally by _tactica@users.sourceforge.net_ on 2010-03-03 14:46:40 +0100**

___
If <> are the only valid email delimiters as the
comments to feature request #583703 seem to imply,
YAM shouldn't accept () in the first place when
writing an email. Currently YAM won't complain at
all if you post a message with a From: header
like "name (user@host)".

**Comment by jens-maus** [comment]
**Originally on 2010-03-03 14:47:27 +0100**

___
Well, the problem is here that ( and ) are prefectly valid characters for
including in the full email address. So e.g. something like "Jens (damato)
Langner <Jens.Langner@light-speed.de>" is perfectly valid and should
therefore also be allowed in YAM. However, the ( and ) chars are clear
'comment' characters and not the delimiters for seperating the email part
from the real name part. So something like "Jens Langner
(Jens.Langner@light-speed.de)" is definitly wrong and violates any RFC.

So, IMO we should keep the possibility to add ( and ) to your real name.
However, YAM should never send any email with such a broken
recipient/sender adress and AFAIR it isn't possible to send such a mail
(apart from manually modifying the From: header line in the write window).
And if YAM should eventually receive such a broken email it should not try
to be smart any treat those ( ) chars as the realname<>email delimiters
instead of <> as this is calling for trouble... Broken mail are broken, and
nothing more :)

**Comment by jens-maus** [comment]
**Originally by _tactica_ on 2010-03-03 14:48:01 +0100**

___
The whole point is that YAM *does* allow to send an email
with a From: line like "Name (user@host.dom)", literally,
at least with my mail server. And yes, I tried this by
editing this header in the Write window.

If that's illegal, YAM is only contributing to the problem,
so it should throw an error immediately.

**Comment by jens-maus** [comment]
**Originally on 2010-03-03 14:48:34 +0100**

___
Yes, you are right. YAM should not allow to send an email with such an
illegal From: and/or To: line whatsoever. So I will see how I can fix that
issue and raise an error instead. However, please note that YAm should also
make sure that it isn't possible to end up with such an address in any
automatic way. So please also check that it isn't possible to enter such an
illegal address in either the addressbook or any other GUI element in the
configuration, for example. But please keep in mind that something like
"Name (doe@doe.com) <doe@doe.com>" is valid even if it doesn't make sense.

**Comment by tboeckel** [comment]
**Originally on 2010-03-03 14:50:35 +0100**

___
According to RFC 2282 even something like this is valid, although not
encouraged:


```
From: Pete(A wonderful \) chap) <pete(his account)@silly.test(his host)>
To:A Group(Some people)
:Chris Jones <c@(Chris's host.)public.example>,
joe@example.org,
John <jdoe@one.test> (my dear friend); (the end of the group)
Cc:(Empty list)(start)Undisclosed recipients :(nobody(that I know))
```


Text within () should be treated as (nested) comment which reduces the
examples above to something like this (if I understood the RFC correctly):


```
From: Pete <pete@silly.test>
To:A Group
:Chris Jones <c@public.example>,
joe@example.org,
John <jdoe@one.test>;
Cc:Undisclosed recipients :;
```


Hence to be on the safe side we would need another lexical analyzer to
parse/check an email address. Simply forbidding () in the address part is
not enough.

**Comment by jens-maus** [comment]
**Originally on 2010-03-03 14:51:12 +0100**

___
As the issue seems to require a rework of our current email address parser
routines and we are running out of time till the 2.5 release, I'll
reschedule that issue for the 2.6 release cycle.

**Comment by jens-maus** [comment]
**Originally on 2010-03-07 11:40:21 +0100**

___
We do have to check if this ticket is still valid and how we can easily fix it for the next release.

**Comment by tboeckel** [comment]
**Originally on 2010-11-17 13:16:36 +0100**

___
I just checked this ticket again with lots of variations of names and addresses with and without bracket and for me YAM either correctly rejected them as invalid or surrounded the brackets with quotes to make them part of the real name.

Hence from my point of view there is nothing to be fixed.

Closing this one as "works for me".

Feel free to reopen this ticket if YAM is doing something wrong in this respect.
