### ISSUE TITLE
Images not visible anymore in Write/Reply and Forward Windows

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#302]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-05-14 10:44:08 +0200**

___
## Summary

With YAM versions as of 2012-05-12 images in Write/Reply and Forward Windows aren't shown anymore even though they are present in the "System:YAM/themes/aiss/toolbar/" drawer.

## Steps to reproduce
 1.
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-05-14 10:39:09 +0200**

___
**Attachment added:** `ScreenGrab2.jpg` (196.3 KiB)
![ScreenGrab2.jpg](https://yam.ch/attachments/302/ScreenGrab2.jpg)

**Comment by tboeckel** [comment]
**Originally on 2012-05-14 16:05:45 +0200**

___
I just tested this on OS3 and all images are available in all windows.

Did you copy the updated .theme files and the changed image files?

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-05-14 16:36:45 +0200**

___
I copied 1:1 the themes drawer from the nightly build archive to the YAM drawer just to see if it could be that. But then I get 30 errors that it could not find the "TBImages" directory. So I think it must be something else.

Adn yes, I copied the updated theme files and changed image files. I could, if it helps, send you an lha archive of the themes drawer, please let me know.

BTW I am on MorphOS, don't know if that changes anything.

**Comment by tboeckel** [comment]
**Originally on 2012-05-14 16:37:48 +0200**

___
Replying to christoph.poelzl@…:
> I copied 1:1 the themes drawer from the nightly build archive to the YAM drawer just to see if it could be that. But then I get 30 errors that it could not find the "TBImages" directory. So I think it must be something else.

Do you have AISS correctly installed? The install script of AISS should set up the TBIMAGES: assign.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-05-14 16:56:09 +0200**

___
No AISS is not installed on my MorphOS System using the script. In fact I only use the AISS images for YAM and have them in the themes/aiss/ drawer.

**Comment by tboeckel** [comment]
**Originally on 2012-05-14 17:00:23 +0200**

___
Well, the .theme file of YAM's AISS theme assumes AISS to be installed and will use the TBIMAGES: assign for that purpose. Assigning TBIMAGES: to your theme directory might work, but I really recommend to really install AISS using the script.

The images in YAM's main window are visible for you, because these are contained in the "default" theme already which each theme will fall back to, if no other replacement image is specifies in the .theme file.

In general the "default" theme and the "AISS" theme are very similar with only very few differences.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-05-14 18:13:59 +0200**

___
Ok, I understand what you are mean. Now it seems that something changed since 20120511 about themes because before it worked in all windows. Don't know what could be a good solution if one does not install AISS completely but want to use only the AISS images for YAM. Perhaps YAM could have his own images supplied with his own .theme file but this would make extra work... hmmm. On the other hand I don't understand why only in the 3 windows I mentioned it will not work anymore even that the images are present and have the correct names and path as per the .theme file, all other images are ok even in Addressbook...

**Comment by tboeckel** [comment]
**Originally on 2012-05-14 21:51:15 +0200**

___
Replying to christoph.poelzl@…:
> Don't know what could be a good solution if one does not install AISS completely but want to use only the AISS images for YAM.

The theme is named "AISS" and hence it **requires** AISS to be installed.

> Perhaps YAM could have his own images supplied with his own .theme file but this would make extra work... hmmm.

Exactly this is the "default" theme. Every theme falls back to these images if the corresponding .theme file does not explicitly replace certain image with own ones.

> On the other hand I don't understand why only in the 3 windows I mentioned it will not work anymore even that the images are present and have the correct names and path as per the .theme file, all other images are ok even in Addressbook...

Well, if you like to know then check with SnoopDOS what is missing.

Anyway, closing this bug as "invalid" as it was no real bug.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-05-15 06:38:23 +0200**

___
**Attachment added:** [`Snoopium.log`](https://yam.ch/attachments/302/Snoopium.log) (35.8 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-05-15 06:38:43 +0200**

___
That is the point, I checked before with Snoopium and it seems that there is nothing missing! So something else seems not working correctly! I include the log, where you can see that all images are listed with "ok".

**Comment by tboeckel** [comment]
**Originally on 2012-05-15 08:37:31 +0200**

___
Replying to rmsyam:
> That is the point, I checked before with Snoopium and it seems that there is nothing missing! So something else seems not working correctly! I include the log, where you can see that all images are listed with "ok".

Then please provide a THEME+IMAGE debug log with your previous non-working semi AISS installation. And if possible please attach your non-working AISS theme to this ticket.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-05-28 11:42:09 +0200**

___
The log is quite large, compressed 1.8 MB and also the theme drawer would exceed the max. size. Would you like it sended privatly?
