### ISSUE TITLE
allow a minimum waiting time for fetching mails per server

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#305]
**Originally by _Michael.Merkel@gmx.net_ on 2012-05-16 20:10:29 +0200**

___
## Problem
For example with Web.de and pop3 access you're only allowed to fetch mails every 720 seconds. not earlier. you simply get an error if you try this. i configured yam to look for new mails every 5 minutes.
## Analysis
you receive an error every 5 minutes because the server needs more time.
## Enhancement recommendation
add a minimum fetch time per server in the settings (or smth similar). e.g. web.de is set to "wait at least 20 minutes between checking for new mails".

thanks and regards
michael

**Comment by jens-maus** [comment]
**Originally on 2012-05-16 20:25:14 +0200**

___
Please explain why you not simple change yam to Look for New Mails every 720 seconds and Not 5 Minutes. This should solve your Problems.

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2012-05-16 20:54:35 +0200**

___
:-)
of course that would be the easiest solution to do. but i want my accounts (especially my main account) to be fetched more often. just because one is too dumb to allow fetching mails more often i don't want all the others to be restricted like that. sort of a "server timeout setting" would just be soo nice :-)

thanks and regards...
michael

**Comment by tboeckel** [comment]
**Originally on 2012-05-16 22:04:48 +0200**

___
I must add that Thunderbird also allows a per-server timeout setting, which I personally use as well to distinguish between web.de and other servers. Gettings mails from all servers just every 20 minutes just to satify the timeout of web.de is a bit annoying.

**Comment by jens-maus** [comment]
**Originally on 2012-05-16 22:13:40 +0200**

___
Now I understand. Of course having separate Mail check intervals per server is something useful. In fact i already thought about it myself, but I am sure Thore is already on the task of implementing it ;)

**Comment by tboeckel** [comment]
**Originally on 2012-05-18 20:52:56 +0200**

___
Replying to damato:
> but I am sure Thore is already on the task of implementing it ;)

Not yet, but I will start as soon as I find the necessary spare time.

**Comment by tboeckel** [comment]
**Originally on 2012-05-21 14:22:18 +0200**

___
In (6b9ed7a):
 * misc: implemented a per POP3 server setting of mail download intervals along with individual mail size limits. This finally makes it possible to avoid timeouts of certain mail providers (i.e. web.de) while still being able to download mails from other servers which don't restrict the periodical mail download on time basis. This closes #305.
