### ISSUE TITLE
Move "Status Update" in hidden config section

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#309]
**Originally on 2012-06-02 23:50:31 +0200**

___
## Phenomenon
Flagging mails from new to unread should only happen if YAM is restarted and not after each mail (POP3) download. Currently the user can enable/disable the status update globally and permanently. However, the default should be used (enabled), and should only be applied when restarting YAM (check with behaviour in thunderbird needed) and the config option moved to the hidden section instead as it is cumbersome to understand and to handle.

**Comment by tboeckel** [comment]
**Originally on 2012-06-05 22:08:43 +0200**

___
In (b3102c3):
 * YAM_CO.c: moved the "Update Status" setting to the hidden section and if set then new mails will become "old" only upon starting YAM, but not ahead of every mail download. This closes #309.
