### ISSUE TITLE
Remove GUI elements in write window for attachment encoding

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#310]
**Originally on 2012-06-03 00:00:32 +0200**

___
## Phenomenon
Manually changing the encoding of an attachment made partly sense in former times but not today anymore because the automatic analysis for finding the right encoding algorithm (quoted-printable vs. base64) is smart enough to choose the right one.

## Implementation recommendation
Remove the GUI elements for allowing to change the encoding of attachments in the write window.

**Comment by tboeckel** [comment]
**Originally on 2012-06-05 21:12:38 +0200**

___
Implemented in r6019.
