### ISSUE TITLE
Show Attachmentlist in first pagegroup of write window

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#311]
**Originally on 2012-06-03 00:20:29 +0200**

___
## Phenomenon
To improve visual feedback for the user the write window should show a list of attachments also on the first pagegroup of the window. Currently a user has to click on the second page group to see the list of attachments.

## Background analysis
Currently the write window only allows to show the currently selected attachments via the second page group tab. However, other mail clients also show the attachments on the main write window tab for better feedback.

## Implementation recommendation
The write window should be slightly redesigned to allow to show (dynamically) a short list of attachments on the right top area of the first pagegroup tab besides the To/From/Cc string gadgets similar to how Thunderbird is showing that. In case no attachment is currently added it should be hidden.

**Comment by tboeckel** [comment]
**Originally on 2013-07-16 09:25:53 +0200**

___
In (e7689e5):
 * mui/WriteWindow.c, mui/WriteAttachmentList.c: the write window now features a small clone of the attachment list on the first page. A context menu allows to perform the same actions as for the big list on the second page. This closes #311.

**Comment by tboeckel** [comment]
**Originally on 2013-07-16 09:26:17 +0200**

___
**Release Note:**
The write window now features a small clone of the attachment list on the first page. A context menu allows to perform the same actions as for the big list on the second page.
