### ISSUE TITLE
remove DST notification (on certain platforms)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#313]
**Originally on 2012-06-03 00:34:21 +0200**

___
## Phenomenon
Currently when daylight saving times switches to summer to winter times or vice versa a notification is showing upon starting YAM. This notification was added because on some platforms (e.g. OS3) no automatic switching is implemented so other tools (e.g. SetDST) are used and these tools might fail to correctly switch to/from DST.

## Background analysis
On platforms like AmigaOS4 the DST is done by the system itself and no external tools are required. Thus this notification is not required anymore. Nevertheless it has to be investigated which other platforms (MorphOS, AROS) also have native DST switching and for these the notification should be completly removed as well.

## Implementation recommendation
Remove DST switching notification completly and trust the OS-based DST switching.

**Comment by tboeckel** [comment]
**Originally on 2012-06-05 21:27:06 +0200**

___
Implemented in r6020.
