### ISSUE TITLE
Move new default folders to default position in folder listtree

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#314]
**Originally on 2012-06-03 00:44:11 +0200**

___
## Phenomenon
Currently when a default folder (incoming, drafts, etc.) is added because it doesn't exist yet it will be added at the bottom of the folder listtree. Better would be to add it at a sensible place with an internally defined order.

## Background analysis
E.g. when adding the "Drafts" folder it should appear right after the "Incoming" folder. A sensible default folder order could be:

1) Incoming
2) Drafts
3) Outgoing
4) Sent
5) Trash
6) Spam

## Implementation recommendation

**Comment by tboeckel** [comment]
**Originally on 2012-06-10 14:24:22 +0200**

___
In (6bab5c8):
 * YAM.c, YAM_COs.c: new standard folders created during the startup phase are now moved to a sensible position within the folder listtree automatically. This closes #314.
