### ISSUE TITLE
Move "New Mail" config items to identities and remove page from config

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#315]
**Originally on 2012-06-03 00:47:57 +0200**

___
## Phenomenon
Since we have the multiple identities support we should move more options there which might be related to a user identity. 

## Background analysis
After a short analysis all the config items in the "New Mail" config page should be moved to the user identities page and thus to the UserIdentityNode structure instead (excluding the Status Update option which should be moved to the hidden options, see #309)

## Implementation recommendation

**Comment by tboeckel** [comment]
**Originally on 2012-06-07 22:37:42 +0200**

___
In (019dfee):
 * YAM_COg.c: moved the new mail notification settings to the POP3 server settings on the TCP/IP page. This finally closes #315.
