### ISSUE TITLE
Recipientstring should not search for recipients in a recipient list

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#316]
**Originally on 2012-06-03 00:55:21 +0200**

___
## Summary
Currently when using a recipientstring object (e.g. entering an address in the To: field in the write window) a user can enter an address which is contained in a recipient list in the addressbook. When using this address the recipient list will be used when resolving this address.

## Steps to reproduce
 1. open write window
 2. enter an address of a recipient in a recipient list of an addressbook
 3. press enter to let it resolve

## Expected results
only the address should be added to the recipientstring object

## Actual results
all recipients of the recipient list are added instead (which is incorrect!)

## Notes

**Comment by tboeckel** [comment]
**Originally on 2012-06-03 22:54:13 +0200**

___
In (d1c889d):
 * mui/YAMApplication.c: the reply address of recipient lists is now excluded from the address matching process. This closes #316.
