### ISSUE TITLE
Show attachment reminders upon keyword matches

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#317]
**Originally on 2012-06-03 01:04:56 +0200**

___
## Phenomenon
A common failure when sending an email with an attachment is that the users forget to add the attachment to the mail before sending it. Modern mail clients identify certain keywords in the mail text and in case no attachment had been added it shows a reminder that the users might want to add the attachment.

## Implementation recommendation
A list of keywords should be added to the global config and changable by the user. When these keywords are found during entering a mail text the write window should remind the user (e.g. by showing the planned attachmentimage object, see #311) with some text that he might want to add an attachment. If the user refuses to do so no further warning should be shown.

**Comment by tboeckel** [comment]
**Originally on 2013-11-01 09:37:00 +0100**

___
In (eed0296):
 * Config.c, mui/AttachmentKeywordList.c, mui/AttachmentKeywordWindow.c, mui/MailTextEdit.c, mui/WriteWindow.c: implemented an interactive attachment reminder feature as known from Thunderbird. If enabled and the user types in certain keywords from a user definable list and no attachment has been added to the mail a reminder will be shown to inform the user that an attachment might be desired. This requires the not yet released version 15.42 of TextEditor.mcc. This closes #317.

**Comment by tboeckel** [comment]
**Originally on 2013-11-01 09:38:57 +0100**

___
**Release Note:**
Implemented an interactive attachment reminder feature as known from Thunderbird. If enabled and the user types in certain keywords from a user definable list and no attachment has been added to the mail a reminder will be shown to inform the user that an attachment might be desired. This requires version 15.42 of TextEditor.mcc.

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 19:25:56 +0100**

___
**Release Note:**
Implemented an interactive attachment reminder feature as known from Thunderbird. If enabled and the user types in certain keywords from a user definable list and no attachment has been added to the mail a reminder will be shown to inform the user that an attachment might be desired.
