### ISSUE TITLE
Take single mails into account for "new mail"-string

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#32]
**Originally by _mario@cattaneo.de_ on 2010-03-03 17:12:48 +0100**

___
I find it sommehow ugly when messages like "1 messages" show up, where a small check could/should be trivial. ;) So, it would be nice, if the message shown by Ringhio would not have "1 new mails" in it. The current solutions, thruout YAM are, if I am right,to write "Mail(s)". So, no real singular/plural case, but a start.

**Comment by tboeckel** [comment]
**Originally on 2010-07-20 05:53:28 +0200**

___
In (d864557):
 * YAM_TR.c, locale/YAM.cd: the notification message now distinguished between
  a single and multiple received mails. This closes #32.
