### ISSUE TITLE
Change IdentityChooser to allow keyboard searches/usage in write window

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#321]
**Originally on 2012-06-03 17:06:56 +0200**

___
## Phenomenon
If a large amount of identities is configured in YAM and a new mail is being composed by a user it takes a while to find and select the desired identity in the identity chooser cycle gadget. Therefore a fast and easy way seems to be missing to quickly select the identity using the keyboard.

## Background analysis
A standard cycle gadget only provides a plain list without any possibility to quickly select an entry using a keyboard search. It should be possible to activate the identity chooser gadget and enter characters in the keyboard to quickly search and select the right user identity.

## Implementation recommendation
It might be possible to simply use a string gadget with a cycle gadget alike background and frame. Then when entering some text or selecting the gadget it should popup a list with the identities and the current match should be selected. If enter is pressed the active object should be advanced to the next one (e.g. the To: string gadget).

**Comment by jens-maus** [comment]
**Originally by _johnblock@storeshop.com_ on 2013-01-04 12:28:18 +0100**

___
Would like the functionality of a freely editable from: that I believe has always been in Yam back rather than the bloat of 

> large amount of identities is configured in YAM

Background in  [http://yam.ch/ticket/366]

Maybe there can be a blank identity which allows use of From: in options

**Comment by tboeckel** [comment]
**Originally on 2013-01-22 20:05:19 +0100**

___
In (19930df):
 * WriteWindow.c, YAM_WR.c, YAM_CO.c: added a new option in the hidden section of the configuration. Setting the option "OverrideFromAddress" to "Y" will add a recipient string object below the identity chooser in the write window. The contents default to the chosen identity's address but can be modified freely. This makes it possible to use a different From: address than the one configured in the identity while still using all other settings like the SMTP server. Please note that such mails might be rejected by the  SMTP server. This finally closes #321.

**Comment by tboeckel** [comment]
**Originally on 2013-01-22 20:08:27 +0100**

___
Setting the milestone to YAM 2.8p1, because the duplicate #366 refers to the same feature and is targeted to 2.8p1 as well already.

**Comment by jens-maus** [comment]
**Originally on 2013-07-01 21:28:32 +0200**

___
**Release Note:**
added a new option in the hidden section of the configuration. Setting the option "OverrideFromAddress" to "Y" will add a recipient string object below the identity chooser in the write window. The contents default to the chosen identity's address but can be modified freely. This makes it possible to use a different From: address than the one configured in the identity while still using all other settings like the SMTP server.
