### ISSUE TITLE
Search for update popup after iconification

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#324]
**Originally by _s.hawamdeh@teletu.it_ on 2012-06-06 18:03:49 +0200**

___
Since a while there is a small but not needed behaviour into the search for update functionality.

If you manually search for an update while there is no update availible and then you iconify the program, then once you deiconify it you will have again and again (loop) the same popup window that alert you that there is no update availible .. this always happen after you reopen the program that was iconificated on Workbench and it happen "only" if you are manually searched for an update before ..

I think it's a small bug but evenetually it might be only a not intended behaviour

**Comment by tboeckel** [comment]
**Originally on 2012-06-10 20:17:03 +0200**

___
Fixed in the next nightly build by r6034.
