### ISSUE TITLE
501 Syntactically invalid EHLO argument(s)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#325]
**Originally by _szakacst@gmx.com_ on 2012-06-06 20:28:25 +0200**

___
## Description

Since the multiple smtp was introduced I have been unable to send e-mails via my provider smtp server, on every attempt error message appears:

Bad response from mail server 'smtp.hdsnet.hu' to command 'EHLO':
501 Syntactically invalid EHLO argument(s)
The mail server couldn't execute the command and replied with the above error message.

Couldn't connect to host 'smtp.hdsnet.hu'.
The mail server is currently down or doesn't support the SMTP protocols.

This is the case with MorphOS and AmigaOS3 2.8-dev version, too.
That SMTP server not need security, only username/password is neccessary. However, google's smtp server work without any problem with SSL/TLS security. With version 2.7 there is no problem with smtp servers.

I use MorphOS2.7 as operating system on Pegasos2.

**Comment by tboeckel** [comment]
**Originally on 2012-06-06 20:33:02 +0200**

___
Nothing in SMTP handling was changed, except that it is now possible to have more than one single SMTP server.

To investigate what is going on during the transfer you should start YAM as "YAM debug" from a shell. During the transfer (POP3 and SMTP) lots of stuff will be printed to the shell. Please attach this output to this ticket.

Although we did our best to hide private stuff like passwords please make sure to check the output for such data as we take no responsibility for leaked passwords and hacked accounts.

**Comment by jens-maus** [comment]
**Originally by _szakacst@gmx.com_ on 2012-06-06 23:39:55 +0200**

___
With YAM debug It can see the difference:

with yam 2.7 :
SERVER[0038]: 220 relay01.digicable.hu ESMTP ready
CLIENT[0016]: EHLO hdsnet.hu
SERVER[0059]: 250-relay01.digicable.hu Hello hdsnet.hu [92.249.170.112]
SERVER[0019]: 250-SIZE 15728640
SERVER[0016]: 250-PIPELINING
SERVER[0022]: 250-AUTH PLAIN LOGIN
SERVER[0010]: 250 HELP
CLIENT[0012]: AUTH LOGIN

etc. and e-mail is sent.

But with nightly build:

SERVER[0038]: 220 relay01.digicable.hu ESMTP ready
CLIENT[0019]: EHLO pegasos2_100
SERVER[0044]: 501 Syntactically invalid EHLO argument(s)

That hdsnet.hu was the SMTP-domain in 2.7 .config file, but now that argument is missing from .config for 2.8? I don't know from where is that pegasos2_100 is came from?

**Comment by jens-maus** [comment]
**Originally on 2012-06-06 23:46:42 +0200**

___
Replying to szakacst@…:

> SERVER[0038]: 220 relay01.digicable.hu ESMTP ready
> CLIENT[0019]: EHLO pegasos2_100
> SERVER[0044]: 501 Syntactically invalid EHLO argument(s)
> 
> That hdsnet.hu was the SMTP-domain in 2.7 .config file, but now that argument is missing from .config for 2.8? I don't know from where is that pegasos2_100 is came from?

This seems to be the hostname of your machine configured in your TCP/IP stack. I already suspected that this might be the actual reason for your problems. In a short test it seems that the SMTP server of your provider doesn't like the "_" character in your hostname. I'll see how I can change that and what the official RFC says about that. Thanks for the report and the debug log.

**Comment by jens-maus** [comment]
**Originally on 2012-06-24 14:38:36 +0200**

___
In (5630903):
 * YAM_UT.c, tcp/Connection.c: reworked the GetHostName() function to call
  GetFQDN within Connection.c to always return a syntactically correct hostname
  string (either valid hostname or IP literal string [x.x.x.x]). By having moved
  this functionality to Connection.c it will now perform the DNS request in the
  corresponding thread rather than always in the main thread. This closes #325.
