### ISSUE TITLE
update notification window always pops up after iconify

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#326]
**Originally by _Michael.Merkel@gmx.net_ on 2012-06-09 10:31:54 +0200**

___
## Summary
after "reiconifying" the update notification window always pops up.
## Steps to reproduce
 1. i check for updates. the update notification window popups up telling me that there is one available.
 2. I ignore it by closing the window
 3. I iconifiy YAM
 4. I reopen YAM.

## Expected results
YAM should pop up with the main window showing only
## Actual results
YAM pops up with the main window and also the update notification window open. the notification window is placed in the background.
(i run YAM on it's own screen, btw.)
## Notes
YAM 2.8dev 20120607
OS4.1beta on x1000

regards...
michael

**Comment by tboeckel** [comment]
**Originally on 2012-06-10 14:51:10 +0200**

___
This is the same issue as #324.

**Comment by tboeckel** [comment]
**Originally on 2012-06-10 20:17:43 +0200**

___
Fixed in the next nightly build by r6034.
