### ISSUE TITLE
nightly os3 doesn't load theme images

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#328]
**Originally by _plokklop@fastmail.fm_ on 2012-06-10 00:15:40 +0200**

___
Yam 2.8 [OS 3] Nightly doesn't load theme images anymore.

Last one that worked is the one from 07/05/2012. Anything after that date have blank buttons.
Copying the 'new' images over the 'old' ones doesn't work, same as copying the 'old' ones over the 'new' ones. 

To reproduce, just unpack to ram: and run the program.

Tested under Winuae 2.3.3 and 2.4.2 b4 with os3.9 and updated mui.

**Comment by jens-maus** [comment]
**Originally by _plokklop@fastmail.fm_ on 2012-06-10 00:09:22 +0200**

___
**Attachment added:** `yambug.jpg` (55.8 KiB)
![yambug.jpg](https://yam.ch/attachments/328/yambug.jpg)
yam showing blank buttons

**Comment by tboeckel** [comment]
**Originally on 2012-06-10 14:25:08 +0200**

___
Which theme are you using? From your description I'd guess that you are using a third party theme and its .theme file is not updated yet.

**Comment by jens-maus** [comment]
**Originally by _plokklop@fastmail.fm_ on 2012-06-10 18:54:03 +0200**

___
Replying to thboeckel:
> Which theme are you using? From your description I'd guess that you are using a third party theme and its .theme file is not updated yet.

I'm using the default theme, but the other themes supplied with yam  (no third party) don't work either. As if they can't be loaded by mui anymore.
Everything worked fine with yam from 07/05/2012. When replacing this version with the new one, all the images are gone. Tried to check out if they load, with snoopdos3. Can't see much difference.

**Comment by tboeckel** [comment]
**Originally on 2012-06-11 09:18:03 +0200**

___
I just downloaded the latest nightly build (11.06.2012), unpacked it to RAM: and ran it from there. Apart from the 3 usual errors (DST settings, characters set, missing .addressbook file) there is no other error and all images are displayed correctly.

Did you copy the complete "default" theme directory including the .theme file or just the image files?

**Comment by jens-maus** [comment]
**Originally by _plokklop@fastmail.fm_ on 2012-06-11 21:15:05 +0200**

___
Did some more checking. Seems that akPNG doesn't like your versions after 07/05/12. Loading of the images with WarpPNG and os3.9 PNG works fine, except for the blank background with the os3.9 datatype. So Yam now works again. :) Did you by any change enable or change the alpha layering of the png images within mui ? This would be a logical explanation for showing the empty buttons. Maybe stripping the images from the alpha layer would help.

**Comment by tboeckel** [comment]
**Originally on 2012-06-12 06:23:20 +0200**

___
The only change I can think of is the new drafts folder image, which Martin Merz recently created for us. But then he also did all the other graphics. I don't know if there is any difference.

Of course all images use transparency and this will definitely not be deactivated.

I did my test on a WinUAE installation running OS 3.9. Here I use akPNG 45.95, which is the most recent one available on AmiNet, and have absolutely no problems.
