### ISSUE TITLE
Icon not correctly showed on attachments

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#329]
**Originally by _s.hawamdeh@teletu.it_ on 2012-06-12 02:18:06 +0200**

___
YAM seems not able to show certain format (icons file attached in a mail) until you click manually into them, for example a text file will be always showed correctly so you will see the correct icon of your text file according to the standard icon installed.

Conversely an LhA file attached in a mail received does not show his standard icon until you select it manually

It may be a bug or maybe just a prefs to set (?), altrough i think it would be better if all type of format can be recognized by default without the need to do an extra click to show their proper icon

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2012-06-12 02:18:52 +0200**

___
**Attachment added:** `Text_File_OK.png` (18.0 KiB)
![Text_File_OK.png](https://yam.ch/attachments/329/Text_File_OK.png)
A text file is always showed correctly

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2012-06-12 02:19:31 +0200**

___
**Attachment added:** `LhA_File_default.png` (17.5 KiB)
![LhA_File_default.png](https://yam.ch/attachments/329/LhA_File_default.png)
An LhA file hide his icon until you select it

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2012-06-12 02:19:59 +0200**

___
**Attachment added:** `Lha_File_After_Manual-Click.png` (16.9 KiB)
![Lha_File_After_Manual-Click.png](https://yam.ch/attachments/329/Lha_File_After_Manual-Click.png)
The same LhA file after a manual click

**Comment by tboeckel** [comment]
**Originally on 2012-07-11 09:47:14 +0200**

___
Sorry for the late reply, but no, everything is working as expected. You just failed to notice the details ;)

Attachments can have an arbitrary size and hence the decoding of the attachment might take an unpredictable amount of time. But without decoding the attachment YAM is not able to detect the true type of that file. Now imagine YAM would automatically decode each and every attachment just for the sake of a different icon image. This would hurt performance a lot more than it does now already. But the consequence is that YAM cannot show the correct icon in the first place, but just a generic replacement for arbitrary file types.
