### ISSUE TITLE
YAM crashed when I pressed Delete key in Ediitor window whilst HD LED flashed

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#330]
**Originally by _hypexed@yahoo.com.au_ on 2012-07-04 17:12:14 +0200**

___
I was editing an email. I pressed Delete. At the same time I noticed the HD light flashed briefly. And then YAM crashed instantly into a Grim Reaper. That's all I know. :-)

Crashlogs attached.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2012-07-04 16:50:13 +0200**

___
**Attachment added:** [`Crashlog_YAM_2012-06-16_02-04-37.txt`](https://yam.ch/attachments/330/Crashlog_YAM_2012-06-16_02-04-37.txt) (33.7 KiB)

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2012-07-04 16:50:37 +0200**

___
**Attachment added:** [`Crashlog_YAM_2012-06-16_02-04-30.txt`](https://yam.ch/attachments/330/Crashlog_YAM_2012-06-16_02-04-30.txt) (33.7 KiB)

**Comment by tboeckel** [comment]
**Originally on 2012-07-04 19:01:38 +0200**

___
This is a known bug of TextEditor.mcc. Unfortunately I haven't been able to track it down to a point where I can tell for sure what is causing the crash. It finally happens in newlib.library, but the last code location of TE.mcc as pointed out by the crashlog does not contain a suitable function call.

I hope Jörg Strohmayer can help us.

**Comment by tboeckel** [comment]
**Originally on 2012-07-09 09:18:42 +0200**

___
I just built a test version of TextEditor.mcc with some enhanced limit checks in the crashing function. I cannot tell if this really fixes the crashes, but at least I hope it does. Please give it a try and report back here. Please note that the version number and date is the same as for the last official release, so don't mix these up.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2012-07-10 17:54:15 +0200**

___
Thanks for this. I don't know how I will go repeating it as the crash was in a rare situation. Guess I could just use brute force on my delete key to see if there is a reaction but that's not practical. :-)

**Comment by tboeckel** [comment]
**Originally on 2012-07-12 09:42:32 +0200**

___
Replying to hypexed@…:
> Thanks for this. I don't know how I will go repeating it as the crash was in a rare situation. Guess I could just use brute force on my delete key to see if there is a reaction but that's not practical. :-)

I very much doubt that the DEL key is the only one to trigger this bug. For me happens with any key, but unfortunately about 3 times per year only. This is a quite weak basis to search for a bug. Especially when the crash log does not point to a sensible position.

**Comment by tboeckel** [comment]
**Originally on 2012-07-12 09:51:04 +0200**

___
I just attached a new version of TextEditor.mcc (now with a bumped date at least) which contains some recent fixes. I very much assume TextEditor.mcc to either trash memory or to operate on memory outside the allocated range which finally makes newlib.library go crazy.

**Comment by tboeckel** [comment]
**Originally on 2012-07-12 10:03:15 +0200**

___
**Attachment added:** [`TextEditor.mcc.lha`](https://yam.ch/attachments/330/TextEditor.mcc.lha) (72.0 KiB)
TextEditor.mcc 15.38 (12.7.2012)

**Comment by tboeckel** [comment]
**Originally on 2012-07-19 20:24:14 +0200**

___
Any new crashes with the (hopefully) fixed TE.mcc?

**Comment by tboeckel** [comment]
**Originally on 2012-07-25 12:18:43 +0200**

___
Bump!

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2012-07-26 21:49:24 +0200**

___
Hi. I haven't had any further crashes. I will test the newer version also. Somethhng that may be of interest, I do get the following from the first TE you attached:

```
../include/mccinit.c:968:LibInit(TextEditor.mcc)
** TextEditor.mcc v15.38 startup **********************
Exec version: v53.25
Initializing runtime debugging:
set debug classes/flags (env:texteditor.mcc.debug): 000000f6/00000003
** Normal processing follows ***************************************
../include/mccinit.c:1133:LibOpen(TextEditor.mcc): 0
../include/mccinit.c:1272:MCC_Query(TextEditor.mcc): 0
../include/mccinit.c:1133:LibOpen(TextEditor.mcc): 1
../include/mccinit.c:1272:MCC_Query(TextEditor.mcc): 0
../include/mccinit.c:1211:LibClose(TextEditor.mcc): 2
../include/mccinit.c:1133:LibOpen(TextEditor.mcc): 1
../include/mccinit.c:1272:MCC_Query(TextEditor.mcc): 0
    InitConfig.c:98:couldn't get config item: 0xad00005f
    InitConfig.c:98:couldn't get config item: 0xad000054
    InitConfig.c:98:couldn't get config item: 0xad000055
    InitConfig.c:98:couldn't get config item: 0xad000059
    InitConfig.c:98:couldn't get config item: 0xad00005a
    InitConfig.c:98:couldn't get config item: 0xad000066
    InitConfig.c:98:couldn't get config item: 0xad000067
    InitConfig.c:98:couldn't get config item: 0xad00006b
   InitConfig.c:98:couldn't get config item: 0xad000055
../include/mccinit.c:1089:LibExpunge(TextEditor.mcc): 2
../include/mccinit.c:1089:LibExpunge(TextEditor.mcc): 2
../include/mccinit.c:1089:LibExpunge(TextEditor.mcc): 2
../include/mccinit.c:1089:LibExpunge(TextEditor.mcc): 2
  InitConfig.c:98:couldn't get config item: 0xad000055
           BlockOperators.c:627:text = 0x557e2818 "
```

**Comment by tboeckel** [comment]
**Originally on 2012-07-26 22:02:55 +0200**

___
That is just standard debug output generated by TextEditor.mcc. Or are you referring to anything "bad" within there?

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2012-07-28 20:31:13 +0200**

___
No, nothing bad, but the "couldn't get config item:" lines did concern me.

**Comment by tboeckel** [comment]
**Originally on 2012-07-28 20:42:40 +0200**

___
That message only means that TE.mcc uses its default value, because there was no custom setting found in the configuration.

**Comment by tboeckel** [comment]
**Originally on 2012-08-06 10:02:55 +0200**

___
This bug should be fixed with the recently released TextEditor.mcc 15.39. If it happens again nevertheless, then please reopen this ticket.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2012-08-06 17:08:30 +0200**

___
Thanks. That's good to know.
