### ISSUE TITLE
YAM tried to open file with previous message subject as name before crashing when sending mail

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#331]
**Originally by _hypexed@yahoo.com.au_ on 2012-07-04 17:13:09 +0200**

___
This is kind of complicated to explain. And it's happened enough now to annoy me. I sent one email and it was fine. The subject was "Re: MAUG meetings, 7/5/2012, 10:15 am".

I then sent another and for comparison the subjject was "Re: MAUG Amiga One Sata".  I then got a file requester trying to open a file called " meetings, 7/5/2012, 10". What!? It kept coming back. I tried to assign it to RAM but you know as it always happens with those bugs assigning it doesn't work. Eventually it crashed. I attach those two emails mentioned and three crash logs. :-)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2012-07-04 17:03:33 +0200**

___
**Attachment added:** [`Re__MAUG_Amiga_One_Sata.eml`](https://yam.ch/attachments/331/Re__MAUG_Amiga_One_Sata.eml) (4.6 KiB)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2012-07-04 17:04:02 +0200**

___
**Attachment added:** [`Re__MAUG_meetings,_7_5_2012,_10_15_am.eml`](https://yam.ch/attachments/331/Re__MAUG_meetings,_7_5_2012,_10_15_am.eml) (1.4 KiB)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2012-07-04 17:04:36 +0200**

___
**Attachment added:** [`Crashlog_YAM_2012-07-05_00-23-38.txt`](https://yam.ch/attachments/331/Crashlog_YAM_2012-07-05_00-23-38.txt) (34.4 KiB)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2012-07-04 17:05:03 +0200**

___
**Attachment added:** [`Crashlog_YAM_2012-07-05_00-23-29.txt`](https://yam.ch/attachments/331/Crashlog_YAM_2012-07-05_00-23-29.txt) (34.5 KiB)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2012-07-04 17:05:28 +0200**

___
**Attachment added:** [`Crashlog_YAM_2012-07-05_00-25-38.txt`](https://yam.ch/attachments/331/Crashlog_YAM_2012-07-05_00-25-38.txt) (35.0 KiB)

**Comment by tboeckel** [comment]
**Originally on 2012-07-04 19:16:51 +0200**

___
I just tried to reproduce this issue using YAM 2.8-dev and did the following:
1. import both mail into the outgoing folder.
2. double click the first mail and the click the "Send later" button
3. the same for the second mail

So far nothing crashed here, but maybe I did it wrong. Please provide a step by step instruction how to reproduce this issue using your two example mails.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2012-07-10 17:54:16 +0200**

___
Hi.

What I did was reply to the first and send it off. Then I replied to the second and sent it off. And this is where YAM went funny.

So I typed up both before sending them away. But here I just repeated the procedure to myself and they were sent fine. So it looks like a rare condition which I have a habit of finding. :-)

According to the crash log something went wrong from YAM:FO_UpdateStatistics() that caused the OS to think it was opening a file. But the last entry in the crash log is a kernel routine but not a DOS routine. :-?

**Comment by tboeckel** [comment]
**Originally on 2012-07-11 16:08:20 +0200**

___
If memory was trashed before by either YAM itself or any other application then the crash log might point anywhere and the last sensible location within YAM must not necessarily be the guilty one. It might just happen to occur in the crash log because the data it is was using were malformed by the trashed memory.

As long as you cannot reproduce this issue it is unlikely that this crash will be fixed.

**Comment by jens-maus** [comment]
**Originally on 2013-01-19 20:47:13 +0100**

___
I agree with thore here. As long as you cannot reproduce the problem youself we will have a hard time finding a proper fix. In addition, now that 2.8 is released, did it happen to you again?

**Comment by tboeckel** [comment]
**Originally on 2013-01-22 12:32:10 +0100**

___
Please refer to #377 for updated versions of BetterString.mcc which no longer should trash memory. The effects you describe very much smell like trashed memory. Please reopen this ticket if it happens again nevertheless.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-23 14:44:46 +0100**

___
Since installing 2.8 I haven't seen this. I will test BetterString.mcc and see how it goes. Hopefully the end of  a buggy ride! :-)
