### ISSUE TITLE
double clicking and URL doesn't do anything

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#333]
**Originally by _javierdlr@euskalnet.net_ on 2012-07-10 18:31:06 +0200**

___
## Summary
YAM28.dev 10.07.2012 double clicking on an URL doesn't do anything.
Have 'URLOpen "%p"' in prefs/Double clicking and URL option

## Steps to reproduce
 1. try to double clikc an URL in read msg
 2. does nothing

## Expected results
open browser and show URL
## Actual results
nothing
## Notes

**Comment by tboeckel** [comment]
**Originally on 2012-07-11 07:29:42 +0200**

___
In (ee23608):
 * mui/ReadMailGroup.c: corrected the parameter order of the double click hook function. This closes #333.
