### ISSUE TITLE
Bar between msg list and read pane doesn't get snapshoted

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#334]
**Originally by _javierdlr@euskalnet.net_ on 2012-07-10 19:48:37 +0200**

___
## Summary
Everytime I load for first time YAM2.8dev the new bar separating msg list and (embedded) read pane is set at top of msg list (only showinf 4 msg) I can move such bar, but if I restart YAM such bar isn't snapshotted and always show a tiny msg list and a "big" read pane.

## Steps to reproduce
  1.2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2012-07-10 18:38:25 +0200**

___
**Attachment added:** `sgrab000b.png` (19.6 KiB)
![sgrab000b.png](https://yam.ch/attachments/334/sgrab000b.png)
my YAM always opens like this, msg list & read pane does't snapshot

**Comment by tboeckel** [comment]
**Originally on 2012-08-06 16:32:44 +0200**

___
In (bea782a):
 * YAM_MA.c, YAM_UT.c: the vertical weight of the mail list was always set for the wrong group object and hence YAM saved and restored the wrong layout values. This closes #334.
