### ISSUE TITLE
'Download messages larger than' value doesn't get saved (stays 1024)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#335]
**Originally by _javierdlr@euskalnet.net_ on 2012-07-13 00:06:01 +0200**

___
## Summary
MSG_CO_DOWNLOAD_LARGE_MAILS1

_Download messages larger than

value is 1024KB, if I change it to 128KB and restart YAM it doesn't get saved in config.

## Steps to reproduce
  1.Change 'Download messages larger than' value to 128
  2.Save settings

## Expected results
128KB

## Actual results
Always 1024KB

## Notes

**Comment by jens-maus** [comment]
**Originally on 2012-07-13 00:07:46 +0200**

___
Thanks for the report. We will investigate as soon as possible. However, please login to the yam.ch webpage next time you report an issue or comment on a ticket!

**Comment by tboeckel** [comment]
**Originally on 2012-07-13 06:33:10 +0200**

___
In (9a52e76):
 * YAM_COs.c: added the saving and loading of the size limit for large mails again. This closes #335.
