### ISSUE TITLE
YAM crashes right at startup when geting e-mails from server

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#336]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-07-16 17:15:13 +0200**

___
## Summary
YAM crashes right at startup when geting e-mails from server. I get hits in the log. The latest working version is the one from 20120626. Used under MorphOS 3.1

## Steps to reproduce
 1. start YAM
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-07-16 17:15:32 +0200**

___
**Attachment added:** [`yam.log`](https://yam.ch/attachments/336/yam.log) (4.4 KiB)

**Comment by jens-maus** [comment]
**Originally on 2012-07-16 22:10:36 +0200**

___
Please provide a debug log using the debug version of the nightly build and issue a "setenv yamdebug @all all" call before starting the debug version. Be prepared to catch a lot of debug information on the serial line and post the last few lines here please.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-07-17 15:49:08 +0200**

___
**Attachment added:** [`yam_1.log`](https://yam.ch/attachments/336/yam_1.log) (1.8 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-07-17 15:49:22 +0200**

___
Please find attached the yam log.

**Comment by tboeckel** [comment]
**Originally on 2012-07-17 16:03:51 +0200**

___
Replying to rmsyam:
> Please find attached the yam log.

Ask you should have noticed yourself this in an incomplete log. Does your machine freeze hard? I am affraid we cannot help you with such a crippled log. Please try to provide a complete one.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-07-17 16:11:48 +0200**

___
Replying to thboeckel:
> Replying to rmsyam:
> > Please find attached the yam log.
> 
> Ask you should have noticed yourself this in an incomplete log. Does your machine freeze hard? I am affraid we cannot help you with such a crippled log. Please try to provide a complete one.

No it's not the machine that freezes but YAM. I can provide a complete log but even lha compressed it's 2.5 MB, no compression it's 45 MB. Can I send it privatly?

**Comment by tboeckel** [comment]
**Originally on 2012-07-17 16:33:28 +0200**

___
Replying to rmsyam:
> No it's not the machine that freezes but YAM. I can provide a complete log but even lha compressed it's 2.5 MB, no compression it's 45 MB. Can I send it privatly?

Of course it is at least YAM that is freezing due to the crash :)

I just asked because the log you attached somehow got "cut" in the middle of a line which typically indicates a fully frozen machine.

However, please go ahead and send the log to us in private. Without it this bug cannot be fixed.

**Comment by tboeckel** [comment]
**Originally on 2012-07-19 20:23:13 +0200**

___
After lots of tests by Christoph Pölzl this bug is finally fixed. Thanks a lot Christoph!
