### ISSUE TITLE
Selecting Config/Read generates hits, MorphOS version of YAM

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#338]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-07-20 15:27:33 +0200**

___
## Summary
Hits are generated when selecting Read in Config.

## Steps to reproduce
 1. Open Config
 2. Select Read

## Notes

**Comment by tboeckel** [comment]
**Originally on 2012-07-25 12:16:24 +0200**

___
In (7a67893):
 * mui/FilterChooser.c, mui/IdentityChooser.c, mui/MailServerChooser.c: added a workaround for a bug in MUI4 of MorphOS which occurs when no entries are available for selection. MorphOS uses a local and non-static variable as replacement in this case, which of course ceased to live as soon as the object's constructor is left. As consequence random memory was accessed.
