### ISSUE TITLE
Reply to sender and all recipients seems not to work

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#339]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-07-20 15:31:52 +0200**

___
## Summary
When selecting Reply and "sender and all recipients" only the sender is used in the new write window but no recipients at all even if there are any.

## Steps to reproduce
 1. Select Reply
 2. Select "sender and all recipients"

## Notes

**Comment by tboeckel** [comment]
**Originally on 2012-07-22 14:20:36 +0200**

___
In (9d3871d):
 * YAM_WR.c: added the missing CC addresses when replying to all recipients. This closes #339.
