### ISSUE TITLE
grim reaper after fetching mails from server

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#340]
**Originally by _Michael.Merkel@gmx.net_ on 2012-07-22 19:25:05 +0200**

___
## Summary
after fetching the mails from the server i got a grim reaper (attached)

## Notes
20.07.2012 (GCC 4.5.3, !r6157)

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2012-07-22 19:25:25 +0200**

___
**Attachment added:** [`Crashlog_YAM_2012-07-22_19-14-07.txt`](https://yam.ch/attachments/340/Crashlog_YAM_2012-07-22_19-14-07.txt) (38.5 KiB)
grim reaper

**Comment by tboeckel** [comment]
**Originally on 2012-07-22 20:26:03 +0200**

___
The location of the crash is the same as for ticket #341. Thus I assume this ticket is just a duplicate of that ticket and has nothing to do with the download process itself, but only with reading mails.
