### ISSUE TITLE
grim reaper when jumping to the next unread mail

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#341]
**Originally by _Michael.Merkel@gmx.net_ on 2012-07-22 19:26:58 +0200**

___
## Summary
i jumped to the next unread mail and got a grim reaper (see attachment)

## Steps to reproduce
  1.2. shift+right
  i need to try to reproduce - just wanted to file this first to not loose the log

## Notes
20.07.2012 (GCC 4.5.3, !r6157)

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2012-07-22 19:27:11 +0200**

___
**Attachment added:** [`Crashlog_YAM_2012-07-22_19-19-42.txt`](https://yam.ch/attachments/341/Crashlog_YAM_2012-07-22_19-19-42.txt) (39.1 KiB)
grim reaper

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2012-07-22 19:29:19 +0200**

___
ok. i can continue - and after several seconds i see the following error:

Es wurden einige nicht erlaubte Zeichen während des Dekodierens des base64-kodierten

MIME-Teiles 1 der Nachricht '!YAM:Folders/betatestAEonX1000/QP-10AAICuA=.001,N'

gefunden. Die Ausgabe könnte daher möglicherweise ungültige Daten enthalten oder aber

beschädigt sein.

Dies kann durch eine falsche Kodierung der Nachricht durch den Sender hervorgerufen

worden sein oder dadurch, dass der base64-kodierte Teil der Nachricht während der

Übertragung verstümmelt wurde.

**Comment by tboeckel** [comment]
**Originally on 2012-07-23 15:47:23 +0200**

___
In (652003d):
 * mime/base64.c: fixed a NULL pointer access in case the decoding process was aborted early due to invalid characters. This closes #341.
