### ISSUE TITLE
YAM crashes on OS4 when sending E-Mails

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#342]
**Originally by _hitman@codehq.org_ on 2012-07-23 07:26:36 +0200**

___
## Summary
I see on the YAM mailing list there is already a thread about this, but I cannot reply to it as YAM crashes when I try to do so!  For me YAM crashes when I try to write a new E-Mail or to forward any E-Mail and it happens for all addresses.

I am on the OS4 beta testing list and recently updated all components after a long absense from testing.  At some point during the updating YAM started crashing when sending E-Mails.  It could be due to YAM, an OS4 beta component or one of the MUI classes such as NList etc.

## Steps to reproduce
 1. Try to send an E-Mail to any address and it crashes when you hit "send"

## Expected results
This is obvious.  :-)

## Actual results
A crash every time.  I have a Grim Reaper crash report that I have added to this ticket.

## Notes
All OS4 beta components are up to date and I have the version of YAM that was released on 23.07.2012.  However, it happens with all recent (ie. In the last month) versions of YAM.

Versions of libraries and classes installed (I think I have the latest of everything):

muimaster.library 20.5722
BetterString.mcc 11.22 [OS4/PPC] (12.05.2012)
BetterString.mcp 11.22 [OS4/PPC] (12.05.2012)
HotkeyString.mcc 12.18 [OS4/PPC] (12.05.2012)
NBalance.mcc 15.12 [OS4/PPC] (12.05.2012)
NBitmap.mcc 15.16 [OS4/PPC] (12.05.2012)
NFloattext.mcc 19.67 [OS4/PPC] (12.05.2012)
NList.mcc 20.131 [OS4/PPC] (12.05.2012)
NListtree.mcc 18.38 [OS4/PPC] (12.05.2012)
NListtree.mcp 18.26 [OS4/PPC] (12.05.2012)
NListview.mcc 19.86 [OS4/PPC] (12.05.2012)
NListviews.mcp 19.82 [OS4/PPC] (12.05.2012)
TextEditor.mcc 15.38 [OS4/PPC] (12.05.2012)
TextEditor.mcp 15.38 [OS4/PPC] (12.05.2012)
TheBar.mcc 26.9 [OS4/PPC] (12.05.2012)
TheBar.mcp 26.9 [OS4/PPC] (12.05.2012)
TheBarVirt.mcc 26.9 [OS4/PPC] (12.05.2012)
TheButton.mcc 26.9 [OS4/PPC] (12.05.2012)

If you need any further information then don't hesitate to ask.  I can also run custom builds for you if you wish and I'm a developer so no worries with technical questions.  :-)

Unfortunately I have only one NG Amiga and it has only two partitions and no CD-ROM drive, so I cannot install an older version of OS4 to try to determine when this crash started to happen.  Looks like we'll have to debug it from the callstack.  :-(

**Comment by jens-maus** [comment]
**Originally by _hitman@codehq.org_ on 2012-07-23 07:16:31 +0200**

___
**Attachment added:** [`Crashlog_YAM_2012-07-23_07-01-43.txt`](https://yam.ch/attachments/342/Crashlog_YAM_2012-07-23_07-01-43.txt) (27.0 KiB)
Grim Reaper crash dump from sending E-Mail

**Comment by tboeckel** [comment]
**Originally on 2012-07-23 09:05:19 +0200**

___
It is quite unlikely that AmigaOS4 is guilty, but YAM itself.

Please download the debug version of the next nightly build of YAM and produce a "mail" debug log with it. Details about YAM's debug facilities can be found in the [FAQ](http://yam.ch/wiki/FAQ/Debugging#BasicsaboutYAMsdebuggingfacilities). Pleast add the log as an attachment here.

**Comment by tboeckel** [comment]
**Originally on 2012-07-25 12:17:33 +0200**

___
In (7a67893):
 * mui/FilterChooser.c, mui/IdentityChooser.c, mui/MailServerChooser.c: added a workaround for a bug in MUI4 of MorphOS which occurs when no entries are available for selection. MorphOS uses a local and non-static variable as replacement in this case, which of course ceased to live as soon as the object's constructor is left. As consequence random memory was accessed.

**Comment by tboeckel** [comment]
**Originally on 2012-07-26 06:49:16 +0200**

___
Sorry, I closed the wrong ticket by accident.

Anyway, we still need this log to be able to fix this issue.

**Comment by jens-maus** [comment]
**Originally by _hitman@codehq.org_ on 2012-07-28 15:57:37 +0200**

___
**Attachment added:** [`yam_debug.lha`](https://yam.ch/attachments/342/yam_debug.lha) (16.8 KiB)
Debug log from running debug version of YAM

**Comment by jens-maus** [comment]
**Originally by _hitman@codehq.org_ on 2012-07-28 20:31:39 +0200**

___
Replying to thboeckel:
> Sorry, I closed the wrong ticket by accident.
> 
> Anyway, we still need this log to be able to fix this issue.

Ok, please find attached a log file generated by using the debug version of YAM and the option:

setenv yamdebug all,file:ram:yam_debug.txt

If you need another run performed, please don't hesitate to ask!

**Comment by tboeckel** [comment]
**Originally on 2012-07-28 20:39:24 +0200**

___
Replying to colinward:
> Replying to thboeckel:

> setenv yamdebug all,file:ram:yam_debug.txt

Please extend this to 
setenv yamdebug @all,all,file:ram:yam_debug.txt

This will produce a huge log (several MB!), but we need this one to know in which function YAM really crashes. Although there is something in the crashlog already this does not yet point to the really last bit within YAM due to compiler optimizations.

**Comment by tboeckel** [comment]
**Originally on 2012-08-07 06:44:43 +0200**

___
Bump!

**Comment by jens-maus** [comment]
**Originally by _hitman@codehq.org_ on 2012-08-08 10:41:29 +0200**

___
**Attachment added:** [`yam_high_debug.lha`](https://yam.ch/attachments/342/yam_high_debug.lha) (53.4 KiB)
Debug log from running debug version of YAM with higher debug level

**Comment by jens-maus** [comment]
**Originally by _hitman@codehq.org_ on 2012-08-08 10:47:37 +0200**

___
Replying to thboeckel:
> Bump!

Oops!  Sorry, I missed your last message somehow.  Ok, please find attached the requested log file.

**Comment by tboeckel** [comment]
**Originally on 2012-08-08 12:20:25 +0200**

___
Replying to colinward:
> Ok, please find attached the requested log file.

Unfortunately the log is truncated, most probably because of the buffered file I/O which did not yet write out the last lines when the crash happened.

Could you please produce the same log again with the next nightly build? That will flush all lines immediately to ensure the log really always contains all debug output.

Alternatively you can capture the output by using Sashimi with the current nightly build already. Just set ENV:yamdebug to "@all,all" (no file:... stuff) and then run YAM. When YAM eventually crashes quit Sashimi to ensure it has written all captured text to the log file as explained in the FAQ.

**Comment by tboeckel** [comment]
**Originally on 2012-08-11 20:55:23 +0200**

___
Bump bump!

**Comment by jens-maus** [comment]
**Originally by _hitman@codehq.org_ on 2012-08-15 08:01:23 +0200**

___
Replying to thboeckel:
> Bump bump!

Sorry, been away!  Please find attached the latest trace from the 15.08.2012 nightly build.  Any more traces are required I should be more available now.  :-)

**Comment by jens-maus** [comment]
**Originally by _hitman@codehq.org_ on 2012-08-15 08:02:31 +0200**

___
**Attachment added:** [`yam_15_08_2012_debug.lha`](https://yam.ch/attachments/342/yam_15_08_2012_debug.lha) (174.8 KiB)
Debug log from running 15.08.2012 debug version of YAM with high debug level

**Comment by tboeckel** [comment]
**Originally on 2012-08-15 10:54:25 +0200**

___
It seems you have no valid SMTP server configured for the identity you are composing the mail with. Please check the SMTP server in your Identity settings (Config -> Identities -> Mail server (SMTP)).

**Comment by jens-maus** [comment]
**Originally on 2012-08-15 15:24:34 +0200**

___
In (1de3c53):
 * src/YAM.c: moved the method stack init¿alization somewhat more up to make sure
  everything is properly initialized. This should close #342.

**Comment by jens-maus** [comment]
**Originally by _hitman@codehq.org_ on 2012-08-17 07:12:40 +0200**

___
Good and bad news on this bug!

The good news is that it is now fixed and I am able to send E-Mails without it crashing.  The bad news is that after sending E-Mail, it now crashes at shutdown.  I am not sure if this is a related bug or a new one.  I tried increasing the stack to 64k but it still crashes and it is entirely reproducible, at least for forwarding E-Mails.

I will attach a new crash log for you to look at - would you like me to open a whole new bug?

**Comment by jens-maus** [comment]
**Originally by _hitman@codehq.org_ on 2012-08-17 07:16:43 +0200**

___
**Attachment added:** [`Crashlog_YAM_2012-08-17_06-12-28.txt`](https://yam.ch/attachments/342/Crashlog_YAM_2012-08-17_06-12-28.txt) (24.5 KiB)
New crash at shutdown now initial forwarding bug is fixed

**Comment by tboeckel** [comment]
**Originally on 2012-08-17 09:28:53 +0200**

___
Replying to colinward:

> The good news is that it is now fixed and I am able to send E-Mails without it crashing.  The bad news is that after sending E-Mail, it now crashes at shutdown.  I am not sure if this is a related bug or a new one.  I tried increasing the stack to 64k but it still crashes and it is entirely reproducible, at least for forwarding E-Mails.
> 
> I will attach a new crash log for you to look at - would you like me to open a whole new bug?

No need for a new ticket. I just fixed this bug. The application's destructor accessed the global configuration which had been freed microseconds before. The next nightly build should not crash anymore.

To add, this crash only happened if the list of cached EMail addresses was modifies, i.e. new addresses were added. Without such a change everything went fine.

**Comment by jens-maus** [comment]
**Originally by _hitman@codehq.org_ on 2012-08-17 10:20:26 +0200**

___
Replying to thboeckel:
> No need for a new ticket. I just fixed this bug. The application's destructor accessed the global configuration which had been freed microseconds before. The next nightly build should not crash anymore.
> 
> To add, this crash only happened if the list of cached EMail addresses was modifies, i.e. new addresses were added. Without such a change everything went fine.

Thanks for the quick response!

Interestingly, when I tried to forward the E-Mail I tried forwarding it to my Yahoo address.  I have often forwarded E-Mails to that address in the past and so when I start typing the address in the to: field it automatically fills out the address.  However, this time this did not happen - it was as though it had forgotten the cached list of addresses.  This explains why the address was considered "new" in the cache.  Has something changed recently that would cause YAM to discard the cache?  ie.  A cache format change?

**Comment by jens-maus** [comment]
**Originally on 2012-08-18 08:23:53 +0200**

___
Replying to colinward:
 
> Thanks for the quick response!
> 
> Interestingly, when I tried to forward the E-Mail I tried forwarding it to my Yahoo address.  I have often forwarded E-Mails to that address in the past and so when I start typing the address in the to: field it automatically fills out the address.  However, this time this did not happen - it was as though it had forgotten the cached list of addresses.  This explains why the address was considered "new" in the cache.  Has something changed recently that would cause YAM to discard the cache?  ie.  A cache format change?

Well, the email cache is implemented as a buffer with a maximum length. That means it will only carry a certain amount of mail addresses. And as soon as it overflows it removes mail addresses which haven't been used for a while. So if you haven't used your yahoo mail address for a while it will be automatically removed from the email cache in case you have sent mails to various other mail addresses exceeding the currently set amount of max addresses in the cache. Beside that nothing has change in the email cache format for a while.

**Comment by tboeckel** [comment]
**Originally on 2012-08-20 07:28:04 +0200**

___
Replying to damato:

> Well, the email cache is implemented as a buffer with a maximum length. That means it will only carry a certain amount of mail addresses. And as soon as it overflows it removes mail addresses which haven't been used for a while. So if you haven't used your yahoo mail address for a while it will be automatically removed from the email cache in case you have sent mails to various other mail addresses exceeding the currently set amount of max addresses in the cache. Beside that nothing has change in the email cache format for a while.

The most obvious explanation is even more simple. Due to the crash the .emailcache file was not written completely and hence did not contain certain addresses anymore. Thus these were "new" again for YAM.

**Comment by jens-maus** [comment]
**Originally by _hitman@codehq.org_ on 2012-08-22 13:53:31 +0200**

___
> Replying to damato:
> 
> The most obvious explanation is even more simple. Due to the crash the .emailcache file was not written completely and hence did not contain certain addresses anymore. Thus these were "new" again for YAM.

I have checked and yes, it turns out that this is indeed the case!  The .emailcache file was zero bytes.  After sending an E-Mail and exiting cleanly with last night's build that has the bugs fixed, the .emailcache file has the target address added correctly to it, and then YAM works as expected again.

Thanks very much in helping to sort out this problem - I was a bit lost without YAM!
