### ISSUE TITLE
No content in Error messages window, it's empty

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#344]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-08-03 06:42:27 +0200**

___
## Summary

If an error occurs and the Error message window comes up, it's empty, there is not content in the window.

## Steps to reproduce
 1.
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-08-03 06:43:24 +0200**

___
**Attachment added:** `ScreenGrab.png` (1097.2 KiB)
![ScreenGrab.png](https://yam.ch/attachments/344/ScreenGrab.png)

**Comment by tboeckel** [comment]
**Originally on 2012-08-03 07:34:55 +0200**

___
I just logged into web.de too early again (there is a time limit of 15 minutes) and got a perfectly readable error message. Does this happen in certain situations only for you? From the screeshot I can see that you were writing a new mail. Perhaps this is specific to this situation only.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-08-03 12:00:07 +0200**

___
Replying to thboeckel:
> I just logged into web.de too early again (there is a time limit of 15 minutes) and got a perfectly readable error message. Does this happen in certain situations only for you? From the screeshot I can see that you were writing a new mail. Perhaps this is specific to this situation only.

Well yes/no... yes I was writing a new mail and the error messages window poped up because I selected forward a message and YAM complained. For now I can confirm that the error messages window is empty in this situation and also when for example YAM couldn't connect to the mail server. To me I rather think it's not a specific situation but global. Could you tell me how I could test this in several situations?

**Comment by tboeckel** [comment]
**Originally on 2012-08-06 10:13:29 +0200**

___
Replying to rmsyam:
> Well yes/no... yes I was writing a new mail and the error messages window poped up because I selected forward a message and YAM complained. For now I can confirm that the error messages window is empty in this situation and also when for example YAM couldn't connect to the mail server. To me I rather think it's not a specific situation but global. Could you tell me how I could test this in several situations?

Could please state exactly what you did in which sequence. So far I was not able to reproduce this issue my self, no matter how many mails I replied to.

For the case that an error message is triggered when trying to connect to a server please provide a simple "net" log. This will include any error messages produced by the threads.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-08-07 06:56:20 +0200**

___
Replying to thboeckel:
> Replying to rmsyam:
> > Well yes/no... yes I was writing a new mail and the error messages window poped up because I selected forward a message and YAM complained. For now I can confirm that the error messages window is empty in this situation and also when for example YAM couldn't connect to the mail server. To me I rather think it's not a specific situation but global. Could you tell me how I could test this in several situations?
> 
> Could please state exactly what you did in which sequence. So far I was not able to reproduce this issue my self, no matter how many mails I replied to.
> 
> For the case that an error message is triggered when trying to connect to a server please provide a simple "net" log. This will include any error messages produced by the threads.

Just to make sure that I explained it correctely: it goes only here that the Error messages window **is empty**, there is no content which is displayed in this window. So if an error occured, I can't see what it caused because the window is empty.

I give you an example here: sometimes when YAM could not connect for whatever reason to the mailserver to get mails, then the Error messages window pops up. but it is empty instead of it's stated that YAM could not retreive the mails because it could not connect to the mailserver.

I hope I was clear enough, otherwise please let me know.

**Comment by tboeckel** [comment]
**Originally on 2012-08-07 07:33:48 +0200**

___
Replying to rmsyam:

> I give you an example here: sometimes when YAM could not connect for whatever reason to the mailserver to get mails, then the Error messages window pops up. but it is empty instead of it's stated that YAM could not retreive the mails because it could not connect to the mailserver.

This is the reason why I was asking for a "net" log. Apart from the usual network traffic such a log also includes error messages from a thread long before it is finally shown (visible or invisible) in the error window.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-08-07 08:20:43 +0200**

___
**Attachment added:** [`yam.log`](https://yam.ch/attachments/344/yam.log) (19.6 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-08-07 08:21:03 +0200**

___
Replying to thboeckel:
> Replying to rmsyam:
> 
> > I give you an example here: sometimes when YAM could not connect for whatever reason to the mailserver to get mails, then the Error messages window pops up. but it is empty instead of it's stated that YAM could not retreive the mails because it could not connect to the mailserver.
> 
> This is the reason why I was asking for a "net" log. Apart from the usual network traffic such a log also includes error messages from a thread long before it is finally shown (visible or invisible) in the error window.

Please find attached the netlog logfile.

**Comment by tboeckel** [comment]
**Originally on 2012-08-07 08:31:04 +0200**

___
Replying to rmsyam:

> Please find attached the netlog logfile.

Did you get an empty error message during this run? All I can see is that there were no messages to download on the server, but this should not cause any errors.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-08-07 09:04:43 +0200**

___
Replying to thboeckel:
> Replying to rmsyam:
> 
> > Please find attached the netlog logfile.
> 
> Did you get an empty error message during this run? All I can see is that there were no messages to download on the server, but this should not cause any errors.

No I didn't, no errors! I mentioned such an example only to explain that when an Error messages window opens the error is not shown, or perhaps invisible.

**Comment by tboeckel** [comment]
**Originally on 2012-08-08 07:35:58 +0200**

___
In (8f284e5):
 * YAM_ER.c: reworked the handling of overflowed error messages added some debug output in case setting up the final error message fails.

Reported as having been fixed by Christoph Pölzl.

**Comment by tboeckel** [comment]
**Originally on 2012-08-09 16:44:12 +0200**

___
In (d313b77):
 * YAM_ER.c: don't rely on MUI's notifications to (re)display the current message as it seems MUI4 on MorphOS does not trigger the notification under the same circumstances as MUI3 does anymore.
