### ISSUE TITLE
Processor 100% creating interface

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#346]
**Originally by _paraphonista@gmail.com_ on 2012-08-16 08:39:03 +0200**

___
## Summary
Since july, YAM doesn't load anymore. It goes up to Creating interface, then processor time goes 100% and nothing happens.
I did some experiments. The last working version is the one dated 16 july (I have to change the system-time in order to use it).
BUT, if I install more recents copies over it AFTER having used it once, the more recent versions WORK. BUT if I reboot, they stop working.
I jump to the conclusion, that the working version calls for some function that stays resident in memory and still works for the other versions who dont call for it anymore, because they find it already in memory, but if I reboot, they don't find it anymore and load a not working version instead.
That's all I can say

## Steps to reproduce
 1.
 2.

## Notes
Here on A1XE with AOS4 update 4

**Comment by tboeckel** [comment]
**Originally on 2012-08-16 09:01:42 +0200**

___
We need an "@all,all" debug log produced with the debug version of YAM. Please refer to the [FAQ](http://yam.ch/wiki/FAQ/Debugging#BasicsaboutYAMsdebuggingfacilities) for details.

Please call "setenv yamdebug @all,all,file:ram:t/yam.log.txt" before running the debug version of YAM. As the "@all" log will become quite large it may be a good idea to use a different path than "ram:t/yam.log.txt" for the log file.

In case the compressed log file should to too large to be attached to this ticket we don't mind if you send to log to us via private EMail.

**Comment by jens-maus** [comment]
**Originally by _paraphonista@gmail.com_ on 2012-08-16 09:21:59 +0200**

___
**Attachment added:** [`logfile.txt`](https://yam.ch/attachments/346/logfile.txt) (250.1 KiB)

**Comment by tboeckel** [comment]
**Originally on 2012-08-16 10:18:05 +0200**

___
Thanks for the log. It seems YAM is misinterpreting the layout string in the wrong way which then in turn causes the freeze. This should be fixed in the next nightly build. Please check again with that version.

**Comment by tboeckel** [comment]
**Originally on 2012-08-16 10:49:45 +0200**

___
In (493c2ca):
 * YAM_UT.c: slightly changed the recognition of old and new layout strings and added some debug output. This closes #346.
