### ISSUE TITLE
Crash after deleting an incoming message

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#347]
**Originally by _JDuch@fulladsl.be_ on 2012-09-24 10:33:51 +0200**

___
## Summary
Domtimes after a first delete of a message, somtimes after the 2nd or 3d delete in the incoming folder, YAM will crash

## Steps to reproduce
 1. Delete an incoming message
 2. If not a crashe repeat 1

## Notes

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-24 10:35:02 +0200**

___
**Attachment added:** [`Crashlog_YAM.debug_2012-09-24_10-28-52.txt`](https://yam.ch/attachments/347/Crashlog_YAM.debug_2012-09-24_10-28-52.txt) (28.3 KiB)
Crash after a first delete

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-24 10:35:50 +0200**

___
**Attachment added:** [`Crashlog_YAM.debug_2012-09-24_10-23-40.txt`](https://yam.ch/attachments/347/Crashlog_YAM.debug_2012-09-24_10-23-40.txt) (30.7 KiB)
crash after previous succesfull deletes

**Comment by jens-maus** [comment]
**Originally on 2012-09-25 21:57:33 +0200**

___
After shortly having looked at the crashlogs you attached I think the problem might be in the HTML conversion routines to display HTML mails as plain text. However, to further investigate could you please provide the raw mail file of the HTML mail that is causing these crashes? That would definitely help.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-26 20:27:37 +0200**

___
Replying to damato:
> After shortly having looked at the crashlogs you attached I think the problem might be in the HTML conversion routines to display HTML mails as plain text. However, to further investigate could you please provide the raw mail file of the HTML mail that is causing these crashes? That would definitely help.

I do not see how i can attach the mail file to this reply.

As after a delete the file is in the "trash" folder and this is emptied when i restart Yam, the easiest way for me is to select 'continue' after  i did write a crashlog with Grimreaper and to forward the 'deleted message'  I did this, but did send the message to Thore,  also with the raw fmessage attached. Can you contact me by mail ?

**Comment by tboeckel** [comment]
**Originally on 2012-09-26 20:48:07 +0200**

___
**Attachment added:** [`QVZaAgACXTo=.001,R`](https://yam.ch/attachments/347/QVZaAgACXTo=.001,R) (12.8 KiB)
Crashing mail as sent by JosDuchIt

**Comment by tboeckel** [comment]
**Originally on 2012-09-26 20:48:51 +0200**

___
**Attachment added:** [`Crashlog_YAM.debug_2012-09-26_08-14-16.txt`](https://yam.ch/attachments/347/Crashlog_YAM.debug_2012-09-26_08-14-16.txt) (29.4 KiB)
Crashlog for crashing mail

**Comment by tboeckel** [comment]
**Originally on 2012-09-26 20:51:08 +0200**

___
Replying to JosDuchIt:

> As after a delete the file is in the "trash" folder and this is emptied when i restart Yam, the easiest way for me is to select 'continue' after  i did write a crashlog with Grimreaper and to forward the 'deleted message'  I did this, but did send the message to Thore,  also with the raw fmessage attached.

I just attached the mail and the crashlog.

And the solution to your "trash" problem is very simple: don't empty the trash folder when starting YAM. Additionally the mail you sent to me is still in your "Sent" folder. You see, there are lots of ways to not loose such a mail.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-27 09:19:32 +0200**

___
Replying to damato:
@Thore 
Thanks for uploading my 'crash' message
Attach files here: 
OK i discoverd how you can attach a file to a message here. I did not see that in fact all files uploaded are linked together in a common "attachments" view, with an upload (attach file) button.
My impression was that, after pressing the "attachments" button below the message,  i just got some upwards shift of the ticket page, while i was expecting a file requester to appear.
Looking bettter, i do see the little up arrow now, next to it.  

Trash problem: the doc states:
Trash
     This box contains messages marked for deletion.  Normally messages
     are not actually deleted from the hard disk until you quit YAM.
     This allows you to recover messages deleted earlier in the session.

I don't see a settings to overrule this. Is there? If not, might be a suggestion

**Comment by jens-maus** [comment]
**Originally on 2012-09-27 09:39:55 +0200**

___
Replying to JosDuchIt:
 
> Trash problem: the doc states:
> Trash
>      This box contains messages marked for deletion.  Normally messages
>      are not actually deleted from the hard disk until you quit YAM.
>      This allows you to recover messages deleted earlier in the session.
> 
> I don't see a settings to overrule this. Is there? If not, might be a suggestion 

There should be some checkboxes in the "Start/Quit" configuration pane in yam where you can then define at which step you want yam to automatically empty your trash. if you unselect both checkboxes yam should never automatically cleanup your trash , thus you have to manually clean it.

**Comment by jens-maus** [comment]
**Originally on 2012-09-30 15:08:47 +0200**

___
According to the crashlog this is essentially the same like ticket #348. Thus I close this ticket as being a duplicate of that. So please continue to discuss this issue there instead.
