### ISSUE TITLE
Systematic Crash when trying to a message

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#348]
**Originally by _JDuch@fulladsl.be_ on 2012-09-28 14:04:46 +0200**

___
## Summary
- The message attached  could not be opened without producing a crash - Crashlog attached
- While this message was the last one in the incoming drawer,Yam crashed when it was loaaded. This happened after a warm & after a cold reboot - cashlog attached
## Steps to reproduce
 1.
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-28 14:08:49 +0200**

___
**Attachment added:** [`Crashlog_YAM.debug_2012-09-28_13-46-16.txt`](https://yam.ch/attachments/348/Crashlog_YAM.debug_2012-09-28_13-46-16.txt) (28.7 KiB)

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-28 14:09:09 +0200**

___
**Attachment added:** [`Crashlog_YAM.debug_2012-09-28_13-50-10.txt`](https://yam.ch/attachments/348/Crashlog_YAM.debug_2012-09-28_13-50-10.txt) (27.6 KiB)

**Comment by jens-maus** [comment]
**Originally on 2012-09-28 14:28:31 +0200**

___
Hi, first of all please attach the raw mail file also to this ticket. Second, you are stating that you are using YAM 2.7. Would you please be so kind in trying to use one of the latest 2.8-dev nightly build versions to see if the problem still exists?

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-28 18:32:28 +0200**

___
**Attachment added:** [`QVlaPgAMHC8=.001,R`](https://yam.ch/attachments/348/QVlaPgAMHC8=.001,R) (9.3 KiB)

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-28 18:39:19 +0200**

___
I was using Yam-debug 2.8dev 9/20/2012 for the report & attachments
You may be mislead by the fact that i use this debug version or alternatively the 2.7 normal version from the same drawer named YAM_2.7

(In fact I don't have the problem with the 2.7 version)

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-28 19:17:19 +0200**

___
**Attachment added:** [`Crashlog_YAM.debug_2012-09-28_19-16-38.txt`](https://yam.ch/attachments/348/Crashlog_YAM.debug_2012-09-28_19-16-38.txt) (28.6 KiB)

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-28 19:17:52 +0200**

___
**Attachment added:** [`QVmjCQANJf0=.001,R`](https://yam.ch/attachments/348/QVmjCQANJf0=.001,R) (7.2 KiB)

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-28 19:19:54 +0200**

___
I added a crashlog & the raw  message of a new one crashing too when opened

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-28 19:31:25 +0200**

___
Downloaded the latest 22 / 09 debug version 
The crash is still there with the same (last message) 
I guess you don't need a new crashlog?

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-29 10:05:15 +0200**

___
**Attachment added:** [`Crashlog_YAM.debug_2012-09-29_09-45-13.txt`](https://yam.ch/attachments/348/Crashlog_YAM.debug_2012-09-29_09-45-13.txt) (28.7 KiB)
Crashlog when opening  next Message

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-29 10:06:03 +0200**

___
**Attachment added:** [`QVp1ogANZfw=.001,R`](https://yam.ch/attachments/348/QVp1ogANZfw=.001,R) (3.2 KiB)
Meesage that crashes when opening

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-09-29 10:08:25 +0200**

___
The last message & its crashlog are for YAM-debug 2.8dev 22/09/12

**Comment by jens-maus** [comment]
**Originally on 2012-09-30 15:06:54 +0200**

___
can you please download the version from Augut, 29th and try to reproduce the problem with that version please?

The download link to this older version is:

http://nightly.yam.ch/2012-08-29-dev/YAM28dev-AmigaOS4.lha

then please simply report of this version crashes also or not?

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-10-01 11:37:00 +0200**

___
I can not run that version: i am told that it is obsolete and have to use a newer version.
What should i do?

**Comment by jens-maus** [comment]
**Originally on 2012-10-07 16:24:20 +0200**

___
I just tried today to reproduce the crash with the mails you have attached to this ticket. However, I wasn't able to reproduce it and here all the three emails display nicely in the texteditor and without showing any crash. Can you please try to reproduce the problem with the latest nightly build. In addition, please give some more information about the system your are using when you try to reproduce the problem. Furthermore it would help if you could also try to reproduce the problem with the debug version of the nightly build.

So sorry, I can't reproduce the problem , thus we need some more help from you to understand the root of your crashes.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-10-07 20:26:39 +0200**

___
I downloaded & installed the latest debug version. 
Please note that all my reports were done using a debug-version, and if not otherwise instructed i'll continue tot do this.

My system is a Sam 440ep with OS4.1 Updt 5

The problem is still there and ocurs when i do set the settings /Read/ convert html e-mails to plain text.
If i don't use that i have no crash but the html tags are all visible

**Comment by jens-maus** [comment]
**Originally on 2012-10-07 20:35:16 +0200**

___
Thats strange. He i tried the same but there are no crashes. Thore, can you reproduce this problem? 
Jos, are you also uptodate with all the mcc classes? Furthrmore it would perhaps also help if you could attach your config file to this ticket. However, please make sure to strip private information first (e.g. Passwords)

**Comment by tboeckel** [comment]
**Originally on 2012-10-08 07:35:16 +0200**

___
Replying to damato:
> Thore, can you reproduce this problem? 

Unfortunately not, but I tried with the AmigaOS3 build only. Maybe this crash is due to the recent change to GCC 4.7.1? The AmigaOS3 build is done with the ancient GCC 2.95.3 and for AmigaOS4 I am still using GCC 4.2.4.

**Comment by jens-maus** [comment]
**Originally on 2012-10-08 08:09:03 +0200**

___
Replying to thboeckel:
> Replying to damato:
> > Thore, can you reproduce this problem? 
> 
> Unfortunately not, but I tried with the AmigaOS3 build only. Maybe this crash is due to the recent change to GCC 4.7.1? The AmigaOS3 build is done with the ancient GCC 2.95.3 and for AmigaOS4 I am still using GCC 4.2.4.

Well, I also thought about that but as I said, I can't reproduce the problem here on my AOne. Also the GCC 4.7.1 compiled version does not crash. But perhaps it would be greate if you could compile a version with the older GCC 4.2.4 and send it to Joseph so that he could test this version instead.

**Comment by tboeckel** [comment]
**Originally on 2012-10-08 08:27:12 +0200**

___
**Attachment added:** [`YAM_os4_gcc424.lha`](https://yam.ch/attachments/348/YAM_os4_gcc424.lha) (875.3 KiB)
YAM (AmigaOS4) built with gcc 4.2.4

**Comment by tboeckel** [comment]
**Originally on 2012-10-08 08:28:26 +0200**

___
Replying to damato:

> Well, I also thought about that but as I said, I can't reproduce the problem here on my AOne. Also the GCC 4.7.1 compiled version does not crash. But perhaps it would be greate if you could compile a version with the older GCC 4.2.4 and send it to Joseph so that he could test this version instead.

Done. Joseph, please try the gcc 4.2.4 build and tell us if that is crashing as well or not.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-10-08 10:02:29 +0200**

___
I tried the ggcc4.2.4 build and it does not crash when the settings is put to "convert to plain text" 
When the settings is not set i see the same message with all the html tags

**Comment by tboeckel** [comment]
**Originally on 2012-10-08 19:27:10 +0200**

___
Replying to JosDuchIt:
> I tried the ggcc4.2.4 build and it does not crash when the settings is put to "convert to plain text" 
> When the settings is not set i see the same message with all the html tags

We have a compiler issue then here which obviously affects the 440 CPU only, but not the G4 CPU in Jens' AmigaOne.

Jens, what suits you best? Reverting to gcc 4.5.x or fixing this bug in gcc 4.7.x?

**Comment by jens-maus** [comment]
**Originally on 2012-10-08 19:31:40 +0200**

___
Replying to thboeckel:
> Replying to JosDuchIt:
> > I tried the ggcc4.2.4 build and it does not crash when the settings is put to "convert to plain text" 
> > When the settings is not set i see the same message with all the html tags
> 
> We have a compiler issue then here which obviously affects the 440 CPU only, but not the G4 CPU in Jens' AmigaOne.
> 
> Jens, what suits you best? Reverting to gcc 4.5.x or fixing this bug in gcc 4.7.x?

Well, one case is no case I would say. So lets first find other people having the same problem. So we should contact other people with a SAM and AOne and see if they could reproduce the problem or not. Then we should investigate where exactly the crash happens and find out if tuning the compiler optimization settings might remove the problem. I doubt that this is a bug in gcc 4.7.1 but perhaps a bug in the code produced by flex which only shows up when using gcc 4.7.1. gcc itself is so widely used that I really doubt that it is buggy without other people (non-amiga users) noticing the problem.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-10-09 10:44:08 +0200**

___
>So lets first find other people having the same problem. So we should contact other people with a SAM and AOne and see if they could reproduce the problem or not. 

use www.Amigans.net forum maybe?

**Comment by jens-maus** [comment]
**Originally on 2012-10-09 19:25:51 +0200**

___
I'll add padrino to this ticket as he should have a SAM as well and may help us in trying to reproduce the crash you are reporting here. Padrino, can you please investigate in trying the latest nightly build together with the mails JosDuchIt attached?

**Comment by tboeckel** [comment]
**Originally on 2012-10-09 20:11:52 +0200**

___
Replying to damato:
> I doubt that this is a bug in gcc 4.7.1 but perhaps a bug in the code produced by flex which only shows up when using gcc 4.7.1. gcc itself is so widely used that I really doubt that it is buggy without other people (non-amiga users) noticing the problem.

I just successfully imported the 3 attached mails using the latest official nightly build (gcc 4.7.1) on my MicroA1 (750FX CPU) and can also successfully view these mails with HTML to text conversion activated. So this more and more smells like an issue with the 440 (maybe 460) CPUs only.

**Comment by tboeckel** [comment]
**Originally on 2012-10-10 11:40:11 +0200**

___
I just had a second look at the provided crash logs and it seems the crash is quite simple to avoid, even if it does not happen on every system. The log points to this assembler mnemonic "lwz r9,0(r9)" with r9 having the value 0xfffffffc. Thus it is obvious that this crashes, because this is an invalid address.

The HTML conversion function calls the causing function yy_top_state() just to avoid compiler warnings about an unused function. But that function accesses a pointer without verifying that this pointer is really valid.

I will build a new version which will avoid this call without causing further warnings.

**Comment by tboeckel** [comment]
**Originally on 2012-10-10 11:49:41 +0200**

___
Joseph, please try the (hopefully) fixed version. Although I cannot verify it myself I am pretty sure this crash is fixed now.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-10-10 14:23:01 +0200**

___
**Attachment added:** [`Crashlog_yam.OS4_2012-10-10_14-21-34.txt`](https://yam.ch/attachments/348/Crashlog_yam.OS4_2012-10-10_14-21-34.txt) (24.3 KiB)
crash when opening (initial window appears)

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-10-10 14:24:31 +0200**

___
I tried out your attached version.
Alas it cashes when loading: the initial warning window shows up, but a crash appears as soon as i  hit the ok button
Crashlog added

**Comment by tboeckel** [comment]
**Originally on 2012-10-10 14:36:13 +0200**

___
**Attachment added:** [`YAM_os4_gcc471_20121010.lha`](https://yam.ch/attachments/348/YAM_os4_gcc471_20121010.lha) (899.4 KiB)
yet another build done with gcc 4.7.1

**Comment by tboeckel** [comment]
**Originally on 2012-10-10 14:37:20 +0200**

___
Replying to JosDuchIt:
> I tried out your attached version.
> Alas it cashes when loading: the initial warning window shows up, but a crash appears as soon as i  hit the ok button
> Crashlog added

Something went wrong there during the build. Please try again with the most recent version attach. I just rebuilt YAM from scratch and replaced the previous versions.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2012-10-10 15:26:10 +0200**

___
Works OK here.


Thanks & congratulations

**Comment by tboeckel** [comment]
**Originally on 2012-10-10 15:36:02 +0200**

___
Replying to JosDuchIt:
> Works OK here.


That's great to hear! Closing this ticket then.
