### ISSUE TITLE
Search without searching in pgp mails

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#35]
**Originally by _zuse@users.sourceforge.net_ on 2010-03-03 22:34:41 +0100**

___
i am searching often in all folders so yam is busy long time. But this search cannot run unattended because YAM asks for my pgp key, while trying to search in the encrypted mails.

Since i know that the wanted mail is NOT pgp encrypted, the requester is not required in this case.

a checkmark on the search page "do NOT search in encrypted mails" would be very nice.

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 08:13:05 +0200**

___
In (bfe47ad):
 * YAM_FI.c, YAM_COs.c, mui/SearchControlGroup.c: PGP encrypted mails can now be excluded from a search to let in run unattended without the need to enter a password. This closes #35.

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 11:43:23 +0200**

___
**Release Note:**
PGP encrypted mails can now be excluded from a search to let in run unattended without the need to enter a password.
