### ISSUE TITLE
Search Messages via ID and when found show them in GUI

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#351]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-10-10 05:43:30 +0200**

___
## Enhancement recommendation

An arexx script to be able to search for e-mails in dirs via the message ID each mail has and show the mail in the GUI. This permits a sort of connection with an external program, like a data base, and link e-mails to a project.

**Comment by tboeckel** [comment]
**Originally on 2012-10-16 21:23:05 +0200**

___
In (b39702b):
 * YAM_MAf.c, Rexx.c, rexx/findmail.c, rexx/setmail.c: added new ARexx command FINDMAIL to find a mail in all folders given a MessageID as returned by the MAILINFO command. Additionally SETMAIL now accepts a MessageID to set the active mail. This closes #351.
