### ISSUE TITLE
grim reaper with nightly when going to the next unread message in another folder

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#352]
**Originally by _Michael.Merkel@gmx.net_ on 2012-10-26 20:09:05 +0200**

___
yam2.8dev 26.10.2012 (also happened with the version before and maybe also with the one before).

i read mails and press "shift right" to jump to the next unread. the folder has no more unread and the popup for the next folder should come up. instead the grim reaper is coming. see attachment. i can "go on" and it looks nice then.

but after quitting yam i usually get a lock here. means no keyboard/mous wokring any more - cpu clock still running.

hardware: x1000
current beta OS4 installed.

any thing else needed?

thanks and regards
michael

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2012-10-26 20:09:30 +0200**

___
**Attachment added:** [`Crashlog_YAM_2012-10-26_19-58-56.txt`](https://yam.ch/attachments/352/Crashlog_YAM_2012-10-26_19-58-56.txt) (38.9 KiB)
YAM Crashlog

**Comment by tboeckel** [comment]
**Originally on 2012-10-28 19:03:56 +0100**

___
I am still searching for the true cause, but so far I can only tell that the recent canged busy stuff is responsible for the issue.

**Comment by tboeckel** [comment]
**Originally on 2012-10-28 20:23:38 +0100**

___
In (78d9d20):
 * InfoBar.c: don't use MUIM_Application_InputBuffered and a timed update unless it is absolutely necessary (i.e. for abortable progress bars). This closes #352.
