### ISSUE TITLE
connections are not done.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#354]
**Originally by _fernandez_jesus@yahoo.fr_ on 2012-11-18 19:13:56 +0100**

___
Hello,
the last version of YAM which worked for me is the nightly build of october, 18.
Since then, I have the same problem. Here it is.
When I launch YAM, the main gui is created and the transfer window appears.
But this window indicates "Initialising transfer" and then yam doesn't seem to do something. The hourglass icon pointer appears and the cpu is at 100%.
Yam can't be closed and I have to reboot. Sometimes, the system hangs.

My system is OS4.1.4 and I have a sam-flex 800

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2012-11-18 15:57:36 +0100**

___
**Attachment added:** [`yamdebug.txt`](https://yam.ch/attachments/354/yamdebug.txt) (36.9 KiB)
Yam debug with startup, net and gui options

**Comment by tboeckel** [comment]
**Originally on 2012-11-18 20:05:06 +0100**

___
Does this happen for all connections or just for a specific one? From the log I can see that you are trying to download mail from 3 servers. What really puzzles me is the fact that the SSL_shutdown() command fails completely, which should never happen.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2012-11-19 06:04:38 +0100**

___
Replying to thboeckel:
> Does this happen for all connections or just for a specific one? From the log I can see that you are trying to download mail from 3 servers. What really puzzles me is the fact that the SSL_shutdown() command fails completely, which should never happen.

Well,
Yes I am trying to download from three servers. In the transfer window, I only see two attempts of connection. The third (sfr.fr) is not present and I don't know if it works because I have generally no emails from this account.
Do you need an another debug output ? All I can write is something in your code relative to network has to be modified since the nightly build of 18/10/12. I can't tell you more as I could not test anymore this version.

**Comment by tboeckel** [comment]
**Originally on 2012-11-19 06:29:10 +0100**

___
Replying to anonymous:

First of all, please log in before you reply. This makes it a lot easier and we don't have to talk to a bunch of different people each of which are named "anonymous".

> Yes I am trying to download from three servers. In the transfer window, I only see two attempts of connection. The third (sfr.fr) is not present and I don't know if it works because I have generally no emails from this account.

Then please try to deactivate all accounts except one to find out if the same issue arises for each account or for specific ones only. At least the download from pop.mail.yahoo.fr seems to be working, as the log indicates that YAM was able to get the list of pending mails and starts to download the first mail.

> Do you need an another debug output ? All I can write is something in your code relative to network has to be modified since the nightly build of 18/10/12. I can't tell you more as I could not test anymore this version.

Exactly that's the problem: no network related code has been touched since then. I admit I did a lot of changes, but all these were either GUI or PGP related.

**Comment by jens-maus** [comment]
**Originally by _Jesus Fernandez <fernandez_jesus@yahoo.fr>_ on 2012-11-19 22:12:38 +0100**

___
You are right. I will always put my email as I couldn't register due to anti (ro)bot question.
I answered OS4, Amiga OS4. They told me that the answers are bad.

I only tried one server each time (Yahoo and hotmail). Now, I retrieved all the emails but after that, I had the same problem as before, i.e. cpu at 100% and yam hangs.

Well, I read the output and it seems that the problem is in rexx.c.

I give you a lha with all the debug output. In the order of the tests,
yamdebug-one server-mails ok : All the mails from yahoo are downloaded.
yamdebug-one server-just after : Just after the previous one.
yamdebug-yahoo server - all options : I used all option.
yamdebug-hotmail server - all options : the same as before with an another server.

**Comment by jens-maus** [comment]
**Originally by _Jesus Fernandez <fernandez_jesus@yahoo.fr>_ on 2012-11-19 22:12:50 +0100**

___
I tried a few to times to upload the lha archive butI had an error from the trac system (spam error).
I copy there the end of the debug file :

00:D:   Rexx.c:312:executing ARexx script: 'YAM:Rexx/HRdownload.rx'
00:D:   Rexx.c:324:executedARexx script: 'YAM:Rexx/HRdownload.rx' => 4c1cb3a0
00:C:  YAM_MA.c:3364:C->RX[num].WaitTerm = 1, 0x0001
00:D:   Busy.c:60:AllocSysObjectTags(6): 0x4c1cb220
00:D:   Rexx.c:726:AllocVecPooled(31): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPBUSY "HTMLRead Downloader"
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8078 ""HTMLRead Downloader"
"
00:C:    Rexx.c:494:cmd = 1409191296, 0x53fe8d80
00:D:   Rexx.c:772:RXIF_INIT 'APPBUSY'
00:D:    appbusy.c:55:AllocVecPooled(4): 0x535c80a0
00:D:   Rexx.c:777:AllocVecPooled(19): 0x535c80b8
00:D:   Rexx.c:800:using template 'TEXT' to parse string '"HTMLRead Downloader"
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPBUSY'
00:D:     Busy.c:60:AllocSysObjectTags(6): 0x4c1cb4a0
00:D:   Rexx.c:906:free of 0x535c80b8 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPBUSY'
00:D:    appbusy.c:81:free of 0x535c80a0 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(11): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPNOBUSY
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPNOBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8079 "
"
00:C:    Rexx.c:494:cmd = 1409191312, 0x53fe8d90
00:D:   Rexx.c:772:RXIF_INIT 'APPNOBUSY'
00:D:    appnobusy.c:55:AllocVecPooled(4): 0x535c8090
00:D:   Rexx.c:777:AllocVecPooled(15): 0x535c80a8
00:D:   Rexx.c:800:using template '' to parse string '
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPNOBUSY'
00:D:     Busy.c:180:free of 0x4c1cb4a0 suceeded
00:D:   Rexx.c:906:free of 0x535c80a8 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPNOBUSY'
00:D:    appnobusy.c:77:free of 0x535c8090 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(66): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPBUSY "Try to load: ...r.com/images/LJ/careerbuilderV2_lj.gif"
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8078 ""Try to load: ...r.com/images/LJ/careerbuilderV2_lj.gif"
"
00:C:    Rexx.c:494:cmd = 1409191296, 0x53fe8d80
00:D:   Rexx.c:772:RXIF_INIT 'APPBUSY'
00:D:    appbusy.c:55:AllocVecPooled(4): 0x535c80c8
00:D:   Rexx.c:777:AllocVecPooled(19): 0x535c80e0
00:D:   Rexx.c:800:using template 'TEXT' to parse string '"Try to load: ...r.com/images/LJ/careerbuilderV2_lj.gif"
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPBUSY'
00:D:     Busy.c:60:AllocSysObjectTags(6): 0x4c1cb4a0
00:D:   Rexx.c:906:free of 0x535c80e0 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPBUSY'
00:D:    appbusy.c:81:free of 0x535c80c8 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(11): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPNOBUSY
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPNOBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8079 "
"
00:C:    Rexx.c:494:cmd = 1409191312, 0x53fe8d90
00:D:   Rexx.c:772:RXIF_INIT 'APPNOBUSY'
00:D:    appnobusy.c:55:AllocVecPooled(4): 0x535c8090
00:D:   Rexx.c:777:AllocVecPooled(15): 0x535c80a8
00:D:   Rexx.c:800:using template '' to parse string '
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPNOBUSY'
00:D:     Busy.c:180:free of 0x4c1cb4a0 suceeded
00:D:   Rexx.c:906:free of 0x535c80a8 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPNOBUSY'
00:D:    appnobusy.c:77:free of 0x535c8090 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(66): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPBUSY "Try to load: ...r.com/images/LJ/careerbuilderV2_lj.gif"
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8078 ""Try to load: ...r.com/images/LJ/careerbuilderV2_lj.gif"
"
00:C:    Rexx.c:494:cmd = 1409191296, 0x53fe8d80
00:D:   Rexx.c:772:RXIF_INIT 'APPBUSY'
00:D:    appbusy.c:55:AllocVecPooled(4): 0x535c80c8
00:D:   Rexx.c:777:AllocVecPooled(19): 0x535c80e0
00:D:   Rexx.c:800:using template 'TEXT' to parse string '"Try to load: ...r.com/images/LJ/careerbuilderV2_lj.gif"
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPBUSY'
00:D:     Busy.c:60:AllocSysObjectTags(6): 0x4c1cb4a0
00:D:   Rexx.c:906:free of 0x535c80e0 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPBUSY'
00:D:    appbusy.c:81:free of 0x535c80c8 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(11): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPNOBUSY
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPNOBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8079 "
"
00:C:    Rexx.c:494:cmd = 1409191312, 0x53fe8d90
00:D:   Rexx.c:772:RXIF_INIT 'APPNOBUSY'
00:D:    appnobusy.c:55:AllocVecPooled(4): 0x535c8090
00:D:   Rexx.c:777:AllocVecPooled(15): 0x535c80a8
00:D:   Rexx.c:800:using template '' to parse string '
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPNOBUSY'
00:D:     Busy.c:180:free of 0x4c1cb4a0 suceeded
00:D:   Rexx.c:906:free of 0x535c80a8 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPNOBUSY'
00:D:    appnobusy.c:77:free of 0x535c8090 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(66): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPBUSY "Try to load: ...coup.net/Images/Design/logo_footer.png"
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8078 ""Try to load: ...coup.net/Images/Design/logo_footer.png"
"
00:C:    Rexx.c:494:cmd = 1409191296, 0x53fe8d80
00:D:   Rexx.c:772:RXIF_INIT 'APPBUSY'
00:D:    appbusy.c:55:AllocVecPooled(4): 0x535c80c8
00:D:   Rexx.c:777:AllocVecPooled(19): 0x535c80e0
00:D:   Rexx.c:800:using template 'TEXT' to parse string '"Try to load: ...coup.net/Images/Design/logo_footer.png"
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPBUSY'
00:D:     Busy.c:60:AllocSysObjectTags(6): 0x4c1cb4a0
00:D:   Rexx.c:906:free of 0x535c80e0 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPBUSY'
00:D:    appbusy.c:81:free of 0x535c80c8 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(11): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPNOBUSY
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPNOBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8079 "
"
00:C:    Rexx.c:494:cmd = 1409191312, 0x53fe8d90
00:D:   Rexx.c:772:RXIF_INIT 'APPNOBUSY'
00:D:    appnobusy.c:55:AllocVecPooled(4): 0x535c8090
00:D:   Rexx.c:777:AllocVecPooled(15): 0x535c80a8
00:D:   Rexx.c:800:using template '' to parse string '
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPNOBUSY'
00:D:     Busy.c:180:free of 0x4c1cb4a0 suceeded
00:D:   Rexx.c:906:free of 0x535c80a8 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPNOBUSY'
00:D:    appnobusy.c:77:free of 0x535c8090 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(66): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPBUSY "Try to load: ...coup.net/Images/Design/logo_footer.png"
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8078 ""Try to load: ...coup.net/Images/Design/logo_footer.png"
"
00:C:    Rexx.c:494:cmd = 1409191296, 0x53fe8d80
00:D:   Rexx.c:772:RXIF_INIT 'APPBUSY'
00:D:    appbusy.c:55:AllocVecPooled(4): 0x535c80c8
00:D:   Rexx.c:777:AllocVecPooled(19): 0x535c80e0
00:D:   Rexx.c:800:using template 'TEXT' to parse string '"Try to load: ...coup.net/Images/Design/logo_footer.png"
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPBUSY'
00:D:     Busy.c:60:AllocSysObjectTags(6): 0x4c1cb4a0
00:D:   Rexx.c:906:free of 0x535c80e0 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPBUSY'
00:D:    appbusy.c:81:free of 0x535c80c8 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(11): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPNOBUSY
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPNOBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8079 "
"
00:C:    Rexx.c:494:cmd = 1409191312, 0x53fe8d90
00:D:   Rexx.c:772:RXIF_INIT 'APPNOBUSY'
00:D:    appnobusy.c:55:AllocVecPooled(4): 0x535c8090
00:D:   Rexx.c:777:AllocVecPooled(15): 0x535c80a8
00:D:   Rexx.c:800:using template '' to parse string '
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPNOBUSY'
00:D:     Busy.c:180:free of 0x4c1cb4a0 suceeded
00:D:   Rexx.c:906:free of 0x535c80a8 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPNOBUSY'
00:D:    appnobusy.c:77:free of 0x535c8090 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(66): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPBUSY "Try to load: ...76&amp;-1&amp;%2F0EukWTlhaYO4WA0FOsqBQ"
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8078 ""Try to load: ...76&amp;-1&amp;%2F0EukWTlhaYO4WA0FOsqBQ"
"
00:C:    Rexx.c:494:cmd = 1409191296, 0x53fe8d80
00:D:   Rexx.c:772:RXIF_INIT 'APPBUSY'
00:D:    appbusy.c:55:AllocVecPooled(4): 0x535c80c8
00:D:   Rexx.c:777:AllocVecPooled(19): 0x535c80e0
00:D:   Rexx.c:800:using template 'TEXT' to parse string '"Try to load: ...76&amp;-1&amp;%2F0EukWTlhaYO4WA0FOsqBQ"
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPBUSY'
00:D:     Busy.c:60:AllocSysObjectTags(6): 0x4c1cb4a0
00:D:   Rexx.c:906:free of 0x535c80e0 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPBUSY'
00:D:    appbusy.c:81:free of 0x535c80c8 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(11): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPNOBUSY
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPNOBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8079 "
"
00:C:    Rexx.c:494:cmd = 1409191312, 0x53fe8d90
00:D:   Rexx.c:772:RXIF_INIT 'APPNOBUSY'
00:D:    appnobusy.c:55:AllocVecPooled(4): 0x535c8090
00:D:   Rexx.c:777:AllocVecPooled(15): 0x535c80a8
00:D:   Rexx.c:800:using template '' to parse string '
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPNOBUSY'
00:D:     Busy.c:180:free of 0x4c1cb4a0 suceeded
00:D:   Rexx.c:906:free of 0x535c80a8 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPNOBUSY'
00:D:    appnobusy.c:77:free of 0x535c8090 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(11): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPNOBUSY
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPNOBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8079 "
"
00:C:    Rexx.c:494:cmd = 1409191312, 0x53fe8d90
00:D:   Rexx.c:772:RXIF_INIT 'APPNOBUSY'
00:D:    appnobusy.c:55:AllocVecPooled(4): 0x535c8090
00:D:   Rexx.c:777:AllocVecPooled(15): 0x535c80a8
00:D:   Rexx.c:800:using template '' to parse string '
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPNOBUSY'
00:D:   Rexx.c:906:free of 0x535c80a8 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPNOBUSY'
00:D:    appnobusy.c:77:free of 0x535c8090 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(11): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPNOBUSY
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPNOBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8079 "
"
00:C:    Rexx.c:494:cmd = 1409191312, 0x53fe8d90
00:D:   Rexx.c:772:RXIF_INIT 'APPNOBUSY'
00:D:    appnobusy.c:55:AllocVecPooled(4): 0x535c8090
00:D:   Rexx.c:777:AllocVecPooled(15): 0x535c80a8
00:D:   Rexx.c:800:using template '' to parse string '
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPNOBUSY'
00:D:   Rexx.c:906:free of 0x535c80a8 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPNOBUSY'
00:D:    appnobusy.c:77:free of 0x535c8090 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(11): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPNOBUSY
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPNOBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8079 "
"
00:C:    Rexx.c:494:cmd = 1409191312, 0x53fe8d90
00:D:   Rexx.c:772:RXIF_INIT 'APPNOBUSY'
00:D:    appnobusy.c:55:AllocVecPooled(4): 0x535c8090
00:D:   Rexx.c:777:AllocVecPooled(15): 0x535c80a8
00:D:   Rexx.c:800:using template '' to parse string '
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPNOBUSY'
00:D:   Rexx.c:906:free of 0x535c80a8 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPNOBUSY'
00:D:    appnobusy.c:77:free of 0x535c8090 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(11): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPNOBUSY
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPNOBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8079 "
"
00:C:    Rexx.c:494:cmd = 1409191312, 0x53fe8d90
00:D:   Rexx.c:772:RXIF_INIT 'APPNOBUSY'
00:D:    appnobusy.c:55:AllocVecPooled(4): 0x535c8090
00:D:   Rexx.c:777:AllocVecPooled(15): 0x535c80a8
00:D:   Rexx.c:800:using template '' to parse string '
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPNOBUSY'
00:D:   Rexx.c:906:free of 0x535c80a8 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPNOBUSY'
00:D:    appnobusy.c:77:free of 0x535c8090 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(11): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPNOBUSY
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPNOBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8079 "
"
00:C:    Rexx.c:494:cmd = 1409191312, 0x53fe8d90
00:D:   Rexx.c:772:RXIF_INIT 'APPNOBUSY'
00:D:    appnobusy.c:55:AllocVecPooled(4): 0x535c8090
00:D:   Rexx.c:777:AllocVecPooled(15): 0x535c80a8
00:D:   Rexx.c:800:using template '' to parse string '
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPNOBUSY'
00:D:   Rexx.c:906:free of 0x535c80a8 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPNOBUSY'
00:D:    appnobusy.c:77:free of 0x535c8090 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(11): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPNOBUSY
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPNOBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8079 "
"
00:C:    Rexx.c:494:cmd = 1409191312, 0x53fe8d90
00:D:   Rexx.c:772:RXIF_INIT 'APPNOBUSY'
00:D:    appnobusy.c:55:AllocVecPooled(4): 0x535c8090
00:D:   Rexx.c:777:AllocVecPooled(15): 0x535c80a8
00:D:   Rexx.c:800:using template '' to parse string '
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPNOBUSY'
00:D:   Rexx.c:906:free of 0x535c80a8 suceeded
00:D:   Rexx.c:910:RXIF_FREE 'APPNOBUSY'
00:D:    appnobusy.c:77:free of 0x535c8090 suceeded
00:D:   Rexx.c:915:free of 0x535c8070 suceeded
00:D:   Rexx.c:726:AllocVecPooled(11): 0x535c8070
00:R:   Rexx.c:736:arg = 0x535c8070 "APPNOBUSY
"
00:R:    Rexx.c:488:com = 0x53fe73c4 "APPNOBUSY"
00:R:    Rexx.c:489:*arg = 0x535c8079 "
"
00:C:    Rexx.c:494:cmd = 1409191312, 0x53fe8d90
00:D:   Rexx.c:772:RXIF_INIT 'APPNOBUSY'
00:D:    appnobusy.c:55:AllocVecPooled(4): 0x535c8090
00:D:   Rexx.c:777:AllocVecPooled(15): 0x535c80a8
00:D:   Rexx.c:800:using template '' to parse string '
'
00:D:   Rexx.c:822:RXIF_ACTION 'APPNOBUSY'
00:D:   Rexx.c:906:free of 0x535c80a8 suceeded

**Comment by tboeckel** [comment]
**Originally on 2012-11-19 22:26:45 +0100**

___
Replying to <fernandez_jesus@…>:
> You are right. I will always put my email as I couldn't register due to anti (ro)bot question.
> I answered OS4, Amiga OS4. They told me that the answers are bad.

No problem here. I just created a test account for me without any problems. I used "AmigaOS" as answer.

Could please attach the HRdownload.rx script here? I suspect there is something wrong with YAM's recent handling of the APPBUSY and APPNOBUSY ARexx commands.

**Comment by jens-maus** [comment]
**Originally by _Jesus Fernandez <fernandez_jesus@yahoo.fr>_ on 2012-11-20 00:46:05 +0100**

___
**Attachment added:** [`HRdownload.rx`](https://yam.ch/attachments/354/HRdownload.rx) (18.5 KiB)

**Comment by tboeckel** [comment]
**Originally on 2012-11-20 19:53:22 +0100**

___
In (8e87024):
 * YAM.c, Busy.c, rexx/appbusy.c, rexx/appnobusy.c: splitted off a separate list for busy actions initiated by ARexx scripts. This is necessary to keep old scripts working, which cannot take into account that there can be other busy actions active now in parallel to the one initiated by the script. The separate list is only required to satisfy the needs of such scripts. This closes #354.

**Comment by tboeckel** [comment]
**Originally on 2012-11-20 19:56:52 +0100**

___
Just one additional comment. If I guessed right, then the loop waiting for APPNOBUSY to return 0 was the cause of this issue, because there was another busy action active and which could not terminate because YAM was waiting for the script to terminate.

Please reopen this ticket if the issue persists.

**Comment by jens-maus** [comment]
**Originally by _Jesus Fernandez <fernandez_jesus@yahoo.fr>_ on 2012-11-20 21:55:49 +0100**

___
The last version (20/11/12) didn't work.

**Comment by tboeckel** [comment]
**Originally on 2012-11-20 21:57:23 +0100**

___
Replying to <fernandez_jesus@…>:
> The last version (20/11/12) didn't work.

As usual, you will have to wait for the **next** nightly build, which will appear this night at 02:00 CET.
