### ISSUE TITLE
Add string gadget for subject to "no subject warning requester"

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#355]
**Originally by _mario@cattaneo.de_ on 2012-11-30 14:28:47 +0100**

___
Would be nice, if the requester telling you, that you forgot to enter a subject would have an empty (but active? ;)) string gadget, where you could enter a subject immediately and then send the mail wihtout having to go back to the edit window.

**Comment by tboeckel** [comment]
**Originally on 2012-12-01 14:04:41 +0100**

___
While this request might be quite sensible on the first sight I must say that I am against adding a string object to enter the subject. Let me explain why.

First of all the requester is modal (blocking all input on other windows) already. This is not very friendly for things like threading. Although this requester is usually terminated quite fast it prohibits handling background stuff as long as it it visible.

Second at one point someone will ask to include more options than just "ok" and "cancel", i.e. "send later". All these options are available in the write window already and it just takes you one mouse click/key press to close the requester and return to the write window. Here the subject string is made active already and you have the full range of options how to continue with the mail.

To make it short: no, this will not be implemented unless Jens contradicts me here.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-12-01 14:20:14 +0100**

___
Well, the requester does only show up if the user has actively set it to do so. So it is nothing where the user can say "I hate it", so it is ok that it blocks everything as the user expects help from it. :)

For the "more feature", well, the Topic of this requester is "Subject", so I think a Subject line would be "on topic" and the other addons are just off topic and don't belong in that requester, therefor I first doubt, someone will suggest it (ok, never say never ;)) and if then a rejection would be valid - at least more than rejecting the wish for a subject line. :)

I don't know how Thunderbird does it (not using Windows ;)), as you often take it as a inspiration. Isn't it there, too?
I know it from my providers web interface, so, to be honost, it is not my idea ;)

**Comment by tboeckel** [comment]
**Originally on 2012-12-01 14:25:57 +0100**

___
Replying to padrino:

> I don't know how Thunderbird does it (not using Windows ;)), as you often take it as a inspiration. Isn't it there, too?
> I know it from my providers web interface, so, to be honost, it is not my idea ;)

Thunderbird opens a requester telling you about the missing subject and offers "send without subject" and "don't send" as possible answers. Choosing "don't send" will return you to the write window with the subject line being the active object. Essentially there is no difference to YAM, just the wording is a bit different.

**Comment by tboeckel** [comment]
**Originally on 2012-12-01 18:05:50 +0100**

___
In (a335633):
 * mui/WriteWindow.c: in case no subject was entered when sending a mail the user will now gets presented a requester with a second chance to enter the subject. This closes #355.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-12-03 18:34:13 +0100**

___
Don't know why the tracker did not notify me on the status change.
Anyway, thanks for adding this.
