### ISSUE TITLE
Problem with email caching and adding new identity

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#356]
**Originally by _mario@cattaneo.de_ on 2012-11-30 14:46:49 +0100**

___
Over the time I had problems with YAM completing mail strings to stuff I never wanted but know I think I have one reproducable case to start with. :)

- Start writing a mail (ie, enter to:) to test@me.com
- Press "Hold"
- Start writing a mail to test@you.com
- Press "Hold"
- Go to prefs, add an identity
- type test@
- select test@me.com
- Use prefs
- Go back to prefs/identity
-> see the address is test@you.com instead of @me.com

I guess, this may have to do with the popup list actually not "using" the selected entry but leaving the "default view" maybe?

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-11-30 15:01:19 +0100**

___
Argh!

Bugtracker is stripping all emails?! :-(

mail addresses are (in order of appearances)

me.com
you.com
me.com
you.com

Hope you get what I mean...

**Comment by tboeckel** [comment]
**Originally on 2012-12-01 14:07:48 +0100**

___
Although I have no clue yet why this happens I can perfectly reproduce this issue.

**Comment by tboeckel** [comment]
**Originally on 2012-12-01 18:46:45 +0100**

___
Ok, found it. Unfortunately the bug is not located in YAM but in BetterString.mcc which handles queued notifications slightly wrong. The next release of BetterString.mcc will fix this.
