### ISSUE TITLE
Another email cache problem with misspelled, ie. longer adresses

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#357]
**Originally by _mario@cattaneo.de_ on 2012-11-30 14:57:56 +0100**

___
Let's say you have a friend at

a@test.de

but as you are German and tend to type too fast you write an email to

a@test.der

"Send" or "Hold" it to get the wrong adress into cache

Now try to fix the address field or try to send to the correct address.
You will have a hard time, cause no matter what you do, YAM will complete the address to the wrong (longer) one. Even if you try

a@test.de_ (where the "_" stand for an aditional space)

when pressing return YAM will place ".der" in the string.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-11-30 15:02:54 +0100**

___
Again stripped...

Missing is:

test.de
test.der
test.de

**Comment by tboeckel** [comment]
**Originally on 2012-12-01 14:10:45 +0100**

___
Yes, it is definitely impossible to remove that additional character. I really wonder why nobody noticed this in YAM 2.7 already.

**Comment by tboeckel** [comment]
**Originally on 2012-12-20 01:54:27 +0100**

___
In (2b716da):
 * mui/RecipientString.c: alias expansion will always add the " >> " markers before the possible expanded string and pressing the right cursor key will take the current recipient as it is and add a comma at the end. Furthermore the entered addresses will be resolved only if the address match window is currently open. This closes #357.
