### ISSUE TITLE
YAM just "auto completes" and jumps to text area

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#360]
**Originally by _mario@cattaneo.de_ on 2012-12-03 18:24:47 +0100**

___
I just have to have the crsr sitting in the to: field or in the subject one and after a while YAM will jump to the text area by itself.

In both cases the GUI debug output is the same, file attached.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-12-03 18:25:15 +0100**

___
**Attachment added:** [`sashimi.out`](https://yam.ch/attachments/360/sashimi.out) (0.7 KiB)

**Comment by tboeckel** [comment]
**Originally on 2012-12-03 19:42:59 +0100**

___
I just encountered this myself and it seems to happen when YAM autosaves the mail to the drafts folder. Does this match your observations?

**Comment by tboeckel** [comment]
**Originally on 2012-12-03 20:01:23 +0100**

___
Ok, I think I solved this faster than expected...

**Comment by tboeckel** [comment]
**Originally on 2012-12-03 20:02:13 +0100**

___
In (520ea98):
 * mui/WriteWindow.c: don't trigger any notifications when setting the write window's active page while saving the mail to the Drafts or Outgoing folder as this would change the active object. This is quite annoying if one was still typing the subject and YAM suddently activates the mail editor. This closes #360.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2012-12-04 16:20:17 +0100**

___
With the latest changement, the content of the Subject gets deleted. This could happen when YAM saves to the Drafts folder, but I'm not sure.

**Comment by tboeckel** [comment]
**Originally on 2012-12-04 19:56:11 +0100**

___
I anybody else still experiencing this second issue? Personally I cannot reproduce it.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-12-05 01:12:22 +0100**

___
I see no problem here :/
