### ISSUE TITLE
Bug when writing a new email with activated BCC and Reply-To fields

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#363]
**Originally by _zauraks@gmx.de_ on 2012-12-30 13:28:13 +0100**

___
AmigaOS 3.9, YAM 2.8 official release
WinUAE 2.5.1

Since YAM 2.8 the BCC and Reply-To fields are removed from options and now are available as drop-down menu. When choosing both fields, they are present on screen, but all fields are on weird positions (including TO and CC fields).

To reproduce the bug start YAM and write a new email with activated BCC and Reply-To fields (screenshot attached). The bug isn't present after deactivating BCC and Reply-To fields.

**Comment by jens-maus** [comment]
**Originally by _zauraks@gmx.de_ on 2012-12-30 21:44:52 +0100**

___
**Attachment added:** `YAM28_NewEmail.jpg` (74.2 KiB)
![YAM28_NewEmail.jpg](https://yam.ch/attachments/363/YAM28_NewEmail.jpg)
YAM 2.8 New Email screenshot

**Comment by jens-maus** [comment]
**Originally on 2012-12-30 23:51:35 +0100**

___
Thore? Can you reproduce this problem? This could be a MUI 3.8 thing, I guess.

**Comment by tboeckel** [comment]
**Originally on 2012-12-31 14:43:32 +0100**

___
In (28b8f1a):
 * mui/WriteWindow.c: sort dynamically added objects using MUIM_Group_Sort instead of MUIM_Group_MoveMember as this method seems to be broken in MUI 3.8. This closes #363.

**Comment by jens-maus** [comment]
**Originally on 2013-07-02 21:13:56 +0200**

___
**Release Note:**
fixed bug where hidden Cc, BCC or Reply-To string gadgets could have ended up at wrong positions when hiding/showing them dynamically in the write window.
