### ISSUE TITLE
english-british catalog wrong version

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#365]
**Originally by @chris-y on 2013-01-01 18:16:18 +0100**

___
The english-british catalog supplied with YAM 2.8 is the wrong version for YAM 2.8.

On launch, YAM proclaims:
YAM has found a translation catalog file in your native language to be available. However, it couldn't be activated as its version is incompatible to version 8 which YAM requires.

Please check if there is a version 8 of your native catalog available or remove the old one.

**Comment by tboeckel** [comment]
**Originally on 2013-01-01 19:14:08 +0100**

___
What does "version <directory of YAM>/catalogs/english-british/YAM.catalog" print out for you? The release archive contains the correct version 8.1 dated 23.12.2012.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2013-01-01 21:56:57 +0100**

___
version catalogs/english-british/YAM.catalog full
YAM.catalog 8.1 (23/12/2012)

-ahem* it seems to be working now, I think the old version must have been in memory when I updated and tried to start YAM 2.8 (all I've done since is rebooted).  I didn't think catalogs normally stayed in memory like libraries?

**Comment by jens-maus** [comment]
**Originally on 2013-01-01 22:03:09 +0100**

___
they do. So next time please always make sire to eüroduce your problem after having rebootet your system.
