### ISSUE TITLE
From: editable alternative to identities

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#366]
**Originally by _johnblock@storeshop.com_ on 2013-01-04 06:17:03 +0100**

___
Need to send off quick emails under lots of addresses eg for relatives or customers and also different contacts get their own email at my domain: thisshop@domain.com thatstore@domain.com electric@domain.com thisnewsletter@ thatnewsletter@ just checked there are 406 addresses on my main domain name!

Need an editable box please as well as identities!

**Comment by tboeckel** [comment]
**Originally on 2013-01-04 06:19:23 +0100**

___
This ticket describes the same feature as #321.

**Comment by jens-maus** [comment]
**Originally by _johnblock@storeshop.com_ on 2013-01-04 10:45:47 +0100**

___
No, this is a different feature.

A new identity is not wanted or needed every website ordered from or every time a ms blue, black, pink needs a quick email sent.

Identities will very quickly become bloated.

Just want a simple From: box as an alternative to using identities

**Comment by jens-maus** [comment]
**Originally on 2013-01-04 11:00:46 +0100**

___
This is exactly what ticket #321 is all aboout. Try to improve useness  of the identity feature. This includes keyboard use and eventually changibg some GUI elements to allow for directly entering the From: address. We are however not yet sure how we will adress that. But ticket #321 is definitly the right place.

BTW: please make sure to log in to yam.ch when contributing or otherwise your ticket is always flagged for moderation.

**Comment by jens-maus** [comment]
**Originally by _johnblock@storeshop.com_ on 2013-01-04 11:03:18 +0100**

___
Have a look at how [http://www.mail2web.com] handles from and reply to

**Comment by jens-maus** [comment]
**Originally on 2013-01-04 11:11:33 +0100**

___
please refrain from reopening a ticket. It is not up to you to do this. In addition adding commercials here is also not the best way of trying to convince us that a certain feature is important. Keep on bringing up logical arguments instead. Also kerp in mind that a freely editable From: is a potential for allowing to send SPAM/fake emails using foreign addresses. So we have to think differently than just allowing to have everything freely editable. Nevertheless, please continue your discussions on ticket #321.

**Comment by jens-maus** [comment]
**Originally by _johnblock@storeshop.com_ on 2013-01-04 11:23:22 +0100**

___
>adding commercials

The link is given so that people can see how another email solution handles the issue.

Showing something is easier and more inspirational than explaining.

>potential for allowing to send

It is up to the user how they send emails

**Comment by jens-maus** [comment]
**Originally on 2013-01-04 11:35:40 +0100**

___
Replying to johnblock:
> >adding commercials
> 
> The link is given so that people can see how another email solution handles the issue.
> 
> Showing something is easier and more inspirational than explaining.

Of course, but then be more specific than just a general link to a commercial webmailer. Showing screenshots also is fine. In addition, one has to register there. Not something I would call open.

> >potential for allowing to send
> 
> It is up to the user how they send emails

As long as this doesn't violate standards an common sense, of course. And it is up to the developers to ensure that. So better bribg up logical technical and constructive arguments instead of just pointibg somewhere tellung it works like that there.

**Comment by jens-maus** [comment]
**Originally by _johnblock@storeshop.com_ on 2013-01-04 12:00:40 +0100**

___
You don`t need to register. It logs onto your mailbox. http://www.mail2web.com/pda is also great on your phone.

Screenshot is a good idea.

Identities is a great addition when using most used addresses.

But also want back the flexibility in 2.7 and before as it fits into my work flow where, when not using main emails, identities is getting in the way.

I`m switching between 2.7 and 2.8

**Comment by jens-maus** [comment]
**Originally on 2013-01-04 13:40:33 +0100**

___
Replying to johnblock:

> You don`t need to register. It logs onto your mailbox. http://www.mail2web.com/pda is also great on your phone.

Oh, thanks for the info. However, I wouldn't really trust them kerping my passwords secure. Keep in mind that using that service you are giving them your passwords so they could in principle read all your mails.

> Identities is a great addition when using most used addresses.
> 
> But also want back the flexibility in 2.7 and before as it fits into my work flow where, when not using main emails, identities is getting in the way.
> 
> I`m switching between 2.7 and 2.8

As soon as we have found and implemented a solution you can of course use the nightly builds. However, this may take some time.

Rest assured, keep in mind that we are appreciating your comments.
