### ISSUE TITLE
yam crashes as soon as i click on new message

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#369]
**Originally by _Michael.Merkel@gmx.net_ on 2013-01-11 19:03:07 +0100**

___
hi.

using the latest nightly from 10.01.2013 (GCC 4.7.1, !r6506) on os4.1 (beta) on X1000.

crashes right after clicking on the "new" button in the toolbar for creating a new mail message.

crashlog is attached. i can skip the grim reaper and go on without problem.

thanks and regards...
michael

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2013-01-11 19:03:28 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-01-11_18-58-58.txt`](https://yam.ch/attachments/369/Crashlog_YAM_2013-01-11_18-58-58.txt) (39.2 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-01-11 19:22:15 +0100**

___
In (af17456):
 * YAM_WR.c: fixed a NULL pointer access when creating a new mail. This closes #369.

**Comment by jens-maus** [comment]
**Originally on 2013-07-02 21:27:29 +0200**

___
**Release Note:**
fixed a crash where it could have happened that YAM accessed an invalid memory location when creating a new mail.
