### ISSUE TITLE
Missing ARexx command to choose an identity

### ISSUE THREAD

**Issue by tboeckel** [jens-maus/yam#371]
**Originally on 2013-01-14 09:04:34 +0100**

___
Since the introduction of user identities it is impossible to choose the user identity to be used when composing a new mail using ARexx. So far YAM will always use the first/default identity which might not be the correct one when a user has configured more than one identity.

A to be implemented WRITEIDENTITY command should make it possible to chose an identity from the list of available identities either by its name/description or by the mail address configured for an identity.

**Comment by tboeckel** [comment]
**Originally on 2013-01-14 09:06:37 +0100**

___
In (fc70b6e):
 * Rexx.c, UserIdentities.c, rexx/writeidentity.c: added the ARexx command WRITEIDENTITY to let a script choose the user identity to be used when composing a new mail via ARexx. The identity can be chosen either by its description or by its mail address. The command template is "IDENTITY/K,ADDRESS/K". This closes #371.

**Comment by jens-maus** [comment]
**Originally on 2013-07-02 21:34:46 +0200**

___
**Release Note:**
added a new 'WRITEIDENTITY' ARexx command to let a script choose the user identity to be used when composing a new mail via ARexx.
