### ISSUE TITLE
Signature settings of folders get lost

### ISSUE THREAD

**Issue by tboeckel** [jens-maus/yam#372]
**Originally on 2013-01-14 09:34:44 +0100**

___
When updating from any version <= 2.7 to YAM 2.8 the signature settings of mailing list folders get lost.

Up to 2.7 YAM offered 3 signatures only (standard, alternative #1, alternative #2) to be chosen from globally and for folders with mailing list support. With YAM 2.8 these limited signatures have been replaced by an extendible list of signatures. The former signatures are automatically converted to this new style. However, for YAM 2.8 the automatic adaption of the signature used in ML folders is missing.

**Comment by tboeckel** [comment]
**Originally on 2013-01-14 10:10:05 +0100**

___
In (9f15df4):
 * YAM_FO.c: implemented updating the fixed signature number of a folder with mailing list support to the new signature handling. This closes #372.

**Comment by jens-maus** [comment]
**Originally on 2013-07-02 21:37:42 +0200**

___
**Release Note:**
fixed a bug where the signature settings of a folder got lost when updating from YAM versions <= 2.7 to 2.8
