### ISSUE TITLE
YAM crashed while entering text in CC line and again in background

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#373]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-14 16:14:18 +0100**

___
I was typing "N1900 EDID" into CC line by accident as I meant it as Subject. Crashed after "EDID". I told it to continmue and it recovered. But then then "N1900 EDID  dsd" appeared. Crashed again in background a few moments later while typing this description into NotePad. Crashlog attached.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-14 16:15:48 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-01-12_00-16-38.txt`](https://yam.ch/attachments/373/Crashlog_YAM_2013-01-12_00-16-38.txt) (32.1 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-01-14 16:58:37 +0100**

___
In (5e467c1):
 * mui/WriteWindow.c: added several NULL pointer checks. This closes #373.

**Comment by jens-maus** [comment]
**Originally on 2013-07-02 21:40:52 +0200**

___
**Release Note:**
fixed a crash when entering certain text in the CC string gadget of a write window.
