### ISSUE TITLE
Write window crashed during editing. NListtree.mcc the culprit!

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#374]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-14 16:24:47 +0100**

___
Simple as it sounds. There I was editing a mail and boom. Another crash. I'm really hoping it is MUI classes and not YAM crashing as I am finding YAM 2.8 very unstable! :-?

The crashlog lists NListtree.mcc as the culprit. :-)

I could recover by ignoring DSIs but then YAM went all weird. And kept looking for a directory of the following name:

Í{÷<ùÚOwò?ëúûy¾ÿ¹¹Öï?I®Íb¦ÚE%¹o%¼ëË¿¬ü>¿ûõ?v3ûKÿµÿäçëçú ÒÁÍ Äéóëº
ö¿nóoÄ§=wÂÛéÿ¿íçÄÙª÷áä¤©È¨çÃÿýþÿÛ®¼·ßïû·ýü×õÛÄ¿¥ö¸Õõöùñ±Ýßÿÿï¶çÿþôÝ=iîû¼NMe$#»½ñÿ|¿ÿ÷·
Äåöéãåóº
ÁÕÄÉÏ ÁÕØ ÁÕØ± ÃÄ° ÃÄ±
ÃÏÎ ÄÈ° ÄÈ± ÄÈ±± ÄÈ±³
ÄÈ±¶ ÄÈ±· ÄÈ±¸ ÄÈ² ÄÈ²±
ÄÈ³ ÄÈ´ ÅÎÖ ÉÃÄ° ÉÄÆ°
ËÃÏÎ ËÒÁ× ÐÁÒ ÐÃ° ÐÉÐÅ
ÐÉÐÅÃÏÎ ÐÒÔ ÒÁÍ ÒÁÎÄÏÍ ÒÁ×
ÓÅÒ ÓÅÒ± Ó×ÁÐ ÔÃÐ ÔÅØÔÃÌÉÐ
ÕÒÌ ÕÓÂÐÒÔ 

That's crazy! I was able to assign it to RAM then hold the mail and quit YAM. I reloaded it back in and it's fine for now.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-14 16:27:25 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-01-15_01-26-54.txt`](https://yam.ch/attachments/374/Crashlog_YAM_2013-01-15_01-26-54.txt) (33.8 KiB)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-14 16:27:50 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-01-15_01-26-47.txt`](https://yam.ch/attachments/374/Crashlog_YAM_2013-01-15_01-26-47.txt) (33.9 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-01-14 20:11:16 +0100**

___
Can you reproduce this crash? Or was it a "one time thing" only, maybe caused by previous crashes as reported in #373?

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-15 16:50:39 +0100**

___
This is another of those rare annoying crashes. But it's not related to #373. This happened in another session of YAM after a fresh bootup. And the code function differs.

It seems I always press something on the keyboard while looking at it and not the screen that triggers these rare bugs. Usually a slip onto shift or sometihng else. Perhaps I am too fast for it. Well, doubt it. :-)

I know these things really need to be reproducable but as soon as it happened I collected crash logs and wanted to report it. I can see the scientific method of bug tracking really needs to work with operational science rather than the hstorical science data I am giving you. :-D  But I prefer to file some notification rather than stay silent and spend ages trying to repeat the damned thing! :-)

And, like in #373, the relevant section of code can be checked to see if a NULL pointer was accessed. However, checkting the crash logs, it's not that simple and it looks like it stepped over the edge of a data structure. Though there is a fine line between valid pointer and invalid memory soon ater it. If that is the case.

**Comment by tboeckel** [comment]
**Originally on 2013-01-21 16:09:56 +0100**

___
Replying to hypex:
Please get the updated binaries of BetterString.mcc from ticket #377. The former version has some severe bugs in it contents string handling which could cause trashed memory quite easily. Install the appropriate build and try to reproduce this issue. Although the bug in BetterString.mcc has survived lots of month without being noticed I really doubt this is a bug in NListtree.mcc. And thinking about the trashed memory by BetterString.mcc this could probably have a bad impact on NListtree.mcc.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-23 14:23:43 +0100**

___
Understood. Will install and test.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-26 15:55:27 +0100**

___
Okay I have been testing with new component but NList is still crashing! I am getting the exact same crash as in my first log. NList calls GetVisualPos() which masks a value with 0xffff and then tries to load an offset pointer from an illegal address.

The only difference is now that the crash can happen anytime I have the edit window open. When I am in the body.

NList.mcc 20.134 (22/12/2012)
BetterString.mcc 11.24 (20/12/2012)

**Comment by tboeckel** [comment]
**Originally on 2013-02-06 10:15:55 +0100**

___
Any news on this issue?

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-02-06 13:54:19 +0100**

___
ATM YAM has been stable. But I haven't had much time for writing emails and so it may just lie dormant. However I think things are looking up! :-)

**Comment by jens-maus** [comment]
**Originally on 2013-02-14 07:40:10 +0100**

___
ok, then we will close this bug. So please reopen it if you feel the issue is back or still exists with the 2.9-dev nightly builds.
