### ISSUE TITLE
Crash of yam configuration under morphos 3.1

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#376]
**Originally by _bruno.flamme@orange.fr_ on 2013-01-17 15:53:52 +0100**

___
Hello,

I am running morphos 3.1 on my pegasos 2 g4. i use yam 2.8 as main mai program. Every thing works well excepted the configuration. if i click on configuration the application (yam) is meditating. It is crashed. is it known from you or am I the first reporting this ?

Brumiga

**Comment by jens-maus** [comment]
**Originally on 2013-01-17 15:55:12 +0100**

___
We haven't heard of any crashes when opening the yam config window under MOS 3.1. Could you please show a crash log or perhaps run a debug version so that we can investigate together?

**Comment by tboeckel** [comment]
**Originally on 2013-01-28 10:56:35 +0100**

___
Bump!

**Comment by jens-maus** [comment]
**Originally by _trac-robot_ on 2013-02-12 07:12:06 +0100**

___
This ticket was closed automatically by the system.  It was previously set to a Pending status and hasn't been updated within 14 days.
