### ISSUE TITLE
Grimreaper adding identity

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#377]
**Originally by _mario@cattaneo.de_ on 2013-01-20 16:30:05 +0100**

___
YAM 2.9-dev (19.01.2013)

- Go to prefs to add an identiy
- click the "+"
-> address field is active
- press RCommand-q
- start typing your address
-> on first char the list of matching addresses will open
-> on second char there will be the crash/GR (find log attached), no matter if the second char does still match or not.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2013-01-20 16:30:44 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-01-20_16-11-03.txt`](https://yam.ch/attachments/377/Crashlog_YAM_2013-01-20_16-11-03.txt) (29.6 KiB)
GR log

**Comment by jens-maus** [comment]
**Originally on 2013-01-20 16:46:26 +0100**

___
Here I could perfectly reproduce the problem. However, smells like a problem in BetterString.mcc. Needs some more investigation.

**Comment by tboeckel** [comment]
**Originally on 2013-01-21 10:18:49 +0100**

___
I found the problem. It is BetterString's internal handling of its string contents. There are 3 different buffers (normal, undo, original), but BetterString kept an allocation size for only one of these. Doing any action which caused the undo buffer to be used (i.e. delete a marked section) would simply swap the normal and undo pointers. However, the remembered allocation size for the former content string was still applied to the swapped string pointer with a (most probably different and smaller) allocation size and hence would trash memory.

I will attach fixed versions for AmigaOS3, AmigaOS4 and MorphOS. Please reopen this ticket if these versions still cause issues.

**Comment by tboeckel** [comment]
**Originally on 2013-01-21 10:19:39 +0100**

___
**Attachment added:** [`bstring_os3.lha`](https://yam.ch/attachments/377/bstring_os3.lha) (21.6 KiB)
Fixed BetterString.mcc for AmigaOS3

**Comment by tboeckel** [comment]
**Originally on 2013-01-21 10:19:51 +0100**

___
**Attachment added:** [`bstring_os4.lha`](https://yam.ch/attachments/377/bstring_os4.lha) (26.5 KiB)
Fixed BetterString.mcc for AmigaOS4

**Comment by tboeckel** [comment]
**Originally on 2013-01-21 10:20:05 +0100**

___
**Attachment added:** [`bstring_mos.lha`](https://yam.ch/attachments/377/bstring_mos.lha) (27.2 KiB)
Fixed BetterString.mcc for MorphOS

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2013-01-22 16:09:35 +0100**

___
Attached version crashes no more, thanks!

**Comment by tboeckel** [comment]
**Originally on 2013-01-22 16:26:32 +0100**

___
Replying to padrino:
> Attached version crashes no more, thanks!

Good to hear. Is it possible this was the cause for #358, too? Or can you still reproduce that one?

**Comment by jens-maus** [comment]
**Originally on 2013-07-04 21:08:08 +0200**

___
**Release Note:**
fixed an issue related to BetterString.mcc which cause YAM to crash.
