### ISSUE TITLE
"Apply to sent" filter moving a sent mail leaves Outgoing folder with wrong number of mails

### ISSUE THREAD

**Issue by tboeckel** [jens-maus/yam#378]
**Originally on 2013-01-21 20:11:27 +0100**

___
Reported privately by Jürgen Lucas:

Yam MorphOS nightly build from 22-Jan-2013

First create a filter that "apply to sent mail" compare something that will fit to the new email that you will create in step 2 and select as action move to folder trash (or some other user defined folder).
Second write a new mail that will fit to the just created filter and sent this mail.
Now you will see that yam show you 1 unread email in outgoing folder in the foldertree.
If you go to folder outgoing you will see that the folder is empty, because the filter moved your new email away. just update the index from outgoing to fix this.
look at the trash folder and you will find your moved email there.

after moving some email by filter the affected folders should get a index update.

**Comment by tboeckel** [comment]
**Originally on 2013-01-22 11:34:55 +0100**

___
In (4a50a2d):
 * tcp/smtp.c: moving a sent mail to another folder by an "apply to sent mails" filter will now update the Outgoing folder's stats to show the correct number of available mails. This closes #378.

**Comment by jens-maus** [comment]
**Originally on 2013-07-04 21:21:37 +0200**

___
**Release Note:**
fixed a bug where the number of mails in the outgoing folder was not correctly set when a mail was moved by mail filter operation.
