### ISSUE TITLE
Deleting multiple messages at once no  longer works

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#379]
**Originally by _mario@cattaneo.de_ on 2013-01-22 20:31:17 +0100**

___
Try to mark more than one mail by clicking and draging.
Then press the "delete" button.
Only one mail (the first?) will be deleted instead of all the marked ones.

**Comment by tboeckel** [comment]
**Originally on 2013-01-23 08:17:06 +0100**

___
Works perfectly here on AmigaOS3/WinUAE. All selected mails are moved to the Trash folder after confirming that more than just a single mail is to be deleted.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2013-01-26 14:50:09 +0100**

___
Strange, seems to have been a temporary effect. After a reboot everything is fine again. :-/
So you can close this.
When it reoccures, I will see if I can find out what makes it happen...
