### ISSUE TITLE
Editing overridden draft resets from: to original

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#380]
**Originally by _mario@cattaneo.de_ on 2013-01-26 14:57:17 +0100**

___
Love this

" * WriteWindow.c, YAM_WR.c, YAM_CO.c: added a new option in the hidden section of the configuration. Setting the option "OverrideFromAddress" to "Y" will add a recipient string object below the identity chooser in the write window."
(thanks guys! :))

But there is a small glitch...

When you put such a mail on hold, well, save it in draft, as it is called now, the correct overridden address is saved to it (you can view it to see it).
But when you edit the mail in the draft folder (via button or double click) the address is set back to the one which was set in the cycler when saving the draft.

Hope I can make myself clear...

**Comment by jens-maus** [comment]
**Originally on 2013-01-26 19:42:47 +0100**

___
Yes, you made yourself perfectly clear. We will investigate that shortly. However, please keep in mind that the new hidden option is largely unsupported and there might be other things not working perfectly with it. Also please refrain from requesting more and more enhancements regarding this hidden option. It is like it is and a compromise to get you back testing yam more intensively :) Still we believe the default user won't need it, thus it is a hidden and undocumented feature as it also increases potential for violating RFCs.

**Comment by tboeckel** [comment]
**Originally on 2013-01-27 19:53:05 +0100**

___
In (675a667):
 * mui/WriteWindow.c, YAM_WR.c: editing a draft mail again with the a modified From: address and the OverrideFromAddress feature being active now correctly restores the modified From: address. This closes #380.

**Comment by jens-maus** [comment]
**Originally on 2013-07-04 21:25:06 +0200**

___
**Release Note:**
fixed a bug where the From: address was not properly restored when the hidden "OverrideFromAddress" option had been used.
