### ISSUE TITLE
Write window is crashing simply by itself now

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#381]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-26 16:10:04 +0100**

___
I have the write window open. I canm be looking at the screen, not typing, and it will just crash. I can go back to Workbench to do some stuff and it will crash in the background. Just then I was posting this ticket and YAM crashed ahead of me!

Attached a few crashlogs that are occuring.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-26 16:11:16 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-01-27_01-32-22.txt`](https://yam.ch/attachments/381/Crashlog_YAM_2013-01-27_01-32-22.txt) (32.7 KiB)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-26 16:11:52 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-01-27_01-32-28.txt`](https://yam.ch/attachments/381/Crashlog_YAM_2013-01-27_01-32-28.txt) (32.7 KiB)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-26 16:12:16 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-01-27_02-05-28.txt`](https://yam.ch/attachments/381/Crashlog_YAM_2013-01-27_02-05-28.txt) (33.3 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-01-26 20:47:32 +0100**

___
I am sorry, but your report is missing some basic information, like which versions exactly you are using. Is this happening with YAM 2.8 or YAM 2.9-dev (which date)? Are you using the fixed version of BetterString as suggested in #377?

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-27 14:41:35 +0100**

___
Sorry thought I had specified using YAM 2.8 ticket version field. From 24/12/2012..

And yes using fixed version of BetterString which here reports as BetterString.mcc 11.24 [OS4/PPC] (20/12/2012). And BetterString.mcp: BetterString.mcp 11.24 [OS4/PPC] (20/12/2012).

With NListtree.mcp 18.29 [OS4/PPC] (22/12/2012).: NListtree.mcc 18.41 [OS4/PPC] (22/12/2012).

Finally muimaster.library 20.2346 (12/12/2012).

**Comment by tboeckel** [comment]
**Originally on 2013-01-27 18:40:15 +0100**

___
Replying to hypex:
> Sorry thought I had specified using YAM 2.8 ticket version field. From 24/12/2012..

The point is people often leave the version field as it is when reporting a new bug. And currently it defaults to "2.8". That's why I was asking.

> And yes using fixed version of BetterString which here reports as BetterString.mcc 11.24 [OS4/PPC] (20/12/2012). And BetterString.mcp: BetterString.mcp 11.24 [OS4/PPC] (20/12/2012).

Ok, would you please try YAM 2.9-dev then? I am quite sure I fixed this bug already since the official release.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-01-28 14:25:27 +0100**

___
Replying to thboeckel:

> The point is people often leave the version field as it is when reporting a new bug. 

I understand. I did see that it was the version I was reporting on.

> Ok, would you please try YAM 2.9-dev then?

Sure. I 'll test it out in the next few days.  And report back here. Right now YAM is acting stable. :-)

**Comment by tboeckel** [comment]
**Originally on 2013-02-06 10:15:46 +0100**

___
Any news on this issue?

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-02-06 13:56:51 +0100**

___
I need to test 2.9-dev more but I think you got it. I also updated MUI via AmiUpdate if that made any difference.

**Comment by jens-maus** [comment]
**Originally on 2013-02-14 07:42:36 +0100**

___
closing this bug as you feel the issue might be fixed. please reopen this ticket if the issue comes back.

**Comment by jens-maus** [comment]
**Originally on 2013-07-04 21:28:30 +0200**

___
**Release Note:**
fixed a bug where keeping the write window open for a while could suddenly crash YAM.
