### ISSUE TITLE
Grim Reaper when opening .eml

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#384]
**Originally by _lee@hawke.free-online.co.uk_ on 2013-02-04 16:07:44 +0100**

___
AmigaONE XE/G4, OS4.1u6, YAM 2.9-dev [OS4/PPC] 04/02/2013 (GCC 4.7.1, r6573)

Having forwarded an email. Open the email in the Sent folder, Double-click the .eml  file located at the bottom of the window - Attachments:
A Grim Reaper is generated, though, it's possible to Ignore DSI Errors and continue.
The crashlog is attached.

**Comment by jens-maus** [comment]
**Originally by _lee@hawke.free-online.co.uk_ on 2013-02-04 16:09:02 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-02-04_11-00-03.txt`](https://yam.ch/attachments/384/Crashlog_YAM_2013-02-04_11-00-03.txt) (32.4 KiB)
Opening .eml

**Comment by tboeckel** [comment]
**Originally on 2013-02-04 16:35:43 +0100**

___
In (e95cf9b):
 * mui/ReadWindowStatusBar.c: fixed two possible NULL pointer accesses for attached "virtual" mails. This closes #384.

**Comment by jens-maus** [comment]
**Originally on 2013-07-04 21:30:55 +0200**

___
**Release Note:**
fixed some crashes related to virtual email display (e.g. opening .eml attachments).
