### ISSUE TITLE
YAM ignores headerlines starting with "newline"

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#385]
**Originally by _mario@cattaneo.de_ on 2013-02-05 15:41:43 +0100**

___
I don't know if this is a bug, or fine due to definition, but YAM cannot/does not handle headerlines that start with newlines.

Eg.

SUBJECT:
This is a subject

Will be displayed with "empty subject", whereas

SUBJECT: This is a 
subject

displays the complete string "This is a subject".

**Comment by tboeckel** [comment]
**Originally on 2013-02-05 16:00:42 +0100**

___
I don't know how the RFCs handle this case. I think Jens can give a better answer if this is valid or not. Perhaps you can provide an example mail.

**Comment by tboeckel** [comment]
**Originally on 2013-02-05 16:11:52 +0100**

___
I just checked a manipulated mail with ThunderBird and MS Outlook and both displayed a subject starting on a new line correctly. Hence I'd say YAM is at fault here.

**Comment by tboeckel** [comment]
**Originally on 2013-02-05 19:10:53 +0100**

___
In (054e6a8):
 * YAM_MAf.c: reworked the mail header parsing to accept initial header lines without content. The content may now start on the next to be parsed line. This closes #385.

**Comment by tboeckel** [comment]
**Originally on 2013-02-06 09:29:51 +0100**

___
Mario, although this issue should be fixed now we still like to get some example mail for reference/evidence. Would you please provide one?

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2013-03-11 17:40:00 +0100**

___
**Attachment added:** [`newline.eml`](https://yam.ch/attachments/385/newline.eml) (44.5 KiB)
Example mail attached on request for reference

**Comment by jens-maus** [comment]
**Originally on 2013-07-04 21:38:12 +0200**

___
**Release Note:**
fixed a bug in the mail header parsing routines where a header line starting with a newline cause problems.
