### ISSUE TITLE
cc gone on 2.9 ?

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#387]
**Originally by _JDuch@fulladsl.be_ on 2013-02-12 15:50:52 +0100**

___
The possibility to indicate cc mail adresses that was moved from 'options' in 2.7 tot the message front in 2.8, does not appear anywhere in 2.9 dev

**Comment by tboeckel** [comment]
**Originally on 2013-02-12 15:55:51 +0100**

___
Check the write window's "View" menu. You will find everything you are looking for there.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-02-12 15:58:53 +0100**

___
And now that i came to notice it: the bcc possibility has gone too, and this also in 2.8

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-02-12 16:07:44 +0100**

___
OK my latest message crossed  your update.

Thanks
