### ISSUE TITLE
check for several online interfaces

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#39]
**Originally by _anonymous_ on 2010-03-03 22:50:48 +0100**

___
It would be nice if it is allowed to specify not only one interface which should be checked if it is online, but several, e.g.: (seperated through ",")

... = ppp0,ppp7,ppp2

(sorry I don't know the exact variable name in the config file under hidden options at the moment but I think it is the one below "IsOnlineCheck")

**Comment by jens-maus** [comment]
**Originally on 2010-03-09 12:41:54 +0100**

___
makes perfectly sense IMHO.

**Comment by tboeckel** [comment]
**Originally on 2010-07-28 09:43:35 +0200**

___
In (1a9f216):
 * YAM_TR.c, YAM_CO.c, YAM_COs.c: implemented a multiple interface check to be
  able to specify more than just a single interface to be checked to be
  online. It is now possible to provide a comma separated list of interfaces
  to be checked in the advanced section of YAM's config (i.e. "eth0,ppp0").
  This closes #39.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2010-07-28 10:51:54 +0200**

___
To be on the save side the patch should also recognise entries like:
" eth0 , ppp0 ". So the iface string should be trim()ed before calling
CheckSingleInterface().

**Comment by jens-maus** [comment]
**Originally on 2010-07-28 11:03:30 +0200**

___
added the Trim() operation now to the execution of CheckSingleInterface(). Thanks for the hint.
