### ISSUE TITLE
Getting mails from gmail,

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#392]
**Originally by _mlehto_ on 2013-03-11 16:58:35 +0100**

___
I have old gmail account full of mails, roughly 1300.

gmail is set up to allow pop/access.

Account itself works.

When I get mails from gmail, YAM find somewhere 100-300 mails. Takes them. Not find all.

Set up is, that it leaves mail to server.

When I get them again, it again finds some mails and start to get them. 

Obviously YAM cant separate new mail from olds, because all in all I got 1600 mails repeating get many times, where 1300 is possible.

Somehow YAM and gmail communication is broken, I think.

When I set up as gmail allow pop/acces from that moment, everything goes well and only new mail arrive.

Other thing was, that at least at time, when I tried to get all old mails from server, all was marked as spam and moved to spam-folder.

**Comment by tboeckel** [comment]
**Originally on 2013-03-11 21:08:45 +0100**

___
Replying to [#392 mlehto]:

> When I get mails from gmail, YAM find somewhere 100-300 mails. Takes them. Not find all.

YAM will remember which mails it already did download from the POP3 server and will skip them on the next POP3 download in case they were left on the server. There is no point in downloading thousands of mails over and over again, isn't it?

> Somehow YAM and gmail communication is broken, I think.

If you think the communication is really broken then start YAM from a shell with the DEBUG option. YAM will then print the complete communication between your machine and the server to the shell. This should reveal if there is something going wrong. Just redirect this output to a file and attach it to this ticket (i.e. YAM debug >t:gmail.log)

> Other thing was, that at least at time, when I tried to get all old mails from server, all was marked as spam and moved to spam-folder.

The spam filter must be trained to be able to tell "good" mails and "bad" mails apart. That means that in the beginning many mails will falsely be treated as spam even if they are normal mails. You then have to tell YAM the truth about these mails by declaring them as "no spam" (or by declaring false negatives as true "spam"). This will train the filter and improve its spam recognition abilities with every new mail.

**Comment by tboeckel** [comment]
**Originally on 2013-03-12 08:50:22 +0100**

___
Replying to thboeckel:
> If you think the communication is really broken then start YAM from a shell with the DEBUG option. YAM will then print the complete communication between your machine and the server to the shell. This should reveal if there is something going wrong. Just redirect this output to a file and attach it to this ticket (i.e. YAM debug >t:gmail.log)

Just one additional note. If you are going to attach such a log here please make sure to remove personal stuff like passwords from it. The log will contain unencrypted passwords. So please don't complain if you forgot to remove this stuff and somebody hacks your mail account!

**Comment by tboeckel** [comment]
**Originally on 2013-03-12 09:02:21 +0100**

___
I just did some tests with my own googlemail account and although YAM is configured to leave all mails on the server they will be deleted nevertheless as soon as they are downloaded via the POP3 protocol. But this deletion is NOT caused by YAM. This seems to be done automatically by googlemail.

Thus there is nothing wrong in YAM. I am sorry, but there is nothing we can do about such an "automatism". Direct your complaints to googlemail directly.

**Comment by tboeckel** [comment]
**Originally on 2013-03-12 21:28:46 +0100**

___
Enable the "recent" mode to download mails to more than just one single device: [http://support.google.com/mail/answer/47948?hl=en]

**Comment by jens-maus** [comment]
**Originally on 2013-03-16 10:29:49 +0100**

___
Replying to thboeckel:
> Enable the "recent" mode to download mails to more than just one single device: [http://support.google.com/mail/answer/47948?hl=en]

As questions about this and similar observations might come up I guess it would be a good idea to create a new FAQ entry about that. Opinions?

**Comment by tboeckel** [comment]
**Originally on 2013-03-17 09:22:10 +0100**

___
Replying to damato:

> As questions about this and similar observations might come up I guess it would be a good idea to create a new FAQ entry about that. Opinions?

You know my usual answer: go ahead ;) A FAQ entry for this special case is real worth being added.
