### ISSUE TITLE
Crash while supposedly running an arexx script in the background.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#393]
**Originally by _Deniil715_ on 2013-03-11 23:52:43 +0100**

___
I came home from work and YAM had crashed. From the crashlog it appeared to be running an arexx script. I have a script that is runs one a day in the background.

**Comment by jens-maus** [comment]
**Originally by _Deniil715_ on 2013-03-11 21:52:53 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-03-11_18-09-52.txt`](https://yam.ch/attachments/393/Crashlog_YAM_2013-03-11_18-09-52.txt) (38.2 KiB)
OS4.1.6 Crashlog

**Comment by jens-maus** [comment]
**Originally by _Deniil715_ on 2013-03-11 21:54:18 +0100**

___
**Attachment added:** [`DagensTV.rexx`](https://yam.ch/attachments/393/DagensTV.rexx) (0.2 KiB)
Script that was running. (The tool DagensTV was not running.)

**Comment by tboeckel** [comment]
**Originally on 2013-03-12 06:42:16 +0100**

___
In (f641c8a):
 * rexx/mailinfo.c: added some NULL pointer checks. This refs #393.

**Comment by tboeckel** [comment]
**Originally on 2013-03-12 07:30:26 +0100**

___
This issue is a bit strange. The crashlog clearly points out that the crash happened while YAM was processing the MAILINFO ARexx command. But there is no such call in the script you supplied. Are you sure it was really this script causing the crash?

**Comment by tboeckel** [comment]
**Originally on 2013-03-12 09:42:55 +0100**

___
Perhaps you should adapt your script to make sure that there is actually a mail to be read and analyzed. For example if the current folder is a folder group instead of a real mail folder then there will be no mail to be read and hence cause your script to fail.

**Comment by tboeckel** [comment]
**Originally on 2013-03-28 09:16:43 +0100**

___
Bump! Still waiting for a reply...

**Comment by jens-maus** [comment]
**Originally by _trac-robot_ on 2013-04-12 07:20:59 +0200**

___
This ticket was closed automatically by the system.  It was previously set to a Pending status and hasn't been updated within 14 days.
