### ISSUE TITLE
Crash on deleting mail

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#394]
**Originally by @raziel- on 2013-03-24 12:36:47 +0100**

___
YAM 2.8

I get a reproduceable crash on deleting a mail
(It might happen when or while simultaneously the bottom scrollbar of MUI is drawn and visible, but i'm not sure if this is related)

Two crashlogs showing nearly the same data attached

Normally it's known info mail or spam that gets immediately deleted by me after i scrolled down to the newest mail. (sorted from top - oldest, to bottom - newest)
On doing so and reaching the bottom of the list the bottom scrollbar (right-left) will be drawn by YAM/MUI covering up the formerly newest mail, so i have to scroll down one line again to make the newest mail visible.

Now on deleting this mail the crash happens right after the bottom scrollbar has been erased by YAM/MUI...so i'd say it might be MUI acting up, but i don't know for sure.

AmigaOS4 up tp date with the debug kernel

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-03-24 12:37:19 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-03-23_00-09-07.txt`](https://yam.ch/attachments/394/Crashlog_YAM_2013-03-23_00-09-07.txt) (37.9 KiB)
Yesterday crash

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-03-24 12:37:41 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-03-24_12-24-06.txt`](https://yam.ch/attachments/394/Crashlog_YAM_2013-03-24_12-24-06.txt) (36.3 KiB)
and today crash with the nearly exact same data

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-03-24 12:40:27 +0100**

___
I need to add that i have to be quick to make it crash.
Normally on scrolling up and down the list the bottom scroller goes away sooner or later when the listview window rearranges itself.

I *think* that once the bottom scroller is gone the crash won't show up.
I have to test that yet ;-)

**Comment by tboeckel** [comment]
**Originally on 2013-03-24 14:05:11 +0100**

___
Please try to switch off NList's automatic scrollbars. This should fix this issue for the moment.

**Comment by tboeckel** [comment]
**Originally on 2013-03-25 11:06:54 +0100**

___
**Attachment added:** [`nlist_20_135.lha`](https://yam.ch/attachments/394/nlist_20_135.lha) (119.5 KiB)
NList 20.135

**Comment by tboeckel** [comment]
**Originally on 2013-03-25 11:15:50 +0100**

___
@raziel-

I just fixed two possible buffer underruns which might have caused trashed memory under certain circumstances. Additionally removing and readding a scrollbar left some old notifications alive and hence let the notification list grow constantly.

What is a bit puzzling is that fact that your crashlogs show the typical 0xcccccccc value in r9 which clearly points to a duplicate Remove() action which was caused by an ancient bug in MUIM_KillNotify. Although MUI on AmigaOS4 is immune to this bug since muimaster.library 20.2346 (you are using 20.2347) it still might be caused by trashed memory.

Please try the attached versions of NList.mcc and NListview.mcc and report back here. I really hope these fix this issue. At least on WinUAE/AmigaOS3 I was not able to reproduce any kind of misbehaviour when definitely occured before.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-03-25 21:22:32 +0100**

___
I should have added that im using the debug kernel (which shouldnt be an issue though, just for the record).

I will try the attached versions as soon as possible (which might be as late as beginning of April im afraid (im not at home right now)

Thanks for the fast reply

**Comment by tboeckel** [comment]
**Originally on 2013-03-26 14:43:45 +0100**

___
You did already in your initial report ;) And without the debug kernel this crash wouldn't have happened.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-04-02 17:37:07 +0200**

___
I'm testing for some time now and the behaviour hasn't come up again, so i'd say it's been fixed...BUT

the attached .mcc classes seem to have a bug itself..at least i get a strange behaviour, but maybe it's known and fixed already.

If i have a "short" list of mails (say 20) the right scrollbar is VERY small and stuck to the top few centimeters of the scrollbar field...when scrolling down the lsit the little scrollbar gadget moves along but only a little bit so it will always stay in the top few centimeters.

Vice versa with a "long" list of eMails (say 120)...now the scrollbar is nearly filling the whole right scrollbar field and is scrolling down only with the first few eMails before it reaches (because of it's size) the bottom and stays there while the scolling is going on still for a very long while.

This will be partly "fixed" when new mail arrives, but only to be replaced by a half full scrollbar which also scrolls to the top or bottom with many mails and then stays there with still many mails to scroll.

**Comment by tboeckel** [comment]
**Originally on 2013-04-03 20:18:05 +0200**

___
**Attachment added:** [`nlistview_19_90.lha`](https://yam.ch/attachments/394/nlistview_19_90.lha) (8.2 KiB)
NListview 19.90 2nd try

**Comment by tboeckel** [comment]
**Originally on 2013-04-03 20:18:54 +0200**

___
@raziel-

> the attached .mcc classes seem to have a bug itself..at least i get a strange behaviour, but maybe it's known and fixed already.

The updated NListview.mcc should fix this.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-04-03 20:33:15 +0200**

___
Yes it does, thanks a lot :-)

I haven't come across this nasty bug anymore.
I'd say it has been handled ;-)

**Comment by tboeckel** [comment]
**Originally on 2013-04-03 20:43:05 +0200**

___
Ok, closing this one.
