### ISSUE TITLE
Crash while trying to delete folder group

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#395]
**Originally by _hypexed@yahoo.com.au_ on 2013-04-15 16:43:43 +0200**

___
Hello. I was trying to add a folder to my main list and accidently created a folder group. I draggged it to where I wanted the folder to be but it wasn't right so decided to delete it. I right clicked it to get context menu and selected delete. YAM then crashed twice before  asking me if I wanted to delete it. I said yes and got two more similar crashes. But then a thrird came and YAM did nor recover.

Logs attached.
YAM 2.8. (24/12/2012)
NListtree.mcc 18.41 [OS4/PPC] (22/12/2012)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-04-15 16:49:37 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-04-16_00-24-23.txt`](https://yam.ch/attachments/395/Crashlog_YAM_2013-04-16_00-24-23.txt) (37.6 KiB)
1st crash after selecting to delete

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-04-15 16:53:01 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-04-16_00-24-30.txt`](https://yam.ch/attachments/395/Crashlog_YAM_2013-04-16_00-24-30.txt) (37.6 KiB)
2nd crash after selecting to delete

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-04-15 16:55:03 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-04-16_00-25-32.txt`](https://yam.ch/attachments/395/Crashlog_YAM_2013-04-16_00-25-32.txt) (38.0 KiB)
1st crash after confirming to delete

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-04-15 16:55:50 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-04-16_00-25-39.txt`](https://yam.ch/attachments/395/Crashlog_YAM_2013-04-16_00-25-39.txt) (38.0 KiB)
2nd crash after confirming to delete

**Comment by tboeckel** [comment]
**Originally on 2013-04-16 09:07:05 +0200**

___
In (8abca01):
 * YAM_FO.c: remember the treenode pointer of a newly created folder group. This closes #395.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2013-04-16 19:34:17 +0200**

___
Good. Thanks. :-)

**Comment by jens-maus** [comment]
**Originally on 2013-07-04 22:13:34 +0200**

___
**Release Note:**
fixed a crash bug when deleting a folder group.
