### ISSUE TITLE
Implement a special Archive folder

### ISSUE THREAD

**Issue by tboeckel** [jens-maus/yam#396]
**Originally on 2013-04-18 08:48:46 +0200**

___
Other mail clients offer a special folder for archiving mails to not let them be deleted when they are too old. Such an archive folder should be a top level folder and contain further subfolders for the individual years. When a mail is archived it will be moved to the respective (automatically created) year subfolder within the archive folder. The year folder corresponds to the mail's send date.

By default there is no archive folder. It will be created upon archiving the first mail and be placed near the top of the folder tree (i.e. somehwere between the Sent and the Trash folder).

**Comment by tboeckel** [comment]
**Originally on 2013-08-14 21:16:23 +0200**

___
In (b2ce9f8):
 * YAM_MA.c, misc: implemented the Archive folder as proposed in #396. Archived mails will be moved to a folder named after the mail's original send date. The archive folders are excluded from deleting old mails automatically to make sure the mails are really archived until the user explicitly deletes them. This closes #396.

**Comment by tboeckel** [comment]
**Originally on 2013-08-14 21:40:51 +0200**

___
**Release Note:**
Implemented the Archive folder as proposed in #396. Archived mails will be moved to a folder named after the mail's original send date. The archive folders are excluded from deleting old mails automatically to make sure the mails are really archived until the user explicitly deletes them.

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 19:28:19 +0100**

___
**Release Note:**
Implemented an 'Archive' folder which move mails to a folder named after the mail's original send date. The archive folders are excluded from deleting old mails automatically to make sure the mails are really archived until the user explicitly deletes them.
