### ISSUE TITLE
Wrong Image Dimensions

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#397]
**Originally by _opionline@yahoo.de_ on 2013-05-12 20:49:38 +0200**

___
Today i update my YAM Installation to Version:
YAM 2.9-dev (09.05.2013) Copyright (C) 2000-2013 YAM Open Source Team [OS3/m68k, r6649]

and get a requester saying:
"
TheBarVirt.mcc image dimension mismatch

The normal image
'PROGDIR:Resources/Themes/NewIcons/toolbar/tb_getmail'
has dimension  29x 28.
The selected image
'PROGDIR:Resources/Themes/NewIcons/toolbar/tb_getmail_s'
has dimension  29x 27.

Please remove this image or replace
it by one with matching dimensions.

A suitable selected image will now be generated
from the normal image.

Continue
"

I think the dimensions shipped with YAM should have the correct dimensions.
BTW: i get the same requester 2 times.

**Comment by jens-maus** [comment]
**Originally on 2013-05-12 20:59:57 +0200**

___
I can confirm that the two images in the NewIcons theme shipped with YAM have different dimensions and should be adapted accordingly.

**Comment by tboeckel** [comment]
**Originally on 2013-05-13 08:41:26 +0200**

___
In (6a084f5):
 * themes/MagicWB reduced, themes/Mason old, themes/NewIcons: fixed the dimensions of some toolbar button images to avoid warnings from TheBar.mcc. This closes #397.

**Comment by jens-maus** [comment]
**Originally on 2013-07-04 22:14:20 +0200**

___
**Release Note:**
fixed some incorrect dimensions of certain theme images.
