### ISSUE TITLE
Progress Bar for uploading mail

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#398]
**Originally by @raziel- on 2013-06-04 21:09:27 +0200**

___
I'd like to ask if the implementation of an upload progress bar is possible?
Especially mails with attachments can grow really big and it would add to the user friendlyness(?). :-)
Plus YAM already knows the size of the mail it's going to send.

Maybe just a short one like the progress bar when the mail filter is active.
And at the same position too.

Thanks a lot

**Comment by tboeckel** [comment]
**Originally on 2013-06-04 21:55:47 +0200**

___
Replying to [#398 Raziel]:
> I'd like to ask if the implementation of an upload progress bar is possible?
> Especially mails with attachments can grow really big and it would add to the user friendlyness(?). :-)
> Plus YAM already knows the size of the mail it's going to send.

What is wrong with the progress bar in the mail transfer window? Ok, it is located in a separate window, but in principle the transfer window will show you all the statistics and progress you are asking for.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-06-04 22:32:50 +0200**

___
yes...now that you mention it, there normally came up a window which showed the mails that are downloaded and the mails that are uploaded (with progress bar).

But i haven't seen it in years :-?
I completely forgot about it...is there an option to turn that window on/off?
I might have done that and forgotten about it.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-06-04 23:53:58 +0200**

___
Found it.

Config - Miscellaneous - Transfer Window
I had set it to "hide always" :blush:

Sorry for the hassle, this can be closed then (though it still would be nice to have it incorporated in the main window - as an option - on a very low priority) ;-)

**Comment by jens-maus** [comment]
**Originally on 2013-06-05 09:00:44 +0200**

___
If you would like to see such a thing implemented please file a separate enhancement request for it.
