### ISSUE TITLE
Jump to oldest unread msg on a per folder basis

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#40]
**Originally by _anonymous_ on 2010-03-03 22:52:23 +0100**

___
Beginning with version 2.3 of YAM, the message list scrolls automatically to the oldest unread message whenever a folder is opened.

While this is a good idea for some folders (like incoming, or any folder where I keep current on all messages), for others it is not. I follow a number of mailing lists in which I read messages only sporadically, and I keep several months of messages online. With such groups, it takes an extra couple of seconds to open the folder because of scanning for read/unread messages, and then I have to manually scroll back to the current messages to see what's new. I don't want to manually mark all messages as read, because it's an extra step and because it is useful for me to know which old messages I've looked at and which I haven't.

Could this process of scanning for the oldest unread message upon opening a folder be made optional on a folder-by-folder basis? That would give us all the best of both worlds.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2010-03-03 22:53:18 +0100**

___
I totally agree with you! The way the message list behave when you enter it should absolutely be optional. This was one reason why I waited so long upgrading to YAM2.3 ...

Please.. don't force us all to use new "features" by default.. that's the microsoft's way of doing things..not the Amiga way..

**Comment by jens-maus** [comment]
**Originally on 2013-01-19 21:28:48 +0100**

___
Valid and makes sense.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-07 22:46:19 +0200**

___
This will be solved at the same time of fixing #284 (and #410 ).

You will then just have to set the "View" cycle gadget to whatever you want (eg. "New") for your folders.

**Comment by tboeckel** [comment]
**Originally on 2013-10-14 16:23:17 +0200**

___
In (3154abb):
 * YAM_FO.c, misc: jumping to the first unread and/or most recent message when entering a folder is now a per folder option instead of a global option. This closes #40.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 22:18:29 +0100**

___
**Release Note:**
changed the "jumping to the first unread and/or most recent message when entering a folder" functionality to be configurable on a per folder basis instead of a being a global option only.
