### ISSUE TITLE
Allow to set alternative default folder on a per account basis

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#400]
**Originally on 2013-07-01 21:10:36 +0200**

___
## Phenomenon
Currently, all mails from all configured POP3 accounts are routed to the very same "incoming" folder. In addition, all the other default folders (outgoing, deleted, etc.) are shared throughout the different accounts. There should be, however, a possibility to configure different incoming folders on a per-POP3-account basis to improvide flexibility for the end-user.

## Background analysis
Users want to have mails from different POP3-accounts, which relates to different email adddresses, be routed to different incoming folders for more easily distinguishing the mails. It is therefore desireable to provide a functionality to define separate incoming and also deleted, outgoing etc. folder.

## Implementation recommendation
When implemented, the YAM configuration should be changed in the TCP/IP config page (Receive mail) to allow to view/modify the standard folders. If not separately configured the default incoming folder will be routed to the global incoming folder associated with the first undeletable account. Also in the SMTP section (Send mail) the possibility to define the 'Sent' folder should be added as well as the already existing identity-based overriding of the Sent folder be changed to simply allow to override the settings. If correctly impelemented this ticket should also automatically fullfil ticket #230 which can then be closed accordingly.

**Comment by jens-maus** [comment]
**Originally on 2013-11-14 20:26:43 +0100**

___
In (d12293b):
 * mui/TCPIPConfigPage.c, misc: added a FolderRequestPopupObject to the POP3
  and SMTP config pages to allow to set an alternative incoming and sent 
  folder. This refs #400. Please note, that the functionality is yet not being
  used in YAM as we first have to change the way folders are referenced within
  YAM.

**Comment by tboeckel** [comment]
**Originally on 2013-11-15 10:14:33 +0100**

___
In (04deb87):
 * YAM_FO.c, Config.c, FolderList.c, misc: each folder now gets a unique ID assigned. In the future everything will be changed to reference folders by this ID only instead of referencing them by name, path or type. This will eventually make it possible to have equally named folders in different paths. This refs #400 and also refs #50.

**Comment by jens-maus** [comment]
**Originally on 2013-11-17 20:23:41 +0100**

___
In (64368a7):
 * tcp/pop3.c, tcp/smtp.c: changed the respective receive and sent functions
  of the pop3 and smtp routines to store mails in the respective mail store
  folder based on the folder id stored. This closes #400 and thus should
  allow to configure different 'Incoming' and 'Sent' folders for each
  POP3 and SMTP account. As a net result this should allow to sort mails
  based on the accounts in different folders.

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 19:32:45 +0100**

___
**Release Note:**
implemented a new functionality to allow to define different 'incoming' and 'sent' folders per configured mail account (POP3/SMTP). This should allow to more easily and directly filter emails not requiring to explicitly define separate filters.
