### ISSUE TITLE
Identities are not working properly (YAM 2.8p1, MorphOS)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#401]
**Originally by _yam.asc@schwarzes.net_ on 2013-07-08 03:05:38 +0200**

___
I've two issues regarding the identity handling (they will also occur with 2.8).

1. Identities which are marked as inactive (active not checked), will be still used for sender/from substitution when replying.

2. This is more complex. Let assume that we have two local identities A and B and now B (which is on travel) is sending an email from remote site to A. If A now replying, the "From" address will be substituted with the identity of B (but should be A).

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 10:52:49 +0200**

___
Please give some more detailed information on how to reproduce this issue. So far I was not able to reproduce this myself. Especially no. 2 puzzles me.

**Comment by jens-maus** [comment]
**Originally by _yam.asc@schwarzes.net_ on 2013-07-08 23:54:22 +0200**

___
Ok, I'll try. Both issues are not the same bug, it was my fault to put them into one ticket.

1. I've two identities, one for my regular email address and another one for my ebay emails. If I 
deactivate the ebay identity (disable active check button in the "Identities Settings"), yam will 
still use this idenity when I compose a reply to an email which was sent to my ebay Email Address.

2. Let's assume, I've two another identities, Mr.A@mydomain.com and Mrs.B@mydomain.com. 
Let's also assume, Mrs.B is on holiday and is sending an email to Mr.A (which is using yam).
If Mr.A now answering to the email from Mrs.B, yam uses the identity of Mrs.B for the reply.

**Comment by tboeckel** [comment]
**Originally on 2013-07-09 08:28:35 +0200**

___
In (c4814ac):
 * UserIdentity.c: searching user identities by address or ID will now correctly respect the identity's active state and return active identities only. In case a mail references an inactive user identity YAM will silently fall back to the next best matching identity. This closes #401.

**Comment by tboeckel** [comment]
**Originally on 2013-07-09 08:33:43 +0200**

___
**Release Note:**
Searching user identities by address or ID will now correctly respect the identity's active state and return active identities only. In case a mail references an inactive user identity YAM will silently fall back to the next best matching identity.

**Comment by tboeckel** [comment]
**Originally on 2013-07-09 09:56:08 +0200**

___
Replying to thboeckel:
> In (c4814ac):
 * UserIdentity.c: searching user identities by address or ID will now correctly respect the identity's active state and return active identities only. In case a mail references an inactive user identity YAM will silently fall back to the next best matching identity. This closes #401.

This solution only covers part 1 of this ticket. Please open a new ticket for the second part and include your latest explanation of how to reproduce this issue.
