### ISSUE TITLE
grim reaper when starting yam nightly (09.07.2013 (GCC 4.7.1, r6681))

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#403]
**Originally by _Michael.Merkel@gmx.net_ on 2013-07-09 20:00:00 +0200**

___
with tonights nightly i get a grim reaper when starting it. i can continue and everything seems to be fine.

using os4.1 beta version (up-to-date).

reaper is attached.

regards...
michael

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2013-07-09 20:00:21 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-07-09_19-53-12.txt`](https://yam.ch/attachments/403/Crashlog_YAM_2013-07-09_19-53-12.txt) (37.8 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-07-10 08:33:43 +0200**

___
In (251bf2b):
 * mui/MainWindow.c: don't clear the quick search bar contents when changing the main window's layout. This closes #403.

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 22:58:35 +0100**

___
**Release Note:**
fixed a bug where clearing the quick search bar contents when changing the main window's layout caused a crash.
