### ISSUE TITLE
GR (DSI) on starting YAM2.9dev (9.07.2013)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#404]
**Originally by _javierdlr@euskalnet.net_ on 2013-07-10 00:33:02 +0200**

___
Starting YAM 2.9dev 9.07.2013 shows a GR on startup, it points to NList.mcc V20.135
Need more data?

Crash log for task "YAM"
Generated by GrimReaper 53.16
Crash occured in module NList.mcc at address 0x7F7F5220
Type of crash: DSI (Data Storage Interrupt) exception

Register dump:
GPR (General Purpose Registers):
   0: 7F7F7660 6062EC70 018445A4 00000000 00000000 00000000 00000000 00000000 
   8: 5FB44360 00000100 60B02784 0226DFC6 48822048 60F99294 00000001 60B024E8 
  16: 00000000 00000000 00000000 00000001 00000000 5FB44360 00000000 FFFFFFFF 
  24: 00000001 00000001 00000000 0000012D 00000000 FFFFFFFF 00000000 5FBB1818 

FPR (Floating Point Registers, NaN = Not a Number):
   0:              nan            255.5          0.99999     4.12498e+267 
   4:    -2.76714e+268     1.22786e+269              128            1.125 
   8:                0      -0.00196464       3.8598e-06      -0.00393181 
  12:                1                1     -1.68136e+16    -1.05263e+306 
  16:    -4.63856e+249    -2.19001e+305       4.799e+142     -1.21148e-80 
  20:     5.44185e+306     1.32648e+228    -2.29062e+231     -2.5254e+221 
  24:    -1.70447e+289    -5.76522e+259    -2.50957e+305    -3.51238e+295 
  28:     1.44715e+221     2.01263e+305    -9.59991e+303    -1.37112e+146 

FPSCR (Floating Point Status and Control Register): 0x82020000

SPRs (Special Purpose Registers):
           Machine State (msr) : 0x0002F030
                Condition (cr) : 0x5FA72360
      Instruction Pointer (ip) : 0x7F7F5220
       Xtended Exception (xer) : 0x0000FFFF
                   Count (ctr) : 0x5FA72710
                     Link (lr) : 0x629954C8
            DSI Status (dsisr) : 0x5FA72380
            Data Address (dar) : 0x0181ABE8

680x0 emulated registers:
DATA: 62ABE1FE 00000003 00000000 00000000 00000000 00000000 00000000 00000000 
ADDR: 6FD2B85C 00000000 00000000 00000000 00000000 00000000 00000000 6062F010 
FPU0:                0                0                0                0 
FPU4:                0                0                0                0 

Symbol info:
Instruction pointer 0x7F7F5220 belongs to module "NList.mcc" (PowerPC) 
Symbol: ParseColumn + 0x200 in section 2 offset 0x000121FC

Stack trace:
    ParseColumn()+0x200 (section 2 @ 0x121FC)
    ParseColumn()+0x88 (section 2 @ 0x12084)
    NL_SetColsAdd()+0x88 (section 2 @ 0x15938)
    NL_List_Clear()+0x1cc (section 2 @ 0x26060)
    _Dispatcher()+0xce8 (section 2 @ 0x5A1C)
    CustomClassDispatcher()+0xa0 (section 1 @ 0x417C)
    native kernel module intuition.library.kmod+0x000181fc
    native kernel module intuition.library.kmod+0x00018420
    native kernel module intuition.library.kmod+0x00008300
    CustomClassDispatcher()+0xa0 (section 1 @ 0x417C)
    native kernel module intuition.library.kmod+0x000181fc
    native kernel module intuition.library.kmod+0x00018420
    native kernel module intuition.library.kmod+0x00008448
    native kernel module intuition.library.kmod+0x00008088
    m_MainMailListGroup_SwitchToList()+0x550 (section 2 @ 0xCF284)
    CustomClassDispatcher()+0xa0 (section 1 @ 0x417C)
    native kernel module intuition.library.kmod+0x000181fc
    native kernel module intuition.library.kmod+0x00018420
    native kernel module intuition.library.kmod+0x00008448
    native kernel module intuition.library.kmod+0x00008088
    m_QuickSearchBar_Clear()+0x84 (section 2 @ 0xD5FAC)
    CustomClassDispatcher()+0xa0 (section 1 @ 0x417C)
    native kernel module intuition.library.kmod+0x000181fc
    native kernel module intuition.library.kmod+0x00018420
    native kernel module intuition.library.kmod+0x00008448
    native kernel module intuition.library.kmod+0x00008088
    m_MainWindow_Relayout()+0x16c (section 2 @ 0xCFCFC)
    CustomClassDispatcher()+0xa0 (section 1 @ 0x417C)
    native kernel module intuition.library.kmod+0x000181fc
    native kernel module intuition.library.kmod+0x00018420
    native kernel module intuition.library.kmod+0x00008448
    native kernel module intuition.library.kmod+0x00008088
    InitAfterLogin()+0x1c8 (section 2 @ 0xB70)
    main()+0x13a8 (section 2 @ 0x612C)
    native kernel module newlib.library.kmod+0x000020ac
    native kernel module newlib.library.kmod+0x00002d5c
    native kernel module newlib.library.kmod+0x00002ef0
    _start()+0x170 (section 2 @ 0x16C)
    native kernel module dos.library.kmod+0x00023378
    native kernel module kernel+0x0003c72c
    native kernel module kernel+0x0003c7ac

PPC disassembly:
 7f7f5218: 7f8ed840   cmplw             cr7,r14,r27
 7f7f521c: 409c00c4   bge-              cr7,0x7F7F52E0
*7f7f5220: 88ae0000   lbz               r5,0(r14)
 7f7f5224: 2f850000   cmpwi             cr7,r5,0
 7f7f5228: 419e00b8   beq-              cr7,0x7F7F52E0

System information:

CPU 
 Model: AMCC PPC460EX V1.2 
 CPU speed: 1155 MHz 
 FSB speed: 231 MHz 
 Extensions:  

Machine 
 Machine name: Sam460ex 
 Memory: 2097152 KB 
 Extensions: bus.pci bus.pcie 

Libraries 
 0x62c1c9d8: ISO-8859-15.charset V52.1 
 0x62c1c8d8: spanish_ISO-8859-15.language V52.1 
 0x0226dfc6: exec.library V53.54 
 0x6ffa8174: vilintuisup.library V0.9 
 0x6ffa8048: cgxvideo.library V42.1 
 0x6ffdf0e0: cybergraphics.library V43.0 
 0x6055ec00: Poppen.mui V20.312 
 0x6055eac0: Popasl.mui V20.262 
 0x6055ea20: Numericbutton.mui V20.268 
 0x6055e840: Popmenu.mui V20.221 
 0x6055e520: Floattext.mui V20.246 
 0x6055e3e0: Frimagedisplay.mui V20.296 
 0x6055e160: Imagedisplay.mui V20.244 
 0x6055e2a0: Pendisplay.mui V20.247 
 0x6055e0c0: String.mui V20.105 
 0x6274badc: xpkSQSH.library V1.10 (Legacy) 
 0x60a148cc: xpkSMPL.library V1.0 (Legacy) 
 0x60f1603c: xpkSHRI.library V2.2 (Legacy) 
 0x60f1b64c: xpkRLEN.library V1.3 (Legacy) 
 0x60a1484c: xpkRAKE.library V1.7 (Legacy) 
 0x60f1b52c: xpkNUKE.library V1.7 (Legacy) 
 0x60a147cc: xpkNONE.library V1.4 (Legacy) 
 0x60ca2e9c: xpkMASH.library V1.98 (Legacy) 
 0x60a145a8: xpkLZMA.library V52.2 
 0x60ca2cf2: xpkIMPL.library V1.0 (Legacy) 
 0x60f1b22c: xpkIDEA.library V1.3 (Legacy) 
 0x60f1b16c: xpkHUFF.library V0.64 (Legacy) 
 0x60a146cc: xpkHFMN.library V1.36 (Legacy) 
 0x60a1464c: xpkFRLE.library V1.0 (Legacy) 
 0x60d99f9c: xpkFEAL.library V1.5 (Legacy) 
 0x60d99edc: xpkFAST.library V1.10 (Legacy) 
 0x60d99e1c: xpkENCO.library V1.3 (Legacy) 
 0x60d99d5c: xpkDUKE.library V1.6 (Legacy) 
 0x60a121ac: xpkDLTA.library V0.1 (Legacy) 
 0x6274b9ec: xpkCBR0.library V1.0 (Legacy) 
 0x60c097cc: xpkBZP2.library V1.7 
 0x60c09684: xpkmaster.library V5.2 
 0x612e8a5c: xadmaster.library V13.1 
 0x6107fe10: Gauge.mui V20.276 
 0x6107fc30: TextEditor.mcc V15.41 
 0x6107faf0: NBalance.mcc V15.16 
 0x6107f9b0: NListtree.mcc V18.42 
 0x6107f7d0: NFloattext.mcc V19.71 
 0x6107f690: NListview.mcc V19.90 
 0x6107f550: NList.mcc V20.135 
 0x6107f0f0: BetterString.mcc V11.25 
 0x6107f2d0: TheButton.mcc V26.12 
 0x6107f190: TheBarVirt.mcc V26.12 
 0x6107f050: TheBar.mcc V26.12 
 0x60a24b48: amissl_v097g.library V3.7 
 0x613efcd8: amisslmaster.library V3.7 
 0x60a92f70: expat.library V53.4 
 0x6160868c: codesets.library V6.15 
 0x6fc9e630: muimaster.library V20.6038 
 0x6106f548: SubDock.docky V53.1 
 0x613eff40: palette.gadget V53.6 
 0x6114d9b0: texteditor.gadget V53.20 
 0x61554648: radiobutton.gadget V53.9 
 0x613ef400: slider.gadget V53.12 
 0x613ef860: getfont.gadget V53.9 
 0x613ef7c0: arexx.class V53.4 
 0x613ef720: getfile.gadget V53.11 
 0x611fd760: requester.class V53.18 
 0x613ef0e0: space.gadget V53.6 
 0x6fc9ff30: bitmap.image V53.9 
 0x6fc9f990: integer.gadget V53.10 
 0x61554288: clicktab.gadget V53.40 
 0x62be0758: chooser.gadget V53.19 
 0x627cc340: penmap.image V53.5 
 0x627cc480: checkbox.gadget V53.9 
 0x61b68654: device.audio V6.2 
 0x61b669f8: listbrowser.gadget V53.56 
 0x6fc9dc50: string.gadget V53.17 
 0x6fc9f7b0: scroller.gadget V53.14 
 0x628269d8: sm502.audio V6.5 
 0x62ccfcd8: filesave.audio V6.5 
 0x62a62aa8: emulation.library V53.2 
 0x62abbaa4: usergroup.library V4.30 
 0x629cb490: bsdsocket.library V4.307 
 0x62ad2d30: mathieeedoubbas.library V52.1 
 0x62ad24bc: hid.usbfd V53.8 
 0x62a8a65c: textclip.library V53.1 
 0x62ab85f0: button.gadget V53.16 
 0x62ab8690: glyph.image V53.3 
 0x62ad1830: window.class V53.54 
 0x62be18c8: popupmenu.class V53.2 
 0x629e8098: popupmenu.library V53.11 
 0x62ab8370: label.image V53.12 
 0x6ffa8c78: layout.gadget V53.21 
 0x62be17d0: bevel.image V53.6 
 0x62ab8190: drawlist.image V53.3 
 0x6fd415d0: gif.datatype V53.4 
 0x62bf6f40: png.datatype V53.10 
 0x62be1560: z.library V53.1 
 0x62bf6d60: ilbm.datatype V53.3 
 0x62c73484: picture.datatype V53.6 
 0x62b23e44: asl.library V53.46 
 0x62cc1c48: timezone.library V53.6 
 0x62be1308: application.library V53.12 
 0x62be015c: ft2.library V53.2 
 0x6ff8008c: workbench.library V53.52 
 0x6ff5d6cc: commodities.library V53.1 
 0x62cb5140: datatypes.library V53.4 
 0x62c72120: Picasso96API.library V54.2 
 0x62c6f9f0: gadtools.library V53.6 
 0x6fd15d54: png.iconmodule V53.1 
 0x62da18cc: icon.library V53.13 
 0x62e2c6c8: version.library V53.11 
 0x62c6f2d0: iffparse.library V53.1 
 0x6ff17ccc: locale.library V53.6 
 0x6ffda7ac: diskfont.library V53.5 
 0x6ff60da8: petunia.library V53.4 
 0x6ff60b68: diskcache.library V3.30 
 0x6fd31690: dos.library V53.138 
 0x6fdfa094: usbprivate.library V53.12 
 0x6ff5f3bc: massstorage.usbfd V53.22 
 0x6ff5f328: bootkeyboard.usbfd V52.3 
 0x6ff5f2a8: bootmouse.usbfd V53.1 
 0x6ffa8e3c: hub.usbfd V53.10 
 0x6ffa8d8c: usbresource.library V53.12 
 0x6ffd95b8: hunk.library V53.4 
 0x6fefadd4: elf.library V53.19 
 0x6feec4d0: intuition.library V53.42 
 0x6ffbc150: rtg.library V54.5 
 0x6fefda20: RadeonHD.chip V0.55 
 0x6fefd9a4: PCIGraphics.card V53.6 
 0x6feff7a0: keymap.library V53.5 
 0x6ff01c30: layers.library V53.7 
 0x6ff16420: graphics.library V54.6 
 0x6ffd9184: nonvolatile.library V53.5 
 0x6ff002b8: newlib.library V53.27 
 0x6fefb1ac: utility.library V53.4 
 0x6feff0a8: expansion.library V53.1 
 0x62abe1fe: rexxsyslib.library V53.4 (Legacy) 

Tasks 
 YAM (Crashed) 
  Stack: 0x60620004 - 0x6062fffc, pointer @ 0x6062ec70 (Cookie OK) 
  Signals: SigRec 0x00000020, SigWait 0x60400100 
  State: Process (Crashed)

**Comment by tboeckel** [comment]
**Originally on 2013-07-10 08:27:03 +0200**

___
Ticket #403 covers the same issue.

Please don't put crashlogs in the normal bug description but add them as attachment next time. This makes reading the ticket much easier.
