### ISSUE TITLE
YAM in German: Shortcut Amiga-C for "Ansicht" is very annoying

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#407]
**Originally by _mrupp@gmx.ch_ on 2013-07-21 12:48:28 +0200**

___
Hi there

If you run YAM in german, there's the shortcut Amiga-C for "Ansicht" ("View") which interferes with the standard "Copy" shortcut. Therefor it makes it impossible to copy any text out of the preview window to the clipboard because Amiga-C invokes changing the current view. That's very annoying, please change that shortcut for the next version.

Thanks
Michael

**Comment by jens-maus** [comment]
**Originally on 2013-07-21 12:53:57 +0200**

___
Sorry, but I am not able to reproduce this problem. Here in the WriteWindow Amiga+C is properly mapped to Amiga+C and there isn't any Amiga-C shortcut assigned to any "View" submenu entry in the write window. Or which window in YAM are you referring to?

**Comment by jens-maus** [comment]
**Originally by _mrupp@gmx.ch_ on 2013-07-21 14:24:48 +0200**

___
I am referring to main window. I'd like to be able to copy text from the preview of an email.

**Comment by jens-maus** [comment]
**Originally on 2013-07-21 14:30:19 +0200**

___
Sorry, but this also seems to work here. What I tried was

1. select some text in preview pane
2. Press Amiga+C
3. go to a write window and paste the text via Amiga+V

This perfectly works. However, please make sure that the text you selected is correctly highlighted and that the preview pane is currently active when you press Amiga+C. Please also note that there is no "Ansicht/View" submenu in the main window as you explained in your original post. In addition, please state which system you are using when trying to reproduce the problem.

**Comment by jens-maus** [comment]
**Originally by _mrupp@gmx.ch_ on 2013-07-22 18:35:06 +0200**

___
Alright, I'm attaching a screenshot, that explains it a lot better.
Oops, that didn't work (no attachments possible, pop on empty list).
And I can't link to it as it's alway reported as spam... aarrghh...

I'll add some spaced, maybe it works then:
home . datacomm . ch / mrupp / transfer / YAM . png

**Comment by jens-maus** [comment]
**Originally on 2013-07-22 18:38:16 +0200**

___
Ah, ok. got it. I'll test that at home ASAP and report back. Now it is more clear. you meant the "Ansicht" label beside the QuickSearchBar and not in the "Menu" as you described in your initial report.

Regarding not being able to attach an image, please make sure you create yourself an account here at yam.ch and login previous to your reports because then trac will allow you to attach images and also immediately post replies without having us to acknowledge them.

**Comment by jens-maus** [comment]
**Originally on 2013-07-22 22:13:27 +0200**

___
I have now checked how YAM behaves regarding the "Ansicht" shortcut (C) in the YAM main window. However, here on OS4 Amiga+C does not switch the content of the cycle gadget but indeed copy the currently selected text to the clipboard. Instead just pressing C without Amiga perfectly switches the cycle gadget. Now, of course, the question comes up why in your case Amiga+C is catched.

To answer that question, please state which operating system and MUI version you are using so that we can investigate further.

**Comment by tboeckel** [comment]
**Originally on 2013-07-23 08:27:56 +0200**

___
I can confirm that RAmiga+C copies the selected text while C and Shift+C cycle through the various quick filters. This works even with MUI 3.8.

**Comment by jens-maus** [comment]
**Originally by _mrupp@gmx.ch_ on 2013-07-24 15:44:24 +0200**

___
I'm using the 68k version on WinUAE running AmigaOS 3.9. The MUI classes seem to be the latest version (0.166), YAM doesn't report any updates when asked. Here pressing C or shift C or RAmiga-C does invoke changing the view cycle (sorry I didn't mention that to be a cycle in my initial report, but I didn't mention the menu either).

But you're right, with the OS4 version this doesn't happen, so it's maybe just the 68k version or even the combination mit WinUAE.

**Comment by tboeckel** [comment]
**Originally on 2013-07-24 16:18:13 +0200**

___
As I wrote above already my WinUAE system does not expose this issue. Do you have any patches running which might interfere with Intuition's menu handling?

Usually an object with a shortcut will react on the key itself, Shift+key and RAmiga+key. If a menu with the same shortcut exists the corresponding RAmiga+key press will be handled by Intuition already and neither the MUI application nor the object will ever see this key press. This is why the cycle object should react on plain "C" and Shift+"C" only, since RAmiga+"C" will be swallowed by the menu already.

**Comment by jens-maus** [comment]
**Originally by _mrupp@gmx.ch_ on 2013-07-25 23:57:17 +0200**

___
I can't think of any patches that could cause this. But does it really matter? It's a matter of fact that my system behaves like this and that this is (I'm sure you agree) quite annoying. I mean, even if we find out about a patch (or something else) that causes this, we can be quite sure that other users are affected as well. I assume it's really not such a big thing to change the shortcut in the german catalog file. Of course it would be interesting to find out the cause but it's also a bit academic.

PLEASE, just change the shortcut and be done with. I (and probably other WinUAE users of the german version, too) would be very grateful.

Keep up the good work, I really like YAM a lot!

**Comment by jens-maus** [comment]
**Originally on 2013-07-26 00:14:31 +0200**

___
I am sorry Michael, but this is not how we address things usually. As the root of the problem doesn't actually originate from YAM but from a faulty component in your  WinUAE/MUI installation we can't simply patch YAM or the catalog to get rid of the problem.

Just removing/changing the shortcut will just hide/workaround the original problem and there will be certainly other situations in YAM or any other MUI application where you will run into the same problem sooner or later. It is a matter of fact that your MUI or WinUAE setup seems to be incorrect or broken and that this causes the problem you are outlining here. It would simply be wrong to patch YAM just because of an obvious problem in a third-party component which we haven't even fully understood.

In addition, there really isn't any shortcut combination in the YAM main window left which we could use without interfering with any other shortcut already taken. So, I am really sorry, but if you are not interested in finding the real root of the problem and thus are not wanting to help us nailing it down, I feel there is nothing we can do about it. We will definitly not workaround the problem just because a single WinUAE/MUI installation behaves incorrect.

So please help us in understanding the problem and there might be chances that we can actually help you fixing your WinUAE installation.

**Comment by tboeckel** [comment]
**Originally on 2013-07-26 09:15:37 +0200**

___
I can only second Jens' statement. If RAmiga+C does not work as expected then any other shortcut will not work either, at least it will not trigger the corresponding menu in your case.

It is not YAM's task to work around the negative effects of certain patches.

The only real workaround we could offer is to remove the shortcut from the "Ansicht" label completely. But as Jens already pointed out this will only hide this effect or delay it to some time in the future. So better let us find the real reason now instead of "patching" it away for the moment. Just try to disable any patches that your WinUAE system might run during executing S:Startup-Sequence and SYS:WBStartup and see if YAM behaves correctly then. If it does then enable single patches again one by one until YAM misbehaves again.

**Comment by jens-maus** [comment]
**Originally by _mrupp@gmx.ch_ on 2013-07-26 10:54:17 +0200**

___
Alright, alright, I'll see want I can find out...

**Comment by jens-maus** [comment]
**Originally by _trac-robot_ on 2013-08-10 05:35:14 +0200**

___
This ticket was closed automatically by the system.  It was previously set to a Pending status and hasn't been updated within 14 days.
