### ISSUE TITLE
KillDuplicates.yam cause DSI and crash

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#409]
**Originally by _AmigaPhil@scarlet.be_ on 2013-08-21 22:15:35 +0200**

___
## Summary
After trying to delete duplicates in my incoming folder (near 3000 messages) using the ARexx script KillDuplicates.yam, GrimReaper appears with a DSI error (see crashlog attached).  Ignoring DSI makes Yam to hang and the system very unstable.
## Steps to reproduce
 1. Execute KillDuplicates.yam
 2.

## Notes
AmigaOne X1000, OS 4.1u6

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-08-21 22:16:13 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-08-21_20-44-47.txt`](https://yam.ch/attachments/409/Crashlog_YAM_2013-08-21_20-44-47.txt) (28.8 KiB)
GrimReaper crashlog

**Comment by tboeckel** [comment]
**Originally on 2013-08-27 21:08:21 +0200**

___
Is it possible you ran out of memory while script was collecting duplicate mails? This is the only reason for this crash that I can think of as there might be a missing a check for a failed memory allocation.

**Comment by tboeckel** [comment]
**Originally on 2013-08-27 21:45:34 +0200**

___
In (600c17d):
 * Rexx.c, rexx/misc: check the allocation of the optional structure and return an error upon failure. This refs #409.

**Comment by tboeckel** [comment]
**Originally on 2013-08-27 21:48:15 +0200**

___
Please check the script again with the next nightly build. If not enough memory is the true cause of the crash then this should be fixed with the next build and the script should return an error in case of a low memory situation.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-08-27 21:50:41 +0200**

___
I would have thought about running out of memory as well, but...
I have 2Gb of RAM, and all the (nearly) 3000 messages compiled as a mbox file are "only" around 32Mb.

I'll try the next nightly build (after midnight IIRC ?).

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-08-28 21:16:17 +0200**

___
**Attachment added:** [`Crashlog_YAM.debug_2013-08-28_17-19-17.txt`](https://yam.ch/attachments/409/Crashlog_YAM.debug_2013-08-28_17-19-17.txt) (29.4 KiB)
Nightly build crashlog

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-08-28 21:16:55 +0200**

___
I've tested it with the nightly build from 28/8/2013.
Again, DSI, Yam hang, and system unstable (and finally freeze).

I've narrowed the problem a bit.  It is caused by the command MAILINFO clashing with some messages.
I've spotted one of those messages.  It was bulk sent by my then ISP.  It has no To: field, and the From: field does not contain a valid e-mail address.

**Comment by jens-maus** [comment]
**Originally on 2013-08-28 21:20:21 +0200**

___
Can you please attach a copy of that email if that's possible. It would help us investigating the problem much easier.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-08-28 22:02:15 +0200**

___
**Attachment added:** [`Modification.eml`](https://yam.ch/attachments/409/Modification.eml) (1.4 KiB)
Example of an e-mail causing MAILINFO to crash

**Comment by jens-maus** [comment]
**Originally on 2013-08-29 01:45:46 +0200**

___
In (276934d):
 * rexx/mailinfo.c: fixed a crash bug where strdup() was used on a NULL pointer
  if a mail didn't contain any messageID. This closes #409.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-08-29 21:54:32 +0200**

___
Thank you for having fixed this bug very quickly.

As now MAILINFO can return NULL for MSGID, I've slightly modified the ARexx script KillDuplicates.yam to handle this.
If there is no message-id, the date is used instead as identifier for the message.

I'm attaching the script here.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-08-29 21:55:52 +0200**

___
**Attachment added:** [`KillDuplicates.yam`](https://yam.ch/attachments/409/KillDuplicates.yam) (0.8 KiB)
KillDuplicates.yam now takes care of missing message-id

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 23:00:34 +0100**

___
**Release Note:**
fixed a bug where the MAILINFO ARexx command caused a crash if the mail in question contained no message ID.
