### ISSUE TITLE
Remember selection choice across sessions.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#410]
**Originally by _AmigaPhil@scarlet.be_ on 2013-08-21 22:34:21 +0200**

___
## Problem
Messages show selection is lost when closing Yam.
## Analysis
For example, if I select show New (or Unread) messages and then quit Yam, I would like that next time I start Yam, it will open on the Incoming folder, showing New (or Unread) messages as well.  (Same behaviour as with Evolution.)
## Enhancement recommendation

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-08-29 18:31:51 +0200**

___
Related to #284
Both tickets can be merged, if possible.

**Comment by tboeckel** [comment]
**Originally on 2013-08-29 19:32:42 +0200**

___
I suppose you are talking about the "View" cycle gadget above the mail list, correct? If yes then this settings should be covered by #284.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-08-29 21:47:16 +0200**

___
Yes, that's it.

**Comment by tboeckel** [comment]
**Originally on 2013-11-05 19:47:43 +0100**

___
In (6ab8317):
 * YAM.c, mui/StartupQuitConfigPage.c, mui/YAMApplication.c: implemented a new option to trigger a snapshot action on all alive windows and to save the layout/state of certain groups and objects. This closes #410.

**Comment by tboeckel** [comment]
**Originally on 2013-11-05 19:56:56 +0100**

___
**Release Note:**
Implemented a new option to trigger a snapshot action on all alive windows and to save the layout/state of certain groups and objects.
