### ISSUE TITLE
Display search doesn't stop and YAM must be quit to abort

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#412]
**Originally by _hypexed@yahoo.com.au_ on 2013-08-25 16:28:43 +0200**

___
## Summary
I was using the display search gadget to the ritght above the email list. I first did a search for Subject then swiitched to Body. It started searching through the mails. I pressed "X" to stop it but it just kept reading. I had to quit to stop it and it took some convincing! I had to press the close gadget a number of times before it too kany notice.

## Steps to reproduce
 1. Use display search gadget to search for a subject.
 2. Swiitch to body and press "X" to stop.

It's easier to see it with a big folder full of mails.

## Expected results
To stop searching.

## Actual results
It keeps searching is hard to quit!

**Comment by tboeckel** [comment]
**Originally on 2013-08-26 09:23:10 +0200**

___
In (f30634f):
 * mui/QuickSearchBar.c: any edit operation in the quick search bar will now abort a search operation in progress. This closes #412.

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 23:04:23 +0100**

___
**Release Note:**
fixed a bug so that any edit operation in the quick search bar will now abort a search operation in progress.
