### ISSUE TITLE
YAM name and version to be showed on titlebar

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#414]
**Originally by _s.hawamdeh@teletu.it_ on 2013-08-26 10:19:03 +0200**

___
In most Amiga programs the name of the application is more or less always showed on the Workbench titlebar, for example in MUI OWB we have:

Origyn Web Browser 1.9 (06.08.2012)

However actually YAM print nothing in titlebar, so no information at all
That means that when YAM is opened you don't have any reference that might be important to determinate, for example which version of YAM you are using, the date of the binary and so on

(Just see the OWB name + version + date above) 

Using a proper reference on titlebar might be usefull also to determinate the nighty build versions used eventually

So, how about adding that ? :-)

**Comment by jens-maus** [comment]
**Originally on 2013-08-26 12:57:24 +0200**

___
Is there really currently nothing shown on the wb titlebar when the yam window is active? Usually mui should take care of that. In additon, please note that showing the name and version should be enough. Nobody really cares about the date or svn revision in the titlebar...

**Comment by tboeckel** [comment]
**Originally on 2013-08-26 13:37:40 +0200**

___
If the main window's title is really completely empty, then there is something going wrong. YAM will set up the window's title as "YAM <version>  -  User: <name>". The version includes the appendix "-dev" for the nightly development builds. As such the title already contains all the basic information you are asking for. The startup window also shows the compile date. If you need more detailed information then you need to open the About window.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2013-08-26 16:34:52 +0200**

___
@thboeckel

You are right about that, at the end full info are already availible in about window and in version too, but i'm not sure about leave the titlebar blank.

Given that pratically all MUI or ReAction programs supports it, i guess that filling the titlebar with a proper string it's an AmigaOS standard ..

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2013-08-26 16:39:08 +0200**

___
@damato

> Is there really currently nothing shown on the wb titlebar when
> the yam window is active?

Yes exactly, actually even if the YAM window is active nothing is showed on titlebar !

> Usually mui should take care of that.

Mmm not automatically for what i can understand, programmers should add it in their program code

**Comment by jens-maus** [comment]
**Originally on 2013-08-27 14:40:17 +0200**

___
After having rediscussed/rethought about your report I feel we should implement it to make it more clear that the active window belongs to YAM.

**Comment by jens-maus** [comment]
**Originally on 2013-08-27 14:44:28 +0200**

___
In (7147346):
 * YAM_MA.c, MUIObjects.c, misc: implemented use of MUIA_Window_ScreenTitle for
  all windows created by YAM. This will change the title of the screen yam is
  running on as soon as a window related to YAM is active. This should improve
  recognition of the currently active window as the screen titlebar will then
  automatically refer to YAM and thus make it possible that a user identifies
  by looking at the screen title bar which application is the currently active
  one. This implements and closes #414.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2013-08-27 16:35:07 +0200**

___
Thanks to have accepting (and quickly fixed) my ticket :-)

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 22:35:23 +0100**

___
**Release Note:**
when opening a new window YAM will now set the title of a screen to the same title as well. This improves recognition of the currently active window as the screen titlebar will then automatically refer to YAM and thus make it possible that a user identifies
by looking at the screen title bar which application is the currently active one.
