### ISSUE TITLE
Crash while checking new mail on single account

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#415]
**Originally by _amigo1one@yahoo.com.au_ on 2013-08-26 10:58:07 +0200**

___
## Summary
GrimReaper while checking for new mail on single accont out of 17 accounts. Only 10 accounts active. 60 active filters.

## Steps to reproduce
 1. select menu "Folder/Check single account/name of the account
 2. wait for YAM to open the "Transfer in progress" and subsequently the "Mail transfer from xxxx" window
3. press the "Start" button on the latter window.

## Expected results
Normal Mail Transfer

## Actual results
4. GrimReaper appears
## Notes
here I can reproduce each time.
Sam440ep-Flex 1GB RAM, Radeon 9250, 160GB HD, Partition File System SFS2, AmigaOS 4.1 update 6 (updated to latest update), YAM 2.8p1

I have a crash-log to attach

**Comment by jens-maus** [comment]
**Originally by _amigo1one@yahoo.com.au_ on 2013-08-26 10:48:56 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-08-26_10-34-00.txt`](https://yam.ch/attachments/415/Crashlog_YAM_2013-08-26_10-34-00.txt) (26.6 KiB)
GrimReaper Crash-log

**Comment by tboeckel** [comment]
**Originally on 2013-08-26 11:14:40 +0200**

___
Do you have any kind of ARexx script running? The crashlog points to the MAILINFO command.

**Comment by jens-maus** [comment]
**Originally on 2013-08-29 07:53:33 +0200**

___
In the meantime we received another bug report regarding the MAILINFO command and fixed it already. Thus, this ticket seems to be a duplicate of ticket #409. In addition, the both crash log look essentially the same, so there are chances that the bug you reported have already been fixed in the meantime. So please either test with a nightly build or wait until YAM 2.9 have been released.
