### ISSUE TITLE
Nightly builds crash (at startup)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#416]
**Originally by _s.hawamdeh@teletu.it_ on 2013-09-02 07:20:15 +0200**

___
On my system i can't start YAM 2.9-dev anymore, the latest 2 or 3 nightly builds crash badly at startup (during the loading the splash screen)

The stack trace point the error at:
m_FolderRequestListtree_OM_NEW()+0x124 ( section 2 @ 0xA8028 )

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2013-09-02 07:20:48 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-09-02_07-38-30.txt`](https://yam.ch/attachments/416/Crashlog_YAM_2013-09-02_07-38-30.txt) (27.2 KiB)
DSI crash at startup

**Comment by tboeckel** [comment]
**Originally on 2013-09-02 09:27:33 +0200**

___
In (b660a7d):
 * mui/FolderRequestListtree.c: added a NULL pointer check before adding the global folder tree notification. This closes #416.

**Comment by tboeckel** [comment]
**Originally on 2013-09-03 09:36:38 +0200**

___
In (96f9a8b):
 * mui/FiltersConfigPage.c: don't ghost inactive GUI elements in the constructor as this requires a valid application pointer. This really closes #416.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2013-09-04 12:50:49 +0200**

___
Thore, the issue is not fixed yet !

At startup it automatically opens the prefs window and then it crash, see log attached

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2013-09-04 12:53:29 +0200**

___
Ops, can't edit the post ?.. Then see the log below:


Symbol info:
Instruction pointer 0x6F9F8E2C belongs to module "YAM" (PowerPC) 
Symbol: IsValidConfig + 0xBC in section 2 offset 0x00064E0C

Stack trace:
    IsValidConfig()+0xbc (section 2 @ 0x64E0C)
    ValidateConfig()+0x4e4 (section 2 @ 0x6535C)
    InitAfterLogin()+0xcc ( section 2 @ 0xA78 )
    main()+0x1140 (section 2 @ 0x5CBC)
    native kernel module newlib.library.kmod+0x00002094
    native kernel module newlib.library.kmod+0x00002d3c
    native kernel module newlib.library.kmod+0x00002eb8
    _start()+0x170 (section 2 @ 0x170)
    native kernel module dos.library.kmod+0x00022d9c
    native kernel module kernel+0x0003bd20
    native kernel module kernel+0x0003bda0
    

PPC disassembly:
 6f9f8e24: 81490150   lwz               r10,336(r9)
 6f9f8e28: 83a90004   lwz               r29,4(r9)
*6f9f8e2c: 83ca0000   lwz               r30,0(r10)
 6f9f8e30: 48007c2d   bl                0x6FA00A5C
 6f9f8e34: 7c7f1b78   mr                r31,r3

System information:

CPU 
 Model: AMCC PPC440EP V1.3 
 CPU speed: 799 MHz 
 FSB speed: 133 MHz 
 Extensions:  

Machine 
 Machine name: Sam440EP 
 Memory: 1048576 KB 
 Extensions: bus.pci

**Comment by tboeckel** [comment]
**Originally on 2013-09-04 15:53:49 +0200**

___
Replying to samo79:
> Ops, can't edit the post ?.. Then see the log below:

Please attach the complete log and not just the part of which you think that it is sufficient.

**Comment by tboeckel** [comment]
**Originally on 2013-09-04 16:04:29 +0200**

___
In (8d4fed3):
 * Config.c: added a NULL pointer check for a valid main window pointer. This refs #416.

**Comment by tboeckel** [comment]
**Originally on 2013-09-04 16:06:12 +0200**

___
The latest change should fix this crash.

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 23:26:51 +0100**

___
**Release Note:**
fixed a crash bug by adding a NULL pointer check for a valid main window pointer.
