### ISSUE TITLE
YAM crash when editing a Folder

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#417]
**Originally by _opionline@yahoo.de_ on 2013-09-06 12:31:36 +0200**

___
YAM crash when editing a Folder. To reproduce do the follow:
1. Choose Edit... in the Folder list
2. Click on "OK" in the "Folder settings" Window 

3. I get the follow hit from MuForce:

```
LONG READ from 00000148                        PC: 09D6FD5A
USP : 09BF860C SR: 0004  (U0)(-)(-)  TCB: 09BE2980
Data: 00000000 0000000C 80000000 40000000 00000000 00000000 FFFFFFFF FFFFFFFF
Addr: 09BF862C 00000148 0A5657A0 09BF8680 09B1DFF8 09B21710 09D6EE8C 080025E0
Stck: 09D7227C 0A5658E8 09D72216 09B21710 09D6E2F0 00000000 09D6EE8C 0A5658E8
Stck: 00000148 09D6E334 09BF8680 09B1DFF8 09D72272 0A5658E8 0A809908 09D72216
Stck: 0A8099EC 0A5B2354 0A565DA0 09D6E2F0 0A809908 0A809994 09D6E334 09BF8780
Stck: 09B1DFF8 09D9069E 0A809908 09D7CF78 0A809908 80422A1A 09BF8780 FFFFFFFF
Stck: FFFFFFFF 0A8099EC 0A8099D0 09BF8780 09D7DC9C 80000000 40000000 00000000
Stck: 02000000 FFFFFFFF 20000000 0A8099D0 09BF8780 0A8099D0 08000B74 80000000
Stck: 0A5B2354 09BF8780 0A8099EC 01000000 02000000 09B21470 09BF87C0 0A8099D0
Stck: 00000000 00003759 00FBC682 08000B74 083FF55C 085287B0 00400000 09E3C99C
Stck: 09D78D9A 80000000 40000000 01000000 09E3C99C 09BF8854 09E3CE2A 09D7A166
Stck: 09E3C99C 80000000 01000000 02000000 00800000 04000000 09E3C980 09D79B24
Stck: 0A2B9A6C 00000001 FFFF7FFF 00000000 00000000 09E3CE2A 09E3C9BC 00000000
Stck: FFFF7FFF 09E69982 09B21438 09BF8854 09E3C980 09E3C318 09E3C314 05000000
Stck: 00000A5B 24000020 00000008 00E88000 0A5B2354 00720148 431D8684 00048C0B
Stck: 0A5B2354 0A5B1FB4 0000FFFF FFFFFFFF FFFF7FFF 0000FFFF 09BF8780 FFFFFFFF
Stck: 0000FFFF FFFFFFFF 0A80C40C 00000000 00000000 00000000 00000000 09D6EB26
Stck: 00004000 00000000 0A331AD2 09E3C980 00000001 0A331A18 09B21438 09E3C980
Stck: 09BF8854 0A2B9F94 09E3C148 09E3C980 09BF8854 09E3C980 09D6FB8C 09BF8B38
Stck: 08000B74 0A331AD2 00000000 08000B74 0A331510 09E3C148 09E3C980 09BF8854
Stck: 0A201290 09E3C980 80423BA6 09BF888E 00010000 00000001 00000001 026F5887
Stck: 026F89CD 0A1FCDCC 0A32F1D4 00000014 09BF8CE8 08000B74 026F9188 000093C9
----> 09D6FD5A - "LIBS:muimaster.library"  Hunk 0000 Offset 00005B5A
----> 09D7227C - "LIBS:muimaster.library"  Hunk 0000 Offset 0000807C
----> 09D72216 - "LIBS:muimaster.library"  Hunk 0000 Offset 00008016
----> 09D6E2F0 - "LIBS:muimaster.library"  Hunk 0000 Offset 000040F0
----> 09D6EE8C - "LIBS:muimaster.library"  Hunk 0000 Offset 00004C8C
----> 09D6E334 - "LIBS:muimaster.library"  Hunk 0000 Offset 00004134
----> 09B1DFF8 - "LIBS:muimaster.library"  Hunk 0001 Offset 00000000
----> 09D72272 - "LIBS:muimaster.library"  Hunk 0000 Offset 00008072
----> 09D72216 - "LIBS:muimaster.library"  Hunk 0000 Offset 00008016
----> 09D6E2F0 - "LIBS:muimaster.library"  Hunk 0000 Offset 000040F0
----> 09D6E334 - "LIBS:muimaster.library"  Hunk 0000 Offset 00004134
----> 09B1DFF8 - "LIBS:muimaster.library"  Hunk 0001 Offset 00000000
----> 09D9069E - "LIBS:muimaster.library"  Hunk 0000 Offset 0002649E
----> 09D7CF78 - "LIBS:muimaster.library"  Hunk 0000 Offset 00012D78
----> 09D7DC9C - "LIBS:muimaster.library"  Hunk 0000 Offset 00013A9C
----> 00FBC682 - "ROM - timer 39.4 (29.7.92)"  Hunk 0000 Offset 000006B2
----> 09D78D9A - "LIBS:muimaster.library"  Hunk 0000 Offset 0000EB9A
----> 09D7A166 - "LIBS:muimaster.library"  Hunk 0000 Offset 0000FF66
----> 09D79B24 - "LIBS:muimaster.library"  Hunk 0000 Offset 0000F924
----> 0A2B9A6C - "yam:yam"  Hunk 0000 Offset 000BCC9C
----> 09D6EB26 - "LIBS:muimaster.library"  Hunk 0000 Offset 00004926
----> 0A331AD2 - "yam:yam"  Hunk 0000 Offset 00134D02
----> 0A331A18 - "yam:yam"  Hunk 0000 Offset 00134C48
----> 0A2B9F94 - "yam:yam"  Hunk 0000 Offset 000BD1C4
----> 09D6FB8C - "LIBS:muimaster.library"  Hunk 0000 Offset 0000598C
----> 0A331AD2 - "yam:yam"  Hunk 0000 Offset 00134D02
----> 0A331510 - "yam:yam"  Hunk 0000 Offset 00134740
----> 0A201290 - "yam:yam"  Hunk 0000 Offset 000044C0
----> 0A1FCDCC - "yam:yam"  Hunk 0000 Offset FFFFFFFC
----> 0A32F1D4 - "yam:yam"  Hunk 0000 Offset 00132404
PC-8: 2F004EB9 09D90B56 221F4A80 67062040 20C12008 4E752021 4EF909D9 0C782250
PC *: 20116708 20802009 720CD081 4E755888 20280004 21490004 C18848D1 01012089
09d6fd3a :  2f00                       move.l d0,-(a7)
09d6fd3c :  4eb9 09d9 0b56             jsr $9d90b56
09d6fd42 :  221f                       move.l (a7)+,d1
09d6fd44 :  4a80                       tst.l d0
09d6fd46 :  6706                       beq.s $9d6fd4e
09d6fd48 :  2040                       movea.l d0,a0
09d6fd4a :  20c1                       move.l d1,(a0)+
09d6fd4c :  2008                       move.l a0,d0
09d6fd4e :  4e75                       rts
09d6fd50 :  2021                       move.l -(a1),d0
09d6fd52 :  4ef9 09d9 0c78             jmp $9d90c78
09d6fd58 :  2250                       movea.l (a0),a1
09d6fd5a : *2011                       move.l (a1),d0
09d6fd5c :  6708                       beq.s $9d6fd66
09d6fd5e :  2080                       move.l d0,(a0)
09d6fd60 :  2009                       move.l a1,d0
09d6fd62 :  720c                       moveq.l #$c,d1
09d6fd64 :  d081                       add.l d1,d0
09d6fd66 :  4e75                       rts
09d6fd68 :  5888                       addq.l #$4,a0
09d6fd6a :  2028 0004                  move.l $4(a0),d0
09d6fd6e :  2149 0004                  move.l a1,$4(a0)
09d6fd72 :  c188                       exg.l d0,a0
09d6fd74 :  48d1 0101                  movem.l d0/a0,(a1)
09d6fd78 :  2089                       move.l a1,(a0)
Name: "Background CLI"  CLI: "yam:yam"  
```

BTW: After step 1 the CheckBox "ML-Support" isn't checked and only "Autodetect" is ghosted.
If i click on "ML-Support" then "Autodetect" gets unghostet.
If i click on "ML-Support" again then all Gadgets gets ghostet.
This should be the case when the Wndow opens if ML-Support is disabled for this folder like in my case.

Used Version:
YAM 2.9-dev (04.09.2013)
Copyright (C) 2000-2013 YAM Open Source Team [OS3/m68k, r7024]

My System is still a A2000 - AOS 3.9 BB2

**Comment by tboeckel** [comment]
**Originally on 2013-09-09 08:52:45 +0200**

___
In (d5fe2c9):
 * mui/FolderEditWindow.c: make sure the ML support GUI elements are initially correctly disabled for folders without ML support. This refs #417.

**Comment by tboeckel** [comment]
**Originally on 2013-09-09 14:13:28 +0200**

___
Does this crash happen for all folders or just for specific ones? So far I was not able to reproduce this myself.

BTW, it would be nice if you could attach crash logs as files instead of making them part of the issue description text.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-09-09 15:35:22 +0200**

___
It seem it happens with all folders. I just tested at least 10 folders including the default incoming and outgoing folders.
I download the debug version, depack and start this version in ram without a config and without a YAM: assign.
The hit happen here too. I attach a sashimi.out file with all the debug output after the edit window was open until i click on OK.

BTW: please notice the lines:
"
mui/MainWindow.c:62:indent level less than 0 (-1)
"
Maybe that happen because i click ok in the requester and cancel in the auto opened config window.
With my working installation such lines are not into the debug output.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-09-09 15:36:44 +0200**

___
**Attachment added:** [`sashimi.out.txt`](https://yam.ch/attachments/417/sashimi.out.txt) (43.6 KiB)
YAM started in RAM: without a configuration file

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-09-09 17:04:05 +0200**

___
Additional Info:
I get the Hit also if i clik the cancel gadged but NOT if i click the close gadget of the window.

**Comment by tboeckel** [comment]
**Originally on 2013-09-09 20:18:52 +0200**

___
Replying to opiopi:
> I get the Hit also if i clik the cancel gadged but NOT if i click the close gadget of the window.

That's really strange, because both actions cause **exactly** the same method to be called. Thus the hit must either occur in both cases or never at all.

**Comment by tboeckel** [comment]
**Originally on 2013-09-09 20:40:06 +0200**

___
Ok, I just switched back to MUI 3.8 and now I am able to reproduce this isse. And yes, clicking the close gadget works, but clicking "Cancel" causes hits. Unfortunately I have no idea what might be causing this strange behaviour, because MUI 3.9 and MUI 4.0 are not affected.

**Comment by tboeckel** [comment]
**Originally on 2013-09-09 22:41:35 +0200**

___
In (bade5e2):
 * mui/MainFolderListtree.c: defer the disposing of the folder edit window  until the notification has finished completely. Since the method to close the window is called synchronously from the notification handling the window must not be disposed immediately as this would "pull out the rug" from under the window's feet while it is still alive. But it is quite strange that only MUI 3.8 falls prey to this effect, while MUI 3.9 and MUI 4.0 seems to be immune. This closes #417.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-09-11 14:08:35 +0200**

___
With the latest nightly build the crash is gone. Thank you very much.

BTW: the AROS builds are missing in the directory http://nightly.yam.ch/latest-dev/

**Comment by tboeckel** [comment]
**Originally on 2013-09-11 15:00:37 +0200**

___
Replying to opiopi:
> BTW: the AROS builds are missing in the directory http://nightly.yam.ch/latest-dev/

Just fixed this. Thanks for the hint.

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 23:28:19 +0100**

___
**Release Note:**
fixed a crash bug when editing a Folder.
