### ISSUE TITLE
Bug when renaming Directory name

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#418]
**Originally by _opionline@yahoo.de_ on 2013-09-06 13:10:45 +0200**

___
If i rename a directory (use Edit.. in the folderlist and change the "Directory name") all seems to work fine.
If i quit YAM and start again then YAM creates the old folder again which is of course empty.
The renamed folder with all mails are still exists in the YAM/Folders/... Directory.

The cause ist that after renaming a folder the ".folder" contain still the old name.
YAM should be so smart and change the ".folder" file so that it contain the new name after renaming.

Used Version:
YAM 2.9-dev (04.09.2013)
Copyright (C) 2000-2013 YAM Open Source Team [OS3/m68k, r7024]

My System is still a A2000 - AOS 3.9 BB2

**Comment by tboeckel** [comment]
**Originally on 2013-09-09 08:31:45 +0200**

___
In (bc7d35a):
 * mui/FolderEditWindow.c: changing a folder's path will now save the global .folders file again to make the change persistent. This closes #418.

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 23:31:55 +0100**

___
**Release Note:**
when changing a folder's path the global .folders file will be immediately saved to make the change persistent.
