### ISSUE TITLE
The trash folder shouldn't be spam checked, IMHO.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#419]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-09 17:52:15 +0200**

___
## Problem
New mails in the trash folder are scanned like other folders (internal spam checker), and mails are moved to the spam folder when there is a match. This does not help when mails are already decided to be deleted. (By default, messages in the trash folder are deleted on Yam exit.)

## Analysis
I made a test with an external spam checker (SpamFryer.yam) configured as a "After download" event. Three mails were spam and immediately moved to the trash folder, as expected.  But just after that process, Yam moved one of these mail from the trash folder to the spam folder.

## Enhancement recommendation
Yam should ignore the trash folder when checking for spam on new messages.

**Comment by tboeckel** [comment]
**Originally on 2013-09-09 20:47:41 +0200**

___
In (73d67e7):
 * YAM_FI.c: mails in the Trash folder are now excluded from the spam filter. This closes #419.

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 23:34:38 +0100**

___
**Release Note:**
mails from the Trash folder are now excluded from the spam filter.
