### ISSUE TITLE
ARexx command for restart

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#42]
**Originally by _anonymous_ on 2010-03-03 23:01:06 +0100**

___
I have a script that automatically gets and sends mail (among other things). I have implemented supplying user information to the script, and the script checks to see if the user information matches the current user. If not the script changes the user.

Currently the only way to do this is by closing YAM and restarting it again. I would like to see an ARexx command that performs the restart with optionally supplied user information. (Would make my script a bit shorter, and quite a bit more elegant...)

**Comment by jens-maus** [comment]
**Originally on 2010-03-09 12:45:56 +0100**

___
makes sense and might be trivial to implement.

**Comment by tboeckel** [comment]
**Originally on 2010-03-10 10:35:18 +0100**

___
In (ae73a38):
 * Rexx.c, rexx/restart.c: implemented the ARexx command "restart". This one
  will do exactly the same as choosing "Restart" from YAM's "Project" menu.
  This closes #42.
