### ISSUE TITLE
ClearFolderMails : DSI after a "After download" event

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#420]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-10 20:14:01 +0200**

___
## Summary
This one is hard to detail as it does not happen all the time.
This started after I created a "After download" ARexx event.  Sometimes, just after the ARexx script (SpamFryer.yam) has finished, the GrimReaper appears.
Last time, Yam was downloading about 12 messages, SpamFryer.yam moved 2 messages to the trash folder, and while returning to Yam -> GR.

## Steps to reproduce
No reproducable at will.

## Notes

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-10 20:14:52 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-09-10_17-25-34.txt`](https://yam.ch/attachments/420/Crashlog_YAM_2013-09-10_17-25-34.txt) (29.0 KiB)

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-10 20:43:48 +0200**

___
Here is another crashlog that just happened.
2 messages downloaded, one messages moved to the trash folder.

Note: I'm confident that the ARexx script is not at fault.  What it tells to Yam last is:
LISTUNFREEZE MAILS
APPNOBUSY


I'll see if I can get another crashlog from the nightly build.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-10 20:44:17 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-09-10_19-26-46.txt`](https://yam.ch/attachments/420/Crashlog_YAM_2013-09-10_19-26-46.txt) (29.4 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-09-11 08:13:23 +0200**

___
Currently I see no reason why anything in ClearFolderMails() should cause a crash.

Please try to reproduce this issue using the debug version of YAM to create a FOLDER log. Details about the debug version can be found in the [FAQ](https://yam.ch/wiki/FAQ/Debugging#BasicsaboutYAMsdebuggingfacilities). Please attach the log to this ticket.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-11 17:58:37 +0200**

___
**Attachment added:** [`debug.log`](https://yam.ch/attachments/420/debug.log) (115.6 KiB)
folder debug log

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-11 18:02:42 +0200**

___
Having seen more DSI in the meantime, I've spotted that GR only appear if a message has previously been moved from incoming to trash.

**Comment by tboeckel** [comment]
**Originally on 2013-09-12 09:23:29 +0200**

___
In (3f823c3):
 * YAM_FI.c, YAM_MA.c, misc: simplified the moving/copying of mails by omitting the additional folder pointer. Since each mail already carries a pointer to the folder it resides in it is quite senseless to specify the mail's source folder explicitly again. Furthermore this changes makes it possible to filter mails from different folders in one go as is it required after receiving mails and some of these mails have been moved from the Incoming folder to somewhere else by a script already (i.e. SpamFryer). This closes #420.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-14 16:37:01 +0200**

___
Unfortunately, it still crash with yesterday's nightly build.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-14 16:38:29 +0200**

___
**Attachment added:** [`debug.2.log`](https://yam.ch/attachments/420/debug.2.log) (128.7 KiB)
debug output - nightly build 13-09-2013

**Comment by tboeckel** [comment]
**Originally on 2013-09-14 19:39:17 +0200**

___
Replying to AmigaPhil:
> Unfortunately, it still crash with yesterday's nightly build.

Your log is not the FOLDER log I asked for, but a simple "nothing" log. Although this log indicates that there are some accesses to invalid strings are happening I really need the information of a FOLDER log for further debugging.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-14 22:05:08 +0200**

___
Here it is, with the folder flag activated.
 
Not much more info before the crash however; but look at the last lines : there is a reference to a "mediatheque.be" folder : I have not and never have had such a folder (!?)

This time, GrimReaper did not mention ClearFolderMails, but <unknown>.
I have not have the chance to save the GR log as the computer froze.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-14 22:06:18 +0200**

___
**Attachment added:** [`debug.3.log`](https://yam.ch/attachments/420/debug.3.log) (115.7 KiB)
Debug log, with FOLDER flag

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-15 18:39:18 +0200**

___
Here is a ARexx script to reproduce the crash easily.
Use it as a "After receiving mails" event.
Send yourself a mail with "yam crash test" as subject to test.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-15 18:40:08 +0200**

___
**Attachment added:** [`crashtest.yam`](https://yam.ch/attachments/420/crashtest.yam) (0.9 KiB)
ARexx test case

**Comment by tboeckel** [comment]
**Originally on 2013-09-15 22:44:02 +0200**

___
Ok, now I am perfectly able to reproduce this issue. Unfortunately I have no solution to this yet, except to not interfere with YAM's mail handling during the download process.

The reason is a bit complicated. Moving a mail from one folder to another will create a new (internal) copy of the mail. The first (old) pointer will finally be freed as it is not needed any longer. But exactly this (old) pointer is the one that will be used during the filter process and this is why YAM is crashing, because it is accessing no longer allocated memory.

I will see what I can do against this issue. Until this is really fixed all I can recommend is not to execute scripts which pull out mails from under YAM's control.

**Comment by tboeckel** [comment]
**Originally on 2013-09-16 09:38:44 +0200**

___
In (7fc5c3b):
 * MailList.c, misc: added a reference counter to each mail. This makes it possible move a mail to a different folder in concurrent processes while still accessing the same mail without accessing invalid or already freed memory. The last referencing instance will finally free the mail if requested. This finally closes #420.

**Comment by tboeckel** [comment]
**Originally on 2013-09-16 09:40:20 +0200**

___
I am quite sure I really fixed this isse this time. Please test this modification with the next nightly build as much as possible to confirm the fix.

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-09-17 19:14:56 +0200**

___
No more crash, thanks !
I'll keep testing for a few days.

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 23:40:26 +0100**

___
**Release Note:**
mail disposal is now protected by a reference counter. This makes it possible to move a mail to a different folder in concurrent processes while still accessing the same mail without accessing invalid or already freed memory. This fixes numerous different potential crash problems.
