### ISSUE TITLE
Ghost the cycle gadget too if SPAM filter is turned off

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#421]
**Originally by _opionline@yahoo.de_ on 2013-09-11 14:12:49 +0200**

___
In Config->SPAM the cycle gadget should be ghosted if the SPAM filter is turned off.

**Comment by tboeckel** [comment]
**Originally on 2013-09-11 15:59:55 +0200**

___
In (2332296):
 * mui/SpamConfigPage.c: disabled all GUI objects in case the spam filter is disabled. This closes #421.

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 23:44:39 +0100**

___
**Release Note:**
All SPAM filter related GUI elements will now be properly disabled if the SPAM filter is completely disabled as well.
