### ISSUE TITLE
Config item "AltReplyBye" isn't loaded/saved correctly

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#422]
**Originally by _opionline@yahoo.de_ on 2013-09-11 14:35:21 +0200**

___
In config->Reply/Forward the Item "Alternative reply phrases" -> "Close" is not saved and loaded correctly.
YAM save the item "MLReplyBye" also as "AltReplyBye" and it seems YAM doesn't load this config item because the Textfield is always empty.

**Comment by tboeckel** [comment]
**Originally on 2013-09-11 16:16:56 +0200**

___
In (22cef85):
 * mui/ReplyForwardConfigPage.c: corrected a variable assignment which caused the alternative leave-taking text to be remain unchanged. This closes #422.

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 23:46:23 +0100**

___
**Release Note:**
fixed a bug where the "Alternative reply phrases" -> "Close" wasn't saved and loaded correctly.
