### ISSUE TITLE
filter condition (Match...) isn't saved correctly

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#423]
**Originally by _opionline@yahoo.de_ on 2013-09-11 16:05:33 +0200**

___
If i add a filter the condition (Match...) isn't saved correctly.
Steps to reproduce:
1. go to config->Filters
2. select a filter and go to the conditions page
3. add a condition using the "+" button
4. fill in your conditions
5. save the config
6. go to config->Filters
7. selet the just changed filter and go to the conditions page
8. look at the textfield - it is empty
9. fill in your conditions again
10. save the config
11. do step 6. and 7. again
12. now the condition is into the textfield

**Comment by tboeckel** [comment]
**Originally on 2013-09-12 08:33:28 +0200**

___
In (251cfa0):
 * mui/FiltersConfigPage.c, mui/SearchControlGroup.c: make sure that all filter conditions are correctly saved when changing filters or config pages. This closes #423.

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 23:50:35 +0100**

___
**Release Note:**
fixed a bug where the filter conditions weren't correctly saved when changing filters or config pages.
