### ISSUE TITLE
version 18/9 crashes when typing new message

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#424]
**Originally by _JDuch@fulladsl.be_ on 2013-09-18 16:02:22 +0200**

___
## Steps to reproduce
 1. At a certain moment when typing (fast?) you get a crash and the corresponding crash repor, or you just get into a dbg session (window opens)
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-09-18 16:05:06 +0200**

___
**Attachment added:** [`Crashlog_YAM.debug_2013-09-18_16-19-32.txt`](https://yam.ch/attachments/424/Crashlog_YAM.debug_2013-09-18_16-19-32.txt) (29.0 KiB)
Crahlog

**Comment by tboeckel** [comment]
**Originally on 2013-09-18 19:23:22 +0200**

___
In (70c589d):
 * MailList.c: allow NULL mail pointers in mail lists. This is required during composing new mails but needs special handing for the reference counter. This closes #424.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 10:43:33 +0100**

___
**Release Note:**
fixed a crash when dealing with NULL mail pointers in mail lists.
