### ISSUE TITLE
Crash whe using "Find" button

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#425]
**Originally by _JDuch@fulladsl.be_ on 2013-09-18 16:13:36 +0200**

___
## Summary
Version 18/9 crashes when i use the Find button
## Steps to reproduce
 1. Use the Find button
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-09-18 16:14:26 +0200**

___
**Attachment added:** [`Crashlog_YAM.debug_2013-09-18_16-33-35.txt`](https://yam.ch/attachments/425/Crashlog_YAM.debug_2013-09-18_16-33-35.txt) (30.1 KiB)
Find Crashlog

**Comment by tboeckel** [comment]
**Originally on 2013-09-18 19:54:50 +0200**

___
In (e202c51):
 * mui/SearchControlGroup.c, misc: use a new attribute to allow/forbid the usage of "Spam" as selectable status instead of accessing the configuration being edited directly as this might not exist. This closes #425.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 10:44:38 +0100**

___
**Release Note:**
fixed a crash bug by using a new attribute to allow/forbid the usage of "Spam" as selectable status instead of accessing the configuration being edited directly as this might not exist.
