### ISSUE TITLE
DSI with YAMdev2.9 2013-09-18

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#426]
**Originally by _javierdlr@euskalnet.net_ on 2013-09-19 11:04:27 +0200**

___
## Summary
I get a DSI when starting YAMdev 2013-09-18.

## Steps to reproduce
 1. Dowload YAMdev 2013-09-18 and unarchive it in RAM:
 2. Execute YAM (like if it was your first time, nothing configured) and upon starting 'loading images' it shows a GR (DSI).

## Notes

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-09-19 11:06:45 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-09-19_11-07-58.txt`](https://yam.ch/attachments/426/Crashlog_YAM_2013-09-19_11-07-58.txt) (17.8 KiB)
YAM DSI GR crashlog

**Comment by tboeckel** [comment]
**Originally on 2013-09-19 16:25:49 +0200**

___
In (9746b87):
 * mui/SearchControlGroup.c: set the status cycle entries when the final address of the instance data is valid. Before the address of some temporary structrue was used which made MUI access invalid memory as soon as the config window was opened. This closes #426.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 10:45:55 +0100**

___
**Release Note:**
fixed a crash bug by setting the status cycle entries when the final address of the instance data is valid.
