### ISSUE TITLE
Crash in search on gravatar button

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#428]
**Originally by _s.hawamdeh@teletu.it_ on 2013-09-21 04:29:43 +0200**

___
On a clean addressbook/new person, i got a DSI crash trying to click on the search gravatar button

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2013-09-21 04:30:57 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-09-21_04-52-18.txt`](https://yam.ch/attachments/428/Crashlog_YAM_2013-09-21_04-52-18.txt) (27.5 KiB)
Crash in search on gravatar button

**Comment by tboeckel** [comment]
**Originally on 2013-09-21 21:23:44 +0200**

___
In (c5029cb):
 * mui/UserPortraitGroup.c: don't use a never set address book entry but a user's address and photo instead. This closes #428.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 10:47:27 +0100**

___
**Release Note:**
fixed a crash bug when using the gravatar image search functionality on a never set address book entry.
