### ISSUE TITLE
yam nightly grim reaper when jumping to next new mail

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#429]
**Originally by _Michael.Merkel@gmx.net_ on 2013-09-21 20:30:51 +0200**

___
## Summary
reading new mails i used the "shift + right" key combination to jump to the next unread mail. that jumped from the inbox to a subfolder with that mail.
then the grim reaper appeared.
i was not able so far to reproduce it :-( sorry.
nevertheless here is the grim reaper - maybe it helps.

## Steps to reproduce
 unfortunately not able so far :-(

## Notes
20.6038 (svn r2770)

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2013-09-21 20:31:10 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-09-21_20-22-29.txt`](https://yam.ch/attachments/429/Crashlog_YAM_2013-09-21_20-22-29.txt) (39.0 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-09-26 14:30:33 +0200**

___
In (7d044a0):
 * YAM_MA.c, mui/WriteWindow.c: artifically increase and decrease the mail's reference counter before it is moved to another folder to prevent it from being freed too early when one of its referencing mail nodes is freed. This refs #429 and refs #435.

**Comment by tboeckel** [comment]
**Originally on 2013-09-27 06:11:41 +0200**

___
In (bed5802):
 * mui/MainMailList.c: fixed a typo in function comparing two address book entries which could have caused an access to a NULL pointer in case one of the entries did not exist. This closes #429.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 10:49:23 +0100**

___
**Release Note:**
fixed a crash bug when jumping to the next new mail.
