### ISSUE TITLE
GR/DSI when clicking on SendNow or SendLater on write window

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#431]
**Originally by _javierdlr@euskalnet.net_ on 2013-09-23 11:15:03 +0200**

___
## Summary
I get a GR/DSI (NListtree.mcc) everytime I click on SendLater or SendNow buttons on write window.

## Steps to reproduce
 1. Open a new mail, write something and click on SendNow or SendLater on write window.
 2.

## Expected results
Send message
## Actual results
GR/DSI

## Notes
After cold reboot/reset message is in OUTGOING drawer, clicking SEND button from main YAM window sends messages without problems.

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-09-23 11:16:20 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-09-23_11-08-32.txt`](https://yam.ch/attachments/431/Crashlog_YAM_2013-09-23_11-08-32.txt) (11.0 KiB)
GR/DSI on write window when clicking SendLater/SendNow button (1)

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-09-23 11:17:33 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-09-23_00-11-13.txt`](https://yam.ch/attachments/431/Crashlog_YAM_2013-09-23_00-11-13.txt) (11.1 KiB)
GR/DSI on write window when clicking SendLater/SendNow button (2)

**Comment by tboeckel** [comment]
**Originally on 2013-09-23 20:07:46 +0200**

___
Which nightly build **exactly** is crashing for you? There have been lots of changes to the internal mail handling recently and so far I am not able to reproduce this issue using the latest nightly build (23-Sep-2013).

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-09-23 23:16:48 +0200**

___
With 23.09.2013. Will go to check with previous versions to see with was the first one.
Using OS4.1 update6 and latest beta components.
Will try with OS4.1 update6 and post here results.

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-09-23 23:58:53 +0200**

___
Ok, try this:
-Start a new message (I have autosave every 2 minutes)
-Wait unitl it gets copied/backuped into drafts folder.

It seems I get the GR/DSI when message is on draft folder. Hope it helps.

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-09-23 23:59:45 +0200**

___
**Attachment added:** [`Crashlog_YAM_2013-09-23_23-58-05.txt`](https://yam.ch/attachments/431/Crashlog_YAM_2013-09-23_23-58-05.txt) (25.7 KiB)
Another GR/DSI (under AOS4.1 update6 "plain")

**Comment by tboeckel** [comment]
**Originally on 2013-09-24 16:10:23 +0200**

___
Replying to javierdlr:
> Ok, try this:
> -Start a new message (I have autosave every 2 minutes)
> -Wait unitl it gets copied/backuped into drafts folder.
> 
> It seems I get the GR/DSI when message is on draft folder. Hope it helps.

Yes, this is the bit of information that was missing before. Now YAM is crashing for me, too. I will see what is causing this.

**Comment by tboeckel** [comment]
**Originally on 2013-09-24 17:02:01 +0200**

___
In (2e6a71d):
 * mui/WriteWindow.c, YAM_MA.c, YAM_UT.c: erase the mail's folder pointer after removing it from a folder to avoid accessing this pointer after the mail has been freed. This closes #431.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 16:38:15 +0100**

___
**Release Note:**
fixed a crash bug when trying to send a mail after it had been autosaved in the drafts folder.
