### ISSUE TITLE
Crash when quiting YAM

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#433]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-24 08:21:00 +0200**

___
## Summary
Not every time but often, YAM crashes when quiting. Everything is blocked, a reset has to be done.

## Steps to reproduce
 1. Quit
 2.

## Notes

**Comment by tboeckel** [comment]
**Originally on 2013-09-24 08:26:07 +0200**

___
Did YAM really crash while producing the attached log file? According to the log YAM successfully ran till its termination and did NOT crash inbetween.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-24 08:41:49 +0200**

___
well no i must admit that this time I did not get any log data in MorphOS's log, but what happens for sure is that everything is blocked, YAM, Ambient, no icons are selectable anymore, etc. Only way is to reset via the button the machine! I send you another, new log.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-24 08:42:44 +0200**

___
**Attachment added:** [`yam_log.lha`](https://yam.ch/attachments/433/yam_log.lha) (938.2 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-24 08:59:38 +0200**

___
Here another MorphOS log file because YAM didn't wirte the simple log to my hd when it crashed.
I used: setenv yamdebug, file:pm3work:yam.log

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-24 09:00:20 +0200**

___
**Attachment added:** [`log_24-09-13.lha`](https://yam.ch/attachments/433/log_24-09-13.lha) (33.1 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-24 10:49:33 +0200**

___
here another log file because YAM crashed again while trying to send a mail.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-24 10:51:18 +0200**

___
**Attachment added:** [`yam_log.2.lha`](https://yam.ch/attachments/433/yam_log.2.lha) (2.9 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-09-24 12:53:05 +0200**

___
Please don't mix crashes in totally different situations within one ticket. This ticket is about a crash when quitting YAM, not when downloading mails.

**Comment by tboeckel** [comment]
**Originally on 2013-09-24 12:58:05 +0200**

___
In (f760c3e):
 * mui/MainFolderListtree.c: don't try to close the folder edit window during OM_DISPOSE, but just close it if it exists. Pushing the dispose method might let YAM try to dispose the window twice later on. This closes #433.

**Comment by tboeckel** [comment]
**Originally on 2013-09-24 13:10:43 +0200**

___
In (3c14bc5):
 * mui/YAMApplication.c: fixed the broken address cache saving. This refs #433.

**Comment by tboeckel** [comment]
**Originally on 2013-09-24 15:27:03 +0200**

___
In (2203f4e):
 * YAM.c, mui/MainFolderListtree.c: reworked the folder edit window disposing once again to be really bullet proof. This refs #433.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 16:39:03 +0100**

___
**Release Note:**
fixed a crash bug when quitting YAM
