### ISSUE TITLE
When hitting send, YAM crashes ans the system also

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#435]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-25 07:05:53 +0200**

___
## Summary
When hitting send, YAM crashes and also the system completly though not every time!

## Steps to reproduce
 1. writing a mail and hitting Send

 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-25 07:06:24 +0200**

___
**Attachment added:** [`log_25-09-13`](https://yam.ch/attachments/435/log_25-09-13) (693.2 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-25 07:39:26 +0200**

___
Here another log file, this was done when hitting send BUT this time the mail was send and the system did not crash!

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-25 07:40:03 +0200**

___
**Attachment added:** [`log_25-09-13.2`](https://yam.ch/attachments/435/log_25-09-13.2) (253.9 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-25 11:48:17 +0200**

___
And here again 2 log files, one from YAM which is not complete as YAM crashes the system and the 2nd is from MorphOS system. Perhaps they help!

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-25 11:49:17 +0200**

___
**Attachment added:** [`log_25-09-13.3`](https://yam.ch/attachments/435/log_25-09-13.3) (252.9 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-25 11:49:29 +0200**

___
**Attachment added:** [`yam.log`](https://yam.ch/attachments/435/yam.log) (18.6 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-25 12:10:05 +0200**

___
and antoher (last) 2 log files. I have to stop because YAM crashes here on nearly every attempt to send a mail and even when viewing...

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-25 12:10:22 +0200**

___
**Attachment added:** [`log_25-09-13.4`](https://yam.ch/attachments/435/log_25-09-13.4) (660.5 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-25 12:10:33 +0200**

___
**Attachment added:** [`yam.2.log`](https://yam.ch/attachments/435/yam.2.log) (20.8 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-25 14:25:53 +0200**

___
Here a log, where YAM did send the mail but I got hits as soon as I hit send. Yam did not crash neihter did the system.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-25 14:26:16 +0200**

___
**Attachment added:** [`log_25-09-13.5`](https://yam.ch/attachments/435/log_25-09-13.5) (292.0 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-09-26 14:30:33 +0200**

___
In (7d044a0):
 * YAM_MA.c, mui/WriteWindow.c: artifically increase and decrease the mail's reference counter before it is moved to another folder to prevent it from being freed too early when one of its referencing mail nodes is freed. This refs #429 and refs #435.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-09-27 13:40:54 +0200**

___
It seems that YAM as of nigthly build from today works correctly! At least it doesn't crash, neither does it crash the system anymore and no hits in log. Many thanks

**Comment by tboeckel** [comment]
**Originally on 2013-09-27 19:39:10 +0200**

___
That's good to hear. I'll close this ticket for the moment. Please reopen it again if this crash should happen again.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 16:42:15 +0100**

___
**Release Note:**
fixed a crash bug when trying to send a mail.
