### ISSUE TITLE
HTML mails are not opend in browser

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#437]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-10-02 13:59:30 +0200**

___
## Summary
when trying to display html mails, instead that they open in the browser, user gets asked where to save the txt.

## Steps to reproduce
 1. open mail, choose display and html part
 2.

## Notes

**Comment by tboeckel** [comment]
**Originally on 2013-10-06 14:28:58 +0200**

___
In (c280e76):
 * YAM_RE.c: don't exclude the letter part's file from determining a proper file name extension. This closes #437.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 16:45:46 +0100**

___
**Release Note:**
fixed a problem where html parts of a mail weren't forwarded to a web browser but saved to disk instead due to not using the right file extension.
