### ISSUE TITLE
Crash when selecting "Send later"

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#438]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-10-04 07:59:02 +0200**

___
## Summary
Write or edit a mail and hit "Send later"
This creates an emtpy line in Drafts. After an "update index" the line hase an e-mail address, and a subject and date.

## Steps to reproduce
 1. edit a mail and hit send later
 2. open this mail again to edit and hit again send later then YAM crashes

## Notes

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-10-04 07:59:34 +0200**

___
**Attachment added:** [`log_04-10-13`](https://yam.ch/attachments/438/log_04-10-13) (519.9 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-10-07 08:33:58 +0200**

___
I send you 2 more log files as well as a screengrab where you can see the error message from YAM and also that the e-mail line in Drafts is emtpy. I already assure you that there is enough space and the folder exists!

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-10-07 08:34:32 +0200**

___
**Attachment added:** [`MorphOS.log`](https://yam.ch/attachments/438/MorphOS.log) (1.3 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-10-07 08:34:49 +0200**

___
**Attachment added:** [`log_07-10-13`](https://yam.ch/attachments/438/log_07-10-13) (257.4 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-10-07 08:35:05 +0200**

___
**Attachment added:** `ScreenGrab.png` (1820.6 KiB)
![ScreenGrab.png](https://yam.ch/attachments/438/ScreenGrab.png)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-10-07 08:44:42 +0200**

___
Following the above and after a reset there is still a file in Drafts, please see the screengrab. When I then try to read it, I get an error message that the file does not exists. When I then do an update index on the Drafts folder everything shows up, e-mail address, subject... and I can read the e-mail.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-10-07 08:45:08 +0200**

___
**Attachment added:** `ScreenGrab.2.png` (2159.5 KiB)
![ScreenGrab.2.png](https://yam.ch/attachments/438/ScreenGrab.2.png)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-10-07 08:45:18 +0200**

___
**Attachment added:** `YAM 2.9-dev - User Christoph Poelzl.png` (75.1 KiB)
![YAM 2.9-dev - User Christoph Poelzl.png](https://yam.ch/attachments/438/YAM%202.9-dev%20-%20User%20Christoph%20Poelzl.png)

**Comment by tboeckel** [comment]
**Originally on 2013-10-07 09:48:52 +0200**

___
It seems there is some kind of memory trashing happening, because the logs point to one of YAM's memory freeing functions and the system logs tells something about a wrong size when freeing memory.

Unfortunately I am not able to reproduce this issue, no matter what I do. Could you please create a simple log using the debug version. This will include error messages about duplicate freeing attempts without any further options. At least this is the only thing I can think of right now.

Does this happen always when sending a mail? Or is this restricted to replying to a mail?

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-10-07 15:20:37 +0200**

___
Please find enclosed the new log's, one from YAM debug and also the MorphOS one.

I'm not sure if it has something to do with new or reply... to me it has rather to do with the mail getting saved in drafts...

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-10-07 15:20:59 +0200**

___
**Attachment added:** [`log_07-10-13.2`](https://yam.ch/attachments/438/log_07-10-13.2) (27.3 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-10-07 15:21:12 +0200**

___
**Attachment added:** [`MorphOS.2.log`](https://yam.ch/attachments/438/MorphOS.2.log) (1.4 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-10-07 20:22:07 +0200**

___
I think I found a situation in which a mail could be freed twice. Perhaps the next nightly build fixes this issue. If it crashes nevertheless, then please  provide a MAIL debug log.

**Comment by tboeckel** [comment]
**Originally on 2013-10-07 20:24:26 +0200**

___
In (fdf2952):
 * mui/WriteWindow.c: fixed a possible duplicate freeing of mails when saving a draft mail. This refs #438.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-10-09 06:55:54 +0200**

___
Working one day without problems now! I think this bug is solved.

**Comment by tboeckel** [comment]
**Originally on 2013-10-09 08:51:31 +0200**

___
Replying to rmsyam:
> Working one day without problems now! I think this bug is solved.

Hooray! :)
Please reopen this ticket if this crash happens again.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 16:46:50 +0100**

___
**Release Note:**
fixed a crash bug caused by freeing the same mail pointer twice.
