### ISSUE TITLE
Upper right main YAM window showing "empty" square

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#440]
**Originally by _javierdlr@euskalnet.net_ on 2013-10-09 10:05:54 +0200**

___
## Summary
Not always, but sometimes, when I click on GET button, and seems when FILTERING new mails on the upper right corner it shows/paints an "empty" square, hidding some toolbar buttons.

IIRC it only shows when I have MUNGE option (os4_commandline=debuglevel=4 MUNGE
)

Please can you enlight me how to help to track this strange "bug"?
Ex. Using YAM.debug and setting XXXX DebugEnvarc. TIA

## Steps to reproduce
 1. CLick on GET button to recieve mails and auto filtering is on.
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-10-09 10:06:47 +0200**

___
**Attachment added:** `sgrab001.png` (30.3 KiB)
![sgrab001.png](https://yam.ch/attachments/440/sgrab001.png)
Upper rright corner showing "empty" square (hidding some buttons)

**Comment by tboeckel** [comment]
**Originally on 2013-10-09 16:10:15 +0200**

___
So far I have never seen anything similar on my systems. Did you notice the empty window title bar? It should show something like "YAM 2.9-dev - User: your name".

The problem is, unless there isn't a crash happening it is quite hard, if not impossible, to spot the exact location or reason of this graphical distorsion.

Which MUI version are you using?

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-10-09 22:54:35 +0200**

___
**Attachment added:** `sgrab001.2.png` (130.0 KiB)
![sgrab001.2.png](https://yam.ch/attachments/440/sgrab001.2.png)
Same image, but without color reducing

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-10-09 22:56:59 +0200**

___
Ups, my foult reduced colors to upload image/grab. Reuploaded with "full" colors, sorry.

MUI 4 Versión:20.6038 (svn r2770).

No, but it happens here only with MUNGE option enabled. I'll continue testing new dev versions, and see if there is some kind of path to reproduce. TIA

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-10-18 01:13:27 +0200**

___
Seems happens in the STATUS BAR, if it's disabled no problems (no empty square hidding icons/part_of_the_main_window).

Fontsize problem? (Localized) strings too long?

**Comment by tboeckel** [comment]
**Originally on 2013-10-18 21:45:09 +0200**

___
Replying to javierdlr:
> Seems happens in the STATUS BAR, if it's disabled no problems (no empty square hidding icons/part_of_the_main_window).
> 
> Fontsize problem? (Localized) strings too long?

I doubt it is either of these. YAM uses the MUI standard fonts (i.e. big, tiny, normal) and does absolutely nothing fancy for the affected group. I am running YAM myself on small screens (640x480, 800x600) and larger screens (1280x1024) but never have seen this effect myself. Too long strings are either truncated or cause an object to be hidden automatically.

I really have no clue which object might be causing this effect and why.

I can offer you to build a special version with some artifical coloring of the individual objects to make it more obvious which object is causing the effect.

You need AmigaOS4 binaries, correct?

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-10-18 23:20:18 +0200**

___
Yes you're correct my system is SAM3460ex with AOS4.1beta.
I'm going away for a few days. So until 23rd I can't test anything.
TIA

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-10-18 23:20:40 +0200**

___
opps my PM is jabierdlrATgmail.com

**Comment by tboeckel** [comment]
**Originally on 2013-10-30 20:13:41 +0100**

___
Special version has been sent privately. These are the special background colors used for debugging purposes:

set(data->TX_FOLDER, MUIA_Background, "rff0000");
set(data->TX_FINFO,  MUIA_Background, "r00ff00");
set(data->GA_GROUP,  MUIA_Background, "r0000ff");
set(data->GA_LABEL,  MUIA_Background, "rffff00");
set(data->GA_INFO,   MUIA_Background, "r00ffff");
set(data->TX_INFO,   MUIA_Background, "rff00ff");

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-10-30 23:32:04 +0100**

___
erm, sorry to bother, but what email did you use? Haven't recieved nothing yet!
Or is somehow attached here in YAM's web/forum/..?

**Comment by tboeckel** [comment]
**Originally on 2013-10-31 06:19:11 +0100**

___
Replying to javierdlr:
> erm, sorry to bother, but what email did you use? Haven't recieved nothing yet!
> Or is somehow attached here in YAM's web/forum/..?

Sorry, my crappy LTE internet connection didn't allow me to send out the mail yesterday. It is on its way now.

**Comment by tboeckel** [comment]
**Originally on 2013-11-04 14:24:51 +0100**

___
Does this effect happen with MUI 3.9, too, or with MUI4 only?

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-11-05 14:08:45 +0100**

___
Testing with MUI3.9 and no problems so far. Let me test it a few more days and will post here results. TIA.

**Comment by tboeckel** [comment]
**Originally on 2013-11-05 16:08:45 +0100**

___
**Attachment added:** `sgrab002.png` (115.3 KiB)
![sgrab002.png](https://yam.ch/attachments/440/sgrab002.png)
Screenshot of special colored version

**Comment by tboeckel** [comment]
**Originally on 2013-11-05 16:16:55 +0100**

___
**Attachment added:** [`yam_color_hspace.lha`](https://yam.ch/attachments/440/yam_color_hspace.lha) (1193.7 KiB)
original HSpace object

**Comment by tboeckel** [comment]
**Originally on 2013-11-05 16:17:19 +0100**

___
**Attachment added:** [`yam_color_text.lha`](https://yam.ch/attachments/440/yam_color_text.lha) (1193.7 KiB)
empty text object instead of HSpace

**Comment by tboeckel** [comment]
**Originally on 2013-11-05 16:22:19 +0100**

___
Replying to javierdlr:
> Testing with MUI3.9 and no problems so far. Let me test it a few more days and will post here results. TIA.

Sounds interesting, but this still doesn't ring a bell for me.

Anyway, I created two more versions of YAM to test. The "hspace" version does some other coloring of the single pages of a page group, but is identical to the normal nightly builds in all respects. The "text" version uses a different object for the empty page, but with the same coloring as the "hspace" version. Perhaps this makes a difference.

The colors for reference:
red   (0xff0000) empty page
green (0x00ff00) progress page, mostly covered by the gauge
blue  (0x0000ff) simple information text

**Comment by tboeckel** [comment]
**Originally on 2013-11-08 13:48:36 +0100**

___
Any news on this issue regarding MUI 3.9 or the updated color versions and MUI 4.0?

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2013-11-09 11:30:39 +0100**

___
Ok after a few days I couldn't reproduce the "rectangle_efect" using either YAM .hspace or .text versions. Now/today (9-11-2013) I reverted to daily debug version and seems ok. In a couple of days I'll post here more results. THX

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-11-12 09:11:48 +0100**

___
Today I got the rectangle (in grey) while using the special YAM.hspace compilation. Changed to use YAM.text compilation will tell you more in a couple of days. THX for being/having patience.
Using latest MUI4 version

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-11-12 09:12:41 +0100**

___
**Attachment added:** `sgrab000_HSPACE.png` (117.4 KiB)
![sgrab000_HSPACE.png](https://yam.ch/attachments/440/sgrab000_HSPACE.png)
YAM.hspace showing rectangle (in grey)

**Comment by tboeckel** [comment]
**Originally on 2013-11-16 22:58:52 +0100**

___
Any news for the "text" version?

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-11-17 10:56:49 +0100**

___
Ok with YAM.text I got the same rectangle, but it takes a lot more to appear (like with YAM.hspace) than normal debug version.
Will try those two version on plain update6 and again with MUI39 and post results ASAP.

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-11-17 10:57:26 +0100**

___
**Attachment added:** `sgrab000_TEXT.png` (115.8 KiB)
![sgrab000_TEXT.png](https://yam.ch/attachments/440/sgrab000_TEXT.png)
YAM.text version

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-12-27 20:56:02 +0100**

___
With final YAM2.9 (now using YAM2.10dev) I don't get such "grey" rectangle anymore!!!! :-)
Will post it after xmas if still ok.

THX

**Comment by jens-maus** [comment]
**Originally on 2013-12-27 20:57:51 +0100**

___
Ok, we will then close this ticket. Please reopen if the issue comes back.

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2014-02-03 11:41:14 +0100**

___
Since a couple of days the 'grey rectangle' showed again :-/
Will do some tests and post here results.
Using 2.10dev nightly builds
Maybe is some sort of latest MUI4 (I'm betatestter) and YAM? Will try with public OS4.1 upd6 and see what happens.

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2014-02-24 10:03:43 +0100**

___
Hi, since updated to 2.10dev the 'grey rectangle' showed again :-/ 

If in YAM I have (MSG_CO_TransferWin) "Transfer window" NOT set to "hide always" I don't get the grey rectangle problem.
So maybe is some string that shows in YAM main window when "Transfer window" is "hide always", that doesn't show if transfer window shows up.

**Comment by tboeckel** [comment]
**Originally on 2014-02-24 12:11:36 +0100**

___
Replying to javierdlr:
> Hi, since updated to 2.10dev the 'grey rectangle' showed again :-/ 
> 
> If in YAM I have (MSG_CO_TransferWin) "Transfer window" NOT set to "hide always" I don't get the grey rectangle problem.
> So maybe is some string that shows in YAM main window when "Transfer window" is "hide always", that doesn't show if transfer window shows up.

There are some things you can try for us:
1. don't use any language catalog. Start YAM using the NOCATALOG option (ToolTypes or commandline).
2. set the status bar to a different location, i.e. bottom or invisible.
2. let MUI use the default settings. I don't really think that your "classic OS3" look could be the culprit, but who knows...

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2014-02-24 21:35:11 +0100**

___
Ok using NOCATALOG option and MUI default settings. Will post news here ASAP.

**Comment by jens-maus** [comment]
**Originally on 2014-03-02 17:59:13 +0100**

___
Any news on that issue?

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2014-03-03 10:16:45 +0100**

___
Since using internal strings (NOCATALOG) and default MUI settigns no problems, so far.
So, seems "my fault" in some MUI settings, just trying to find what in MUI is causing the "grey ractangle".
I suspect is in MUI BUTTONS settings, will go one by one settings in MUI BUTTONS and post here (or MUIdev web) results.

THX for being patience with such "problem".

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2014-03-12 10:12:24 +0100**

___
With NOCATALOG and MUI defaults prefs (changed only Buttons GAUGE settings) I got today the rectangle problem in YAM, so maybe is MUI problem (too small gauge height to fit image/text/button?).

Attached is MUI prefs with such change, hope you can reproduce it.

THX and sorry for the hassle.

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2014-03-12 10:13:53 +0100**

___
**Attachment added:** [`YAM_RectangleBug.prefs`](https://yam.ch/attachments/440/YAM_RectangleBug.prefs) (0.1 KiB)
MUI default prefs. Only changed GAUGE settings

**Comment by tboeckel** [comment]
**Originally on 2014-03-15 19:11:38 +0100**

___
According to a private mail from Javier this issue will be fixed by the upcoming release of MUI 4.0-2014R3.
