### ISSUE TITLE
Yam doesn't save the Filter part in config correctly.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#441]
**Originally by _opionline@yahoo.de_ on 2013-10-10 00:30:21 +0200**

___
Yam doesn't save the Filter part in config correctly.

To reproduce you can try the attached (simple) config file.
It contain 2 condtions: "test1" and "test2"
If you change i.e. "test1" to "test12" save the config and compare the saved file with the original file you will see that nothing has changed.

Anything is really working wrong here.
In my working copy of Yam some conditions are randomly changed e.g. if i change a filter condition then in another filter a string gets deleted.
And i wonder why the filter is working wrong...

Used Version:
YAM 2.9-dev (09.10.2013)
Copyright (C) 2000-2013 YAM Open Source Team [OS3/m68k, r7140]
on Amiga 2000 BB2 - MUI 3.8

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-10-10 00:32:09 +0200**

___
**Attachment added:** [`.config`](https://yam.ch/attachments/441/.config) (9.9 KiB)
Test config file

**Comment by tboeckel** [comment]
**Originally on 2013-10-10 10:22:25 +0200**

___
In (80cd459):
 * mui/FiltersConfigPage.c: make sure to transfer any pending changes from the GUI to the current filter entry when closing the config window. This closes #441.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 17:58:12 +0100**

___
**Release Note:**
fixed a problem where the filter part of the config wasn't save correctly.
