### ISSUE TITLE
Cannot enter adresses from the message window (button next to addressline, cc)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#442]
**Originally by _JDuch@fulladsl.be_ on 2013-10-28 11:03:44 +0100**

___
## Summary
When clicking on the V right next to the address or cc line, nothing happens
## Steps to reproduce
 1.
 2.

## Expected results
expected to see the  address window pop up
## Notes

**Comment by tboeckel** [comment]
**Originally on 2013-10-28 19:45:05 +0100**

___
In (1ce6ad4):
 * mui/AddressField.c, mui/YAMApplication.c, misc: moved the address field into a separate group and made the recipient string popup button work again. This  closes #442.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 18:04:34 +0100**

___
**Release Note:**
fixed a problem where the recipient string popup wasn't working anymore.
