### ISSUE TITLE
Clicking on a line in address book window does not enable the possibility to enter selected line in messag

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#443]
**Originally by _JDuch@fulladsl.be_ on 2013-10-28 11:16:23 +0100**

___
## Summary
As in title
## Steps to reproduce
 1. open a new message
 2. Open the window with menu settings/addressbook
 3. select an adress

## Expected results
the "to/cc/Bcc" should  be eanbled for selection
## Actual results
This is not the case
## Notes

**Comment by tboeckel** [comment]
**Originally on 2013-10-29 06:19:59 +0100**

___
In (0a29203):
 * mui/AddressBookWindow.c: increased the method parameter counter to correctly pass the required parameter to the UseEntry method. This closes #443.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 20:05:17 +0100**

___
**Release Note:**
fixed a bug where an incorrect number of function parameters caused the address book not to work correctly.
