### ISSUE TITLE
Add low memory handler to flush folder indexes automatically

### ISSUE THREAD

**Issue by tboeckel** [jens-maus/yam#444]
**Originally on 2013-10-28 12:09:29 +0100**

___
## Problem
Large mail folders might keep lots of memory allocated. Although YAM will free this memory for folders which haven't been used for a certain time it might be desirable to free as much memory as soon as the low memory situation occurs.

## Analysis
A low memory handler can be hooked into the system to free as much memory as possible in a low memory situation.

## Enhancement recommendation
Add a low memory handler to fire the corresponding timer immediately.

The memory allocation causing the handler to be triggered might not be fulfilled, because YAM cannot free the memory from within the low memory handler but has to do this asynchronously and therefore a little bit later.

**Comment by tboeckel** [comment]
**Originally on 2013-10-28 12:26:20 +0100**

___
In (e4ce744):
 * YAM.c: added a low memory handler to flush the folder indexes in case of a low memory situation. This closes #444.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 20:06:15 +0100**

___
**Release Note:**
added a low memory handler to flush all folder indexes automatically if a system is about to run low on memory.
