### ISSUE TITLE
Trace of Filtered & moved  mails do remain in "incoming" folder

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#445]
**Originally by _JDuch@fulladsl.be_ on 2013-11-06 11:26:21 +0100**

___
## Summary
Witth the debug version of 31/10/2013
i observed that there were some messages which on clicking upon, confronted me with the message that the file did not exist.
Those were three files i normally would expect to have been moved by installed filters to some other folders. Verifying there, i did observe they were indeed moved.

## Steps to reproduce
 1. wait & see if it happens again ii guess
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-06 11:44:10 +0100**

___
having installed the 06/11/2013 build, and hit the "get" button a new "file trace" appeared in my "incoming" window. The file was not present there, but this is really worrying: it was not present in my AROS folder too where it should have been moved.

**Comment by jens-maus** [comment]
**Originally on 2013-11-06 11:56:29 +0100**

___
Hi, I am sorry but as long as you cannot reproduce the problem consistently we are kinda out of ideas here. So please try to get a reproduceable case and even better would be if you could run the debug version of YAM and give some detailed debug output to us. Just stating "there seems to be something wrong" doesn't help...

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2013-11-07 13:03:57 +0100**

___
I do appreciate your position,  Mine is not easy here too.
The problem was nasty and consistent on my 440 ep . I feared loss of incoming messages and have therefore decide not to continue the usage of YAM 2.9 dev debug   there

I do indeed run the de"bug version, but since no error appears i can't give you more info.really.
I can run snoopy, when i try to open such a 'trace' in the incoming drawer, but i guess it will show you exactely what you can observe if you delete some message directly using filer or the shell)

All my observations were on SAM440ep OS4.1 update 6 freshly reinstalled. As YAM is on another partition and only AppDir has to be reInitialised, i don't see where the problems could come from. Still that might be from the use of some other program that lost some  preference info, i don't know. I do observe other strange errors (not YAM)

I did install YAM 2.8p1 on my new SAM460ex
 as well as the debug version of 2.9 Dev

I tried to test as follows:

created a folder Test and a filter moving messages i sent  to myself into this new folder.
This seems to work OK, so i can't reproduce the problem.

BTW in creating the folder, i did not enter the directory name which appeared to be there allready somewhat ghoste, i agree, but i got a crash.

The drawer was created but was not included in .folders, editing .foldersmanually did not make YAM aware of it too. 

I'll try to do the same on SAM440ep

**Comment by tboeckel** [comment]
**Originally on 2013-11-07 13:14:39 +0100**

___
Replying to anonymous:

> I can run snoopy, when i try to open such a 'trace' in the incoming drawer, but i guess it will show you exactely what you can observe if you delete some message directly using filer or the shell)

Don't guess, prove it! If you don't check it then nobody will be able to tell you what is really going on.

> I do observe other strange errors (not YAM)

Perhaps you solve these errors first before complaining here about bugs in YAM.

> BTW in creating the folder, i did not enter the directory name which appeared to be there allready somewhat ghoste, i agree, but i got a crash.

Which version? 2.8p1 or 2.9? And where is the crashlog? Sorry, but you are constantly complaining about non-working stuff, but you are giving us absolutely nothing except vague descriptions to solve this issue. Even the very basic information about which version of YAM caused the crash is missing. How do expect us to help you?

> The drawer was created but was not included in .folders, editing .foldersmanually did not make YAM aware of it too. 

Well, if YAM crashes before it is able to write the updated .folders file it is obvious that the new folder is missing, isn't it? Things are done in a sequence. If this sequence is interrupted inbetween the remaining actions won't be done.

**Comment by jens-maus** [comment]
**Originally by _JDuch@fulladsl.be_ on 2013-11-07 15:44:32 +0100**

___
Om my sam 460 apart from the YAM2.8p1  i installed the latest nightly build
I have no special problems here, The install is brand new
The mentioned problem is still present for the nightly build 07/11/2013
So the problem is clearly with recent YAM nightly builds
A trace remains in the incoming folder for a message that has been moved by filtering elsewhere.
When clicking in on that trace an error messsage appears telling  "Impossible de lire le fichioer "Q2BY3gADZPU=.001.N3"
Controlling in the incoming folder with filer , i can indeed tell there is no such file there, but it is present in the "MovedTo" folder, where it can be opened normally from YAM.

As the filtering problem happens when downloading messages,  i fail to see to what the  snoopy trace can tell you, but here it is.

```
    Log Generated by; Snoopy 53.32 (14.10.2013)

00001 : ENV/env-handler 53.2  : FAIL = Lock("ENVARC:MagicWB",SHARED) [50uS]
00002 : YAM             : FAIL = GetVar("MagicWB",0x5EA54BA4,4,0x00000100) [343uS]
00003 : YAM             : o.k. = [exec] OpenLibrary("mui/Pixmap.mui",20) [179uS]
00004 : YAM             : o.k. # Open("Datas:YAM_2.7/Incoming/Q28ZuAAIiKU=.001,",OLD)[0x183F0462] [201uS]
00005 : YAM             : o.k. = ExamineFH("Q28ZuAAIiKU=.001,") [13uS]
00006 : YAM             : FAIL = IsInteractive("Datas:YAM_2.7/Incoming/Q28ZuAAIiKU=.001,")
00007 : YAM             : o.k. = IsFileSystem("Datas:") [36uS]
00008 : YAM             : FAIL = Lock("T:YAMr0000005a-p0.txt",SHARED) [61uS]
00009 : YAM             : o.k. # Open("T:YAMr0000005a-p0.txt",RW )[0x183F0498] [107uS]
00010 : YAM             : o.k. = ExamineFH("YAMr0000005a-p0.txt") [16uS]
00011 : YAM             : FAIL = IsInteractive("T:YAMr0000005a-p0.txt")
00012 : YAM             : o.k. = IsFileSystem("T:") [36uS]
00013 : YAM             : DIR  = ParentOfFH(0x183F0498) "T:YAMr0000005a-p0.txt" [17uS]
00014 : YAM             : o.k. = ExamineFH("YAMr0000005a-p0.txt") [12uS]
00015 : YAM             :        CurrentDir("<untracked>")
00016 : YAM             : o.k. = SetProtection("YAMr0000005a-p0.txt",0x00008802) [214uS]
00017 : YAM             :        CurrentDir("<untracked>")
00018 : YAM             : o.k. = ExamineObject(0x5EA54F08) [118uS]
00019 : YAM             : o.k. = SetComment("T:YAMr0000005a-p0.txt","Header") [227uS]
00020 : YAM             : FAIL = Lock("T:YAMr0000005a-p1.txt",SHARED) [46uS]
00021 : YAM             : o.k. # Open("T:YAMr0000005a-p1.txt",RW )[0x183F0498] [88uS]
00022 : YAM             : o.k. = ExamineFH("YAMr0000005a-p1.txt") [13uS]
00023 : YAM             : FAIL = IsInteractive("T:YAMr0000005a-p1.txt")
00024 : YAM             : o.k. = IsFileSystem("T:") [32uS]
00025 : YAM             : DIR  = ParentOfFH(0x183F0498) "T:YAMr0000005a-p1.txt" [15uS]
00026 : YAM             : o.k. = ExamineFH("YAMr0000005a-p1.txt") [12uS]
00027 : YAM             :        CurrentDir("<untracked>")
00028 : YAM             : o.k. = SetProtection("YAMr0000005a-p1.txt",0x00008802) [236uS]
00029 : YAM             :        CurrentDir("<untracked>")
00030 : YAM             : o.k. = ExamineObject(0x5EA54F08) [122uS]
00031 : YAM             : o.k. = SetComment("T:YAMr0000005a-p1.txt","Letter") [226uS]
00032 : YAM             : DIR  = ParentOfFH(0x183F0462) "Datas:YAM_2.7/Incoming/Q28ZuAAIiKU=.001," [55uS]
00033 : YAM             : o.k. = ExamineFH("Q28ZuAAIiKU=.001,") [9uS]
00034 : YAM             : o.k. # Open("T:YAMr0000005a-p1.txt",OLD)[0x183F0462] [86uS]
00035 : YAM             : o.k. = ExamineFH("YAMr0000005a-p1.txt") [13uS]
00036 : YAM             : FAIL = IsInteractive("T:YAMr0000005a-p1.txt")
00037 : YAM             : o.k. = IsFileSystem("T:") [34uS]
00038 : YAM             : FAIL = Lock("T:YAMm0000005a-p1.1",SHARED) [41uS]
00039 : YAM             : o.k. # Open("T:YAMm0000005a-p1.1",RW )[0x183F0498] [81uS]
00040 : YAM             : o.k. = ExamineFH("YAMm0000005a-p1.1") [15uS]
00041 : YAM             : FAIL = IsInteractive("T:YAMm0000005a-p1.1")
00042 : YAM             : o.k. = IsFileSystem("T:") [32uS]
00043 : YAM             : DIR  = ParentOfFH(0x183F0498) "T:YAMm0000005a-p1.1" [17uS]
00044 : YAM             : o.k. = ExamineFH("YAMm0000005a-p1.1") [14uS]
00045 : YAM             :        CurrentDir("<untracked>")
00046 : YAM             : o.k. = SetProtection("YAMm0000005a-p1.1",0x00008802) [213uS]
00047 : YAM             :        CurrentDir("<untracked>")
00048 : YAM             : DIR  = ParentOfFH(0x183F0462) "T:YAMr0000005a-p1.txt" [15uS]
00049 : YAM             : o.k. = ExamineFH("YAMr0000005a-p1.txt") [13uS]
00050 : YAM             : o.k. = Delete("T:YAMr0000005a-p1.txt") [253uS]
00051 : YAM             : o.k. = ExamineObject(0x5EA54B78) [122uS]
00052 : YAM             : o.k. = SetComment("T:YAMm0000005a-p1.1","Part 1.1") [235uS]
00053 : YAM             : o.k. # Open("T:YAMm0000005a-p1.1",OLD)[0x183F0462] [100uS]
00054 : YAM             : o.k. = ExamineFH("YAMm0000005a-p1.1") [15uS]
00055 : YAM             : FAIL = IsInteractive("T:YAMm0000005a-p1.1")
00056 : YAM             : o.k. = IsFileSystem("T:") [34uS]
00057 : YAM             : DIR  = ParentOfFH(0x183F0462) "T:YAMm0000005a-p1.1" [17uS]
00058 : YAM             : o.k. = ExamineFH("YAMm0000005a-p1.1") [13uS]
00059 : YAM             : o.k. = Rename("Datas:YAM_2.7/Incoming/Q28ZuAAIiKU=.001," -> "Datas:YAM_2.7/Incoming/Q28ZuAAIiKU=.00
00060 : YAM             : FAIL = Lock("Datas:YAM_2.7/Incoming/.index",SHARED) [121uS]
00061 : YAM             : o.k. # Open("Datas:YAM_2.7/Incoming/.index",RW )[0x183F0462] [253uS]
00062 : YAM             : o.k. = ExamineFH(".index") [16uS]
00063 : YAM             : FAIL = IsInteractive("Datas:YAM_2.7/Incoming/.index")
00064 : YAM             : o.k. = IsFileSystem("Datas:") [38uS]
```

**Comment by tboeckel** [comment]
**Originally on 2013-11-07 16:12:29 +0100**

___
Replying to JosDuchIt:

> I have no special problems here, The install is brand new

Is you Snoopy log refering to this "brand new" installation using YAM 2.9-dev? I am just asking, because the log states you named your directory "YAM_2.7" which is a bit odd for a "brand new" installation. Furthermore the current nightly builds of YAM 2.9-dev use a path like "<YAM's dir>/Folders/incoming" for the Incoming folder. This special path is missing from your log, so I must assume you are using YAM 2.8p1 instead of YAM 2.9-dev.

So please execuse my question, but which version of YAM are you really using? Your description mentions both versions, which you seem to mix up constantly.

"Impossible de lire le fichioer "Q2BY3gADZPU=.001.N3"

Did you copy&paste this string, or did you type it manually? The digit "3" at the end of the name is definitely wrong, as well as the second dot which should be a comma. The file should be named "Q2BY3gADZPU=.001," plus some letters describing the mail state.

> Controlling in the incoming folder with filer , i can indeed tell there is no such file there, but it is present in the "MovedTo" folder, where it can be opened normally from YAM.

Your Snoopy log just states that a mail was decoded and displayed and then you most probably switched to another mail. There is only one Delete() operation logged, which refers to a temporary file of a decoded mail. Second, there is a Rename() call which (I must guess here, due to the shortened lines) renames "Q28ZuAAIiKU=.001," to something else within the same directory ("Datas:YAM_2.7/Incoming").

To make it short: what ever your log is meant to prove in respect to this ticket it does not contain the information.

I cannot tell if it is possible to produce longer lines with Snoopy. If yes, then try to capture another log containing the **complete** filter process and please add the log as an attachment here instead of inlining it in your reply.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2013-11-07 17:39:25 +0100**

___
**Attachment added:** [`.folders2.8p1`](https://yam.ch/attachments/445/.folders2.8p1) (4.1 KiB)

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2013-11-07 17:40:01 +0100**

___
**Attachment added:** [`.folders2.9`](https://yam.ch/attachments/445/.folders2.9) (4.1 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-11-07 19:02:24 +0100**

___
Better change your POP3 and SMTP passwords **IMMEDIATELY**. Everybody can read your mails now that you have posted your private config files here without removing the private stuff first...

And please log in before commenting or adding attachments.

**Comment by tboeckel** [comment]
**Originally on 2013-11-07 20:44:42 +0100**

___
Some things I notices, although unrelated to this issue.

- You have two folders named "Drafts" but in different locations "drafts" and "drafts_1".
- You swapped the names of the 2.8p1 and 2.9-dev configurations. Quite confusing if one is expecting certain things..

**Comment by tboeckel** [comment]
**Originally on 2013-11-07 20:59:34 +0100**

___
Yet another observation. All your filter conditions have at least one empty condition (no match string). One the one hand this is a bug in the filter import in YAM 2.9-dev of older configurations (YAM 2.8p1 and older). But even your 2.8p1 config contains these empty conditions.

**Comment by tboeckel** [comment]
**Originally on 2013-11-12 09:48:02 +0100**

___
I was just able to reproduce this issue myself. I think I know what is causing this.

**Comment by tboeckel** [comment]
**Originally on 2013-11-12 10:27:33 +0100**

___
In (5dff16e):
 * YAM_MAf.c, YAM_UT.c: make sure to have a loaded and valid folder whenever a mail is to be added or removed from a folder. Otherwise it might happen that the corresponding mail file is moved somewhere else, but the index entry stays in the former folder. This closes #445.

**Comment by jens-maus** [comment]
**Originally on 2013-11-14 07:54:13 +0100**

___
Please note that #450 was just closed as a duplicate with some potential additional information.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 20:30:48 +0100**

___
**Release Note:**
fixed a problem where mail were not completely moved to another folder.
