### ISSUE TITLE
GR at startup (QuickSearchBar)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#446]
**Originally by _AmigaPhil@scarlet.be_ on 2013-11-06 18:04:29 +0100**

___
This crash happened on the 6/11/2013 nightly build on OS4.1u6 (see crashlog attached).

## Steps to reproduce
 1. Load Yam
 2. Change the View cycle gadget to "New"
 3. Close Yam
 4. Load Yam => Gream reaper

**Comment by jens-maus** [comment]
**Originally by _AmigaPhil@scarlet.be_ on 2013-11-06 18:05:13 +0100**

___
**Attachment added:** [`Crashlog_YAM.debug_2013-11-06_16-47-11.txt`](https://yam.ch/attachments/446/Crashlog_YAM.debug_2013-11-06_16-47-11.txt) (34.1 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-11-06 20:07:33 +0100**

___
In (1656b71):
 * QuickSearchBar.c: added a NULL pointer check for a valid folder. This closes #446.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 20:42:59 +0100**

___
**Release Note:**
fixed a crash bug when starting YAM referring to the QuickSearchBar functionality.
