### ISSUE TITLE
YAM crashes during sending of an e-mail

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#447]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-11-07 09:28:09 +0100**

___
## Summary

This happens now since a week or so, during sending an e-mail, about 60 to 70% has already been transfered, it seems that YAM crashes. When this happens the whole System is crashed and a Reset must be done. This does not happen every time and unfortunately I can't reproduce the problem in a specific way. I add a MorphOS Logfile, perhaps it helps.

## Steps to reproduce
 1. sending an e-mail
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-11-07 09:28:29 +0100**

___
**Attachment added:** [`log_07-11-13`](https://yam.ch/attachments/447/log_07-11-13) (318.8 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-11-07 11:54:05 +0100**

___
The log doesn't help anything except that I can see that the crash happens somewhere in YAM's WriteToHost() function, but not directly there. The final crash seems to happen in the 68k emulation, I suppose in the SSL stuff. I can assure you that we didn't touch this section of the code for several month now. And what is even more puzzling is the fact that the transfer works up to a certain point and crashes then. If there was a general bug it should either crash immediately or never, because the transfer is basically a big loop going from start to end while sending out small portions of the mail.

If this should really be a bug in YAM introduced recently then going back to an older nightly build (i.e. one week at least as you suggested yourself) and trying to reproduce this issue (or proving the contrary) is the only viable solution from my point of view. Did you change anything on your system except the nightly builds of YAM?

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-11-11 08:52:42 +0100**

___
Well, it does not happen often but it happens, so I wait some more time and see the frequency of this before I do the necessary tests in going back several versions of YAM.

Yes system get's updated with newer MorphOS versions as well as YAM's nightly builds.

**Comment by tboeckel** [comment]
**Originally on 2013-11-11 09:10:03 +0100**

___
Replying to rmsyam:
> Yes system get's updated with newer MorphOS versions as well as YAM's nightly builds.

Has your system been updated recently? And if yes, did the update affect the 68k emulation?

**Comment by jens-maus** [comment]
**Originally on 2013-11-11 09:21:25 +0100**

___
Let me please comment on that ticket as well as Thore was talking about SSL and 68k emulation. Please keep in mind that the AmiSSL version used on MorphOS is the 68k version from OS3 as there is no MorphOS-native build of AmiSSL yet. And it could be easily possible that it is the SSL certificate check that might be buggy in recent YAM builds. So it might be worth disabling SSL and see if the problem vanishes.

This really reminds me that we need to build AmiSSL for MorphOS also in some near future. Luckily I were able to get hold of the AmiSSL sources a few month ago and started a new sf.net project. See here: https://sourceforge.net/projects/amissl/

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-11-11 14:01:08 +0100**

___
Unfortunately I don't think I can diable AmiSSL because I do have secured access to my mail boxes and if I diable it I don't think I can access the Mail-Server!

**Comment by tboeckel** [comment]
**Originally on 2013-11-16 22:56:19 +0100**

___
Replying to rmsyam:
> Unfortunately I don't think I can diable AmiSSL because I do have secured access to my mail boxes and if I diable it I don't think I can access the Mail-Server!

Well, at least you could try it. If you don't try you don't know if it might work without SSL.

**Comment by tboeckel** [comment]
**Originally on 2013-11-25 06:29:16 +0100**

___
Replying to thboeckel:
> Well, at least you could try it. If you don't try you don't know if it might work without SSL.

Christoph, did you do any further tests? Or did the crashes vanish?

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-11-25 07:00:55 +0100**

___
Replying to thboeckel:
> Replying to thboeckel:
> > Well, at least you could try it. If you don't try you don't know if it might work without SSL.
> 
> Christoph, did you do any further tests? Or did the crashes vanish?

Sorry forgott about this :-( Yes I could say, it vanished, did not experience this problem since my last post here.

**Comment by tboeckel** [comment]
**Originally on 2013-11-25 19:46:23 +0100**

___
Replying to rmsyam:

> Sorry forgott about this :-( Yes I could say, it vanished, did not experience this problem since my last post here.

Just to satify my curiosity, did you change anything else on your system except the nightly builds of YAM?

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2013-11-27 07:29:37 +0100**

___
Replying to thboeckel:
> Replying to rmsyam:
> 
> > Sorry forgott about this :-( Yes I could say, it vanished, did not experience this problem since my last post here.
> 
> Just to satify my curiosity, did you change anything else on your system except the nightly builds of YAM?

Yes I install from time to time new official MorphOS versions. But I think it could rather be (have been) a problem together with OWB which is very memory hungry... e. g. I do get sometimes also crashes when OWB is running together with Designer... and as YAM is always running, it could be that... I test this further and see.

**Comment by jens-maus** [comment]
**Originally on 2013-11-27 09:00:17 +0100**

___
Replying to rmsyam:

> Yes I install from time to time new official MorphOS versions. But I think it could rather be (have been) a problem together with OWB which is very memory hungry... e. g. I do get sometimes also crashes when OWB is running together with Designer... and as YAM is always running, it could be that... I test this further and see.

Yes, this could be easily the reason for your problems. That's exactly the price you pay with an operating system not capable of having separate address spaces per application and no memory protection at all.

**Comment by jens-maus** [comment]
**Originally by _goja@baud.de_ on 2013-11-29 14:38:53 +0100**

___
I 'm not shure if this is the same bug. Yam 2.9-dev 29.11.2013 OS3.9 crashes after sending and then moving the mail to the sent-folder. It arives at the receipient and in the sent drawer, but the index of outgoing, sent and drafts need to be rebuild after the crash.
Guru# 8000000.00000008 and Lastalert shows 02000000.d1000000

**Comment by jens-maus** [comment]
**Originally on 2013-11-29 14:40:50 +0100**

___
Replying to goja@…:
> I 'm not shure if this is the same bug. Yam 2.9-dev 29.11.2013 OS3.9 crashes after sending and then moving the mail to the sent-folder. It arives at the receipient and in the sent drawer, but the index of outgoing, sent and drafts need to be rebuild after the crash.
> Guru# 8000000.00000008 and Lastalert shows 02000000.d1000000

To identify if this is the same problem we would need more information, I am afraid. Please provide the usual information:

  1. Which system are you using
  2. Which YAM version
  3. Is the problem reproducible, does it ALWAYS occur
  4. Please provide any crash log/segtracker output, if possible.

Just stating that something crashes is really not enough, nor does the guru number help in any way.

**Comment by jens-maus** [comment]
**Originally by _goja@baud.de_ on 2013-12-06 10:32:50 +0100**

___
Sorry. I 'm not able to reproduce it anymore and I also dont know what caused this. As the only thing, that is wrong after the crash, is the index, I think my bug is more related to bug #468 (YAM crash while (auto) saving Indexes)

I happend on a: A4000T MC68060RC50 PPC604E@233Mhz 402Mb OS3.9 with YAM 2.9-dev (29.11.13)

**Comment by tboeckel** [comment]
**Originally on 2013-12-08 20:16:11 +0100**

___
Everybody, please keep an eye on this issue. As nobody seems to be able to reproduce it anymore I will close it for the time being. If this issue should happen again then please reopen this ticket.
