### ISSUE TITLE
RFC2047 decoding writes one byte too much for certain strings

### ISSUE THREAD

**Issue by tboeckel** [jens-maus/yam#449]
**Originally on 2013-11-13 08:22:04 +0100**

___
## Summary
With certains mails YAM's RFC2047 decoding writes one byte too much to a destination buffer causing a buffer overrun. The byte is always a single NUL byte. The Wipeout hit points to the mime/rfc2047.c line 877.

## Steps to reproduce
 1. Open the example mail

**Comment by tboeckel** [comment]
**Originally on 2013-11-13 08:24:39 +0100**

___
**Attachment added:** [`rfc2047crash.eml`](https://yam.ch/attachments/449/rfc2047crash.eml) (3.9 KiB)
Example mail causing the Wipeout hit

**Comment by tboeckel** [comment]
**Originally on 2013-11-13 08:24:59 +0100**

___
**Attachment added:** [`wipeouthit.txt`](https://yam.ch/attachments/449/wipeouthit.txt) (3.8 KiB)
Wipeout hit when opening the mail

**Comment by tboeckel** [comment]
**Originally on 2013-11-13 08:54:22 +0100**

___
In (3f27ff3):
 * mime/base64.c: the output buffer for the decoding was always one byte too small to keep the terminating NUL byte. This always went unnoticed even when running tools like Wipeout/Mungwall if the length of the source string was not a multiple of 8. In this case the granularity of AmigaOS' memory system shadowed this buffer overrun. Only for source strings with a length being an exact multiple of 8 bytes the buffer overrun eventually really happend. This closes #449.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 21:43:12 +0100**

___
**Release Note:**
fixed a buffer overrun in the RFC 2014 decoding routines which potentially caused unexpected crashes.
