### ISSUE TITLE
Modified date field when reading

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#45]
**Originally by _thecremlin@users.sourceforge.net_ on 2010-03-03 23:09:21 +0100**

___
Currently the "DATE" field listed in the header information when reading a mail is exactly what the message contains, where as the date field for the message list is the "converted to local time" version. Could the read window display this converted value also as it is sometimes inconvenient and not aways possible to look at the message list?

I'm not asking for the original mail to be changed maybe something like...

2.3/4: Thu, 26 Sep 2002 12:28:09 -0400

2.x: Thu, 26 Sep 2002 12:28:09 -0400 (17:28:09)

**Comment by jens-maus** [comment]
**Originally on 2013-01-19 21:39:20 +0100**

___
Makes sense and should be doable. Times/Dates shown in yam should always be converted to local time if possible.

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 07:40:11 +0200**

___
In (0cf8109):
 * mui/HeaderList.c: the time and date information from the Date: header line will now be converted to local time if the usual "short" headers are shown. For full header display it will be shown as it is. This closes #45.

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 11:43:37 +0200**

___
**Release Note:**
The time and date information from the Date: header line will now be converted to local time if the usual "short" headers are shown. For full header display it will be shown as it is.
