### ISSUE TITLE
YAM craashed after opeinng Find window

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#452]
**Originally by _hypexed@yahoo.com.au_ on 2013-11-18 18:57:50 +0100**

___
## Summary

Opened Find window. Crash

## Steps to reproduce

 1.Clicked Find. :-)

## Expected results

To find. 

## Actual results

A crash. ;-)

## Notes

Note that I am aware of bug #425 but posted a ticket as the crashlog in in a different function.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-11-18 15:08:18 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-11-19_00-54-05.txt`](https://yam.ch/attachments/452/Crashlog_YAM_2013-11-19_00-54-05.txt) (38.0 KiB)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-11-18 15:08:38 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-11-19_00-54-05.2.txt`](https://yam.ch/attachments/452/Crashlog_YAM_2013-11-19_00-54-05.2.txt) (38.0 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-11-18 19:26:10 +0100**

___
#425 is absolutely unrelated to this ticket as it was YAM 2.9-dev crashing, not 2.8p1.

Did you do anything else before the crash? Does YAM always crash when opening the search window, even right after the start?

**Comment by tboeckel** [comment]
**Originally on 2013-11-25 06:29:41 +0100**

___
Bump!

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2013-11-26 16:26:12 +0100**

___
IIRC I would have been reading and replying to emails before the crash. So it wasn't from a fresh YAM start. And no, it doesn't always crash in the find window, It seems I have triggered some random state that causes Find to crash. It is hard to reproduce and I don't recall seeing it since. But I do like to log these entries if I come across a rare crash.In case an overlook is found  that code section.

**Comment by tboeckel** [comment]
**Originally on 2013-12-09 12:31:30 +0100**

___
If I understand you correctly, then this issue is quite hard to reproduce,if at all. I will therefore close this ticket. Please reopen it again if this crash should happen again with YAM 2.9.
