### ISSUE TITLE
Difficulties with addresssbook

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#453]
**Originally by _JDuch@fulladsl.be_ on 2013-11-19 11:58:44 +0100**

___
## Summary
Entering an address form addressbookis more difficult than some NB ago
1. entering an alias in the To field and sending the msg gives an error "unknown alias
2. going to the addressbook, from the messages To field button, selcting the alisa, hitting to, going to the To filed in the message and entering, then sending the msg: same error
3. typing the beginning of a real address or alias, selecting one that appears, then enter, then send, very often will not be sent
see below
## Steps to reproduce
 1.type slowly the beginning of some YAM known address (eg your own)
 2. when the righ line appears highlighted : enter
 3. send

## Expected results
msg sent
## Actual results
error
Bad response from mail server
'smtp.scarlet.be' to command 'RCPT':

550 5.1.1 <Joseph>... User unknown

The message is saved in outgoing (en attente) with as address "Joseph"

## Regression
I understand this is trying with previous NB's ?

## Notes

**Comment by tboeckel** [comment]
**Originally on 2013-11-19 19:35:02 +0100**

___
In (f5d1576):
 * mime/rfc2047.c: restored a formerly replaced memcpy() call as the strlcpy() function omits certain characters due to the length restriction. This closes #453.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 21:46:27 +0100**

___
**Release Note:**
fixed a problem with entering new addresses in the address book because of an incorrect memory copy routine use.
