### ISSUE TITLE
Crash on drag&drop (copy) of more than 15 mails

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#455]
**Originally by @raziel- on 2013-11-20 13:16:08 +0100**

___
## Summary

OK, i have a *very* weird behaviour here

## Steps to reproduce
 1. Choose any mail folder
 2. Mark more than 15 mails
 3. Drag&Drop/Move/Copy them to the Incoming folder

## Expected results

Mails to be copied without a crash

## Actual results

They get copied alright, but immediately afterwards i get a crash

## Regression

Pretty sure it is one, but i'm surprised that this behaviour didn't caught my attention before

## Notes

The weird part is that

1. It adds up, meaning i can copy 14 mails and it will crash if i copy three afterwards (thus going beyond the 16th mail)
2. This affects ALL copy operations in YAM (Move, Copy from the PullDown Menu, Drag&Drop with the mouse, it even crashes after a filter operation moved more than 16 mails)

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-20 13:16:39 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-11-20_12-52-32.txt`](https://yam.ch/attachments/455/Crashlog_YAM_2013-11-20_12-52-32.txt) (36.9 KiB)
Crash after a normal drag&drop

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-20 13:17:37 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-11-20_12-41-41.txt`](https://yam.ch/attachments/455/Crashlog_YAM_2013-11-20_12-41-41.txt) (36.7 KiB)
The same crash but after the filter moved 30 mails

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-20 13:27:50 +0100**

___
Make that 15+ mails.

I get that crash between 16 and 20 mails, very strange

**Comment by jens-maus** [comment]
**Originally on 2013-11-20 16:54:20 +0100**

___
I am sorry, but I cannot reproduce the problem here. What I find strange in the crash log, however, is that it is point to the "FilterMails()" function in YAM. In the description above you are saying you manually drag&drop mails to the incoming folder, but this shouldn't trigger the filter of YAM in any way?!? So something might be special in your installation. So can you please state the exact version you are using? And if possible, please try to reproduce the problem with the latest nightly build. It might be that this already fixes that issue. If not, then please try to reproduce the problem with the debug version and attach the debug output of that version until it crashes.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-20 17:18:28 +0100**

___
Yes, as i said in the original "Notes" it even affects the filter operation.
Whereas the filter itself is properly processed but on moving the mails after the filter operation the crash is there.

I'll add notes about using the 2.8p1 debug and the nightly build

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-20 17:37:43 +0100**

___
**Attachment added:** [`Crashlog_YAM.debug_2013-11-20_17-22-24.txt`](https://yam.ch/attachments/455/Crashlog_YAM.debug_2013-11-20_17-22-24.txt) (37.5 KiB)
Yam.debug 2.8p1

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-20 17:38:12 +0100**

___
**Attachment added:** [`Crashlog_YAM.debug_2013-11-20_17-34-58.txt`](https://yam.ch/attachments/455/Crashlog_YAM.debug_2013-11-20_17-34-58.txt) (36.7 KiB)
YAM.debug 2.9 NB 20.11.2013

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-20 17:39:35 +0100**

___
What i meant with above comment was that even if it's crashing in YAM's filter process it might still be the move operation that is the culprit?

Added YAM.debug crash log 2.8p1 and 2.9 NB 22.11.2013

It does still crash in the NB

**Comment by jens-maus** [comment]
**Originally on 2013-11-20 17:45:11 +0100**

___
Thanks for the crash logs. To further investigate this issue we would, however, need also some debug logs using the debug version. So please run your test again and catch the debug log using "setenv yamdebug @all all" before running yam from the shell. This will output some debug information on the serial console. So please use Sashimi to catch that information.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-20 17:52:46 +0100**

___
I'm sorry for the flood, missed the part where you asked for the exact version.

Version: 2.8p1 [OS4/PPC]
Compilation date: 07.07.2013 (GCC 4.7.1 r6666)

The Buffer was overrun in sashimi...i hope you can work with it
Memguard is running too btw

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-20 17:53:21 +0100**

___
**Attachment added:** [`YAM.log`](https://yam.ch/attachments/455/YAM.log) (64.1 KiB)
Sashimi/Memguard log of YAM.debug 2.8p1

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-21 10:25:16 +0100**

___
Did the log help?
Is there anything else i can provide?

**Comment by tboeckel** [comment]
**Originally on 2013-11-21 21:40:38 +0100**

___
@raziel-
> Did the log help?
> Is there anything else i can provide?

Sorry, but I had no time to take a closer look yet. If Sashimi's buffer does overrun, you can redirect YAM's debug output directly to a file by adding "file:path_to_file" to ENV:yamdebug, i.e. file:ram:t/yamlog.txt to redirect the output to ram:t/yamlog.txt. Of course RAM: is a bad decision for an @all,all log, as this is going to become **very** big.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-21 22:01:47 +0100**

___
Thank you Thore, that did it.

New logs attached

Sorry for being a little pushy, i always forget that people have different work shifts :-)

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-21 22:02:45 +0100**

___
**Attachment added:** [`YAM.Debug.log`](https://yam.ch/attachments/455/YAM.Debug.log) (1357.6 KiB)
Full debug log

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-21 22:03:02 +0100**

___
**Attachment added:** [`YAM_sashimi.out`](https://yam.ch/attachments/455/YAM_sashimi.out) (11.7 KiB)
Sashimi Crash log

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-24 16:56:40 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-11-24_16-54-33.txt`](https://yam.ch/attachments/455/Crashlog_YAM_2013-11-24_16-54-33.txt) (35.8 KiB)
Crash after a normal drag&drop operation

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-24 16:59:43 +0100**

___
Replying to damato:
> What I find strange in the crash log, however, is that it is point to the "FilterMails()" function in YAM.
You are right, i'm sorry
I added two crashlogs that both happened after filermails() to the initial bug report.

I added a log from after a normal drag&drop operation

**Comment by tboeckel** [comment]
**Originally on 2013-11-25 06:28:20 +0100**

___
Did the latest crash happen with 2.8p1 or with 2.9-dev? From the crashlog I can see that the crash is caused by a duplicate Remove() call (0xcccccccc in r9).

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-25 10:13:42 +0100**

___
The latest crashlog was from 2.8p1.

But as you can see in Crashlog_YAM.debug_2013-11-20_17-34-58.txt it also happens the same way in 2.9-dev.

I could do another NB check, if needed?

**Comment by tboeckel** [comment]
**Originally on 2013-11-25 10:48:47 +0100**

___
@raziel-

> I could do another NB check, if needed?

I don't think that will be necessary. I just managed to reproduce this issue on AmigaOS3 with a quick'n'dirty patch to let certain functions behave like in AmigaOS4. This seems to a bug in NListview.mcc. If I should guess I'd say the reason why 16 is the magic number for you is the fact that you can see 15 lines in your main mail list and the vertical scrollbar is visible. If more than 15 mails are removed from a folder then the scrollbar might vanish if less than 15 mails are left in the folder, which then causes the crash because the removed scrollbar is still accessed as an object in a list.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-25 10:59:09 +0100**

___
> I just managed to reproduce this issue on AmigaOS3 with a quick'n'dirty patch to let certain functions behave like in AmigaOS4. This seems to a bug in NListview.mcc.

Ah, sweet :-)

> If I should guess I'd say the reason why 16 is the magic number for you is the fact that you can see 15 lines in your main mail list and the vertical scrollbar is visible. If more than 15 mails are removed from a folder then the scrollbar might vanish if less than 15 mails are left in the folder, which then causes the crash because the removed scrollbar is still accessed as an object in a list.

Not quite :-)
I have 13 lines visible and the vertical scrollbar is indeed there.

I have 29 mails in the folder, 13 are visible, vscrollbar visible
moving 16 (or more) mails
remaining 13, vscrollbar gets removed, but accessed and crashes

Is this what you meant?

**Comment by tboeckel** [comment]
**Originally on 2013-11-25 11:01:24 +0100**

___
@raziel-

> Is this what you meant?

Yes, exactly. Now the problem is that I still have to find the true cause why this removed scrollbar is still accessed ;)

**Comment by tboeckel** [comment]
**Originally on 2013-11-25 16:31:20 +0100**

___
**Attachment added:** [`nlistview_2013_11_25.lha`](https://yam.ch/attachments/455/nlistview_2013_11_25.lha) (8.5 KiB)
Fixed version of NListview.mcc

**Comment by tboeckel** [comment]
**Originally on 2013-11-25 16:32:35 +0100**

___
Please try the attached version of NListview.mcc. It has the same version as the one from the last official release, but a current date in the version string. For me this one fixes the crashes.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-11-25 17:09:35 +0100**

___
Confirmed.

Crash does not happen anymore :-)

Thank you very much for the fast fix

**Comment by jens-maus** [comment]
**Originally on 2013-11-25 17:30:12 +0100**

___
Problem should be fixed with NListview.mcc v19.91+

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 21:51:03 +0100**

___
**Release Note:**
fixed a problem where drag&drop operations caused a crash due to a bug in NListview.mcc.
