### ISSUE TITLE
creating and delete a group crash YAM

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#457]
**Originally by _opionline@yahoo.de_ on 2013-11-23 20:05:08 +0100**

___
creating and delete a group crash YAM
here the steps to reproduce:
1. open the adressbook
2. click the Group button
3. Type the alias and descripton
4. click "OK"
5. the group is in the list (here with abnormal letters, seems something is wrong here)
6. select this group and click delete
7. YAM crash

I add the log as MuOutput-cut.txt
It contain only the first 3 hits.

Used Version:
YAM 2.9-dev (23.11.2013)
Copyright (C) 2000-2013 YAM Open Source Team [OS3/m68k, r7341]
on a A2000/060 OS 3.9 BB2

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-11-23 20:05:28 +0100**

___
**Attachment added:** [`MuOutput-cut.txt`](https://yam.ch/attachments/457/MuOutput-cut.txt) (16.8 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-11-23 20:53:19 +0100**

___
In (471e1c0):
 * mui/AddressBookWindow.c: added a missing initialization of a new address book node. This refs #457.

**Comment by tboeckel** [comment]
**Originally on 2013-11-23 21:47:35 +0100**

___
In (44bd222):
 * mui/AddressBookWindow.c: don't use a local variable for a new address book entry and duplicate it later on as the copy will still point to the local variable. This closes #457.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 21:52:12 +0100**

___
**Release Note:**
fixed a problem where adding/deleting an address book group caused a crash.
