### ISSUE TITLE
support for mailnglists is brooken

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#458]
**Originally by _opionline@yahoo.de_ on 2013-11-23 21:15:45 +0100**

___
the support for mailnglists is brooken:

I have a list in my adressbook. The list part in the .addressbook file looks like follow (my adress changed)

...
@LIST Bowling
Frank Weber <myadress@example.de>
Bowling

Detlef
Martina
Ute
Gabi
Ingo
Karin
Claudi
Isabell Brauns
Kathleen
Frank Weber

@ENDLIST
...

All names have of course a valid entry in the adressbook.

If i type in any of the "to", "cc" or "bcc" fields the string "Bowling" i get as address
"Bowling <Frank Weber <myadress@example.de>>, " which is of course wrong.
It should insert all names from the list and then the names get resolved with the adresses.
in this way it was working with old versions of YAM.

I check my send mails and the result is:
it was working with: YAM/2.9-dev (AmigaOS3; m68k; rv:20130917r7062)
non working version: YAM/2.9-dev (AmigaOS3; m68k; rv:20131018r7180)

Used Version:
YAM 2.9-dev (23.11.2013)
Copyright (C) 2000-2013 YAM Open Source Team [OS3/m68k, r7341]
on a A2000/060 OS 3.9 BB2

**Comment by tboeckel** [comment]
**Originally on 2013-11-25 20:00:12 +0100**

___
Are you sure that 2.9-dev r7062 does work, but r7180 does not? I just checked with YAM 2.7, 2.8 and 2.8p1. Resolving lists is broken since YAM 2.8! Only YAM 2.7 correctly resolves lists to its members.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-11-25 20:19:43 +0100**

___
I send since years all 14 Days some sport results to this list and nothing is changed in the list configuratio.
I just checked my send mails again and on 09.10.2013 (r7062) the send mail goes to all members and on the 18.10.2013 (r7180) not.

**Comment by tboeckel** [comment]
**Originally on 2013-11-25 20:42:10 +0100**

___
Hm, according to my tests r6459 is the one which broke the list resolve process. I did that change 4 days ahead the release of YAM 2.8. Perhaps I shouldn't have coded that late at night back then :)

I will investigate what went wrong there.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-11-25 21:29:13 +0100**

___
I forgot to say i don't type the addresses but i write such mail with an script. The BCC-part looks like follow:
...
Bcc = "Bowling"
...
'WRITEBCC "'Bcc'"'
...

**Comment by tboeckel** [comment]
**Originally on 2013-11-26 09:26:59 +0100**

___
In (6b988d7):
 * mui/RecipientString.c: restored the behaviour of YAM 2.7 when resolving the names of address book mailing lists. Additionally the resolve process did not specify any flag for the kind of entries to search when resolving the recipients. This closes #458.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 21:57:37 +0100**

___
**Release Note:**
restored the behavior of previous versions when resolving the names of address book mailing lists. The new method added in YAM 2.8+ caused certain problems.
