### ISSUE TITLE
wrong german translation

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#459]
**Originally by _opionline@yahoo.de_ on 2013-11-23 21:46:53 +0100**

___
the german translation (string MSG_HELP_EA_ST_REALNAME) contain a "s" to much.

**Comment by tboeckel** [comment]
**Originally on 2013-11-23 21:56:19 +0100**

___
In (b613605):
 * locale/german.ct: fixed a typo. This closes #459.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 21:58:19 +0100**

___
**Release Note:**
fixed a minor typo in the german translation.
