### ISSUE TITLE
Account based preselection window

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#46]
**Originally by _anonymous_ on 2010-03-03 23:11:22 +0100**

___
as i am using the prewiev for deleting spam on the server, it would be nice if this option could be switched on or off for every mail-account seperately. this is because i have only 2 accounts that receive spam, the others are "clean". otherwise, great work, yam is getting better and better ;)

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-06-04 18:26:00 +0200**

___
I'd suggest something like this:

in TCP/IP POP3 prefs add "trigger preselection"
in new mail prefs add to preselection "dpeend on TCP/IP setting"

Of course the naming could be different and also the implementation ;)

This is just an idea how it could work.

**Comment by tboeckel** [comment]
**Originally on 2011-01-01 14:50:03 +0100**

___
In (3032dee):
 * misc: It is now possible to define the mail preselection individually for
  each account. This closes #46. The same applies for the "avoid duplicates"
  setting.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2011-01-02 20:37:57 +0100**

___
Thanks for this one!

Unfortunatelly it does not work. :-/
Prefs are always set back to "never".
Try change them in tcp/ip, press safe/use. Return to prefs and see, all is re-set.

**Comment by tboeckel** [comment]
**Originally on 2011-01-02 22:48:07 +0100**

___
Hm, this one works for me as expected, no matter how often I try to reproduce this issue. However, what was not working as expected is the "Apply remote filters" setting. Just committed the necessary change for that one. Did you mix up these two?

**Comment by tboeckel** [comment]
**Originally on 2011-01-04 19:35:13 +0100**

___
padrino, any news from your side?

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2011-01-05 01:21:14 +0100**

___
Sorry,

I replied, but forgot to login, so maybe my comment is still waiting for moderation...
The problem is still here, with yesterdays verion, with "filter-fix". Sorry, have no access to aOS right now.
The problem is, when I go to prefs and set to "always" it is reset to "never" when I return, *but* when I check and uncheck the filter setting before that and then switch to "always", the setting will stay and will not be reset...

**Comment by tboeckel** [comment]
**Originally on 2011-01-05 07:47:25 +0100**

___
In (4eb387b):
 * MailServers.c: added missing comparison of the preselection mode. This closes #46.
