### ISSUE TITLE
Discarding changes in an edited draft mail deletes the mail

### ISSUE THREAD

**Issue by tboeckel** [jens-maus/yam#460]
**Originally on 2013-11-24 13:14:33 +0100**

___
## Summary
Editing a mail in the drafts folder a second time will delete the mail if there are yet unsaved changes and the user closes the write window and chooses "

## Steps to reproduce
 1. Write a new mail
 2. Save it as draft and close the write window
 3. Edit the draft mail again and make some changes
 4. Close the write window and choose "Discard" in the confirmation requester

## Expected results
The former draft mail should be kept, at least in the state in which the second edit action started. Later changes being made permanent by the auto save feature should of course be kept, too.

## Actual results
The mail is deleted.

**Comment by tboeckel** [comment]
**Originally on 2013-11-24 13:25:02 +0100**

___
In (2f69b31):
 * mui/WriteWindow.c: draft mails being edited a second time are no longer deleted when the user did some changes and closes the write window to discard the changes. This closes #460.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 21:59:41 +0100**

___
**Release Note:**
fixed a problem where draft mails being edited a second time are now no longer deleted when the user did some changes and closes the write window to discard the changes.
