### ISSUE TITLE
Wrong german umlauts in Mail subject and body

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#463]
**Originally by _opionline@yahoo.de_ on 2013-11-25 22:59:07 +0100**

___
YAM's support for german umlauts seems to be broken, steps to reproduce:
1. Click "New".
2. Type as Subject and in the body e.g. "äöü"
3. Click "Send later".
4. go to the outgoing folder and double click the just created mail.
5. see what happen: here i see ??? in the Subject and body.
I attach such mail with xxx as my address.

My charset in the config is set to: ISO-8859-1 + Euro

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-11-25 22:59:41 +0100**

___
**Attachment added:** [`Q4eCRgAGk0w=.001,N`](https://yam.ch/attachments/463/Q4eCRgAGk0w=.001,N) (0.6 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-11-26 06:00:28 +0100**

___
That is absolutely no problem here. Your example mail is displayed 100% correctly for me on WinUAE/AmigaOS3.

Do you have ISO-8859-1 set for both the standard charset (First Steps config page) and for the write charset (Write config page)? It is very important that the standard charset is something the system itself is able to handle. It must NOT be something like UTF8.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-11-26 19:58:09 +0100**

___
Yes both are set too the same charset. Also the setting "EditorCharset" in the "Mixed" section is set to the same charset.
All "CharsetName"s in the "MIME" section are set to the same charset. (BTW : for my taste really to much charset settings)

I check my config and found that the setting "DetectCyrillic" in the "Read" section of the config is the culprit.
But IMHO "DetectCyrillic" should not change german umlauts...

**Comment by tboeckel** [comment]
**Originally on 2013-11-26 20:27:49 +0100**

___
That option is mean for users using the cyrillic alphabet only. The cyrillic charsets use some characters for the cyrillic alphabet which are used for the german umlauts or other accented characters in western european languages. Hence this option should really be activated if and only if the cyrillic alphabet is to be used.

This is the german bubble help for this option:
Versucht mittels einer automatischen Methode in der codesets.library, den benutzten kyrillischen Zeichensatz zu identifizieren. (nur für kyrillische Benutzer relevant)

Jens, perhaps we should add a warning is DetectCyrillic in enabled and any of the selected charsets is not Windows-1251, IBM866 or KOI8-R (these are the 3 charsets being checked by codesets.library).

**Comment by jens-maus** [comment]
**Originally on 2013-11-26 21:07:13 +0100**

___
Replying to thboeckel:

> Jens, perhaps we should add a warning is DetectCyrillic in enabled and any of the selected charsets is not Windows-1251, IBM866 or KOI8-R (these are the 3 charsets being checked by codesets.library).

That's a good idea. I would propose to show such a warning when the user is about to "Save" or "Use" the configuration and the YAM configuration window is about to be closed.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-11-26 21:19:56 +0100**

___
Maybe the Help text should be changed too. First i don't know "kyrillische Benutzer" only "Benutzer kyrillischer Zeichensätze" and second as you can see it is very "relevant" also for other users and sould be changed in something like "Diese Option nur verwenden wenn ein kyrillischer Zeichensatz verwendet wird".

**Comment by tboeckel** [comment]
**Originally on 2013-11-27 08:52:33 +0100**

___
In (9a2dd9f):
 * Config.c: implemented a check to catch the automatic detection of cyrillic charsets while the configured local charset is not cyrillic. As this might cause malformed characters the user is now asked to deactivate the automatic detection. This closes #463.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 22:05:59 +0100**

___
**Release Note:**
when enabling the "detect cyrillic code sets" functionality YAM will now warn the user in case he has setup YAM to use a non-cyrillic code set for as the local charset.
