### ISSUE TITLE
YAM crash while (auto) saving Indexes

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#468]
**Originally by _opionline@yahoo.de_ on 2013-12-05 00:41:49 +0100**

___
YAM crash while (auto) saving Indexes. It also crashes sometimes when i filter E-Mails.
I have no more information but maybe the MuOutput.txt help to find the bug.
If not i can investigate the problem next weekend...

Used version: YAM 2.9-dev (30.11.2013)
Copyright (C) 2000-2013 YAM Open Source Team [OS3/m68k, r7366]

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-12-05 00:42:02 +0100**

___
**Attachment added:** [`MuOutput.txt`](https://yam.ch/attachments/468/MuOutput.txt) (4.7 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-12-06 20:48:53 +0100**

___
Unfortunately the log doesn't help. At least I am not able to extract more information from it than that the crash happens while freeing a mail, which can happen at any time.

If possible then please try to make this crash reproducable and give exact instructions how to archive that.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-12-10 00:10:38 +0100**

___
I do a lot of tests and i think i found a case in which the crash always occur:
1. run YAM and go to the outgoing folder
2. click new and write a new mail, add e.g. you own adress,a subject and some text in the body
3. wait until the mail gets autosaved
4. go to attachments tab and add a attachment
5. click send now
here i get a errormessage and a hit from mutools. both attached to this ticket.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-12-10 00:11:33 +0100**

___
**Attachment added:** [`YAM-Hit.txt`](https://yam.ch/attachments/468/YAM-Hit.txt) (6.4 KiB)

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-12-10 00:11:48 +0100**

___
**Attachment added:** [`Errormessage.txt`](https://yam.ch/attachments/468/Errormessage.txt) (0.2 KiB)

**Comment by tboeckel** [comment]
**Originally on 2013-12-10 08:34:13 +0100**

___
I followed your steps exactly with all kinds of debugging tools running but for me everything is done alright and without any crash. Even enabling/disabling the embedded read pane makes no difference.

Could you please generate a MAIL,FOLDER,UTIL log using the debug version? Perhaps this reveals what is going wrong for you.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-12-10 14:25:15 +0100**

___
I was using the non debug version and IIRC the crash doesn't happen with the debug version. Can you please test the above steps with the non debug version? I can do some more tests tomorrow.
BTW: Sometimes YAM crash here also if i use YAM in a normal way (getting mails, reading mails, filter mails) and quit YAM. Then YAM show the Quit splash window and crashes. After the crash the splash and the main window is still open and i must reset the system.

**Comment by tboeckel** [comment]
**Originally on 2013-12-10 14:31:28 +0100**

___
I did use the non-debug build, although my own build done with the same compiler. But that should not make any difference. But nevertheless, it would be interesting if the debug build is really not affected. So please try to reproduce the crash using the debug build. I will check again with the official non-debug nightly build, too.

Regarding the crash when quitting YAM: no crashlog, no help. Sorry. The plain information "it crashes" is not enough.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-12-11 09:34:33 +0100**

___
The step 1. (see above) should be "run YAM and go to the drafts folder" but only to see in the mainwindow (in background behind the write window) if the autosave is done.

This time i follow the steps 1-5 and quit YAM after step 5.
I write the log to a file and i got the crash now with the debug version too. 
The logfile was more as 77 MB in length because YAM was scanning the send folder from the last crash. I cut a lot of lines (see in the file)
I add the logfile and the crashlog as "YAM-log-cut-11.12.2013.txt" and "YAM-Hit-11.12.2013.txt".

BTW: the log contain a line "timer event received but no timer was processed" but no hint which timer event was received.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-12-11 09:36:15 +0100**

___
**Attachment added:** [`YAM-log-cut-11.12.2013.txt`](https://yam.ch/attachments/468/YAM-log-cut-11.12.2013.txt) (52.8 KiB)

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-12-11 09:36:39 +0100**

___
**Attachment added:** [`YAM-Hit-11.12.2013.txt`](https://yam.ch/attachments/468/YAM-Hit-11.12.2013.txt) (16.0 KiB)

**Comment by jens-maus** [comment]
**Originally on 2013-12-11 14:24:32 +0100**

___
Same here: Please try to reproduce the problem with the latest nightly build first! No reports on old nightly builds please.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2013-12-11 14:54:03 +0100**

___
Same here: 1. Yes it is *always* reproducible! Did you try it???

2. here was not much changes in the nightly builds and it should be possible to reproduce the bug for you too.
If you really want logfiles from the latest nightly build you must wait at least until friday because such debug sesson with the debug version need really much time.

**Comment by jens-maus** [comment]
**Originally on 2014-01-05 00:01:21 +0100**

___
Does this problem still exist with the official 2.9 version? Please try to reproduce and report back.

**Comment by jens-maus** [comment]
**Originally by _trac-robot_ on 2014-01-19 05:57:44 +0100**

___
This ticket was closed automatically by the system.  It was previously set to a Pending status and hasn't been updated within 14 days.
