### ISSUE TITLE
format also the "Mail account" column in the mainlistview

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#471]
**Originally by _opionline@yahoo.de_ on 2013-12-11 14:33:39 +0100**

___
to be consistent YAM should IMHO format also the "Mail account" column in the mainlistview depending on the status of the mail.
Now all unread mails are displayed in bold, but the "Mail account" column is displayed in normal (unbold) letters.

**Comment by tboeckel** [comment]
**Originally on 2013-12-11 14:49:15 +0100**

___
In (20561c2):
 * mui/MainMailList.c: the read/unread marking of mails is now done for all columns. This closes #471.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 22:37:11 +0100**

___
**Release Note:**
fixed the read/unread marking of mails which was not done for all columns of the mail list.
