### ISSUE TITLE
Doubleclick on interenet adresses does not work anymore

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#475]
**Originally by _hpollmeier@dhps.de_ on 2013-12-17 17:08:16 +0100**

___
## Summary
Double click on an internet address does not work anymore

## Steps to reproduce
 1. Double click on an internet address in a mail like the mail asking for support does not work. 
 2. Amiga OS4.1 latest update is used. Muiowb or netsurf are the brousers.

## Expected results
The default brouwser should be startet and connecting to the address in the mail.
## Actual results
no reaction
## Notes

**Comment by tboeckel** [comment]
**Originally on 2013-12-17 19:32:04 +0100**

___
Please provide a GUI log produced with the debug version. And please state the exact versions of YAM and TextEditor.mcc.

**Comment by tboeckel** [comment]
**Originally on 2013-12-17 19:42:03 +0100**

___
Sorry, please make that a GUI,UTIL debug log.

**Comment by tboeckel** [comment]
**Originally on 2013-12-17 21:11:26 +0100**

___
I just tried to reproduce this myself and for me double clicks on links and mail addresses work perfectly. So we really need the debug log. Otherwise we cannot help you.

**Comment by jens-maus** [comment]
**Originally on 2013-12-17 21:36:43 +0100**

___
Here I have verified that double clicking links in a mail works perfectly. So I can only support Thores' suggestion: Please provide a debug log with a debug version of a nightly build.

**Comment by jens-maus** [comment]
**Originally by _hpollmeier@dhps.de_ on 2013-12-18 19:04:25 +0100**

___
I have downloaded the debug from yesterday. It seems to me to be a fault somewhere on the AREXX path . See attached:

Ausführung des AREXX-Kommandos 'YAM:Rexx/gotoURL.yam "www.matrica.de"' feklgeschlagen (Fehler 10). Bitte stellen Sie sicher, dass die Datei existiert und ein korrektes Arexx-Skript ist.

(18.12.2013 10:39:15)

Several other gave s the same result. Looking at the AREXX-Skript it was in place and seemed okay. Should I send you personally the AREXX-Skript in question?

**Comment by jens-maus** [comment]
**Originally on 2013-12-18 22:33:20 +0100**

___
As Thore stated in a private mail to you, I would suggest that you please remove the use of 'gotoURL.yam' completely and install openurl.library instead which will essentially provide the same functionality but with less problems. gotoURL.yam is from times where openurl wasn't supported in YAM, thus it is considered to be obsolete. So please reopen this ticket as soon as you have converted to OpenURL and you are still seeing problems.
