### ISSUE TITLE
All mails was sent from Drafts folder

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#479]
**Originally by _tuomas.hokka@nbl.fi_ on 2013-12-23 16:59:52 +0100**

___
## Summary
All mails was sent from the Drafts folder which should never happen in any case.

## Steps to reproduce
 1. Select Outgoing folder
 2. Select any mail in the Outgoing folder
 3. Press the Send button in main GUI
 4. It will send all mails from both the Outgoing and Drafts folders instead of sending the selected one only

## Expected results
Any email client should never send out anything from the Drafts folder in any case

## Actual results
The opposite what was expected

## Notes

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 17:04:59 +0100**

___
Does this problem still exist when you try to reproduce it with one of the latest nightly builds? (see http://nightly.yam.ch/)

**Comment by jens-maus** [comment]
**Originally by _tuomas.hokka@nbl.fi_ on 2013-12-24 12:38:33 +0100**

___
I wasn't able to reproduce this problem with 2.8p1 or with 2.9dev today anymore. What I did when it happened: 1. Create two mails leaving their windows open, 2. Send both emails one at a time, YAM sends the first one but not the second one which is left in Outgoing folder (this is reproducible every time). 3. Then I was trying to find menu item to send one selected mail only. I tried context menus first and then normal menus. After that I pressed the Send button. I guess this problem might happen only in rare cases. Or toying with menus first somehow affected it.

There's discussion in AmigaWorld.net where somebody else said having the same problem so I'm not the only one: http://amigaworld.net/modules/newbb/viewtopic.php?topic_id=38536&forum=32

**Comment by jens-maus** [comment]
**Originally on 2013-12-25 12:14:10 +0100**

___
I admit that others seem to have reported that too on amigaworld.net. However, I wasn't able to reproduce that in any case here. So this issue seems to require some more attention and testing from your side as well as from our side so that we can identify a procedure that clearly reproduces the problem. Thus, I will file that ticket to be more closely investigated within the 2.9p1 milestone.

So please try to generate a reproducible case and please also use the official 2.9 version to try to reproduce the issue.

**Comment by tboeckel** [comment]
**Originally on 2014-01-14 09:28:00 +0100**

___
Any news on this issue? I admit the Draft handling of YAM 2.8p1 might have had some bugs, but these should be fixed now with YAM 2.9.

**Comment by jens-maus** [comment]
**Originally by _trac-robot_ on 2014-01-29 06:10:57 +0100**

___
This ticket was closed automatically by the system.  It was previously set to a Pending status and hasn't been updated within 14 days.
