### ISSUE TITLE
Can all search data be treated equally, as strings?

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#48]
**Originally by _thetao@users.sourceforge.net_ on 2010-03-04 18:32:59 +0100**

___
When typing search data in the main "Find Message" window or in the Filters->Comparison section of the prefs, I find it awkward that search text doesn't remain available when cycling through different options. For example, if I enter a name under the "From field", that name disappears from the string gadget for most other searches, like Subject, Message Body, Whole Message, etc. With the exception of "Message size", these are all still strings, and I wish YAM would stop second-guessing whether my data applies in this or that situation.

**Comment by jens-maus** [comment]
**Originally on 2013-02-03 15:02:45 +0100**

___
agreed, this should be definitly improved in a future version of yam.

**Comment by tboeckel** [comment]
**Originally on 2013-08-15 08:30:59 +0200**

___
In (9443070):
 * mui/SearchControlGroup.c: the entered search strings is now automatically cloned between the different pages. This closes #48.

**Comment by tboeckel** [comment]
**Originally on 2013-08-15 08:31:37 +0200**

___
**Release Note:**
The entered search string is now automatically cloned between the different pages.
