### ISSUE TITLE
confusing ghosted buttons on the filter page

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#481]
**Originally by _opionline@yahoo.de_ on 2013-12-24 01:26:55 +0100**

___
Steps to reproduce: (sorry some german strings)
1. open the config and go to filters and select a filter.
2. delete all 4 checkmarks at the "Generelle Einstellungen" tab.
3. now set the checkmark at "Remote-Filter".
4. click on any of the remaining 3 buttons.
All 3 remaining buttons gets ghosted and you can't get them unghosted again except you uncheck "Remote-Filter" again and go to the "Aktionen" tab and change some checkmarks (sorry not all checkmarks tested here)
This is really very confusing IMHO.

**Comment by tboeckel** [comment]
**Originally on 2013-12-24 12:54:53 +0100**

___
In (f8a4fc1):
 * mui/FiltersConfigPage.c: toggling the filter's remote state correctly disables certain GUI objects again. This closes #481.

**Comment by jens-maus** [comment]
**Originally on 2013-12-24 13:48:39 +0100**

___
**Release Note:**
fixed a problem where not all checkmarks were correctly ghosted when "remote filter" had been activated.
