### ISSUE TITLE
Crash in the install script preprocessing.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#485]
**Originally by _pferrucci@sfr.fr_ on 2013-12-25 22:48:20 +0100**

___
## Summary

Error in the install script (OS4).

## Steps to reproduce
 1. Run the install-YAM icon from the WB

## Expected results

Installation.

## Actual results

    (help @copyfiles-help)
ERROR: Unmatched parenthesis on line 885.

## Notes

Remove line 887

**Comment by tboeckel** [comment]
**Originally on 2013-12-25 22:49:06 +0100**

___
This issue is the same as #483 and has been fixed already.
