### ISSUE TITLE
ARexx: RESULT in MAILSEND(ALL)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#49]
**Originally by _tactica@users.sourceforge.net_ on 2010-03-04 18:35:46 +0100**

___
In YAM 1.3.3 - 1.3.5, RESULT was set to the number of sent mails, or -1 in case of failure. The former could sometimes come in handy, and should be probably put back.

**Comment by tboeckel** [comment]
**Originally on 2013-01-20 19:50:31 +0100**

___
Replying to damato:

Currently the MAILSEND command just triggers sending the mail in a separate thread and hence cannot return the number of sent mails anymore as the send process most probably is not finished yet when the triggering returns.

However, changing this into a blocking call would require a MUI object to be notified when all mails have been sent. Unforturnately there is no such object to let ARexx commands wait for the completition of a thread. At least currently I don't know of a way how to archive this.

**Comment by jens-maus** [comment]
**Originally by _trac-robot_ on 2013-02-04 07:09:05 +0100**

___
This ticket was closed automatically by the system.  It was previously set to a Pending status and hasn't been updated within 14 days.
