### ISSUE TITLE
MUI4 and YAM tabs/groups show "minimun" width

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#490]
**Originally by _javierdlr@euskalnet.net_ on 2013-12-27 21:04:02 +0100**

___
## Summary
MUI4 and setting the new dynamic tabs Stretch to 0%, under YAM2.10dev such tabs/gruops show with a "minimun" width

## Steps to reproduce
 1. Set in MUI4 Groups Strecht to 0%
 2. Change % to high value (50%) shows group/tabs labels ok

## Expected results
See tab/group labels full text
## Actual results
Not so "tiny" tabs

## Notes

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-12-27 21:05:46 +0100**

___
**Attachment added:** `sgrab000.jpg` (239.4 KiB)
![sgrab000.jpg](https://yam.ch/attachments/490/sgrab000.jpg)
MUI4 groups Stretching 0% ('Estirar')

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2013-12-27 21:06:17 +0100**

___
**Attachment added:** `sgrab001.jpg` (241.6 KiB)
![sgrab001.jpg](https://yam.ch/attachments/490/sgrab001.jpg)
MUI4 groups Stretching at 5% ('Estirar')

**Comment by tboeckel** [comment]
**Originally on 2013-12-27 21:22:39 +0100**

___
Sorry, but this is not a bug of YAM, but of MUI4/AmigaOS4. It will be fixed with the next MUI4 release.
