### ISSUE TITLE
Files "in use" block part of YAM 2.9 install script

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#491]
**Originally by _amigaak2@maxnet.co.nz  (Noel Fuller)_ on 2013-12-27 22:51:31 +0100**

___
## Summary
config, and one or two other files remained "in use" after I had been running YAM 2.8 before installing 2.9, which blocked installation until rectified. Also starting 2.9 failed at first because codesets.library 6.15 was in memory although 6.16 had been installed.

## Steps to reproduce
 1.
 2.

**Comment by jens-maus** [comment]
**Originally on 2013-12-31 13:26:25 +0100**

___
Please note, that the installation script should check if currently a YAM version is running and perhaps request to close it. In addition, at the end it should ask the user to reboot since a common fault seems to be that users tend to start YAM right away but old, outdated third-party classes/libraries are still in use.

**Comment by tboeckel** [comment]
**Originally on 2014-01-28 20:56:40 +0100**

___
In (b6a0eb4):
 * doc/Install-YAM: reworked the Installer script to check for a running instance of YAM. If that is the case then the user is prompted to terminate that instance to make sure that no files which might get overwritten during the installation are locked. After the installation a reboot is recommended to ensure that updated libraries and classes are really flushed from memory. This closes #491.

**Comment by tboeckel** [comment]
**Originally on 2014-01-28 20:57:16 +0100**

___
**Release Note:**
reworked the Installer script to check for a running instance of YAM. If that is the case then the user is prompted to terminate that instance to make sure that no files which might get overwritten during the installation are locked. After the installation a reboot is recommended to ensure that updated libraries and classes are really flushed from memory.
