### ISSUE TITLE
AmigaPL->UTF-8 for sending mails problem

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#492]
**Originally by _amiga@pekdar.net_ on 2013-12-28 00:10:43 +0100**

___
I have found problem with proper handling encding AmigaPL->UTF-8 for sent mails.
I have set encodings AmigaPL for System (Config->First step->Charset AmigaPL) and for Write (Config->Default charset AmigaPL).
After sending mail, all national characters are displayed with negative question mark or others wird characters displayed on any system with any webmail or other e-mail client app.

Please, could You fix this with YAM2.9p1 please?
I had to write my own AREXX script to make proper characters conversion from AmigaPL to UTF-8 for sending mails. I'm useing this script from version YAM2.8 or maybe earlier, can't remember now.

My configuration (short): AmigaOS 3.9+BB1+BB2+patches, PPC 604e, 060.

**Comment by jens-maus** [comment]
**Originally on 2013-12-28 12:27:02 +0100**

___
To properly understand (we are not using polish charsets here) and identify the problem please provide an example email and a step-by-step explanation of how we can reproduce the issue on our own systems. In addition, please provide your own AmigaPL charset translation tables which you might be using with codesets.library.

In addition, please provide screenshots of the actual problem as well as screenshots of how it actually should be.

**Comment by jens-maus** [comment]
**Originally by _amiga@pekdar.net_ on 2013-12-28 20:33:11 +0100**

___
**Attachment added:** `amigapl_codeset_standard.png` (49.0 KiB)
![amigapl_codeset_standard.png](https://yam.ch/attachments/492/amigapl_codeset_standard.png)
AmigaPL charset translation table

**Comment by jens-maus** [comment]
**Originally by _amiga@pekdar.net_ on 2013-12-28 21:50:58 +0100**

___
**Attachment added:** [`export_ODP__AmigaPL_test_e-mail.eml`](https://yam.ch/attachments/492/export_ODP__AmigaPL_test_e-mail.eml) (3.4 KiB)
This is exported e-mail - received ansfer from my tablet

**Comment by jens-maus** [comment]
**Originally by _amiga@pekdar.net_ on 2013-12-28 21:54:32 +0100**

___
**Attachment added:** `mail_from_YAM-Screenshot_2013-12-28-21-17-31.png` (58.2 KiB)
![mail_from_YAM-Screenshot_2013-12-28-21-17-31.png](https://yam.ch/attachments/492/mail_from_YAM-Screenshot_2013-12-28-21-17-31.png)
screenshot from my tablet - received mail from YAM

**Comment by jens-maus** [comment]
**Originally by _amiga@pekdar.net_ on 2013-12-28 21:59:07 +0100**

___
**Attachment added:** `reply_from_tablet.png` (83.7 KiB)
![reply_from_tablet.png](https://yam.ch/attachments/492/reply_from_tablet.png)
screenshot of my reply from my tablet

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2013-12-28 22:17:08 +0100**

___
Replying to damato:
> To properly understand (we are not using polish charsets here) and identify the problem please provide an example email and a step-by-step explanation of how we can reproduce the issue on our own systems. In addition, please provide your own AmigaPL charset translation tables which you might be using with codesets.library.
> 
> In addition, please provide screenshots of the actual problem as well as screenshots of how it actually should be.

I have provided attachment (amigapl_codeset_standard.png) with print screen of the AmigaPL charset translation tables from Wiki.
To reproduce problem You need to:
1. Install and configure AmigaOS 3.9 BB2 with YAM2.9
2. Install this file: ftp://amigaftp:amigaftpqaz@ftp.pekdar.net//OS3.9-update/BoingBag39-2-polski.lha
3. Setup Locale preferences to "Polska" and save configuration.
4. Setup Input preferences (Keboard maps) to "Polska - AmigaPL-USA" and save configuration.
5. Setup YAM with Config -> Firs steps -> System settings -> Charset -> set AmigaPL.
6. Setup YAM with Config -> Write -> Message body -> Default charset -> set AmigaPL.
7. Save YAM configuration.
8. Type New mail and write some Polish national characters, You can do this by pressing and hold down left or right Alt and typeing letters: azsxcnol
Big Polish national letters with left or right Shift button pressed + Alt.
9. Send e-mail to self? f.e. as i did.
10. Open received e-mail f.e. with any webmail under Windows, Linux, or any mobile system with IMAP client as i did on muy tablet (example: mail_from_YAM-Screenshot_2013-12-28-21-17-31.png).
11. Done

My example reply for mail from YAM you can see on attachment reply_from_tablet.png.
I commented on this screenshot what happend and you can see how problem of character encoding/conversion looks like now and how should be.
I hope my example is good enough to explain problem?
If i could do anything more to help you understand the nature od problem, let me know. I'll do my best.

**Comment by jens-maus** [comment]
**Originally on 2013-12-31 13:29:27 +0100**

___
Thanks for the information. I will review the situation shortly. However, please also provide the Arexx script you are mentioning in your original bug description which you seem to use.

**Comment by jens-maus** [comment]
**Originally by _amiga@pekdar.net_ on 2013-12-31 15:28:22 +0100**

___
**Attachment added:** [`AmigaPL2UTF-8.rexx`](https://yam.ch/attachments/492/AmigaPL2UTF-8.rexx) (3.0 KiB)
ARexx script for annotate to make conversion from AmigaPL->UTF-8

**Comment by jens-maus** [comment]
**Originally by _amiga@pekdar.net_ on 2013-12-31 17:12:35 +0100**

___
Arexx script attached. I use Annotate editor to edit text and make conversion AmigaPL->UTF-8 with my script.

**Comment by tboeckel** [comment]
**Originally on 2014-01-14 09:25:52 +0100**

___
Please try to set the external editor's charset to "AmigaPL" (Config window -> Misc -> External editor) and try to reproduce this issue **without** your conversion script. Your script should be obsolete with YAM 2.9, because all the necessary charset conversions are handled by YAM internally already now.

If the "AmigaPL" charset is required anywhere else you should adapt YAM's configuration accordingly, too.

**Comment by jens-maus** [comment]
**Originally by _amiga@pekdar.net_ on 2014-01-17 20:37:33 +0100**

___
**Attachment added:** `Screenshot_2014-01-17-20-22-17.png` (120.2 KiB)
![Screenshot_2014-01-17-20-22-17.png](https://yam.ch/attachments/492/Screenshot_2014-01-17-20-22-17.png)
New test of Polish AmigaPL charset for sending mails

**Comment by jens-maus** [comment]
**Originally by _amiga@pekdar.net_ on 2014-01-17 20:45:56 +0100**

___
Replying to tboeckel:
> Please try to set the external editor's charset to "AmigaPL" (Config window -> Misc -> External editor) and try to reproduce this issue **without** your conversion script. Your script should be obsolete with YAM 2.9, because all the necessary charset conversions are handled by YAM internally already now.
> 
> If the "AmigaPL" charset is required anywhere else you should adapt YAM's configuration accordingly, too.

I did necessary changes as You post with (Config window -> Misc -> External editor) and did setup with AmigaPL. Just after I took test with a new mail and sent it to my second mail account.
I checked received mail from YAM on my tablet and you can see what i saw.
Problem still persist.

**Comment by jens-maus** [comment]
**Originally on 2014-01-17 20:48:34 +0100**

___
> I did necessary changes as You post with (Config window -> Misc -> External editor) and did setup with AmigaPL. Just after I took test with a new mail and sent it to my second mail account.
> I checked received mail from YAM on my tablet and you can see what i saw.
> Problem still persist.

So please verify again: Are you using still using your ARexx script for conversion or have you removed it? Because with 2.9 on you don't have to convert anything to UTF8 because all internal files are already in UTF8 now.

**Comment by jens-maus** [comment]
**Originally on 2014-01-18 01:18:25 +0100**

___
After a deep investigation of the problem you reported I finally found the following:

- To me it really seems to be that you are having YAM incorrectly configured. After setting up YAM correctly I have no problems in converting between AmigaPL<>UTF8. So please make sure that you have the following settings in YAM:
 1. Config->First steps->Charset: set to 'AmigaPL'
 2. Config->Write->Default charset: set to 'UTF-8'
 3. Config->Miscellaneous->Display charset: set to 'UTF-8' (if you have a UTF-8 capable editor, or to 'AmigaPL' otherwise)
 4. Make sure that you are NOT using your ARexx script anymore. With YAM 2.9 that script is obsolete!
* While investigating your report, I identified a minor bug in codesets.library regarding the AmigaPL codeset (but unrelated to your reported issue): the 0xc484 (utf-8) character wasn't correctly converted (it was set to plain 'A') as it was missing in the conversion routines. In the meantime I fixed that, so that in an upcoming codesets.library update the AmigaPL<>UTF8 conversion routines should include all the special characters AmigaPL supports.

As said above, I really believe that the issue reported here is simply a misunderstanding and misconfiguration of YAM because with YAM 2.9 many UTF-8 related things changed and YAM is now perfectly able to send UTF-8 encoded emails itself. So please retry again by following my instructions above for setting up YAM correctly. Then please try to reproduce the problem again and reporting back if the issue is now fixed or if you are still having issues.

**Comment by jens-maus** [comment]
**Originally by _amiga@pekdar.net_ on 2014-01-20 21:11:33 +0100**

___
Replying to damato:
> > I did necessary changes as You post with (Config window -> Misc -> External editor) and did setup with AmigaPL. Just after I took test with a new mail and sent it to my second mail account.
> > I checked received mail from YAM on my tablet and you can see what i saw.
> > Problem still persist.
> 
> So please verify again: Are you using still using your ARexx script for conversion or have you removed it? Because with 2.9 on you don't have to convert anything to UTF8 because all internal files are already in UTF8 now.

I did and i did not use my ARexx script for conversion.

**Comment by jens-maus** [comment]
**Originally on 2014-01-20 21:36:05 +0100**

___
Replying to amiga@…:

> I did and i did not use my ARexx script for conversion.

Is that all information you can provide? Please have a look at my latest comment where I gave instructions how you are supposed to setup YAM so that it should correctly send UTF-8 encoded mails.

**Comment by jens-maus** [comment]
**Originally by _amiga@pekdar.net_ on 2014-01-20 23:03:20 +0100**

___
Replying to damato:
> Replying to amiga@…:
> 
> > I did and i did not use my ARexx script for conversion.
> 
> Is that all information you can provide? Please have a look at my latest comment where I gave instructions how you are supposed to setup YAM so that it should correctly send UTF-8 encoded mails.

Of course not. During your answer in the same time i wrote my answer for last comment. I just want to not leave your question without answer about Arexx conversion. I'm not fast as you with english ;-)

**Comment by jens-maus** [comment]
**Originally on 2014-01-25 22:18:16 +0100**

___
Any news on that item? I thought I give clear instructions (see https://yam.ch/ticket/492#comment:9)  on how to fix the problem which I believe is a simple misconfiguration. Do my instructions solve the problems related to AmigaPL for you?

**Comment by jens-maus** [comment]
**Originally by _Pekdar <amiga@pekdar.net>_ on 2014-01-28 10:30:34 +0100**

___
Something is wrong. I can not send reply. The two times I filled out the form with my reply to comment:9 and 13 and nothing show up?
I always saw the answer "Comments you submit will be routed for moderation" ... and nothing.

What's going on?

**Comment by tboeckel** [comment]
**Originally on 2014-01-28 10:34:57 +0100**

___
Replying to <amiga@…>:

> What's going on?

That happens when you are not logged in. Such comments must be approved by Jens or me before they become visible for everybody. Very obviously you have no account on yam.ch yet.

**Comment by jens-maus** [comment]
**Originally on 2014-01-28 12:28:27 +0100**

___
Replying to <amiga@…>:
> Something is wrong. I can not send reply. The two times I filled out the form with my reply to comment:9 and 13 and nothing show up?
> I always saw the answer "Comments you submit will be routed for moderation" ... and nothing.
> 
> What's going on?

I actually checked the spam filter log files of this webpage and your replies were flagged as being SPAM because you weren't logged in and the spam probability of your answer was >80% for that particular reply. So please generate yourself a login for this web page and log in before you post anything.

However, here is an excerpt of the message you replied recently:

>OK I'll write reply again (but much shorter) for your comment:9
>
>I did all steps as You describe and now I have working conversion AmigaPL->UTF-8 with sent mails!
>Thank You very much for help!
>
>I discover that problem is only with BIG letter 'A' with polish character as You describe before.

Ok, so I guess the problem is finally sovled now. In the end it was a misunderstanding on how to setup YAM to write UTF-8 emails and where you should configure AmigaPL and where UTF-8. But this should be clear now.

In addition, if you install the latest released 6.17 version of codesets.library the problem with the uppercase 'A' should be solved as well.
