### ISSUE TITLE
Crahs in DateStamp2String()

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#493]
**Originally by _pferrucci@sfr.fr_ on 2013-12-29 13:01:47 +0100**

___
## Summary

DSI in 
DateStamp2String()+0x50 (section 2 @ 0x32B2C)

## Steps to reproduce
I don't know. 
What I was doing is: deleting emails, one after another. At some point, maybe on a particular email, YAM crashed.

## Notes

Full crashlog attached

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2013-12-29 12:56:35 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-12-29_11-47-25.txt`](https://yam.ch/attachments/493/Crashlog_YAM_2013-12-29_11-47-25.txt) (32.8 KiB)

**Comment by jens-maus** [comment]
**Originally on 2014-01-05 00:11:51 +0100**

___
Sorry, we are not able to reproduce the problem nor identify the reasons based on your crash log. Can you please try to reproduce the problem/crash with the debug version and report back and send us another crash log performed with the debug version.

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-01-05 12:24:31 +0100**

___
**Attachment added:** [`Crashlog_YAM.debug_2014-01-05_12-17-20.txt`](https://yam.ch/attachments/493/Crashlog_YAM.debug_2014-01-05_12-17-20.txt) (32.2 KiB)
Log done with 2.9 debug

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-01-05 12:32:28 +0100**

___
I found something new:

- it doesn't happen if I delete emails very fast i.e. without letting YAM display the email content in the preview area
- if I delete emails pressing the Del key every half second, YAM displays the email text and after a few emails only, it says in the status area, at the top right of Yam: "deleting 1 message(s)" with a progress bar filled at 100% and saying "1/1".
Then it halts for one second and then GrimReapper appears.

**Comment by jens-maus** [comment]
**Originally on 2014-01-20 21:34:51 +0100**

___
Sorry, but I tried hard to reproduce your problem. In addition, the crash logs you supplied doesn't point at some code where it makes sense that it crashes. So please try to reproduce the issue again and please try to use the latest nightly debug build (http://nightly.yam.ch/). Furthermore, please if you can catch a UTIL debug log (see http://yam.ch/wiki/FAQ/Debugging#BasicsaboutYAMsdebuggingfacilities for more information)

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-01-26 20:11:45 +0100**

___
Fixed in 18-january version

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-01-26 23:09:18 +0100**

___
Sorry no, I completely forgot I had to delete emails to trigger the bug :-(

So I still have crashes but only with the non-debug version!
If I use YAM.debug, I can delete many emails with no problems.

What can we do from here?

**Comment by jens-maus** [comment]
**Originally on 2014-01-26 23:46:06 +0100**

___
Replying to Elwood:

> What can we do from here?

Well, there is actually little we can do as you seem to be the only person facing this problem right now. It is also strange that the debug version seems not to cause any problem for you. So the question remains what exactly triggers the problem. And as we (Thore and me) cannot reproduce your problems I wonder if you could first try to perform a complete new installation of YAM starting from the ground up and see if even a clean install causes crashes or if they are suddenly gone. So can you please try that?

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-01-27 21:54:55 +0100**

___
**Attachment added:** [`Crashlog_YAM.debug_2014-01-27_21-55-02.txt`](https://yam.ch/attachments/493/Crashlog_YAM.debug_2014-01-27_21-55-02.txt) (33.2 KiB)
Crashloh with YAM.debug 2014-01-18

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-01-27 22:00:14 +0100**

___
I reported too fast last time :-(

I have the crash with debug or non debug versions. New crashlog attached with 18 january version.

Now that I see a lot of updates of MUI classes and YAM too, I'll update everything and report soon...

**Comment by tboeckel** [comment]
**Originally on 2014-01-28 08:29:29 +0100**

___
In (8335e38):
 * mui/HeaderList.c: added a NULL pointer check for the rare case that the list of header lines gets updated while the mail pointer is not yet valid. This closes #493.

**Comment by tboeckel** [comment]
**Originally on 2014-01-28 08:31:34 +0100**

___
Replying to Elwood:

> I have the crash with debug or non debug versions. New crashlog attached with 18 january version.

Please try again with the next nightly build. At least the crash should be fixed now, but make sure to take a look at the displayed Date: line. If it is missing then there is still something else going wrong.

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-02-01 19:37:33 +0100**

___
I tried hard to reproduce it with version 30-jan-2014 but couldn't! Good job!

**Comment by jens-maus** [comment]
**Originally on 2014-04-09 00:57:33 +0200**

___
**Release Note:**
fixed a rare crash bug where YAM crashed in DateStamp2String() due to a missing NULL pointer check.
