### ISSUE TITLE
Error with AISS mage file 'folder_archive' since 2.9 .update

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#497]
**Originally by _hypexed@yahoo.com.au_ on 2013-12-30 15:15:08 +0100**

___
## Summary

An error occurred while trying to load the image file 'folder_archive' from directory
'PROGDIR:Resources/Themes/AISS/folder'.

Please make sure that your theme contains all the necessary images as defined in the latest
theme version layout.

## Notes

I have no "folder" directory there. My YAM AISS contains this:

dir YAM:Resources/Themes/AISS/ all
     config (dir)
       config_abook          config_abook_big      config_answer
       config_answer_big     config_filters        config_filters_big
       config_firststep      config_firststep_big  config_identities
       config_identities_big config_lookfeel       config_lookfeel_big
       config_mime           config_mime_big       config_misc
       config_misc_big       config_network        config_network_big
       config_read           config_read_big       config_scripts
       config_scripts_big    config_security       config_security_big
       config_signature      config_signature_big  config_spam
       config_spam_big       config_start          config_start_big
       config_update         config_update_big     config_write
       config_write_big
     icon (dir)
       check_aros.info check.info      check_mos.info  check_os3.info
       check_os4.info  empty_aros.info empty.info      empty_mos.info
       empty_os3.info  empty_os4.info  new_aros.info   new.info
       new_mos.info    new_os3.info    new_os4.info    old_aros.info
       old.info        old_mos.info    old_os3.info    old_os4.info
  .theme  preview

**Comment by tboeckel** [comment]
**Originally on 2013-12-30 17:25:00 +0100**

___
Suitable folder icons have been added already to the nightly build archives. You can copy the "folder" directory from the default theme over to the AISS theme yourself to fix this issue.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2014-01-04 14:30:35 +0100**

___
Thanks.

**Comment by jens-maus** [comment]
**Originally on 2014-04-09 00:59:26 +0200**

___
**Release Note:**
added the missing folder icons to the supplied AISS theme which was complaining about these missing icons.
