### ISSUE TITLE
Crash after recieving a mail.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#499]
**Originally by @broadblues on 2013-12-30 19:23:48 +0100**

___
## Summary

This crash appears to come in two parts which may or mau not be directly related. First a message about YAM rendering on the wrong process pops up on the Workbench, then a GR occurs with AddPath() being the last but one entry in the stack. 

## Steps to reproduce
 1. Run YAM on it's own screen
 2. Go to workbench screen and wait for mail to arrive.
 3. The Message about rendering on the wrong process occurs
 4. The Grim reaper occurs just after the above has auto cleared.

I've only seen the GR after one of the rendering error messages, and these don;t occur everytime a mail is downloaded. 

## Expected results

A new mail is downloaded and added to incoming.

## Actual results

The new mail disappears, ignoring the GR requires a reboot and so the mail is lost. I'm not yet sure whther it's dleted at the server side.

**Comment by jens-maus** [comment]
**Originally by @broadblues on 2013-12-30 19:24:26 +0100**

___
**Attachment added:** [`Crashlog_YAM thread [1]_2013-12-30_18-10-11.txt`](https://yam.ch/attachments/499/Crashlog_YAM%20thread%20[1]_2013-12-30_18-10-11.txt) (3.9 KiB)
Grim Reaper Log

**Comment by jens-maus** [comment]
**Originally by @broadblues on 2013-12-30 20:40:20 +0100**

___
I just looked into my incomming folder to see what mails were there after the last occurance of this crash. 
I see the following two mails, which are idenetical in all but name. 

Q7V4aQAD98Y=.001,R             3528 ----rw-d Today     18:11:53
Q7V3zQAAdJk=.001,N             3528 ----rw-d Today     18:09:17

Only the later email is included in the index, and this later email was the mail downloaded imediatly after reboot. So it seems the mail is not deleted from the server has been downloaded and saved correctly but not added to the index file.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-12-31 12:19:46 +0100**

___
**Attachment added:** [`Crashlog_YAM thread [2]_2013-12-31_10-49-19.txt`](https://yam.ch/attachments/499/Crashlog_YAM%20thread%20[2]_2013-12-31_10-49-19.txt) (34.1 KiB)
Same crash with different thread

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2013-12-31 12:21:41 +0100**

___
I can confirm this crash, just got it myself this morning.
Yam tried to download a mail, but was stuck with the "Checking mail from..." message in it's main window.

The mail was never downloaded.
I had to reset because CPU useage went up to 100% and draw the system unuseable.

The crash happened in another YAM thread, though

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2014-01-12 23:59:50 +0100**

___
Now i lost a mail aswell.

The already mentioned crash came up again which i resumed in GrimReaper.

On (automatic through filter) moving that mail to it's subdir another crash happened.
(Something to do with "TransferMail")

I'm not sure if the mail was downloaded already (and on my HDD), at least i cannot find it.
It was deleted from the server though.

Unfortunately the system was already unstable so it did not save that crashlog.

If i ever get another chance, i'll try to save the second crashlog
(If you need it that is? I was told that after resuming one crash, a followup can't be trusted due to the system already being messed up?)

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2014-01-13 08:56:41 +0100**

___
Mail found.

Index of Incoming wasn't updated after the second crash.
A reboot and new start of YAM brought the mail back.

Another tiny bit of information, albeit unrelated.
The crash happened with the (already per mail) reported MUI_Redraw error up front.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2014-01-13 08:57:13 +0100**

___
**Attachment added:** `MUI_Redraw() task mismatch_000.png` (16.7 KiB)
![MUI_Redraw() task mismatch_000.png](https://yam.ch/attachments/499/MUI_Redraw()%20task%20mismatch_000.png)
MUI_Redraw error

**Comment by tboeckel** [comment]
**Originally on 2014-01-13 09:17:48 +0100**

___
Please switch to YAM 2.10-dev for the time being to avoid this bug.

**Comment by tboeckel** [comment]
**Originally on 2014-01-14 09:19:30 +0100**

___
In (db7bb7d):
 * tcp/pop3.c, tcp/smtp.c: added some checks for correctly resolved incoming and sent folders. This refs #499.

**Comment by tboeckel** [comment]
**Originally on 2014-01-14 09:21:18 +0100**

___
Please try to reproduce this issue with the next nightly build. If mails are not received at all then please provide a FOLDER debug log created with the debug version.

**Comment by jens-maus** [comment]
**Originally by _trac-robot_ on 2014-02-02 06:03:14 +0100**

___
This ticket was closed automatically by the system.  It was previously set to a Pending status and hasn't been updated within 14 days.
