### ISSUE TITLE
YAM fail to check signed e-mails from User-Agent: IceDove

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#5]
**Originally by _amigasurfer@users.sourceforge.net_ on 2010-03-03 15:01:22 +0100**

___
If I try to check the signatur of an e-mail mit quoted printable and the signatur inside the textbody, e.g. generated with User-Agent: IceDove 1.5.0.14pre (X11/20071018), YAM allways says invalid signatur.

The problem is, YAM gives the file directly to PGP without converting the quoted printable back first.

Attached you will find an example e-mail.

If I copy this e-mail and convert all quoted printable by hand and doesn't makes a mistake in doing this, then PGP does check the signatur good.

PS: The required pgp-key 0x16AC66D9 can be found at the common keyservers. Same for my key needed for the other bugreport.

**Comment by jens-maus** [comment]
**Originally by _amigasurfer_ on 2010-03-03 15:02:36 +0100**

___
**Attachment added:** [`OIt++AAGW6Q=.001,RA`](https://yam.ch/attachments/5/OIt++AAGW6Q=.001,RA) (4.8 KiB)
signed e-mail with quoted printable and the sig inside the textbody - Moved from SF. Original author: amigasurfer

**Comment by tboeckel** [comment]
**Originally on 2010-03-03 15:03:27 +0100**

___
For me PGP also fails if I pass it the decoded message part from T:.

I think the mail itself is broken. It contains the usual "-----BEGIN PGP
SIGNED MESSAGE-----" line, but no "-----END PGP SIGNED MESSAGE-----". The
signature seems to be complete.

If I strip everything but the signature PGP tells me that a newer version
is needed to check this signature. I used PGP 2.6.3i.

**Comment by jens-maus** [comment]
**Originally by _amigasurfer_ on 2010-03-03 15:04:03 +0100**

___
Yesterday I read somewhere that "-----END PGP SIGNED MESSAGE-----" isn't
explicit needed, if the signature seamless follows the signed text with
"-----BEGIN PGP SIGNATURE-----". This line is then equal to "-----END PGP
SIGNED MESSAGE-----". But I read yesterday so many forums and google
results. I can't remember where I read this and can't find it again.

I'm astonished that you could add the public key 0x16AC66D9 to your
keyring with PGP 2.6.3i. The key is a DSS/Diffie-Hellman key. You need PGP
5.1 for this. PGP 2.6.3i can only handle RSA keys.

**Comment by tboeckel** [comment]
**Originally on 2012-10-26 22:29:05 +0200**

___
This should finally be fixed by the next nightly build (see r6350 to r6359).
