### ISSUE TITLE
Problems with filter IN option

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#500]
**Originally by @chris-y on 2014-01-01 12:07:54 +0100**

___
When a filter has been set with an IN condition and a filename, upon calling up that filter the filename selection and pop-up/edit gadgets are ghosted.  This is on OS4.

Cycling to a different option (eg >) and then back to IN enables the two gadgets, however the pop-up/edit one does not work correctly - it opens a NotePad window with a name of [(null)] and no content.

The filter itself appears to work OK, it is only the GUI functionality which is faulty.

**Comment by tboeckel** [comment]
**Originally on 2014-01-01 12:54:38 +0100**

___
In (e4cb093):
 * mui/FiltersConfigPage.c: fixed the broken reactivation of some objects in case a filter takes the search patterns from a file. This refs #500.

**Comment by tboeckel** [comment]
**Originally on 2014-01-01 13:09:48 +0100**

___
In (0193211):
 * mui/SearchControlGroup.c: for empty IN pattern files the edit button will be disabled now. Only the popup button will be enabled to let the user select an existing pattern file. This closes #500.

**Comment by tboeckel** [comment]
**Originally on 2014-01-01 13:12:13 +0100**

___
**Release Note:**
For empty IN pattern files the edit button will be disabled now. Only the popup button will be enabled to let the user select an existing pattern file.
