### ISSUE TITLE
YAM crashes when auto-saving emails

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#501]
**Originally by @chris-y on 2014-01-01 12:08:00 +0100**

___
YAM crashes when auto-saving emails.  This might be related to #470 and/or #468.
Crashlog attached.

**Comment by jens-maus** [comment]
**Originally by @chris-y on 2014-01-01 01:30:52 +0100**

___
**Attachment added:** [`Crashlog_YAM_2013-12-31_23-42-29.txt`](https://yam.ch/attachments/501/Crashlog_YAM_2013-12-31_23-42-29.txt) (4.7 KiB)
Crashlog

**Comment by jens-maus** [comment]
**Originally on 2014-02-04 10:23:36 +0100**

___
As this ticket is hanging around for a while now and time has passed please try to verify that the problem still exists when using one of the latest nightly builds.

**Comment by jens-maus** [comment]
**Originally by @chris-y on 2014-02-04 13:13:04 +0100**

___
I haven't seen the problem for ages, even using the old build.  Guessing one of the MUI4 or class updates might have fixed it.

**Comment by tboeckel** [comment]
**Originally on 2014-02-04 13:15:04 +0100**

___
Ok, closing this one.
