### ISSUE TITLE
Filters lost MoveTo folder specs on conversion to 2.9

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#502]
**Originally by _nbache2@mail.dk_ on 2014-01-02 23:19:22 +0100**

___
## Summary
All my filters are of the form:

IF [some header field] matches [something]
AND
Status different from new/unread
then move to [some folder]

When I upgraded from 2.8p1 to 2.9, all the target directories were lost; the config file had MoveToFolderIDs of 00000000 for all of them.

I had to re-select all the destination folders in the GUI and re-save the config.

## Steps to reproduce
 1. In 2.8p1, create some filters of the above form.
 2. Upgrade to 2.9.

## Expected results
Filters still contain the destination folders they used to, config file should have been converted to use the correct folder IDs in the new MoveToFolderID fields.

## Actual results
No destination folders in the GUI, IDs 00000000 in the config file.
## Notes
Not sure what can reasonably be done about this now, except maybe to warn people and instruct them on how to repair the issue if it happens to them (i.e. if anybody but me has filters with MoveTo defined ;-)).

**Comment by tboeckel** [comment]
**Originally on 2014-01-06 11:38:10 +0100**

___
In (8fbd346):
 * Config.c: the configuration version is now remembered globally and any upgraded configuration will be saved after the validation to make the upgraded options permanent. Furthermore any newly resolved folder ID during the upgrade will also trigger the saving of the new configuration. This closes #502.

**Comment by jens-maus** [comment]
**Originally on 2014-04-06 16:42:23 +0200**

___
**Release Note:**
fixed the folder conversion routines to not loose connection to the destination folder in case of a move-to-folder operation.
