### ISSUE TITLE
Filters with AND in 2.8p1 were converted to "if one or more conditions met" in 2.9

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#503]
**Originally by _nbache2@mail.dk_ on 2014-01-02 23:35:58 +0100**

___
## Summary
All my filters move mails to specific directories if two conditions are both true (see previous ticket 502 for details).

When upgrading to 2.9, they were converted to only demand "one or more" conditions to be met.

As my second condition is always "Status <> new/unread", this meant that the whole (read) content of my inbox matched the first filter in my collection and was moved to the corresponding folder (luckily one with only old mails in it, so easily fixed manually).

I had to go through all my filters and manually set the top cycle gadget to "all" instead of "one or more".

## Steps to reproduce
 1. Create some filters with two criteria connected by "and" in 2.8p1.
 2. Upgrade to 2.9.

## Expected results
The filters should have "all" in the cycle gadget.

## Actual results
They had "one or more".

## Notes
As with ticket 502, it's probably already too late to actually fix this, but people can be warned and told how to repair the resulting setup.

**Comment by tboeckel** [comment]
**Originally on 2014-01-06 11:47:43 +0100**

___
In (b142733):
 * Config.c: correctly handle the different meaning of the filter's rule combination mode when upgrading from older configuration versions. This closes #503.

**Comment by jens-maus** [comment]
**Originally on 2014-04-06 23:22:33 +0200**

___
**Release Note:**
fixed the incorrect conversion of filters from older YAM versions when using an AND combination of rules.
