### ISSUE TITLE
New field for alternative Sent folder in identities not always ghosted when it should

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#504]
**Originally by _nbache2@mail.dk_ on 2014-01-02 23:50:38 +0100**

___
## Summary
The new string gadget for the name of the alternative Sent folder, on the second tab page of the Identities sub-window in the config editor is initially ghosted when the check box above it is not checked. But if you have multiple identities, and switch between them with that tab page open, it is not ghosted on the next identity. It gets ghosted again if you switch to another tab page and back again, and also if you check the checkbox and uncheck it again.

## Steps to reproduce
 1. Create more than one identity.
 2. Select the first one.
 3. Switch to the second tab page; the string gadget for alternative Sent folder name is ghosted.
 4. Still with the same tab page open, select the second identity and observe the string gadget.

## Expected results
The string gadget should still be ghosted.

## Actual results
The string gadget is no longer ghosted.

## Notes

**Comment by jens-maus** [comment]
**Originally on 2014-01-05 00:33:43 +0100**

___
That issue seems to be related to the MUI4 version of OS4. Thus a future MUI4 update for OS4 will take care of that. If it is fixed, this ticket will be closed by thore.

**Comment by tboeckel** [comment]
**Originally on 2014-01-09 08:24:55 +0100**

___
I just opened BZ 8630 to cover this issue.

**Comment by tboeckel** [comment]
**Originally on 2014-01-09 08:48:31 +0100**

___
This issue should be fixed now. Please refer to BZ 8630 for details.
