### ISSUE TITLE
multi assigm

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#505]
**Originally by _mc4834@mclink.it_ on 2014-01-05 18:28:02 +0100**

___
Amiga os 3.x, YAM 2.9

Since 2.9 upgrade multi assign doesn't work.
I have codesets.library installed in "path_to_dir", outside LIBS: and assigned with: 
ASSIGN ADD LIBS: path_to_dir

**Comment by tboeckel** [comment]
**Originally on 2014-01-05 19:28:50 +0100**

___
What **exactly** is not working? Is it possible that you have another copy of codesets.library installed in any other path of you LIBS: assign?

**Comment by jens-maus** [comment]
**Originally by _mc4834@mclink.it_ on 2014-01-05 21:57:51 +0100**

___
The program fails to start.
With error message: prerequisite missing.
But, if I do (from CLI):
version codesets.library
it works. (6.5)
And it worked before, until the upgrade.

**Comment by tboeckel** [comment]
**Originally on 2014-01-05 22:13:20 +0100**

___
Ok, and what about my question regarding possible multiple copies of codesets.library? Did you check every path the LIBS: assign points to?

Please note that with a multiassign only the very first version of a library will be found and used, no matter if further and more recent versions exist in other parts of LIBS:.

**Comment by jens-maus** [comment]
**Originally by _mc4834@mclink.it_ on 2014-01-06 10:19:22 +0100**

___
No problems for that.
Just one installation of codesets.library is present.
During YAM upgrade (expert mode) I skipped codesets installation because it was yet installed.
Maybe I can try to upgrade to a previous version (2.7) to see if the problem was older...

**Comment by tboeckel** [comment]
**Originally on 2014-01-06 10:20:58 +0100**

___
So this all happened because you explicitly forbade the installation of the new version, correct?

I will close this ticket then.

**Comment by jens-maus** [comment]
**Originally on 2014-01-06 11:04:27 +0100**

___
Replying to mc4834@…:

> No problems for that.
> Just one installation of codesets.library is present.
> During YAM upgrade (expert mode) I skipped codesets installation because it was yet installed.

Well, code sets.library was perhaps installed, but not in the correct version! YAM 2.9+ requires code sets.library version 6.16 to work. So please reinstall YAM 2.9 and DO NOT skip installation of any third-party component.

> Maybe I can try to upgrade to a previous version (2.7) to see if the problem was older...

No, simply reinstall YAM 2.9 and install ALL third-party libraries as they are delivered by YAM.

In addition, your reported error message should have clearly stated that you need a newer version for YAM 2.9 to work!
