### ISSUE TITLE
.emailcache with quotes

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#508]
**Originally by _antibike@web.de_ on 2014-01-14 09:32:54 +0100**

___
Emails welche von meinem Arbeitgeber kommen haben gegenüber anderen Emails
die Besonderheit, dass der From Eintrag einen Inhalt mit Anführungszeichen
beinhaltet. z.B. diesen hier.

  From: "Nachname, Vorname" <Vorname.Nachname@arbeitgeber.com>

Das ganze landet dann wie folgt im .emailcache:

  "Nachname, Vorname" <Vorname.Nachname@arbeitgeber.com>

Wenn ich nun eine neue Email schreibe und die sonst sehr praktische
automatische Ergänzung zuschlägt, dann kommt folgendes dabei heraus:

  "\"Nachname, Vorname\"" <Vorname.Nachname@arbeitgeber.com>

Das ganze führt dann aber spätestens beim sender zu folgendem Problem:

  Unknown alias or name: "\"Nachname, Vorname\""
  <Vorname.Nachname@arbeitgeber.com>.

  YAM couldn't find the e-mail address of this
  recipient in the address book. Please verify the
  spelling.

**Comment by jens-maus** [comment]
**Originally on 2014-01-14 11:30:54 +0100**

___
Can you please provide an example raw email for investigation of the issue. We really have to make sure how these emails are encoded when you receive them. If there is too much private information in one of these emails please send us this email in private mail.

**Comment by tboeckel** [comment]
**Originally on 2014-01-15 10:48:03 +0100**

___
In (aef630f):
 * mui/YAMApplication.c: the address cache now saves unquoted real names and removes possible quotes upon loading the cached addresses. This closes #508.

**Comment by jens-maus** [comment]
**Originally on 2014-01-15 11:09:46 +0100**

___
As this issue is fixed now, please retry with the next nightly build if your still have problems with quoted real names in mails and the address cache.

BTW: Bitte generier dir einen Account auf yam.ch mit deinem Realnamen damit in Zukunft die Ticketzuordnung eindeutiger/einfacher ist.

**Comment by jens-maus** [comment]
**Originally on 2014-04-07 22:59:59 +0200**

___
**Release Note:**
fixed a bug where quoted real names in an email address string was incorrectly added to YAMs emailcache mechanism.
