### ISSUE TITLE
Certain lines in a QP encoded mail get duplicated

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#509]
**Originally by _frank@bussinet.de_ on 2014-01-14 20:09:52 +0100**

___
## Steps to reproduce
1. Import and read the attached mail

## Expected results
The last two lines should read "viele Grüße\nfoo"

## Actual results
The "foo" of the original last line gets some strange characters appended as well as a second line reading "foo".

**Comment by tboeckel** [comment]
**Originally on 2014-01-14 20:10:24 +0100**

___
**Attachment added:** [`example.eml`](https://yam.ch/attachments/509/example.eml) (1.9 KiB)
Example mail

**Comment by jens-maus** [comment]
**Originally on 2014-01-17 21:00:33 +0100**

___
In (8dddcf0):
 * YAM_RE.c: fixed a bug in the mail parsing routines where it could have
  happened that YAM was parsing over the boundaries of a readable MIME
  part if the text contained many UTF8 convertable characters. This resulted
  in arbirary characters being added at the end of a displayed text. 
  This closes #509.

**Comment by jens-maus** [comment]
**Originally on 2014-04-09 01:00:52 +0200**

___
**Release Note:**
fixed a bug in the mail parsing routines where it could have happened that YAM was parsing over the boundaries of a readable MIME part if the text contained many UTF8 convertable characters.
