### ISSUE TITLE
D&D of mails as attachments won't show the attachment list

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#510]
**Originally on 2014-01-15 09:37:01 +0100**

___
## Summary
When using drag&drap to drag a mail as an attachment into the attachment list of a write window the attachment list on the first register page of the write window won't get visible/updated.

## Steps to reproduce
 1. open a write window and change to the attachment list
 2. D&D a mail into the attachment list
 3. change to the first tab of the register group where the texteditor is located
 4. notice that there is no small attachment list shown at the right of the To/Cc/BCc string gadgets

## Expected results
As soon as the D&D operation is finished YAM should make the small attachment list visible in the first tab of the register group of the write window.

**Comment by tboeckel** [comment]
**Originally on 2014-01-15 11:34:53 +0100**

___
In (516494c):
 * mui/WriteAttachmentList.c: set a name for dropped mails just like for forwarded mails. This refs #510.

**Comment by tboeckel** [comment]
**Originally on 2014-01-15 12:11:55 +0100**

___
In (f6d5440):
 * YAM_WR.c, mui/WriteAttachmentList.c, mui/WriteWindow.c: all attachments are now added by a central method to ensure that they appear in both list objects. This closes #510.

**Comment by tboeckel** [comment]
**Originally on 2014-01-15 12:14:29 +0100**

___
**Release Note:**
All attachments are now added by a central method to ensure that they appear in both list objects.

**Comment by jens-maus** [comment]
**Originally on 2014-01-15 13:00:39 +0100**

___
**Release Note:**
Fixed a bug where the small attachment list in the first tab of the write window wasn't updated if attachments were added in the 'attachments' tab.
