### ISSUE TITLE
clone attachment list open wrong attachment

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#511]
**Originally by _antibike@web.de_ on 2014-01-15 10:39:27 +0100**

___
## Summary
Wenn eine email mehr als nur einen Anhang hat, dann kann man in der "clone attachment list" jeden beliebigen Anhang doppelt anklicken, es wird trotzdem immer der Anhang geöffnet der in der echten Attachment list aktiv ist.

## Steps to reproduce
 1. open new mail (write window)
 2. attach more then one attachment
 3. try too open diffent attachments using the small clone attachment list
 4. make another entry active using the real attachment list
 5. try again to open diffent attachments using the clone attachment list

## Expected results
Es sollte in der clone attachment list immer der Anhang geöffnet werden, welcher doppelt geklickt wird.

## Actual results
Es wird immer der Anhang geöffnet der in der echten Attachmentlist aktiv ist

**Comment by tboeckel** [comment]
**Originally on 2014-01-15 11:30:58 +0100**

___
In (3d1485d):
 * mui/WriteWindow.c: pass an additional parameter to the method to display a double clicked attachment entry to respect the clicked list object. This closes #511.

**Comment by tboeckel** [comment]
**Originally on 2014-01-15 11:42:42 +0100**

___
**Release Note:**
The tiny attachment list on the write window's first page handles double clicks correctly now instead of showing the selected entry in the main attachment list on the second page.
