### ISSUE TITLE
Using URLOpen in MIME, shows requester with additional "

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#513]
**Originally by _javierdlr@euskalnet.net_ on 2014-01-16 12:34:25 +0100**

___
## Summary
Just added as MIME text/html (URLOpen file://%s).
On the read message window when using context menu 'Display...' and choose the HTML document part it shows the URLOpen requester but the file/url shows " at the end of string.
See pics attached with YAM MIME config and OpenURL requester.

BTW the workaround is to use URLOpen '"file://%s (add '" in front of file://)

## Steps to reproduce
 1. See pics attached
 2.

## Expected results
Open the HTML document without problems
## Actual results
Browser complains about non existant file ('cos it has " at the end of string)
## Notes
The workaround i found is to use URLOpen '"file://%s (add '" in front of file://)

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2014-01-16 12:35:13 +0100**

___
**Attachment added:** `sgrab001.png` (84.0 KiB)
![sgrab001.png](https://yam.ch/attachments/513/sgrab001.png)
my text/html YAM MIME settings

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2014-01-16 12:36:43 +0100**

___
**Attachment added:** `sgrab002.png` (12.8 KiB)
![sgrab002.png](https://yam.ch/attachments/513/sgrab002.png)
URLOpen shows " at the end of file/url string

**Comment by tboeckel** [comment]
**Originally on 2014-01-30 11:38:25 +0100**

___
In (478db5c):
 * YAM_RE.c: possible prefixes and postfixes of placeholders (i.e. file://%s) are now correctly quoted as a complete word instead of the inserted string for the placeholder only. This closes #513.

**Comment by tboeckel** [comment]
**Originally on 2014-01-30 11:38:59 +0100**

___
**Release Note:**
 possible prefixes and postfixes of placeholders (i.e. ​file://%s) are now correctly quoted as a complete word instead of the inserted string for the placeholder only.

**Comment by tboeckel** [comment]
**Originally on 2014-01-30 11:43:12 +0100**

___
One final addition from my side. I didn't check this solution with AmigaOS4's URLOpen command yet, but I am sure this issue is fixed by the latest change. If the trailing quote character should nevertheless occur in the URL being passed to the browser then this is definitely a bug of URLOpen and not of YAM. YAM will now quote its placeholders like '"file://path_to_file"' instead of 'file://"path_to_file"'.

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2014-01-31 13:18:09 +0100**

___
Fixed. Works fine, I don't have to add " in front of file:// in MIME config

THX
