### ISSUE TITLE
Crash when apply a "remote filter"

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#516]
**Originally by _s.hawamdeh@teletu.it_ on 2014-01-29 18:59:44 +0100**

___
Seems quite easy to reproduce, in a clean installation of YAM just go in Prefs/Filters and active the "Remote filter" button

It crash on latest nighty (2014-01-29)

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2014-01-29 19:01:43 +0100**

___
**Attachment added:** [`Crashlog_YAM_2014-01-29_19-24-25.2.txt`](https://yam.ch/attachments/516/Crashlog_YAM_2014-01-29_19-24-25.2.txt) (28.8 KiB)

**Comment by tboeckel** [comment]
**Originally on 2014-01-29 20:04:16 +0100**

___
In (4ae1f0a):
 * mui/FiltersConfigPage.c: make sure that all objects are disabled in case no filter is defined at all. This closes #516.
