### ISSUE TITLE
Transparence in "Make a Donation" button

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#521]
**Originally by _s.hawamdeh@teletu.it_ on 2014-02-02 16:13:03 +0100**

___
The current "Make a Donation" button was created without consider the trasparence borders, this is pretty visible using a different MUI theme

Would be cool to paint a better one with a proper "transparence effect" :-)

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2014-02-02 16:13:26 +0100**

___
**Attachment added:** `about.png` (86.6 KiB)
![about.png](https://yam.ch/attachments/521/about.png)

**Comment by tboeckel** [comment]
**Originally on 2014-02-02 20:08:50 +0100**

___
In (46ce59f):
 * mui/AboutWindow.c: use the input handling of Area.mui instead of the one done by NBitmap.mcc to avoid the duplicate background drawing. This closes #521.

**Comment by jens-maus** [comment]
**Originally on 2014-04-09 00:47:28 +0200**

___
**Release Note:**
fixed a minor bug regarding the transparency settings of the donate image in the About window of YAM.
