### ISSUE TITLE
Add possibility to directly specify the window number in READINFO&Co

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#522]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2014-02-04 07:15:32 +0100**

___
## Problem
There is currently a limitation in the READINFO/READPRINT/READCLOSE/READSAVE commands work with having multiple read windows open. The same applied to the write window routines.

## Analysis
A user have to currently explicitly switch between windows via MAILREAD WINDOW X or via MAILWRITE WINDOW X in the write window case instead of directly specifying the window number/reference these commands should be performed on.

## Enhancement recommendation
To improve handling of multiple read/write windows via ARexx it would be good to have an additional WINDOW parameter for every Arexx command operating on a specific read/write window. This parameter could be an integer with the window number or a unique reference number (even better).

**Comment by jens-maus** [comment]
**Originally on 2014-02-04 10:22:14 +0100**

___
According to the official API documentation this should not be the case. See here:

[[Documentation/ARexx API/MAILREAD]]

All you potentially have to do is call MAILREAD without any WINDOW parameter and it should immediately open a new read window and return the number/index of the read window. Then you can use this index in subsequent ARexx commands.

So please verify that this still works and if not this should be rather a bug report than an enhancement request.

**Comment by tboeckel** [comment]
**Originally on 2014-02-04 10:30:59 +0100**

___
Although you can open several read windows using MAILREAD and get a window number as return value the READCLOSE command takes no parameter and will always close the last opened read window. Any further read window cannot be closed afterwards via ARexx as there is only one global ActiveRexxRMData pointer.

The same limitation applies for all write windows opened via ARexx. All commands following i.e. MAILWRITE will implicitly reference the last opened write window. This is major restriction in case more than one write window was spawned via ARexx. Here we also have only a single global ActiveRexxWMData pointer.

**Comment by jens-maus** [comment]
**Originally on 2014-02-04 10:58:49 +0100**

___
Replying to tboeckel:
> Although you can open several read windows using MAILREAD and get a window number as return value the READCLOSE command takes no parameter and will always close the last opened read window. Any further read window cannot be closed afterwards via ARexx as there is only one global ActiveRexxRMData pointer.
> 
> The same limitation applies for all write windows opened via ARexx. All commands following i.e. MAILWRITE will implicitly reference the last opened write window. This is major restriction in case more than one write window was spawned via ARexx. Here we also have only a single global ActiveRexxWMData pointer.

I agree that the current solution is somewhat suboptimal. However, one can perfectly use YAM with multiple read/write windows by always switching between them via the following example pseudo-code sequence:

```
/* Open two read windows */
firstWindowNr = MAILREAD QUIET
secondWindowNr = MAILREAD QUIET

/* Print the body of the first read window */
MAILREAD QUIET WINDOW firstWindowNr
READPRINT 1

/* Print body of second read window */
MAILREAD QUIET WINDOW secondWindowNr
READPRINT 1

/* Close first read window */
MAILREAD QUIET WINDOW firstWindowNr
READCLOSE

/* Close second read window */
MAILREAD QUIET WINDOW secondWindowNr
READCLOSE
```

Of course, always having to switch via MAILREAD between the windows seems to be somewhat awkward. In addition, there is a limitation in case two parallel running ARexx scripts are running. However, there are potentially hundreds of situations where parallel scripts might do something wrong/incorrect. Nevertheless, I agree that we could do better here and thus scheduling this to "future" version seems to be appropriate to me so that we can discuss its priority later again and assign it to a future YAM version.

I will also change the ticket content to better match the purpose.

**Comment by tboeckel** [comment]
**Originally on 2014-02-04 11:02:10 +0100**

___
I admit I didn't really notice that MAILREAD can also be used to switch between multiple read windows.

Christoph, does this solution solve your problem? As Jens pointed out we will invest more work in this respect, but the proposed solution should work immediately for you without any change in YAM.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2014-02-12 17:36:20 +0100**

___
Yes tested this with MUIbase and it works! So for now this is fine.
Thanks for having helped.

**Comment by jens-maus** [comment]
**Originally on 2014-02-12 18:12:14 +0100**

___
Ok, perfect. Please also note that I recently reworked the whole ARexx online documentation for better readability and being more compatible to what YAM 2.9 actually implements. Have a look at the update docs here https://yam.ch/wiki/Documentation/ARexxAPI

**Comment by tboeckel** [comment]
**Originally on 2014-04-22 14:49:28 +0200**

___
Closing this one as there is nothing to be done.
