### ISSUE TITLE
MUIRedraw error message

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#523]
**Originally by _JDuch@fulladsl.be_ on 2014-02-04 15:40:25 +0100**

___
## Summary
Not sytematic but very often, when starting message download
I get an error message. I never was able to copy it, , now i was holding a regular download message "clicked on" 
This was the message 
"Mui Redraw (0x546B6BE4 0x0000002) was called from task 0x546B3CB0 'YAM thread [2]instead of the application's main task. This is a violation of basic MUI rules.

## Steps to reproduce
 1. hit the "recevoir" button of the main window
 2.

## Notes

**Comment by tboeckel** [comment]
**Originally on 2014-02-04 15:51:19 +0100**

___
This has been fixed already. Please refer to #484.

**Comment by jens-maus** [comment]
**Originally on 2014-02-04 15:55:13 +0100**

___
And next time please read through the already assigned and closed tickets in the respective roadmap so that you don't report a duplicate:

http://yam.ch/roadmap
