### ISSUE TITLE
Crash setting a different blinkspeed in TextEditor

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#526]
**Originally by _s.hawamdeh@teletu.it_ on 2014-02-08 08:11:05 +0100**

___
To reproduce it just open your MUI4 prefs directly from YAM, then go to MCC_TextEditor preferences and try to set a different blinkspeed from it (by default blinkspeed is inactive)

I was trying to set it at 25ms but it crash instantanely

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2014-02-08 08:11:38 +0100**

___
**Attachment added:** [`Crashlog_YAM_2014-02-08_08-27-59.txt`](https://yam.ch/attachments/526/Crashlog_YAM_2014-02-08_08-27-59.txt) (28.9 KiB)

**Comment by jens-maus** [comment]
**Originally on 2014-03-02 18:02:51 +0100**

___
I am able to reproduce that problem. However, my feeling it that this is actually a bug/problem in TextEditor.mcc directly. Nevertheless, I will schedule this ticket to be investigated for 2.9p1. So perhaps we can fix it in another TE.mcc version before the final 2.9p1 release.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2014-03-11 10:13:36 +0100**

___
Yep, i wasn't sure if the problem was caused by YAM or because the TextEditor.mcc class, so at the end i decided to report it here :-)

**Comment by jens-maus** [comment]
**Originally on 2014-03-24 11:34:04 +0100**

___
have to move this ticket to the 2.10 milestone as it is anyway a foreign component that is at fault here and as it stands we are unable to track it down in time for the 2.9p1 release, I am afraid.

**Comment by tboeckel** [comment]
**Originally on 2014-04-28 14:38:39 +0200**

___
Some first investigations have shown that the suggest window of TextEditor.mcc's spell checking facility is causing the trouble here. However, I still have to find out what exactly is the true cause.

**Comment by tboeckel** [comment]
**Originally on 2014-04-28 20:49:01 +0200**

___
**Attachment added:** [`te_mcc_15_46.lha`](https://yam.ch/attachments/526/te_mcc_15_46.lha) (73.5 KiB)
TextEditor.mcc 15.46 prerelease

**Comment by tboeckel** [comment]
**Originally on 2014-04-28 20:49:24 +0200**

___
**Attachment added:** [`te_mcp_15_46.lha`](https://yam.ch/attachments/526/te_mcp_15_46.lha) (34.0 KiB)
TextEditor.mcp 15.46 prerelease

**Comment by tboeckel** [comment]
**Originally on 2014-04-28 20:51:19 +0200**

___
I think I found the culprit. Please check the attached prereleases of TextEditor.mcc/mcp 15.46. For me they are no longer causing a crash when modifying any setting while TextEditor.mcc object is alive, i.e. by having a write window open.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2014-04-29 08:09:11 +0200**

___
Unfortunely it doesn't seems to work yet, once i set to 25ms it still crash also with the updated 15.46 class, see crashlog

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2014-04-29 08:09:46 +0200**

___
**Attachment added:** [`Crashlog_YAM_2014-04-29_08-11-11.txt`](https://yam.ch/attachments/526/Crashlog_YAM_2014-04-29_08-11-11.txt) (27.9 KiB)

**Comment by tboeckel** [comment]
**Originally on 2014-04-29 14:08:23 +0200**

___
Does the crash happen only when modifying the blink speed or for other settings as well?

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2014-04-29 20:28:36 +0200**

___
Yep it happen only when i modify the blink speed option moving the slider...

(by default this option is disactive, but once i move it to 25ms it crash)

**Comment by tboeckel** [comment]
**Originally on 2014-04-30 20:25:06 +0200**

___
I just tried this again myself, but for me everything is working properly with this version. But then I am using a more recent MUI version which is not yet publically available.

I think we can leave this ticket closed for the moment. Please reopen it if the problem remains after the next MUI release.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2014-05-01 06:08:31 +0200**

___
No need, just solved now ;-)

What a crap, i downloaded both (15.46) classes above, but when i drag them into MUI/Libs/mui only the single .mcp file was copied correctly, now reinstalled both and the issue seems completely fixed, sorry !
