### ISSUE TITLE
Writing/edit message behaviour (lines, wrap, paragraph)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#529]
**Originally by _stellan.pistoor@gmx.de_ on 2014-02-13 16:55:06 +0100**

___
According to a discussion on yam-user@yam.ch (Subject  Re: [yam-user] GMX and SSL + questions). Description follows:

Thore wrote:
>According to the source code TE.mcc 15.38 did exactly the same as the current version >Modifying a draft mail again will parse the mail text and in that case every hard wrapped line >will appear as a single line. But as long as you are typing a new mail one paragraph will be a >single line only and hence there cursor positions will be different.                                      
>                                                                                     
>This is one thing that needs to be changed in YAM. Modifying a draft mail again must >unwrap the wrapped lines of a paragraph again and concatenate them to a single line again. >An even better approach would be to not perform any hard line wrap when writing out the >mail to disk but to keep the lines as long as they are.

**Comment by tboeckel** [comment]
**Originally on 2014-05-01 20:43:19 +0200**

___
Currently we have a setting on the Write config page to define at which position the line wrap should happen and when this is to be done (while typing or before sending the mail). I think if we implement this feature this settings will have to vanish as it makes no sense to define a fixed line wrap position if no hard line wrapping is to be applied at all. Only the soft line wrapping applied by TE.mcc will remain which will just reformat the text for the on-screen display. Other modern mail clients don't do any hard line wrapping as well to be able to reformat and display the paragraphs as flexible as possible.

With the hard line wrap removed this feature should be quite easy to be implemented.

Jens, what do you think?

**Comment by jens-maus** [comment]
**Originally on 2014-05-12 10:07:01 +0200**

___
After having thought about that I think we could actually do a prototype of that functionality and remove the hard line wrapping for the moment. However, I still feel that we should keep the option in the configuration for setting a line width. Then we should (instead of doing a hard-wrap) make sure we only use soft-wrapping at that border because there might be users wanting to keep a visible line width of e.g. 80 chars and don't see the text always being aligned to the current width of the window (which should be the default).

In addition, we have to take care of the following things:

1. AFAIR, the RFC2822 standard defines emails (transfer and actually files in mbox format) lines to be of maximum width of 998. Thus we have to make sure that when writing out the text that we do a hard wrapping at some point. In fact, if I remember correctly that's exactly what the "format=flowed" option (see ticket #74) is all about. Thus we need to implement support for that as well.

2. when doing soft-wrapping only we have to make sure that quoted text will get correctly requoted as soon as a read/write windows is resized. In fact, again this is why modern mail links don't use that ">" character anymore but use vertical colored lines in front of quoted lines. Thus we might need to add support to TE.mcc for that functionality.

**Comment by tboeckel** [comment]
**Originally on 2014-10-15 16:23:36 +0200**

___
In (f9420ab):
* mui/WriteWindow.c, Config.c: excluded the "before sending" wrapping mode from the list of possible settings. Too long lines in the generated mail file will be encoded as quoted-printable not exceeded 998 characters anyway already. Resizing the write window more narrow than the wrap column will do a dynamic wrapping anyway, no matter if soft line wrapping (while typing) is active or not. All in all this makes it possible to continue editing a draft mail and being able to insert new text in the middle of a paragraph without being forced to rewrap the paragraph manually. This finally closes #529.
