### ISSUE TITLE
Crash selecting a mail with the Enter key

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#531]
**Originally by _s.hawamdeh@teletu.it_ on 2014-02-18 04:31:15 +0100**

___
In a clean YAM installation I was tested the import functionality, so i taked a fake mail as example and of course the importation goes ok, however when i try to open it (pressing Enter) YAM crashed 

No problem instead tring to open it with a simple double click of the mouse

Consider that for this test i didn't configure YAM at all, so before trying to open the mail YAM of course will opened or atleast tried to open the prefs window

If you like to reproduce it, in attachment i will include:

- A draft folder with a mail (as example)
- A grab of YAM
- The crashlog

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2014-02-18 04:31:57 +0100**

___
**Attachment added:** [`Crashlog_YAM_2014-02-18_04-57-54.txt`](https://yam.ch/attachments/531/Crashlog_YAM_2014-02-18_04-57-54.txt) (29.0 KiB)

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2014-02-18 04:32:16 +0100**

___
**Attachment added:** [`draft_folder.lha`](https://yam.ch/attachments/531/draft_folder.lha) (0.8 KiB)

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2014-02-18 04:32:31 +0100**

___
**Attachment added:** `grab.png` (85.7 KiB)
![grab.png](https://yam.ch/attachments/531/grab.png)

**Comment by jens-maus** [comment]
**Originally on 2014-03-02 17:58:16 +0100**

___
I can perfectly reproduce the problem here on OS4. In fact, the following alternative step-by-step explanation will help to more easily reproduce the problem on any YAM installation:

1. Make sure you have a mail in your drafts folder
2. Go to the drafts folder select a mail and press 'Enter' to start an EditMail action
3. Make sure YAM will show the requester in Config.c:IsValidConfig() by forcing valid=FALSE like:

```
--- Config.c	(revision 7749)
+++ Config.c	(working copy)
@@ -2854,6 +2854,7 @@
            firstSMTP->hostname[0] != '\0' &&
            firstPOP3->hostname[0] != '\0');
 
+  valid = FALSE;
   if(valid == FALSE)
   {
     DoMethod(G->App, MUIM_YAMApplication_OpenConfigWindow);
```

4. Now with that change as soon as one uses the "Enter" key in the drafts folder to start an edit mail action a requester and the config window appears and as soon as the requester is acknowledged with 'Okay' a crashlog will be generated as posted above. If the mouse is used instead to double click a mail no crash happens and everything seems to work fine.

After some investigation it seems the cultrip might either within NList or even in MUI itself. To prevent the crash from happening one can do the following:

1. Comment out the MUI_Request() call in Config.c:IsValidConfig()
2. replace MUI_Request(G->App, ...) by MUI_Request(NULL, ...) and a normal EasyRequester will be generated instead which results in no crash at all.

So, Thore, can you please try to investigate if the cultrip is somewhere in MUI itself? Or at least try to reproduce it yourself first. At least this bug reports seems to be perfectly valid. Thus, scheduling it for 2.9p1.

**Comment by tboeckel** [comment]
**Originally on 2014-03-02 20:58:51 +0100**

___
How do you end up with a mail in the Drafts folder, but without a valid config to create it beforehand? I don't want to declare this ticket as invalid. YAM should handle this situation definitely gracefully. But the way to prepare the prerequisits sounds very artificial.

**Comment by tboeckel** [comment]
**Originally on 2014-03-02 22:01:36 +0100**

___
This is another ancient bug in MUI 3.9 and MUI 4 which gets triggered by calling the method MUIM_Application_NewInput in a recursive fashion like it happens when MUI_RequestA() is called as a reaction on a key press. The next MUI release will fix this crash.

**Comment by jens-maus** [comment]
**Originally by _s.hawamdeh@teletu.it_ on 2014-03-11 10:09:39 +0100**

___
@Thore & damato

In a casual manner I just moved there the mail and so i discover the issue, however i admit it was a bit artificial as a test
Aniway guys thanks for the test and the fix !
