### ISSUE TITLE
Config GUI - Filter: Condition page ghosted

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#533]
**Originally by _stellan.pistoor@gmx.de_ on 2014-02-23 13:24:16 +0100**

___
Just a small GUI thing. To reproduce you need at least two filters.

If I choose filters the first filter is marked and shown. The condition page is ghosted if it is choosen. To get it unghosted I chose the second filter what is already unghosted and then just select the first filter. Now condition page is normal displayed (unghosted) and changes can be made.

After this when I choose a different config entry (Identities, Read, Spam, ...) and then go back to Filters GUI behaviour is the same as discribed above. I use MUI 3.8

**Comment by jens-maus** [comment]
**Originally by _stellan.pistoor@gmx.de_ on 2014-02-23 13:25:58 +0100**

___
**Attachment added:** [`Filter_log_pic.lha`](https://yam.ch/attachments/533/Filter_log_pic.lha) (7.3 KiB)
Logfile and config filter pic

**Comment by tboeckel** [comment]
**Originally on 2014-02-24 08:55:28 +0100**

___
In (83af0eb):
* mui/FilterRuleList.c: setting the disabled state of the filter rules list will only disable the individual rule objects, but not the complete object. This closes #533.

**Comment by jens-maus** [comment]
**Originally on 2014-04-09 00:50:12 +0200**

___
**Release Note:**
fixed a bug where a setting the disabled state of filter rules always cause to set complete disabled state of the whole filter.
