### ISSUE TITLE
"Apply remote filter" config entry is lost

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#534]
**Originally by _stellan.pistoor@gmx.de_ on 2014-02-24 01:51:47 +0100**

___
If you update Yam from an old verions (2.5) to 2.9 and load the .config file form 2.5 to 2.9 then the "Apply remote filter" setting is lost. Attached is .config form Yam 2.5

**Comment by jens-maus** [comment]
**Originally by _stellan.pistoor@gmx.de_ on 2014-02-24 01:53:06 +0100**

___
**Attachment added:** [`V2.5config.lha`](https://yam.ch/attachments/534/V2.5config.lha) (2.7 KiB)

**Comment by tboeckel** [comment]
**Originally on 2014-02-24 09:16:18 +0100**

___
In (1178a5c):
* MailServers.c: the default settings for POP3 servers now enforce the applicance of remote filters, because this was the implicit behaviour of YAM until version 2.6p1. This closes #534.
