### ISSUE TITLE
Falsche Umlaute in den Icons/Menüs

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#535]
**Originally by _amiga@eschi-web.de_ on 2014-03-08 21:13:48 +0100**

___
Mir ist gerade aufgefallen, dass bei der MOS Version die Umlaute in den Menüs und den Icons nicht mehr korrekt dargestellt werden. Der Umlaut und bis zu 3 weitere Zeichen werden durch ein ? ersetzt. (Ändern # ?dern, LöschenL?en ...)
Da ich in letzter Zeit YAM wenig benutzt habe, kann ich nicht genau sagen, ob es mit der aktuellen Version kam oder bei einem der letzten Nightly Builds schon falsch war.

Die Umlaute in den Mails selber sind übrigens korrekt dargestellt und andere Programme, die MUI verwenden, stellen auch alles korrekt dar!

**Comment by tboeckel** [comment]
**Originally on 2014-03-09 19:49:11 +0100**

___
Jens, ich denke das ist deine Baustelle. AmigaOS3 und AmigaOS4 sind definitiv nicht betroffen. Da AmigaOS3 genauso wie MorphOS von UTF8 nach ISO8859-1 wandeln muß, scheint das mal wieder ein MorphOS-spezifisches Problem zu sein.

**Comment by jens-maus** [comment]
**Originally on 2014-03-11 10:19:31 +0100**

___
Auch hier kann ich das Problem nicht reproduzieren. D.h. bei mir funktionieren die Umlaute in MorphOS ohne Probleme. Meine Vermutung ist das hier ein alter Catalog verwendet wird der noch nicht UTF8 kodiert ist. Daher bitte sicherstellen das das aktuelle catalog file aus dem neuesten nightly build verwendet wird und nicht irgend ein altes catalog file. Dann sollten umlaute auch wieder korrekt dargestellt werden.

**Comment by jens-maus** [comment]
**Originally by _amiga@eschi-web.de_ on 2014-03-11 21:02:46 +0100**

___
Sooo, habe mich dann jetzt intensiv auf die Suche gemacht und folgendes festgestellt:
Im Catalogs Ordner gab es den Unterordner "deutsch" und "german". In "deutsch" war ein altes catalog file und in "german" das aktuelle. Leider braucht es aber den Ordner "deutsch", weil sonst bleibt alles in englisch ... Im aktuellen nightly build gibt es den Ordner "deutsch" jedenfalls nicht mehr, weshalb auch mein catalog file nicht mehr aktualisiert wurde!

Habt Ihr da evtl. irgendwas geändert?

**Comment by jens-maus** [comment]
**Originally on 2014-03-11 21:04:38 +0100**

___
Kann gut sein. Nightly builds sind eben nightly builds und da ist eigener Hirnschmalz gefordert. Wenn es also nun geht ist ja alles gut. Im finalen release Archiv wird das ganze eh anders aussehen.

**Comment by jens-maus** [comment]
**Originally by _amiga@eschi-web.de_ on 2014-03-11 21:06:19 +0100**

___
Das heißt, ich muss jetzt bis auf weiteres immer das catalog file aus "german" nach "deutsch" kopieren???

**Comment by jens-maus** [comment]
**Originally on 2014-03-11 21:34:27 +0100**

___
genau

**Comment by jens-maus** [comment]
**Originally by _amiga@eschi-web.de_ on 2014-03-12 19:54:54 +0100**

___
EIne Frage noch: Wieso gibt es denn den Ordner "german" mit entsprechendem catalog file, wenn YAM ihn doch nicht berücksichtigt?

Muss also nicht entweder YAM den Ordner "german" suchen oder alternativ der Ordner "german" in "deutsch" umbenannt werden, den YAM ja standardmäßig sucht!?

Ich versuche jedenfalls den Sinn dahinter zu verstehen und der ergibt sich mir nicht so ganz...

**Comment by jens-maus** [comment]
**Originally on 2014-03-12 20:16:25 +0100**

___
Wie gesagt, du lädst ein nightly build Archiv herunter in dem eben halt etwas chaos herrscht. Unter OS4 haben die Verzeichnisse eben den englischen Namen und unter OS3 und MorphOS eben noch die alten Namen "deutsch". Einen Sinn gibts da nicht, das Skript das die nightly builds baut berücksichtigt diesen Fakt eben nicht. Ist aber auch egal, denn wer die nightly builds nutzt sollte wissen was zu tun ist. Otto-Normal-Verbraucher nutzen die offiziellen releases, dort stimmt dann auch alles.

**Comment by jens-maus** [comment]
**Originally by _stellan.pistoor@gmx.de_ on 2014-03-19 16:47:31 +0100**

___
Die nightly-builds würde ich sowieso immer in english laufen lassen. Das ist einfacher und besser nachzuvollziehen. Normalerweise wird für Bugreports ja Englisch benutzt. :-) Zumindestens können dann auch nicht deutsch Kenner es verstehen.
