### ISSUE TITLE
Arexx function MAILCHECK does not work correctly

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#536]
**Originally by _opionline@yahoo.de_ on 2014-03-14 00:36:07 +0100**

___
The Arexx function MAILCHECK does not work correctly.
I add 3 lines (ADDRESS 'YAM' and the tast 2 lines) to the example script in the documentation and attach the script here.
If i execute the attached script i get the follow output:
12.Ram_Disk:> rx GetMailExample.rexx
Downloaded emails:  ST.DOWNLOADED
Left on server:     ST.ONSERVER
Duplicates skipped: ST.DUPSKIPPED
Deleted on server:  ST.DELETED
RC:                 5
Result              RESULT
12.Ram_Disk:>  

YAM should display the correct values instead of the names in big letters.
The RC variable is set to 5 if no Mails are loaded and 20 if at least one mail is loaded.
The doc say that RC is set to 5 if the TCP/IP stack is not online, but the TCP/IP stack is online here.
The doc say nothing about the RESULT variable in the V2.0 version.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2014-03-14 00:36:55 +0100**

___
**Attachment added:** [`GetMailExample.rexx`](https://yam.ch/attachments/536/GetMailExample.rexx) (0.4 KiB)

**Comment by tboeckel** [comment]
**Originally on 2014-03-14 13:31:44 +0100**

___
In (30bdf4a):
* rexx/mailcheck.c: added the missing initialization of the result stem variable. This closes #536.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2014-03-17 00:42:52 +0100**

___
Sorry for reopening but MAILCHECK still work not correct.
I run attached script GetMails.rexx and got 14 E-Mails at the first account.
But the requester show me that i got 14 E-Mails on every account. (see PIC-YAM-001.png)
If i run the script a second time with no Mails downloaded i get a requester like in picture PIC-YAM-002.png.
Seems the stem variable get not initialized at the start.

And what about the RC Variable. As you can see in the pictures i get a RC=5 if no mails are loaded. The Doc say that RC=5 mean the stack is not online which is not true. So either the program or the doc should be changed.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2014-03-17 00:43:22 +0100**

___
**Attachment added:** [`GetMails.rexx`](https://yam.ch/attachments/536/GetMails.rexx) (0.7 KiB)

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2014-03-17 00:43:30 +0100**

___
**Attachment added:** `PIC-YAM-001.png` (6.7 KiB)
![PIC-YAM-001.png](https://yam.ch/attachments/536/PIC-YAM-001.png)

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2014-03-17 00:43:39 +0100**

___
**Attachment added:** `PIC-YAM-002.png` (10.1 KiB)
![PIC-YAM-002.png](https://yam.ch/attachments/536/PIC-YAM-002.png)

**Comment by tboeckel** [comment]
**Originally on 2014-03-17 14:04:54 +0100**

___
The download results are definitely reset to zero ahead of getting mails from a specific server. The results are summed up if and only if no account number is given and all available accounts are checked.

For me at least the first and second account out of three were polled successfully. For the third I get the same effect as you with the download results of the last successful one, the second one in my case. Calling the script a second time gives exactly the same failure as for you.

The strange thing is that your script fails even if YAM is terminated and restarted from scratch. Hence I assume a bug in ARexx itself here rather than YAM. But this is nothing we can control.

**Comment by tboeckel** [comment]
**Originally on 2014-03-17 14:05:52 +0100**

___
**Attachment added:** `result_thore.png` (22.8 KiB)
![result_thore.png](https://yam.ch/attachments/536/result_thore.png)
Partly successful result for 2 out of 3 accounts

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2014-03-18 00:13:58 +0100**

___
It seems that the STEM Variables is set (SetRexxVar()) only if RC=0 (see file Rexx.c Line 858 ) but we have rc=5 if no mail is on the server, so the next call of MAILCHECK with the next server seems to use the old values.
I don't check where the wrong rc value is set...

**Comment by jens-maus** [comment]
**Originally by _stellan.pistoor@gmx.de_ on 2014-03-19 16:41:38 +0100**

___
I just want to mention that I also had some issues with MAILCHECK. At least with option MANUAL. I`ve to check first before I can provide facts but some wrong or missing RC/RESULTS or at least differ documentation to it. Maybe it was just a feature I missed.

**Comment by tboeckel** [comment]
**Originally on 2014-03-19 19:51:14 +0100**

___
In (205b966):
* tcp/pop.c: don't treat no downloadable messages on the server as an error. This refs #536.

**Comment by tboeckel** [comment]
**Originally on 2014-03-19 20:01:51 +0100**

___
With the latest change I can run the GetMail.rexx script several times without any problems, no matter if mails were downloaded or not. So please check again with the next nightly build.

**Comment by tboeckel** [comment]
**Originally on 2014-03-21 13:47:46 +0100**

___
Any news?

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2014-03-22 12:05:31 +0100**

___
It is still not correct. If the connection go offline while the script is running you get still wrong values. Try attached script GetMailsWait.rexx and follow the instruction in the requester. You get the values for the first pop server for all follow popservers which is wrong. Here the values should be uninitialized (the variable name itself in big letters) or the values should be 0.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2014-03-22 12:13:27 +0100**

___
**Attachment added:** [`GetMailsWait.rexx`](https://yam.ch/attachments/536/GetMailsWait.rexx) (0.8 KiB)

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2014-03-22 12:13:48 +0100**

___
**Attachment added:** `PIC-YAM-003.png` (4.2 KiB)
![PIC-YAM-003.png](https://yam.ch/attachments/536/PIC-YAM-003.png)

**Comment by tboeckel** [comment]
**Originally on 2014-03-24 13:18:29 +0100**

___
Replying to opiopi:
> It is still not correct. If the connection go offline while the script is running you get still wrong values. Try attached script GetMailsWait.rexx and follow the instruction in the requester. You get the values for the first pop server for all follow popservers which is wrong. Here the values should be uninitialized (the variable name itself in big letters) or the values should be 0.

But the RC value already indicates that something was not ok. Hence I'd say you should use the STEM variable if and only if RC==0. For any other value you must not use the variables.

**Comment by jens-maus** [comment]
**Originally on 2014-03-24 14:11:29 +0100**

___
I agree with Thore here. Good programming style would be to first check the RC value and only if it is 0 read out the other values, otherwise they are in an uninitialized state. In fact, this should be the usual programming style when programming ARexx.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2014-03-24 19:39:15 +0100**

___
The fact that the RC value must be checked first should be mentioned in the documentation and the example script should be changed too.

**Comment by tboeckel** [comment]
**Originally on 2014-03-25 08:23:44 +0100**

___
I just added this paragraph to the general ARexx documentation:

IMPORTANT NOTE: Always check the RC return code after the command execution before examining any further returned variables. Additional variables will only be set for successfully executed commands with RC==0. A failed command execution will leave these variables unchanged in their previous state.

There is no point in repeating this for each and every single command.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2014-03-25 19:43:42 +0100**

___
OK, now it's fine. :-)
I changed the MAILCHECK example script because the syntax was wrong. Now it should run as expected...

**Comment by jens-maus** [comment]
**Originally on 2014-03-25 20:50:54 +0100**

___
Ok, thanks. And of course, feel free to tune all the other Arexx API documentation examples as you like. We are really short on people taking care of the various documentation and I feel you would be the perfect person to actually taking care of the Arexx API documentation ;)

**Comment by jens-maus** [comment]
**Originally on 2014-04-09 00:51:59 +0200**

___
**Release Note:**
fixed a minor bug in the MAILCHECK Arexx command where the STEM variables weren't correctly initialized.
