### ISSUE TITLE
Redirect menu item is disabled when in sent folder

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#537]
**Originally by _pferrucci@sfr.fr_ on 2014-03-16 22:11:59 +0100**

___
## Summary

"Redirect" menu item is disabled when in sent folder

## Steps to reproduce
 1. go to the sent folder
 2. select a message
 3. right click on the menu bar, go to "message" menu

## Expected results

menu item should be enabled in the menu bar as it is enabled in the context menu (when doing a right click on the message)

**Comment by tboeckel** [comment]
**Originally on 2014-03-17 13:23:06 +0100**

___
Why do you want to redirect a mail you just composed yourself? I'd say the context menu is wrong here, not the global menu.

**Comment by tboeckel** [comment]
**Originally on 2014-03-17 13:31:06 +0100**

___
In (6776579):
* mui/MainMailList.c: disable the "Redirect" item of the mail context menu for the Sent folder. This closes #537.
