### ISSUE TITLE
Ignore notification on new mails

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#539]
**Originally by _stellan.pistoor@gmx.de_ on 2014-03-19 17:18:52 +0100**

___
If I get a mail where the sender wants do have a notification the usual window appears where I can select what I want to do. If I click on "ignore" I get attached MuForce hit.

**Comment by jens-maus** [comment]
**Originally by _stellan.pistoor@gmx.de_ on 2014-03-19 17:19:49 +0100**

___
**Attachment added:** [`Yam_ignore_notification_Hits.txt`](https://yam.ch/attachments/539/Yam_ignore_notification_Hits.txt) (2.4 KiB)

**Comment by tboeckel** [comment]
**Originally on 2014-03-19 19:32:24 +0100**

___
First of all, always state the **exact** version of YAM you are using, especially for nightly builds.

No problem here, no matter if I use MUI 3.8, MUI 3.9 or MUI 4.0.

**Comment by jens-maus** [comment]
**Originally by _stellan.pistoor@gmx.de_ on 2014-03-20 12:39:41 +0100**

___
Version used: YAM 2.10-dev (18.03.2014)

The last version where it happen too was from 16.02.2014 if I remember right. Maybe this was also in YAM V2.5. If you can`t reproduce it than you might ignore it because it is just a small problem here I can avoid. I really seldom get mails with notification request.

**Comment by tboeckel** [comment]
**Originally on 2014-03-20 23:00:46 +0100**

___
Ok, please reopen this bug if it happens again and the MuForce log contains more useful data.
