### ISSUE TITLE
Crash on sending the FIRST mail

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#540]
**Originally by @raziel- on 2014-03-21 19:07:01 +0100**

___
## Summary
YAM is crashing (after the latest MUI update, it didn't do it with R2) when the very first mail is sent (First means the first mail after starting YAM).
All following mails are being sent fine without crashes.

## Steps to reproduce
 1. Start YAM
 2. Send a mail

## Expected results

No crash

## Actual results

Crash

## Regression

Yes, pretty sure about that.
I don't know why or what is causing it, but after updating to MUI R3 it started to happen

## Notes

YAM 2.9
MUI 20.6175 (svn r3383) (15.03.2014
AmigaOS4 upd 6 plus all updates (kernel.debug)

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2014-03-21 19:07:30 +0100**

___
**Attachment added:** [`Crashlog_YAM_2014-03-21_16-02-56.txt`](https://yam.ch/attachments/540/Crashlog_YAM_2014-03-21_16-02-56.txt) (35.5 KiB)
First crashlog

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2014-03-21 19:08:00 +0100**

___
**Attachment added:** [`Crashlog_YAM_2014-03-21_18-52-37.txt`](https://yam.ch/attachments/540/Crashlog_YAM_2014-03-21_18-52-37.txt) (37.7 KiB)
Second crashlog, after a reboot and new start of YAM

**Comment by tboeckel** [comment]
**Originally on 2014-03-21 19:16:52 +0100**

___
This is fixed already. It is a bug in MUI. A fixed muimaster.library can be found here: http://muidev.de/ticket/23
