### ISSUE TITLE
MUI window gadget for popup menu don`t work

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#542]
**Originally by _stellan.pistoor@gmx.de_ on 2014-04-02 15:04:54 +0200**

___
If two write message windows are open the MUI window gadget for popup menu doesn't work on all windows (write message windows and yam main window). Doesn't work mean a click on the gadget does nothing, no popup menu appears.
Using YAM 2.10-dev (18.03.2014).

**Comment by tboeckel** [comment]
**Originally on 2014-04-02 15:20:05 +0200**

___
You are talking about the user definable gadgets in the window border, correct? Then we can do nothing about that, because that is beyond the control of YAM or any other application. This seems to be yet another bug in MUI 3.8.

**Comment by tboeckel** [comment]
**Originally on 2014-04-02 16:36:32 +0200**

___
I just tried to reproduce this myself with MUI 3.8 but for me the popup menu appears for all windows.

**Comment by jens-maus** [comment]
**Originally by _stellan.pistoor@gmx.de_ on 2014-04-02 17:28:44 +0200**

___
It is a really not important issue. Normaly I never open an second write window. However, I just tried it again and for some reason it works now. So you can close this ticket. Sorry for but when I made the report I could reproduce it.
