### ISSUE TITLE
UpdateCheck window should inform about finished downloads

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#543]
**Originally by @raziel- on 2014-04-06 09:00:29 +0200**

___
## Phenomenon
The UpdateCheck window stays silent when a user is downloading, hence no indication of a finished download is given.

## Background analysis
At least a window telling the user that a download has finished should be shown.
The better and user friendlier solution would be to use progress bars on every single available download (if possible) that will show up once the user clicks on "Download"

## Implementation recommendation
I know about task #322 and having the UpdateCheck overhauled to a whole new level...i like that :-)
Maybe this progress bar request can be used as a stop-gap on the way to an automated UpdateCheck/Installer?

**Comment by tboeckel** [comment]
**Originally on 2014-04-06 19:50:34 +0200**

___
Downloading an archive already opens the transfer window. That way you get all the necessary information about the download. Why do you need yet another requester when the download is finished? The transfer window should make it very obvious when a download is finished. A normal web browser doesn't open such a requester either.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2014-04-06 23:47:22 +0200**

___
Ah, so we are back to my earlier report of an "in-main-window-progress-bar" from #399.
:-)
See, i have the transfer window still shut down through config and as such it won't show up when downloding updates (i wasn't aware that the transfer window will display the update downloads aswell).

Maybe we can merge this and #399 then, because they both stem from the same source of having the transfer window suppressed?

**Comment by tboeckel** [comment]
**Originally on 2014-04-07 06:12:19 +0200**

___
The transfer window shows **all** kinds of transfers, not just mail transfers. It is no problem to let the file download override the global settings and always show the transfer window.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2014-04-07 07:53:01 +0200**

___
Ok, that would fix the problem i'm having.

But how to do that? There is no option to override the global setting.
Or has it to be implemented yet?

**Comment by tboeckel** [comment]
**Originally on 2014-04-07 07:58:57 +0200**

___
@raziel-

> But how to do that? There is no option to override the global setting.
> Or has it to be implemented yet?

Perhaps my answer was a bit unspecific. Of course this requires some changes to the source code, but this is easy to do.

**Comment by tboeckel** [comment]
**Originally on 2014-04-07 08:02:16 +0200**

___
In (d5e4860):
* mui/YAMApplication.c, misc: downloading an update archive will now always show the transfer window to inform the user about the download's progress no matter what if the transfer window is configured to be invisible for mail transfers. This closes #543.

**Comment by tboeckel** [comment]
**Originally on 2014-04-07 08:03:12 +0200**

___
**Release Note:**
Downloading an update archive will now always show the transfer window to inform the user about the download's progress no matter what if the transfer window is configured to be invisible for mail transfers.

**Comment by tboeckel** [comment]
**Originally on 2014-04-11 20:58:45 +0200**

___
In (d2181ba):
* ChangeLog: added entry for ticket #543.
