### ISSUE TITLE
Allow the internal update mechanism to "Check on startup"

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#544]
**Originally by @raziel- on 2014-04-19 09:14:19 +0200**

___
## Problem
YAM 2.9 has a new update in the queue (2.9p1)

I know that because after i start YAM i received eMails from the mailinglist telling so and reminders from sourceforge that there is an update waiting.

Yet i don't get *any* indication from YAM itself.
It downloaded all the new mails and then just sat there.
(The config setting is set to "Daily" and "3 am")

Only after i used the "Check for updates" Project menu item it presented me with the available update.

If it weren't for the mails i wouldn't know that there was one.
(Granted, i would probably have done a manual download after i read the mails, but i think that isn't the point of an internal update checker, is it?)

## Analysis

I have turned off the upload/download transfer window which already resulted in similar problems, described and (partially) fixed in bug items #543 and #399.
I don't know if they are related to this one, i'm just adding them for conveniance.

I have set YAM to only use sound for downloaded mails and AmigaOS4's Notifications.
Notifications does not have any information printed that there is an update either, so i think YAM hasn't checked (yet?) or the functionality of notifying about updates isn't available (?)

## Enhancement recommendation

I'd like to ask for two additions to the Config/Updates tab and to the main window.

Updates tab:
Would adding a new item to the pull down menu labeled "on startup" together with the functionality to check and inform on startup be possible?
I don't know if that functionality is already built in, then again it doesn't seem to work for me.

Main window:
A little icon indicating there is an update available would be nice, with the functionality to open the updates window once the user clicks on it.
Either one that is ghosted if there is no update and colored up if there is or completely hidden if not and visible if yes.
Together with the possibility to turn all other indicators off (i.e. bringing up the whole update window) and only show/hide that update icon.

**Comment by tboeckel** [comment]
**Originally on 2014-04-20 22:06:07 +0200**

___
Replying to [#544 Raziel]:

> Yet i don't get *any* indication from YAM itself.
> It downloaded all the new mails and then just sat there.
> (The config setting is set to "Daily" and "3 am")

How do you set a specific time? YAM's update mechanism can only be set to "every day", "once per week" and "once per month".

I just tweaked the .updatestate file to point back one week plus 5 minutes and configured YAM to check for updates once per week. Then I ran YAM 2.9. After 5 minutes I got the update notification window. So this mechanism is working perfectly.


> I have turned off the upload/download transfer window which already resulted in similar problems, described and (partially) fixed in bug items #543 and #399.
> I don't know if they are related to this one, i'm just adding them for conveniance.

There is no correlation between these two meachanisms.


> Would adding a new item to the pull down menu labeled "on startup" together with the functionality to check and inform on startup be possible?
> I don't know if that functionality is already built in, then again it doesn't seem to work for me.

YAM already computes the remaining time since the last update check for the configured interval. If that period is expired already it will check for updates immediately.

To make it short: for me everything is working perfectly and I cannot reproduce this issue.

If you think that the update check mechanism is broken then please provide an UPDATE debug log created with the debug version of YAM 2.9 (not p1!). You can check yourself when YAM checked for updates the last time on the Updates config page and then you will know when the next check should happen. Please tell us these dates together with your current date+time.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2014-04-21 08:54:12 +0200**

___
> How do you set a specific time? YAM's update mechanism can only be set to "every day", "once per week" and "once per month".

Sorry, AmiUpdate slipped in there.
I was fooled that the "Check now" button was a "Set time" button.

> YAM already computes the remaining time since the last update check for the configured interval. If that period is expired already it will check for updates immediately.

I think i know now why it didn't inform me about updates then.
It had checked for updates the day before at 22:30 and would have waited until 22:30 the day the update was uploaded (Having set the mechanism to check daily)

I don't think there is something "broken", i just think it would be nice to be able to tell YAM to check at a specific time, like midnight or 3 am (daily/weekly/monthly).
Not that my YAM is running then, but it would at least check once i start it up every day and get the effect i'm looking for

Even better would be of course to be able to tell YAM to check every time it starts up (i turn my amiga on and off a lot of times - it's not running 24/7 here)

This is just a feature/enhancement request, please don't think i'm trying to make up bugs.

I could alter .updatestate manually but it would change back once an update has been found or when i manually click on "Check now", i'm just looking for a way to make it permanent.

Thanks a lot

**Comment by tboeckel** [comment]
**Originally on 2014-04-22 14:23:18 +0200**

___
@raziel-

> I think i know now why it didn't inform me about updates then.
> It had checked for updates the day before at 22:30 and would have waited until 22:30 the day the update was uploaded (Having set the mechanism to check daily)

So basically we are talking about your impatience here, correct? :) You would have been notified the very next day. Not much of an unbearable delay, I'd say.

> Even better would be of course to be able to tell YAM to check every time it starts up (i turn my amiga on and off a lot of times - it's not running 24/7 here)

We don't release new stuff that often that one needs to check for updates several times a day. You won't suffer or die if you get notified about new updates one day after their release.

> I could alter .updatestate manually but it would change back once an update has been found or when i manually click on "Check now", i'm just looking for a way to make it permanent.

This is absolutely discouraged. Don't mess with YAM's private files, even if they look readable to you.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2014-04-23 03:14:46 +0200**

___
Sorry that i jump in here, but what do think about a new Arexx function for checking for updates? With such function any body could be happy if he put the function (or a script which use this function) in any of the entries in the script section of the config. If that is not fullfill his needs he can also use the function from external e.g. called from a cron program.

**Comment by tboeckel** [comment]
**Originally on 2014-04-23 20:35:59 +0200**

___
Why add yet another external scheduler for a task that YAM already performs properly? The point is that certain peple are just too impatient and cannot wait a few more hours until they are notified. We are talking about an additional delay of 12 hours in average until the notification for daily update checks eventually happens. And we are talking about 2 YAM update per **year** at most.

**Comment by jens-maus** [comment]
**Originally on 2014-04-23 20:45:03 +0200**

___
Replying to tboeckel:

> Why add yet another external scheduler for a task that YAM already performs properly? The point is that certain peple are just too impatient and cannot wait a few more hours until they are notified. We are talking about an additional delay of 12 hours in average until the notification for daily update checks eventually happens. And we are talking about 2 YAM update per **year** at most.

I fully agree with Thore here. First of all we are talking about very few updates only and not about release cycles like Firefox here. In addition I would like to raise the point that by adding a shorter time interval for automatically running the update check mechanism will put more load on our update server. So in case people start YAM often and would have set it to "Check at startup" the update server will received lot more update check requests. The same applies for the requested ARexx command request. There it might even be more severe if for some reason a developer would (accidentally) do a while loop running that update check in that particular loop. That would certainly result in a too high load for our YAM update server. In addition, this would be a perfect candidate to trigger a DoS kind of attack.

So, to make the story short: There is no reason to change anything because YAM has enough functionality regarding the update check. In addition, there are more important things to be done than improving the update mechanisms in that way...
