### ISSUE TITLE
Crash in Configuration/Signature

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#545]
**Originally by @raziel- on 2014-04-19 09:53:51 +0200**

___
## Summary
If you copy something (anything) into the "Signature text" field while it's not in use and leave it there while cancelling the changes YAM will crash

## Steps to reproduce
 1. Open Notepad or any other text based program
 2. Enter anything...like dkjgbjdshngjksödhgiösihdsf
 3. Mark what you typed
 4. Right-Amiga + C it (copy to Clipboard)
 5. In YAM go to Config/Signature

My signature tab looks like this:

Signatures:
Default Signature

Signature:
Active - Checked

Description:
Default Signature

Signature Text:
Completely empty
All three buttons beneath the Signature text are greyed out
Append a file as signature instead: Checked
Path to the signature file

 6. Now click once into the "Description" field underneath the "Active" checkmark (a cursor should be visible now behind the text "Default signature")
 7. Press the TAB key (you'll see a border appear underneath around the "Description" field when it gets activated)
 8. Press Right-Amiga + V to paste your Clipboard text here
 9. The last step is to click on "Cancel" and then on "Close Window" and it crashes

## Expected results
No crash and probably no possibility to activate the "Signature text" field using TAB when it's not meant to be in use

## Actual results
The possibility to activate and paste into the "Signature text" filed while it's not in use and crashing YAM :-)

## Regression
I have no idea if this is a regression as i never tried to do the above.

What i know is that it also happens in v2.9...i checked before updating

## Notes
Hmm, notes, notes...ah, ok

Thank you for the very best eMail program on every platform out there :-)

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2014-04-19 09:54:07 +0200**

___
**Attachment added:** [`Crashlog_YAM_2014-04-19_09-24-56.txt`](https://yam.ch/attachments/545/Crashlog_YAM_2014-04-19_09-24-56.txt) (35.6 KiB)

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2014-04-19 09:54:34 +0200**

___
**Attachment added:** [`Crashlog_YAM_2014-04-19_09-19-27.txt`](https://yam.ch/attachments/545/Crashlog_YAM_2014-04-19_09-19-27.txt) (35.9 KiB)
This is a crashlog created with YAM2.9

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2014-04-19 09:58:58 +0200**

___
Step 7 should of course be

 7. Press the TAB key (you'll see a border appear underneath around the "**Signature text**" field when it gets activated)

**Comment by tboeckel** [comment]
**Originally on 2014-04-20 13:56:47 +0200**

___
In (807ae3e):
* mui/SignatureTextEdit.c: getting a modified signature text from the editor object must treat the destination string as a dynamically allocated string. Otherwise a crash will happen when the string is finally freed. This closes #545.

**Comment by tboeckel** [comment]
**Originally on 2014-04-20 13:58:10 +0200**

___
**Release Note:**
fixed a wrong pointer handling for signatures causing a crash.
