### ISSUE TITLE
Packing Attachements should show the progress

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#55]
**Originally by @raziel- on 2010-03-04 18:53:50 +0100**

___
If one attaches **many huge** files to a mail, it took sometime quite a long time to pack&amp;add those archive to the mail. But you never know when it is ready again.

For example, you could put in a progress bar which show the status of the packing or e.g. a counter in percent.

I, for one, use LZX to pack smaller or larger files to a mail. The larger ones do need quite a while.

Could someone implement it (if it`s possible) in one of the next versions? Please!

**Comment by jens-maus** [comment]
**Originally by _Raziel_Nosgoth@web.de_ on 2010-03-04 18:54:59 +0100**

___
Me again, :-) at least with LZX and LHA it`s possible to open a window and show the progress. Could that be implemented (the window showing the progress) in YAM (a native YAM-window, so to say)?

and...is it possible to support &quot;in-game&quot; :-) PKZip packing???

**Comment by tboeckel** [comment]
**Originally on 2013-08-14 22:32:07 +0200**

___
In (151fa32):
 * YAM_CO.c, mui/WriteWindow.c: the output of the external archiver command can now be redirected optionally to a console window while the archiver is running to show the progress. This closes #55.

**Comment by tboeckel** [comment]
**Originally on 2013-08-14 22:32:45 +0200**

___
**Release Note:**
The output of the external archiver command can now be redirected optionally to a console window while the archiver is running to show the progress.
