### ISSUE TITLE
mention the used filter in the logfile

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#550]
**Originally by _opionline@yahoo.de_ on 2014-04-21 16:23:27 +0200**

___
Today i filter my incoming mails and some of them was moved to a wrong folder.
I seach which filter do the wrong movement but the log say nothing about the used filter
Therefore it would be very helpful if YAM could write the used filter into the logfile.
now such logfile line is e.g.:
1 Nachricht(en) aus dem Postfach 'Eingang' nach 'xxx' verschoben
and could be:
1 Nachricht(en) aus dem Postfach 'Eingang' mittels Filter 'xyz' nach 'xxx' verschoben

**Comment by tboeckel** [comment]
**Originally on 2014-04-21 21:19:27 +0200**

___
I will add a log entry for each moved mail. It will reference the filter name, the mail subject, the sender and the source and destination folder names.

**Comment by tboeckel** [comment]
**Originally on 2014-04-21 21:29:47 +0200**

___
In (9943758):
* YAM_FI.c: moving a mail from one folder to another by a filter will now create a log entry in verbose mode including the filter which caused the move operation. This closes #550.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2014-05-09 00:55:03 +0200**

___
Now i get 2 nearly identical Entries in the log file, for my taste a little to much and logical not correct:
first entry with the prefix "Filter 'Filtername' hat " ... verschoben
second with exact the same text without the prefix.

Both say a mail is moved but in real really only one mail is moved.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2014-05-09 01:08:03 +0200**

___
i forget to mention the version:
YAM 2.10-dev (08.05.2014)
Copyright (C) 2000-2014 YAM Open Source Team [OS3/m68k, r7843]

**Comment by tboeckel** [comment]
**Originally on 2014-05-09 20:24:46 +0200**

___
In (1fd662f):
* YAM_MA.c, misc: added an originator name for all mail movements. This name will be put into the verbose log for reference. In case the move was caused by a filter the filter's name will be used. This closes #550 again.
