### ISSUE TITLE
wrong icon info file in archive for 2.9p1 (os4)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#551]
**Originally by _Michael.Merkel@gmx.net_ on 2014-04-22 20:05:11 +0200**

___
## Summary
when you unarchive the new 2.9p1 archive to ramdisk and try to open the resources folder the amiga slows down for 2 seconds and then lists the content. except the "gallery" drawer and its icon. looking at it it is existing - but not recognized as icon it seems.
## Steps to reproduce
 1. unarchive the 2.9p1 archive to ram
 2. try to open the ressources directory on workbench.

i checked the serial output with no luck. nothing is put to the line :-(
using a current os4 beta installation on the x1000.

## Notes
see screenshot.

regards...
michael

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2014-04-22 20:05:48 +0200**

___
**Attachment added:** `GR_036.png` (89.9 KiB)
![GR_036.png](https://yam.ch/attachments/551/GR_036.png)
directory with icons. see the different look of the gallery icon.

**Comment by jens-maus** [comment]
**Originally on 2014-04-22 20:18:58 +0200**

___
I can support that observation on OS4 here. I had more or less the same issue when I was preparing the release archive of 2.9p1 and found that when trying to view the content of the "Resources" folder using the Workbench the system stalled. I, however, suspected OS4 beta to be the problem. However, more investigation is certainly required. That's why I will flag this report as "accepted" and scheduled for 2.10.

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2014-04-22 20:40:32 +0200**

___
i was informed by one person (matthias bachmann) who is no betatester and has the same problem.
maybe he can add a comment here if he reads it.
i sent him the link to this ticket.

thanks and regards...
michael

**Comment by tboeckel** [comment]
**Originally on 2014-04-22 21:04:22 +0200**

___
I think this is exactly the same issue we had with the latest MUI release (refer to http://muidev.de/ticket/22).

I snapshotted some icons for different systems with DOpus Magellan on my WinUAE setup and very obviously this system malforms the icon files in such a way that OS4 cannot handle them anymore afterwards.

The solution is very simple. We just have to replace the broken icon file with a new one.

**Comment by jens-maus** [comment]
**Originally on 2014-04-22 21:08:39 +0200**

___
Replying to tboeckel:
 
> The solution is very simple. We just have to replace the broken icon file with a new one.

I already guessed that. However, it would also probably nice to fix the real root of the problem: no icon file whatsoever should result in the explained behavior here. So the responsible OS4 developer should probably look at these files and check what makes OS4 going wild just because of these files.

**Comment by tboeckel** [comment]
**Originally on 2014-04-30 19:16:05 +0200**

___
In (de1cac4):
* icons/os4: replaced the faulty Gallery drawer icon by a fixed one. This closes #551.
