### ISSUE TITLE
click on a http link does cut off some characters

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#553]
**Originally by _Michael.Merkel@gmx.net_ on 2014-04-25 19:44:41 +0200**

___
## Summary
hi.
i have a mail with an http link. clicking on it in YAM does open the browser (odyssey) but the last 8 chars are missing.
copying an pasting it to the browser is ok - so the link works in general.

the link is:

http://www.googleadservices.com/pagead/aclk?sa=L&ai=CqL6PHwVaU4DiMuemjAbuhYGAAdzjmtYEvKXsw6cBybqw9c4BCAAQAigDUJGTsvMDYJWqs4LAB6AB3Ial_APIAQGpAmyqSG86Nbc-qgQiT9CfXKC97bIkcNF3vBfST3I2vUH7RiRT7Jz6FtgLrQ8sS4AHjPnaA5AHAQ&val=ChBhMzYwYzU0MWU3ZjE4ODM5EKSK6JoFGgikDKlXD6883CAAKAA&sig=AOD64_2JV8tzokmM9_lBBDyPK-dRxp4nng&adurl=http://122.xg4ken.com/media/redir.php%3Fprof%3D654%26camp%3D94360%26affcode%3Dkw126783%26cid%3D44906459124%26networkType%3Dsearch%26kdv%3Dc%26url%5B%5D%3Dhttp%253A%252F%252Fwww.pitstop.de%252FReifen

when opening it with urlopen directly it is working fine:
urlopen "http://www.googleadservices.com/pagead/aclk?sa=L&ai=CqL6PHwVaU4DiMuemjAbuhYGAAdzjmtYEvKXsw6cBybqw9c4BCAAQAigDUJGTsvMDYJWqs4LAB6AB3Ial_APIAQGpAmyqSG86Nbc-qgQiT9CfXKC97bIkcNF3vBfST3I2vUH7RiRT7Jz6FtgLrQ8sS4AHjPnaA5AHAQ&val=ChBhMzYwYzU0MWU3ZjE4ODM5EKSK6JoFGgikDKlXD6883CAAKAA&sig=AOD64_2JV8tzokmM9_lBBDyPK-dRxp4nng&adurl=http://122.xg4ken.com/media/redir.php%3Fprof%3D654%26camp%3D94360%26affcode%3Dkw126783%26cid%3D44906459124%26networkType%3Dsearch%26kdv%3Dc%26url%5B%5D%3Dhttp%253A%252F%252Fwww.pitstop.de%252FReifen"

## Steps to reproduce
 1. create a mail with the link
 2. double click on it

this is with the latest 2..10 nightly (24.04.2014)
on os4 (beta) using openurl.

regards...
michael

**Comment by tboeckel** [comment]
**Originally on 2014-04-25 20:08:32 +0200**

___
The cut off happens due to a fixed size buffer of 512 bytes. I will change this to dynamically allocated one. This should cover URLs of arbitrary length. The raw URL has a length of 516 bytes. When using Launch-Handler 4 additional bytes will be added for the leading "URL:" device spec. This explains the missing 8 characters.

**Comment by tboeckel** [comment]
**Originally on 2014-04-25 20:12:50 +0200**

___
In (5dc93a7):
* YAM_UT.c: use a dynamically allocated buffer when having to add qoutes or  the "URL:" device prefix for an URL to be opened instead of a fixed size buffer. This closes #553.
