### ISSUE TITLE
ClearFolderMails crash

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#554]
**Originally by _pferrucci@sfr.fr_ on 2014-04-28 22:42:45 +0200**

___
## Summary

There was an email edit window opened in the background. I was doing something else on another program. At some point, the Grimreaper opened on the foreground.

Maybe Yam was saving the edited email when the crash occured.

## Steps to reproduce
Unknown

## Notes
Yam automatic update reports nothing to update so I have all later versions (Yam, MUI, codesetslib).

Full crashlog attached.

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-04-28 22:43:01 +0200**

___
**Attachment added:** [`Crashlog_YAM_2014-04-28_22-23-58.txt`](https://yam.ch/attachments/554/Crashlog_YAM_2014-04-28_22-23-58.txt) (29.8 KiB)
crashlog

**Comment by tboeckel** [comment]
**Originally on 2014-04-29 14:04:36 +0200**

___
Which version of YAM are you using? YAM 2.9p1 or 2.10-dev? No pending updates does not tell anything about the used version.

Then try to reproduce this issue using the corresponding debug build and create a FOLDER log with it. All I can tell from the crashlog is that it happened while YAM was flushing the folder index automaically after the usual timeout. If it is not reproducable it is unlikely we will be able to fix this issue.

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-04-29 15:28:26 +0200**

___
Replying to tboeckel:
> Which version of YAM are you using? YAM 2.9p1 or 2.10-dev?

I selected "Version : nightly build" ;-) so 2.10-dev 27.04.2014

I just hoped the offset in the crashlog could ring a bell :-/

**Comment by tboeckel** [comment]
**Originally on 2014-04-30 14:54:03 +0200**

___
Replying to Elwood:
> Replying to tboeckel:
> > Which version of YAM are you using? YAM 2.9p1 or 2.10-dev?
> 
> I selected "Version : nightly build" ;-) so 2.10-dev 27.04.2014

I know, but in general there is nothing like "the one nightly build" but lots of them instead. Hence we need to know the exact date. If you are using an older nightly build it might be possible that the bug has been fixed in the mean time already.

> I just hoped the offset in the crashlog could ring a bell :-/

Unfortunately not. I think Jens should not strip the binaries for the nightly builds. Then we are able to get more detailed information from the crashlog.

But as I said already, if possible please try to reproduce this issue using the debug version and create a FOLDER log. That should contain more suitable information.

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-05-07 15:08:16 +0200**

___
Hi,

Even if I didn't have another crash, I switched to debug version and updated to nightly build 07/05/2014

Leaving Yam opened with an email being edited, I see this debug output:
00: D:       DockyIcon.c:213:remove Docky icon
00: D:       DockyIcon.c:242:Docky icon changed
00:W:         MailList.c:457:FreeMail attempt on mail (58330f18 ) with RefCounter > 0 (1)
00:W: Timer.c:891:timer event received but no timer was processed!!!

Not necessarily a problem but I see 2 things that could indicate some problem:
- it talks about a Docky but I have none in Amidock.
- the last line could indicate something wrong in the use of the timer device.

**Comment by tboeckel** [comment]
**Originally on 2014-05-07 20:56:22 +0200**

___
Replying to Elwood:

> - it talks about a Docky but I have none in Amidock.

The message about the removed docky icon just indicates that no docky icon is configured. Updating the AppIcon will also update the docky icon, no matter if it is used or not.

> - the last line could indicate something wrong in the use of the timer device.

It may happen that YAM receives a signal to handle a timer event but actually handles two events at a time. The signal will still be pending and next next timer handling will do nothing and cause the warning. Nothing harmful.

Better concentrate on finding a reproducable test case for this ticket's issue than jumping to conclusions about completely unrelated stuff.

**Comment by tboeckel** [comment]
**Originally on 2014-08-19 07:55:56 +0200**

___
Any news on this issue?

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-08-23 19:03:15 +0200**

___
No. I didn't have it again.

**Comment by tboeckel** [comment]
**Originally on 2014-08-26 07:42:59 +0200**

___
Please reopen this ticket if it happens again.
