### ISSUE TITLE
Problem with some reply address, when i try reply

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#555]
**Originally by _kaczus@wp.pl_ on 2014-05-04 10:17:21 +0200**

___
## Summary
When I try reply e-mail on some e-mails sometimes receiver addres is not seen ( nothing in "To" gadget).
I don't know what is wrong, because headers emails looks properly.
## Steps to reproduce
I can send an example e-mail, but not to the public view.

## Notes

**Comment by jens-maus** [comment]
**Originally on 2014-05-04 10:18:53 +0200**

___
Ok, as for the example email you can either replace all your private information in the email with some dummy information and attach it to that ticket or you can send it in private mail (the raw email file, zipped please) to thore and me.

**Comment by tboeckel** [comment]
**Originally on 2014-05-04 11:31:40 +0200**

___
Please also check the folder's settings. Perhaps the mail is located in a folder with active mailling list support but without a proper reply address.

**Comment by jens-maus** [comment]
**Originally by _kaczus@wp.pl_ on 2014-05-04 12:48:06 +0200**

___
Replying to damato:
> Ok, as for the example email you can either replace all your private information in the email with some dummy information and attach it to that ticket or you can send it in private mail (the raw email file, zipped please) to thore and me.

Ok, where I can find these e-mails addresses?

**Comment by jens-maus** [comment]
**Originally by _kaczus@wp.pl_ on 2014-05-04 12:48:08 +0200**

___
Replying to tboeckel:
> Please also check the folder's settings. Perhaps the mail is located in a folder with active mailling list support but without a proper reply address.

No, it is not a folder with active mailling list support. Some mails replay action work properly, some not.

**Comment by tboeckel** [comment]
**Originally on 2014-05-04 12:49:27 +0200**

___
Replying to kaczus@…:

> Ok, where I can find these e-mails addresses?

They are contained in each and every changelog file.

**Comment by jens-maus** [comment]
**Originally on 2014-05-04 13:32:28 +0200**

___
Replying to kaczus@…:
> Replying to damato:
> > Ok, as for the example email you can either replace all your private information in the email with some dummy information and attach it to that ticket or you can send it in private mail (the raw email file, zipped please) to thore and me.
> 
> Ok, where I can find these e-mails addresses?

Send to: mail@jens-maus.de and tboeckel@gmx.de

**Comment by tboeckel** [comment]
**Originally on 2014-05-04 20:56:13 +0200**

___
Both mails are correctly replied to here for me.

**Comment by jens-maus** [comment]
**Originally by _kaczus@wp.pl_ on 2014-05-04 21:49:12 +0200**

___
I analized when reply works properly. When in mail header there is **Reply-to:** or **Cc:** (and choose **Sender and all Recipients**) reply works properly. In other situation I have empty **To:** gadget.

**Comment by tboeckel** [comment]
**Originally on 2014-05-05 20:50:22 +0200**

___
Please create a MAIL debug log created with the debug version of YAM when replying to such a faulty mail. Basics about the debug version can be found in the [FAQ](http://yam.ch/wiki/FAQ/Debugging#BasicsaboutYAMsdebuggingfacilities).

BTW: Please log in before commenting. If you have no login yet then it is time to get one.

**Comment by jens-maus** [comment]
**Originally by _kaczus@wp.pl_ on 2014-05-05 21:42:02 +0200**

___
**Attachment added:** [`systemlog_yam.log`](https://yam.ch/attachments/555/systemlog_yam.log) (22.3 KiB)
log with opened Yam and try Reply on one mail

**Comment by jens-maus** [comment]
**Originally by _kaczus@wp.pl_ on 2014-05-05 21:55:36 +0200**

___
Ok I've created debug log. I opened Yam, selected e-mail and clicked Reply button

Log looks like (full log in attachment):
```
00:D:        YAM_RE.c:940:content 'multipart/alternative; boundary="==o2.pl-WebMail-53924a3.3224b136.9f257=="' 
00:D:        YAM_RE.c:984:0 content type 'multipart/alternative' 
00:D:        YAM_RE.c:940:content 'text/plain; charset="UTF-8"' 
00:D:        YAM_RE.c:984:0 content type 'text/plain' 
00:D:        YAM_RE.c:940:content 'text/html; charset="UTF-8"' 
00:D:        YAM_RE.c:984:0 content type 'text/html' 
00:W:         qprintable.c:494:error while trying to convert qpdecoded string to local charset! 
00:W:         qprintable.c:494:error while trying to convert qpdecoded string to local charset!
```

**Comment by tboeckel** [comment]
**Originally on 2014-05-05 21:58:13 +0200**

___
Very obviously you did not read the FAQ entry. You forgot to set ENV:yamdebug accordingly. Please enter `setenv yamdebug mail file:path_to_log_file.txt` in a Shell before running the debug version of YAM to create the log again.

**Comment by tboeckel** [comment]
**Originally on 2014-05-06 08:39:44 +0200**

___
In (c965b0e):
* YAM_WR.c: added some debug output about the added recipients when replying to a mail. This refs #555.

**Comment by tboeckel** [comment]
**Originally on 2014-05-07 22:15:50 +0200**

___
In (06d3a29):
* YAM_WR.c: added some more debug output for ticket #555.

**Comment by tboeckel** [comment]
**Originally on 2014-05-09 22:11:57 +0200**

___
In (89caf16):
* YAM_WR.c: when trying to find a suitable user identity when replying to a mail in a folder with active mailling list support the To: address must now be valid as well. This refs #555.

**Comment by tboeckel** [comment]
**Originally on 2014-05-12 09:08:57 +0200**

___
In (892af99):
* mui/FolderEditWindow.c: restructured the safety checks before saving the folder's configuration. Especially the mailing list options have been reworked to avoid invalid settings which might cause problems later. This refs #555.

**Comment by tboeckel** [comment]
**Originally on 2014-05-12 09:19:04 +0200**

___
After some private conversation it turned out that some folders had an invalid ML pattern (i.e. '#?') or an invalid empty destination address.

Replying to a mail in the Incoming folder will scan **all** folders for their mailing list support and will use these information of the first suitable folder. In this case the empty destination address together with the catch-all pattern caused YAM to leave the To: address of the reply mail empty.

My latest change will make sure that this situation cannot happen again. A yet desirable feature would be an automatic check for all folders when loading their configuration. The user should at least be prompted with a warning to check the folder configuration.
