### ISSUE TITLE
RMB click on "Papierkorb leeren" in folder listing leads to crash

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#556]
**Originally by _hpollmeier@dhps.de_ on 2014-05-07 12:12:51 +0200**

___
## Summary
Right Mouse Click in the folder listing to clean the tray from deleted mails leads to crash . Reboot needed afterwards.
## Steps to reproduce
 1. Delete one or more mail in the deleted folder with RMB menu

 2. Upcomes the grimreaper Both versions, debug an development

## Expected results
mails in the folder to disappear

## Actual results
grimreaper with the choice of restart the system automatically or forget, then you have to restart by hand.
## Notes

**Comment by tboeckel** [comment]
**Originally on 2014-05-07 12:14:21 +0200**

___
First of all, if you are referring to a nightly build then please state the **exact** date of that build. We have far too many nightly builds to be able treat them all equally.

Where is the crashlog?

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-07 12:56:34 +0200**

___
**Attachment added:** [`Crashlog_YAM.debug_2014-05-07_11-26-27.txt`](https://yam.ch/attachments/556/Crashlog_YAM.debug_2014-05-07_11-26-27.txt) (40.1 KiB)
Crash log for the debug version. Debug version of yam of today

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-07 13:02:33 +0200**

___
Replying to tboeckel:
> First of all, if you are referring to a nightly build then please state the **exact** date of that build. We have far too many nightly builds to be able treat them all equally.
> 
> Where is the crashlog?
 I was fiddling around how to add a crashlog file to the ticket. That lasted to long, now I have added it.
 It happens with the debug version of today as well with version yam210dev from yesterday.

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-07 14:25:30 +0200**

___
Detailed descryption of system here is in the crashlog.

**Comment by tboeckel** [comment]
**Originally on 2014-05-07 21:33:08 +0200**

___
My first guess is that you are using the embedded read pane in the main window (correct?) and that closing the context menu causes a redraw of the mail's header list. But at that point the mail including its list of header lines has been disposed already, but the header list object has not yet got new content. That's why YAM is accessing invalid memory (see 0xdeadbeef values in the crashlog) and hence causes the crash. If all this proves to be true, then we will have to find a way to forbid updates of the header list object (and probably other objects as well) until the next to be displayed mail has been prepared for display.

**Comment by tboeckel** [comment]
**Originally on 2014-05-08 06:34:12 +0200**

___
In (7cde60a):
* YAM_MA.c: don't show a progress bar when deleting, copying or moving single mails. First because the progress bar makes no real sense in these situations, and second because updating the progress bar might cause certain updates of the GUI which in turn can access memory which has just been freed, i.e. when deleting a mail. This refs #556.

**Comment by tboeckel** [comment]
**Originally on 2014-05-08 06:39:42 +0200**

___
So far I was not able to reproduce this issue myself, but I'd guess is that my last chance will fix it. Please try again with the next nightly build.

**Comment by tboeckel** [comment]
**Originally on 2014-05-08 06:41:58 +0200**

___
Just one final recommendation when referring to nightly builds. Please don't use relative terms like "today" or "yesterday" but always use full dates. The point is that this bug tracker will display all times at the top of each comment relative to their age. At the beginning they will read like "today", "yesterday" or "3 days ago". But after some time this will change to "1 year" ago when then makes it really hard to tell which nightly build exactly caused the problem.

The names of crash logs typically contain a date, but that is no 100% reliable source, because that will be the date of the crash which does not necessarily match the date of the nightly build.

So please always use exact dates when referring to nightly builds.

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-09 16:22:42 +0200**

___
QUESTIONS:
Should I try the normal or the debug version?
Will I be notified when to try a new version?

problem solved with the Version 09.05.2014 !

**Comment by tboeckel** [comment]
**Originally on 2014-05-09 16:34:59 +0200**

___
The normal version should suffice. If that causes no further problems we can close this ticket. But I must add that my change is just a workaround and no real fix. That definitely needs more thought and work.

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-09 17:12:52 +0200**

___
**Attachment added:** [`Crashlog_YAM.debug_2014-05-07_11-26-27.2.txt`](https://yam.ch/attachments/556/Crashlog_YAM.debug_2014-05-07_11-26-27.2.txt) (40.1 KiB)
Crash for 10 mails with nightly 2014-05-09

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-09 19:03:18 +0200**

___
I wanted to add a new crashlog but did not find a way to to that.

**Comment by tboeckel** [comment]
**Originally on 2014-05-09 19:43:28 +0200**

___
Unfold the "Attachments" section right below the initial bug report. There you will find a button to add further attachment.

**Comment by tboeckel** [comment]
**Originally on 2014-05-10 19:47:14 +0200**

___
In (6667339):
* YAM_MA.c: clear the embedded read pane ahead of deleting single mails to ensure that no structures of the active but possibly already deleted mail are accessed during a possible redraw action. This refs #556.

**Comment by tboeckel** [comment]
**Originally on 2014-05-12 21:47:56 +0200**

___
Please check again with the current nightly build. Unfortunately I am not able to reproduce this issue myself so far.

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-13 10:58:49 +0200**

___
Replying to tboeckel:
> Please check again with the current nightly build. Unfortunately I am not able to reproduce this issue myself so far.

I checked the Nightly build of 12.05.2014 and deleted 16 mails in the descibed manner without a crash!
I think we can close this ticket

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-15 14:33:20 +0200**

___
**Attachment added:** [`Crashlog_YAM.debug_2014-05-07_11-26-27.3.txt`](https://yam.ch/attachments/556/Crashlog_YAM.debug_2014-05-07_11-26-27.3.txt) (40.1 KiB)

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-15 14:34:49 +0200**

___
**Attachment added:** [`sashimi_YAM_2014-05-15.out`](https://yam.ch/attachments/556/sashimi_YAM_2014-05-15.out) (59.1 KiB)
Crashlog and sashimi.out of the same event

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-15 14:41:19 +0200**

___
It happened again! 6 mails to delete and the text of the last mails still sits on the embedded pane, but the list is empty.
Computer not dead completely so I can edit the content of this ticket. I think, we should reopen it.

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-15 14:47:18 +0200**

___
**Attachment added:** [`Crashlog_YAM_2014-05-15_12-16-02.txt`](https://yam.ch/attachments/556/Crashlog_YAM_2014-05-15_12-16-02.txt) (39.2 KiB)
This one is the right one of today. nightly 2014-05-14

**Comment by tboeckel** [comment]
**Originally on 2014-05-15 15:11:11 +0200**

___
Please provide some verbose instructions how to reproduce this issue. So far I have not been able to make YAM crash in any way. If this is really related to GUI refreshes then a screenshot of YAM's main window would be very helpful. Please also indicate where you press the RMB to open the context menu. And does this crash also happen if you delete mails by pressing the Delete key or by using the toolbar?

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-15 17:09:53 +0200**

___
**Attachment added:** [`Crashlog_YAM_2014-05-15_16-59-55.txt`](https://yam.ch/attachments/556/Crashlog_YAM_2014-05-15_16-59-55.txt) (41.3 KiB)

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-15 17:10:19 +0200**

___
**Attachment added:** `Fehlermeldung10.png` (171.0 KiB)
![Fehlermeldung10.png](https://yam.ch/attachments/556/Fehlermeldung10.png)

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-15 17:10:49 +0200**

___
**Attachment added:** [`sashimi_YA_2014-05-15_16-59.out`](https://yam.ch/attachments/556/sashimi_YA_2014-05-15_16-59.out) (64.1 KiB)

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-15 17:31:42 +0200**

___
hopefully this will help you! After I received your mail I immedately tried it again with the result, that it did not fail. The pane was empty or blank. I got a little bit desparate.Think I got crazy.
Again 16 mails deleted and than crash! The picture shows the situation after crash.
I tried to catch a picture of RMB menu, but no success. If you position the curser over the text Papierkorb and press LMB, the entry gets highlighted.Then press RMB over the highlighted entry upcomes a menu which offers several entries, one of them beeing Papierkorb löschen. Choose this menue point and release RMB. Result as shown in the picture.
Now I am puzzeled because that seems to happen randomly and perhaps only on me.

**Comment by tboeckel** [comment]
**Originally on 2014-05-15 20:36:47 +0200**

___
Ok, I am sure I added the clearing of the read pane 5 days ago already. At least the Changelog has such an entry. But obviously I forgot this...

Shame on me.

**Comment by tboeckel** [comment]
**Originally on 2014-05-15 20:37:20 +0200**

___
In (908e7f6):
* mui/YAMApplication.c: make sure to clear the embedded read pane when deleting all mails from the trash folder. This refs #556.

**Comment by tboeckel** [comment]
**Originally on 2014-05-15 20:42:42 +0200**

___
Please check again with the next nightly build.

What is that "Assistant" application which causes lots of MemGuard hits according to the log sashimi_YA_2014-05-15_16-59.out​? The hits in the log don't look too lethal, but I would ditch an application which is not able to correctly free some memory.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2014-05-16 19:30:39 +0200**

___
Assistant is my calender program, in use since the eighties and I want that going on, because it has all my data since then. It was running on my A2000, A4000, SAM and now on my x1000.
I got the source from the author, but I am not able to convert that to OS4. Probably I am to old to do that.  learned progamming on a IBM 1104 in 1961 with ASPER, later FORTRAN and worked with it. Never got experience with C.
Now the program is running in emulation mode.

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-05-19 15:18:07 +0200**

___
I have tested the latest version over the weekend with 10, 25 and 50 mails.
No crash!
Believe that this ticket can be closed finally.
Thank you for your good work!
