### ISSUE TITLE
to much mails shown in the logfile

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#558]
**Originally by _opionline@yahoo.de_ on 2014-05-09 01:05:18 +0200**

___
It seems YAM does report to much mails in the logfile.
i.e. yesterday i get an entry like:
08.05.2014 23:13:47 [31] Verbunden mit POP3-Konto 'xxx': 182057826 Nachrichten vorhanden
seems to me a "little" to much
i run YAM with debug argument and it show:
SERVER[0062]: +OK maildrop ready, 371 messages (3442768 octets) (74443857)
CLIENT[0006]: STAT
SERVER[0017]: +OK 371 3442768
CLIENT[0006]: LIST
SERVER[0035]: +OK 371 messages (3442768 octets)

so the logfile should also show 371 mails.

YAM 2.10-dev (08.05.2014)
Copyright (C) 2000-2014 YAM Open Source Team [OS3/m68k, r7843]

**Comment by tboeckel** [comment]
**Originally on 2014-05-09 14:03:11 +0200**

___
In (f59ab18):
* tcp/pop3.c: removed a superflous parameter when logging the number of mails waiting on a POP3 server. This closes #558.
