### ISSUE TITLE
automatic mail check not working in nightly?!

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#561]
**Originally by _Michael.Merkel@gmx.net_ on 2014-05-09 21:47:15 +0200**

___
## Summary
I use the current (latest) nightly 20.6185 (r3383).
i have YAM iconified and know that there is one mail on the server. server settings are set to check each minute. but yam does not check... i waited and watched the icon on screen - does not work.
## Steps to reproduce
 1. start yam
 2. configure auto mail check on a server
 3. wait...

don't know since when this is no longer working here...
i use os4.1 beta on a X1000 - maybe the bug lies there?

regards...
michael

**Comment by tboeckel** [comment]
**Originally on 2014-05-11 13:57:21 +0200**

___
In (38ef26c):
* Timer.c, YAM_MA.c: added some debug output to the automatic POP3 download. This refs #561.

**Comment by tboeckel** [comment]
**Originally on 2014-05-11 13:58:20 +0200**

___
Replying to [#561 MichaelMerkel]:

> I use the current (latest) nightly 20.6185 (r3383).

Please don't use terms like "latest" but use exact dates instead, because "latest" will be impossible to determine in a few weeks with some further nightly builds inbetween. And the version number is the one of MUI, not the one of YAM...

> i have YAM iconified and know that there is one mail on the server. server settings are set to check each minute. but yam does not check... i waited and watched the icon on screen - does not work.

Create a TIMER+NET debug log using the debug version of YAM. That will show which timer expires when and how far the download process gets.

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2014-05-11 18:29:48 +0200**

___
Replying to tboeckel:
> Replying to [#561 MichaelMerkel]:
> 
> > I use the current (latest) nightly 20.6185 (r3383).
> 
> Please don't use terms like "latest" but use exact dates instead, because "latest" will be impossible to determine in a few weeks with some further nightly builds inbetween.

really no need to tell me. as you see i tried to add the version but unfortunately grabbed the mui version string :-/

> And the version number is the one of MUI, not the one of YAM...

sorry for that.

regards...
michael

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2014-05-11 18:31:00 +0200**

___
Replying to tboeckel:
> Replying to [#561 MichaelMerkel]:
...

> Create a TIMER+NET debug log using the debug version of YAM. That will show which timer expires when and how far the download process gets.

here it comes with latest nightly from tonight (build 20140511).

thanks and regards
michael

**Comment by jens-maus** [comment]
**Originally by _Michael.Merkel@gmx.net_ on 2014-05-11 18:31:20 +0200**

___
**Attachment added:** [`YAM_debuglog.txt`](https://yam.ch/attachments/561/YAM_debuglog.txt) (26.5 KiB)

**Comment by tboeckel** [comment]
**Originally on 2014-05-12 20:54:51 +0200**

___
In (16a5968):
* Timer.c: fixed the not processed POP3 timers in case two or more timer events were handled within one loop. This closes #561.
