### ISSUE TITLE
Couldn't initialize TLSv1/SSLv3 session with host

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#568]
**Originally by _antibike@web.de_ on 2014-06-10 10:17:30 +0200**

___
Beim Versuch Emails per SMTP ueber 'smtp.web.de' oder 'mail.gmx.net' zu versenden bekomme ich folgende Fehlermeldung als Doppelpack (hier das Beispiel fuer Web.de):

Couldn't initialize TLSv1/SSLv3 session with host
'smtp.web.de'. (07.06.14 10:46:13)
---
Couldn't connect to host 'smtp.web.de'.
The mail server is currently down or doesn't support
the SMTP protocols. (07.06.14 10:46:13)

Das ganze scheint etwas Tageszeit abhaengig zu sein. Hin und wieder kann ich Emails versenden, auch wenn der Verbingungsaufbau zum SMTP sehr langsam ist. Meistens aber kann ich keine Emails versenden.

**Comment by jens-maus** [comment]
**Originally on 2014-06-10 10:30:26 +0200**

___
Bitte mal die debug version des neuesten YAM nightly verwenden und ein NET debug log erzeugen und dann den Bereich um SSL_connect() und die eigentliche Fehlermeldung bitte hier posten, dann können wir schauen was genau schiefgeht.

P.S: Im übrigen wäre es schön die tickets bitte immer in englisch zu verfassen damit andere hiervon auch profitieren.

**Comment by jens-maus** [comment]
**Originally by _antibike@web.de_ on 2014-06-10 10:53:10 +0200**

___
**Attachment added:** [`debugfile`](https://yam.ch/attachments/568/debugfile) (7.3 KiB)
debugfile

**Comment by jens-maus** [comment]
**Originally by _antibike@web.de_ on 2014-06-10 10:53:10 +0200**

___
Attachment (debugfile) added by ticket reporter.

**Comment by jens-maus** [comment]
**Originally on 2014-06-10 11:12:46 +0200**

___
Thanks for the debug output.  In fact, this seems to be exactly the same problem like #530, however until now only classic AmigaOS3 systems were affected by this. So please state which machine you use and which MorphOS version you actually use for doing these tests. In addition, please state if there is a rather long delay in trying to connect to the server and actually returning the error message or does it immediately return the error? Furthermore, please show the "SocketOptions =" line in your yam config file (section [Advanced]).

**Comment by jens-maus** [comment]
**Originally by _antibike@web.de_ on 2014-06-10 11:21:15 +0200**

___
machine = Pegasos2 G4
os = MorphOS 3.5.1
delay between click on send button up to error message ~12 seconds
config file say "SocketOptions =" ... no option is set

**Comment by jens-maus** [comment]
**Originally on 2014-06-10 11:32:07 +0200**

___
Replying to antibike:
> machine = Pegasos2 G4
> os = MorphOS 3.5.1
> delay between click on send button up to error message ~12 seconds
> config file say "SocketOptions =" ... no option is set

Ok, thanks. And can you correlate the delay of ~12 seconds with the debug output and have a look where exactly it gets stuck until it continues and outputs the error message?

Furthermore please retry your test with the following SocketOptions setting:

```
SocketOptions = SO_RCVTIMEO=30 SO_SNDTIMEO=30 SO_KEEPALIVE=1
```

**Comment by jens-maus** [comment]
**Originally by _antibike@web.de_ on 2014-06-11 10:45:35 +0200**

___
if you look at the allready attached debuglog it gets stuck on line 116 and continues with line 117
at the moment i can send emails, so testing new SocketOptions makes no sense

**Comment by jens-maus** [comment]
**Originally by _antibike@web.de_ on 2014-06-11 10:53:15 +0200**

___
ok i tried with the SocketOptions "SO_RCVTIMEO=30 SO_SNDTIMEO=30 SO_KEEPALIVE=1" but it stock on the same line and failed.

**Comment by jens-maus** [comment]
**Originally on 2014-06-11 20:10:25 +0200**

___
In (1e18ca2):
- added some more debug output to better analyze SSL related
  connection problems. This refs #530 and #568.

**Comment by jens-maus** [comment]
**Originally on 2014-06-11 20:15:30 +0200**

___
Replying to antibike:
> if you look at the allready attached debuglog it gets stuck on line 116 and continues with line 117
> at the moment i can send emails, so testing new SocketOptions makes no sense

Thanks for your tests. It is, however, quite strange that the delay should happen between line 116 and 117. That's why I have added some more debug output. So please retry your tests with the next nightly build and please upload a new debug log again hopefully giving more hints where exactly the hang occurs.

**Comment by jens-maus** [comment]
**Originally by _antibike@web.de_ on 2014-06-12 09:25:02 +0200**

___
**Attachment added:** [`2014-06-12_1_debuglog.txt`](https://yam.ch/attachments/568/2014-06-12_1_debuglog.txt) (4.4 KiB)

**Comment by jens-maus** [comment]
**Originally by _antibike@web.de_ on 2014-06-12 09:37:03 +0200**

___
here is the new debug log and it stuck at line 56 for around 10 seconds and continues at line 57
the bad thing is, there is no additional debug
is the debug flag correctly set?
`setenv yamdebug net,!startup,stdout`

**Comment by jens-maus** [comment]
**Originally on 2014-06-12 11:03:45 +0200**

___
In (79cbe25):
- revised some parts of the SSL certificate verification code to be a bit more robust.
  In addition, more debug output had been added to identify potential problems more
  easily. This refs #530 and #568.

**Comment by jens-maus** [comment]
**Originally on 2014-06-12 11:30:54 +0200**

___
Replying to antibike:
> here is the new debug log and it stuck at line 56 for around 10 seconds and continues at line 57
> the bad thing is, there is no additional debug
> is the debug flag correctly set?
> `setenv yamdebug net,!startup,stdout`

Yes, the debug flags are correct and there were actually some new debug output which I could identify and use. however, we are still not there so I revised some code passages in ssl.c and added even more debug output. In addition I rebuilt the latest nightly build from today (12th June) and put it on the nightly build server. So please download the nightly from today again and run your tests again. This time there should be definitely more debug output potentially identifying the reason why it hangs for 10 seconds.

**Comment by jens-maus** [comment]
**Originally by _antibike@web.de_ on 2014-06-12 13:58:14 +0200**

___
**Attachment added:** [`2014-06-12_2_debuglog.txt`](https://yam.ch/attachments/568/2014-06-12_2_debuglog.txt) (4.5 KiB)

**Comment by jens-maus** [comment]
**Originally by _antibike@web.de_ on 2014-06-12 14:01:48 +0200**

___
so here is the new debuglog with delay times

**Comment by jens-maus** [comment]
**Originally on 2014-06-12 14:27:48 +0200**

___
thanks for the new debug output. now I can see where it hangs for 11 seconds. Can you please, however:

1. upload a debug log where the connection actually worked
2. please retry the test but after having emptied the PROGDIR:Resources/certificates/ca-bundle.crt file so that it is completely empty.

**Comment by tboeckel** [comment]
**Originally on 2014-06-12 15:03:01 +0200**

___
In (1ebf6e4):
* Debug.c: each debug message will now include the current time to be able to spot long delays more easily. This refs #530 and #568.

**Comment by jens-maus** [comment]
**Originally by _antibike@web.de_ on 2014-06-12 22:34:06 +0200**

___
**Attachment added:** [`2014-06-12_3_debug_nocerts.txt`](https://yam.ch/attachments/568/2014-06-12_3_debug_nocerts.txt) (5.4 KiB)

**Comment by jens-maus** [comment]
**Originally by _antibike@web.de_ on 2014-06-12 22:34:13 +0200**

___
**Attachment added:** [`2014-06-12_4_debug_mail_sent.txt`](https://yam.ch/attachments/568/2014-06-12_4_debug_mail_sent.txt) (9.3 KiB)

**Comment by jens-maus** [comment]
**Originally by _antibike@web.de_ on 2014-06-12 22:36:58 +0200**

___
i had some luck an can provide a debuglog with a working connetion
see also the debuglog with empty crt file

**Comment by jens-maus** [comment]
**Originally on 2014-06-13 09:45:33 +0200**

___
Please note the following comment in ticket #530 pointing out that the mail server of GMX and web.de have to be blamed for the problem you are seeing:

https://yam.ch/ticket/530#comment:68

Please also note the comment from Thore and the suggestion to exclude AES-based ciphers to work around the problem and which should give you additional 1-2 seconds less delay until SSL negotiations are finished and thus less probability that you will reach the timeout limit of GMX and web.de

**Comment by jens-maus** [comment]
**Originally on 2014-06-13 10:58:14 +0200**

___
Due to the latest analysis this ticket seems to be exactly the same problem like #530. Thus, flagging it as a duplicate. Please continue any discussion in that ticket instead.
