### ISSUE TITLE
Editing/saving address book sometimes corrupts it

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#569]
**Originally by _nbache2@mail.dk_ on 2014-06-28 20:17:43 +0200**

___
## Summary
Sometimes, but unfortunately not always, when I make a change in the address book and save it, the next time I start YAM, it crashes. When i check the contents of the .addressbook file, it has rearranged the entries and among other things put all the @ENDGROUP lines together at the end of the file.

I have tried starting a fresh address book and making a few groups and persons to see if I could reproduce it for this report, but unfortunately not. Today I even tried restoring my address book from my nightly backup and re-doing the exact change which made it happen, and it didn't happen again.
## Steps to reproduce
 1. Have a largish address book with multiple groups and entries (?)
 2. Make a change to one of the entries
 3. Close YAM and start it again
## Expected results
Normal start.
## Actual results
A crash; sometimes a DSI (in fact many after each other, when one is ignored, the next one comes - eventually I just reboot), sometimes an "Unknown". I noticed LoadABook (or similar) close to the top. And I also see in the loading progress messages in the splash window that the address book is currently being loaded.
## Notes
Sorry for the imperfect report. I thought I would be able to reproduce a "clean" test case and save a crash log from it, but couldn't (see above). I'll attach a crash log later if I get one. But it may not be so relevant - the crash is obviously caused by the already corrupted address book file, so the problem must be in the saving or editing of the address book. Anyway, I thought it was better to make this report than to keep silent about it.

**Comment by tboeckel** [comment]
**Originally on 2014-06-28 20:38:03 +0200**

___
An example of a corrupted address book file would definitely be helpful. That might explain why it it created that way in the first place. And of course a crashlog is definitely required. That should always be provided, no matter what. And it is no good idea to risk successfully capturing a crashlog by trying to continue which might result in a frozen system or a total crash.

Does the corruption really happen just after a single simple change? Or does it require more step including moving entries around, dropping them in some groups and/or moving them out of a group?

**Comment by jens-maus** [comment]
**Originally by _nbache2@mail.dk_ on 2014-06-28 21:03:13 +0200**

___
I can send you my address book privately - both the one backed up Yesterday (which was the same state as just before the change was made) and the corrupted one I copied aside after the change before restoring the backup copy. Obviousy please treat them confidentially.

As I said, I'll save a crashlog if/when it happens again, but do note that the crash is just YAM's (or the system's) reaction to finding an already corrupted file at startup. There is no crash involved when the corruption takes place. The reason I didn't save them Today was that I expected to be able to recreate a simpler example, which it turned out I wasn't.

Yes, the only change I had made (this time) was adding a character to the alias of one of the entries. I opened a group, edited the entry, closed the group again and saved the address book.

When the corruption had happened, I restored my backup file and made the same change with Notepad directly in the file, saved it and could start YAM without problems.

It happened to me also a few weeks ago, but I don't remember exactly what I had done that day. It has never happened before upgrading to 2.9p1.

**Comment by tboeckel** [comment]
**Originally on 2014-06-30 08:48:29 +0200**

___
Unfortunately I was not able to reproduce this issue, neither with 2.9p1 nor with 2.10-dev. I am sure I followed your instructions exactly: open the corresponding entry for editing, add a character to the alias, close the edit window, save the address book, quit YAM. For the the resulting .addressbook file is perfectly ok and is loaded again correctly, too.

All in all this smells like corrupted data structures due to memory trashing, but unless we find a way to make this issue easily reproducible I am affraid it will be next to impossible to fix it.

The address book handling was completely reworked for YAM 2.9 already, 2.9p1 just added some very minor bug fixes which from my point of view are unrelated to this issue. So basically this shouldn't be a bug introduced by YAM 2.9p1. Most probably it was introduced by 2.9 already but went unnoticed until now.

**Comment by tboeckel** [comment]
**Originally on 2014-08-19 07:55:11 +0200**

___
Did this issue happen again within the last 7 weeks?

**Comment by jens-maus** [comment]
**Originally by _nbache2@mail.dk_ on 2014-08-19 23:27:24 +0200**

___
Replying to tboeckel:
> Did this issue happen again within the last 7 weeks?

No, but I have been away on vacation for almost half that time.

**Comment by jens-maus** [comment]
**Originally by _nbache2@mail.dk_ on 2014-11-07 18:25:32 +0100**

___
Following up: It hasn't happened again at all since. I won't blame you if you close this issue or at least put it on the backburner ;-).

**Comment by tboeckel** [comment]
**Originally on 2014-11-07 18:43:22 +0100**

___
No problem. Even if the ticket is closed it will remain available to be reopened if that should be necessary.
