### ISSUE TITLE
Edit signature in external editor DSI

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#571]
**Originally by _javierdlr@euskalnet.net_ on 2014-07-08 09:47:09 +0200**

___
## Summary
When closing the external editor with the signature I'am editing I get a GR/DSI error.

#version SDH1:Comm/YAM/YAM full
YAM 2.10-dev ( 5-07-2014)
Copyright (C) 2000-2014 YAM Open Source Team [OS4/PPC, r8118]

## Steps to reproduce
 1.Go to Settings->Signature and click on 'Edit in external editor' (MSG_CO_EditSig) button
 2.Without changing the signature close the external editor (in my case I use CodePad).
 3. GR/DSI error pops up
## Expected results
External editor closes without any problem.
## Actual results
GR/DSI when quitting external edutir with signature.
## Notes

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2014-07-08 09:47:56 +0200**

___
**Attachment added:** [`Crashlog_YAM_2014-07-08_09-39-32.txt`](https://yam.ch/attachments/571/Crashlog_YAM_2014-07-08_09-39-32.txt) (26.8 KiB)
Crashlog when quitting external editor with signature edited

**Comment by tboeckel** [comment]
**Originally on 2014-07-08 11:36:32 +0200**

___
In (61a12e9):
* Config.c: added a missing assignment for the editor codeset. This closes #571.

**Comment by tboeckel** [comment]
**Originally on 2014-07-08 11:56:01 +0200**

___
**Release Note:**
Fixed a crash when using an external editor to modify a signature.

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2014-07-10 14:54:40 +0200**

___
Now works fine, no GR/DSI error with latest nightly YAM 10-07-2014
