### ISSUE TITLE
I am getting a message about failing to initialize TLSv1/SSLv3 when I try to get mail

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#575]
**Originally by _tlm@mccoyasc.com_ on 2014-08-10 19:05:27 +0200**

___
## Steps to reproduce
 1.Get mail
 2.

## Expected results
connect to server and downloaad mail
## Actual results
Message shown above
## Notes
My POP3 mail server guys tells me that he just updated the certificates on his server.  This was required by the people who generate certificates. That's when my problem started.  I think I need to update the certs in the cert directory of YAM  but don't know how to do that.

**Comment by tboeckel** [comment]
**Originally on 2014-08-10 19:09:45 +0200**

___
This issue is very probably exactly the same as #530. Please refer to this ticket.

The nightly builds of YAM are distributed with more recent certificates than the 2.9 release. Just copy the ca-bundle.crt over your installed version in the resources/certificates directory.

**Comment by jens-maus** [comment]
**Originally on 2014-08-11 09:28:51 +0200**

___
As you are using AmigOS4 I think there is a probability that you are not affected by #530 but have a different problem. To better investigate this problem please download the debug version of YAM 2.9p1 and execute the following command in a command shell:

```
setenv yamdebug net,file:ram:t/debuglog.txt
```

then run YAM and your tests again and please attach debuglog.txt to this ticket (after having stripped any private information) so that we can investigate the real reason.

In addition you can download an updated ca-bundle.crt from https://yam.ch/export/HEAD/trunk/resources/certificates/ca-bundle.crt

and store it into PROGDIR:Resources/Certificates.

**Comment by jens-maus** [comment]
**Originally by _tlm@mccoyasc.com_ on 2014-08-17 14:12:39 +0200**

___
**Attachment added:** [`debuglog.txt`](https://yam.ch/attachments/575/debuglog.txt) (25.2 KiB)

**Comment by jens-maus** [comment]
**Originally on 2014-08-17 19:40:17 +0200**

___
Thanks for the debug log. It clearly points out that this is indeed a different issue than the main one explained in #530. In fact, it is a duplicate of #559 which, however, have been already fixed since a while.

So please wait until YAM 2.10 had been released or (as a workaround) download the latest nightly build and use that instead because the latest nightly builds contain fixes for the problem described there.
