### ISSUE TITLE
Fenster für Passworteingabe nicht sichtbar

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#576]
**Originally by _yvan_amiga@gmx.net_ on 2014-08-14 15:52:15 +0200**

___
## Summary
Ich habe mehrere YAM Accounts und einige davon mit einem Passwort geschützt.

## Steps to reproduce
 1. Wenn ich YAM starte und einen passwortgeschützten Account anklicke erscheint das Fenster mit der Passworteingabe nicht.
2. Ich kann das Passwort aber blind eintippen und mit <Return> bestätigen. Es wird akzeptiert und YAM startet mit dem Account weiter.

## Expected results

Textfeld für Passworteingabe sichtbar
## Actual results

Textfeld für Passworteingabe nicht sichtbar

## Notes
Systeme bei dem Fehler eintrifft

Amiga OS4.1 Update 6
YAM Version 2.9p1

Amiga OS 3.9
YAM Version 2.9p1

System ohne diesen Fehler

Morpos 1.4
YAM Version 2.9p1

**Comment by tboeckel** [comment]
**Originally on 2014-08-14 15:57:20 +0200**

___
Replying to [#576 yvan_amiga@…]:

>  1. Wenn ich YAM starte und einen passwortgeschützten Account anklicke erscheint das Fenster mit der Passworteingabe nicht.

Welches Fenster genau meinst du? Das Startfenster mit dem YAM-Logo? Und passiert das grundsätzlich immer oder nur manchmal? Und vor allem, passiert das erst neuerdings oder schon länger? Ein Screenshot wäre hier ganz hilfreich.

**Comment by jens-maus** [comment]
**Originally by _trac-robot_ on 2014-09-03 07:21:26 +0200**

___
This ticket was closed automatically by the system.  It was previously set to a Pending status and hasn't been updated within 14 days.
