### ISSUE TITLE
Fetching mails only on second step

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#577]
**Originally by _pollmeier-h@t-online.de_ on 2014-08-15 11:32:29 +0200**

___
## Summary
Fetching mails only on second step
## Steps to reproduce
 1. Start YAM210dev  and the download should start as it did before. If you then klick on "Holen" the mails are downloaded.

 2. When YAM is started the transfer window opens  all accounts and tries to download.
But on ervery acoount is shown nothing to download. When you then a second later klick on download every mail on every account is downloaded.

## Notes
System here is AmigaOne X1000

**Comment by tboeckel** [comment]
**Originally on 2014-08-15 11:47:00 +0200**

___
Please start YAM from a shell with the "DEBUG" option. This will print out all network trafic to the shell, including the number of mails waiting on the server. Please attach that output to this ticket, but make sure to strip any private data before.

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-08-15 16:26:09 +0200**

___
**Attachment added:** [`sashimi.out`](https://yam.ch/attachments/577/sashimi.out) (28.1 KiB)
Output when starting YAM debug

**Comment by jens-maus** [comment]
**Originally by _pollmeier-h@t-online.de_ on 2014-08-15 16:34:29 +0200**

___
The interesting lines of sashimi output seem to be Nr. 259 to 270.

**Comment by tboeckel** [comment]
**Originally on 2014-08-16 15:18:55 +0200**

___
This is not exactly the log I asked for. But at least the log clearly shows that there are no mails available for download. So YAM's reaction is correct.

You can create a second log by starting the non-debug build from a shell like "YAM debug". This is different from starting the debug build.

For a third log you must again use the debug build and set ENV:yamdebug to "NET" before starting it.

Jens, we really should rename that DEBUG option to something else to avoid this kind of confusion in the future.

**Comment by tboeckel** [comment]
**Originally on 2014-08-19 10:01:24 +0200**

___
I was just able to reproduce this issue myself. I will see what is the cause.

**Comment by tboeckel** [comment]
**Originally on 2014-08-19 10:22:37 +0200**

___
In (08282d4):
* tcp/pop3.c, tcp/pop3.c, tcp/smtp.c: the answer to POP3/SMTP command received from the server is now included in the NET debug log. This refs #577.

**Comment by tboeckel** [comment]
**Originally on 2014-08-19 10:30:48 +0200**

___
In (b98132d):
* tcp/pop3.h: fixed a wrong flag definition which caused the automatic mail download upon startup to be treated as a connection test which does not download any mails by intention. This closes #577.
