### ISSUE TITLE
The execution of the command 'SYS:Utilities/Multiview "RAM Disk:T/1-YAMm000000b5-p1.1' failed (error code 120: argument line invalid or too long).  (09/25/2014 11:58 PM)

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#585]
**Originally by _tlm@mccoyasc.com_ on 2014-09-26 06:14:43 +0200**

___
## Steps to reproduce
 1. I get this error when Itry to display a message that is text only and doesn't have a HTML version 
 2.

## Expected results
The text displays, including links

## Actual results
I get the error message shown in summary block

## Notes

**Comment by tboeckel** [comment]
**Originally on 2014-09-26 06:23:21 +0200**

___
Does this happen with every text-only mail or just with certain special mails?

**Comment by jens-maus** [comment]
**Originally on 2014-09-26 07:08:50 +0200**

___
Well, fron the above description i can spot that the concluding " (quote) seems to be missing. So please post the corresonding config setting here so that we can check that everything is correct.

**Comment by tboeckel** [comment]
**Originally on 2014-09-26 09:01:04 +0200**

___
I can confirm that setting a command string like

```
SYS:Utilities/Multiview "%s
```

causes this error to happen. Note the missing closing quote after the %s.

This is something that YAM cannot check, becase it cannot know the individual invocation syntax of certain commands. YAM will only close quotes which it added itself.

So please check the command strings of all your MIME types for proper quotes.
