### ISSUE TITLE
YAM 2.10-dev (30-09-2014) shows GR on TCP/IP prefs.

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#586]
**Originally by _javierdlr@euskalnet.net_ on 2014-09-30 11:03:42 +0200**

___
## Summary
Trying to go to TCP/IP settings shows a GR, with laetst YAM 2.10-dev (30-09-2014)

## Steps to reproduce
 1. Open Prefs window
 2.Click on TCP/IP page

## Expected results
See TCP/IP options
## Actual results
GR shows up
## Notes

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2014-09-30 11:04:05 +0200**

___
**Attachment added:** [`Crashlog_YAM_2014-09-30_10-58-27.txt`](https://yam.ch/attachments/586/Crashlog_YAM_2014-09-30_10-58-27.txt) (29.9 KiB)
GR when going to TCP/IP prefs page

**Comment by tboeckel** [comment]
**Originally on 2014-09-30 11:30:09 +0200**

___
In (caf7adf):
* mui/misc: the state variable for the NextObject() call must be initialized with the list's lh_Head variable instead of the result of the GetHead() function, because NextObject() does not check for NULL pointers. This closes #586.

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2014-10-01 11:08:10 +0200**

___
Confirmed, now TCP/IP page opnes without GR. :-)
THX
