### ISSUE TITLE
YAM cannot send attached emails

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#587]
**Originally by _phantom@amigafuture.de_ on 2014-10-20 13:53:54 +0200**

___
## Summary

YAM does not send any emails with any type of an attached file. While it sends normal emails to everyone (with no files attached).

## Steps to reproduce
 1. Compose a new email message
 2. Select to attach any file
 3. Select to send it now.

Then it tries to connect with the SMTP server but it hangs up and comes with the following message:
"The connection with the server 'smtp.mail.yahoo.com' interrupted while trying to execute the command ' '."

Which the command's field is always empty.

**Comment by tboeckel** [comment]
**Originally on 2014-10-20 14:08:18 +0200**

___
Since when does this effect happen? If you did not change anything in YAM's configuration then this most probably happens due to a change on the server side.

Does the size of the attachment have any influence? How big are the attached files?

You can try to start YAM from a shell like this:

```
YAM debug >t:yamlog.txt
```

This will dump the full network traffic to the file "t:yamlog.txt". Please attach that file here, but please make sure to strip any private data like passwords from it **before** attaching it here. Perhaps that will reveal the cause for this issue.

**Comment by jens-maus** [comment]
**Originally by _phantom@amigafuture.de_ on 2014-10-20 15:07:05 +0200**

___
This effect did happen 3-4 days ago. Before everything was running normal. I didn't change anything in my configuration for a long long time.

The size of the attachments is really small, only some kilobytes (tried a catalog file and a simple ASCII text file to send).

Attached is the yamlog.txt file you requested, although for a strange reason that file was always 0 bytes, so I forced to save it from KingCon's menu option through shell.

**Comment by tboeckel** [comment]
**Originally on 2014-10-20 15:31:11 +0200**

___
Unfortunately that log does not reveal what is going wrong. There is just one suspicious line near the end with a server response of -1 bytes.

We need to dig a big deeper using the debug version of YAM. Please download that one and type this in a shell before starting it:

```
setenv yamdebug net file:path:to/a/logfile
```

That will create a log file in the path "path:to/a/logfile" which you can choose yourself.

**Comment by jens-maus** [comment]
**Originally by _phantom@amigafuture.de_ on 2014-10-20 15:49:06 +0200**

___
**Attachment added:** [`yamlog.txt`](https://yam.ch/attachments/587/yamlog.txt) (52.2 KiB)

**Comment by jens-maus** [comment]
**Originally by _phantom@amigafuture.de_ on 2014-10-20 15:49:33 +0200**

___
Attached is the logfile from the debug version 2.9p1.

**Comment by tboeckel** [comment]
**Originally on 2014-10-20 16:31:08 +0200**

___
**Attachment added:** [`yam_nosize.lha`](https://yam.ch/attachments/587/yam_nosize.lha) (3921.4 KiB)
no SMTP SIZE argument

**Comment by tboeckel** [comment]
**Originally on 2014-10-20 16:34:34 +0200**

___
There seems to be a difference between the raw mail size and what really is sent over the line. Perhaps Yahoo enforced some additional checks in case the mail's size is known. Please try the attached special version. It omits that SIZE argument. Perhaps that makes a difference already.

**Comment by jens-maus** [comment]
**Originally on 2014-10-20 16:38:31 +0200**

___
If not, please also make sure to test if sending emails still works with other clients (e.g. SimpleMail).

**Comment by jens-maus** [comment]
**Originally by _phantom@amigafuture.de_ on 2014-10-20 18:17:04 +0200**

___
Unfortunately nothing happens, I got exactly the same problem. Yesterday I tried SimpleMail as well, but with the same problems, so probably it's not YAM's fault (which I thought from the beginning) but might there's something changed in Yahoo and how it handles attached files?

**Comment by jens-maus** [comment]
**Originally on 2014-10-20 19:04:17 +0200**

___
nope. there is a clear standard on how to do that. So if sending mails with attachments fails for you with YAM and SimpleMail it is absolutely clear that Yahoo is to blame here. So please open a support request there instead and only reopen this ticket if the yahoo guys answered.

**Comment by jens-maus** [comment]
**Originally by _phantom@amigafuture.de_ on 2014-10-20 19:17:24 +0200**

___
Yes, the problem is that I tried to send attachments via yahoo's browser client (yahoo.com or yahoo.gr) and it worked!

**Comment by jens-maus** [comment]
**Originally on 2014-10-20 20:57:55 +0200**

___
Replying to Phantom:

> Yes, the problem is that I tried to send attachments via yahoo's browser client (yahoo.com or yahoo.gr) and it worked!

Of course, sending mails via a web browser is fundamentally different than sending it via an external mail client. You could in principle also test to send it via a non-Amiga mail client (e.g. Thunderbird) and see if it works there or not.

**Comment by jens-maus** [comment]
**Originally by _phantom@amigafuture.de_ on 2014-10-20 22:48:22 +0200**

___
I tried with Thunderbird on my MacBookPro and it is working without any problems. So is it AmigaOS specific?
