### ISSUE TITLE
Crash when clicking on Start while the email list is being retrieved

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#590]
**Originally by _pferrucci@sfr.fr_ on 2014-11-07 22:42:14 +0100**

___
## Steps to reproduce
 1. I click get, the "retrieving window" opens
 2. while the list is being populated in the window, I immediately click on Start or Abort
 2. crash occurs

## Actual results

Crashlog attached done with debug version

## Notes

Yam debug 16/10/2014

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-11-07 22:42:29 +0100**

___
**Attachment added:** [`yam.txt`](https://yam.ch/attachments/590/yam.txt) (12.7 KiB)

**Comment by tboeckel** [comment]
**Originally on 2014-11-09 20:19:33 +0100**

___
I this reproducable in any way and does this happen every time for you? I never experienced such a crash yet. Usually I use the preselection window for large mails (>1MB) only and hence I see it quite seldom only, but it never caused any crashes and fetching all the details from the server takes a long time for me as there are waiting approx 25000 mails there. So usually YAM nevers finishes the details when I click on "Start".

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-11-09 20:35:10 +0100**

___
Well I reproduced 3 or 4 times before filling the bug report. Now I can't anymore :-(

It could be caused by some text in the subject of my emails that I now deleted. Will be hard to reproduce :-(

**Comment by tboeckel** [comment]
**Originally on 2014-11-09 21:15:32 +0100**

___
Well, if a specific subject should really be the cause, then it should happen anytime again, because due to the crash you did not download the mail and hence the next time the preselection window is shown the mail should trigger the crash again.

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-11-09 22:15:02 +0100**

___
But in the meantime I deleted non wanted emails, silly me :-( That's why I don't have the crash anymore, I suppose.

**Comment by tboeckel** [comment]
**Originally on 2014-11-09 22:32:18 +0100**

___
Then we have to wait until you get such a bad mail again or hope that the crash never happens again.

I will leave this ticket open until then.

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2014-11-11 11:13:50 +0100**

___
I think you can close it. It's working well.

While I was testing Final Edition, I probably booted the system with a configuration that caused this (probably the fact that I installed biosversion.resource.kmod that shouldn't be used).

**Comment by tboeckel** [comment]
**Originally on 2014-11-11 11:17:08 +0100**

___
As you like. The ticket will nevertheless continue to exist, so it can be reopened later if the issue arises again.

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2015-07-09 16:36:46 +0200**

___
Well it's back now with version from 19 June. Attaching a new debug log.

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2015-07-09 16:37:16 +0200**

___
**Attachment added:** [`yam-2015-06-19.txt`](https://yam.ch/attachments/590/yam-2015-06-19.txt) (10.1 KiB)

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2015-07-09 16:53:35 +0200**

___
This log was with files:
Muimaster 20.6373 (but it crashes also with 20.6421)
Frimagedisplay.mui 20.315  (I'm surprised to see it mentioned in the 68k registers)
Intuition 54.19 (crashes also with 54.18 )

Should I try with different version os intuition?
Can you add more debug output at some "interesting" locations? :-)

**Comment by tboeckel** [comment]
**Originally on 2015-07-10 09:29:36 +0200**

___
I think I found a possible reason for the crash. The scrollbars are added in an asynchronous fashion to avoid certain other issued. However, if there are no mails to be transferred (as indicated by your log) it might happen that the NListview object is destroyed before the asynchonous method to add the scrollbars is actually executed. When the method is finally executed it is executed on a dead object and most probably causes the crash you are seeing.

I added a fix to NListview.mcc which removes any asynchronous pushed method in case the object is destroyed before the method has been handled. Please try this hopefully fixed version.

**Comment by tboeckel** [comment]
**Originally on 2015-07-10 09:30:26 +0200**

___
**Attachment added:** [`NListview_os4.lha`](https://yam.ch/attachments/590/NListview_os4.lha) (101.9 KiB)
NListview.mcc for AmigaOS4 with unpushing asynchronous methods

**Comment by tboeckel** [comment]
**Originally on 2015-07-10 09:30:44 +0200**

___
**Attachment added:** [`NListview_os3.lha`](https://yam.ch/attachments/590/NListview_os3.lha) (67.4 KiB)
NListview.mcc for AmigaOS3 with unpushing asynchronous methods

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2015-07-10 15:56:23 +0200**

___
Thanks.
Unfortunately I did a wrong move and I deleted all my spam emails so I don't have a lot of emails in my mail accounts to check with.

Anyway I tried the OS4 NListview.mcc and I don't have the crash. Let me check these coming days and I'll tell you soon.

Thanks again.

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2015-07-12 16:04:47 +0200**

___
I think it's fixed. I couldn't make it crash.
Thanks a lot.

**Comment by tboeckel** [comment]
**Originally on 2015-07-12 20:10:36 +0200**

___
Ok, but please keep an eye on this issue in case it should happen again.
