### ISSUE TITLE
using the docky to close yam does not work

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#591]
**Originally by _Michael.Merkel@gmx.net_ on 2014-12-27 18:42:01 +0100**

___
## Summary
when using the context menu on the YAM docky in amidock ans selecting "beenden" it does not work. this is with yam minimized to the docky.

## Steps to reproduce
 1. open yam on its own screen.
 2. close/minimize yam
 3. -> only the docky is visible now. no yam screen or other yam icon.
 4. select "beenden" (quit/close?) from the context menu of the yam docky.

## Expected results
yam should be quit. the docky be removed.

## Actual results
yam still runs. docky does not vanish.
and yam can not be opened again using the docky!
but you can make it show up by starting yam again.
then the screen and window opens. and the "do you want to quit yam" requester is visible then (in the background unfortunately - actually a second problem?)

i can quit it then from there.

## Regression
always behaves like that.

## Notes

current nightly (2.10-dev 15.12.2014 r8294)
os4.1 FE beta system.

**Comment by tboeckel** [comment]
**Originally on 2014-12-27 20:34:01 +0100**

___
In (5d7067a):
* DockyIcon.c: selecting "Quit" from the DockyIcon's context menu will quit YAM silently if it is iconified even if there is something which requires confirmation. This closes #591.
