### ISSUE TITLE
Wrong caracters in text

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#592]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2015-01-06 07:48:39 +0100**

___
## Summary

E-mail has wrong caracters in text

## Steps to reproduce
 1. read the mail
 2.

## Expected results

Mail should have accented caracters

## Actual results

Accented caracters are replaced by "?"

## Notes

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2015-01-06 07:53:37 +0100**

___
**Attachment added:** [`Dr_Betz.msg`](https://yam.ch/attachments/592/Dr_Betz.msg) (0.9 KiB)
saved e-mail with these wrong caracters

**Comment by tboeckel** [comment]
**Originally on 2015-01-06 08:24:25 +0100**

___
Take a look at the mail's raw text yourself. It does not contain any charset information and the mail body text does not contain any accented characters at all, but only question marks in certain locations where one would expect accented characters. All YAM can do is to display the mail exactly as it is. There is no conversion error.

Furthermore there are some escape sequences around the header lines which should not be there. Where do these come from?

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2015-01-06 09:06:47 +0100**

___
Well, I don't know what is happening but I receive mails like that every now and then from several customers of us, so I wanted to notify it. But if this is due to a whatever problem on the customer side, then good, I know, I can explain to the customers to look into their configurations.

About the escape sequences, sorry but I have no idea where they come from, I just received the mail like that!
