### ISSUE TITLE
DSI error when trying to save a new signature

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#595]
**Originally by _phantom@amigafuture.de_ on 2015-03-18 15:05:56 +0100**

___
## Summary
I got a DSI error each time I tried to save my changed signature.

## Steps to reproduce
 1. Go to signatures tab
 2. In the signature-field, write/change your new signature
 3. Press 'Save' to save changes

## Notes

**Comment by jens-maus** [comment]
**Originally by _phantom@amigafuture.de_ on 2015-03-18 15:06:14 +0100**

___
**Attachment added:** [`Crashlog_YAM_2015-03-18_15-58-49.txt`](https://yam.ch/attachments/595/Crashlog_YAM_2015-03-18_15-58-49.txt) (35.8 KiB)

**Comment by tboeckel** [comment]
**Originally on 2015-03-18 15:40:14 +0100**

___
This has been fixed already in YAM 2.10-dev. See ticket #545.
