### ISSUE TITLE
Option to clear spam folder on exit automatically

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#596]
**Originally by _phantom@amigafuture.de_ on 2015-03-18 17:29:46 +0100**

___
It would be nice to have an option to clear the spam folder when quiting YAM automatically. It is already available for the trash, but it should be nice for an option for spam folder as well.

**Comment by tboeckel** [comment]
**Originally on 2015-05-12 08:36:37 +0200**

___
On the first sight this might sound like a sensible idea. But on the second sight I must say it is a quite bad idea.

The reson is quite simple. No spam filter can reliably detect spam 100%. There will always be false positives (non-spam mails which nevertheless are considered to be spam). If such mails end up in the spam folder and you quit YAM with the desired option active before having noticed this false spam mail you will definitely loose mails without a chance to restore them.

From my point of view it is a far better approach to set the maximum age of the spam folder to 2 or 3 days instead. This will give you the chance to review YAM's spam filtering process, even if you quit and restart YAM. Especially a just activated or reset and hace yet untrained spam filter will move lots of mails into the spam folder. Having an option like "delete all spam on quit" will cause too much harm.

I know, some people prefer a clean system without any unwanted stuff being kept for a longer period of than really absolutely necessary. But loosing non-spam mails without a chance to revert later is far more serious than keeping real spam mails for a few days.
