### ISSUE TITLE
Error validating server certificate for 'pop.gmail.com:995'

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#603]
**Originally by _javierdlr@euskalnet.net_ on 2015-08-18 20:05:48 +0200**

---
## Summary

Since a couple of weeks everytme I GET message I get a window with:
Error validating server certificate for 'pop.gmail.com:995'
clicking on ACCEPT downloads the message without problem.

'ca-bundle.crt' getting "old"?
## Steps to reproduce
1. I just click on GET
2. Window/Requester pops up, clicking on ACCEPT downloads messages ok.
## Expected results

Downloading from pop.gmail.com without warning requester.

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2015-08-18 20:06:48 +0200**

___
**Attachment added:** `sgrab000.png` (33.7 KiB)
![sgrab000.png](https://yam.ch/attachments/603/sgrab000.png)
grab of YAM's warning requester

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2015-08-18 20:07:45 +0200**

___
**Attachment added:** [`certificate.txt`](https://yam.ch/attachments/603/certificate.txt) (3.5 KiB)
YAM's SHOW CERTIFICATE button output

**Comment by tboeckel** [comment]
**Originally on 2015-08-18 21:03:37 +0200**

___
This is exactly the same issue as described in #530. AmiSSL is outdated and fails to validate a perfectly valid certificate. A new AmiSSL version linked against a recent OpenSSL version is in the works, but it will take some more time to finish it.
