### ISSUE TITLE
Error message, can't use YAM anymore

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#604]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2015-08-20 10:13:18 +0200**

___
## Summary

I get an error message, please see attached sg, so I can't use YAM anymore, it seems blocked.

## Steps to reproduce
 1.
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2015-08-20 10:13:52 +0200**

___
**Attachment added:** `Messages d'erreur.png` (11.1 KiB)
![Messages d'erreur.png](https://yam.ch/attachments/604/Messages%20d'erreur.png)

**Comment by tboeckel** [comment]
**Originally on 2015-08-20 22:48:54 +0200**

___
I this issue related to #605? If yes, then this seems to be exactly the same as #603 and #530. According to #605 your provider has updated the SSL certificates recently (August 12th) and the new certificates are now longer accepted by AmiSSL although they are perfectly valid.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2015-08-21 06:30:43 +0200**

___
Well it could be related but I'm not sure it is, because YAM 2.9p1 seems not to function at all anymore since this SSL update, so I had to change to 2.10 beta! 2.10 beta seems to work.

**Comment by tboeckel** [comment]
**Originally on 2015-08-21 20:19:23 +0200**

___
Ok, I always was under the impression that you use the nightly builds all the time. And yes, YAM 2.10-dev is required to be able to ignore the failed certificate checks.
