### ISSUE TITLE
YAM crashes when hitting "clear warning" under TCP/IP

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#605]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2015-08-20 10:16:17 +0200**

___
## Summary

when I hit "clear warnings" under TCP/IP I get a crash. Crash log attached. This is with MorphOS version of YAM.

## Steps to reproduce
 1.
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2015-08-20 10:16:54 +0200**

___
**Attachment added:** [`20150820_yam_crash.log`](https://yam.ch/attachments/605/20150820_yam_crash.log) (33.6 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2015-08-20 10:19:32 +0200**

___
Ah, I did get yesterday the following warning: please see attached sg.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2015-08-20 10:19:46 +0200**

___
**Attachment added:** `SSL Certificate Warning.png` (31.6 KiB)
![SSL Certificate Warning.png](https://yam.ch/attachments/605/SSL%20Certificate%20Warning.png)

**Comment by tboeckel** [comment]
**Originally on 2015-08-20 22:42:25 +0200**

___
In (e4403aa):
* mui/TCPIPConfigPage.c: added a missing parameter for a method invocation when clearing the SSL certificate warnings. This closes #605.
