### ISSUE TITLE
Use the new title class instead of "old" register class

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#607]
**Originally by _javierdlr@euskalnet.net_ on 2015-08-25 00:06:51 +0200**

___
## Problem
Can at least for AOS4 the new title class be sued insetad of "old" register class?

## Analysis
Files affected: TCPIPConfigPage.c, LookFeelConfigPage.c, IdentitiesConfigPage.c, FiltersConfigPage.c and WriteWindow.c (hope they are all)

## Enhancement recommendation
Example for TCPIPConfigPage.c:
..
#if define(__amigaos4__)
    MUIA_ConfigPage_Contents, VGroup,
      Child, TitleObject,
        Child, TextObject, MUIA_Text_Contents,rtitles[0], End,
        Child, TextObject, MUIA_Text_Contents,rtitles[1], End,
      End,
#else
    MUIA_ConfigPage_Contents, RegisterGroup(rtitles),
      MUIA_CycleChain, TRUE,
#endif
..

**Comment by tboeckel** [comment]
**Originally on 2015-08-25 08:27:55 +0200**

___
Same question as for MUI ticket 241: why? What advantage would such a change bring to you?

**Comment by jens-maus** [comment]
**Originally by _javierdlr@euskalnet.net_ on 2015-08-25 22:35:57 +0200**

___
As I have under MUI (prefs) Groups Stretching set to 0% those tabs look "ugly"/unfriendly/.. under AOS4+MUI4.

Instead a '#if define (_amigaos4_)' it would be better check for 'mui_lib' version in use and the stick with "old" register class (MUI3) or use new title class (MUI4).

**Comment by tboeckel** [comment]
**Originally on 2015-09-23 09:07:15 +0200**

___
This issue has been fixed in MUI. See MUI ticket 241 for details: https://muidev.de/ticket/241
