### ISSUE TITLE
YAM crashes when OS detects DST change

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#608]
**Originally by _hypexed@yahoo.com.au_ on 2015-10-07 16:30:56 +0200**

___
## Summary
I am using OS4.1 U6. The OS put up a message when it detected a daylight saving change. I confirmed it. Then saw YAM crashed in the background. I grabbed the reaper log.

## Steps to reproduce
 1. Run YAM in background.
 2. Be in a timezone where a DST change is going to occur. :-)
 3. When OS notices DST change allow it to change clock.
 4. By now YAM should have crashed. 

## Expected results
Nothing.

## Actual results
Simple crash. Recoverable.

## Notes
I checked the tickets for similar cases. Found none alike. I think this may be a hidden bug I have seen before but as it only happens once a year easy to forget I had saved it. :-)

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2015-10-07 16:34:21 +0200**

___
**Attachment added:** [`Crashlog_YAM_2015-10-04_02-00-16.txt`](https://yam.ch/attachments/608/Crashlog_YAM_2015-10-04_02-00-16.txt) (31.2 KiB)
Crashlog of the crash (obviously).

**Comment by tboeckel** [comment]
**Originally on 2015-10-07 19:43:27 +0200**

___
In (432799f):
* TZone.c: added a check for a possibly failed mktime() call and an additional NULL pointer check for the generated time zone name. This closes #608.

**Comment by tboeckel** [comment]
**Originally on 2015-10-07 19:44:25 +0200**

___
Please check again with the next nightly build. The possible causes were the only sensible ones. Unfortunately I am lacking the time to check myself on AmigaOS4.

**Comment by jens-maus** [comment]
**Originally by _hypexed@yahoo.com.au_ on 2015-10-11 15:41:26 +0200**

___
Thanks for the quick fix. I'm not sure how to test it though. I tried setting my time back and the system responded by detecting DST, again. But YAM didn't crash. So without triggering it again it's hard to test the nighly. Regardless, it isn't likely to crash every day, so I'm happy to let it be. If there's no crash this time next year consider it fixed. :-)
