### ISSUE TITLE
CC parser adds wrong address if given address is broken

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#609]
**Originally by @raziel- on 2015-11-01 18:08:20 +0100**

___
## Summary

If i write (by accident, of course ;-) ) a broken address into the CC field and open that eMail after trying to send (it's not being sent, of course) in YAM's editor with "Edit", YAM or the Editor's parser is changing the broken address to soemthing else by cutting a part off and adding something on it's own, which is wrong.
It's probably replacing the broken part from the 1st users eMail address or something like that.

## Steps to reproduce

 1. Click on New eMail
 2. Use any eMail address in the TO field
 3. Use i.e. "A Stupid User <stupid@ stupid.net" as CC address (mind the missing closing >!!!)
(Also don't put the space in there, YAM's bug tracker will cut the address off, which is good :-) ) 
 4. Now try to send the mail...it will get caught by the server...it throws a 501 for me, but YAM will also put the eMail into OUTGOING
 5. Mark and EDIT that eMail...the CC field is filled with "A@ web.de" for me...which is more than wrong :-)
But it shows that the parser is trying to fix the problem by taking the address from my address (i think) which happens to be @web.de.

## Expected results

Not really sure, maybe an error requester on sending that the format of the address is wrong or broken, just like it happens with when i miss the subject?

## Actual results

Described above, plus a shortly puzzled user who asks himself wtf is wrong again with the server ;-)

## Regression

No idea, never happened before though, as long as i can remember

## Notes

1) It's interesting that if i write a valid address in the TO field it's still not being sent.
2) If i doubleclick the broken eMail to simply show it, the broken address is still there (so i guess it's a problem in the Editor?)
3) If i only use two words with a space, i.e. "Stupid User" the whole CC field will be erased when i open it in the Editor, three or more words and it will show up broken.

**Comment by tboeckel** [comment]
**Originally on 2015-11-12 08:31:25 +0100**

___
In (fe7f36b):
* YAM_UT.c: treat address/name combinations like "name <abc@de.fg>" and "abc@de.fg (name)" in the same fashion when separating them into address and realname parts. This refs #609.

**Comment by tboeckel** [comment]
**Originally on 2015-11-12 08:33:08 +0100**

___
In (0804aae):
* mui/WriteWindow.c: don't try to resolve any addresses and don't check the subject when saving a mail as Draft. This refs #609.

**Comment by tboeckel** [comment]
**Originally on 2015-11-12 08:35:44 +0100**

___
In (41ff84c):
* mui/RecipientString.c: when resolving recipients the address is checked to be really valid, i.e. no spaces in the the address part, correctly paired angle brackets, etc. Invalid recipients will be kept now instead of being removed silently and an error message will be popped up instead. Effectively this makes it impossible to send off mails with invalid recipients. This finally closes #609.
