### ISSUE TITLE
Option to disable attachment crop requesters

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#61]
**Originally by _andreasmg@users.sourceforge.net_ on 2010-03-04 19:11:33 +0100**

___
I wish to see an option in the preferences (or in the hidden options in the config file) to disable/enable the attachment crop confirmation requesters. In feature request 434548 someone wanted it, but it's not a good solution for me because I want to crop every bigger attachment from my emails and have to confirm everytime the requester. There are a lot of emails I want to edit in such way...

**Comment by jens-maus** [comment]
**Originally on 2010-03-12 14:37:01 +0100**

___
Sounds reasonable. However, it should only be implemented as a hidden config option and not as a general option available in the configuration GUI.

**Comment by tboeckel** [comment]
**Originally on 2010-09-08 14:01:01 +0200**

___
In (8cf39f3):
 * misc: implemented feature request #61. The confirmation requester can now be
  disabled globally by setting the ConfirmRemoveAttachments option in the
  hidden section of the configuration to "Y" or "1". YAM will then *never* ask
  for confirmation before removing any attachment. You have been warned! This
  closes #61.
