### ISSUE TITLE
Attachment reminder not properly erased/drawn

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#612]
**Originally by @raziel- on 2015-12-20 22:38:41 +0100**

___
## Summary
Once the attachemnt reminder kicks in, activated by a given key word, it adds itself to the bottom of a mail in writing.
If the last line just above the bottom window border happens to have text in it, though, the attachment reminder will cut some of this line and use it as part of it's own frame once it's drawn (see screenshot)

## Steps to reproduce
 1. Open the write window
 2. Enter text that has to be on the bottom (a signature e.g.)
 3. Scroll down (by using blank lines) until the text lines are just above the bottom write window border
 4. Now type any word that triggers the reminder to pop up, i use "I attach..."

## Expected results
Attachment reminder popping up nice and clean

## Actual results
Attachment reminder popping up with cut text which looks wrong

## Regression
Don't think so

## Notes

YAM 2.9p1
AmigaOS4.1FE

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2015-12-20 22:39:22 +0100**

___
**Attachment added:** `[1] Write message_ _000.png` (58.8 KiB)
![[1] Write message_ _000.png](https://yam.ch/attachments/612/[1]%20Write%20message_%20_000.png)
See the line that has been cut? It's the line that's actually a signature in the mail

**Comment by tboeckel** [comment]
**Originally on 2015-12-22 20:54:38 +0100**

___
I haven't been able to reproduce this issue myself so far, but it might be caused by showing the attachment reminder synchronously. The next nightly build will do it asynchronously. Please test it and report back here.

**Comment by tboeckel** [comment]
**Originally on 2015-12-22 20:56:35 +0100**

___
In (ef11bb9):
* mui/WriteWindow.c: show the attachment reminder asynchronously. This might fix some graphical glitches. This refs #612.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2015-12-22 22:35:17 +0100**

___
hmm, shouldn't nighthly builds be built...nightly?
I can see the last build is from 12/13/2015, seems there wasn't any new ones since 10 days?
Or am i looking in the wrong place?

**Comment by tboeckel** [comment]
**Originally on 2015-12-22 22:43:22 +0100**

___
That's why I wrote **next** nightly build instead of **current** nightly build. Nightly builds are built at around 02:00 CET if some new code has been comitted. The next nightly build will appear in a little bit more than 3 hours from now.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2015-12-22 22:48:11 +0100**

___
I got that :-)

But 12/13/2015 means the last *nightly* build was 10 days away, so it's not really a nightly build, more a weekly build ;-)

...ah, missed the part where you said "if some new code has been commited"

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2015-12-23 08:42:37 +0100**

___
Fixed in nightly build

Thanks a lot for the fast feedback and fix

**Comment by jens-maus** [comment]
**Originally on 2015-12-23 11:21:06 +0100**

___
**Release Note:**
fixed bug where the attachment reminder was not properly erased/drawn under some circumstances.
