### ISSUE TITLE
Wrong command execute when clicking on html

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#613]
**Originally by @raziel- on 2016-01-06 14:01:49 +0100**

___
## Summary
I got an email which just holds a certain portion in readable text, the rest is html.

When i open the mail and choose the icon "Display" in the read window i get another windowq with the option to "Display message" No *1 Part 1.1 HTML document.

If i choose to do so i get an error requester telling me that

Error message
The execution of the command 'Appdir:OWB "RAM
Disk:T/1-YAMm00000056-p1.html"' failed (error code 205:
object not found).

and right it is because APPDIR:OWB doesn't exist.

Actually OWB isn't even installed on my system, the APPDIR: entry "OWB" doesn't exist and the URL prefs setting for "OWB" also doesn't exist.

I don't even use the browser exe first at all to start the installed browser, i use a private script to check if the browser is running and use that instead of opening up a new instance and only if no running broswer is found it's run.

Now my question:
Is "OWB" in some way hardcoded in YAM?
How can i rectify that behaviour?

I'd like YAM to check for the URL prefs setting for a browser and not use "OWB".

## Steps to reproduce
 1. Open an email with a html document
 2. Click on the "Display" icon
 3. Click on "Part *1 HTML document"

## Expected results

Yam should check for the URL prefs setting and choose whatever it finds there
My URL prefs setting for HTTP, HTTPS and WWW uses a private script

## Actual results

YAM tries to open the html document with APPDIR:OWB

## Regression

No idea, but i guess so, i haven't had that problems with earlier versions of YAM, which they are i can't really tell

## Notes

**Comment by tboeckel** [comment]
**Originally on 2016-01-06 14:06:08 +0100**

___
Check your OpenURL and URL: settings. Most probably these reference OWB. YAM definitely has no browser hardcoded in any way.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2016-01-06 14:16:29 +0100**

___
As si wrote, i don't have any setting with OWB

OpenURL i haven't even installed.
I checked ENVARC and there is only launch-handlers dir which (as i wrote above) hold the Odyssey settings, nothing more

**Comment by tboeckel** [comment]
**Originally on 2016-01-06 14:22:09 +0100**

___
But there must be something on your system outside YAM which references "Appdir:OWB" in any way. YAM definitely doesn't do this. YAM has no clue about all the individual browsers exiting out there. It simply relies on either OpenURL or URL: to do the right thing, i.e. launch a browser, an FTP client or whatever.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2016-01-06 14:24:37 +0100**

___
OK, checked with the "find" utilitiy and i actually have the APPDIR:OWB on my system.

launch-handler keeps a subdir called "defaults" in it's ENVARC: dir and for some reason YAM picks that up instead of the one that is one level above

It looks like this:

10.ENV:launch-handler> list all
URL                             Dir ----rwed 12-Nov-15 21:08:08

Directory "URL" on Wednesday 06-Jan-16
Defaults                        Dir ----rwed 09-Jan-15 16:51:34
FILE.LH                        1624 ----rwed 12-Nov-15 21:08:08
HTTP.LH                        1622 ----rwed 12-Nov-15 21:08:08
HTTPS.LH                       1790 ----rwed 12-Nov-15 21:08:08
MAILTO.LH                      1505 ----rwed 22-Feb-15 17:36:11
WWW.LH                         1541 ----rwed 12-Nov-15 21:08:08

Directory "URL/Defaults" on Wednesday 06-Jan-16
FILE.LH                        1767 ----rwed 22-Nov-14 23:00:00
HTTP.LH                        1754 ----rwed 22-Nov-14 23:00:00
HTTPS.LH                       1758 ----rwed 22-Nov-14 23:00:00
MAILTO.LH                      1505 ----rwed 22-Nov-14 23:00:00
WWW.LH                         1770 ----rwed 22-Nov-14 23:00:00

Hmm, if YAM is picking the one up that is in defaults then it seems launch-handler is the culprit

...i faintly remember having had a problem before...need to check the Hyperion forums then

Sorry for the noise, not YAM's fault :-)

**Comment by tboeckel** [comment]
**Originally on 2016-01-06 14:27:45 +0100**

___
No problem. Better having 10 invalid bug reports than not being informed about a true bug at all.

**Comment by jens-maus** [comment]
**Originally by @raziel- on 2016-01-06 14:47:36 +0100**

___
Just to close this and to blame me, me and only me :-)

I actually found the setting.
In Config/MIME i had set up text/html with it's viewer Appdir:OWB

Does YAM prioritize this setting or could it be changed to only pick it up if one actually clicks on a html document (and not "Display" it from the button)?

I guess not, thinking about it makes me believe it's the same
