### ISSUE TITLE
Crash when displaying a picture from a draft email

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#615]
**Originally by _pferrucci@sfr.fr_ on 2016-02-03 23:37:31 +0100**

___
## Summary

When I open a draft with a picture attachment, I can't "display" the file.

## Steps to reproduce
 1. Create a draft with an attached picture
 2. in the draft listbrowser double-click the draft to edit it
 3. on the "attachment" area, right click the picture and select display in the context menu

## Expected results

Picture displayed.

## Actual results

Crash.

## Notes

It works if I double-click the image. Only the right click/Display makes Yam crash.
Version 03/02/2016.
I can't test previous version now as I have to go to bed :-)

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2016-02-03 23:37:50 +0100**

___
**Attachment added:** [`Crashlog_YAM.debug_2016-02-03_23-33-33.txt`](https://yam.ch/attachments/615/Crashlog_YAM.debug_2016-02-03_23-33-33.txt) (29.5 KiB)

**Comment by tboeckel** [comment]
**Originally on 2016-02-04 07:34:54 +0100**

___
In (9d78549):
* mui/WriteAttachmentList.c: added a missing parameter when calling the method to display an attachment. This closes #615.

**Comment by jens-maus** [comment]
**Originally by _pferrucci@sfr.fr_ on 2016-02-05 10:27:55 +0100**

___
Confirmed. Thanks.
