### ISSUE TITLE
MorphOS: YAM crashes at startup

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#617]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2016-03-31 08:08:54 +0200**

___
## Summary

crash at startup

## Steps to reproduce
 1. open yam
 2.

## Notes

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2016-03-31 08:09:23 +0200**

___
**Attachment added:** [`log_31-03-16_yam_crash`](https://yam.ch/attachments/617/log_31-03-16_yam_crash) (377.2 KiB)

**Comment by jens-maus** [comment]
**Originally on 2016-03-31 08:53:58 +0200**

___
Thanks for the report. Can you please try the debug version and upload the info it outputs until the crash?

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2016-03-31 11:45:03 +0200**

___
**Attachment added:** [`yam.log`](https://yam.ch/attachments/617/yam.log) (18.0 KiB)

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2016-03-31 11:48:04 +0200**

___
Hi, i uploaded the yam.log file. Hope this helps.

**Comment by jens-maus** [comment]
**Originally by _anonymous_ on 2016-03-31 17:04:51 +0200**

___
Isn't there a possibility that you have the crash log and serial debug output of YAM being printed at the same console so that we can see at which time exactly the crash happens?

**Comment by jens-maus** [comment]
**Originally on 2016-04-01 21:32:37 +0200**

___
Can you please state which version of MorphOS you are using and on which machine you are running MorphOS?

**Comment by tboeckel** [comment]
**Originally on 2016-04-02 09:08:17 +0200**

___
I just tried the latest MorphOS nightly build myself and can confirm that it stops with the "Creating user interface" message in the splash window. But I don't get any crash at all. YAM just freezes.

Is there any official way to output debug stuff in MorphOS' system logger?

**Comment by jens-maus** [comment]
**Originally on 2016-04-02 12:03:33 +0200**

___
Frank Wille also reported the same behavior in a private conversion. He also don't get any crash here but YAM simply freezes when trying to build the user interface.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2016-04-04 05:50:16 +0200**

___
For me, I use MorphOS 3.10 latest beta from 20160331. For now I had to switch back to YAM from 20160317 so that I can at least use it.

**Comment by tboeckel** [comment]
**Originally on 2016-04-04 08:35:22 +0200**

___
Jens, perhaps it would be worth the effort to revert back to the previous MorphOS gcc version. I cannot really believe that this issue is caused by recent code changes, keeping in mind that there have been only minor changes which definitely don't affect the GUI creation process.

**Comment by jens-maus** [comment]
**Originally on 2016-04-04 09:44:23 +0200**

___
Yes, of course. But I would like to first try to understand/debug the root of the problem instead of simply reverting to the old GCC 2.95.3 version. Perhaps also someone from the MorphOS world could try help debugging us this situation so that we can make sure that we understand/find the root cause and potentially fix the issue. In the meantime MOS users could easily continue to use the 20160317 version of YAM nightly.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2016-04-06 07:03:25 +0200**

___
That's what I did anyway, I need to use 20160317 version in the meantime!

**Comment by jens-maus** [comment]
**Originally on 2016-04-06 10:15:59 +0200**

___
with mentioning "someone from the MorphOS" world I actually meant that we would need some help from some MorphOS developers since I tried to analyze your crashlog but couldn't find a reason as to why it crashes when compiled with the latest GCC 5.3.x version while with the old GCC 2.95.3 YAM perfectly works for MorphOS.

So perhaps you can send some MorphOS developers a reference to this issue and potentially someone could help us debugging this situation?!? That would be great.

**Comment by jens-maus** [comment]
**Originally by _christoph.poelzl@rmsvideo.ch_ on 2016-04-07 06:53:30 +0200**

___
Hi, I had the chance to talk to Frank Mariak about this problem and he is willing to help to get this problem corrected so that we have again a working MorphOS version of YAM :-)

I already explained as far as I could the problem, but could you please contact him per mail so that you talk between developers as I don't know nothing about it. Thanks in advance!

If you need his e-mail address, please let me know privatly.

**Comment by jens-maus** [comment]
**Originally on 2016-04-07 09:20:34 +0200**

___
Thanks for having contacted Frank. I just sent him an email and hope he can help us to get things sorted out.

**Comment by jens-maus** [comment]
**Originally on 2016-04-11 10:44:25 +0200**

___
In (92ab2b2):
* misc: replaced several VARARGS68K uses with calls to preprocessor macros which
  will convert a varargs function call into a tagitem list function call. This
  is a preparation of GCC5 support for the MorphOS build and refs #617.

**Comment by jens-maus** [comment]
**Originally on 2016-04-11 21:23:03 +0200**

___
In (9656df7):
* tools/genclasses/gc.c: implemented an ASM stub for MorphOS compiles with
  GCC > 2 because newer GCC versions unfortunately don't support VARARGS68K
  anymore. This should hopefully fix recent problems with our GCC5 compiles
  for MorphOS, thus closes #617.

**Comment by jens-maus** [comment]
**Originally on 2016-04-12 09:35:16 +0200**

___
Now that I have integrated a potential fix for the problem, please test the latest nightly build throughoutly and please report any problem or issue that might be related to the problem reported here.

**Comment by jens-maus** [comment]
**Originally on 2016-04-12 17:07:19 +0200**

___
In (a4eb4d2):
* tools/genclasses/gc.c: reworked YAM_NewObject() once more and replaced
  the ASM stub for the MorphOS build with some C-language equalivant which
  copies all variable arguments into a "struct TagItem" array with a maximum
  size of 128 entries. This routine is now generally used rather than using
  VARARGS68K for the other platforms. In addition, it solves a still existing
  problem where more than 8 arguments resulted in some undefined problems and
  thus the ASM stub couldn't be usd. This refs #617.
