### ISSUE TITLE
Save attachments - jump to file via number key

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#62]
**Originally by _treteimer@users.sourceforge.net_ on 2010-03-04 19:13:08 +0100**

___
Attachments are listed with a number in the first column. Why not use them? Until now, when you want to save attachment no. 3 of 7 you have to scroll around to select it. Idea: hit the "3" and it gets selected. If you want to select file no. 12 just quickly hit "1" and "2" to select it as Workbench does with file selection.

**Comment by jens-maus** [comment]
**Originally on 2013-02-03 15:00:31 +0100**

___
Support for key 1 – 9 could be quite easily added, but allowing to select e.g. attachment >= 10 by using key 1 and 0 quickly will probably put too much effort into thie enhancement request. My suggestion:

key 0: select all attachments (part 1 – 9).
key 1 – 9: select letter part 1 – 9.

That should be quite easily doable, thought having a low priority IMHO.

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 07:42:03 +0200**

___
In (764512b):
 * mui/AttachmentList.c: the single items of the list can now be activated immediately by pressing their number on the keyboard. "0" will be mapped to the 10th attachment. This closes #62.

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 11:43:50 +0200**

___
**Release Note:**
The single items of the list can now be activated immediately by pressing their number on the keyboard. "0" will be mapped to the 10th attachment.
