### ISSUE TITLE
yam binary for 68000 and os 3.x

### ISSUE THREAD

**Issue by yam68k** [jens-maus/yam#626]
hello,

is it possible to create a version for plain 68000 on 3.x machines (a500 a600)?
there are (almost) zero alternatives for a modern email client.

best regards,
yam68k

**Comment by jens-maus** [comment]
Sorry, but if you are really using a plain 68000 machine you are better suited with using an old version of yam since all last version published are targeted for m68020+ machine (even better using a winuae environment). So no, we haven't planned to build 68000 versions - it's 2016, get a faster machine I would say ;)

**Comment by yam68k** [comment]
hello,

that was quick. well, it is not about speed, it is about quality and usability.

i already tried myself, basicaly i changed src/Makefile:
  #CPU	    = -m68020-60 -msoft-float
  CPU		= -m68000

is this enough?

there were some other issues, but it did compile ( crosscompiler toolchain in cygwin )
eg: yam-2.9p1-68k/src/DynamicString.c missing a #include "extrasrc.h"

i think the mayor trouble is yam-2.9p1/src/lib/os3/libm.a, i had to replace with one, which came with the toolchain (there were some unresolved functions).
is this libm.a compiled for 020+ ? do i have to find a version for 68000 ?

best regards,
yam68k

**Comment by jens-maus** [comment]
It is not only yam that you would need to recompile. You would also have to recompile all the mui custom classes (mcc) as well as codesets.library, amissl.library and so on.

**Comment by jens-maus** [comment]
As I said in #627 you can perfectly continue to comment here. Please note, however, that this is no discussion forum to discuss things but an issue tracker. So if you really want to get the recent YAM sources compiled&running for plain 68000 and os3 for a500/600 you are completely on your own. IMHO this doesn't make in any way sense. IMHO you would be better off continue using YAM 2.2. There are so many performance critical things in recent YAM versions and its companion MCC/libraries that a plain A500/600 is simply not powerful enough.
