### ISSUE TITLE
Closing/Restarting YAM with write/answer messages opened

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#63]
**Originally by _anonymous_ on 2010-03-04 19:15:10 +0100**

___
If you close or restart YAM while you have a "write-in-progress" message window opened, you will not be asked about what to do with it, in the same way you are when you close that window on purpose, so you can lose a message you are writing without noticing it, f.ex., its window is behind other windows while surfing the web, looking for info you need for that message, and you need also info that is in another YAM account: you forget the message is behind, you do a YAM restart and you lose the message you are writing.

A check and a warning should be included in both cases, restarting and closing YAM.

**Comment by tboeckel** [comment]
**Originally on 2010-03-05 10:56:22 +0100**

___
In (2e9eaf4):
 * YAM.c: quitting YAM while a write window is still open will open a requester
  which explicitly ask for confirmation and allow the user to put the mails on
  hold. This fixes #63.
