### ISSUE TITLE
YAM 2.10dev: No connection to freenet outbox server

### ISSUE THREAD

**Issue by halle-saale** [jens-maus/yam#631]
Acording to the this freenet website http://kundenservice.freenet.de/artikel/1869, I set in YAm mx.freenet.de as the outbox server, chose port 587 and STARTTLS. Then I tried all modes (AUTO, PLAIN etc.) but I always got the message, that a connection to the SMTP server could not be established.
I also wrote freenet, but they refered me to the website I mentioned above. With any other provider, arcor or t-online, I had no problems. So I guess this is a YAM issue.

**Comment by jens-maus** [comment]
Would you please state which OS and YAM version you are using? In addition a debug lig generated by executing "YAM debug" on the command line would help to identify the reason. In addition please state the exact error message YAM is giving you!

**Comment by halle-saale** [comment]
Did you get my email including the debug file and the information you required?

**Comment by halle-saale** [comment]
I just wanted to add that I am using AmigaOS 3.9 and the latest developer version of YAM.
YAM also cannot delete messages from the Freenet server.
