### ISSUE TITLE
releasenotes/changelog missing?

### ISSUE THREAD

**Issue by MichaelMerkel** [jens-maus/yam#634]
hi.

the currentl nighlies (as of 09.08.2016) don't contain a changelog since yam has been moved to github.
is this an inteded change? i usually like to read it when yam gets updates.

thanks and regards...
michael

**Comment by jens-maus** [comment]
I am sorry, but that is/was an intended change. It was simply way to much of a hassle to maintain the ChangeLog file in long term. So please use the features of github to monitor changes. In addition, the update notification will have an automatic generated ChangeLog added.

**Comment by tboeckel** [comment]
IIRC you told me about a solution to generate the Changelog file automatically from the commit comments some month ago? That one could be included instead. Isn't that a viable solution?

**Comment by jens-maus** [comment]
Sure, just have a look at our nightly build script here:

https://github.com/jens-maus/yam/blob/master/www/nightly.yam.ch/yam-build.sh#L331

There you will see how the automatic generated ChangeLog file is generated now. BTW: There I can see that this ChangeLog should actually be included in each nightly build archive. Isn't it?

**Comment by tboeckel** [comment]
No, there is no ChangeLog file included in the archive, although the build log does try to include it:

`archiving:
+ cp src/YAM.os3 /usr/local/amiga/yam-build/2016-08-15-dev/YAM
+ cp /usr/local/amiga/yam-build/yam/icons/os3/YAM.info /usr/local/amiga/yam-build/2016-08-15-dev/
cp: cannot stat '/usr/local/amiga/yam-build/yam/icons/os3/YAM.info': No such file or directory
+ cd /usr/local/amiga/yam-build/2016-08-15-dev
+ lha ao5 YAM210dev-AmigaOS3.lha YAM YAM.info ChangeLog README.txt catalogs resources
+ md5sum YAM210dev-AmigaOS3.lha
+ rm YAM
+ set +x`

The "resources" directoy and the YAM icon are missing, too. The archives consist of the YAM binary, the catalogs and the README.txt file only.
