### ISSUE TITLE
Swiss spelling

### ISSUE THREAD

**Issue by polluks** [jens-maus/yam#637]
--- german.po.bak	2016-08-11 00:00:40 +0200
+++ german.po	2016-08-11 00:27:40 +0200
@@ -1107,7 +1107,7 @@
 
 msgctxt "MSG_CO_PSLarge (360//)"
 msgid "large messages"
-msgstr "grosse Nachrichten"
+msgstr "groÃe Nachrichten"
 
 msgctxt "MSG_CO_PSAlways (361//)"
 msgid "always"

**Comment by tboeckel** [comment]
Fixed.

BTW, you could have done this yourself using the services of Transifex...

**Comment by polluks** [comment]
I'm not allowed to edit this
https://www.transifex.com/ato/yam/translate/#de/trunk/20247492?qt=Schliessen


2016-08-11 7:30 GMT+02:00, Thore Böckelmann <notifications@github.com>:

**Comment by tboeckel** [comment]
Just should have received an invitation from Transfex. Now you are allowed to translate and review the german translation of YAM.

Please let me know if you want to be added for other projects as well.

**Comment by polluks** [comment]
thanks


Am 17. August 2016 07:34:29 MESZ, schrieb "Thore Böckelmann" <notifications@github.com>:
>Just should have received an invitation from Transfex. Now you are
>allowed to translate and review the german translation of YAM.
>
>Please let me know if you want to be added for other projects as well.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jens-maus/yam/issues/637#issuecomment-240317644

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
