### ISSUE TITLE
Copy&paste crashes texteditor.mcc

### ISSUE THREAD

**Issue by TSK007** [jens-maus/yam#642]
Trying copy marked text or paste in YAM 2.9p1, texteditor.mcc crashes every time. AmigaOS4.1 FE, MUI5 21.1. TextEditor.mcc 15.47 [OS4/PPC] (6.8.16).

**Comment by tboeckel** [comment]
This has been reported and fixed already (https://github.com/amiga-mui/texteditor/issues/4). Fixed binaries for AmigaOS3 and AmigaOS4 can be found there as well:
https://github.com/amiga-mui/texteditor/files/412831/te_os3.zip
https://github.com/amiga-mui/texteditor/files/412832/te_os4.zip

BTW, the bugtracker of TextEditor.mcc would have been a better place for this report.
