### ISSUE TITLE
Can't send Mails using Yahoo account

### ISSUE THREAD

**Issue by Weber-Frank** [jens-maus/yam#648]
I can't send E-Mails with the Version YAM 2.10-dev (28.10.2016) Copyright (C) 2000-2016 YAM Open Source Team [OS3/m68k, 87c29ff]
I get after the SSL Cert warning (see Picture) this Error:
```
Fehler beim Lesen der Nachrichtendatei: YAM:Folders/Archiv_Ausgang/SQt2vAALz90=.001,N.
Die Datei existiert zwar, aber beim Lesen trat ein Fehler auf.
(31.10.2016 22:21:31)
```

Here is the debug log with some datas replaced with x'es:

```
Neuer Shell-Prozeß 11
[CLI 13]
11.DFU-YAM:YAM> yam debug
SERVER['opionline@smtp.mail.yahoo.com', 0037]: 220 smtp.mail.yahoo.com ESMTP ready
CLIENT['opionline@smtp.mail.yahoo.com', 0020]: EHLO [192.168.1.2]
SERVER['opionline@smtp.mail.yahoo.com', 0025]: 250-smtp.mail.yahoo.com
SERVER['opionline@smtp.mail.yahoo.com', 0016]: 250-PIPELINING
SERVER['opionline@smtp.mail.yahoo.com', 0019]: 250-SIZE 41697280
SERVER['opionline@smtp.mail.yahoo.com', 0015]: 250-8 BITMIME
SERVER['opionline@smtp.mail.yahoo.com', 0040]: 250 AUTH PLAIN LOGIN XOAUTH2 XYMCOOKIE
CLIENT['opionline@smtp.mail.yahoo.com', 0012]: AUTH LOGIN
SERVER['opionline@smtp.mail.yahoo.com', 0018]: 334 VXxxxxxxxxxx
CLIENT['opionline@smtp.mail.yahoo.com', 0014]: b3xxxxxxxxxx
SERVER['opionline@smtp.mail.yahoo.com', 0018]: 334 UGxxxxxxxxxx
CLIENT['opionline@smtp.mail.yahoo.com', 0034]: Qmxxxxxxxxxxxxxxxxxxxxxxxxxxxx==
SERVER['opionline@smtp.mail.yahoo.com', 0014]: 235 2.0.0 OK
CLIENT['opionline@smtp.mail.yahoo.com', 0041]: MAIL FROM:<xxxxxxxxx@yahoo.de> SIZE=624
SERVER['opionline@smtp.mail.yahoo.com', 0020]: 250 OK , completed
CLIENT['opionline@smtp.mail.yahoo.com', 0033]: RCPT TO:<xxxxxxx@alice-dsl.net>
SERVER['opionline@smtp.mail.yahoo.com', 0020]: 250 OK , completed
CLIENT['opionline@smtp.mail.yahoo.com', 0006]: DATA
SERVER['opionline@smtp.mail.yahoo.com', 0036]: 354 Start Mail. End with CRLF.CRLF
```

With Version YAM 2.10-dev (24.09.2016) Copyright (C) 2000-2016 YAM Open Source Team [OS3/m68k, 5d708cd]
i can send E-Mails but i have to change the Date first because YAM won't start with the actual date.

**Comment by Weber-Frank** [comment]
![pic007-1](https://cloud.githubusercontent.com/assets/23178317/19874032/a61e4754-9fc2-11e6-950c-a939e0b1b6a0.png)

**Comment by jens-maus** [comment]
Thanks for your report. Is there some more information from the version that can't send emails? In your debug log I can just see that the last line says that the main mail data should be send and finished with CRLF.CRLF but nothing further is shown?!?

And why are you attaching a screenshot of the certificate requester?

**Comment by Weber-Frank** [comment]
The screenshot is attached to show what i mean with SSL Cert warning. I clicked of course "Akzeptieren"

Here is no more in the debug log. Instead of sending the data i get the Errormessage in the Error requester.

That should follow (just created with the working version with changed date to 01 Oct 2016):
"
SERVER['opionline@smtp.mail.yahoo.com', 0036]: 354 Start Mail. End with CRLF.CRLF
CLIENT['opionline@smtp.mail.yahoo.com', 0038]: From: Frank Weber <xxxxxxxxx@yahoo.de>
CLIENT['opionline@smtp.mail.yahoo.com', 0002]: 
CLIENT['opionline@smtp.mail.yahoo.com', 0042]: Reply-To: Frank Weber <xxxxxxxxx@yahoo.de>
CLIENT['opionline@smtp.mail.yahoo.com', 0002]: 
CLIENT['opionline@smtp.mail.yahoo.com', 0037]: To: xxxxxxxxx <xxxxxxx@alice-dsl.net>
CLIENT['opionline@smtp.mail.yahoo.com', 0002]: 
CLIENT['opionline@smtp.mail.yahoo.com', 0044]: Date: Sat, 01 Oct 2016 18:51:04 +0200 (CEST)
CLIENT['opionline@smtp.mail.yahoo.com', 0002]: 
CLIENT['opionline@smtp.mail.yahoo.com', 0053]: Message-ID: <48e3c694e0.41451c50@smtp.mail.yahoo.com>
CLIENT['opionline@smtp.mail.yahoo.com', 0002]: 
CLIENT['opionline@smtp.mail.yahoo.com', 0062]: User-Agent: YAM/2.10-dev (AmigaOS3; m68k; rv:20160924-5d708cd)
CLIENT['opionline@smtp.mail.yahoo.com', 0002]: 
CLIENT['opionline@smtp.mail.yahoo.com', 0020]: OpenPGP: id=D9C3FE06
CLIENT['opionline@smtp.mail.yahoo.com', 0002]: 
CLIENT['opionline@smtp.mail.yahoo.com', 0018]: Subject: Sendetest
CLIENT['opionline@smtp.mail.yahoo.com', 0002]: 
CLIENT['opionline@smtp.mail.yahoo.com', 0017]: MIME-Version: 1.0
CLIENT['opionline@smtp.mail.yahoo.com', 0002]: 
CLIENT['opionline@smtp.mail.yahoo.com', 0024]: Content-Type: text/plain
CLIENT['opionline@smtp.mail.yahoo.com', 0002]: 
CLIENT['opionline@smtp.mail.yahoo.com', 0002]: 
CLIENT['opionline@smtp.mail.yahoo.com', 0006]: Hallo 
CLIENT['opionline@smtp.mail.yahoo.com', 0002]: 
CLIENT['opionline@smtp.mail.yahoo.com', 0002]: 
CLIENT['opionline@smtp.mail.yahoo.com', 0009]: Sendetest
CLIENT['opionline@smtp.mail.yahoo.com', 0002]: 
CLIENT['opionline@smtp.mail.yahoo.com', 0005]: 
.
SERVER['opionline@smtp.mail.yahoo.com', 0020]: 250 OK , completed
CLIENT['opionline@smtp.mail.yahoo.com', 0006]: QUIT
SERVER['opionline@smtp.mail.yahoo.com', 0034]: 221 Service Closing transmission
"

**Comment by jens-maus** [comment]
Ah ok, now I understand. The actual error is the `Die Datei existiert zwar, aber beim Lesen trat ein Fehler auf.` message. Right? Can you please also provide a snoopdos output please where one can see what might be the reason why the corresponding output file cannot be read? Another thing I am curious about is that the error message says `YAM:Folders/Archiv_Ausgang/` as the path to the temporary file it tries to send. Are you sure `Archiv_Ausgang` is correct and the same like for the older version of YAM?

**Comment by jens-maus** [comment]
Another thing you could please try is to use the debug version of the nightly build and attaching the corresponding debug output here after having catched it on the serial line or forwarding it to a file (see https://yam.ch/wiki/FAQ/Debugging).

**Comment by Weber-Frank** [comment]
Yes correct this is the error i get.
Maybe a tip for finding the bug: The Error is not written to the logfile.

The Path is funny but correct,, see the last part of the Snoopdoslog:
```
4348  BetterSt OpenDev     clipboard.device                                   Unit 0  OK   
4349  BetterSt FindSem     NSDPatch (8.3.2002)                                        OK   
4350  TextEdit OpenDev     clipboard.device                                   Unit 0  OK   
4351  TextEdit FindSem     NSDPatch (8.3.2002)                                        OK   
4352  yam      Lock        T:YAMw09e405f8-1.txt                               Read    OK   
4353  yam      Open        T:YAMw09e405f8-1.txt                               Write   OK   
4354  yam      ChangeDir   RAM:T                                                           
4355  yam      ChangeDir   DH3:YAM                                                         
4356  yam      Open        T:YAMw09e405f8-1.txt                               Read    OK   
4357  yam      Lock        YAM:Folders/Archiv_Ausgang/SQzApgAG3Vg=.001,N      Read    Fail 
4358  yam      Lock        YAM:Folders/Archiv_Ausgang/SQzApgAG3Vg=.001,N      Read    Fail 
4359  yam      Open        YAM:Folders/Archiv_Ausgang/SQzApgAG3Vg=.001,N      Modify  OK   
4360  yam      Open        T:YAMw09e405f8-1.txt                               Read    OK   
4361  yam      ChangeDir   DH3:YAM/Folders/Archiv_Ausgang                                  
4362  yam      ChangeDir   DH3:YAM                                                         
4363  yam      Open        YAM:Folders/Archiv_Ausgang/SQzApgAG3Vg=.001,N      Read    OK   
4364  yam      Lock        YAM:Folders/Archiv_Ausgang/SQzApgAG3Vg=.001,N      Read    OK   
4365  yam      Lock        YAM:Folders/Archiv_Ausgang/.index                  Read    OK   
4366  yam      Open        YAM:Folders/Archiv_Ausgang/.index                  Read    OK   
4367  yam      Delete      YAM:Folders/Archiv_Ausgang/.index                          OK   
4368  yam      Open        YAM:logs/YAM-Nov2016.log                           Modify  OK   
4369  yam      ChangeDir   DH3:YAM/logs                                                    
4370  yam      ChangeDir   DH3:YAM                                                         
4371  yam      Delete      T:YAMw09e405f8-1.txt                                       OK   
4372  yam      Delete      T:YAMw09e405f8-1.txt                                       Fail 
4373  YAM thre OpenLib     bsdsocket.library                                  Ver 2   OK   
4374  YAM thre OpenDev     timer.device                                       Unit 0  OK   
4375  YAM thre FindSem     NSDPatch (8.3.2002)                                        OK   
4376  YAM thre OpenLib     miami.library                                      Ver 10  OK   
4377  yam      OpenLib     mui/Virtgroup.mui                                  Ver 19  OK   
4378  yam      OpenLib     mui/Gauge.mui                                      Ver 19  OK   
4379  yam      OpenLib     mui/Gauge.mui                                      Ver 19  OK   
4380  yam      LockScreen  Workbench                                                  OK   
4381  yam      OpenLib     muiwinscroller.class                               Ver 19  OK   
4382  ramlib   Load        LIBS:muiwinscroller.class                                  OK   
4383  ramlib   OpenLib     graphics.library                                   Ver 36  OK   
4384  ramlib   OpenLib     intuition.library                                  Ver 36  OK   
4385  ramlib   OpenLib     utility.library                                    Ver 36  OK   
4386  yam      OpenLib     muiwinborder.class                                 Ver 19  OK   
4387  YAM thre OpenDev     timer.device                                       Unit 1  OK   
4388  YAM thre FindSem     NSDPatch (8.3.2002)                                        OK   
4389  YAM thre OpenDev     timer.device                                       Unit 1  OK   
4390  YAM thre FindSem     NSDPatch (8.3.2002)                                        OK   
4391  YAM thre Lock        PROGDIR:Resources/certificates/7651b327.0          Read    Fail 
4392  YAM thre GetVar      OPENSSL_ALLOW_PROXY_CERTS                          Any*    Fail 
4393  yam      OpenLib     muiwinborder.class                                 Ver 19  OK   
4394  YAM thre OpenDev     timer.device                                       Unit 1  OK   
4395  YAM thre FindSem     NSDPatch (8.3.2002)                                        OK   
4396  YAM thre Open        YAM:Folders/Archiv_Ausgang/SQzApgAG3Vg=.001,N      Read    OK   
4397  yam      Open        YAM:logs/YAM-Nov2016.log                           Modify  OK   
4398  yam      ChangeDir   DH3:YAM/logs                                                    
4399  yam      ChangeDir   DH3:YAM                                                         
4400  YAM thre Open        YAM:Folders/Archiv_Ausgang/SQzApgAG3Vg=.001,N      Read    OK   
4401  YAM thre Lock        YAM:Folders/Archiv_Ausgang/SQzApgAG3Vg=.001,N      Read    OK   
4402  yam      OpenLib     NFloattext.mcc                                     Ver 0   OK   
4403  yam      OpenLib     NListview.mcc                                      Ver 0   OK   
4404  yam      OpenLib     mui/Numericbutton.mui                              Ver 19  OK   
4405  ramlib   Load        LIBS:mui/Numericbutton.mui                                 OK   
4406  yam      OpenLib     muimaster.library                                  Ver 19  OK   
4407  yam      OpenLib     muigfx.library                                     Ver 19  OK   
4408  yam      OpenLib     muilowlevel.library                                Ver 19  OK   
4409  yam      LockScreen  Workbench                                                  OK   
4410  yam      OpenLib     muiwinborder.class                                 Ver 19  OK   
4411  yam      Rename      YAM:Folders/Archiv_Ausgang/SQzApgAG3Vg=.001,N                   
4412  yam      to -->      YAM:Folders/Archiv_Ausgang/SQzApgAG3Vg=.001,NE             OK   
```
After that the Mail is not sent in the Outgoing folder. 

Did you try to send a Mail with the latest YAM Version, maybe you get the same Error?
Then i can save myself the work with the debug version.

BTW: At the start of YAM i get over 2000(!) entries in the Snoopdos log like:
`1765  YAM-24.0 GetVar      codeset_default                                    Global  Fail `
Is this really necessary so often call this function?

**Comment by Weber-Frank** [comment]
Forget to mention:
The 2 entries in the logfile write anything like:
`01.11.2016 21:48:39 [10] Neue Nachricht an 'xxxxxxxx' über 'Sendetest' mit 0 Anhängen erstellt
01.11.2016 21:48:45 [41] Verbunden mit SMTP-Server 'smtp.mail.yahoo.com'`

**Comment by jens-maus** [comment]
commit https://github.com/jens-maus/yam/commit/941adb5593ba40d97a7598ccfdb32627125fcb3f seem to have solved the issues. Thus, closing this ticket.
