### ISSUE TITLE
YAM nightly build crash/GR when clicking on config button (MUI v5 nightly build)

### ISSUE THREAD

**Issue by javierdlr** [jens-maus/yam#649]
Hi I get a crash/GR with YAM 2.10dev (10-11-2016) nightly build crash/GR when clicking on config button, to open YAM prefs,  and MUIv5 nightly build (svn5567)

**Comment by javierdlr** [comment]
Crash log for task "YAM"
Generated by GrimReaper 53.19
Crash occured in module muimaster.library at address 0x7F7CCA30
Type of crash: DSI (Data Storage Interrupt) exception
Alert number: 0x80000003

Register dump:
GPR (General Purpose Registers):
   0: 7F7CC9FC 5C46E040 01876EE4 5C46E418 5C46E080 5C46E388 5C46E388 5FB8B034 
   8: 00000000 80420629 0228DCA2 02340000 40822888 5C47F9F4 00000002 00000000 
  16: 80421788 00000001 80428B9D 5FB8B02C 80428398 00000000 80420629 80421788 
  24: 5FB90000 8042120B 5C46E080 5FB8B08C 5B4D8CF8 5F4F8E10 5B4D8AF0 5C46E388 


FPR (Floating Point Registers, NaN = Not a Number):
   0:              nan          3.93555          0.99999     1.28862e+267 
   4:    -6.65657e+306       4.5036e+15     -1.54389e-05      -0.00196464 
   8:      3.30205e-15      3.30205e-14                1         0.666667 
  12:       4.5036e+15               86     -1.00582e+16    -4.93318e+304 
  16:     9.14818e+245    -6.84646e+303     1.39262e+140     -3.09868e-82 
  20:      1.8702e+299      1.9303e+217    -5.59245e+227    -2.19082e+227 
  24:    -5.07964e+284    -2.12428e+258    -8.14215e+302    -8.30195e+294 
  28:     2.84197e+182     4.02182e+305    -1.46483e+299    -7.02084e+144 

FPSCR (Floating Point Status and Control Register): 0x82004000


SPRs (Special Purpose Registers):
           Machine State (msr) : 0x0002F030
                Condition (cr) : 0x00000001
      Instruction Pointer (ip) : 0x7F7CCA30
       Xtended Exception (xer) : 0xFFFFFFFF
                   Count (ctr) : 0x80080008
                     Link (lr) : 0x5B02F2EC
            DSI Status (dsisr) : 0x80080009
            Data Address (dar) : 0x5B02F358



680x0 emulated registers:
DATA: A2B33500 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
ADDR: 6FFF8000 A2AD8E00 00000000 00000000 00000000 00000000 00000000 5C46D940 
FPU0:                0                0                0                0 
FPU4:                0                0                0                0 



Symbol info:
Instruction pointer 0x7F7CCA30 belongs to module "muimaster.library" (PowerPC) 
Symbol: CycleDispatcher + 0x398 in section 1 offset 0x0003BA2C

Stack trace:
    [Cycle.c:336] LIBS:muimaster.library:CycleDispatcher()+0x398 (section 1 @ 0x3BA2C)
    [Cycle.c:324] LIBS:muimaster.library:CycleDispatcher()+0x364 (section 1 @ 0x3B9F8)
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x0000a2ac
    YAM:m_TZoneLocationChooser_OM_SET()+0xe0 (section 1 @ 0xFA24C)
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x000218c8
    native kernel module intuition.library.kmod+0x00009ee4
    native kernel module intuition.library.kmod+0x0000a184
    YAM:m_TZoneLocationChooser_UpdateLocations()+0x58 (section 1 @ 0xFA32C)
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x0000a3f4
    native kernel module intuition.library.kmod+0x0000a034
    YAM:m_TZoneLocationChooser_OM_SET()+0x15c (section 1 @ 0xFA2C8)
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x000218c8
    native kernel module intuition.library.kmod+0x00009ee4
    native kernel module intuition.library.kmod+0x0000a184
    YAM:m_TZoneChooser_OM_SET()+0x178 (section 1 @ 0xF96FC)
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x000218c8
    native kernel module intuition.library.kmod+0x00009ee4
    native kernel module intuition.library.kmod+0x0000a184
    YAM:m_FirstStepsConfigPage_MUIM_ConfigPage_ConfigToGUI()+0xf4 (section 1 @ 0x9FE78)
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x0000a3f4
    native kernel module intuition.library.kmod+0x0000a034
    YAM:m_ConfigWindow_OM_NEW()+0x1088 (section 1 @ 0x99484)
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x0000a348
    YAM:YAM_NewObject()+0x194 (section 1 @ 0x7FC10)
    YAM:m_YAMApplication_OpenConfigWindow()+0xd0 (section 1 @ 0x114E64)
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x0000a3f4
    LIBS:mui/TheButton.mcc:_Dispatcher()+0x1580 (section 1 @ 0x7FF8)
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x0000a3f4
    [Notify.c:332] LIBS:muimaster.library:m_Notify_SET()+0x420 (section 1 @ 0x63E4C)
    [Area.c:1734] LIBS:muimaster.library:m_Area_SET()+0x1e0 (section 1 @ 0x33F4C)
    [Area.c:2692] LIBS:muimaster.library:AreaDispatcher()+0x1030 (section 1 @ 0x35E54)
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x0000a2ac
    LIBS:mui/TheButton.mcc:mSets()+0x6e4 (section 1 @ 0x64F8)
    LIBS:mui/TheButton.mcc:_Dispatcher()+0xe84 (section 1 @ 0x78FC)
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x000218c8
    native kernel module intuition.library.kmod+0x00009ee4
    native kernel module intuition.library.kmod+0x0000a184
    [Area.c:2135] LIBS:muimaster.library:m_Area_HandleEvent()+0x5ec (section 1 @ 0x2ED20)
    [Area.c:2702] LIBS:muimaster.library:AreaDispatcher()+0x17a8 (section 1 @ 0x365CC)
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x0000a2ac
    LIBS:mui/TheButton.mcc:_Dispatcher()+0x200 (section 1 @ 0x6C78)
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x0000a2d8
    native kernel module intuition.library.kmod+0x00009f8c
    [Window.c:1255] LIBS:muimaster.library:SendIMsgs()+0x2bc (section 1 @ 0x7BCE0)
    [Window.c:2645] LIBS:muimaster.library:m_Window_Input()+0xa7c (section 1 @ 0x80DD4)
    [Window.c:6981] LIBS:muimaster.library:WindowDispatcher()+0xdc (section 1 @ 0x855F8)
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x0000a2ac
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x0000a3f4
    [Application.c:2083] LIBS:muimaster.library:m_Application_NewInput()+0x89c (section 1 @ 0x286E0)
    [Application.c:3983] LIBS:muimaster.library:ApplicationDispatcher()+0x18d4 (section 1 @ 0x2D098)
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x0000a2ac
    native kernel module intuition.library.kmod+0x00021448
    native kernel module intuition.library.kmod+0x000215ec
    native kernel module intuition.library.kmod+0x0000a3f4
    native kernel module intuition.library.kmod+0x0000a034
    YAM:main()+0xcec (section 1 @ 0x5358)
    native kernel module newlib.library.kmod+0x00001e80
    native kernel module newlib.library.kmod+0x00002fb4
    native kernel module newlib.library.kmod+0x00003060
    YAM:_start()+0x170 (section 1 @ 0x16C)
    native kernel module dos.library.kmod+0x00026038
    native kernel module kernel.debug+0x00067db0
    native kernel module kernel.debug+0x00067df8

PPC disassembly:
 7f7cca28: 419e08a8   beq-              cr7,0x7F7CD2D0
 7f7cca2c: 7d074378   mr                r7,r8
*7f7cca30: 81480000   lwz               r10,0(r8)
 7f7cca34: 39200000   li                r9,0
 7f7cca38: 2f8a0000   cmpwi             cr7,r10,0

System information:

CPU 
 Model: AMCC PPC460EX V1.2 
 CPU speed: 1155 MHz 
 FSB speed: 231 MHz 
 Extensions:  

Machine 
 Machine name: Sam460ex 
 Memory: 2097152 KB 
 Extensions: bus.pci bus.pcie

**Comment by tboeckel** [comment]
This will be fixed by the next nightly build of MUI.

**Comment by javierdlr** [comment]
Confirmed YAM's config window shows again without problem. THX
