### ISSUE TITLE
nitghly builds expiration date and new build created

### ISSUE THREAD

**Issue by javierdlr** [jens-maus/yam#655]
## Submission type
  - Bug report / Feature Request

## YAM version
Nighly build

## Used operating system
  - AmigaOS4/PPC

## Used Amiga system
SAM460ex

When the current nitghly build expires, some poeple complained the "new" nighlt build isn't downloadable/ready yet.

As I don't know how/when then new monthly builds gets (re)build, maybe adding a more "relaxed" EXPDATE (33-35 days) will then be safe so a new version gets build and nitghly-build doesn't expire.

**Comment by javierdlr** [comment]
http://amigaworld.net/modules/newbb/viewtopic.php?topic_id=41265&start=20&post_id=794292&order=0&viewmode=flat&pid=794212&forum=14#794212

**Comment by MichaelMerkel** [comment]
the user lives in australia... quite some hours advanced.
so he already has reached the expire date while here in germany it is still some hours to go.

-> so please create the nightly one day earlier and let it run one day longer or like that...

regards...
michael
