### ISSUE TITLE
Possibility to read in ca-bundle.crt from a given path and name

### ISSUE THREAD

**Issue by raziel-** [jens-maus/yam#657]
## Submission type
  - Feature Request

## YAM version
[2.9p1]

## Used operating system
   - AmigaOS4/PPC 4.1 FE Update 1
 
## Used Amiga system
[AmigaOneX1000]

## Expected behaviour you didn't see
[It would be nice if you could add either a normal or a hidden option/setting to read/use the "Bundle of CA Root Certificates" (ca-bundle.crt) from a user given path and a user given name (e.g. curl-ca-bundle.crt or certdata.txt).
This way updating this file would become cleaner, if a users chooses to do so by him/herself.
My preference would be to have the file in DEVS: and let YAM read it from there.
(nb: Odyssey lets the user decide from where to read that file, just fyi)

Config/Security would be a good candidate or the hidden settings in .config, it's your decision obviously]

## Unexpected behaviour you saw
[Yam, right now, automatically reads and uses a specially named file (ca-bundle.crt) from it's Resources subdir.
This file should of course stay there (and also still be updated when a YAM update is rolled out) and read/used by default since not all users go through all of their settings, but the possibility of giving a user path and name for that file would add a nice little touch of controllability.]

## Steps to reproduce the problem
[No problem]

**Comment by jens-maus** [comment]
There should be no need for a user to replace or override this file. There are enough places in AmiSSL to place an own certificate in the global AmiSSL:certs path which YAM should also evaluate, use.

**Comment by raziel-** [comment]
Ah, i forgot about AmiSSL

Of course it would fit better to let AmiSSL take care of that.
Some "foreign" programs like Odyssey uses this file for their certs and since YAM 2.9p1 does the same i thought it would be a good idea to bring them together.

If AmiSSL is going to be used together with YAM 2.10 i think you can trash this FR
