### ISSUE TITLE
Replying to new draft causes crash

### ISSUE THREAD

**Issue by Hypexed** [jens-maus/yam#658]
## Submission type
  - Bug report
## YAM version
2.10-dev

## Used operating system
  - AmigaOS4/PPC

## Used Amiga system
AmigaOne XE

## Expected behaviour you didn't see
An editing window.

## Unexpected behaviour you saw
A crash.

## Steps to reproduce the problem
Open new draft: Press "New" button.

Save draft: Press "Save as draft" button.

Select draft: Select Drafts folder. Click on new draft.

Attempt reply to draft: Click "Reply" buton.

**Comment by raziel-** [comment]
Regression

2.9p1 is fine

**Comment by tboeckel** [comment]
Where is the crashlog?

**Comment by Hypexed** [comment]
It must have lost in the ether. I used Odyssey to report it. And upload the crashlog. I selected it. Bug reporting on AmigaOS is now harder because the latest browser you can find is still too old for a site like this that requires latest HTML technology.
[Crashlog_YAM_2017-02-21_01-15-50.txt](https://github.com/jens-maus/yam/files/1001332/Crashlog_YAM_2017-02-21_01-15-50.txt)
