### ISSUE TITLE
Could d&d of mails into read window work?

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#66]
**Originally by _mario@cattaneo.de_ on 2010-03-04 19:21:11 +0100**

___
It would be nice if it was possible to drag a mail from the list onto an open read window. It would then be displayed in the open window (replacing the current message of course ;)).

**Comment by tboeckel** [comment]
**Originally on 2012-04-26 17:18:03 +0200**

___
On the one hand this could be implemented quite easily (I guess). But on the other hand, what would really be the benefit of such a feature? If you have to move the mouse to the main window to select a different mail (for dragging) then double clicking this mail is much easier than having to drag it around. Furthermore it is unclear how the situation when several mails are dragged around has to be handled.

All in all I must say that this feature request does not make as much sense as it perhaps does on the first thought.
