### ISSUE TITLE
Multiple duplicated keyboard shortcuts in GUI

### ISSUE THREAD

**Issue by tac1ica** [jens-maus/yam#660]
Cosmetic, but this breaks usability when using the keyboard and is ugly. Tested with 2.9p1 using the built-in GUI.

There is a number of duplicated keyboard shortcuts scattered all over the GUI in the default English GUI. I suppose that providing a patch against the YAM.pot file won't do, so I'll leave it to others to fix this. I didn't check the catalogs. Here's a listing of the clashing GUI elements I found:

### Write window

* In the "Message" tab, "_Cc" and the bottom "_Cancel" button
* In the "Attachments" tab, "Re_move" and "_MIME type"
* In the "Options" tab, "_Charset" and "_Cancel" -- "_Delete after sending" and "Save as _draft" 

### Main window

* The "Project/Hide" and "Help/Contents" menu items are both using RAmiga-H.

### Address book window

* "Remo_ve" and "Search on gra_vatar.com..."

### Configuration window

* "TCP/IP" page, POP3 tab: "Serve_r/Port" and "_Requester" -- "Delete mail _on server" and "S_ound" -- "_Password" and "_Pre-selection" 
* "Read" page: "Show te_xt colors" and "Show te_xt styles"
* "Write" page: "Closing p_hrase" and "Default c_harset"
* "Signature" page: "_Active" and "T_agline separator"
* "MIME" page: "Display _charset" and "_Cancel"
* "Miscellaneous" page: "D_ecode files to" and "_External editor" -- "Download _path:" and "A_ppIcon on Workbench" -- "For _temporary files" and "_Transfer window"
* "Look & Feel" page, "Main window" tab: "Posi_tion" and "Rela_tive date output"

**Comment by jens-maus** [comment]
@tac1ica Thanks for your  comments. As our development resources are quite limited (as you know) please feel free to submit either a pull request with changes against the YAM.pot file so that we can integrate your changes right away or use transifex to edit translations based on the pot file.

**Comment by tac1ica** [comment]
I don't get how pull requests work so here's a patch. Fixing the duplicated shortcut for menu items in the main window is up to you...

[YAM.pot.patch.txt](https://github.com/jens-maus/yam/files/1080499/YAM.pot.patch.txt)

**Comment by jens-maus** [comment]
@tac1ica Well, you really should teach yourself in how git and GitHub works so that you can use/send pull requests in future. I am sorry, but I don't have time to work on YAM myself anytime soon or even integrate the patch myself. So this will have to wait if you are not able to provide pull requests.
