### ISSUE TITLE
2.10-dev 27.06.2017 1ee6879b - console output

### ISSUE THREAD

**Issue by MichaelMerkel** [jens-maus/yam#663]
## Submission type
  - Bug report

## YAM version
2.10-dev 27.06.2017 1ee6879b

## Used operating system
  - AmigaOS4/PPC

## Used Amiga system
4.2beta

## Unexpected behaviour you saw
console output during run.
yam opens a console window and writes the following debug output:
display 57861950 5051f558
display 558bc2d0 5051fd80
display 57861a40 505205a8
display 585e05d0 50520dd0
display 585e0650 505215f8
...

## Steps to reproduce the problem
just run YAM - no debug version.

**Comment by tboeckel** [comment]
That output has been removed already. The current nightly build is quiet again.
