### ISSUE TITLE
Merge old ChangeLog file with the latest changes

### ISSUE THREAD

**Issue by samo79** [jens-maus/yam#665]
Since the transition to github the old ChangeLog text file of YAM has been lost and it is now unclear
what daily changes has been made to the program at a time.
Actually a fresh new one is included and updated (even if always limited to the very latest commits only)
I wonder if it could be possible to retrieve the latest complete ChangeLog and make a merge with all the latest changes since March 2016 so to have a complete history of all the changes made to YAM

Latest full changelog attached:

http://s000.tinyupload.com/index.php?file_id=38144874781681996734

**Comment by jens-maus** [comment]
Sorry, but this won't happen anytime soon are at all. We simply don't have time to manually maintain a changelog like this was done in former times. In addition, the functionality git and github provides is really be enough to get an idea what was actually changed. In addition, this is how modern open source software development is working these days. So please use git or github yourself to get information on the actual changes. However, i will see if i can at least tune the automatically generated changelog to combine changes from the same day. But we won' bring back the old ChangeLog like in former times (all change information can be gathered via git, thought)
