### ISSUE TITLE
yam complains about temporary file at start

### ISSUE THREAD

**Issue by MichaelMerkel** [jens-maus/yam#667]
## Submission type
  - Bug report

## YAM version
2.10-dev 16.01.2018 a63a202d

## Used operating system
  - AmigaOS4/PPC

## Used Amiga system
X1000

## Unexpected behaviour you saw
every day at first startup yam complains in the error window:

[Kann temporäre Datei 'T:YAMt0000002a.tmp' nicht öffnen.
Überprüfen Sie die Pfadeinstellung in der Konfiguration.
]
when i close yam and restart it i see no more popup.

## Steps to reproduce the problem
i just start it for the first time of the day.

*maybe* this can happen, if yam is not closed when shuting down the computer?
whcih logs can i provide?

regards
michael

**Comment by MichaelMerkel** [comment]
btw... i don't know if this is always the same filename. i'll check next time it happens.

**Comment by tboeckel** [comment]
If the issue happens on the first start only I'd suspect the update check. That's the only location which can trigger that error message. Try to disable it or set it to a longer period than "daily". It seems the temporary file containing the update information was not downloaded correctly, although YAM thinks the download was successful.

**Comment by MichaelMerkel** [comment]
seems you're right.
if i trigger the update check manually via menu i also get the popup - each time!

regards...
michael

**Comment by tboeckel** [comment]
Ok. Could you please create a NET debug log using the debug build of YAM and checking for updates? That should explain why YAM is so uncertain about the result of the download.

**Comment by MichaelMerkel** [comment]
hope i did it correct...

**Comment by MichaelMerkel** [comment]
Sashimi installed ([Ctrl]+C or "Break 1" to remove)
** YAM 2.10-dev [OS4/PPC, a63a202d, GCC 5.4.0] date 16.01.2018 (build 20180116) startup **********************
Exec version: v53.97
Initializing runtime debugging:
parsing ENV:yamdebug content 'net'
set 'net' debug flag
set debug classes/flags (env:yamdebug): 000000fe/00000403
set debug files: ''
** Normal processing follows ***************************************
00:D|00:00:00.000000| YAM.c:229:InitLib: library intuition.library v54.26 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000| YAM.c:229:InitLib: library icon.library v54.6 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000| YAM.c:229:InitLib: library utility.library v54.1 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000| YAM.c:229:InitLib: library diskfont.library v53.11 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000|  NewReadArgs.c:471:ReadArgs() okay
00:D|00:00:00.000000|YAM.c:2563:ProgDir.: 'Programme:NetzSoftWare/YAM'
00:D|00:00:00.000000|YAM.c:2564:ProgName: 'YAM.debug'
00:D|00:00:00.000000|YAM.c:2583:using themes directory 'Programme:NetzSoftWare/YAM/Resources/Themes'
00:D|00:00:00.000000|  YAM.c:229:InitLib: library locale.library v54.2 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000|  YAM.c:229:InitLib: library codesets.library v6.20 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000|  Locale.c:2225:successfully opened YAM.catalog v10.47 (language: 'deutsch', codeset: 111)
00:D|00:00:00.000000|  YAM.c:229:InitLib: library graphics.library v54.241 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000|  YAM.c:229:InitLib: library layers.library v54.12 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000|  YAM.c:229:InitLib: library workbench.library v53.60 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000|  YAM.c:229:InitLib: library keymap.library v53.9 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000|  YAM.c:229:InitLib: library iffparse.library v53.3 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000|  YAM.c:229:InitLib: library rexxsyslib.library v53.4 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000|  YAM.c:229:InitLib: library datatypes.library v54.7 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000|  YAM.c:229:InitLib: library muimaster.library v21.110 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000|  YAM.c:229:InitLib: library openurl.library v7.17 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000|  YAM.c:229:InitLib: library expat.library v53.6 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000|  YAM.c:229:InitLib: library application.library v53.14 with iface 'application' v2 successfully opened.
00:D|00:00:00.000000|  YAM.c:304:checking for v26.15+ of 'TheBar.mcc'
00:D|00:00:00.000000|  YAM.c:325:found TheBar.mcc v26.19 through MUIA_Version/Revision
00:D|00:00:00.000000|  YAM.c:330:found TheBar.mcc to be >= v26.15
00:D|00:00:00.000000|  YAM.c:350:successfully created test custom class of 'TheBar.mcc'
00:D|00:00:00.000000|  YAM.c:304:checking for v26.15+ of 'TheBarVirt.mcc'
00:D|00:00:00.000000|  YAM.c:325:found TheBarVirt.mcc v26.19 through MUIA_Version/Revision
00:D|00:00:00.000000|  YAM.c:330:found TheBarVirt.mcc to be >= v26.15
00:D|00:00:00.000000|  YAM.c:350:successfully created test custom class of 'TheBarVirt.mcc'
00:D|00:00:00.000000|  YAM.c:304:checking for v26.15+ of 'TheButton.mcc'
00:D|00:00:00.000000|  YAM.c:325:found TheButton.mcc v26.19 through MUIA_Version/Revision
00:D|00:00:00.000000|  YAM.c:330:found TheButton.mcc to be >= v26.15
00:D|00:00:00.000000|  YAM.c:350:successfully created test custom class of 'TheButton.mcc'
00:D|00:00:00.000000|  YAM.c:304:checking for v11.28+ of 'BetterString.mcc'
00:D|00:00:00.000000|  YAM.c:325:found BetterString.mcc v11.32 through MUIA_Version/Revision
00:D|00:00:00.000000|  YAM.c:330:found BetterString.mcc to be >= v11.28
00:D|00:00:00.000000|  YAM.c:350:successfully created test custom class of 'BetterString.mcc'
00:D|00:00:00.000000|  YAM.c:304:checking for v20.138+ of 'NList.mcc'
00:D|00:00:00.000000|  YAM.c:325:found NList.mcc v20.143 through MUIA_Version/Revision
00:D|00:00:00.000000|  YAM.c:330:found NList.mcc to be >= v20.138
00:D|00:00:00.000000|  YAM.c:350:successfully created test custom class of 'NList.mcc'
00:D|00:00:00.000000|  YAM.c:304:checking for v19.93+ of 'NListview.mcc'
00:D|00:00:00.000000|  YAM.c:325:found NListview.mcc v19.98 through MUIA_Version/Revision
00:D|00:00:00.000000|  YAM.c:330:found NListview.mcc to be >= v19.93
00:D|00:00:00.000000|  YAM.c:350:successfully created test custom class of 'NListview.mcc'
00:D|00:00:00.000000|  YAM.c:304:checking for v19.74+ of 'NFloattext.mcc'
00:D|00:00:00.000000|  YAM.c:325:found NFloattext.mcc v19.79 through MUIA_Version/Revision
00:D|00:00:00.000000|  YAM.c:330:found NFloattext.mcc to be >= v19.74
00:D|00:00:00.000000|  YAM.c:350:successfully created test custom class of 'NFloattext.mcc'
00:D|00:00:00.000000|  YAM.c:304:checking for v18.45+ of 'NListtree.mcc'
00:D|00:00:00.000000|  YAM.c:325:found NListtree.mcc v18.50 through MUIA_Version/Revision
00:D|00:00:00.000000|  YAM.c:330:found NListtree.mcc to be >= v18.45
00:D|00:00:00.000000|  YAM.c:350:successfully created test custom class of 'NListtree.mcc'
00:D|00:00:00.000000|  YAM.c:304:checking for v15.19+ of 'NBalance.mcc'
00:D|00:00:00.000000|  YAM.c:325:found NBalance.mcc v15.24 through MUIA_Version/Revision
00:D|00:00:00.000000|  YAM.c:330:found NBalance.mcc to be >= v15.19
00:D|00:00:00.000000|  YAM.c:350:successfully created test custom class of 'NBalance.mcc'
00:D|00:00:00.000000|  YAM.c:304:checking for v15.23+ of 'NBitmap.mcc'
00:D|00:00:00.000000|  YAM.c:350:successfully created test custom class of 'NBitmap.mcc'
00:D|00:00:00.000000|  YAM.c:385:successfully opened 'NBitmap.mcc' as library, found v15.28, open count 1
00:D|00:00:00.000000|  YAM.c:304:checking for v15.45+ of 'TextEditor.mcc'
00:D|00:00:00.000000|  YAM.c:325:found TextEditor.mcc v15.50 through MUIA_Version/Revision
00:D|00:00:00.000000|  YAM.c:330:found TextEditor.mcc to be >= v15.45
00:D|00:00:00.000000|  YAM.c:350:successfully created test custom class of 'TextEditor.mcc'
00:D|00:00:00.000000|  YAM.c:642:creating startup semaphore...
00:D|00:00:00.000000| YAM.c:1909:setup internal MUI classes...
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AboutWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AccountList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AddressBookEditGroupPanel' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AddressBookEditListPanel' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AddressBookEditUserPanel' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AddressBookEditWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AddressBookEntryList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AddressBookListtree' as subclass of 'NListtree.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AddressBookToolbar' as subclass of 'TheBarVirt.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AddressBookWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AddressField' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AddressMatchList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AddressMatchPopupWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_Attachment' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AttachmentGroup' as subclass of 'Virtgroup.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AttachmentImage' as subclass of 'Area.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AttachmentKeywordList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AttachmentList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AttachmentRequestWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_Base64Dataspace' as subclass of 'Dataspace.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_BirthdayRequestWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_CheckboxRequestWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_CodesetPopup' as subclass of 'Popobject.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_CodesetPopupList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ConfigPage' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ConfigPageList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ConfigWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_FilterChooser' as subclass of 'Cycle.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_FilterList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_FilterPopupList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_FiltersConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_FirstStepsConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_FolderEditWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_FolderListtree' as subclass of 'NListtree.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_FolderRequestListtree' as subclass of 'YAM_FolderListtree'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_FolderRequestPopup' as subclass of 'Popobject.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_FolderRequestWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_GenericRequestWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_HeaderList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_IdentitiesConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_IdentityChooser' as subclass of 'Cycle.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_IdentityList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ImageArea' as subclass of 'Area.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_InfoBar' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_InfoWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_LookFeelConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_MailServerChooser' as subclass of 'Cycle.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_MailTextEdit' as subclass of 'TextEditor.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_MainFolderListtree' as subclass of 'YAM_FolderListtree'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_MainMailList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_MainMailListGroup' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_MainWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_MainWindowToolbar' as subclass of 'TheBarVirt.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_MimeConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_MimeTypeList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_MimeTypePopup' as subclass of 'Popobject.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_MixedConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ObjectList' as subclass of 'Scrollgroup.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ObjectListitem' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_PassphraseRequestWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_PGPKeyPopup' as subclass of 'Popobject.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_PlaceholderPopup' as subclass of 'Popobject.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_PlaceholderPopupList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_PreselectionWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_QuickSearchBar' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ReadConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ReadMailGroup' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ReadWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ReadWindowStatusBar' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ReadWindowToolbar' as subclass of 'TheBarVirt.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_RecipientString' as subclass of 'BetterString.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ReplyForwardConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ScriptList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ScriptsConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_SearchControlGroup' as subclass of 'YAM_ObjectListitem'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_SearchMailWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_SearchTextWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_SecurityConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ShutdownWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_SignatureChooser' as subclass of 'Cycle.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_SignatureConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_SignatureList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_SignatureTextEdit' as subclass of 'YAM_MailTextEdit'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_SpamConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_SplashWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_StartupQuitConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_StringRequestWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_TCPIPConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ThemeList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_ThemeListGroup' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_TransferControlGroup' as subclass of 'YAM_ObjectListitem'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_TransferControlList' as subclass of 'YAM_ObjectList'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_TransferMailList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_TransferWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_TZoneChooser' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_TZoneContinentChooser' as subclass of 'Cycle.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_TZoneInfoBar' as subclass of 'Text.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_TZoneLocationChooser' as subclass of 'Cycle.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_UpdateComponentList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_UpdateConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_UpdateNotifyWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_UserList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_UserPortraitGroup' as subclass of 'Group.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_WriteAttachmentList' as subclass of 'NList.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_WriteConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_WriteWindow' as subclass of 'Window.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_WriteWindowToolbar' as subclass of 'TheBarVirt.mcc'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_YAMApplication' as subclass of 'Application.mui'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_AddressBookConfigPage' as subclass of 'YAM_ConfigPage'
00:D|00:00:00.000000|  Classes.c:2273:creating class 'YAM_FilterRuleList' as subclass of 'YAM_ObjectList'
00:D|00:00:00.000000| YAM.c:1920:creating root object...
00:D|00:00:00.000000| YAM.c:1933:init libraries...
00:D|00:00:00.000000|  YAM.c:229:InitLib: library xadmaster.library v13.2 with iface 'main' v1 successfully opened.
00:D|00:00:00.000000|  YAM.c:229:InitLib: library xpkmaster.library v5.2 with iface 'main' v1 successfully opened.
00:E|00:00:00.000000|  YAM.c:576:error on XpkQuery() of packer 'BZIP': 'Can't find required XPK library'
00:E|00:00:00.000000|  YAM.c:576:error on XpkQuery() of packer 'LHLB': 'Can't find required XPK library'
00:D|22:42:22.935884|  YAM_US.c:337:user mail dir 'YAM:'
00:D|22:42:22.935932|  YAM_US.c:343:user config file 'YAM:.config'
00:D|22:42:22.935984| YAM.c:1460:loading configuration...
00:D|22:42:22.953301|  ssl.c:1046:successfully opened AmiSSL library 4.1 (amissl_v110e.library 4.1 (13.03.2017) os4 version
)
00:D|22:42:22.966201|  ssl.c:1057:AmiSSL: seeding random number generator
00:D|22:42:22.994129|  ssl.c:1071:AmiSSL: SSL ctx timeout: 7200 s
00:D|22:42:22.994294|  ssl.c:1075:AmiSSL: CAfile = 'PROGDIR:Resources/certificates/ca-bundle.crt', CApath = 'PROGDIR:Resources/certificates'
00:D|22:42:23.126617|  ssl.c:1116:AmiSSL: successfully initialized
00:W|22:42:23.418156|      Timer.c:271:timer[10]: already stopped
00:D|22:42:23.418348|   Config.c:2895:found PGP version 2 installed in 'PGP:'
00:D|22:42:23.418505| YAM.c:1488:creating GUI...
00:D|22:42:23.419195|  DockyIcon.c:104:registering with custom Docky icon 560d9720
00:D|22:42:23.427011|  DockyIcon.c:164:registered YAM to application.library with appID: 17
00:W|22:42:23.525356|       Timer.c:271:timer[4]: already stopped
...
00:W|22:42:24.861380|     Timer.c:271:timer[4]: already stopped
00:D|22:42:25.192803| Logfile.c:83:logging id 0, text 'YAM gestartet' to file 'PROGDIR:YAM-Feb2018.log'
00:D|22:42:25.194837|   DockyIcon.c:223:set custom Docky icon 3 560d9cc0
00:D|22:42:25.194903|   DockyIcon.c:242:Docky icon changed
00:D|22:42:25.194953| YAM.c:2046:user 'John Doe' differs from '' of the last start, performing startup actions
00:W|22:42:25.195118|     Timer.c:271:timer[8]: already stopped
00:D|22:42:25.195214|   Connection.c:466:got socket interface
00:D|22:42:25.195261|   Connection.c:472:set break mask
00:D|22:42:25.195307|  Connection.c:720:identified bsdsocket v4 TCP/IP stack (RoadShow)
00:D|22:42:25.195704|    Connection.c:1283:disconnecting TCP/IP session 4ffd2418
00:D|22:42:25.195990|  Connection.c:810:found the TCP/IP stack to be ONLINE
00:D|22:42:25.196062| Logfile.c:83:logging id 1, text 'Angemeldet als Benutzer '%s'' to file 'PROGDIR:YAM-Feb2018.log'
00:D|22:42:25.210353|YAM.c:2679:YAM allocated signals:
00:D|22:42:25.210398|YAM.c:2680: timerSig          = 02000000
00:D|22:42:25.210444|YAM.c:2681: rexxSig           = 00100000
00:D|22:42:25.210489|YAM.c:2682: appSig            = 01000000
00:D|22:42:25.210535|YAM.c:2683: applibSig         = 00400000
00:D|22:42:25.210580|YAM.c:2684: writeWinNotifySig = 00800000
00:D|22:42:25.210625|YAM.c:2685: threadSig         = 40000000
00:D|22:42:25.210670|YAM.c:2686: wakeupSig         = 00004000
00:D|22:42:25.210716|YAM.c:2687: methodStackSig    = 80000000
00:W|22:42:25.210930|    Timer.c:271:timer[5]: already stopped
00:W|22:42:28.380369| Timer.c:906:timer event received but no timer was processed!!!
01:D|22:42:28.380467|    Connection.c:466:got socket interface
01:D|22:42:28.380554|    Connection.c:472:set break mask
01:D|22:42:28.380634|    Connection.c:720:identified bsdsocket v4 TCP/IP stack (RoadShow)
01:D|22:42:28.381120|    Connection.c:810:found the TCP/IP stack to be ONLINE
01:D|22:42:28.384971|    Connection.c:1034:connecting to host 'update.yam.ch' port 80
01:D|22:42:28.386282|     Connection.c:882:Host 'update.yam.ch':
01:D|22:42:28.386371|     Connection.c:883:  Officially: 'update.yam.ch'
01:D|22:42:28.386464|     Connection.c:888:  Type: 'AF_INET'
01:D|22:42:28.386549|     Connection.c:892:  Address: '81.169.168.23'
01:D|22:42:28.386760|    Connection.c:1059:host 'update.yam.ch', successfully set socket to non-blocking I/O
01:D|22:42:28.386893|     Connection.c:255:set options
01:D|22:42:28.386968|     Connection.c:387:opened socket 00000000
01:D|22:42:28.387056|     Connection.c:393:SO_KEEPALIVE..: 0 [bool]
01:D|22:42:28.387146|     Connection.c:397:TCP_NODELAY...: 0 [bool]
01:D|22:42:28.387237|     Connection.c:401:IPTOS_LOWDELAY: 0 [bool]
01:D|22:42:28.387327|     Connection.c:405:SO_SNDBUF.....: 32768 bytes
01:D|22:42:28.387420|     Connection.c:409:SO_RCVBUF.....: 65536 bytes
01:D|22:42:28.387514|     Connection.c:413:SO_SNDLOWAT...: 2048 bytes
01:D|22:42:28.387605|     Connection.c:417:SO_RCVLOWAT...: 1 bytes
01:D|22:42:28.387694|     Connection.c:421:SO_SNDTIMEO...: 0.0 s
01:D|22:42:28.387781|     Connection.c:425:SO_RCVTIMEO...: 0.0 s
01:D|22:42:28.387874|    Connection.c:1073:trying TCP/IP connection to host 'update.yam.ch' with IP 81.169.168.23 on port 80
01:D|22:42:28.407412|    Connection.c:1126:host 'update.yam.ch', WaitSelect() succeeded
01:D|22:42:28.408221|    Connection.c:1263:connection to 'update.yam.ch:80' succeeded
Host: update.yam.ch2|   http.c:314:tc->requestResponse = 0x4ffd3b91 "GET /?ver=YAM%202%2E10%2Ddev%20%5BOS4%2FPPC%2C%20a63a202d%2C%20GCC%205%2E4%2E0%5D&buildid=20180116&builddate=16%2E01%2E2018&lang=deutsch%2010%2E47&exec=53%2E97&lib0=codesets-6%2E20&lib1=amissl-4%2E1&lib2=xpk-5%2E2&lib3=openurl-7%2E17&mui=21%2E110&mcc0=thebar-26%2E19&mcc1=texteditor-15%2E50&mcc2=betterstring-11%2E32&mcc3=nlist-20%2E143&mcc4=nlistview-19%2E98&mcc5=nfloattext-19%2E79&mcc6=nlisttree-18%2E50&mcc7=nbalance-15%2E24 HTTP/1.0
User-Agent: YAM/2.10-dev (AmigaOS4; PPC; rv:20180116-a63a202d)
Connection: close
Accept: */*

"
00:D|22:42:28.410565|    DockyIcon.c:223:set custom Docky icon 0 560d9450
00:D|22:42:28.410630|    DockyIcon.c:242:Docky icon changed
01:D|22:42:28.413061|     Connection.c:2134:TCP: sent 558 of 558 bytes (1)
01:R|22:42:28.452275|   http.c:329:tc->requestResponse = 0x4ffd3b91 "HTTP/1.1 200 OK
"
01:R|22:42:28.452412|    http.c:83:tc->requestResponse = 0x4ffd3b91 "Server: nginx/1.13.8
"
01:R|22:42:28.452543|    http.c:83:tc->requestResponse = 0x4ffd3b91 "Date: Tue, 13 Feb 2018 21:42:28 GMT
"
01:R|22:42:28.452690|    http.c:83:tc->requestResponse = 0x4ffd3b91 "Content-Type: text/html; charset=UTF-8
"
01:D|22:42:28.452830|    http.c:95:using line based content receive function
01:R|22:42:28.452933|    http.c:83:tc->requestResponse = 0x4ffd3b91 "Connection: close
"
01:R|22:42:28.453059|    http.c:83:tc->requestResponse = 0x4ffd3b91 "X-Powered-By: PHP/7.1.13
"
01:R|22:42:28.453189|    http.c:83:tc->requestResponse = 0x4ffd3b91 "X-Frame-Options: SAMEORIGIN
"
01:R|22:42:28.453326|    http.c:83:tc->requestResponse = 0x4ffd3b91 "X-Content-Type-Options: nosniff
"
01:R|22:42:28.453465|    http.c:83:tc->requestResponse = 0x4ffd3b91 "X-XSS-Protection: 1; mode=block
"
01:R|22:42:28.453593|    http.c:83:tc->requestResponse = 0x4ffd3b91 "
"
01:C|22:42:28.453687|   http.c:126:tc->contentLength = 0, 0x00000000
01:D|22:42:28.453793|   Connection.c:1283:disconnecting TCP/IP session 4ffd4260
01:D|22:42:28.468964|    Connection.c:1283:disconnecting TCP/IP session 4ffd4260
00:D|22:42:28.472146|    DockyIcon.c:223:set custom Docky icon 3 560d9cc0
00:W|22:42:28.472610|    UpdateCheck.c:312:potential invalid fopen call with return (0x00000000, 0x00000001)
00:D|22:42:28.473012|      YAM_ER.c:115:added error message #1 'Kann temporäre Datei 'T:YAMt000000b7.tmp' nicht öffnen.

Überprüfen Sie die Pfadeinstellung in der Konfiguration.

(13.02.2018 22:42:28)'
00:D|22:42:28.473143|      YAM_ER.c:162:showing error message #1 'Kann temporäre Datei 'T:YAMt000000b7.tmp' nicht öffnen.

Überprüfen Sie die Pfadeinstellung in der Konfiguration.

(13.02.2018 22:42:28)'
00:W|22:42:28.579622|        Timer.c:271:timer[5]: already stopped

**Comment by tboeckel** [comment]
Here is the line, which explains its all:
01:C|22:42:28.453687| http.c:126:tc->contentLength = 0, 0x00000000

The server responds with an empty response, although the header itself looks ok, but lacks the "Content-Length" line. That's why nothing is ever written to the temporary file and hence YAM complains about a non-existing file.

The big question is now why the HTTP response is lacking the Content-Length line...

**Comment by MichaelMerkel** [comment]
confirmed!
