### ISSUE TITLE
In the New email screen, tabs to add files and options have been replaced by sections on the screen

### ISSUE THREAD

**Issue by jerseywurzel** [jens-maus/yam#668]
## Submission type
  - Feature Request

## YAM version
Amiga OS 3.9, nightly dev 15/02/18

## Used operating system
  - AmigaOS3/m68k

## Used Amiga system
[...]
Amiga A1200

## Expected behaviour you didn't see
[...]
I expected to see tabs to add files and options 

## Unexpected behaviour you saw
[...]

## Steps to reproduce the problem
[...]
The screen was divided into 3 sections which leaves a little section to write the email in. You need to scroll up or down often to re-read what you've typed. It would be good if they could be resized but they appear to be fixed

**Comment by tboeckel** [comment]
A screenshot would explain things more easily. For me everythings looks like ever. Three tabs: Message, Attachments, Options.

**Comment by jerseywurzel** [comment]
Hi Thore,

I attach a screenshot.

This behaviour has only happened recently but I do not know the cause.

I have MUI5 installed too.

Thank you.

On 26/02/2018, you wrote:
> A screenshot would explain things more easily. For me everythings looks like ever. Three
> tabs: Message, Attachments, Options.




Bye for now,
-- 
Russell

Got an e-mail today from a bored local housewife, 43, who was looking for some hot action! So I sent her my ironing. That'll keep the lazy woman busy.

weather: 
Partly Cloudy : -4.00 C, 24.80 F
Winds : East 12.66 MPH, 20.37 KPH, 11.00 Knots
 Jersey Airport (EGJJ), United Kingdom

**Comment by tboeckel** [comment]
The exact version of MUI5 would be interesting, too.

**Comment by jerseywurzel** [comment]
Hi Thore,

On 26/02/2018, you wrote:
> The exact version of MUI5 would be interesting, too.

It's MUI5, OS3, mc68020
GCC 2.95x
Version 21.110 (svnr5636)
08.01.18

Hope that helps


Bye for now,
-- 
Russell

You cannot give away kindness, it always comes back to you.

weather: 
Partly Cloudy : -1.00 C, 30.20 F
Winds : East 16.11 MPH, 25.93 KPH, 14.00 Knots
 Jersey Airport (EGJJ), United Kingdom

**Comment by tboeckel** [comment]
That MUI release works perfectly for me.
Did you have a nightly build of MUI5 installed before? And how did you install the latest stable MUI5 release? I remember that issue, but only with nightly builds of MUI5. And these nightly builds were not installed completely, but only certain modified classes were installed and hence caused problems due to internal changes.

Your screenshot is still missing. Just to make sure we are talking about the same issue...

**Comment by jerseywurzel** [comment]
Hi Thore,

On 27/02/2018, you wrote:
> That MUI release works perfectly for me.
> Did you have a nightly build of MUI5 installed before? And how did you install the latest
> stable MUI5 release? I remember that issue, but only with nightly builds of MUI5. And these
> nightly builds were not installed completely, but only certain modified classes were
> installed and hence caused problems due to internal changes.

I cannot remeber exactly now, but I updated MUI 5 after downloading from Aminet, I think, in January. I don't think I had a nightly build of MUI 5 but I was testing AmiSSL with Jens early last year - I don't know if it would be coupled with that?

> Your screenshot is still missing. Just to make sure we are talking about the same issue...

Sorry, I forgot to attach it! It should be attached now and thanks for helping.


Bye for now,
-- 
Russell

**Comment by jerseywurzel** [comment]
Ok. I definitely attached it last night so obviously something is not right. I'll do as you a Great and let you know.

On 1 Mar 2018 7:24 am, Thore Böckelmann <notifications@github.com> wrote:

Still no screenshot.
Anyway, I suggest to reinstall MUI5 from scratch, just to make sure that everything is uptodate and there is no mixup of classes from different releases.

**Comment by jerseywurzel** [comment]
Hi Thore,

Ok, it was a bit of a battle but I finally managed to update MUI5 cleanly, with no leftovers from 3.8 or 4. That seemed to do the trick!

Many thanks for you help - all seems to be fine now.


On 28/02/2018, you wrote:
> Hi Thore,

> On 27/02/2018, you wrote:
>> That MUI release works perfectly for me.
>> Did you have a nightly build of MUI5 installed before? And how did you install the latest
>> stable MUI5 release? I remember that issue, but only with nightly builds of MUI5. And
>> these nightly builds were not installed completely, but only certain modified classes were
>> installed and hence caused problems due to internal changes.

> I cannot remeber exactly now, but I updated MUI 5 after downloading from Aminet, I think,
> in January. I don't think I had a nightly build of MUI 5 but I was testing AmiSSL with Jens
> early last year - I don't know if it would be coupled with that?

>> Your screenshot is still missing. Just to make sure we are talking about the same issue...

> Sorry, I forgot to attach it! It should be attached now and thanks for helping.


> Bye for now,



Bye for now,
-- 
Russell

I came.  I saw.  I stole your tagline.

weather: 
Haze : 1.00 C, 33.80 F
Winds : East 26.47 MPH, 42.60 KPH, 23.00 Knots
 Jersey Airport (EGJJ), United Kingdom
