### ISSUE TITLE
Add "reset folder" to folder popupmenu

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#67]
**Originally by _mario@cattaneo.de_ on 2010-03-04 19:23:35 +0100**

___
Could you add to the folder menu, an entry "reset" or similar, that resets the folder to the saved settings. Now if I chage a sorting order and want it to go back I switch to another folder and then go back again. :)

**Comment by tboeckel** [comment]
**Originally on 2013-02-01 08:56:21 +0100**

___
Having thought about this I came to the conclusion that this might be a desirable feature. Additionally it is almost a "no-brainer" as we have all the required stuff already.

Note for the possible implementation:
  FO_LoadConfig(folder);
  MA_ChangeFolder(NULL, TRUE);

These two lines should do the trick already, apart from adding the required menu entries.

**Comment by tboeckel** [comment]
**Originally on 2013-02-01 10:08:22 +0100**

___
Ok, I just had another thought plus a discussion with Jens and we came to the conclusion that an additional menu item for this purpose makes no real sense.

If the folder settings are changed in the settings window then these changes are permanent, hence there is no way to restore anything.

If just the folder's sort order is changed, then this can easily be undone by changing to another folder and back again. The former sort order will then be restored automatically. Thus there is no need for a menu item as requested.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2013-02-05 15:47:56 +0100**

___
How about if double clicking the folder when "open prefs on double click" is not set would do this kind of refreshing.
This would feel "intuitive", I guess.

**Comment by jens-maus** [comment]
**Originally on 2013-02-05 17:55:14 +0100**

___
No, I am sorry, but this doesn't feel intuitive. Doubleclicking should open something and not refresh something IMHO. So I think changing folders should really be enough.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2013-02-05 18:28:01 +0100**

___
Well, of course I am not against the "double click to open" operation, this makes perfect sense.
I am speaking about the case where the folder is already open/active.
In that case a double click could be some kind of "reopening", ie. refresh/reset the display to the sorting orders set.
