### ISSUE TITLE
yam complains that amissl 4.2 is not installed

### ISSUE THREAD

**Issue by rmsyam** [jens-maus/yam#675]
## Submission type
  - Bug reportt

## YAM version
[nightly build YAM210dev-20190219-MorphOS.lha ]

## Used operating system

  - MorphOS/PPC

## Used Amiga system
[...]

## Expected behaviour you didn't see
[...]

## Unexpected behaviour you saw
[SSL connections are not possible anymore even though AmiSSL 4.2 is correctly installed]

## Steps to reproduce the problem
[...]

**Comment by jens-maus** [comment]
@rmsyam Have you checked using `version` command that the `libs:amisslmaster.library` as well as libs:amissl/amissl_v110g.library` really return `4.2` as the version code? Please show output and also show a screenshot of the error message YAM displays.

**Comment by jens-maus** [comment]
Should be fixed with latest nightly build and AmiSSL 4.3 released.
