### ISSUE TITLE
Foldergroup statistics please

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#68]
**Originally by _stevebow@users.sourceforge.net_ on 2010-03-04 19:27:55 +0100**

___
Each time I download messages I have to hunt through my entire folder hierarchy to locate which folders contain new messages, which gets rather tedious at times.

Would it be possible to have Group statistics (esp. new messages) display totals for its child folders/groups please.

**Comment by tboeckel** [comment]
**Originally on 2010-09-03 13:09:35 +0200**

___
Before I start implementing this feature I have some questions about how far these statistics are supposed to go.

1. Optional?
2. If optional, on a per-group basis or as a global option for all groups?

The statistics would be the same as for the folders and hence the information displayed would be the same.

Opinions?

**Comment by tboeckel** [comment]
**Originally on 2010-09-06 09:17:54 +0200**

___
In (fe920a0):
 * mui/MailFolderListtree.c: folder groups will now show the number of new and
  unread mails after their name, just like it is done for normal folders. This
  closes #68.
