### ISSUE TITLE
Yam 2.9p1 installer bug

### ISSUE THREAD

**Issue by Jonson26** [jens-maus/yam#684]
## Submission type
  - Bug report
  - In the 2.9p1 distribution, there is a bug in the installer script on line 124: instead of a "w" there is a " ". Because of this, the installation fails if the polish locale is turned on. Replacing the letter in a text editor fixes the problem.

## YAM version
[...]

## Used operating system
  - AmigaOS3/m68k
  - AmigaOS4/PPC
  - MorphOS/PPC
  - AROS

## Used Amiga system
[...]

## Expected behaviour you didn't see
[...]

## Unexpected behaviour you saw
[...]

## Steps to reproduce the problem
[...]

**Comment by jens-maus** [comment]
This bug is already fixed in the nightly builds, thus will be fixed in a new YAM version to be released at some time. See:
https://github.com/jens-maus/yam/blob/master/dist/common/YAM/Install/Install-YAM#L130
