### ISSUE TITLE
[FEATURE REQUEST] / [QUESTION] TLS 1.2 support

### ISSUE THREAD

**Issue by tenleftfingers** [jens-maus/yam#690]
I'm using YAM 2.9p1 on m68k 020 @28MHz.

POP connection to Zoho mail fails because "couldn't initialize TLSv1/SSLv3 session with host...".

They are using TLS 1.2. Is that the problem?

**Comment by Jonson26** [comment]
If you use one of the 2.10 nightly builds, you will be able to use the newest AmiSSL with it. This should give you the ability to connect to those servers. (I know that it says these builds are unstable, but personally I've had far less problems with them than with 2.9p1 during the short timespan in which I used it.)

**Comment by tenleftfingers** [comment]
Ah, that's great news - thanks for letting me know about that!
