### ISSUE TITLE
recovering autosave.txt to clips:0

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#71]
**Originally by _anonymous_ on 2010-03-04 20:13:23 +0100**

___
Should the autosave0.txt file be there when yam is started, could another button offer to write its content to the clipboard?

That way, when the crash happened during a reply rather than a new message it's easier to select the message that was being replied to, click reply, select all and paste the text over it.

**Comment by tboeckel** [comment]
**Originally on 2012-07-25 12:23:04 +0200**

___
Refer to #276. The new Drafts folder should be superior to the old autosaveX.txt files.
