### ISSUE TITLE
Allow permanent dismissal of "Developer Snapshot Warning" dialog for nightly build on startup

### ISSUE THREAD

**Issue by tenleftfingers** [jens-maus/yam#716]
## Submission type
Feature Request

## YAM version
2.10DEV-20220710

## Used operating system
AmigaOS3.14/m68k 
 
## Used Amiga system
OS 3.14

## Expected behaviour you didn't see
An option either on the dialog itself or in the YAM settings to disable the warning permanently.
Now that I am using the DEV version, I hope to submit detailed reports. But I regularly launch YAM and forget that it doesn't load until the warning is dismissed. So I have to wait yet again. It gets frustrating for someone who closes the application or reboots a lot : )

## Unexpected behaviour you saw
The same notification every time I launch YAM.

## Steps to reproduce the problem
Launch YAM 2.10 DEV night build and observe notice.

# SUGGESTIONS # 
Some alternatives:
Make the message part of the splash screen so it doesn't block the app from loading. 
Include another button with [Go on] [Visit homepage] [Exit] which says [Don't remind me]
Include an option in YAM settings (maybe a dev specific section?) where this can be disabled completely.

**Comment by javierdlr** [comment]
What if you set "I_KNOW_YAM_IS_UNDER_DEVELOPMENT" to 1 and save to ENVARC/ENV?

**Comment by tenleftfingers** [comment]
@javierdlr, thanks. That works. I did not see it in the docs.
