### ISSUE TITLE
Add underline-feature for URL in readwin

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#72]
**Originally by _mario@cattaneo.de_ on 2010-03-04 20:14:58 +0100**

___
As browsers tend to underline links it would be nice if YAM could do this, too. So could you add "underline URL" in the prefs, where the color can be set for URLs. Guess it's not that hard and it can man the users look more consitent. Thanks. :)

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 07:43:14 +0200**

___
In (d2f85da):
 * ParseEmail.l: all kinds of links (http(s), ftp, etc) will now be underlined as well. This closes #72.

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 11:44:05 +0200**

___
**Release Note:**
All kinds of links (http(s), ftp, etc) will now be underlined as well.
