### ISSUE TITLE
Support multiple attachments d&d

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#73]
**Originally by _mario@cattaneo.de_ on 2010-03-04 20:17:06 +0100**

___
Right now you can click and activate every attachment file of a mail, and they all they visually selected. But when you d&d on the last selected file is extracted. In the meantime, as it might take longer till multiple d&d works, just avoid multiselecttion and remove the active state for an icon as soon as a new attachment icon is clicked.

**Comment by tboeckel** [comment]
**Originally on 2014-05-07 08:56:19 +0200**

___
In (1814197):
* mui/Attachment.c, mui/AttachmentGroup.c, mui/AttachmentImage.c: implemented Drag'n'Drop for multiple selected attachments. Please note that there is no visual feedback yet if one or multiple attachments are dragged. The drag image will be the one of the attachment which started the DnD action. This closes #73.
