### ISSUE TITLE
Adapt default order of next mail to reversed display

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#76]
**Originally by _mario@cattaneo.de_ on 2010-03-04 20:22:57 +0100**

___
I'd call this a bug, but as you probably say it's a feature, I am good boy and write a _request_. So, feel free to postpone it. ;)

When I have read-window open and delete the displayed mail, the content, by default will be replaced with the one of the mail below. As I use reversed order for date, I'd like this to be reversed, too. So, the next to the top is selected.

I know I can change the order by opening the mail below the one I want to delete, then do <-, then delete. Then the step is reversed and YAM moves up.

My problem is the step in the first place, ie. the default for the first delete operation.

Hope I could make myself clear. :)

**Comment by jens-maus** [comment]
**Originally on 2013-02-03 15:07:32 +0100**

___
Yes, I think you made yourself clear. What you want is:

The first delete operation should check the current sorting option and if it is, e.g., from bottom to top you want the 1. delete operation to also perform like this and select the next mail to the top after the deletion. Pretty clear and makes sense IMHO. Thus we will postpone that for a future release.

**Comment by tboeckel** [comment]
**Originally on 2013-10-14 08:55:14 +0200**

___
I know it is a long time since this ticket was opened, but I need some further information to implement this enhancement properly.

Are you referring to separate read windows here or are you using the embedded read pane in the main window? I ask, because currently there is a special handling of the next to be shown mail for the separate read window only.

**Comment by tboeckel** [comment]
**Originally on 2013-10-14 08:57:48 +0200**

___
In (9b97eb8):
 * mui/ReadWindow.c: determine the next to be shown mail after deleting/moving the current one on basis of the current sort order instead of the direction of the last navigational movement within the folder. This refs #76.

**Comment by tboeckel** [comment]
**Originally on 2013-10-14 10:13:16 +0200**

___
In (63255c2):
 * mui/MainMailList.c, mui/ReadWindow.c: use the folder's current sort order to determine the next to be shown mail instead of the configured order. This refs #76.

**Comment by tboeckel** [comment]
**Originally on 2013-10-14 15:24:57 +0200**

___
In (6585d93):
 * YAM_MA.c, mui/ReadWindow.c, mui/MainMailList.c: deleting or archiving a single mail will now behave consistently in every situation and correctly respect the folder's current sort order. This closes #76.

**Comment by jens-maus** [comment]
**Originally on 2013-12-23 22:26:22 +0100**

___
**Release Note:**
deleting or archiving a single mail will now behave consistently in every situation and correctly respect the folder's current sort order.
