### ISSUE TITLE
Don't keep "check for update" silent

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#80]
**Originally by _mario@cattaneo.de_ on 2010-03-04 20:29:11 +0100**

___
When one performs and update check via main menu, and there is no update available, then YAM just keeps silent. Think there should be some kind of info, that there is no update available. Maybe in YAMs main status line, at the bottom?

**Comment by tboeckel** [comment]
**Originally on 2010-07-29 14:52:35 +0200**

___
In (bd84a0c):
 * UpdateCheck.c, YAM_MA.c: an update checktriggered by the user but without
  any new updates will no longer be quiet but instead inform the user. This
  closes #80.
