### ISSUE TITLE
Enable filter to search header fields in mail parts too

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#82]
**Originally by _coldhoff@swipnet.se_ on 2010-03-04 20:38:36 +0100**

___
It would be useful if the filter search in header fields could (perhaps optionally) include all such fields, i.e., also the Content-Type fields in mail parts. I understand that this could slow down the search considerably for emails with large (e.g. HTML) parts, and that it might be somewhat unlogical to lump all the fields together, but from a users point of view, I think that all header fields are perceived as equal, so they should be included.

Scanning the mail file to find these header fields to be appended to the main header is made easier by the fact that one only has to find the beginning "--" of the boundary delimiters of each part to locate the "sub"-headers.

**Comment by tboeckel** [comment]
**Originally on 2012-07-25 12:26:41 +0200**

___
Searching in custom header lines is possible with YAM 2.7 already.
