### ISSUE TITLE
[remote] filter(s) on desired account(s) only

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#83]
**Originally by _diegocr@users.sourceforge.net_ on 2010-03-04 20:40:51 +0100**

___
The situation, I have configured in YAM 6 email accounts, and just for one I've set a remote filter, it is a bit annoying that remote filter is checked on all accounts while it is not needed, action which slow down a lot receiving mails (for all my accounts)

Hence, is there any chance on getting a new filter option to set the email account where that remote filter check should be perfomed, please?

**Comment by jens-maus** [comment]
**Originally by _amigalex@users.sourceforge.net_ on 2010-03-04 20:41:38 +0100**

___
I concur, same issue here.

**Comment by tboeckel** [comment]
**Originally on 2011-01-01 15:21:57 +0100**

___
In (8447bb2):
 * misc: applying the remote filters is now optional for each POP3 account.
  This saves possible issues when remote filters are meant for certain
  accounts only, but were applied for all accounts. This closes #83.
