### ISSUE TITLE
Add TO: field column in mail transfer window

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#84]
**Originally by _amigalex@users.sourceforge.net_ on 2010-03-04 20:42:58 +0100**

___
To facilitate deleting spam messages off the server without having to download it first only to find out that it was spam with the recipient in the BCC: field, it would help to see the TO: field in the mail transfer (download) window.

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 07:44:53 +0200**

___
In (173bf8e):
 * TransferMaillist.c: the mail preselection list now shows the contents of the To: header line to let users spot unwanted mails easier. This closes #84.

**Comment by tboeckel** [comment]
**Originally on 2013-07-08 11:44:27 +0200**

___
**Release Note:**
The mail preselection list now shows the contents of the To: header line to let users spot unwanted mails easier.
