### ISSUE TITLE
crop single files

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#85]
**Originally by _antibike@users.sourceforge.net_ on 2010-03-04 20:45:54 +0100**

___
crop all files is a good thing, but sometimes i only want to crop a single file of some attachments. today i must use the text editor to do it.

**Comment by tboeckel** [comment]
**Originally on 2013-01-30 13:27:32 +0100**

___
This is possible already, but not from the main mail list's (context) menu. To crop single attachments the corresponding mail must be visible either in the embedded read pane or in a separate read window. Single attachments can then be deleted from the mail by choosing either "Delete", "Delete selected" or "Delete all" from context menu of the to be deleted mail part.

I think it will be better to remove the "Delete attachments" item from the main and the context menu and force the user to use the attachment list's context menu instead as this gives more precise control over which parts are really to be deleted.

**Comment by tboeckel** [comment]
**Originally on 2013-02-06 10:23:37 +0100**

___
Having discussed this issue with Jens we came to the conclusion to leave everything as it is. Deleting attachments from the main menu will delete all attachments while the read pane/read window lets the user choose single attachments for deletion. The "all or nothing" approach from the main menu is sufficient as the user has to confirm this action.
