### ISSUE TITLE
Open adressbook arexx command

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#88]
**Originally by _JDuch@fulladsl.be_ on 2010-03-04 20:52:43 +0100**

___
I am using some (gui4Cli) interfaces to YAM using its arexx ability.

I do miss a command opening the addressbook (eg after having loaded a new addressbook with ADDRLOAD

**Comment by tboeckel** [comment]
**Originally on 2013-01-15 16:02:39 +0100**

___
In (a6517d0):
 * rexx/addrload.c: extended the ADDRLOAD command to take a second parameter OPEN/S to immediately open then address book window after the address book file has been loaded successfully. This closes #88.

**Comment by jens-maus** [comment]
**Originally on 2013-07-01 21:24:42 +0200**

___
**Release Note:**
extended the ADDRLOAD command to take a second parameter OPEN/S to immediately open then address book window after the address book file has been loaded successfully.
