### ISSUE TITLE
Wrong UTF-8 Support

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#9]
**Originally by _opionline@yahoo.de_ on 2010-03-03 15:29:03 +0100**

___
Hi Develoers

I think YAM does not support the UTF-8 encoding correct.

Here is a Step by Step example:

1. Write a new Mail (Type and To and Subject).
2. Switch to the Options Tab.
3. Select UTF-8 as Charset.
4. Switch back to the Message Tab.
5. Type some non ASCII Letters (e.g. the Euro Sign and ��� ��� �).
6. Click "Hold".
7. Switch to the Outguing Folder.
8. Select the Mail you just wrote.
9. Click Read in the Toolbar.
10. Look at the Content-Type it's text/plain; charset=UTF-8 11. But in the Mail you see "? ? ???" but it should "� ��� ��� �"

The cause it that YAM does not encode the Mail to UTF-8 if you click on the "Hold" Button. If you then open the Mail for Read YAM seems to try to decode the UTF-8 Mail but can't find any UTF-8 sequence and you see the question marks.

Hope anybody can fix that...

TIA

Best Regards Frank (Opi) Weber

**Comment by tboeckel** [comment]
**Originally on 2010-03-03 15:30:06 +0100**

___
This is not really a bug, but more or less a not yet completed feature.

We introduced the modifyable character set for writing new mails recently only for the purpose to fake the character set of an outgoing mail. That means you can type you mail as usual (most probably using some kind of eastern european characters) and set the charset to something like ISO-8859-42, at least anything different than ISO-8859-1, which AmigaOS uses by default. The receiver of the mail will then be able to read the mail properly. But YAM does NO reencoding of the mail corresponding to the new charset. Only the charset information in the mail's headers will be adopted.


An "quick'n'easy" fix for this issue would be to exclude UTF8 from the list of charsets for writing mails. The complete fix would be to make YAM *and* TE.mcc able to handle arbitrary charsets, or even better completely switch to UTF8 internally.

**Comment by jens-maus** [comment]
**Originally on 2013-08-18 01:59:59 +0200**

___
In [6877]) * mui/WriteWindow.c: change SaveToFile uses to actually convert the entered
  text to the target charset selected in the write window. This should fix
  problems when trying to generate/send UTF8 encoded mails as they were
  written to the temp file of the write window with the read encoding always.
  Now YAM will compare the configured read and write charset and if they are
  different a charset conversion via SaveToFile will be performed. This
  hopefully fix a long standing bug and closes #9.
* mui/MailTextEdit.c: added charset conversion functionality to LoadFromFile
  and SaveToFile methods which will allow to save the currently displayed
  mail text in a specific target charset.

**Comment by tboeckel** [comment]
**Originally on 2013-09-25 10:11:43 +0200**

___
In (10655ef):
 * YAM_WR.c, mui/WriteWindow.c: all header lines are encoded using the configured or dynamically set write charset. This finally makes it possible to compose proper UTF8 encoded mails and refs #9.

**Comment by jens-maus** [comment]
**Originally on 2013-12-22 19:00:37 +0100**

___
**Release Note:**
fixed a problem where YAM was unable to create properly UTF-8 encoded emails.
