### ISSUE TITLE
Debug Output without private Data

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#90]
**Originally by _opionline@yahoo.de_ on 2010-03-04 20:56:03 +0100**

___
I think it's a good idea to introduce a debuglevel which doesn't print private Data (e.g. Mailadresses, Passwords) in Debug reports, because i do not want to spread my private datas if i post a bugreport.

**Comment by jens-maus** [comment]
**Originally on 2010-03-06 07:22:53 +0100**

___
I understand your reasoning, but I think we already changed something about that some time ago. Thore? any more information on that?

Not a separate debug option, but we did something to not expose that critical information per default. So in case you still see some private data exposed which should not be in the standard debug output please bring up each case here separately and point your finger at it.

**Comment by jens-maus** [comment]
**Originally by _Opi_ on 2010-03-06 16:40:44 +0100**

___
IIRC here was a change which doesn't show a passwort in plain text
but IMHO all E-Mail adresses should also not displayed in such
bugreport because they may be available for public in the www.
So replace all characters after a '@' until the next whitespace
should fulfill this request.

**Comment by tboeckel** [comment]
**Originally on 2010-03-09 10:05:05 +0100**

___
I changed the debug output to change passwords into "XXXX". Other stuff like mail addresses, real names, etc are still printed as they are.

**Comment by jens-maus** [comment]
**Originally on 2010-03-09 11:04:59 +0100**

___
Ok, I also think it would make the debugging a lot more complex if we would have to identify all situations where email adresses are output. The current solution with prevent at least the output of passwords should be enough IMHO. Therefore I am closing this ticket.
