### ISSUE TITLE
open folders in tree automatically

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#92]
**Originally by _Michael.Merkel@gmx.net_ on 2010-03-04 21:40:28 +0100**

___
related to my previous one. i don't know if this is technically possible at all. but i'd like it :-) it is actually used to be used in other os' like windows.

imagine the following: you want to move a message into a folder which is inside a folder group which is closed

it would now be nice if you could drag the message over the closed folder group and wat for one second. then the folder group opens automatically. then you can drag it to the real target folder inside that group. this would be very user frindely if you ask me ;-)

**Comment by tboeckel** [comment]
**Originally on 2010-03-11 20:59:12 +0100**

___
This will be possible with the next NList release and the next MUI3.9 release for OS4.1. Additionally this requires a hi/truecolor screen and compositing enabled.

Yes, I know, these are quite heavy requirements, but currently every drag'n'drop operation requires the screen to be locked to prevent other applications from drawing their own stuff. On the other hand automatically opened nodes may require large updates of the window containing the NListtree object which would interfere with the locking done before and hence cause deadlocks.

Compositing makes it possible to perform drag'n'drop operations without any locking and thus is it possible to do exactly what you want.
