### ISSUE TITLE
Remove "mailto:" from "to:"-strings

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#93]
**Originally by _mario@cattaneo.de_ on 2010-03-04 21:42:44 +0100**

___
Thought I filed this already, but can't find it... Would be nice, this way, e.g. copying a URL from a browser could be pasted to YAM without any cut-operations by the user. Would be handy... I think. :)

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-06-10 15:31:46 +0200**

___
Hi,

just got a Mail from my "PC-granny" ;) and it contained, mail addresses in the style name <mailto:address>.
Don't know if this is PC style, but in this case an "auto-strip" of YAM would be very cool, too. :)

**Comment by tboeckel** [comment]
**Originally on 2010-06-10 16:24:15 +0200**

___
Could you provide an example mail please? Jens and me don't know what you are talking about.

And where is the connection to the initial request at all?

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-06-10 17:11:13 +0200**

___
Well, the mail was nothing special... She just wrote, something like:

Here are the email-addresses you requested.

She then used some prg/tool (whatever) to paste/add them to the mail body.
They ended up as

Your name <mailto:name@add.net>

If YAM, would filter, as in my request, I could easily mark the whole line, copy it to "TO:" and forget about it.
ATM I have to strip the mailto: by hand.
That's the connection.

As she used a PC/Win this is probably some typical thing how addresses can end up in a mail. So I thought, it would be nice if YAM could cope with this...

**Comment by tboeckel** [comment]
**Originally on 2010-06-10 20:40:24 +0200**

___
No. From my point of view automatically removing text from a mail is no option. What if you definitely want to include such strings in your mails and YAM just removes them silently? It would be impossible to keep these strings. Furthermore where do we start to remove stuff and where do we end? As you suggest only the "mailto:" part should be removed, but what if the complete address looks like "<mailto:foobar>"? You would end up with "<foobar>", which is even worse.

If someone includes them in the mail body it may look ugly for other people. But nobody knows if these strings were included by accident or by intention, no matter which OS was used to compose the mail, so better leave them in.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-06-10 20:50:32 +0200**

___
You missunderstood me...

I am not speaking about the mail body. :(

I am Speaking about the To: string when composing a message. It wouldn harm to strip a mailto: there when generating the mails.
E.g. Subject strips "RE:" to.

**Comment by jens-maus** [comment]
**Originally on 2010-06-10 23:23:10 +0200**

___
Ok, I think I know now what you mean Mario (unfortunately your reports are often confusing at a first sight).

You mean that when you have the text "mailto:test@test.de" in your copybuffer and you press "Amiga+V" in the recipientstring you want to have "mailto:" stripped from the text. Right? Of course this would be possible, however the valid question have to be asked why you don't simply double-click on the mailto: link so that YAM opens a new write window for you with already having the "mailto:" stripped? And another question is why you not simply only select the mail address if you are anyway at the job in selecting text in the read window?

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-06-11 02:23:09 +0200**

___
Well, it does hot need to be a "real time" stripping on paste. To me, it would be enough if the stripping happens when you press send, hold, later...
Cause at that point a to: with "mailto:" is not valid.

To bw honest, I don't know all about this... But I remeber, that "back" then, it happend quite often to me, that I ended up with a "mailto:" in the string gadget.
Maybe OpenURL was not there, or badly configured whatever.

I don't think that it is about clicking urls put copying them "from the outside world", ie. not in a mail, but in some readme, textdoc, etc.

This mail I just mentioned was just another case where it could be usefull, cause I wanted to have the realname in the to: string to, so a double click was no option, as it would have only passed the mailaddress.
And when I copy the complete string, then I have to eiterh copy it in two parts or remove the "mailto:" by hand afterwards.

Hope I could make myself clear.

Sorry, if my English is not that good, but I am getting older, more confused and my English skills fade more and more...

**Comment by tboeckel** [comment]
**Originally on 2010-06-11 11:04:55 +0200**

___
In (7d6b90c):
 * mui/Recipientstring.c: a possible "mailto:" header in front of an address
  will now be stripped upon resolving the complete string. This closes #93.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2010-06-12 14:08:06 +0200**

___
First of all, thanks.

But could you improve it? Cause atm it only works for

mailto:test@doma.in

but not for

<mailto:test@doma.in>
Me <mailto:test@doma.in>
"M E" <mailto:test@doma.in>

**Comment by tboeckel** [comment]
**Originally on 2010-06-13 20:02:04 +0200**

___
If this is going to be implemented it won't be done by me. From my point of view there must be a limit somewhere. You cannot expect to paste arbitrary "crap" and let YAM convert it to exactly what you expect. Especially the last two examples look very broken and not RFC conformant to me. Maybe Jens knows better. As last instance your SMTP server should reject utterly broken addresses before accepting them.

Being able to paste arbitrary text gives you lots of freedom on the one hand, but on the other hand it requires some responsibility from you to paste only those parts which belong to a valid email address. As I already stated before you want to be able to type what ever you want without any interpretation or modification by YAM. If you paste or type crappy addresses you will have to live with that. Period.
