### ISSUE TITLE
Add "Abort" toolbar-button to stop filtering in progress

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#94]
**Originally by _amigalex@users.sourceforge.net_ on 2010-03-04 21:44:17 +0100**

___
In some case it is desirable to abort filtering, like when a filter wasn't set right and starts moving 1000's of messages to another folder...

**Comment by tboeckel** [comment]
**Originally on 2010-03-04 21:45:46 +0100**

___
This already possible for some time with the nightly builds. While filtering is in progress you get a progress bar in the status bar with an "X" button on the right side. Just press the "X" to abort the filter process. Of course that requires the status/info bar to be active. If haven't done so, then please activate it in the config window on the Look&Feel page.

**Comment by jens-maus** [comment]
**Originally by _amigalex_ on 2010-03-04 21:46:47 +0100**

___
Actually I disabled it on purpose...

I like the GUI clean and simple, the same way it was with 2.3p, so I don't use the status bar, preview pane, and search field. (see atachment) Besides, I already have the selected folder and unread/total messages info from the list on the left...

An alternative would be to open a progress window with just the gauge gadget and "stop" button if A: the status bar is disabled, and B: the total number of messages to be filtered is over a certain treshold. There's probably no point in opening a progress window for less than 20 messages as it would finish too fast to read or react.

**Comment by jens-maus** [comment]
**Originally by _amigalex_ on 2010-03-04 21:47:47 +0100**

___
**Attachment added:** `02h13m36s.png` (83.7 KiB)
![02h13m36s.png](https://yam.ch/attachments/94/02h13m36s.png)
yam gui snapshot - Moved from SF. Original author: amigalex

**Comment by jens-maus** [comment]
**Originally on 2010-03-04 21:48:33 +0100**

___
IMHO an additional progress window will be too much. However, we already have plans to add a dynamic "Stop" toolbar button as soon as there is something to abort. Unfortunately this have to wait until we start working on YAM 2.6. Until that happens you might want to turn the status bar back on as otherwise you won't have any chance to abort e.g. the filtering, I am afraid.

**Comment by jens-maus** [comment]
**Originally on 2013-01-14 23:44:19 +0100**

___
duplicate of #134
